### ISSUE TITLE
Document context keys usable for menu visibility

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-docs#1000]
There's a context called `resourceFilename` which can be used for showing/hiding commands in the command palette but as far as I can tell there isn't a complete list. I tried searching this repo for `resourceFilename` and the only instance is in the release notes when it was added. I did find a `keybindings.md` file that had a bunch of them in, but didn't seem to include this.

If it does already exist and I overlooked it, apologies, and I'd appreciate the link :-)

**Comment by gregvanl** [comment]
Issue #1000. The repo is growing up. Thanks!
