### ISSUE TITLE
Add docs on how to test debug adapters in a CI environment

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-docs#101]
In the mock-debug adapter for example is a test folder included with a dummy mocha test. But how can one _actually_ test VS Code extensions and debug adapters? Especially with something like Travis CI.

**Comment by felixfbecker** [comment]
I saw that there is some documentation on testing normal extensions, but nothing about debug adapters. @weinand some help maybe? Testing all possible constellations manually on all OS is a pain. I had some thoughts on [this issue](https://github.com/felixfbecker/vscode-php-debug/issues/7)

**Comment by weinand** [comment]
@felixfbecker A test suite for debug adapters is in the works. Please see the January iteration plan: https://github.com/Microsoft/vscode/issues/1826

**Comment by weinand** [comment]
@felixfbecker you can find a first version of the test suite here: https://github.com/Microsoft/vscode-node-debug/blob/master/src/tests 

The DebugClient.ts defines the API and will be moved (together with ProtocolClient.ts) into the npm module soon. adapter.test.ts contains a first batch of tests. More to come...

**Comment by felixfbecker** [comment]
@weinand This looks very promising, when will it get included in the NPM package?

**Comment by weinand** [comment]
@felixfbecker soon, I hope. Need to find some time to write more tests to exercise the API....

**Comment by gregvanl** [comment]
This issue has been very quiet and looks like @felixfbecker is happy with the tests added to the vscode-node-debug repo. Closing
