### ISSUE TITLE
Improve Using Newer TypeScript Version Section

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-docs#1021]
From https://github.com/Microsoft/vscode/issues/27826

This section of the TypeScript docs needs additional attention. It should better explain what the global and  VSCode versions of TypeScript are used for and how to fix the error

**Comment by gregvanl** [comment]
Also call out that users need to install the TypeScript compiler separately (verbatim)
Make sure to include ctrl+space for IntelliSense in tsconfig.json (verbatim)

**Comment by gregvanl** [comment]
This message will be removed in the 1.15 release. Updating the TypeScript topic on vnext
