### ISSUE TITLE
Gifs and images in the intellisense.md need an update for 1.13 release

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-docs#1030]
https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/intellisense.md has gifs and images that need to be updated for 1.13 release

Specifically:
- [x] https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/images/intellisense/intellisense.gif
- [x] https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/images/intellisense/intellisense_packagejson.gif
- [x] https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/images/intellisense/quick_outline.png

**Comment by ramya-rao-a** [comment]
cc @gregvanl

**Comment by ramya-rao-a** [comment]
@waderyan You can either re-use the gifs I have in the release notes (https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/images/1_13/suggest.gif) or create a new one if you want to retain the code on "express"

**Comment by waderyan** [comment]
Closed with https://github.com/Microsoft/vscode-docs/commit/48d06ec43cd62d317662f305680d213d332bba98
