### ISSUE TITLE
How to close this Friendly Tips？

### ISSUE THREAD

**Issue by Eter365** [Microsoft/vscode-docs#1039]
![image](https://user-images.githubusercontent.com/5517980/27116820-e33b74d2-5105-11e7-9ea8-9f22f08b3ca1.png)

How to close this Friendly Tips？

![image](https://user-images.githubusercontent.com/5517980/27116867-0ff183e0-5106-11e7-9d2f-e90313a0f5e2.png)

**Comment by gregvanl** [comment]
Hi @Eter365, did you try the "go get" step to get the go-outline library and you still see the message?
The vscode-docs repo is for the VS Code documentation source and issues. If you still see the message after following the instructions in the tip, you can open an issue against the Go extension at https://github.com/Microsoft/vscode-go/issues. Your question seems related to https://github.com/Microsoft/vscode-go/issues/998 and indicates you are missing some required Go tools.
