### ISSUE TITLE
Windows setup tip for running from console on git bash incorrect

### ISSUE THREAD

**Issue by jskrepnek** [Microsoft/vscode-docs#105]
Hi,

I believe this used to just work - but with 10.6:

In a git bash terminal for instance, running "code ." does not work - you need to run "code.cmd ."  This is not an issue in a windows command prompt.

The docs should indicate this, since I'd guess a lot of will be in alternative terminals.

**Comment by gregvanl** [comment]
Could not reproduce this on git version 2.8.0.windows.1 with git Bash.  "code ." seems to work fine from the bash prompt.
gregvanl@GREGVANL00 MINGW64 ~/vscode-docs (vnext)
$ code .
