### ISSUE TITLE
Angular tutorial Intellisense example poor

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#1054]
Currently Intellisense is illustrated on the global `console` object, that is totally unrelated to angular (see below). The example should show intellisense on an Angular component, e.g., in code that uses the the `AppComponent` class.

![image](https://user-images.githubusercontent.com/172399/27517186-77156f8a-59c8-11e7-9f2d-20f7d14f159c.png)

**Comment by gregvanl** [comment]
Agreed, I wasn't very happy with the example.
