### ISSUE TITLE
Move "Extensions Gallery" under Customization header

### ISSUE THREAD

**Issue by wadeanderson7** [Microsoft/vscode-docs#106]
It makes more sense to me to have Extensions Gallery in customization instead of Editor. Maybe I'm in the minority...

**Comment by gregvanl** [comment]
I remember now why Sean wanted it under Editor. Editor is the first node in the docs and he wanted Extension Gallery there for easy first-time discoverability.  The Editor node is also where we put other important but general topics like Setup, The Basics and Why VS Code.
You could argue that the Customization node makes more logical sense but this requires more hunting by the first time user.  We also have an Extension Gallery topic link at the top of the Customization Overview page.

**Comment by wadeanderson7** [comment]
Makes sense.
