### ISSUE TITLE
Add Vue.js tutorial

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#1072]
Similar to React and Angular tutorials
Show
- IntelliSense and code navigation
- client side debugging

**Comment by gregvanl** [comment]
doc feedback verbatim on the Node.js tutorial: "why no vue?"

**Comment by gluons** [comment]
Oh! I come to ask for Vue tutorial. Hope it will be on vscode docs soon. 😄

**Comment by arthurbdiniz** [comment]
Hi @gregvanl, i just added the PR for vue tutorial

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/4aff14de92615d9e75894e4d2389015f6f124481
