### ISSUE TITLE
Add copyable hyperlink to each header

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#108]
Popular documentation like [reactjs](https://facebook.github.io/react/docs/getting-started.html) and [asp.net](https://docs.asp.net/en/latest/) add links to each of their headers. This is useful for referencing to a specific part of our documentation.

**Comment by gregvanl** [comment]
This is a tooling change not a doc change and already covered by vscode-website https://github.com/Microsoft/vscode-website/issues/1
