### ISSUE TITLE
Need a document on Code Navigation

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#109]
suggest to write the authoritative document on code navigation in VS Code.

https://github.com/microsoft/vscode/issues/1843

**Comment by gregvanl** [comment]
We now have a dedicated Code Navigation topic which has a leading section on Quick Open file navigation https://code.visualstudio.com/docs/editor/editingevolved#_quick-file-navigation which should answer the referenced vscode issue.

**Comment by rashidul0405** [comment]
For zen mode user, recently edit files. On jetbrains editor it's Cmd + E and extremely useful.

**Comment by rashidul0405** [comment]
I guess Cmd + P lists recent files on top.
