### ISSUE TITLE
Unable to scroll down left navigation on the docs website (Mac OS, Chrome)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-docs#1092]
On Chrome on my MacBook (2017, 12" Retina 2304x1440, all settings default) I can't scroll down to the bottom of the left nav here - scrolling moves the page content but not the nav. For the longer sections (like the one expanded) this means the links aren't all accessible. Even if I try tabbing to them, they remain off the screen and not visible.

<img width="1280" alt="screen shot 2017-07-15 at 11 45 20" src="https://user-images.githubusercontent.com/1078012/28238808-a0c44082-6953-11e7-99ae-3b6aa03c5c49.png">

**Comment by gregvanl** [comment]
@DanTup Thank you for logging this issue. It is a known problem and is already logged on our private website repo where we track issues related to rendering and website navigation. Closing this issue as it isn't related to the content directly.
