### ISSUE TITLE
Request: Provide guidance for extension icon size(s)

### ISSUE THREAD

**Issue by joelday** [Microsoft/vscode-docs#1101]
Regarding https://github.com/Microsoft/vscode-docs/blob/master/release-notes/v1_14.md#extension-authoring, now that extension developers are replacing .svg images, I'd like to know a recommended image size. Would be a bummer if the marketplace had to serve low resolution or excessively large images.

Thanks!

**Comment by gregvanl** [comment]
Recommendation is 128 x 128 pixel image.
See https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_fields
The extension package.json icon field IntelliSense also calls this out.
Feel free to reopen if you think there should be more clarification.
