### ISSUE TITLE
Update website main screenshots

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#1124]
I noticed that (for macOS at least) our screenshot of VS Code is really outdated. Mainly we do not show our nice custom window title bar:

![image](https://user-images.githubusercontent.com/900690/29207391-4b8d1c04-7e86-11e7-99c8-7954399d07ce.png)

vs:

![image](https://user-images.githubusercontent.com/900690/29207409-608c7aaa-7e86-11e7-8161-3080f0fa74ce.png)

**Comment by gregvanl** [comment]
This image is in the vscode-website repo and covered by https://github.com/Microsoft/vscode-website/issues/640
