### ISSUE TITLE
Find all references (shift+12) does not work

### ISSUE THREAD

**Issue by andyysj** [Microsoft/vscode-docs#1128]
By now I tried both stable and inside version with several Windows platform with C code, no one platform works, and I found this is very old issue reported by several guys, so what is the status and reason?

**Comment by gregvanl** [comment]
Hi @andyysj This GitHub repo is for Visual Studio Code documentation (Markdown files and issues related to their content). It sounds like you want to know the status of a product issue. You can check on or report an issue at https://github.com/Microsoft/vscode/issues.
