### ISSUE TITLE
[vscode-website] Turn off hidden animation for "Skip to content" link

### ISSUE THREAD

**Issue by gilmoreorless** [Microsoft/vscode-docs#1131]
**Note:** This issue affects the whole site, not just the docs, but I'm raising the issue here because the `vscode-website` repo is not public.

I'd noticed that my computer's CPU usage was increasing every time I was viewing a page on https://code.visualstudio.com/. After digging into it I found there's a hidden "Skip to content" link which appears when tabbing to it. This is great for accessibility, however within the link is an icon:
![image](https://user-images.githubusercontent.com/159415/29412127-d80aedb4-839a-11e7-8dd0-caa9c849eba3.png)
The icon has a 0.5 second looping animation that infinitely moves the icon up and down by 3 pixels. This animation is causing the browser to take up a non-trivial amount of CPU usage.

Given that the animated icon is only visible when the link has focus via the keyboard, and the link itself is a feature for screenreader users, is there any use in having the animation?
I'd prefer if the animation was removed, but obviously I don't have the final say. 😉

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-website#684

**Comment by gregvanl** [comment]
@gilmoreorless Thank you for creating the issue. I moved it to vscode-website and will reply back here when the issue is fixed.

**Comment by gilmoreorless** [comment]
Thanks @gregvanl!

**Comment by octref** [comment]
Thanks for pointing out. This is fixed and will be published to website soon.

**Comment by octref** [comment]
Thanks for pointing out. This is fixed and will be published to website soon.
