### ISSUE TITLE
Keyboard layout compatibility

### ISSUE THREAD

**Issue by pujiaxun** [Microsoft/vscode-docs#1148]
- VSCode Version: 1.15.1 
- OS Version: macOS Sierra 10.12.6  

I am using an simplified Chinese input method. And this seems to change the keyboard layout, which makes a few keybindings failed.

For example:

When **ABC(English)** input method:

```json
[
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "editorTextFocus && !editorReadonly"
    },
  {
        "key": "cmd+/",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
  }
]
```

When **Simplified Chinese** input method:
```json
[
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "editorTextFocus && !editorReadonly"
    }
]
```

**The `cmd+/` disappeared!**

Finally I find this:

```json
    {
        "key": "cmd+[Slash]",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
    }
```

I wonder whether I can toggle a switch to change the keybindings from `/` to `[Slash]`, from `,` to `[Comma]`, and so on?

Thank you!

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode#34174

**Comment by gregvanl** [comment]
This is a product issue not a documentation issue so moving to vscode repo.
