### ISSUE TITLE
code.visualstudio.com/blogs display

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode-docs#1149]
![1](https://user-images.githubusercontent.com/11925432/29854497-e79d05c2-8d78-11e7-93e5-56d0545c5fe7.gif)

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/7b013fb7e36375660f798045f80c2e994135837c which removes older blog posts.
Will be deployed in a day or so.
