### ISSUE TITLE
Can I contribute by translation to this project?

### ISSUE THREAD

**Issue by lv7777** [Microsoft/vscode-docs#115]
I want to translation(japanese).

**Comment by gregvanl** [comment]
Thank you for contacting us.  We're still working on our localization plans and will likely need community support.  I'll let you know when we are ready.

**Comment by egamma** [comment]
@lv7777 this the plan item for the localization work of the VS Code application microsoft/vscode#2041.

**Comment by lv7777** [comment]
thank you very much your introduce!
I'm busy this month, but I try to contribution l10n.
