### ISSUE TITLE
Indicate deprecated APIs more prominently

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docs#1150]
When going through the API reference I noticed that deprecated API is only showing up as deprecated once you expand the details of an API:

![image](https://user-images.githubusercontent.com/900690/29932278-224fcb36-8e74-11e7-88fd-d41cb6b67c8b.png)

vs.

![image](https://user-images.githubusercontent.com/900690/29932290-2a7b1fcc-8e74-11e7-9d78-3e7092ca06ad.png)

I think we should make it much more obvious that something is deprecated without having to drill into.

/cc @jrieken

**Comment by gregvanl** [comment]
No current plans to update VS Code API generation. Closing old issue
