### ISSUE TITLE
Weird extra details for enumeration values

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#1151]
I am not sure what the purpose of this is:

![image](https://user-images.githubusercontent.com/900690/29932505-c4e0c990-8e74-11e7-89b4-840199b82b43.png)

It looks like the ordinal value of the enumeration, but is that useful?

/cc @jrieken

**Comment by jrieken** [comment]
Yeah, kind of upstream as the library add the 'value' of enums into them

**Comment by gregvanl** [comment]
Would be fixed if we adopted the suggestion in #665. Close as duplicate
