### ISSUE TITLE
SCM Multirepo work is not preview

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-docs#1163]
I just saw that the SCM Multirepo work is labelled as preview.

This is incorrect. While it may relate to multiroot, this work is already in stable for everyone. You'll get multiple repositories simply by opening files from different repositories, independently of multiroot.

**Comment by gregvanl** [comment]
Oops. Fixed with https://github.com/Microsoft/vscode-docs/commit/5651c0aaab7d56baea6df46fb179905c4f4fe43d

**Comment by joaomoreno** [comment]
Thanks!
