### ISSUE TITLE
Add some links to useful extensions for the different runtimes

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#117]
For example, the vscode-docs/docs/runtimes/nodejs.md could list some extensions which are useful for node.js development, e.g.,

- [eslint](https://marketplace.visualstudio.com/items/dbaeumer.vscode-eslint)
- [vscode-jshint](https://marketplace.visualstudio.com/items/dbaeumer.jshint)
- [vscode-npm-script-runner](https://marketplace.visualstudio.com/items/eg2.vscode-npm-script)
- [EditorConfig](https://marketplace.visualstudio.com/items/chrisdias.vscodeEditorConfig)

CC @chrisdias @wadeanderson

**Comment by waderyan** [comment]
Ongoing..

**Comment by waderyan** [comment]
completed and ongoing.
