### ISSUE TITLE
auto semicolon 

### ISSUE THREAD

**Issue by jiangwenbo737** [Microsoft/vscode-docs#1173]
when I use st3，it supports inserting an semicolon at the end of the current line when I press Tab or Enter， I think it is very useful especially in SCSS，so can vscode support this ability？

**Comment by gregvanl** [comment]
Hi @jiangwenbo737, this repository is for VS Code documentation issues. I think you are making a VS Code feature suggestion and so it should go to the VS Code product repo.
I think your suggestion is https://github.com/Microsoft/vscode/issues/34141 where you can upvote it.
