### ISSUE TITLE
Transform Language Id to link

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1174]
On this page: [keybindings](https://code.visualstudio.com/docs/getstarted/keybindings) there are 2 mentions of `Language Id`:

editorLangId | True when the editor's associated `language Id` matches. Example: "editorLangId == typescript".
-- | --

resourceLangId | True when the Explorer or editor title  `language Id` matches. Example: "resourceLangId == markdown"
-- | --

I think it would be good to replace plain text with the link to [languages/identifiers](https://code.visualstudio.com/docs/languages/identifiers) or at least mention it somewhere in the page.

**Comment by gregvanl** [comment]
Great suggestion, Thanks!
