### ISSUE TITLE
can not get the function list, type list, and variable list of current open file.

### ISSUE THREAD

**Issue by qidianbuji** [Microsoft/vscode-docs#1178]
Hi, 
    when I try to use vscode to develop c/c++ running on linux, I find that, vscode cannot show me a window about the function, type, macros, variables etc of the current open or edited file. It will be a bigger limit.
    Can you help me how to solve it?
Thank you.

**Comment by gregvanl** [comment]
Hi @qidianbuji, do you have the C/C++ extension installed? Sounds like you need a language service installed to give you code intelligence.  This [C++ topic](https://code.visualstudio.com/docs/languages/cpp) may help you install the extension and understand what features it will provide.

**Comment by gregvanl** [comment]
Closing. Reopen if you think this is a documentation issue.
