### ISSUE TITLE
tasks "taskName" is deprecated, should be "label"

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#1181]
the docs for tasks refer to a property called `taskName` that doesn't exist in IntelliSense:

![image](https://user-images.githubusercontent.com/1487073/30791362-e0829da4-a17f-11e7-8162-79933eae4adf.png)

for example, here: https://code.visualstudio.com/docs/editor/tasks#_custom-tasks

it looks like `taskName` should be renamed `identifier` in the docs.

**Comment by gregvanl** [comment]
@chrisdias The default Other task template will fill in the taskName and I see taskName in IntelliSense on both 1.15.1 and Insiders.
![taskname](https://user-images.githubusercontent.com/12818376/30792931-1371c54e-a173-11e7-854b-e6c877533845.png)

**Comment by chrisdias** [comment]
//cc @dbaeumer 

i don't see this on 1.16 nor in today's insiders.   This is what I see in Stable (1.16.1 27492b6):

![image](https://user-images.githubusercontent.com/1487073/30822709-ad5bea70-a1f7-11e7-9b69-218943536c8b.png)

**Comment by gregvanl** [comment]
I mispoke above, I meant 1.16.1 (updated comment).

**Comment by chrisdias** [comment]
How are you invoking the completion list?

**Comment by gregvanl** [comment]
Ctrl+space (on Windows). I also see IntelliSense for taskName when I start typing "ta".

**Comment by chrisdias** [comment]
hmmm... with the object empty, press CTRL+Space, get this:

![image](https://user-images.githubusercontent.com/1487073/30823024-ed7c45a4-a1f8-11e7-9f8f-ea92cee23e6c.png)

Now, put in quotes:

![image](https://user-images.githubusercontent.com/1487073/30823134-3b95ce04-a1f9-11e7-90da-e0b7af4634a6.png)

Note, `type` is not in completion list.

put in `type`, no error and no completion for it:

![image](https://user-images.githubusercontent.com/1487073/30823171-52d8b4e6-a1f9-11e7-938c-da09a6dca202.png)

CTRL+Space after the `:`

![image](https://user-images.githubusercontent.com/1487073/30823189-5fd44e08-a1f9-11e7-89fb-9e1d11164f7b.png)

open quotes, press CTRL+Space:

![image](https://user-images.githubusercontent.com/1487073/30823215-735cd670-a1f9-11e7-9b95-1ab8bf2d6f96.png)

Now i get a `taskName`:

![image](https://user-images.githubusercontent.com/1487073/30823227-7f9e6b74-a1f9-11e7-9c40-48ebebb00640.png)

Change type to `npm` and I no longer see `taskName`:

![image](https://user-images.githubusercontent.com/1487073/30823261-9687d85c-a1f9-11e7-8a3c-12fd07eb5b8d.png)

**Comment by chrisdias** [comment]
perhaps `npm` is a contributed task configuration which doesn't support `taskName`.

**Comment by chrisdias** [comment]
a clue...

I uninstalled my npm extension and no different. however, I tried to put in `tasnName` manually and see this...

![image](https://user-images.githubusercontent.com/1487073/30823859-a694d356-a1fb-11e7-9c9c-ca8ee75e2438.png)

**Comment by chrisdias** [comment]
ok, now i see what is going on.  `type` defines the task type, and then what the other valid settings are.  So for `"type": "shell"` you need to have a `taskName` and a `command`:

![image](https://user-images.githubusercontent.com/1487073/30824206-c4bdcd28-a1fc-11e7-8577-b3e124bfd21c.png)

The Tasks Output pane gives you a "live" validation session.  Here its telling me that I need to have a `command` or `dependsOn` property as well:

![image](https://user-images.githubusercontent.com/1487073/30824246-ea4c27ec-a1fc-11e7-96d5-c87ba6b5abab.png)

So I think the docs still can be clarified... the way they read right now every task has a `taskName`, etc.  when it is scoped to the `type`.

**Comment by dbaeumer** [comment]
Yes, the shape of a task depends type attribute. For contributed task (e.g. gulp, grunt, npm, ...) the attribute to control the UI is `label` since `taskName` was too confusing. It might be mistaken for the name of the gulp task :-)

I have an item to clean this up. E.g. to consistently use label. See https://github.com/Microsoft/vscode/issues/29852

**Comment by thecriticalpoint** [comment]
I am still so confused. The task.json documentation is written by people for people that already know how to use it. In 2021 I'm still not sure where the best resource and example guide is that I can count on being up to date. Yes, I've been googling. No, my frustration is not at you. The barriers to entry just keep stacking up.
