### ISSUE TITLE
Error when accessing https://code.visualstudio.com/tutorials/nodejs-deployment/introduction

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-docs#1189]
From https://github.com/Microsoft/vscode/issues/35356

Steps to Reproduce:

1. access https://code.visualstudio.com/tutorials/nodejs-deployment/introduction
2. error message: 
Sorry!
We seem to be having technical issues

**Comment by gregvanl** [comment]
Fixed. We removed that page but hadn't provided a redirect to https://code.visualstudio.com/tutorials/nodejs-deployment/getting-started
