### ISSUE TITLE
Replace spaces with control characters?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1197]
https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_snippets

This example in Tips and Tricks uses hard coded 3 spaces for snippet body:

```json
"create component": {
    "prefix": "component",
    "body": [
        "class $1 extends React.Component {",
        "",
        "   render() {",
        "      return ($2);",
        "   }",
        "",
        "}"
    ]
}
```

Wouldn't it be better to use `\t`, which will properly render with tabs and any numeric space indentation?

```json
[
    "\trender() {",
    "\t\treturn ($2);",
    "\t}"
]
```

**Comment by gregvanl** [comment]
You are correct, it should be using tabs. Thanks!

**Comment by gregvanl** [comment]
Actually made tabs explicit with https://github.com/Microsoft/vscode-docs/commit/dd9b318f807e879d04e7375ee519253571b3445c
