### ISSUE TITLE
workspaceFolder or workspaceRoot

### ISSUE THREAD

**Issue by saxtonjoshua1** [Microsoft/vscode-docs#1207]
I have been recently trying to use the MinGW gcc compiler with Code, and am getting some issues with Intellisense(not breaking, but I find it annoying).

I followed the documentation to edit the path for the c_cpp_properties.json file, but the error continues to pop up and I think I have also found contradictory information.

   {
        "name": "Win32",
        "includePath": [
            "${workspaceRoot}"
        ],
        "defines": [
            "_DEBUG",
            "UNICODE"
        ],
        "intelliSenseMode": "msvc-x64",
        "browse": {
            "path": [
                "${workspaceRoot}",
                "C:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include\\c++"
            ],
            "limitSymbolsToIncludedHeaders": true,
            "databaseFilename": ""
        }
    }
],
"version": 3
I looked on the github repo for the documentation and found someone had committed a change where ${workspaceRoot} was changed to workspaceFolder in the documentation. However, root seems to be the default for VS code, and I only updated to the new orange logo version this morning.

https://github.com/Microsoft/vscode-docs/commit/fa613d436a53bd9c5a21065cf5fa0f1b350d9bc6

So which is the correct way to get Intellisense working, Folder or Root for the documentation purposes?

https://stackoverflow.com/questions/46797258/does-vscode-use-workspaceroot-or-workspacefolder

**Comment by gregvanl** [comment]
Hi @saxtonjoshua1, workspaceRoot will still work but is being deprecated in favor of workspaceFolder as part of the work to support multi-root (folder) workspaces.
