### ISSUE TITLE
Can't find vscode-docs website dependence

### ISSUE THREAD

**Issue by hatroman** [Microsoft/vscode-docs#1223]
Hi!

Generally I’m looking for a web engine for hosting our documentation. And vscode-docs looks very interesting.

I tried to build vscode docs from current repo with gulp, but I failed. Gulp cannot find vscode-website repo (https://github.com/Microsoft/vscode-docs/blob/master/gulpfile.js#L23). 
What I’m doing wrong? Is it an internal project? Could you help me to find it?

**Comment by gregvanl** [comment]
Hi @hatroman, Yes, vscode-website is our internal website repo and not open source. The gulp tasks are in the vscode-docs public repo only to get around an implementation constraint of our continuous integration builds. Sorry, for the confusion.

**Comment by hatroman** [comment]
okay ...
