### ISSUE TITLE
Add how to do 'Definition Hovering'to the docs

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#1226]
Hover over a symbol with the CMD/CTRL key pressed, shows you the definition of the symbol in the hover. It should be mentioned in this section.

![image](https://user-images.githubusercontent.com/172399/32132407-693221f8-bbc3-11e7-9d8a-b591aea8203f.png)

**Comment by gregvanl** [comment]
Oops, fixed typos with https://github.com/Microsoft/vscode-docs/commit/a6014d1cc055696c3c95bd7d0c3d04c5838fac7c
