### ISSUE TITLE
Multi-root: the debugger menu example should be simpler

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#1231]
The current example is showing **2** launch configs from the `mono` folder and **14** from the `vscode` folder (14 is a lot and overwhelming). Suggest to use a simpler setup, e.g., 2 folders with 2 launch configs (see my tslint workspace setup below). May be show both the multi-root folder setup and the resulting debugger dropdown. 
![image](https://user-images.githubusercontent.com/172399/32282388-ba9e30ac-bf21-11e7-999c-a67f16a4c6bb.png)

![image](https://user-images.githubusercontent.com/172399/32282545-1cceeab4-bf22-11e7-8326-a3d567de6b65.png)

// CC @weinand

**Comment by gregvanl** [comment]
Updated debugging section with https://github.com/Microsoft/vscode-docs/commit/c028a50462480144e270d15e89ec1acd0f91b05d
