### ISSUE TITLE
Fix doc.keybindings files

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-docs#1234]
https://github.com/Microsoft/vscode-docs/commit/67557dc279875be83c2679b98eb8c576809ded7c removed the following files:

```
	new file:   scripts/keybindings/doc.keybindings.js
	new file:   scripts/keybindings/doc.keybindings.linux.json
	new file:   scripts/keybindings/doc.keybindings.osx.json
	new file:   scripts/keybindings/doc.keybindings.win.json
```

The smoketest depends on them, for some reason. So I had to bring them back for the endgame: https://github.com/Microsoft/vscode-docs/commit/0e387383cf1065a1a50f4be2a2003f40ab3f05ce. Someone should look into why the smoketest depends on them and move them to another place if needed.

**Comment by octref** [comment]
Sure. Thanks for letting me know.
