### ISSUE TITLE
Add keybinding when context enumeration

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#124]
An ask for documentation through doc feedback verbatim.
We should add an explanation for the enumeration to keybindings.md

**Comment by gregvanl** [comment]
editorFocus
editorTextFocus
inReferenceSearchEditor
editorHasSelection
editorTabMovesFocus
editorHasMultipleSelections
findWidgetVisible
inSnippetMode
inChangeAllMode
markersNavigationVisible
referenceSearchVisible
parameterHintsVisible
quickFixWidgetVisible
suggestWidgetVisible
renameInputVisible
globalMessageVisible
inDebugMode
inQuickOpen
searchViewletVisible
editorLangId ==
suggestionSupportsAcceptOnKey

**Comment by gregvanl** [comment]
+1 verbatim

**Comment by Tyriar** [comment]
:+1: I'm likely about to add a new value to the list as well. Would be good if it was documented.

**Comment by ramya-rao-a** [comment]
@gregvanl  Now that VS Code supports extensions contributing to the menus (which was a popular ask _and_ uses the same `when` model), +1 to getting this documented

**Comment by Tyriar** [comment]
I just added `terminalFocus` which is true when a terminal instance has focus https://github.com/Microsoft/vscode/commit/9900f278ab9290e2bbb049d91802e1f5243135d2

**Comment by spywhere** [comment]
Agreed for this to be documented as I also find a way for that `terminalFocus` context in the VS Code's documentation.

**Comment by Tyriar** [comment]
@gregvanl has `terminalFocus` being added in vnext? We need to remember to do this for v1.4.0.

**Comment by gregvanl** [comment]
@Tyriar It's on my list to do once I merge master with this change to vnext.
