### ISSUE TITLE
Cross-file intellisense not working for JS

### ISSUE THREAD

**Issue by Darrel12** [Microsoft/vscode-docs#1240]
Much like the closed issue #241, I'm having an issue with cross-file intellisense. I'm running the latest version (1.17.2). I originally didn't have a jsconfig.json when I discovered the issue. After making one with the following information the issue still persists:

```
{
    "compilerOptions": {
      "target": "ES6",
      "module": "commonjs"
    },
    "include": [
      "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
  }
```

I'm using AngularJS with Node handled by Grunt if that matters. Here's my simplified project structure:

```
MY-APP/
 |
 +-- build/
 |
 +-- node_modules/
 |
 +-- src/
 |      |
 |      +-- app/
 |            |
 |            +-- autoDeploy/
 |                  |
 |                  \-- autoDeploy.js
 |                  \-- autoDeploy.service.js
 |      
 \-- jsconfig.json
```

In `autoDeploy.js` I right click a function that was declared in `autoDeploy.service.js` and choose `Go To Definition`. It only searches for it in the current file — `autoDeploy.js`.

As mentioned, I have tested this without a `jsonconfig.js` as well as the current location of `jsconfig.json`, moving it one level deeper to be situated in `src/`, and modifying the above to be `app/**/*` rather that `src/**/*`. All with no affect.

**Comment by OneOfOne** [comment]
Why are you posting this here? this belongs on https://github.com/Microsoft/vscode
