### ISSUE TITLE
Include reasonable Python install instructions

### ISSUE THREAD

**Issue by kraigb** [Microsoft/vscode-docs#1250]
Python extension relies on an interpreter being installed. The statusbar will tell you when there isn't one, but need to review the experience of adding one.

From Brett:
It relies on Python already being installed. As for installing it, either get it from the OS (at least on Linux), from the OS package manager (Linux or macOS if you install Homebrew), download it from https://www.python.org/, or download https://www.anaconda.com/download/. IOW there is no blanket recommendation as it varies by OS and what version you want

**Comment by gregvanl** [comment]
aka.ms/vscodebi verbatim "Shouldnt the article mention that one should actually install Python on the computer?"

**Comment by kraigb** [comment]
Done. See https://code.visualstudio.com/docs/python/python-tutorial
