### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1255]
This page: https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/language-support.md - all images 404.

**Comment by gregvanl** [comment]
@usernamehw Thanks for reporting this! Fixed with https://github.com/Microsoft/vscode-docs/commit/e92b8f9981f906a8defe4206bc99aefb38b8d1b6

**Comment by gregvanl** [comment]
@octref We should be on the lookout for any other topics which were relying on the name prefix for images. Any topics referencing images from another topic would be broken.
