### ISSUE TITLE
Review and update JavaScript topic

### ISSUE THREAD

**Issue by ghogen** [Microsoft/vscode-docs#1275]
The CSAT for the [JavaScript Programming with Visual Studio Code](https://code.visualstudio.com/Docs/languages/javascript) topic is appearing in our VS MSR report - which looks at topics with high PVs and low CSAT.  We should investigate and address issues.

**Comment by gregvanl** [comment]
@ghogen Can we add a link to the report for these MSR reported issues?

**Comment by gregvanl** [comment]
November CSAT 95% for 19 ratings (relative low compared to previous months)
Tracking for a few more months.

**Comment by gregvanl** [comment]
December 91% CSAT
January 75% CSAT
