### ISSUE TITLE
Review and update Linux topic

### ISSUE THREAD

**Issue by ghogen** [Microsoft/vscode-docs#1276]
We should review feedback and make improvements to the [Running Visual Studio Code on Linux](https://code.visualstudio.com/docs/setup/linux) topic.  This is showing up in the high PVS / low CSAT report for the VS MSR.

**Comment by gregvanl** [comment]
November CSAT 80%
We should track this for a few months

**Comment by gregvanl** [comment]
December 74% CSAT
January 78% CSAT
