### ISSUE TITLE
Document persistent Markdown preview, if possible

### ISSUE THREAD

**Issue by tedhudek** [Microsoft/vscode-docs#129]
Is it possible to use VS Code to quickly click through a tree of .md files, opening each in Markdown preview mode?  This topic explains how you can manually toggle edit/preview when looking at a single file, but didn't see a way to make preview persist.

https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/markdown.md

Thanks!

**Comment by gregvanl** [comment]
Not currently supported.  You can enter a suggestion issue on the product's GitHub site https://github.com/Microsoft/vscode/issues and I'm sure the team will consider it.
