### ISSUE TITLE
Keybinding activating when not intended. 

### ISSUE THREAD

**Issue by neenjaw** [Microsoft/vscode-docs#1299]
I have been working with the atom keybinding extension (have also posted this there) but in my search of the documentation I'm not sure the fix is possible from the keybinding settings and this may be more of a vs code issue. 

Problem: In the atom keybinding extension, the 'h' key when in the explorer context causes the list to collapse. Now the problem happens when you are renaming a file, press the 'h' key, it causes the rename to lose focus and rename your file to whatever you had entered up to that point. 

Is there a way to prevent the firing of this keybinding when renaming the file? Is there a when condition I am unaware of from the documentation? Or is this a vscode bug

**Comment by gregvanl** [comment]
Issue discussed and solved in https://github.com/Microsoft/vscode-atom-keybindings/issues/44
