### ISSUE TITLE
Prompt when looking for plugin in the Extend ——XHR failed:

### ISSUE THREAD

**Issue by wujidong** [Microsoft/vscode-docs#1320]
Thanks for your help

**Comment by gregvanl** [comment]
Hi @wujidong, I think you have reported a product issue, not a documentation issue. You can report VS Code product issues at https://github.com/Microsoft/vscode/issues. Searching in that repo, I think https://github.com/Microsoft/vscode/issues/34385 is your issue.

**Comment by wujidong** [comment]
Thank you for your reply and the path you provide . A good man's life is safe
