### ISSUE TITLE
Peek Definition Shortcut key 

### ISSUE THREAD

**Issue by khatrizeeshan** [Microsoft/vscode-docs#1321]
[Go to Definition, Peek definition](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_go-to-definition-peek-definition)

Peek Definition shortcut shown in document is (Ctrl+Shift+F12), whereas it is (Ctrl+Shift+F10)

**Comment by gregvanl** [comment]
Hi @khatrizeeshan, I think the Peek Definition shortcut is correct with ctrl+shift+f12 and by default ctrl+shift+f10 isn't bound to any command. Could an extension be binding ctrl+shift+f10? Or maybe you added the binding yourself. You should be able to find the details of the ctrl+shift+f10 binding by looking in the Keyboard Shortcuts view (File > Preferences > Keyboard Shortcuts) and filtering on ctrl+shift+f10 and looking at the Source column.

**Comment by khatrizeeshan** [comment]
I just verified from here, kindly check.

[Keyboard shortcuts for linux](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf)
