### ISSUE TITLE
Failed to push to gitlab with SSH protocol.

### ISSUE THREAD

**Issue by Leafyyuki** [Microsoft/vscode-docs#1322]
Using HTTP protocol is ok, but using SSH always faild with the error: Git: Permission denied, please try again. There is no step to let me enter passphrase.
I wonder whether vscode supports to push with SSH ?

**Comment by gregvanl** [comment]
Other users have hit this as well

**Comment by gregvanl** [comment]
VS Code doesn't support SSH authentication if the SSH key was created with a passphrase.
You can track this feature request at https://github.com/Microsoft/vscode/issues/13680.
I'll add a Common Questions entry to the Version Control topic https://code.visualstudio.com/docs/editor/versioncontrol to mention this.

**Comment by gregvanl** [comment]
Added https://github.com/Microsoft/vscode-docs/commit/5c47e655a451bb30fd5e4f09857adbc6e1cc119f.
You can also launch VS Code from a Git Bash prompt to inherit its SSH environment.

**Comment by westwin** [comment]
seems gitlab is not stable as github.

I'm suffering the same issue now... but I can do git push days later... 

And I always get a gitlab 500 error.... 

I'm hesitating to migrate to github.com ...
