### ISSUE TITLE
Search docs leads to 500

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1323]
https://code.visualstudio.com/Search?q=token%20color
✔️ `token` => 10 results found
✔️ `token color` =>10 results found
❌  `tokencolor` => 500

**Comment by gregvanl** [comment]
Seems to be working now. Please reopen if you see issues again.

**Comment by usernamehw** [comment]
@gregvanl, Did you remove the space between words?

**Comment by usernamehw** [comment]
Is this the default behavior of this search? To show 500 page when nothing found...

**Comment by gregvanl** [comment]
I did remove the spaces. You raise a good issue, we should show a "no results found" message rather than error 500. For example, searching for "asdf" results in error 500. https://code.visualstudio.com/Search?q=asdf

**Comment by gregvanl** [comment]
@usernamehw I've moved this issue to our website repo since it is a website infrastructure issue. I'll report back here when it's been fixed. Thanks.
