### ISSUE TITLE
Extensions Intro Video

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#133]
There is a very helpful video on [channel 9](https://channel9.msdn.com/Events/Visual-Studio/Connect-event-2015/Visual-Studio-Code-Extensions) for building an extension. It would be great to link to this somewhere in the docs.

**Comment by gregvanl** [comment]
There is resistance to linking out from our docs to Channel 9 for several reasons:

1. We want traffic to come to our site, not leave.
2. Channel 9 content can become stale and we don't control it.
3. Channel 9 content quality varies.
