### ISSUE TITLE
Bad scrolling on website

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-docs#1335]
* open https://code.visualstudio.com/docs on MBP 13"
* open 'Extensibility Reference'
* try to click on the last item in there, impossible unless you scroll the main page to the bottom

![jan-04-2018 12-32-09](https://user-images.githubusercontent.com/1794099/34561705-900d170c-f14b-11e7-96fe-add294612e80.gif)

**Comment by gregvanl** [comment]
Duplicate of https://github.com/Microsoft/vscode-website/issues/728
