### ISSUE TITLE
Add vscode version to updates navigation

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1341]
https://code.visualstudio.com/updates/v1_19
I believe most of the time you know version of vscode and don't know the date

![nav](https://user-images.githubusercontent.com/9638156/34745577-07f44a88-f5a2-11e7-84ff-f2df2437707b.PNG)

Adding versions would be a useful enhancement.

**Comment by gregvanl** [comment]
This is an interesting idea but I'm reluctant to change the TOC since it matches our planning issues which are date based [Iteration Plan for January 2018](https://github.com/Microsoft/vscode/issues/41061).
Currently the browser link shows the version in the hover URL so you can match the date to the version pretty easily.
I'll leave this issue open and see if other users vote it up.

**Comment by usernamehw** [comment]
To be clear - I'm not proposing to remove the date (simply adding a version). It could be done on hover or some other clever way:
![hover](https://user-images.githubusercontent.com/9638156/34802277-f553aef0-f67d-11e7-94bd-1f35e9203bd3.gif)

**Comment by gregvanl** [comment]
Assigning to @octref for consideration. It would be a website change rather than a documentation change in vscode-docs.

**Comment by octref** [comment]
@gregvanl 
Would something like this work for you?

![image](https://user-images.githubusercontent.com/4033249/35019419-ab523850-fadb-11e7-8df3-5979998a72bb.png)

This way it also aligns with the title.

**Comment by gregvanl** [comment]
That would work but it is a little messy looking and we need to make sure the entries never wrap to two lines.  Showing the version on hover would be cleaner.

**Comment by octref** [comment]
It wouldn't wrap to two lines.
Showing additional info of navigation on hover is doable (albeit with some work), but it defeats the point of having versions on the left navbar for navigation...

**Comment by gregvanl** [comment]
Closing as we haven't seen any other users vote up this suggestion and adding to the release version in the TOC feels to cluttered.
