### ISSUE TITLE
Unable to scroll navigation on left of docs website

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-docs#1354]
2017 Macbook, stable Chrome with default zoom, I'm unable to scroll the left nav here down to get to the bottom. I've raised this in a couple of places before (including the LSP website) so I don't know if they all came from the same template or if there's an easy fix for them all.

<img width="506" alt="screen shot 2018-01-14 at 18 42 13" src="https://user-images.githubusercontent.com/1078012/34919383-ed85c61a-f95a-11e7-9353-f64eae937656.png">

**Comment by gregvanl** [comment]
Hi @DanTup Thanks for entering an issue. This is a known problem with our doc website and there is already an open issue in our private website repo. I'll respond back to this issue when it is fixed.
