### ISSUE TITLE
Provide possibility to use [taskRunner].autoDetect option in workspace or folder settings

### ISSUE THREAD

**Issue by AlexAkhremenko** [Microsoft/vscode-docs#1355]
I set
```
"settings": {
  "gulp.autoDetect": "off",
  "npm.autoDetect": "off"
}
```
in workspace settings and still see these detected tasks.
Also, in this way I don't see any tasks from my tasks.json.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode#41758

**Comment by gregvanl** [comment]
@AlexAkhremenko This looks like a product issue so moved to the VS Code product repo.

**Comment by AlexAkhremenko** [comment]
Oh, thank you. Sorry for wrong repo.
