### ISSUE TITLE
Add Cloud Shell "tip" to the Azure CLI deployment tutorial

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#1357]
https://code.visualstudio.com/tutorials/nodejs-deployment/getting-started

We should call out here that another option is to use the Azure Account extension to then use the  Cloud Shell instead of installing the Azure CLI locally.

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/62211d2865f4a2b1e860010ba4b9797304f3f803
