### ISSUE TITLE
Chinese (zh-Hans) translation of keyboard shortcuts keymap wanted

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#1363]
_From @xgqfrms-GitHub on January 2, 2018 15:32_

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

# i18n & L10n

> zh-Hans is wanted!

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows-zh.pdf

_Copied from original issue: Microsoft/vscode#41035_

**Comment by gregvanl** [comment]
_From @auchenberg on January 24, 2018 0:43_

@gregvanl Should we move this to the docs repo?

**Comment by lorderikir** [comment]
@gregvanl. Is there a template for this doc?

**Comment by gregvanl** [comment]
@lorderikir You can find the original Word documents that are used to create the PDFs at https://github.com/Microsoft/vscode-docs/tree/master/docs/customization.

**Comment by lorderikir** [comment]
Awesome thanks @gregvanl

**Comment by gregvanl** [comment]
@lorderikir Just a heads-up, the VS Code website doesn't support localized content or currently have a way to provide a localized PDF. It would require some engineering work to support this but Chinese versions of the PDFs could be hosted in this repo initially.

**Comment by lorderikir** [comment]
I've started the initial work here: https://github.com/lorderikir/vscode-docs/tree/feature/docs/zh-HANS-doc

**Comment by gregvanl** [comment]
Closing old issue. No one has responded to the `help wanted` label.
