### ISSUE TITLE
Fix package name in Python linting docs

### ISSUE THREAD

**Issue by michaelmulley** [Microsoft/vscode-docs#1369]
In the `Specific Linters` section, https://code.visualstudio.com/docs/python/linting#_specific-linters, the `pip install package name` for mypy is outdated. It should be `mypy`, not `mypy-lang`.

(You can confirm the new package name by looking at the mypy-lang package, https://pypi.python.org/pypi/mypy-lang, which is now just a reminder that you should be using `mypy`.)

**Comment by gregvanl** [comment]
@kraigb @DonJayamanne Can you take a look at this. Thanks.

**Comment by DonJayamanne** [comment]
I agree this should be `mypy`. The change in the codebase was made some time ago (https://github.com/DonJayamanne/pythonVSCode/issues/930), guess the documentation was never updated and that flowed onto the MS docs.
