### ISSUE TITLE
Typos in command names

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1381]
I'm pretty sure it was already fixed ( https://github.com/Microsoft/vscode-docs/commit/b032d24d8c118c1971e9fa6ddc01a0c6d46f6f4a ) 

Later reverted back at https://github.com/Microsoft/vscode-docs/commit/f5101649b536d7ae1b5ca559a7fad54432fcb619#diff-69746c26b1ae74aaf9f082db62281097. Should Pull Requests be merged in vnext branch?

Document: https://github.com/Microsoft/vscode-docs/blob/master/docs/extensions/themes-snippets-colorizers.md
`Developer Tools: Inspect TM Scopes` => `Developer: Inspect TM Scopes`

`Generate Color Theme from Current Settings` => `Developer: Generate Color Theme from Current Settings`

**Comment by gregvanl** [comment]
Thanks for spotting this!
