### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1382]
https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/vscode-api.md

Is there any secret meaning or difference between `icon-name` & `icon'name`:

```
My text $(icon-name) contains icons like $(icon'name) this one.
```

**Comment by gregvanl** [comment]
Hi @usernamehw, this content is auto-generated from the vscode.d.ts API declaration file. Moving to vscode for clarification and possible update.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode#42991
