### ISSUE TITLE
Overall code viewer can't be disabled

### ISSUE THREAD

**Issue by Sudharshaun** [Microsoft/vscode-docs#1389]
I'm using visual code now. And the code preview of the page we see doesn't seem to get disabled the one that comes along with the scroll bar.

**Comment by gregvanl** [comment]
You can disable minimap (code outline) using the "editor.minimap.enabled" [setting](https://code.visualstudio.com/docs/getstarted/settings).

```json
  "editor.minimap.enabled": false
```

Is this what you needed to know?

**Comment by Sudharshaun** [comment]
Yes it is that. Sorry I was new and was claustrophobic of the IDE. I got it already. Thanks man !
