### ISSUE TITLE
Bad TypeScript example at your docs page

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#139]
_From @egamma on February 2, 2016 20:27_

_From @PhilipMay on February 2, 2016 20:24_

Hello,
at your docs page you have a TypeScript example:
https://code.visualstudio.com/docs/languages/typescript

```
class Startup {
    public static main(): number {
        console.log('Hello World');
        return 0;
    }
}
```
The example implies that it prints Hello World to the console.
But it does not. There is a "Startup.main();" missing at the end.

_Copied from original issue: Microsoft/vscode#2652_

_Copied from original issue: Microsoft/TypeScript#6849_

**Comment by egamma** [comment]
good catch, moving to vscode-docs

**Comment by egamma** [comment]
_From @RyanCavanaugh on February 2, 2016 20:41_

@egamma wrong repo I think

**Comment by egamma** [comment]
_From @RyanCavanaugh on February 2, 2016 20:43_

Also, please don't write TypeScript code like this :( TypeScript isn't C#, there's no reason to shove things into classes

**Comment by egamma** [comment]
_From @PhilipMay on February 2, 2016 21:13_

> TypeScript isn't C#, there's no reason to shove things into classes

Well - that's right. This would just be way better (and simpler):

`console.log('Hello World')`

But I thought you wanted to show some of the TypeScript features in the example.

What's the right place for this report? Is it https://github.com/Microsoft/vscode-docs ?

**Comment by egamma** [comment]
OOPS, issue mover mistake... sorry
This should have been moved to vscode-docs

**Comment by PhilipMay** [comment]
Please do not forget to update this page (where is bug still is): https://code.visualstudio.com/docs/languages/typescript

**Comment by gregvanl** [comment]
There is often a short delay between when we commit a doc change and when it goes live on our portal.  We'll have a portal refresh in a couple of days.
Thanks
