### ISSUE TITLE
Outdated screenshot in angular javascript tutorial

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-docs#1403]
The documentation says to click an information icon to show a flyout. In the current version of code, there's no information icon, the flyout for the selected item is automatically shown.
![screen shot 2018-02-16 at 12 59 24 pm](https://user-images.githubusercontent.com/3672607/36329022-405eb1bc-1319-11e8-8caf-a5c0f53501e1.png)

**Comment by gregvanl** [comment]
I believe this flow is accurate as the initial flyout state is closed and the user will see the information button. You may have already expanded the flyout once in your VS Code instance (the flyout state is sticky across sessions).
