### ISSUE TITLE
Better organization of language pages?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-docs#1407]
The JS language page feelings rather unorganized:

![screen shot 2018-02-16 at 3 09 31 pm](https://user-images.githubusercontent.com/12821956/36333392-817a3074-132b-11e8-9476-f1c6be9e188b.png)

Specifically, documentation for language features is mixed in with 'how to X' type sections and  'getting started' sections.

My proposal is a structure closer to:

```md
# JS Introduction
## jsconfig
## ...

# JS language features
## IntelliSense
## Reference code lenses
## ...

# Extending JavaScript
## Linters
## Building with babel
## ...

# Next Steps

# Common questions
```

However I'm not sure if this would work with our doc templates. @gregvanl any thoughts?

**Comment by mjbvz** [comment]
The C++ page already does something similar. My main concern with the proposed structure as-is is that it would no longer spotlight our specific language features in the sidebar

**Comment by gregvanl** [comment]
I've done some reordering and moving content to H3 to clean up the right nav:

![image](https://user-images.githubusercontent.com/12818376/38949370-08cf1c38-42f7-11e8-9da1-9bd299090648.png)

I don't think it make sense to break the sections up further until we support more than two levels in the TOC. We could break up the JavaScript topic into subtopics like Overview, Language Features, Linters, Debugging, Extending.
