### ISSUE TITLE
Extensibility - Hello World feedback

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#1408]
https://code.visualstudio.com/docs/extensions/example-hello-world

```
* Please read the [`package.json` extension manifest reference](/docs/extensionAPI/extension-manifest.md)
* More information on [`package.json` contribution points](/docs/extensionAPI/extension-points.md)
* Each VS Code extension must have a `package.json` file that describes it and its capabilities.
* VS Code reads this file during start-up and reacts to each `contributes` section immediately.
```

The order should be reversed. Should explain what the `package.json` is and have links for "to read more".

```
"engines": {
    "vscode": "^1.5.0"
},
```

We need explanation here that the `postinstall` command in `package.json` downloads the correct version of `vscode.d.ts` according to this setting.

> Installing your Extension Locally

I think instead of suggesting to copy-paste, we should use `vsce package` here.

---

Overall feedback: I think this repeats a lot of things in https://code.visualstudio.com/docs/extensions/yocode. Also a flow from Overview -> Hello World would be better. Not interrupted by the extension generator section.

Also I think for "Hello World", maybe using plain JS and not using generator would be a better choice. Just a suggestion.

Finally we should have a Hello World sample in https://github.com/Microsoft/vscode-extension-samples.

**Comment by octref** [comment]
Also PR at https://github.com/Microsoft/vscode-docs/pull/1409

**Comment by gregvanl** [comment]
Closing as the tutorial has been rewritten by @octref
