### ISSUE TITLE
Publish skeleton repos for extension development

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode-docs#141]
I'm not saying that Yeoman templates are overkill, but asking people who aren't already using Yeoman to install it probably is.

Basically, the docs should say something like "You can use the `yo code` Yeoman generator [...] or you can just `git clone` <this repo> and edit the package.json fields."

I set up [an example repo with a skeleton extension](https://github.com/d3431a8a0421aead/vsc-typescript-extension).  The vscode-generator-code team should push the results of running the generators to repos like this.

Carrying along the skeleton repo's git history might be a problem, but that's as easy as deleting the `.git` directory before doing the first commit.  GitHub also already has built-in support for source drops (that don't carry the git history) by using the releases feature.  [Here's an example from the vsc-typescript-extension repo mentioned above](https://github.com/d3431a8a0421aead/vsc-typescript-extension/releases), so people could just unzip those instead.

**Comment by gregvanl** [comment]
Thank you for the suggestion. We haven't seen much feedback on this issue so closing.
