### ISSUE TITLE
Docathon: Extensions Marketplace

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-docs#1415]
Notes on https://code.visualstudio.com/docs/editor/extension-gallery

The sections from `Browse and Install extensions`, `Install extension`, `Search Extension`, `Manage Extensions` should be arranged in a better way, preferably in the order of interaction with the extensions view. There is some overlap in these sections.

**Browse Extensions**
This should cover 
     - discovery of the extension view let, 
     - default view: popular extensions when no extensions are installed and Installed + Recommended extensions when there are installed extensions
     - Use of the `...` menu to show different views and the fact the same can be done via the command pallet
     - Search extensions 

**Extension details**
  - Readme, Contributions, Changelog, Dependencies, Extension packs

**Manage(Install, Update, Disable) extensions**
This is same as the current "Manage extensions"
   - The note on "List installed extensions" is not necessary as the default view provides exactly that
   - The notes on Update and Auto-updates give the impression that auto updating extensions is opt-in and that manual update is the norm where as in truth its the opposite. Would suggest to talk about auto-update first -> talk about how to disable auto-update -> then talk about the "Update" button and the "Show outdated extensions" menu item
   - The 2 gifs for disabling extensions should be combined
   - The text on disabling extensions should talk about disable always vs disable workspace
   - If we are talking about disabling extensions, then we should talk about enabling them as well

**Workspace Recommended Extensions**
  - Note on the ability to edit the workspace recommendations and install all in the "Recommended View" should be added
  - Note on "other recommendations" should be added as well

**Comment by joaomoreno** [comment]
A couple more notes on this:

- There is a proxy disclaimer hidden towards the end of the `Browse and install extensions` section. We should probably pull that up as a disclaimer at the top.
- The `Can VS Code read TextMate bundles directly?` FAQ question seems more appropriate in the `Extension Authoring` or `Extensibility Reference` sections.

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/e2c84f0a0b4b7136309a63d87f995d3746c2e3bb
