### ISSUE TITLE
Doacthon: css/sass/less page feedback

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#1418]
IMO this page should be renamed to css, scss and less. scss is different than sass. All occurences of sass actually refer to scss and should be replaced.

We should point to this extension for sass users: https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented

One of my larger concern is the documentation digress off to two pages of scss/less transpilation, task runner configuration and gulp. Task page should either include this info or be educative enough that people can learn how to plug in the scss/less transpiler cli tool into the task system.

**Comment by gregvanl** [comment]
Sass -> SCSS update with https://github.com/Microsoft/vscode-docs/commit/f9eab280a20fc7a13991fc83aa723abd716224e2

**Comment by octref** [comment]
Thanks!
