### ISSUE TITLE
Doacthon: react page feedback

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#1419]
> To install and use the generator as well as run the React application server, you'll need the Node.js JavaScript runtime and npm (the Node.js package manager) installed. npm is included with Node.js which you can install from here.
Tip: To test that you have Node.js and npm correctly install on your machine, you can type node --version and npm --version.

This is way too verbose. React's official tutorial only has one sentence: Make sure you have a recent version of Node.js installed.
https://reactjs.org/tutorial/tutorial.html#if-you-prefer-to-write-code-in-your-editor

> Markdown Preview

Why we jump off to this thing when we just taught the user to create a React app? We should directly jump to React support. Markdown features don't belong to this page IMO.

> Angular

Why do we even mention Angular starter kit in a React support page?

Finally, this page should contain some recommended extensions. Matt's styled-component comes to mind, but there are other recommendable React extensions on MarketPlace too.

**Comment by gregvanl** [comment]
This tutorial has one of our highest CSAT ratings 92% so I am reluctant to reduce the level of instruction for new users or remove any "green light" sections such as Markdown preview.
