### ISSUE TITLE
Docathon: review of the JavaScript section

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#1420]
Doc review #1396 

The document links to a description of the JavaScript language service:

![image](https://user-images.githubusercontent.com/172399/36370316-e00a4a22-155e-11e8-9ffa-74d151d3efc7.png)

This is a great document, but the issue is that this document includes VS specific information (e.g. https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#whats-new-in-the-javascript-language-service-in-visual-studio-2017), which is confusing for a reader coming from VS Code. The best would be that the JavaScript language service document is refactored so that it is IDE neutral or includes both information on VS and VS Code. 

----

VS Code provides support for entering JSDoc comments and this should be mentioned in the doc. I suggest a separate section on entering JSDoc comments. Explain that entering /** <ENTER> fills in a template (best shown in an animated gif)

This was in the release notes and could be promoted
https://code.visualstudio.com/updates/v1_10#_auto-jsdoc-comments

----

https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson

It should be mentioned that you can have mixed JS/TS projects, which is useful when migrating from JS to TS. In this case you enable JS in TS project by adding the settings `allowJS` to true. More details here https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

----

The debug section feels out of place it comes in between language service features like jsconfig.con/type checking). I suggest to move it to the end.

----
Doc review #1396 

There should be a section on refactoring and it should explain that the refactorings are available in the light bulb when you make a selection

![image](https://user-images.githubusercontent.com/172399/36372192-9353d968-1564-11e8-9172-6a5336b01a43.png)

----

The most popular JS linter is eslint, but it isn´t shown in the list?

![image](https://user-images.githubusercontent.com/172399/36371437-5f98af38-1562-11e8-8eae-e8ef8d486a3d.png)

----

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/aea39f260f7f81c0cd616841ec02e85fdd660bb8
Switch to curated JavaScript Linter extension list
Move Debug section down
Add JSDoc support section

**Comment by gregvanl** [comment]
In contact with the TypeScript team about making their JavaScript Language Service wiki page more IDE/editor agnostic.
