### ISSUE TITLE
Docathon: Tips and Tricks

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode-docs#1423]
# Specific Feedback

[Multi-cursor selection](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_multi-cursor-selection) requires more textual guidance. It's not clear from the animated gifs how these things can be accomplished.

[From the Command Palette (Ctrl+Shift+P) and select Debug: Open launch.json, select the environment.](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_configure-debugger) sentence is off.

https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_navigate-to-a-file and https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_quick-open are almost duplicates.

[VS Code has a powerful command line interface (CLI) to help you customize the editor launch your specific scenarios.](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_command-line) sentence is off.

# General Feedback
I think we should reconsider the position of the tips and tricks section. It's a rather advanced subsection and shouldn't be put at the start of the getting started section.
Maybe we should also reconsider whether we want to elevate this to a section of it's own. That way we could create several subsections that make it easier for us to maintain (smaller chance of duplicates) and also easier for the users to digest. Currently this subsection contains roughly 2500 words.

I found that the looping gifs made it quite difficult to study the text at times. A good example is the [Change your theme section](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_change-your-theme):
![loopinggifs](https://user-images.githubusercontent.com/15158320/36383866-c0840e7a-158d-11e8-84c8-b20434ee8173.gif).
I think it would be a big improvement if the users could trigger the animations themselves by hovering or clicking. This would yield two advantages: First, the user wouldn't be distracted by the animations. Second, the user would immediately know where the sequence starts without having to watch the same loop over and over again.
[freezeframe.js](http://ctrl-freaks.github.io/freezeframe.js/) and [gifplayer](http://rubentd.com/gifplayer/) are two projects on GitHub that demonstrate how nice and quiet user triggered gifs can be.

**Comment by Ayush-Rawal** [comment]
Should this issue be closed? Or is this still relevant?

**Comment by gregvanl** [comment]
@Ayush-Rawal Thanks for noticing. Everything has been covered that we want to address at this time.
