### ISSUE TITLE
Supported node like runtimes section too long for start of page

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#1426]
Currently the start of the node debugging section is dominated by the [Node runtimes section](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_supported-nodelike-runtimes)
I feel like this is too advanced and is an implementation details. Why do users have to know about this?
Why is it at the very top of the page?

IMHO nodejs debugging document should focus on the issues that the users are having and I believe those are source maps, and none of the users care about what adapter is used underneath.

Suggestion: move this section to the wiki of the node extension and just mention briefly in the [Launch configuration attributes](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes) when you discuss the `protocol` attirbute

**Comment by weinand** [comment]
I agree that since many users have switched to node.js >= 8.0 the runtime section is now a bit too prominent. On the other hand I still get at least one issue per day where this version issue is still an issue.

I suggest that we just move this further down but keep it in the doc.
The wiki is not an option as end-users don't have to care about the originating repositories.

**Comment by isidorn** [comment]
We shuold maybe consider to split the node debugging page . I feel like the current document has the following all mixed up:
* introduction
* tips
* list of all features
* troubleshooting

I am not saying to split up the document in 4 subdocuments, but to make it better strucutred based on what the user wants to do.
If he just wants to read about how to start node debugging, he should be able to read the start of the document to get a general idea how to start.

**Comment by weinand** [comment]
@gregvanl I've reviewed the change and the Node.js debugging doc is now much easier to approach. Thanks!
