### ISSUE TITLE
Launch configurations for common scenarios could be shortened

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#1427]
In this [section](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configurations-for-common-scenarios) for each snippet we mention what the snippet asks the user to enter.

I feel this makes that section too long and full of text. What is asked by each snippet is obvious since the snippet will highlight and select whatever input is needed.

I suggest to remove those sentences from the snippets.
If you agree let me know and I can remove them

**Comment by weinand** [comment]
@isidorn I agree that there are some items that mention what the snippet asks the user to enter. But most items provide additional information that is not obvious when reading the snippet inserted.

I suggest you try to remove the "obvious" information from the items but keep the information that is not obvious from the snippet. I went through the items and most have at least one sentence that falls into the latter category.

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode-docs/commit/ca3209592a9615e4a202236df7d316a16db97c0d
@weinand please review
