### ISSUE TITLE
Mention about multi-select in user interface page

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-docs#1430]
[User Interface](https://code.visualstudio.com/docs/getstarted/userinterface) talks about explorer and open editors views. It would be good if this page also mentions about multi selection gesture which was recently implemented.

**Comment by gregvanl** [comment]
We introduce multi-selection early in the Basic Editing topic. https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

**Comment by sandy081** [comment]
@gregvanl This is about multi-select in explorer - https://github.com/Microsoft/vscode-docs/blob/master/release-notes/v1_20.md#multi-select-in-the-explorer

**Comment by gregvanl** [comment]
Oops, got it. Yes, that makes sense to add to the user interface topic.
