### ISSUE TITLE
Link to node debugging intro video is at the very end

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#1431]
The link to this page https://code.visualstudio.com/docs/introvideos/debugging
is at the very end after the user has read all the complex details about node debuggin.

I feel like this video should be linked at the very start of the page

**Comment by gregvanl** [comment]
Our video quality isn't great and I think we want to keep users on the topic page first.

**Comment by auchenberg** [comment]
We got https://www.youtube.com/watch?v=2oFKNL7vYV8 now  @gregvanl  :)
