### ISSUE TITLE
Node2 debugger showing up in node extensions docs

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-docs#1435]
It's a bit odd that we show the Node2 debugger showing up in node extensions docs, as it ships inside the box.

https://code.visualstudio.com/docs/nodejs/extensions
 
![javascript extensions in vs code 2018-02-19 11-05-33](https://user-images.githubusercontent.com/173559/36393537-de33d5be-1564-11e8-9c3c-65c81052f3dd.png)

**Comment by auchenberg** [comment]
Proposal: We should hide built in extensions

**Comment by gregvanl** [comment]
Will be fixed when we use "node.js" in issue #1436
