### ISSUE TITLE
Node extensions: NPM extension dominant in the Node.js category 

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-docs#1436]
I know we are pulling these automatically, but there's duplicates, and it's a bit weird that we are recommendation mostly NPM extensions...

<img width="836" alt="screen shot 2018-02-19 at 11 11 32 am" src="https://user-images.githubusercontent.com/173559/36393769-d6013354-1565-11e8-8590-571cc6bb76ec.png">

**Comment by gregvanl** [comment]
We should switch to a query for "node.js" in the website marketplace-extensions-node query

**Comment by gregvanl** [comment]
Fixed by using a curated extension list https://github.com/Microsoft/vscode-docs/commit/abb1deca10dcfbb63d2a11524f9c33373408a963
