### ISSUE TITLE
Python debug configuration docs are outdated

### ISSUE THREAD

**Issue by PaleNeutron** [Microsoft/vscode-docs#1438]
for example:
````json
    "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput"
    ]
````
Both `WaitOnAbnormalExit` and `WaitOnNormalExit` are announced as removed in VSC.

Also, `console` options is outdated.

I have not review the whole doc,  maybe there are more difference between doc and code.

**Comment by gregvanl** [comment]
@kraigb Can you have a look at this? Thanks

**Comment by kraigb** [comment]
@DonJayamanne What's current here? We're referring to: https://code.visualstudio.com/docs/python/debugging

**Comment by DonJayamanne** [comment]
> Both WaitOnAbnormalExit and WaitOnNormalExit are announced as removed in VSC.

Not sure what you mean by `announced as removed in VSC.` We have removed them from the default config, but they aren't invalid.
If not provided we default to `["RedirectOutput"]`

> Also, console options is outdated.

Not true. This is still used. If not provided we default to `none`

**Comment by DonJayamanne** [comment]
@kraigb I'd leave the existing settings as they are.
Our plan is to simplify this json as follows:
```json
{
    "name": "Python",
    "type": "python",
    "request": "launch",
    "program": "${file}"
}
```

If we manage to make this change, we'll let you know.

**Comment by PaleNeutron** [comment]
After I add WaitOnAbnormalExit to the config file, I got green line under it and a notification list all available options.
I will provide a screenshot after several hours.

**Comment by DonJayamanne** [comment]
@PaleNeutron
My apologies, yes you are correct. 
The values `WaitOnAbnormalExit` and `WaitOnNormalExit` are no longer valid entries.

@kraigb 
the valid values are as follows:
```
"RedirectOutput",
"DebugStdLib",
"BreakOnSystemExitZero",
"DjangoDebugging",
"Sudo",
"IgnoreDjangoTemplateWarnings",
"Pyramid"
```

My suggestion is to just document the following:
```
"RedirectOutput",
"DebugStdLib",
"DjangoDebugging",
"Sudo",
"Pyramid"            // Used when debugging a Pyramid application
```

The reason is as follows:
* Other entries excluded will become obsolete and are very rarely used.
* Currently we're working on a new debugger for Python extension & some items will be redundant (the items I have excluded from the above list)

**Comment by PaleNeutron** [comment]
Thanks a lot for the 'new debugger for Python extension'!

The current Mac version debugger not works well with 'caught unexpected'.

**Comment by DonJayamanne** [comment]
> The current Mac version debugger not works well with 'caught unexpected'.

Please raise an issue in our github repo, I'd like to look into this and find a solution for you.

**Comment by kraigb** [comment]
Edits made in https://github.com/Microsoft/vscode-docs/pull/1449.
