### ISSUE TITLE
Installing a locally developed extension

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-docs#1439]
The docs in several places say that a locally developed extension can be install by copying it to `$HOME/.vscode/extensions`. It would be safer to package the extension as VSIX and install that because that will make sure everything is compiled and verified.
- Make sure `vsce` is installed.
- In the extension folder run: `vsce package`.
- Install the resulting VSIX: `code --install-extension my-extension-0.1.2.vsix`.

As an advanced way of installation we could still explain that one can link (better than copy) an extension's folder into `$HOME/.vscode/extensions`, so the local development version of the extension becomes available as an installed extension.

/cc @aeschli

**Comment by gregvanl** [comment]
Moving this issue to the October milestone when the Extensibility documentation refactoring is planned. This suggestion would be good in the initial Hello World section.

**Comment by octref** [comment]
This content should go into https://vscode-ext-docs.azurewebsites.net/api/working-with-extensions/publishing-extension, and be referred to in "Testing Extension" topic like "This topics covers how to write unit tests but not for 'how to test your extension in stables', go to blah blah topic for that".

**Comment by octref** [comment]
Included a section on this topic at https://vscode-ext-docs.azurewebsites.net/api/working-with-extensions/publishing-extension#packaging-extensions.

![image](https://user-images.githubusercontent.com/4033249/50110898-3ab17d00-01f0-11e9-87e7-93a2f8b36d4d.png)

Only references to `.vscode/extensions` is the Color Theme topic. I'll fix it as part of https://github.com/Microsoft/vscode-docs/issues/2240.

**Comment by starball5** [comment]
> As an advanced way of installation we could still explain that one can link (better than copy) an extension's folder into $HOME/.vscode/extensions, so the local development version of the extension becomes available as an installed extension.

This no longer seems to work. At what point did that change and why?

**Comment by starball5** [comment]
Following up on changes related to Profiles, it would be nice to have the `Developer: Install Extension from Location` command be better documented where [the extension packaging docs are](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions).

- It's [mentioned in 1.74 release notes](https://code.visualstudio.com/updates/v1_74#_install-an-extension-located-on-disk), but only says you can use it to install VSIXes, and doesn't include that you can also pass an unpackaged extension directory.
- [Web Extension publishing docs](https://code.visualstudio.com/api/extension-guides/web-extensions) also mention that it can be used for testing locally-served extensions on vscode.dev.

**Comment by zachpoblete** [comment]
Thank you @starball5!

I was frustrated for 15 minutes that my theme wasn't showing up. The quickstart file Yeoman generated just told me that I needed to restart VS Code:

<img width="1047" height="178" alt="Image" src="https://github.com/user-attachments/assets/08502c65-f959-4c78-b8d7-89dc85e0e491" />

Running `Developer: Install Extension from Location` did the trick!
