### ISSUE TITLE
Debugging in a multi root workspace

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-docs#1440]
The "[Debugging](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_debugging)" chapter lacks some introduction/motivation paragraph that explains what debugging could be for a multi-root workspace.

It just starts with "VS Code searches across all folders for launch.json debug configuration". This detail does not really spark the user's excitement.

**Comment by gregvanl** [comment]
Closing old issue, only one upvote
