### ISSUE TITLE
Link to examples from "Extension Generator"

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-docs#1441]
Extension Generator is a good overview. Its sections could each link to the corresponding example page which goes into more detail on what else is involved beyond generating the scaffold. E.g. at the end of a section: "See [Example - Hello World]() for more details."

**Comment by thisisabdus** [comment]
@gregvanl, I want to work on this issue. Is this still up for grab? Please let me know.

**Comment by gregvanl** [comment]
Hi @thisisabdus We're going to be doing a large refactoring of the VS Code extensibility topics in the next few months so this would not be a good issue to work on. Thank you for your interest in the VS Code documentation.

**Comment by thisisabdus** [comment]
Hi @gregvanl, thanks for letting me know! Have a good day ahead.

**Comment by octref** [comment]
No longer relevant for the new API doc.
