### ISSUE TITLE
Consider to fold "Debugging" section 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-docs#1442]
If multi root workspaces have become "mainstream" (and no longer are a novel feature), we might want to consider to move the contents of the section["Multi-root Workspaces Debugging"](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_debugging) back into the [Debugging documentation](https://code.visualstudio.com/docs/editor/debugging).

**Comment by isidorn** [comment]
Should we then also do that for Git, Tasks and other sections of that document?

**Comment by weinand** [comment]
@bpasero has the final say here...

**Comment by gregvanl** [comment]
I'm reluctant to fold  MRW content back into the other topics. We get a discovery advantage by having a separate topic in the User Guide TOC. I also think in most cases features, such as debugging and source control, "just work" as expected in MRWs. Having a single doc explaining MRW in one place is good but we could certainly provide links in other topics.

**Comment by gregvanl** [comment]
Reconsidering as the page view for the multi-root workspace topic is falling (#40 Feb-March). It is still highly rated (CSAT 90%) but fewer users may be looking at the dedicated page. Moving to the backlog milestone.

**Comment by gregvanl** [comment]
Closing as multi-root workspaces haven't been widely adopted (telemetry shows only about 5% of users have multi-root workspaces) and so it is good to keep information on the advanced configuration in it's own topic.
