### ISSUE TITLE
Docathon: Version Control

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-docs#1444]
- The screenshot in the `Git Support` section is outdated
- The `Initialize a Repository` section is very outdated: that UI doesn't exist anymore. The recommended way is to open the command palette and run `Git: Initialize Repository`
- The `Git patch/diff mode` section should instead be titled as `Code as a Diff Tool`
- In the `Using Visual Studio Code, I accidentally initialized a Git repo on a folder with a massive number of files, like my entire hard drive. Now VS Code is too slow to use or hangs. What do I do?` FAQ question, a user can find out where the git repository root is with the `git rev-parse --show-toplevel` command
- In that same question, Code no longer becomes too slow or hangs, since Git is an extension.

**Comment by gregvanl** [comment]
@joaomoreno I took your last comment to mean that we don't need the "massive number of files" FAQ at all any more.
