### ISSUE TITLE
Global snippets are not documented

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode-docs#1455]
The title says it all, but the new Global Snippets feature does not seem to be documented in the main snippets doc (https://code.visualstudio.com/docs/editor/userdefinedsnippets).

**Comment by jrieken** [comment]
fyi @gregvanl - I have pushed some sentences about global snippets to the next-branch. Please review.

**Comment by gregvanl** [comment]
Thanks @jrieken! Published.
