### ISSUE TITLE
cmd+enter on file explorer focus no longer opens selected file 

### ISSUE THREAD

**Issue by TylerSustare** [Microsoft/vscode-docs#1458]
Mac OS-X 10.13.3
VS Code 1.20.1

I haven't found any docs on how I would add this to my personal `keybindings.json` either. This was probably removed by design but I can't find out how to bring this back into my workflow.
The below (default) config still works for opening to the side, but I want the file opened in the current window. 
```js
{ "key": "ctrl+enter",            
"command": "openReferenceToSide",
"when": "referenceSearchTreeFocused && referenceSearchVisible" },
```

**Comment by gregvanl** [comment]
You can use the setting workbench.list.multiSelectModifier to switch to using "Alt" instead of "Cmd".
https://code.visualstudio.com/updates/v1_20#_multi-select-in-the-explorer
