### ISSUE TITLE
Office Add-ins with VS Code - Document - Contains Bad link

### ISSUE THREAD

**Issue by CyberUnDead** [Microsoft/vscode-docs#1468]
In the _vscode-docs/docs/other/office.md_ document the link specified in *Step 1: Get setup* titled **Create an Office Add-in using any editor**  is now a 404.  I believe the href could be [https://dev.office.com/blogs/creating-office-add-ins-with-any-editor-introducing-yo-office](https://dev.office.com/blogs/creating-office-add-ins-with-any-editor-introducing-yo-office)

**Comment by gregvanl** [comment]
Thanks for pointing this out and providing the new link.
