### ISSUE TITLE
Can't set value on variables!

### ISSUE THREAD

**Issue by MousKamel** [Microsoft/vscode-docs#1469]
My debugger works with php. I'm capable of seeing all the variables, But I can't click on SetValue.

![](https://i.stack.imgur.com/a5HEo.png)

**Comment by gregvanl** [comment]
Hi @MousKamel, not all debug extensions support Set Value. If the debug extension doesn't indicate that it `supportsSetVariable` in it Capabilities https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L594, the VS Code Set Values command will be disabled. If you are using a PHP extension, please contact that author to see if they support Set Value and if not, you can enter an issue or feature request in  their repo.
