### ISSUE TITLE
Add client side debugging walkthrough to docs

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#148]
We should consider adding a walk through as is done in the blog below for client side debugging into our docs.

The chrome debugger extension is now the 3rd most downloaded extension.

http://blogs.msdn.com/b/jtarquino/archive/2016/01/24/debugging-typescript-in-visual-studio-code-and-chrome.aspx

**Comment by gregvanl** [comment]
Basic client side debugging (launch an .html page from VS Code) shows up in doc feedback verbatim.

**Comment by gregvanl** [comment]
Covered now in the React tutorial and the soon to be written Angular tutorial.
