### ISSUE TITLE
Are there documents for complex key binding?

### ISSUE THREAD

**Issue by Fenzland** [Microsoft/vscode-docs#1484]
In SublimeText, I do this configs:
```json
{"keys":["(",],"command":"insert_snippet","args":{"contents":"$1(${2:$SELECTION})$0",},"context":
	[
		{"key":"selection_empty","operator":"equal","operand":false,"match_all":true,},
	],
},
{"keys":["i","f","(",],"command":"insert_snippet","args":{"contents":"if( ${1:$SELECTION} ){\n\t$0\n}",},"context":
	[
		{"key":"selector","operator":"equal","operand":"(source.php,source.js) - string - comment","match_all":true,},
	],
},
```
So when I select some code and press "(", selected code will wrapped with "()", and cursor will goto the front of "(", so I can type function name without press "left", "left".
When I select some code and press "i", "f" ,"(" in PHP and JS, a "if" snippet will build with selected code in "()".

How to make these in vscode?

Are there documents for available commands and there acceptable arguments?

**Comment by gregvanl** [comment]
@Fenzland You can get pretty close by looking at our snippets documentation which describes how to add a keybinding to a snippet. https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets.

I came up with this and added it to my keybindings.json file:

```json
{
	"key": "ctrl+k 1",
  	"command": "editor.action.insertSnippet",
        "when": "editorHasSelection",
        "args": {
    		"snippet": "$1(${2:$TM_SELECTED_TEXT})$0"
	}
}
```

It comes close to what you want. I'm not sure you can override the '(' key.

**Comment by Fenzland** [comment]
Thanks, this documentation is pretty helpful.
But there seems no way to bind a to key "(".
(In my keyboards layout, "(" is not "shift+0".)
