### ISSUE TITLE
We should add a section in the doc to list all examples from https://github.com/Microsoft/vscode-extension-samples.git

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-docs#1492]
I could not find a section explaining all samples we have in one place. The doc section should also contain a short description of the sample.

**Comment by gregvanl** [comment]
We have Extensions/Additional Examples at https://code.visualstudio.com/docs/extensions/samples.
Is this the topic you were looking for?
It may not be fully up to date for all samples https://github.com/Microsoft/vscode-docs/issues/1208

**Comment by dbaeumer** [comment]
We should at least link the task provider example. 

I would even argue we should list them all with a sentence explaining what they do even if they are used in some other doc section as well.

**Comment by gregvanl** [comment]
Folding into #1208
