### ISSUE TITLE
Extension Gallery

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#150]
Couple things I think can be improved here. 

- Instead of Extension Gallery for the title, what if we changed it to Extensions?
- The two top images is a bit confusing. One gets to the list of extensions through F1 and the other gets to it with cmd+P. I think it would reduce cognitive friction for the user if we used the same experience for both images and were consistent throughout.

**Comment by gregvanl** [comment]
We landed on Extension Gallery for two reasons; there already was a top node called Extensions and this topic is about finding and using extensions from the gallery.
As we talked about this morning F1 "showCommands" is different from Ctrl+P.  Ctrl+P is a useful tip and out of the main doc flow.
