### ISSUE TITLE
Update Python docs for incoming changes to launch.json

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1500]
The template has been greatly simplified and we are now having users use snippets to add application-specific details.

/cc @DonJayamanne

**Comment by kraigb** [comment]
@brettcannon Is there any more information on this? The referenced issue has no links to applicable PRs or such, and it sounds like a significant change.

**Comment by brettcannon** [comment]
Sorry about that. Basically a bunch of defaults mean the examples used in the docs can be pruned down. The relevant templates are:

https://github.com/Microsoft/vscode-python/blob/c8db382ba8e4714fb20454560a5ae2de8af3443b/package.json#L289-L463
