### ISSUE TITLE
Doc Request: Where is the all available 'when' condition values of Contribution Points ?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#1503]
_From @ayqy on March 16, 2018 4:4_

Yes, but something related to the lack of extension document is the common case, not a certain question about my own projects.

- VSCode Version:NA
- OS Version:NA

Steps to Reproduce:

1.Search on the [official docs website](https://code.visualstudio.com/docs/extensionAPI/extension-points)
2.No related results found

Does this issue occur when all extensions are disabled?: Yes/No
Yes

FYI, related question is [here](https://stackoverflow.com/questions/38267360/vscode-extension-api-identify-file-or-folder-click-in-explorer-context-menu), but any update or official docs ?

_Copied from original issue: Microsoft/vscode#45943_

**Comment by gregvanl** [comment]
_From @eamodio on March 16, 2018 4:19_

@ayqy I doubt that this is the full list, but here is what is documented today: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

**Comment by gregvanl** [comment]
_From @ayqy on March 16, 2018 6:51_

@eamodio Thanks for your response.

>  Contribute a menu item for a command to the editor or Explorer. The menu item definition contains the command that should be invoked when selected and the condition under which the item should show. The latter is defined with the when clause which uses the key bindings [when clause contexts.](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts)

Link in above doc is what I missed then, maybe it would be a bit more conspicuous. eg. A separate section or just move the existing full list (at GET STARTED/Key Bindings) to the extension API page.

**Comment by gregvanl** [comment]
It is hidden in a large body of text. Split it up so the link is more visible in the first paragraph.

**Comment by eamodio** [comment]
It would also be great to expand the list of the contexts that are documented, because there are quite a lot more than are listed.

**Comment by gregvanl** [comment]
There's https://github.com/Microsoft/vscode-docs/issues/1491 to fill in the list. 
We've tried to keep the list manageable and not include VS Code UI specific contexts. Are there some missing contexts which you think are useful for extension authors?

**Comment by eamodio** [comment]
I think the main one I've used that is missing is `isInDiffEditor` and I'm curious how it differs from `textCompareEditorVisible` &mdash; visible vs focus?. Honestly it would be great if there was a pass taken of renaming these with some common structure/naming -- some of them can feel quite cryptic especially given that with keybindings they are user-facing. Any just my 2c ;)

While not exactly related &mdash; imo, the biggest missing documentation for extensions if the lack of `setContext` here https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

**Comment by eamodio** [comment]
Also `resourceScheme` and `resourceExtname` would also be valuable imo
