### ISSUE TITLE
HTML Highlighting for Angular Syntax in HTML

### ISSUE THREAD

**Issue by hgundogdu** [Microsoft/vscode-docs#1507]
Hi ,
I'm using vs code with angular.
Is there a any way to colorize angular syntax in html. 

For example;

"< p >{{ ' Welcome '+username }}</ p >
< button class="btn btn-primary" [disabled]="username ===''" (click)="username=''">Reset< / button >"

" Welcome [different color], username [different color], 
[disabled] [different color], username ===' '  [different color],
(click)  [different color],username=' '  [different color] " 

sorry fo rmy bad english.

**Comment by gregvanl** [comment]
Hi @hgundogdu This looks like a VS Code product question so moving to the vscode repo.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode#46290
