### ISSUE TITLE
jsconfig documentation is hidden

### ISSUE THREAD

**Issue by user135711** [Microsoft/vscode-docs#1508]
The only link that I could find for [jsconfig ](https://code.visualstudio.com/docs/languages/jsconfig) documentation is a single reference at the bottom of the [javascript ](https://code.visualstudio.com/docs/languages/javascript) language topic mixed in with the topics which **are** listed in the navigation bar on the left. If the navigation bar supports it, the topic should be a sub-link underneath the javascript. It's confusing to have an isolated topic not organized in the navbar on the left, while everything else is. It's much easier if you want to read everything or pick what to read out of everything if every link is listed in the outline.

**Comment by gregvanl** [comment]
@user135711 Unfortunately, code.visualstudio.com doesn't yet support a third-level in the TOC so we commonly leave supplemental reference pages out of the TOC and provide links in the appropriate context. For example, there are four links to the jsconfig topic in the JavaScript language topic.
