### ISSUE TITLE
Videos on Python WOW page are not sharp on hdpi screens

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1514]
https://code.visualstudio.com/docs/languages/python

**Comment by kraigb** [comment]
@brettcannon @DonJayamanne Which one of you created these in the first place? Are you able to re-record with better resolution?

**Comment by gregvanl** [comment]
@kraigb These videos were initially created by Wade, a former PM on VS Code. https://github.com/Microsoft/vscode-docs/commit/684a85f0070f6ab115df156fe09e832bfd29f226#diff-687c7ad2cc089e6e94c92b87c2cd12d9
I think he used Camtasia to record them.

**Comment by gregvanl** [comment]
Closing since the topic is doing very well (94% CSAT) so users don't seem to mind the video quality. My guess is that these videos may be getting stale after extension updates and so should be redone or replaced with images for easier maintenance.
