### ISSUE TITLE
Augment tip about the location of typings

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#152]
in https://code.visualstudio.com/docs/languages/javascript

Augment the following tip:

>Tip: If your workspace contains folders with JavaScript files that belong to separate applications, e.g, a client and a server, then consider adding a separate jsconfig.json into the corresponding folders.

Add something like: if you move the jsconfig.json to a subfolder make sure that the corresponding `typings` folder are moved to the subfolders as well, otherwise they are not part of the project.

**Comment by SteveALee** [comment]
You might also like to explicitly state typings are needed for node built in modules. I know this is more context than strictly javascript but anyone not familiar with typescript and typings is likely to get caught out when using intelligence with node.

**Comment by egamma** [comment]
We currently mention the node.d.ts in the node walk through https://code.visualstudio.com/docs/runtimes/nodejs.
@gregvanl may be you find another location where this tip would fit in.

**Comment by SteveALee** [comment]
That is a great walk through. Somehow I missed it. Perhaps as been visiting site since you launched.

BTW I used 'tsd install node' which is easier to type than given text. I've no idea if it has less functionality though.

**Comment by egamma** [comment]
> I used 'tsd install node' which is easier to type than given text. I've no idea if it has less functionality though.

This is historical, I think tsd at some point aligned the command line arguments with npm.
@gregvanl we should update the doc to use the simpler command line `tsd install node expres`
instead of 
```
tsd query node --action install
tsd query express --action install
```

**Comment by gregvanl** [comment]
Docs have been updated to use Typings rather than TSD and are using the typings command:
typings install node --ambient
