### ISSUE TITLE
Document python.jediMemoryLimit

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1529]
https://github.com/Microsoft/vscode-python/blob/3b9dd72349482a804c7c4cfad3e8a4110bfbe597/package.json#L1061-L1066

**Comment by ahmadmiz** [comment]
Thanks

**Comment by gregvanl** [comment]
@brettcannon Go ahead and label these with "python" and assign to Kraig if he'll be updating the topics.

**Comment by brettcannon** [comment]
@gregvanl I would if I could but I don't have write permissions on this repo 😉

**Comment by gregvanl** [comment]
Doh
