### ISSUE TITLE
Docs mention an event for when a visible text document is closed which doesn't seem to exist?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-docs#1542]
In the docs for `onDidCloseTextDocument` it says:

> To add an event listener when a visible text document is closed, use the TextEditor events in the window namespace.

As far as I can tell, there is no such event.

**Comment by gregvanl** [comment]
I think the comment is referring to these events https://code.visualstudio.com/docs/extensionAPI/vscode-api#_window.

**Comment by DanTup** [comment]
As far as I can tell, I'm not able to tell "when a visible text document is closed" from any of those events. There's an open issue at https://github.com/Microsoft/vscode/issues/15178 and it seems without it, it's impossible for an extension to reliable know which documents are open. As such, I think the comment in the docs is misleading. There's no reliable way to tell when a user "closes a file" (neither the concept of an "editor" nor a "document" in VS Code matches the concept on a users open file).

**Comment by jrieken** [comment]
Our definition of a text editor is a 'visible text document', in other words every document that's shown in a editor is an editor, there is no editor without a document ever. So what you are looking for is `onDidChangeActiveTextEditor` or `onDidChangeVisibleTextEditors`

**Comment by DanTup** [comment]
Is it worth changing `visible text document` to `text editor` in the docs? TextEditors and Documents in the API are very different things so often referring to an editor as a document is confusing.
