### ISSUE TITLE
Tips and tricks page loads 25MB of animated gifs

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode-docs#1543]
https://code.visualstudio.com/assets/docs/getstarted/tips-and-tricks/markdown-preview-sync.gif weighs over 4MB with a total running time of 4 secs.

![tipsntricks](https://user-images.githubusercontent.com/15158320/38294618-b9c81f9c-37eb-11e8-9b9a-1b6dc1217d18.PNG)

**Comment by oriash93** [comment]
Here are all the images in this page, sorted by size:

![image](https://user-images.githubusercontent.com/14019835/38473030-85c77ce8-3b91-11e8-9693-f72dce679383.png)

![image](https://user-images.githubusercontent.com/14019835/38473035-9b632520-3b91-11e8-9577-5a7241b6bec6.png)

![image](https://user-images.githubusercontent.com/14019835/38473045-b1cbbb42-3b91-11e8-8e7f-ab0e099aa4eb.png)

**Comment by CadenG150** [comment]
So you want this to be smaller.  By how much?

**Comment by lannonbr** [comment]
I'm not sure if this can be done with how the markdown is rendered to the docs page, but possibly a suggestion could have the images and videos be lazy-loaded using the [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) so the content would progressively load.

**Comment by gregvanl** [comment]
I've done a pass on the topic and removed some of the largest .gifs in favor of images. That shrunk the page size by about 1/3 down from 28 MB to 19 MB. Closing this issue for now as tips and tricks isn't the largest topic and it is highly rated with average 93% CSAT so users don't seem to mind waiting for the page to load. I only notice page load jumping if I navigate down the topic (via the right header navigation).
