### ISSUE TITLE
Add an anchor for each key binding

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1552]
It would allow to send anyone to a specific command (and it would show them the right keybinding for their OS).

**Comment by gregvanl** [comment]
Hi @usernamehw, I'm afraid I don't understand this issue. Is this a suggestion for the VS Code product or the documentation? If this is for the documentation, which topic are you referencing?

**Comment by usernamehw** [comment]
Docs, https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by gregvanl** [comment]
I see. We're using markdown-it to generate our HTML pages and this is just a standard Markdown table. I'm hesitant to move away from the standard rendering to create a custom table with anchors.
