### ISSUE TITLE
Update the docs once we adopt TS 1.8 and switch to Salsa

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#156]
In https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson We must update the following tip when we ship the February update with Salsa as the default, since Salsa has different defaults.

>Tip: You can exclude folders from the JavaScript project using the exclude property. By default, VS Code excludes .git, node_modules, bower_components, jspm_packages, tmp, and temp folders.

With salse the there are default excludes is  'node_modules' if there is no value defined in the jsconfig.json and the 'outdir' folder if it is defined in the jsconfig.json.

**Comment by gregvanl** [comment]
Updated in vnext for February release.
see https://github.com/Microsoft/vscode-docs/blob/vnext/docs/languages/javascript.md#javascript-projects-jsconfigjson

**Comment by egamma** [comment]
Did a quick review:

>Tip: You can exclude folders from the JavaScript project using the  exclude  property. If you do not have a  jsconfig.json  in your workspace, VS Code will by default exclude the  node_modules  folder and the folder defined by the  out  attribute.

We should add the recommend list of excludes from the Migration guide, may be we can do this in a table.
