### ISSUE TITLE
Reference macOS consistently in our docs

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#1561]
From twitter:

>code It’s not Mac OSX anymore, It’s macOS, update your description! You’re welcome! :)

We indeed have some inconsistencies

>Visual Studio Code is free and available on your favorite platform - Linux, Mac OSX, and Windows. Download Visual Studio Code to experience a redefined code editor ...

>Keyboard shortcuts for macOS - Visual Studio Code

**Comment by gregvanl** [comment]
Content pages on vscode-docs are fine but vscode-website landing pages need to be updated.
