### ISSUE TITLE
Document python.venvPath on the Python/Environments page

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1568]
https://code.visualstudio.com/docs/python/environments doesn't mention `python.venvPath` which people have bumped up against wanting previously.

(Plus that page overall probably could stand to be looked over with fresh eyes since I last made changes to it 😉 .)

**Comment by kraigb** [comment]
Brett, I added mention of venvPath in two places on environments.md and clarified it in settings-reference.md as well (see the two commits above). I think those are the two places to surface it; let me know what you think.

**Comment by brettcannon** [comment]
I'm a little worried about the phrasing of "A virtual environment located in the folder". Since the setting points to a folder that contains one or more virtual environments and not a virtual environment itself, my concern is someone will read that and go, "OK, so I just point that at my virtual environment folder", and not, "I point that at the folder that contains the folder that is my virtual environment". Does that make sense?

So `.envs`, for instance, could have `env1`, `env2`, etc., and each of those are virtual environments. So the setting should point to `.envs` and not e.g. `.envs/env1`. Since virtual environments themselves are directories I'm worried someone will mistake "located in the folder" as "the folder that is the virtual environment".

I do like where you put the clarifications, though, and the general settings wording!

**Comment by kraigb** [comment]
That's what I was asking about before, so was a little confused. I'll fix it.

**Comment by brettcannon** [comment]
Ah, sorry about that. I thought you were asking if it was a string or an array.

**Comment by kraigb** [comment]
No problem...so it's just a string with a path to a folder that contains virtual environments in subfolders. I think I got it now.

**Comment by brettcannon** [comment]
@kraigb yep, you got it! Basically some folks keep all of their virtual environments in a single location on their machine, so this setting lets them point to that directory (it's confusing because virtual environments are themselves folders).

**Comment by kraigb** [comment]
OK, try this commit: https://github.com/Microsoft/vscode-docs/commit/c56225634292e6df4a5ddba48f12d746a852ff14

**Comment by brettcannon** [comment]
Great!

**Comment by corydorning** [comment]
Would love to see https://github.com/Microsoft/vscode-python/issues/1019 implemented. :)
