### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by Dragon-Softwares** [Microsoft/vscode-docs#1573]
Hi, what is an extension to work vb, html and c#? All I need is the names. Thanks

**Comment by gregvanl** [comment]
Here is the extension identifier {publisher.extensionName} for the popular C# extension:
ms-vscode.csharp see https://code.visualstudio.com/docs/languages/csharp
I don't know of any extension specifically for VB but I think the C# extension language service also supports VB as .NET Core supports C#, Visual Basic, and F# https://docs.microsoft.com/en-us/dotnet/core/index#languages.
For HTML, there is good support in VS Code in-the-box. If you want to try client side debugging, you can look at the Chrome Debugger extension msjsdiag.debugger-for-chrome
Have a look at the VS Code Marketplace and you can see which extensions are popular and highly rated. https://marketplace.visualstudio.com/vscode

HTML
