### ISSUE TITLE
Document the Ctrl-Enter keyboard shortcut for sending selected lines to the REPL

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1576]
This will be in the next version of the Python extension. I also don't think `Run Selection/Line in Python Terminal` has any explicit documentation.

**Comment by kraigb** [comment]
Right now we don't have the REPL documented at all, in fact (e.g. even the command). I think we can add it to the editing.md file, which would be the right place for the Run Select/Line command as well. Agree? I don't think there's quite enough to break REPL out on its own.

**Comment by brettcannon** [comment]
Agreed.

**Comment by brettcannon** [comment]
Great, thanks, Kraig!
