### ISSUE TITLE
Broken link in webview.html

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-docs#1578]
Tests: https://github.com/Microsoft/vscode/issues/48453

The link to the complete code of the example is broken. It points to https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensions/TODO

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/f455d99d9e09d6a54dbc90d17b1779818788ae11
