### ISSUE TITLE
Incorrect keyboard shortcut for showCommands

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode-docs#158]
The keyboard short cut for installing a new extension is incorrect:
https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/extension-gallery.md

The docs say:
> Tip: As an alternative, press `kb(workbench.action.quickOpen)`

It should be `ctrl+shift+p`, not `ctrl+p`, however using `kb(workbench.action.showCommands)` gives the *other* keyboard shortcut, `F1`.

**Comment by gregvanl** [comment]
This is actually correct.  F1 and Ctrl+Shift+P both run the showCommands actions from where the user can use Extensions: Install Extensions to display the Marketplace extensions list.
This tip is calling out using Ctrl+P with "ext install <extension name>" to run Extensions: Install Extensions directly and filter with the extension name.
Give the Tip a try as it is a handy shortcut.
