### ISSUE TITLE
Provide documentation for moving away from bundled language packs to Marketplace language packs

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#1582]
_From @sandy081 on April 25, 2018 8:8_

Write a documentation page for moving away from bundled language packs to Marketplace language packs.

Provide me the fwd link to show it in the message.

_Copied from original issue: Microsoft/vscode#48645_

**Comment by gregvanl** [comment]
_From @dbaeumer on April 25, 2018 9:30_

@chrisdias & @danyeh can you please write the page. It should contain the following information:

- a little history about language packs and that we have them for additional languages since n months
- why we make the move. The reason is that all language should be equal (exception is our default language which will still ship out of the box).
- translation issue can be fixed independent of code fixes.

We should also make clear that in n month we will remove the bundled langauges. So users need to install the language pack then.

**Comment by gregvanl** [comment]
_From @chrisdias on April 25, 2018 18:11_

@gregvanl can you help here?

**Comment by sandy081** [comment]
@gregvanl Can I have the fwd link for this page https://code.visualstudio.com/docs/getstarted/locales until I get the correct one.

**Comment by gregvanl** [comment]
@sandy081 Here you go: https://go.microsoft.com/fwlink/?linkid=872941

**Comment by gregvanl** [comment]
@sandy081 Here you go: https://go.microsoft.com/fwlink/?linkid=872941
We can update to a subsection by H2 header link once the new content is written.

**Comment by sandy081** [comment]
@gregvanl Looks good. Thanks.
