### ISSUE TITLE
Missing workbench color

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#1587]
where: https://code.visualstudio.com/docs/getstarted/theme-color-reference

what: `editorOverviewRuler.bracketMatchForeground`

link: https://github.com/Microsoft/vscode/issues/16228

**Comment by usernamehw** [comment]
`terminal.border` is missing too 
https://code.visualstudio.com/updates/v1_21#_new-theme-colors-and-removal-of-old-colors

**Comment by usernamehw** [comment]
another one `debugToolBar.border`

**Comment by rediffusion** [comment]
Can you explain what this feature can do?

> editorOverviewRuler.bracketMatchForeground

**Comment by usernamehw** [comment]
Probably a bug - requires reload of the editor to work.

It's a color in the scrollbar when your cursor is at the matching bracket.

![Screenshot (136)](https://user-images.githubusercontent.com/9638156/73888244-56596600-487e-11ea-9354-732502094ec8.png)
