### ISSUE TITLE
Complete JSON of colorCustomizations

### ISSUE THREAD

**Issue by AndreasBackx** [Microsoft/vscode-docs#1588]
When working on a theme for VS Code you need to make sure you have looked at every single `colorCustomizations` option from the [theme color reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference). This is quite a big pain so while I was working on my own theme I "converted" the page into a JSON file so new themes can copy this and edit it easily. Is there a way this can be added to the docs and kept up to date?

[See this GitHub gist for the JSON file with comments. I don't want to spam the issue.](https://gist.github.com/AndreasBackx/ab5c7df0ef214a798cfa8fdeaf59197f)

**Comment by aeschli** [comment]
You don't necessarily need all, but I understand you want to go through each one to make sure you have covered them all.
It would be good if we can avoid having another file to maintian, so maybe we should look into an action that creates our ref (and the JSON file) automatically. @gregvanl Let me know if we have a acton that we run every release and I can try add some code that updates our ref.

**Comment by AndreasBackx** [comment]
@aeschli it would definitely be better if it could be generated automatically. The docs from the page could possibly be replicated in JSON with the docs attached (description and perhaps links to the screenshots).

**Comment by aeschli** [comment]
The `Developper: Generate Color Theme From Current Settings' command in VSCode now generates a theme file that includes all colors, commenting out the ones that have the default values.

![image](https://user-images.githubusercontent.com/6461412/40984593-8fe04a10-68e2-11e8-941f-092cac015692.png)


That will be in 1.25.

**Comment by aeschli** [comment]
As a related note, I also added a new script `scripts/test-release.sh` that fetches the latest [theme color reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference) from `vnext` and makes sure that it mentions all colors we have in our color registry.

Generating the doc file from the registry is harder as it contains screenshot and customized descriptions.

**Comment by AndreasBackx** [comment]
@aeschli sweet, thank you very much!
