### ISSUE TITLE
Document python.globalModuleInstallation

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1590]
https://github.com/Microsoft/vscode-python/blob/da91e3fd6aa40fb8c8a11514bb309028fff0ae2f/package.json#L1228

Controls whether the interpreter uses `--user` or not when installing for an interpreter (as compared to a virtual environment).

**Comment by brettcannon** [comment]
The change in the PR isn't quite right. So what the flag does is controls whether a package gets installed globally or for the user when using a globally-installed interpreter. IOW if the setting is on then `--user` is **not** used. This does not affect environments.

**Comment by kraigb** [comment]
OK, I'll update. It wasn't quite clear from your original description. :)

**Comment by kraigb** [comment]
Check the latest commit now.

**Comment by brettcannon** [comment]
The "Default behavior" explanation is reversed logic-wise. Since the flag disables the use of --user and it's set to false by default, that means --user is the default behaviour.

**Comment by kraigb** [comment]
Yeah, I've been struggling with that. :) Anyway, check https://github.com/Microsoft/vscode-docs/pull/1579/commits/cbbe898a2da0b0d80b7d90e4ef4ed0e35a757216.

**Comment by brettcannon** [comment]
Yeah, we will probably at some point take a review of our settings and their names and clean them up.

Anyway, looks great now for this setting!
