### ISSUE TITLE
apt installation instructions and https

### ISSUE THREAD

**Issue by pnorman** [Microsoft/vscode-docs#1592]
- OS Version: Debian Stretch

The instructions at https://code.visualstudio.com/docs/setup/linux call for these commands to be run:

```sh
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
```

When `apt-get update` is run, the following error occurs
```
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/InRelease  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

The https is not necessary and http can be safely used, as the package integrity is insured by the signing of packages, not transport-level security.

I would prepare a PR, but I'm on the road and can't easily do so right now.

**Comment by Tyriar** [comment]
I'd prefer to keep `https` as an additional check. If people run into the error they can always google and it and solve the problem pretty easily.
