### ISSUE TITLE
Document how other extensions can interact with the Python extension

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1597]
E.g. how can they find out what interpreter someone has selected?

Obviously need to discuss this a bit more, but I wanted to open this issue before we forgot.

/cc @Microsoft/pvsc-team

**Comment by kraigb** [comment]
Is there any more information on this yet? In the meantime, I'm going to assign to the backlog milestone.

**Comment by kraigb** [comment]
@brettcannon Just checking in if there's anything we can do with this issue.

**Comment by brettcannon** [comment]
Nope, we need to discuss things on the team and everyone is on vacation 😄 . If having this sitting open here is a problem we can move to our issue tracker.

**Comment by brettcannon** [comment]
Yeah, been a crazy two months. 😉

**Comment by DonJayamanne** [comment]
@brettcannon 	
I have introduced a format API (interface) that the extension now exposes.
Currently the API merely return a promise that lets us know whether the extension has completed loading (activation). This was added to resolve a CI issue.
We can build on that if necessary, however the bigger question is what should this API look like (what do we want to expose?)

**Comment by DonJayamanne** [comment]
could probably help [neuron](https://github.com/lorenzo2897/vscode-ipe) here https://github.com/lorenzo2897/vscode-ipe/issues/162#issuecomment-426485115
