### ISSUE TITLE
"Edit on GitHub" links are broken

### ISSUE THREAD

**Issue by kenhowardpdx** [Microsoft/vscode-docs#16]
Page URL ---> https://code.visualstudio.com/docs/editor/setup
Incorrect Edit URL ---> https://github.com/Microsoft/vscode-docs/blob/master/editor/setup.md
Correct Edit URL ---> https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/setup.md

**Comment by gregvanl** [comment]
Fixed.  Thank you for reporting the issue.

- Greg
