### ISSUE TITLE
Java Serverless tutorial

### ISSUE THREAD

**Issue by Nepomuceno** [Microsoft/vscode-docs#1612]
In the Java serverless tutorial, you say just 'behind the scene we set up a launch.json' but you don't explain at any place how can I set up that

https://github.com/Microsoft/vscode-docs/blob/master/docs/java/java-serverless.md

**Comment by gregvanl** [comment]
Hi @Nepomuceno The launch.json configuration file should be under your workspace .vscode folder. You can also open that file by clicking on the Debug view gear button.

![image](https://user-images.githubusercontent.com/12818376/40326385-06f81b78-5d0d-11e8-92a3-58daba606673.png)

The Java tutorials are under review and we'll try to make that step clearer.
