### ISSUE TITLE
Documentation for "trace" launch config arg does not match IntelliSense

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode-docs#1616]
At https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes the documentation mentions that `trace` can be set to `"all"` to enable verbose output. However, when editing the `launch.json` only `true` and `false` are given as available options.

**Comment by gregvanl** [comment]
@oliversalzburg Thanks for pointing this out.

**Comment by oliversalzburg** [comment]
Sure thing. Thanks for taking care of it :)
