### ISSUE TITLE
API docs saying !!!MISSING TYPE

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#1626]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_window

<img width="769" alt="screen shot 2018-05-22 at 7 14 41 am" src="https://user-images.githubusercontent.com/2193314/40368107-deaeaadc-5d8f-11e8-9c2b-2b9cf1227cb6.png">

**Comment by Tyriar** [comment]
Maybe there should be some CI check that prevents docs from being published if they contain missing types?

**Comment by gregvanl** [comment]
Fixed

**Comment by Tyriar** [comment]
@gregvanl @octref can it be part of the website build to ensure this doesn't happen again?

**Comment by gregvanl** [comment]
@Tyriar @octref Created vscode-website issue https://github.com/Microsoft/vscode-website/issues/759
