### ISSUE TITLE
Python: Compound debugger fails with integratedConsole

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vscode-docs#1642]
Issue Microsoft/vscode-python#1667

Creating a compound debugging session in vscode with the python extension stops after the *first* debugging item is launched with `"console": "integratedConsole"` is set. We should probably document this behaviour to allow our users to change this to `"console": "none"` or something that won't block.

/cc: @Microsoft/pvsc-team

**Comment by DonJayamanne** [comment]
I think we should fix this bug instead of updating the documentation to provide workarounds.

**Comment by d3r3kk** [comment]
That's fine, however I am uncertain whether it is a bug on the extension or the vscode debugger process itself. Where would the bug go? (Answer me tomorrow when you are back at work).

**Comment by gregvanl** [comment]
Closing since no longer a documentation issue.
