### ISSUE TITLE
VSCode is often stuck in Windows 10!

### ISSUE THREAD

**Issue by RikaLuo** [Microsoft/vscode-docs#1643]
VSCode is often stuck in Windows 10! Please tack measure to solve the problem!!!

**Comment by gregvanl** [comment]
Hi @RikaLuo From your issue description, it sounds like you want to enter an issue with the VS Code product, not the VS Code documentation. This repository is for VS Code documentation issues and suggestions. If you are still having problems, please create a new issue in the VS Code product repository https://github.com/Microsoft/vscode/issues
