### ISSUE TITLE
alias

### ISSUE THREAD

**Issue by yangmin4052** [Microsoft/vscode-docs#1644]
I can't use /etc/profile.d/aliases.sh in the terminal of vscode

**Comment by Tyriar** [comment]
Why? What happens when you try? How are you using it?

**Comment by Tyriar** [comment]
So you're on Windows? What's in your settings.json file?

**Comment by yangmin4052** [comment]
Yes, my personal computer is on windows 10,and my working computer is on windows 7. The settings.json file on my personal computer is like this
{
    "terminal.integrated.shell.windows": "D:\\Program Files\\Git\\bin\\bash.exe",
    "files.autoSave": "afterDelay",
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.copyOnSelection": true,
    "terminal.integrated.cursorStyle": "line",
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "liveServer.settings.donotShowInfoMsg": true,
    "gitlens.historyExplorer.enabled": true
}
 And the settings.json file on my working computer is like this
{
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
"workbench.iconTheme": "vscode-icons",
"workbench.colorTheme": "Monokai",
// liveServer
"liveServer.settings.donotShowInfoMsg": true,
"liveServer.settings.host": "localhost",
"liveServer.settings.port": 8078, // 端口号
"files.autoSave": "onFocusChange", // 失去焦点文件自动保存
"gitlens.advanced.messages": {
"suppressCommitHasNoPreviousCommitWarning": false,
"suppressCommitNotFoundWarning": false,
"suppressFileNotUnderSourceControlWarning": false,
"suppressGitVersionWarning": false,
"suppressLineUncommittedWarning": false,
"suppressNoRepositoryWarning": false,
"suppressResultsExplorerNotice": false,
"suppressShowKeyBindingsNotice": true,
"suppressUpdateNotice": false,
"suppressWelcomeNotice": true
},
// 关闭代码参数提示。
"editor.parameterHints": false,
"editor.wordBasedSuggestions": false,
"editor.snippetSuggestions": "top",
"emmet.showSuggestionsAsSnippets": true,
"prettier.tabWidth": 2, // 每个tab键相当于几个空格
"prettier.semi": true, // 是否每行要分号结尾
"prettier.trailingComma": "none", // 是否可以有尾随逗号
"prettier.useTabs": false, // 缩进使用tab还是空格
"prettier.singleQuote": true, // 是否使用单引号
// vetur配置
"vetur.format.defaultFormatter.js": "prettier",
"vetur.validation.template": true, 
"editor.tabSize": 2,
"editor.formatOnType": true,
"eslint.options": {},
"gitlens.keymap": "alternate",
// "editor.fontSize": 24
}

**Comment by Tyriar** [comment]
When you launch bin/bash.exe from explorer the aliases won't work either. It appears that this is what git-bash.exe does which doesn't work as a shell. So you will need to call this manually using something like `bash.exe --init-file`. See `bash.exe --help` and specify the args in `terminal.integrated.shellArgs.windows`.

**Comment by yangmin4052** [comment]
You are right. I set the settings.json file just like this and it works. Thank you very much!
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["--init-file","C:\\Program Files\\Git\\etc\\profile.d\\aliases.sh"],
}
