### ISSUE TITLE
Intellisense page links to old, abandoned extension for Rust

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode-docs#1645]
On the https://code.visualstudio.com/docs/editor/intellisense page under the "IntelliSense for your programming language" section, one of the eight icons is for the [Rusty Code](https://marketplace.visualstudio.com/items?itemName=saviorisdead.RustyCode) extension for Rust. That extension has not been maintained in a long time; it was forked once as [Rust](https://marketplace.visualstudio.com/items?itemName=kalitaalexey.vscode-rust), and even the fork has been abandoned.

It would be nice to change that link to the first-party extension [Rust (rls)](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) instead.

The souce for those icons isn't in [the page](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/intellisense.md) (`<div class="marketplace-extensions-languages-curated"></div>`) so I'm not sure what needs to be updated.

**Comment by gregvanl** [comment]
Good suggestion. The curated list is in our private website repo (handles rendering, landing pages, extension lists). I've updated to Rust (rls). Thanks!
