### ISSUE TITLE
Add a section for all when clauses

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#1658]
Currently in our docs we do not really have a list of all the `when` clauses that we have in our product.
The closest we have is a list of when clauses that are attached to keybindings here https://code.visualstudio.com/docs/getstarted/keybindings

However there are many more which are simply not attached to any keybinding by default (example: `activePanel`)
Some are also only used by extensions (example: `callStackItemType`)

fyi @weinand

**Comment by gregvanl** [comment]
Added activeViewlet and activePanel.
