### ISSUE TITLE
Add RSS/Atom feeds for blog posts

### ISSUE THREAD

**Issue by Andy-Wilkinson** [Microsoft/vscode-docs#166]
Following the move of the VS Code blog from blogs.msdn.microsoft.com to code.visualstudio.com (see https://blogs.msdn.microsoft.com/vscode/2016/02/20/the-vs-code-blog-has-moved/), there is no support for following new posts via RSS/Atom. Support for this would allow readers to easily keep track of any new posts.

**Comment by gregvanl** [comment]
Thank you for the feedback.
This feature request will be implemented in our private website sources which has an existing issue to add an RSS feed (https://github.com/Microsoft/vscode-website/issues/104).
