### ISSUE TITLE
Python docs for "Run Selection/Line in Python Terminal" lists keyboard shortcut as "unassigned"

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1660]
https://code.visualstudio.com/docs/python/editing#_run-selectionline-in-terminal-repl

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/e6f77d62fb6a440f4fc38f6f538777b6c79f9951
