### ISSUE TITLE
Document that on first run, Python's "Run Selection/Line in Python Terminal" may not work

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1661]
There's a race between VS Code sending text to the terminal and the REPL being ready to accept text. Letting people know they may need to simply run their selection again the first time if this occurs should help folks who wonder why it didn't work.

**Comment by kraigb** [comment]
@brettcannon See the commit referenced here and let me know if anything more is needed.

**Comment by brettcannon** [comment]
The only change I would suggest is go from "try the command again after waiting a few seconds."  to "try again once the REPL has finished loading."

**Comment by kraigb** [comment]
Perfect, thanks.
