### ISSUE TITLE
Document configuring PYTHONPATH environment variable

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode-docs#1664]
PYTHONPATH environment variable is used by Python to locate modules, this is crucial for:
* Debugging
* Linting
* Intellisense

This should be documented as its crucial for proper functioning of the editor (VS Code). **Note, as other IDEs document this as well.**

For instance the source could be located in the `src` folder and tests in the `tests` folder. When running the test, the tests would not be able to access the modules located in `src` without hardcoding the relative paths. The solution is to add `src` to the python path environment variable as follows `PTYHONPATH=src`.

The environment variable `PYTHONPATH` can be configured in the `.env` file as documented here in [Environment variable definitions file](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file)

**Comment by kraigb** [comment]
Let me know if you think anything more is needed.
