### ISSUE TITLE
Provide an example of how to use python.formatting.pylintArgs (and other *Args settings)

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1671]
Not sure how best to cover this, but there have been enough users confused on how best to do this that we should consider how to fix things. Examples maybe? But people consistently don't know that if there is any whitespace separating a CLI option and its value then it needs to be split into separate array strings.

**Comment by kraigb** [comment]
I scrubbed through various uses of args and clarified or added notes; see the above commit.

**Comment by brettcannon** [comment]
One potential point of confusion is the docs now say "each element of an argument string that's separated by space on the command line must be a separate item in the args list", but then has an example where spaces are left because it represents a single item on the command line:
```json
"python.formatting.yapfArgs": ["--style", "{based_on_style: chromium, indent_width: 20}"]
```

**Comment by tommai78101** [comment]
That confusion is still getting me.
