### ISSUE TITLE
update tutorials to show/reference Azure custom view

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#1673]
for example, in the [App Service Deployment tutorial](https://code.visualstudio.com/tutorials/app-service-extension/getting-started), we make reference to the "APP SERVICE EXPLORER":

![image](https://user-images.githubusercontent.com/1487073/41130732-d5a24360-6a6c-11e8-8035-ad2f648c3927.png)

It should say that the Azure View has an App Service explorer:

![image](https://user-images.githubusercontent.com/1487073/41130817-528d400a-6a6d-11e8-88e8-4691b064ae2c.png)

**Comment by gregvanl** [comment]
Fixed by https://github.com/Microsoft/vscode-docs/pull/1684
