### ISSUE TITLE
Document Sorting of imports in Python

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode-docs#1676]
Update VS Code Docs for Python for the June release.
Python VS Code extension will be adding the ability to sort imports as is possible in TypeScript and JavaScript, see here https://code.visualstudio.com/updates/v1_23#_javascript-and-typescript-organize-imports

To enable this in Python one needs to add the following setting into their `user` or `workspace` settings (`settings.json`):
```js
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
```

Feature supported added in PR https://github.com/Microsoft/vscode-python/pull/1926

**Comment by kraigb** [comment]
Cool stuff; I didn't know about using scoped settings like that. :)
