### ISSUE TITLE
Add a hint about search.useRipgrep?

### ISSUE THREAD

**Issue by imba-tjd** [Microsoft/vscode-docs#1677]
Hi. In
https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/codebasics.md#search-across-files
> VS Code does support regular expression searches, however, backreferences, lookaround, and multiline matches are not supported. This is because VS Code depends on the search tool ripgrep, which, while extremely fast, doesn't support these advanced regex features.

But I see VSC has a `search.useRipgrep` option. If it is set to false, VSC seems support those `advance search options`. Shall we add a hint about it?

Besides, there are a `search.useRipgrep` option and a `searchrg.enable` option, which make me confused...
Thanks.

**Comment by roblourens** [comment]
I keep trying to remove the old non-ripgrep search. I'm also working on allowing extensions to contribute their own search provider: https://github.com/Microsoft/vscode/issues/47058. With that API, someone can implement an extension for search that supports all the advanced regex features.

Thanks for the suggestion but I don't want to encourage anyone else to depend on `search.useRipgrep` for now. And `searchrg.enable` is temporary for switching between the builtin search and the "experimental" search that uses the SearchProvider api.

**Comment by AlexFiliakov** [comment]
search.useRipgrep doesn't work anymore

"search.useRipgrep": false; // doesn't give lookahead

The advice in https://github.com/Microsoft/vscode/issues/24626 is outdated.

**Comment by roblourens** [comment]
It works for me? But, don't count on `search.useRipgrep`, it will probably be removed soon.
