### ISSUE TITLE
Update Python code execution keyboard shortcut to be Shift+Enter

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1680]
Microsoft/vscode-python#1875

This will be in the next release of the extension.

/cc @Microsoft/pvsc-team

**Comment by kraigb** [comment]
@brettcannon Did this change already ship?

**Comment by DonJayamanne** [comment]
Yes it did. However it might change yet again

**Comment by kraigb** [comment]
Fixed by https://github.com/Microsoft/vscode-docs/pull/1702. Please open another issue when there's a change.
