### ISSUE TITLE
Black not indicated as possible option for python.formatting.provider

### ISSUE THREAD

**Issue by pzelnip** [Microsoft/vscode-docs#1686]
On https://code.visualstudio.com/docs/python/editing#_general-formatting-settings in the table it indicates that the only options for ```python.formatting.provider``` are "autopep8" or "yapf", but "black" is now a supported option.

**Comment by brettcannon** [comment]
The change was actually already made to the docs, but I believe we missed the push window for VS Code's last release, so this should be going live with VS Code 1.25.

**Comment by kraigb** [comment]
@brettcannon If 1.25 is fairly soon, then there's minimal harm leaving it as is. Or should we revert this change for the time being?

**Comment by gregvanl** [comment]
@brettcannon All the latest Python content in vscode-docs master is published so there shouldn't be any need to wait until 1.25.

**Comment by pzelnip** [comment]
Cool, if someone else has already done the change, by all means feel free to decline my associated PR.  Thanks!

**Comment by brettcannon** [comment]
The confusion is all on my end as that section of the docs mentions Black multiple times and there's a sentence that nearly mirrors the line in the table that @pzelnip has a PR to fix. The PR is accurate and should go in.
