### ISSUE TITLE
TreeDataProvider doesn't exist in javascript project

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode-docs#1696]
I followed this link https://code.visualstudio.com/docs/extensions/yocode to create a vscode plugin project in `javascript`. I want to use TreeDataProvider to create a tree view but this class is not found from vscode module.

`const { TreeItemCollapsibleState, TreeDataProvider } = require('vscode');`

The above code return undefined to TreeDataProvider. Below is my package.json dependencies:
```
"devDependencies": {
    "@types/mocha": "^2.2.42",
    "@types/node": "^7.0.43",
    "eslint": "^4.11.0",
    "typescript": "^2.6.1",
    "vscode": "^1.1.17"
  }
```

**Comment by sandy081** [comment]
What is the vscode version value you have in `engine` property?

**Comment by sandy081** [comment]
`TreeDataProvider` is an interface and you can get them using require in Javascript. You have to create the data provider and register it using

`vscode.window.registerTreeDataProvider`

**Comment by zhaoyi0113** [comment]
Do you mean `can` or `can't`? 

I have used `vscode.window.registerTreeDataProvider` to register my tree data provider. But what is the method I can use to re-render the tree view? I see in typescript, people has below code:

```
public readonly onDidChangeTreeDataEmitter: vscode.EventEmitter<TreeItem | null> =
        new vscode.EventEmitter<TreeItem | null>();
    public readonly onDidChangeTreeData: vscode.Event<TreeItem | null> = this.onDidChangeTreeDataEmitter.event;

```
Is there any way for me to fire an event to refresh the whole tree view in `javascript`?

**Comment by sandy081** [comment]
Sorry you can't.

Yes, you have to fire an event from your data provider.

**Comment by zhaoyi0113** [comment]
Hi, do you have a sample for me to look at how to fire that event in javascript? The code I pasted in the previous post is for typescript. How does the event work with vscode? Who will listen on this event?
Thanks,
Joey

**Comment by sandy081** [comment]
Sorry.. we only have Typescript samples. You can may be see the generated code in the out folder in the sample extension

**Comment by zhaoyi0113** [comment]
yes I have looked at your sample which was written in typescript. I wonder what kind of the event I need to fire in order to let the treeview re-render. Is there a document the describe this logic? Like who will listen on this event, and event structure etc.
