### ISSUE TITLE
Update locales.md for 1.25

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-docs#1697]
With 1.25 we stop shipping bundles languages except English. From now on forward all languages come through language pack support from the market place.

We should update above document accordingly. Here is the update path which we should mention in the document as well:

- if a user updates from 1.22 or older to 1.25 the UI will start in English and the user is prompted to install the corresponding language pack
- if a user updates from 1.23 or 1.24 to 1.25 then he already got prompted to install the language pack for the UI language of his choice. If he did so, 1.25 will start as normal and the UI is presented in the chosen UI language. If he didn't install the language pack he will now be prompted to do so.
- if he freshly installs 1.25 or a newer version VS Code will prompt to install a corresponding language pack if available in the market place.

**Comment by dbaeumer** [comment]
@sandy081 please check above rules.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/572f5a63c628ec28afc1260d488933529035125e#diff-d60a27bb3a8302c832dbd7a46bf9843d
I opted to not include the update path section in the main doc since most users should just be able to follow the prompt if they need to install a Language Pack.
