### ISSUE TITLE
Example Language Server should not show the debug adapters

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#1704]
https://code.visualstudio.com/docs/extensions/example-language-server#_testing-the-language-server

![image](https://user-images.githubusercontent.com/172399/42183835-91bcfd58-7e43-11e8-8c9e-5987472cf18f.png)

**Comment by octref** [comment]
@egamma You are looking at the current master version. it should be the one on vnext:

![image](https://user-images.githubusercontent.com/4033249/42190252-e4abe412-7e10-11e8-914e-249297856cba.png)

**Comment by AvatarWeb1** [comment]
2018-07-02 18:59 UTC−04:00, Pine <notifications@github.com>:
> Closed #1704.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Microsoft/vscode-docs/issues/1704#event-1712715461


-- 
*    Merci pour votre           collaboration*
*   a bientôt j'espère.                               //TiLou//
 Martin Theriault*

**Comment by AvatarWeb1** [comment]
triplebyte.com
