### ISSUE TITLE
Surface log point support for Python extension

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1707]
@DonJayamanne wrote https://medium.com/@don.jayamanne/inspecting-variables-in-python-apps-using-python-debugger-in-vs-code-without-any-code-changes-7e5432d8dd39 to help document support for log points since people ask about this regularly, probably because they read the Python extension docs and then don't bother reading the general VS Code docs. Might be worth either linking to the generic docs more widely or having a Python-specific example.

/cc @Microsoft/pvsc-team

**Comment by kraigb** [comment]
I've added some notes about logpoints within the context of the current docs + experimental debugger. I'll edit again when the debugger change happens (which I'm tracking separately from GH issues here).
