### ISSUE TITLE
Silent (unattended) installation switches. 

### ISSUE THREAD

**Issue by AndresPae** [Microsoft/vscode-docs#1714]
Those are missing from doc. Luckily /? reveals most of them, but even with running /VERYSILENT /NOREBOOT VScode starts automatically.
Adding  /mergetasks=!runcode helps with  NOT opening vscode automatically.

**Comment by AvatarWeb1** [comment]
👽😍😍👽Studio Avatar Web Presente. Pour Confection De Site Web Et Création En Animation 3D Mon nom est Martin Thériault StudioAvatarWeb@Gmail.Com Développeur Web et concepteur 3D 👽😍😍👽

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-docs/pull/1723
