### ISSUE TITLE
Provide a better explanation between launch and attach debug configurations

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-docs#1717]
We should provide a better explanation between launch and attach debug configurations in https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

Proposal text from LogPoints blog post:

In VS Code we have two core concept for debugging: Launch and attach-configurations, which caters to two different workflows and segments of developers. Depending on which segment you belong to, it can be confusing to determine what kind of debug configuration you need for your project.

If you come from a browser DevTools background you aren't used to the concept of "launching from your tool", as your browser instance already is open, and when opening DevTools you simply attach DevTools to your browser tab. On the other hand, if you come from a Java background it's quite normal to have your editor launch your Java process for you, and have your editor attaching its debugger to the newly launched process.

The best way to explain the difference between launch and attach is think about launch configurations as a recipe for how to start your app in debug mode before the VS Code attaches to it, while an attach config is a recipe for how to connect VS Code's debugger's to an app or process that's already running.

The value of launch configurations is to give you a way to offload some of the cognitive overhead of launching your app with the right debugging paramaters by creating a configuration that's easy repeatable and sharable with your project and team.

**Comment by HamzaMateen** [comment]
To this day, I don't think that this explanation has been added!
