### ISSUE TITLE
Typo in variable name in tutorial

### ISSUE THREAD

**Issue by ManuInNZ** [Microsoft/vscode-docs#1741]
in the Python Flask tutorial, there is a small typo on the variable name when introducing the CSS use.
`<span class="message">{{ message }}</span>. It's {{ date.strftime("%A, %d %B, %Y at %X") }}.`
should still be using name as variable.
`<span class="message">{{ name }}</span>. It's {{ date.strftime("%A, %d %B, %Y at %X") }}.`

**Comment by kraigb** [comment]
@ManuInNZ Thanks for pointing that out. I've made a fix, which should propagate soon.
