### ISSUE TITLE
New VSTS link in Publishing extensions page is dead

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode-docs#1747]
In https://code.visualstudio.com/docs/extensions/publish-extension#_publishing-extensions, at 
```
First, make sure you have a Visual Studio Team Services account.
```
The link for VSTS, https://docs.microsoft.com/vsts/accounts/create-account-msa-or-work-student, gives a 404

**Comment by gregvanl** [comment]
@JacksonKearl Seems to be working now. It is redirecting https://docs.microsoft.com/en-us/vsts/organizations/accounts/create-organization-msa-or-work-student now.

**Comment by JacksonKearl** [comment]
Indeed it is
