### ISSUE TITLE
Python: mpl_toolkits.mplot3d and matplotlib.inferno

### ISSUE THREAD

**Issue by MarkyMark1000** [Microsoft/vscode-docs#1757]
I am reasonably new to Python, so please forgive any mistakes.

I have installed Anaconda3 into the following area on my Mac:
/anaconda3/.....

I can run the following code on visual studio code and it appears to work, however there are 2 problems:
1 - With the import statement for mpl_toolkits.mplot3d, it is saying "Unable to resolve 'mpl_toolkits.mplot3d', intellisence may be missing for this module"

2 - The piece of code that contains facecolors=cm.inferno(G) is highlighting the cm with a red underscore and saying:
[pylint] E1101: Module 'matplotlib.cm' has no inferno member.

It seems to me that there is something wrong with vs code linting, because the code actually works when I run it.   [ Anaconda Custom (64 bit) Python 3.6.6 (base) ]

Unfortunately it is highlighting my file red and saying that there are 2 problems with this file, which is very unpleasant and I am unsure how to fix it.   The code also works when I run it in Spyder.   

[Please ignore the comment saying #THIS DOESN'T WORK IN VS Code, but works in Spyder.   It does work in both when I run it.]

Code for SurfacePlot3D.py:
-------------------------------------------------------------
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

X, Y = np.meshgrid(np.arange(-100, 100), np.arange(-100,100))
Z = X ** 2 + Y ** 2

G_x, G_y = np.gradient(Z)
G = np.sqrt(G_x**2 + G_y**2)
G = G / G.max()

#Figure contains all of the objects in the plot
fig = plt.figure()
#Get the axes of the plot
ax = Axes3D(fig)
#THIS DOESN'T WORK IN VS Code, but works in Spyder
#Uncomment the following line to plot the surface.
ax.plot_surface(X,Y,Z, facecolors=cm.inferno(G))
#Show the Plot
plt.show()

**Comment by kraigb** [comment]
@MarkyMark1000 Thanks for your issue. Because the repo here covers only documentation for VS Code, you need to file this issue on https://github.com/Microsoft/vscode-python/issues, which is the repo for the Python extension, specifically. I'm closing this one in the meantime.
