### ISSUE TITLE
More info for certain keybinding commands wanted

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode-docs#1760]
With the introduction of sub-word support, I went to modify/optimize my keyboard mappings.

And I found this mapping in the defaults. I wonder what might it do, since trying the shortcut in `ctrl+p` panel seemed to do nothing.

```
{ "key": "alt+left",              "command": "workbench.action.quickInputBack",
                                     "when": "inQuickOpen" },
```

There are other exotic commands that are difficult to understand / imagine what they do.

**Comment by gregvanl** [comment]
Hi @ackvf, the quickInputBack command isn't currently used by any of the out-of-the-box VS Code UI. It is there for extensions when they start using the new Quick Input flow. Unfortunately, I don't know of any extension which currently uses Quick Input. There is a sample which demonstrates Quick Input. https://github.com/Microsoft/vscode-extension-samples/tree/master/quickinput-sample.

**Comment by ackvf** [comment]
Thanks for clarification.
