### ISSUE TITLE
Feb Release notes (vnext branch) salsa instructions refer to January

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#177]
testing https://github.com/Microsoft/vscode/issues/3170

from the release notes for feb, in the vnext branch, still refers to January:

The JavaScript language service in VS Code has always been powered by TypeScript. We are now migrating to a new JavaScript language service implementation called Salsa. Salsa will become available with TypeScript 1.8 **but for the January update, we are providing way to preview Salsa in VS Code.**

**Comment by gregvanl** [comment]
The February release notes have been updated and reviewed.
