### ISSUE TITLE
`kb(search.history.showNext)` is mapped to `unassined`

### ISSUE THREAD

**Issue by zhengwx11** [Microsoft/vscode-docs#1770]
`kb(search.history.showNext)` is mapped as `unassigned`, which should be something like `↓`.
<img width="701" alt="default" src="https://user-images.githubusercontent.com/7693630/43756594-fbf2bc56-9a47-11e8-863c-5828e8a91c74.png">

**Comment by gregvanl** [comment]
Thanks for pointing this out!
