### ISSUE TITLE
Matplotlib installation

### ISSUE THREAD

**Issue by Kort94** [Microsoft/vscode-docs#1774]
Hi, I cannot install matplotlib via my terminal. see error message below.
_pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ pip install matplotlib_

**Comment by kraigb** [comment]
What system are you running on? Also, does the "python" command work ("python3" on macOS/Linux)?

**Comment by blackhal0** [comment]
I get the same thing. 

I am on Win10, I installed Python 3.7 prior to installing VS Code (which adds Python to the PATH upon installation , if marked to do so)

I can open a Command Prompt, type 'Python' and get the following:

Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

VS Code seems to use Power Shell as the terminal, and even if I switch over to Command Prompt and type 'python' I get an error:

'python' is not recognized as an internal or external command,
operable program or batch file.

Thus following the tutorial located at https://code.visualstudio.com/docs/python/python-tutorial

Thus (for Win 10) Opening a terminal and typing "pip install matplotlib" does not work. I must do this by opening a Command Prompt window via Start> 'CMD'

**Comment by Kort94** [comment]
I am using Windows 10, I will try out @blackhal0 suggestion and see if it works.

**Comment by Kort94** [comment]
it still does not work, but anyways, I will use Anaconda as an interpreter for now

**Comment by kraigb** [comment]
@scottpschneider does "pip3" instead of "pip" work?

**Comment by scottpschneider** [comment]
Just tried, still not recognized.  Thank you for the response, I am searching through google for any other solutions..  Thanks again!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by KevYChen** [comment]
I just figured out the problem, I uninstalled python then reinstalled it with the "link to path" option checked during installation. Seems like that did the trick and now I'm able to install using pip install matplotlib in the terminal.

**Comment by kraigb** [comment]
@dhermes made edits in https://github.com/Microsoft/vscode-docs/pull/1816 to change the commands to install matplotlib to the following, which don't rely on PATH environment variables and should address the issues here. If this is not the case, please reopen.

Windows: py -m pip install matplotlib
Linux/MacOS: python -m pip install matplotlib

**Comment by ikhall** [comment]
kraigb that worked perfectly without doing anything else.
This also worked after changing "python" to "py"
python -m pip install --upgrade pip

Thanks
