### ISSUE TITLE
some python debugging instructions are not valid anymore

### ISSUE THREAD

**Issue by choeffer** [Microsoft/vscode-docs#1780]
First Part:

As written here:
https://code.visualstudio.com/docs/python/environments#_choose-a-debugging-environment

"Although selecting a different environment changes the python.pythonPath value in your Workspace settings.json file, it doesn't affect the User settings.json file, which is used by default for debugging. You can also specify an interpreter for debugging using the pythonPath in a debugger configuration in the launch.json file. See Debugging."

is not valid anymore. The debugger uses the selected interpreter in the workspace settings also for debugging, even if in the user settings a different interpreter is selected.

I created a venv, in this installed the package matplotlib with pip3, then created a file test.py which inherits:
'
import matplotlib

print('test')
'
My workspace settings are:

'
{
    "python.pythonPath": "${workspaceFolder}/env/bin/python"
}
'
My user settings are:
'
{
    "python.pythonPath": "/usr/bin/python3",
    "python.autoComplete.addBrackets": true
}
'
And with "Run Python File in Terminal" and "Start Debugging" I get no errors, even if matplotlib is just installed in the venv and not in the global python3 environment.
So the statement in the documentation is not valid anymore.

Second part:

Also in https://code.visualstudio.com/docs/python/debugging
"
Note: The debugger settings don't support relative paths, including when relying on the main python.pythonPath setting. To work around this, use an environment variable, or create a variable such as ${workspaceFolder} that resolves to your project folder, then use that variable in the path, as in "python.pythonPath": "${workspaceFolder}/venv/bin/python".
"
is not valid anymore. Because the same setup like above also works with just relative paths without producing any error.

With this workspace settings:

'
{
    "python.pythonPath": "./env/bin/python"
}
'
I am on Debian Stretch with VSCode installed from the MS repository and used the instruction in the offical documentation.

**Comment by gregvanl** [comment]
@brettcannon Do you want to take a look at this since Kraig is out.

**Comment by brettcannon** [comment]
@gregvanl we will have a look next week

**Comment by brettcannon** [comment]
So @choeffer is correct on both counts. There are some other things that Kraig doesn't have in his PR related to debugging as well, so I can roll this in to my PR that will stack on top of his.
