### ISSUE TITLE
Improvements to the Extensions page

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-docs#1786]
The below are a few suggestions to improve https://github.com/Microsoft/vscode-docs/blob/298332ba2e8ad312f673389f462ffb800d403d66/docs/editor/extension-gallery.md

- The extensions viewlet is said to show the most popular extensions. But for users with 1 or more installed extensions, the viewlet shows Enabled, Recommended and Disabled extensions
- `you'll see an Reload button which will prompt you to restart VS Code`. This implies that clicking on the button will result in a prompt which is not the case.
- **Extension Details** Here we refer to it as `extension details window` but previously we say `You can click on the extension item to display the extension's VS Code Marketplace page where you can learn more.` The previous reference should use the term `Extension Details` page/window
- **Extension Pack**: This is changing with the current version of 1.26
- **Extensions view commands**: "More" is now "More Actions..."
- **Search for an extension**: Note that if you are using the id of the extension, you will have to use `@id:`. People often copy paste the extension id from other docs and not see any results
- **Search for an extension**: A link to filters from here can be helpful
- **List installed extensions**: `By default, the Extensions view will show your installed extensions`. Nope, we show Enabled by default
- **Uninstall an extension**: The image needs an update. It should show the Enabled extensions not Installed
- **Disable an extension**: How a about combining Uninstall and Disable? The same image can be re-used between the 2? 
- **Extension auto-update**: Needs an update to include the new setting `extensions.autoCheckUpdate`
- **Update an extension**: Rename this to `Update an extension manually` and include the point that if you have disabled both `autoUpdate` and `autoCheckUpdate`, then you can run `Check for Updates` to first see which extensions need update, and then update them
- **Command line extension management**: `show-versions` and `extensions-dir` is missing. Instead of the code sample in the example, why not show an image of the Extensions Management section of `code -h`? This will include docs for all the switches.
- **Extensions view filters**: Needs update as per 1.26

**Comment by JacksonKearl** [comment]
@gregvanl I've been working through these, I can put up a PR in a bit?

**Comment by gregvanl** [comment]
@JacksonKearl Sure, whenever you are ready.
