### ISSUE TITLE
Reduce size of repo

### ISSUE THREAD

**Issue by dht** [Microsoft/vscode-docs#1789]
I wanted to change a small code example in the autocompilation of Scss. I gave up after 15 minutes of cloning and reaching 21% and 350mb. Perhaps git is not the best way for developing the docs, as old versions are bound to be inferior to the latest and greatest, or perhaps it would be better to archive old commits from time to time.

Great job to all contributors of docs and editor alike. I just migrated from Webstorm and I am in love ;-)

**Comment by octref** [comment]
This makes sense. We have a lot of images here that's taking up space. They seldom change and can be stored somewhere else than git.

Meanwhile, you can try to use `git clone --depth=1`, or make changes directly to MD files on GitHub.

**Comment by vipulgupta2048** [comment]
How about using Cloud services to store and parse images onto web pages. Everyone knows git isn't the best when it comes to large media/binary files. We can shift all the content and add placeholders in their places.

**Comment by octref** [comment]
We tried git-lfs. This isn't really doable without compromising our workflow, so unfortunately the only way to contribute to vscode-docs without downloading the whole repo is to make change on GitHub interface.

**Comment by bpasero** [comment]
I really suffer from this too....

**Comment by octref** [comment]
This also slows down CI, will try to get a fix on debt week.

**Comment by octref** [comment]
We switched to LFS. You can now use https://github.com/Microsoft/vscode-docs#cloning which clones the 16MB text files, and pulls in images on demand.
