### ISSUE TITLE
Update the 'learn more' link for user level install 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#1790]
https://code.visualstudio.com/updates/v1_25#_user-setup-for-windows

The doc still talks about that this is only available for insiders. I suggest to also mention that settings and extensions will be preserved when doing the update (the question came up on twitter several times).

![image](https://user-images.githubusercontent.com/172399/44082639-1b18b698-9fb2-11e8-8b3c-8bb6b831caeb.png)

**Comment by joaomoreno** [comment]
Fixed.
