### ISSUE TITLE
Document new menu colors

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-docs#1799]
The following colors need to be documented in the color reference:

https://github.com/Microsoft/vscode-docs/blob/vnext/docs/getstarted/theme-color-reference.md

      -  "menubar.selectionForeground: Foreground color of the selected menu item in the menubar."
      -  "menubar.selectionBackground: Background color of the selected menu item in the menubar."
      -  "menubar.selectionBorder: Border color of the selected menu item in the menubar."
      -  "menu.foreground: Foreground color of menu items."
      -  "menu.background: Background color of menu items."
      -  "menu.selectionForeground: Foreground color of the selected menu item in menus."
      -  "menu.selectionBackground: Background color of the selected menu item in menus."
      -  "menu.selectionBorder: Border color of the selected menu item in menus."

**Comment by gregvanl** [comment]
Fixed in vnext since new menubar is still in preview.
https://github.com/Microsoft/vscode-docs/commit/773ff60e323aff706132dfa406870ca95ddd4be6
