### ISSUE TITLE
update extension-manifest doc for license

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#180]
can we update http://code.visualstudio.com/docs/extensionAPI/extension-manifest to make it clear how to specify `license` in `package.json` so that the Marketplace will scrape it and be at the endpoint of the LICENSE button in the Command Palette (in Feb2016 drop of VS Code)?

Docs: https://docs.npmjs.com/files/package.json#license

You need to set the license property in package.json to this:

```json
"license" : "SEE LICENSE IN <filename>"
```

**Comment by gregvanl** [comment]
Joao has added this in vnext 
https://github.com/Microsoft/vscode-docs/commit/9bce91c090f2ffb31a72bb64a8df2a696a82ab22

**Comment by chrisdias** [comment]
:)
