### ISSUE TITLE
Documentation should be updated for Typings now that TSD is deprecated.

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#181]
_From @Elusive138 on February 22, 2016 6:16_

The VS Code documentation still contains instructions for TSD: https://code.visualstudio.com/Docs/runtimes/nodejs

TSD is now deprecated and listed as such (warning on install) on npm: https://github.com/DefinitelyTyped/tsd/issues/269

Typings is the replacement.

VS Code's documentation probably should probably be updated to reflect this change.

_Copied from original issue: Microsoft/vscode#3225_

**Comment by egamma** [comment]
_From @jpierson on February 24, 2016 22:14_

Is there any compatibilities using [typings](https://github.com/typings/typings) instead of _TSD_ with VSCode?

**Comment by egamma** [comment]
I spent some time on this and using 'typings install --ambient xxx' is the backward compatible way to do this.

We should do this change to:
- docs @gregvanl 
- vscode-sample @chrisdias 

moving to vscode-docs.

**Comment by Elusive138** [comment]
Couple of bugs:

/docs/runtimes/nodejs.md:82 link to DefinitelyTyped repo has a typo in the org name (`DefinitelyType`) resulting in a broken link

/release-nodes/latest.md:46 tip for installing `react-global` is missing the `--ambient` flag and won't work

**Comment by gregvanl** [comment]
Thanks for catching this (said sheepishly).

**Comment by chrisdias** [comment]
@gregvanl you are definately not alone...

* http://www.d-e-f-i-n-i-t-e-l-y.com/
* http://www.telegraph.co.uk/education/educationnews/5538890/Definitely-is-most-commonly-misspelt-word.html
* http://spellingtrouble.blogspot.ch/2014/10/definitely-or-definately.html

:)
