### ISSUE TITLE
ES6 / React docs

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#182]
I have been working on an ES6 / React project and found the documentation lacking for setting up VS Code to work well. There are a few strings to pull to get syntax highlighting to work correctly. See [this issue](https://github.com/Microsoft/vscode/issues/2394) for the discussion and suggestions. 

FYI - @egamma

**Comment by kristianmandrup** [comment]
Does anyone have a step-by-step guide to setup VScode for ES6+ and React/React Native? Thanks :)

**Comment by gregvanl** [comment]
Closing in favor of more recent issue https://github.com/Microsoft/vscode-docs/issues/484
