### ISSUE TITLE
First screen shot of Getting Started is outdated

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-docs#1822]
Since a while we sort completion proposals by how well they match (not just highlighting the best match). We should update that screen shot

<img width="891" alt="screen shot 2018-08-30 at 12 54 15" src="https://user-images.githubusercontent.com/1794099/44847465-e049dc00-ac53-11e8-9627-54d63fca03e1.png">

**Comment by oriash93** [comment]
![image](https://user-images.githubusercontent.com/14019835/45446817-82e36f80-b6d6-11e8-86be-859d054316f2.png)

I created something similar, I hope it is good enough.

**Comment by CyberiumShadow** [comment]
Had a look around, that specfic image is hosted at Microsoft/vscode-website which is Organisation-access locked.

So we need the Microsoft team to update it on thier side

**Comment by gregvanl** [comment]
Image updated
