### ISSUE TITLE
Document PowerShell language development

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-docs#1823]
This proposal is to add a section for PowerShell within this list and not simply a PowerShell page under the Language section. I believe there is enough content needed for PowerShell development that warrants more details than a simply getting started in the language section with Python.

![image](https://user-images.githubusercontent.com/11204251/44963673-b01f6900-aef1-11e8-9c5d-a5d881aab495.png)

PowerShell being a main language for Microsoft products and with Azure management it warrants building out content so users can see how to get started with PowerShell development. I would propose the initial layout for pages to get started:

```
PowerShell
├── Extension
├── Editing Code
├── Plaster
├── PSScriptAnalyzer
├── Pester
├── Debugging
├── Settings Reference
```

**Comment by DareDevelOps** [comment]
Have a look [DareDevelops VSCode Docs](https://github.com/DareDevelOps/vscode-docs/blob/lang-PowerShell/docs/languages/powershell.md)

**Comment by wsmelton** [comment]
My proposal is to have much more detail than what should go on one language page. We need a section just like Python and Azure.

**Comment by gregvanl** [comment]
@wsmelton and @DareDevelOps, it's great to see interest for PowerShell in VS Code. From the comments and ratings I've seen, the PowerShell extension well liked. As you know, our TOC is limited to two levels and so TOC real estate is at a premium and we're trying to keep the TOC, and doc set in general, pretty tight. At this point, VS Code isn't ready to have PowerShell be a full TOC node but we're very happy to have a topic under Languages as @DareDevelOps has provided. We'd prefer to have extension specific content go in the extension README or GitHub repo (as Markdown docs or wiki). We track file type usage and .ps1 is still pretty far down the list (compared to other languages like python and java). 
I'm not a PowerShell expert so I may not understand the need for documentation that should live outside the PowerShell extension repo.
Again, we'd be happy to see a new topic under Languages. Also the advantage of having more details and links in the extension README is that it is viewable from within VS Code on the Extensions details page, users don't need to search or bookmark a topic in code.visualstudio.com

**Comment by wsmelton** [comment]
So just from curiosity then what warrants a language or extension getting real estate in the TOC? Why does Azure really need documentation on this site, Azure Login extension just is under 900k and other Azure extensions have not even broken 500k yet. Powershell has had 3.9 million downloads to date!

**Comment by rismoney** [comment]
Simple solution here - move node, JavaScript, python, and Java under languages
Create new cloud TOC, and put Azure in there.  Reserve spaces for AWS, GC, etc.
End this nonsense and focus on meaningful stuff.

**Comment by potatoqualitee** [comment]
This "nonsense" is meaningful to us. Otherwise, solid proposal.

**Comment by gregvanl** [comment]
The PowerShell hub on docs.microsoft.com would be a good location for more in-depth topics https://docs.microsoft.com/en-us/powershell/. The VS Code site Languages/PowerShell topic can provide links (Next Steps, etc).

**Comment by potatoqualitee** [comment]
Can you address @rismoney's proposal, @gregvanl ? I think Microsoft not showing preferences via TOC would be beneficial to the adoption of non-preferred languages.

**Comment by gregvanl** [comment]
Hi @potatoqualitee, @rismoney, unfortunately the VS Code website is currently limited to a two level TOC. I agree it would be better to have a deeper TOC under Languages and then program language specific content could live there.

**Comment by gregvanl** [comment]
A website TOC which allows arbitrary depth (like docs.microsoft.com) would be nice and could support nesting deep subject content. This would allow a tree under Languages each with it's own detailed content. The VS Code website doesn't currently support more than a two level TOC.

**Comment by potatoqualitee** [comment]
I understand then that the answer is no. I also understand Microsoft's emphasis on Azure, and that the Azure TOC cannot change until the website supports nesting.

Until then, is it possible to give Python, Java, Node, etc the same treatment as PowerShell? They all go under languages and just get one link as well?

Visibility is important and the current TOC suggests that some languages are more important than others.

**Comment by KevinMarquette** [comment]
The PowerShell team and PowerShell community have adopted VSCode as the official editor for PowerShell. Microsoft has even depreciated the ISE in favor of VSCode.

**Comment by sdwheeler** [comment]
I think there should be a PowerShell page under the Languages node of the TOC, as a start. Let's get that built and start feedback on that. If we need more in-depth content then we should probably discuss that in the PowerShell-RFC repo or the PowerShell-Docs repo.

**Comment by wsmelton** [comment]
@sdwheeler why is documentation specific to VS Code relevant to PowerShell-Docs? This is not about how to use PowerShell but the extension specific to how it works and is utilized within VS Code.

As well, lets take Azure out of it. Python has a whole flipping tutorial...a tutorial. Another extension that is not even close to 500k downloads.

**Comment by sdwheeler** [comment]
@wsmelton There are several factors that contribute to the decision of where the content should go. I am saying that the VS Code docs should have a PowerShell page under languages. Let's start there. 

Creating detailed content beyond that is not always easy. We need an owner to create and maintain that content, regardless of where it lives. I am offering the PowerShell-Docs and PowerShell-RFC channels as a place for discussing this with the PowerShell team. If there is enough demand from the community then the team is more likely to allocate the resources.

**Comment by SteveL-MSFT** [comment]
@sdwheeler if you look at the link above https://github.com/DareDevelOps/vscode-docs/blob/lang-PowerShell/docs/languages/powershell.md, we already have community members ready to help contribute documentation.  We just need a place to put it where VSCode users can easily find it.

**Comment by DareDevelOps** [comment]
Why not redirect any/all in depth docs to docs.microsoft.com/topic? if real estate plot size is the issue. I would think all "Docs" would generate from there to begin with. This would reserve local real estate for product specific information.

**Comment by kilasuit** [comment]
My take is that there's no issue in adding PowerShell in under Languages here but some further confusion was caused by the last part of the issue where the suggested content for the PowerShell Page was shown with it's own TOC

Now with @sdwheeler comment about the TOC's is correct in the LEFT hand side - however individual pages also have their TOC in the right like below for the JSON page at https://code.visualstudio.com/docs/languages/json#_hovers
![sketch](https://user-images.githubusercontent.com/6355225/45224019-cb52f580-b2b0-11e8-90ac-f548b7569148.png)

So the PR to fix this should do as suggested by @potatoqualitee said here -https://github.com/Microsoft/vscode-docs/issues/1823#issuecomment-419091890

**Comment by wsmelton** [comment]
Well...let's just say I'm a third grader and want to know why Jimmy ('Python') gets top shelf treatment (in both top-level TOC and in languages), but I don't ('PowerShell')

**Comment by octref** [comment]
I work on the VS Code website and I don't think adding PowerShell to top-level TOC is a good idea:

- There are C++, C#, Go, Vue (Vetur), PHP that have more downloads than Powershell. They aren't in the top level TOC either.
- Extension docs could live very well in GitHub repositories. See https://marketplace.visualstudio.com/items?itemName=octref.vetur and https://vuejs.github.io/vetur.
- Adding it to `/Languages` as a topic makes sense, too.

**Comment by rismoney** [comment]
I'm sorry for participating.  I think I'm too pragmatic for this type of project and will find something else to dip my feet into.  Good luck all.

**Comment by gregvanl** [comment]
New PowerShell topic is live at https://code.visualstudio.com/docs/languages/powershell
