### ISSUE TITLE
Contributing to website design

### ISSUE THREAD

**Issue by iinfin** [Microsoft/vscode-docs#1825]
A private repository for VSCode website is mentioned [here](https://github.com/Microsoft/vscode-docs#publishing), why not make the main parts of it public too? I'd like to contribute to design by making both main and docs website better aligned to Fluent Design System.

**Comment by gregvanl** [comment]
Hi @iinfin, thank you for your interest in the VS Code website. At this point, we are keeping the website repo private. If you have specific suggestions for improvements, please feel free to let us know.
