### ISSUE TITLE
vscode Occasionally no extensions can be found

### ISSUE THREAD

**Issue by Ckefan** [Microsoft/vscode-docs#1843]
No extension found
![image](https://user-images.githubusercontent.com/23022046/45344498-7677ed80-b5d6-11e8-8bd5-c23556fa1323.png)

![image](https://user-images.githubusercontent.com/23022046/45344559-9c04f700-b5d6-11e8-9e14-79915a41bf11.png)

**Comment by gregvanl** [comment]
Hi @Ckefan, this is the repository for VS Code documentation. If you are seeing a VS Code product issue, you can enter an issue at https://github.com/Microsoft/vscode/issues.
One question: Do you have any extensions installed? You would see this behavior if you have a clean VS Code without any extensions.
