### ISSUE TITLE
Why is my vscode display not supported?

### ISSUE THREAD

**Issue by IngersollM** [Microsoft/vscode-docs#1846]
My vscode is the latest version, and today I found it showing Unsupported. How should I solve it?
![image](https://user-images.githubusercontent.com/40142112/45426382-a5718a80-b6ce-11e8-874b-43e351f250a0.png)

**Comment by gregvanl** [comment]
Hi @IngersollM [Unsupported] in the title bar means that you are running a patched version of VS Code and not a pure install. Uninstall your current version of VS Code and reinstall to clear this message.
Did you do anything to modify your install of VS Code such as install an extension or run a script?

**Comment by gregvanl** [comment]
@IngersollM Thank you as well. You helped me spot a documentation gap as we didn't mention the [Unsupported] text in the title bar.
