### ISSUE TITLE
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by AMDphreak** [Microsoft/vscode-docs#1849]
Mac OSX:

```
Installing collected packages: futures, singledispatch, backports-abc, tornado, nose
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/futures-3.2.0.dist-info'
```

Full log
[https://pastebin.com/9BpP5she](https://pastebin.com/9BpP5she)

I'm following the start tutorial:
[https://code.visualstudio.com/docs/python/python-tutorial#_prerequisites](https://code.visualstudio.com/docs/python/python-tutorial#_prerequisites)

The tutorial says that the process could require elevated permissions (sudo):

> Then enter the following commands as appropriate for your operating system (commands may require elevation if the Python interpreter is installed in a protected area of the file system):

But the process automatically tried to use the built-in Python 2.x version. I intend to use Python 3.7, and I have already installed it (via easy_install). Will this install the package for both python versions? Or should the tutorial be using `sudo python3 -m pip install matplotlib` instead?

Python 3.7 is stored here:

```
$ which -a python3
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
/usr/local/bin/python3
```

(Note that `/usr/local/bin/python3` is symlinked to the first one mentioned.)

but permissions are "read, execute" for group and others:

```
$ ls -l /Library/Frameworks/Python.framework/Versions/3.7/bin/ | grep python3
lrwxr-xr-x  1 root  admin     9 Sep 13 16:09 python3 -> python3.7
lrwxr-xr-x  1 root  admin    16 Sep 13 16:09 python3-config -> python3.7-config
-rwxrwxr-x  2 root  admin  9604 Jun 26 22:26 python3.7
lrwxr-xr-x  1 root  admin    17 Sep 13 16:09 python3.7-config -> python3.7m-config
-rwxrwxr-x  2 root  admin  9604 Jun 26 22:26 python3.7m
-rwxrwxr-x  1 root  admin  2081 Jun 26 22:27 python3.7m-config
```

The built-in Python 2.x install is in a system folder:
```
$ which python
/usr/bin/python
```

**Comment by kraigb** [comment]
@AMDphreak Thanks for the correction, which I've merged. I appreciate the detail you provided here, as it clarifies the Mac behavior.

**Comment by AMDphreak** [comment]
> @AMDphreak Thanks for the correction, which I've merged. I appreciate the detail you provided here, as it clarifies the Mac behavior.

Yes, this works.
