### ISSUE TITLE
Update Python Debugger documentation to remove references to Experimental debugger

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode-docs#1859]
The experimental debugger is no more, the documentation needs to reflect this.
Areas to be updated:
* Screen samples
* https://code.visualstudio.com/docs/python/python-tutorial#_configure-and-run-the-debugger

**Comment by kraigb** [comment]
Thanks...I'd updated the debugging article but neglected the tutorial. Fixing now.
