### ISSUE TITLE
Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure. 

### ISSUE THREAD

**Issue by GREGG-CHRISTOFFERSON** [Microsoft/vscode-docs#1862]
In the getting started tutorial, I was able to display the figure when running the python program in the windows powershell terminal.  However, when running it using bash I get the error: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend()).  I am using Windows Subsystem for Linux, Ubuntu bash

**Comment by kraigb** [comment]
@GREGG-CHRISTOFFERSON Thanks for letting me know; I'll add a caveat to that section, because I think it's specific to the Linux subsystem. I've tested the steps on Ubuntu directly, and they work fine.
