### ISSUE TITLE
Document that the Python extension now automatically activates environments

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1866]
Will be in the `2018.8.1` release (aiming for early next week). Can be disabled with `"python.terminal.activateEnvironment": false`.

**Comment by kraigb** [comment]
Reopening due to revert.

**Comment by brettcannon** [comment]
@kraigb did you mean #1878 instead of this issue?

**Comment by kraigb** [comment]
Yes, I mean to reopen #1878, which I've done. Closing this one now as completed.
