### ISSUE TITLE
Document the "python.condaPath" setting

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1867]
Will be a part of the 2018.8.1 release. Basically lets people manually specify where the `conda` command lives.

**Comment by kraigb** [comment]
Thanks for your interest. In this case there's already a PR #1906 that's lined up to make the basic change, which itself is very simple. For most settings, they do in the file docs/python/settings-reference.md. Sometimes we add more discussion in another article, where it's useful to talk about the setting in an appropriate context. In this case I probably will want to look at instances where the pythonPath setting is discussed, and determine whether it's appropriate to also mention condaPath. That's something you could look into as the existing PR only adds the setting to the reference section.

In any case, when making contributions, start by familiarizing yourself with the existing documentation that's published, on code.visualstudio.com/docs/python in this case, to get a sense of how things are presented. Then you can go to the repo and look at the source files under docs/python, where you'll also see how images are placed and included in the repo directly.
