### ISSUE TITLE
"Steps for how to publish documentation changes can be found here in the (private) repository of the VS Code website." - Broken Link

### ISSUE THREAD

**Issue by dimitardanailov** [Microsoft/vscode-docs#1870]
README file has a broken link: 

Section: Publishing
Paragraph: Steps for how to publish documentation changes can be found **here** in the (private) repository of the VS Code website.

**Comment by gregvanl** [comment]
@dimitardanailov The link is valid but it is a private repo. I understand it is confusing for the community not to have access but we keep the link so the VS Code engineers can quickly find information on publishing if they need to.
