### ISSUE TITLE
Ability to manually change OS assumption for key bindings

### ISSUE THREAD

**Issue by angeliquejw** [Microsoft/vscode-docs#1874]
> The VS Code portal is able to show the correct key bindings depending on the reader's operating system (macOS, Windows or Linux).

Is there any method for a user of the docs to override this OS-sniffing or to manually change the key bindings they are shown?

Use cases:
1. Someone trying to help a friend or colleague on a different OS than they have.
1. Teachers in mixed-OS environments.

The latter is my use case, and I'm currently viewing docs on my macOS system and using BrowserStack to emulate Windows to make sure I can also describe the proper keyboard shortcuts to my Windows-using students. 🤷‍♀️

**Comment by gregvanl** [comment]
Hi @angeliquejw, if you hover over a keyboard shortcut with your cursor, a tooltip appears that shows the other platform keybindings.

![image](https://user-images.githubusercontent.com/12818376/45961574-add19b80-bfd3-11e8-9815-75ad20fde28b.png)

Will this work for you and your students?

**Comment by angeliquejw** [comment]
That is brilliant, @gregvanl, and I'm sorry I didn't spot it before opening this issue! 👍

**Comment by gregvanl** [comment]
I'm glad this works for you. Are you aware of our keyboard shortcut cheatsheets? They might be helpful for your students. Help > Keyboard Shortcut Reference from within the product and https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference on the websites.
https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference
