### ISSUE TITLE
Update Python environments documentation to mention virtual environment directory is acceptable

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#1878]
E.g. setting `"python.pythonPath": ".venv"` should work when `.venv` is a virtual environment. This is important when committing a `.vscode/settings.json` file that much be cross-platform.

**Comment by brettcannon** [comment]
Just to clarify, `.venv` is not a magical value, just an example of a directory name.

And a [tweak just came in](https://github.com/Microsoft/vscode-python/pull/2750/files) where marking the directory as relative is prudent, e.g. `./.venv`.

@kraigb do you want a separate issue for this update?

**Comment by kraigb** [comment]
Reopening, as this isn't actually complete.
