### ISSUE TITLE
Error: Could not locate a Flask application. 

### ISSUE THREAD

**Issue by GREGG-CHRISTOFFERSON** [Microsoft/vscode-docs#1881]
After following these steps in the Python Flask tutorial:
https://code.visualstudio.com/docs/python/tutorial-flask#_refactor-the-project-to-support-further-development

I can only run the app in the python debug console.  I can't run it in powershell, although I am following the same steps, I get this error:

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by kraigb** [comment]
Under Powershell, you have to set the FLASK_APP environment variable as follows:

$env:FLASK_APP = "webapp"

Then you should be able to run "python -m flask run" inside the hello_app folder. In other words, PowerShell manages environment variables differently, so the standard command-line "set FLASK_APP=webapp" won't work.

Let me know if that solves your problem.

**Comment by GREGG-CHRISTOFFERSON** [comment]
Yes that worked. Thank you!

**Comment by kraigb** [comment]
Great! Thanks for filing the issue, too; it's not quite a detail I want to put in the docs proper, so having the issue here allows folks to find the solution if they run into the same problem.

**Comment by CarlosEduardo12** [comment]
> Under Powershell, you have to set the FLASK_APP environment variable as follows:
> 
> $env:FLASK_APP = "webapp"
> 
> Then you should be able to run "python -m flask run" inside the hello_app folder. In other words, PowerShell manages environment variables differently, so the standard command-line "set FLASK_APP=webapp" won't work.
> 
> Let me know if that solves your problem.

Thanks i had the same problem and that worked!!

**Comment by schanore** [comment]
> Under Powershell, you have to set the FLASK_APP environment variable as follows:
> 
> $env:FLASK_APP = "webapp"
> 
> Then you should be able to run "python -m flask run" inside the hello_app folder. In other words, PowerShell manages environment variables differently, so the standard command-line "set FLASK_APP=webapp" won't work.
> 
> Let me know if that solves your problem.

I am facing this issue in Anaconda prompt? can you help me with the solution ?

**Comment by StrawberryStatement** [comment]
> > Under Powershell, you have to set the FLASK_APP environment variable as follows:
> > $env:FLASK_APP = "webapp"
> > Then you should be able to run "python -m flask run" inside the hello_app folder. In other words, PowerShell manages environment variables differently, so the standard command-line "set FLASK_APP=webapp" won't work.
> > Let me know if that solves your problem.
> 
> I am facing this issue in Anaconda prompt? can you help me with the solution ?

Have you solved it?

**Comment by Shubham-nodia** [comment]
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by drinkmorewaters** [comment]
For others try "export FLASK_APP=hello.py" the name of your entry file being whatever you called it "app.py", "this.py" upto you

**Comment by DinaTaklit** [comment]
> For others try `export FLASK_APP=hello.py` the name of your entry file being whatever you called it `export FLASK_APP=app.py`, `export FLASK_APP=this.py` upto you.

Thank you this solved the issue for me :D

**Comment by marcelogere** [comment]
> Under Powershell, you have to set the FLASK_APP environment variable as follows:
> 
> $env:FLASK_APP = "webapp"
> 
> Then you should be able to run "python -m flask run" inside the hello_app folder. In other words, PowerShell manages environment variables differently, so the standard command-line "set FLASK_APP=webapp" won't work.
> 
> Let me know if that solves your problem.

This work for me, thanks!!!

**Comment by kraigb** [comment]
@JoshuaPartlow just a reminder note to check the VS Code docs and make sure the PowerShell variant reported here is included.

**Comment by truewithdream** [comment]
Set-Location C:\Users\truew\PycharmProjects\milan\webserver

(webserver) PS C:\Users\truew\PycharmProjects\milan\webserver> flask run
 * Serving Flask app "webapp"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "webapp".

**Comment by Muhammadb1094** [comment]
I'm a new in python flask and using pycharm how to run 1st output on the web browser..where to run and how to run the commands.
its showing me this if i write   "flask run"  in terminal ! ?

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the curren
t directory.

**Comment by kraigb** [comment]
@Muhammadb1094 You need to create an environment variable named FLASK_APP. See the "Tip" under step 8 in https://code.visualstudio.com/docs/python/tutorial-flask#_create-and-run-a-minimal-flask-app.

**Comment by ankushbosi13** [comment]
thank you it worked for me ;)

**Comment by Muhammadb1094** [comment]
Thanks..karaigb

**Comment by Mohamedkable** [comment]
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
.....I can not solve this error

**Comment by JoshuaPartlow** [comment]
Hi @Mohamedkable - What filename are you using for your Flask app? By default, a Flask looks for app.py, if you use something different then you need to set a FLASK_APP environment variable with the alternate filename. So if you used hello.py as your file, on Windows, you'd need to use "set FLASK_APP=hello.py" in the terminal that you're running the Flask commands. The [Flask cli docs](https://flask.palletsprojects.com/en/1.0.x/cli/) have some guidance. Does that help?

**Comment by Mohamedkable** [comment]
@JoshuaPartlow  I do that already, but i do now work also..i run the code from Git Bash on windows

**Comment by JoshuaPartlow** [comment]
I've not tried running from Git Bash before, but you should be able to do "echo $FLASK_APP" to verify if the variable has been set correctly.

**Comment by Mohamedkable** [comment]
Thanks,sir 
I write this code in my app that is run well but if i change the port to 5000.it do not work...
i do not know why..? @JoshuaPartlow 
if __name__ == '__main__':
    app.run(port=4000,debug=True)

**Comment by JoshuaPartlow** [comment]
Hi @Mohamedkable - The help I can offer is around the VS Code docs for our [Flask tutorial](https://code.visualstudio.com/docs/python/tutorial-flask). For general Flask issues I'd suggest looking at the documentation for Flask.

**Comment by Mohamedkable** [comment]
okay sir thank you

**Comment by Suban5** [comment]
adding "python_dotenv" solved my issue in pycharm

**Comment by JoyVehmeijer** [comment]
> For others try `export FLASK_APP=hello.py` the name of your entry file being whatever you called it `export FLASK_APP=app.py`, `export FLASK_APP=this.py` upto you.

This worked for me!

**Comment by Dharanya-Subramanian** [comment]
> 
> 
> After following these steps in the Python Flask tutorial:
> https://code.visualstudio.com/docs/python/tutorial-flask#_refactor-the-project-to-support-further-development
> 
> I can only run the app in the python debug console. I can't run it in powershell, although I am following the same steps, I get this error:
> 
> Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

I'm facing the same issue but I use command prompt instead of power shell.
Need some guidance.

**Comment by JoshuaPartlow** [comment]
@Dharanya-Subramanian - So, to clarify, the app is running in the VS Code console, but you can't get it to run from a standard windows cmd window?

**Comment by Dharanya-Subramanian** [comment]
> 
> 
> @Dharanya-Subramanian - So, to clarify, the app is running in the VS Code console, but you can't get it to run from a standard windows cmd window?

Yes Sir

**Comment by Dharanya-Subramanian** [comment]
> 
> 
> @Dharanya-Subramanian - So, to clarify, the app is running in the VS Code console, but you can't get it to run from a standard windows cmd window?

Yes Sir

**Comment by JoshuaPartlow** [comment]
@Dharanya-Subramanian - If that's the case, you likely just need to create an environment variable in your cmd window prior to running. By default, Flask looks for app.py, if you use something different (like hello.py) for your filename then you need to set a FLASK_APP environment variable with the alternate filename. So if you used hello.py as your file, on Windows, and were running in the cmd window you'd need to use `set FLASK_APP=hello.py`. The [Flask cli docs](https://flask.palletsprojects.com/en/1.0.x/cli/) also have some guidance.

**Comment by Dharanya-Subramanian** [comment]
Thank you so much sir. It works for me.

**Comment by Dharanya-Subramanian** [comment]
Thank you for your guidance Sir. Its helpful for me

**Comment by raeesanjum010** [comment]
@JoshuaPartlow i was set the environment. set the FLASK_APP and FLASK_ENV both. but still get this error  **"Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory."** let me now how to solve this

**Comment by kolliparachandra** [comment]
$env:FLASK_APP = "file.py" works like charm in VS code, thanks for the help

**Comment by JoshuaPartlow** [comment]
Hi @raeesanjum010 - Are you working through the [VS Code Flask tutorial](https://code.visualstudio.com/docs/python/tutorial-flask)? If you are, generally the solution to that error is to make sure you've explicitly set the FLASK_APP environment variable to the correct file name if you haven't used the default `app.py` name. If you're not working on the tutorial, you might want to take a look at the [Flask CLI documentation](https://flask.palletsprojects.com/en/1.0.x/cli/) and [Flask docs](https://flask.palletsprojects.com/en/1.1.x/).

**Comment by marquitobb** [comment]
export FLASK_APP=main.py

**Comment by Thakur-ajay12** [comment]
> > Under Powershell, you have to set the FLASK_APP environment variable as follows:
> > $env:FLASK_APP = "webapp"
> > Then you should be able to run "python -m flask run" inside the hello_app folder. In other words, PowerShell manages environment variables differently, so the standard command-line "set FLASK_APP=webapp" won't work.
> > Let me know if that solves your problem.
> 
> I am facing this issue in Anaconda prompt? can you help me with the solution ?

after getting into directory run dir and then use traditional command set FLASK_APP = hello.py

**Comment by akshay386** [comment]
> For others try `export FLASK_APP=hello.py` the name of your entry file being whatever you called it `export FLASK_APP=app.py`, `export FLASK_APP=this.py` upto you.

this one is work for me

**Comment by Anteneh2121** [comment]
if you are using window 
set FLASK-APP=hello
flask run
it works for me

**Comment by DofusCL** [comment]
I had to move the file from the subfolder that i put it to the location from the VENV folder, or the Flask could't catch the file.
How do i set the rute for the envierment to the FLASK_APP ?

Tnks.

**Comment by Anteneh2121** [comment]
Hello
Can I saw your code, or terminal,  I will help you with zoom, slack or
telegram

**Comment by mohamedx29** [comment]
Actually, the problem is solved once we use $env:FLASK_APP="run" for example, then for th first time we should call python -m flask shell or run or whatever. The second time you connect to the FLASK_APP, we can use the first like : set FLASK_APP="run" and flask shell/run ... I did work for me in both the windows cmd CLI and PowerShell.
I hope that will help. 

Thanks.

**Comment by saintmathew** [comment]
> $env:FLASK_APP = "webapp"

Wow, this worked for me. I've been stuck for few days.
