### ISSUE TITLE
can't install 64-bit version

### ISSUE THREAD

**Issue by amhani** [Microsoft/vscode-docs#1883]
when download and install 64-bit version of code in windows，it show 'please uninstall the 32-bit version of code before installing this 64-bit version', but i have deleted all the file and directory about the before (32-bit) version

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode#59588

**Comment by gregvanl** [comment]
Hi @amhani, this repository is for VS Code documentation. I've moved your issue to the VS Code product repository.
