### ISSUE TITLE
Errors when starting Code

### ISSUE THREAD

**Issue by JanKok** [Microsoft/vscode-docs#189]
I get these errors each time I start code from xterm in Ubuntu:

jan@i5:~/GM/mgm$ code .
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

Other programs don't do that, so I assume this is a problem with Code. Would someone please clean up these warnings/errors?

**Comment by Tyriar** [comment]
This will be fixed in the February release as `code` is no longer a symlink to the Electron binary. See https://github.com/Microsoft/vscode/issues/2859

**Comment by JanKok** [comment]
@Tyriar I have the February ("stable") release and it's still giving that message.

**Comment by Tyriar** [comment]
@JanKok it was actually pushed back to March where deb and rpm packages will be available for installation.

**Comment by JanKok** [comment]
I just downloaded and installed VSCode v0.10.10 dated 2016-03-07 from the ZIP file, and it's still giving that message. Other things are working better.
