### ISSUE TITLE
Documentation: please define "project," "workspace," etc.

### ISSUE THREAD

**Issue by JanKok** [Microsoft/vscode-docs#190]
Please briefly explain the distinctions between folders, projects, workspaces, and similar (does Code have containers?). How can one have multiple projects in one folder? Does the concept of "project" exist for all types of projects, for example a C code project?

A good place for a brief intro might be codebasics / Opening a Project. (But keep it brief, and supply a pointer to more detailed info elsewhere if necessary. The codebasics page is a bit long already.)

**Comment by egamma** [comment]
This is a good request and we should do this. This will help us to be more consistent in the docs. 
Other terms I've seen in our docs are `project context`, `folder based project`.

/// @chrisdias @gregvanl

**Comment by gregvanl** [comment]
Closing as an old issue and we haven't seen many users confusing by the folder based workspace approach.
