### ISSUE TITLE
Inconsistent UI usage in codebasics.md

### ISSUE THREAD

**Issue by TravisTheTechie** [Microsoft/vscode-docs#192]
https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/codebasics.md L12 uses "UI" the first time user interface is encountered. However, on line 14 it uses "user interface." 

Generally, you should expand the word the first time it's used (L12) then use the acronym the following instances. It appears all further instances of user interface are just "UI" in codebasics.md.

**Comment by gregvanl** [comment]
Tuned "user interface" and "UI" usage with https://github.com/Microsoft/vscode-docs/commit/a404600224bfba8b4c927c17f41e23087a023714
