### ISSUE TITLE
Issue with debugging azure function remotely

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/vscode-docs#1930]
I was reading the documentation: vscode-docs/docs/java/java-azurefunctions.md. When I tried to connect remotely to debug the deployed azure function, I came across an exception in vs code.

I also posted the issue on https://github.com/Microsoft/vscode-java-debug/issues/450 since I don't know if this is related to vscode or if i'm missing something in the documentation?   I posted it here since the document outlines everything I did.  

Any help appreciated,
Thanks,
Derek

**Comment by gregvanl** [comment]
@jdneo Is there any plan to update the documentation?

**Comment by gregvanl** [comment]
Closing as no progress for one month. @jdneo @hexiaokai
