### ISSUE TITLE
Lazy collapsed API documentation

### ISSUE THREAD

**Issue by arthurbdiniz** [microsoft/vscode-docs#1939]
I was reading the api documentation [/docs/extensionAPI/vscode-api](https://code.visualstudio.com/docs/extensionAPI/vscode-api). When I tried to open the collapsed dropdown i saw i little bug.

The **container** closes but the final **class** applied to the div its a little bit lazzy.

#### Preview:
![2018-10-05 15 55 33](https://user-images.githubusercontent.com/18387694/46554578-23344a80-c8b7-11e8-9385-648413e69a9b.gif)

> OBS: In the Gif its difficult to see the real bug

**Comment by arthurbdiniz** [comment]
Can i take this issue?

**Comment by arthurbdiniz** [comment]
Okay, thanks @gregvanl for the answer!

**Comment by gregvanl** [comment]
Closing as small UX issue. Documentation is still usable.
