### ISSUE TITLE
Cannot install matplotlib

### ISSUE THREAD

**Issue by imaki-broadsoft** [Microsoft/vscode-docs#1945]
https://code.visualstudio.com/docs/python/python-tutorial says that matplotlib can be installed in Windows environment with command

`py -m pip install matplotlib`

However that command will tell that 'py' is an unrecognized command. Running `python -m pip install matplotlib` appears to do something but even after that the example code cannot be run successfully so there must be something else missing as well. The error message given when trying to run the example code is this:

_Exception has occurred: ImportError
 Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy. If you're working with a numpy git repo, try `git clean -xdf` (removes all files not under version control).  Otherwise reinstall numpy.  Original error was: DLL load failed: The specified module could not be found._ 

I have tried to install numpy separately but it says that the requirement is already satisfied. I started to learn Python and using Visual Studio Code today so I'm really newbie with this, more experienced with C++. I am running Visual Studio Code as Administrator just in case.

I have both miniconda2 and anaconda3 installed in my laptop, I usually need miniconda2 but now going to attend a class that has anaconda3 in its requirements. I manually removed references to miniconda2 from my path environment variable and added anaconda3 there instead (and restarted Visual Studio Code after the modifications).

**Comment by kraigb** [comment]
@imaki-broadsoft What operating system are you running on?

**Comment by imaki-broadsoft** [comment]
Windows 10

**Comment by kraigb** [comment]
Hmmm...not sure what's going on. I'll have to investigate. In the meantime, that part of the tutorial isn't particular critical to doing other work with Python in VS Code, so don't let it be a blocker. :)

**Comment by imaki-broadsoft** [comment]
matplotlib would have been needed in a Python course I attended this week but now the course is over anyway so take your time

**Comment by kraigb** [comment]
Going back to the "python -m pip install" command, can you just run "python" and tell me what version comes up. Also run "where python.exe" and let me know the paths. I'm wondering which interpreter it's picking up, which depends on how things are in your PATH environment variable.

**Comment by kraigb** [comment]
I just tested the section of the tutorial on a fresh machine with a stock Python 3.6 installation, and everything worked fine using python -m pip install matplotlib. I will try again with an Anaconda install, but in the meantime I'm closing this issue because it seems to be an edge case that's not blocking you.
