### ISSUE TITLE
Plan for migrating VS Code API docs

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#1949]
Following https://github.com/Microsoft/vscode/issues/58226 and internal discussions, we decided to move the existing extension docs (`Extension Authoring` & `Extensibility Reference`) from `/docs` to its own place, `/api`. You can preview it at https://vscode-ext-docs.azurewebsites.net/api.

This plan captures the migration. We plan to publish a minimal version by the end of October iteration, and continue to improve it in the following months.

## Iconography

- 🌟 Nice-to-have items. These items would make the whole extensibility doc more complete, but are not necessary for publishing.
- 📝 Items that require writing new docs.
- 📄 Link to file.

## Working On The Items

- Work happen in the [`ext-docs`](https://github.com/Microsoft/vscode-docs/tree/ext-docs) branch of vscode-docs
- CI automatically builds [`ext-docs`](https://github.com/Microsoft/vscode-docs/tree/ext-docs) branch and publish it to https://vscode-ext-docs.azurewebsites.net/ for preview
- Each item links to its corresponding markdown files. Each file has some writing instructions. Work on that file, push changes to `ext-docs` branch and check the results on https://vscode-ext-docs.azurewebsites.net.
- Links: Link to end points on the preview site. We'll do a find-replace for the domain name before publishing.
- Image/Gif: They follow the same folder convention as other parts of the website.
  - If you have `/foo/bar/topic.md`
  - Create a folder `/foo/bar/images/topic/`, and put images in it
  - In the MD file, link the file with `![](images/topic/<my-image>.png)`
  - A sample change: https://github.com/Microsoft/vscode-docs/commit/98022a951b2c46cd49db3c9bf524106fcba948fa
- Finally, remove the old documents/images. Endpoints to them will be redirected.

## Write and Review key topics

~~Each topic has two assignees, for example A / B. A writes the doc and B reviews it.~~
This part tracks the writing. Reviewing assignment will be created as testplan items.

- [x] 📝 Overview [📄](https://github.com/Microsoft/vscode-website/blob/ext-docs/server/views/api/index.handlebars) @octref (review: @jrieken)
- [x] 📝 Extension Capabilities / Overview [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-capabilities/overview.md) @mjbvz (review: @jrieken)
- [x] 🌟📝 Extension Capabilities / Theming [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-capabilities/theming.md) @octref (review: @bpasero)
- [x] 🌟📝 Extension Capabilities / Extending Workbench [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-capabilities/extending-workbench.md) @isidorn (review: @sandy081)
- [x] 📝 Extension Guides / Overview [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/overview.md) @octref (review: @sandy081)
- [x] 📝 Language Extensions / Overview [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/language-extensions/overview.md) @octref (review: @dbaeumer)

## `Hello Code`

@auchenberg @octref

Hello Code is the HelloWorld sample in VS Code API land. This example is a cornerstone in the new API doc. It should:
- Explain the lifecycle of scaffold / write / run / debug / test / publish extensions
- Explain the fundamental concepts, such as contribution points, how to use VS Code API
- Point people to correct tools and resources. For example, `vscode` NPM module, `vsce` for packaging and publishing, `yo code` for scaffolding.

---

- [x] Define subtopics and their contents @octref & @auchenberg 
- [x] :runner: Put into `Hello World` section existing docs from [Hello World](https://vscode-ext-docs.azurewebsites.net/docs/extensions/example-hello-world), [Word Count](https://vscode-ext-docs.azurewebsites.net/docs/extensions/example-word-count), [Developing](https://vscode-ext-docs.azurewebsites.net/docs/extensions/developing-extensions) / [Testing](https://vscode-ext-docs.azurewebsites.net/docs/extensions/testing-extensions) / [Publishing](https://vscode-ext-docs.azurewebsites.net/docs/extensions/publish-extension) and make them a coherent piece [📄](https://github.com/Microsoft/vscode-docs/tree/ext-docs/api/hello-code) @octref @auchenberg 
- [x] Publish the sample code as `hellocode-sample` at https://github.com/Microsoft/vscode-extension-samples @octref

## `Extension Guides`

Each assignee should:
- Move existing docs to the new place and do some editing.
- Update the sample to meet the sample quality standard. Microsoft/vscode-extension-samples#110.

---

- [x] Color Theme [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/color-theme.md) @bpasero 
- [x] Task Provider [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/task-provider.md) @dbaeumer 
- [x] Webview [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/webview.md) @mjbvz 
- [x] 🌟📝TreeView [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/tree-view.md) @sandy081 
- [x] Debugger [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/debugger.md) @weinand 
- [x] Source Control API [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/scm-provider.md) @joaomoreno 
- [x] Markdown Extension API [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/markdown-extension.md) @mjbvz 

## `References`

@octref will do the moving.

- [x] vscode API
- [x] Principle and Patterns
- [x] Contribution Point
- [x] Activation Event
- [x] Theme Color Reference
- [x] Document Selector
- [x] Complex Commands

## `Language Extensions`

- [x] Migrate `Language Extension Guidelines` [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/language-extensions/language-features.md) @octref 
- [x] Split original `Themes, Snippets and Colorizers` into `Syntax Highlighting` ([📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/language-extensions/syntax-highlight-guide.md)) and `Snippets` ([📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/language-extensions/snippet-guide.md)) topics @octref (moving) / @jrieken (reviewing)
- [x] Migrate `Language Server Example` [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/language-extensions/smart-editing-guide.md) and [📄](https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/language-extensions/smart-editing-lsp-guide.md) @octref

**Comment by lannonbr** [comment]
The groundwork that has been done so far looks extremely promising. I think it will be great to have a more in-depth look at the API for existing devs as well as being welcoming to new devs.

Glad to see the work being done with this @octref!

**Comment by gregvanl** [comment]
Assigned to Pine so there is an owner

**Comment by octref** [comment]
Closed in favor of https://github.com/Microsoft/vscode-docs/issues/2199.
