### ISSUE TITLE
List of Commands

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#195]
Does there exist an up to date list of all available VS Code commands? 

I'm looking for something like what [Sublime has](http://www.sublimetext.com/docs/commands).

**Comment by gregvanl** [comment]
There is a list in the keybinding.md topic but it's buried under Customization.
We could add a link in codebasics.md to this list.
We maintain this list each release but could do a better job of keeping it up to date.
I've also seen doc feedback verbatim asking for printable command and keybinding lists.

**Comment by gregvanl** [comment]
We now have the keyboard shortcut reference PDFs.
