### ISSUE TITLE
Docs: Explain `scope` Field within `configuration` Contribution Point...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode-docs#1957]
the docs for the `configuration` contribution point make no mention of the `scope` field - yet we are warned about setting it / not setting it under certain circumstances. what does `scope` do?

docs:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration

example:
https://github.com/Microsoft/vscode-extension-samples/blob/master/configuration-sample/package.json#L42

warning:
https://github.com/Microsoft/vscode/issues/36623
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#run-time-diagnostics

thanks 🙏

**Comment by HrushikeshBodas** [comment]
Id like to take up this issue.

**Comment by busticated** [comment]
I replied over here 👉 https://github.com/Microsoft/vscode-docs/pull/1995#issuecomment-430295897

**Comment by gregvanl** [comment]
Will be covered by https://github.com/microsoft/vscode-docs/issues/2731
