### ISSUE TITLE
Docs: Include Full Lookup Path and Make Things Easier to Copy+Paste...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode-docs#1958]
minor but helpful things:

* make the property / method names easily copy+paste-able (ex. `createOutputChannel` [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#window.createOutputChannel))
* in each property / method section, include the full parent reference so i don't need to scroll around to find it - e.g. `window.createOutputChannel()`

thanks 🙏

**Comment by gregvanl** [comment]
Closing as no upvotes.
As workarounds, the property/method names can be manually selected and copied and the containing namespace is visible in the right navigation list.
