### ISSUE TITLE
Publishing Extension docs

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#196]
I really like our extension development experience. However, I can never remember the publishing steps. When I'm looking for how to publish an extension I'd expect to see something close to "Installing Extensions". 

I propose we make a new page called "Publishing Extensions" to make the doc navigation very clear. As it is I have a hard time remembering the steps are in [tooling](code.visualstudio.com/docs/tools/vscecli).

**Comment by gregvanl** [comment]
The extension ecosystem is doing well so closing.
