### ISSUE TITLE
Update the refactoring page with the refactoring improvements

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-docs#1960]
https://code.visualstudio.com/docs/editor/refactoring

Motivation:
![image](https://user-images.githubusercontent.com/172399/46717193-3d7b7900-cc67-11e8-89da-ba9f7eaee41b.png)

**Comment by gregvanl** [comment]
Closing old issue. I don't think it is feasible to list all refactorings supported by all language extensions. This list is growing all the time and will be hard to keep up to date. The most reliable source will be the refactorings displayed in the editor.
