### ISSUE TITLE
Talk about the problems on using pip freeze

### ISSUE THREAD

**Issue by Guilhermeslucas** [Microsoft/vscode-docs#1967]
Hello all, how are you? I was reading the docs on Django and Flask, and on both of them are saying to use ```pip freeze > requirements.txt```. That's good for explaining how a requirements file works, but its not the best practice, since you can create a requirements file full of packages that are not needed for the specific project. Besides, we could talk more about versions of packages inside the file. 
What do you think? Thanks a lot!

**Comment by kraigb** [comment]
We're doing well, thank you, and thanks for your suggestion. I'm thinking that the Django/Flask tutorials themselves are the not quite the right place for best practices for requirements.txt, but should link to the appropriate information. Is there somewhere in Python docs, perhaps, that describe what you're looking for?

Alternately, there's a comment on requirements.txt at the end of this section: https://code.visualstudio.com/docs/python/environments#_global-and-virtual-environments. I could see a separate section on requirements.txt in that article. If you'd like to draft something up in a PR, I'm happy to add the edit and polish. Or you can just make a list of what you'd like to see in this issue and I'll work it over.

**Comment by Guilhermeslucas** [comment]
Hey Kraig, thanks a lot for your answer! And I totally agree with you that this is not the place to take too much time explaining the best practices on requirements files. I think it would be totally cool to have a explanation what ```pip freeze > requirements.txt``` will do, putting all the packages you have installed in the environment to a file. Besides, it would be cool to have a simple link explaining more about this. I can work on a draft for it an open a PR. Is it cool?
Thanks a lot!

**Comment by kraigb** [comment]
Yes, open a PR and let's collaborate on this! It's exactly why the docs are open source. :)
