### ISSUE TITLE
Documentation website common "tweet" share link is broken.

### ISSUE THREAD

**Issue by qayshp** [Microsoft/vscode-docs#1984]
When viewing any markdown page on the Docs site, for example [setup overview](https://code.visualstudio.com/docs/setup/setup-overview), there is a column on the right called "IN THIS ARTICLE" with each of the headings from the rendered markdown. At the bottom of that section is a blue link titled "Tweet". That is the bad link, as all it does is link to https://twitter.com/share while a user would likely think it would tweet a link to the page being viewed. Using the example page from above, that would translate roughly to https://twitter.com/intent/tweet?url=https://code.visualstudio.com/docs/setup/setup-overview

![image](https://user-images.githubusercontent.com/714080/46890299-3301e080-ce1b-11e8-9cec-625bc7d198c2.png)

Since there is nothing in this repository that looks like it converts the markdown to html or includes the navigation bars, I can only guess that the actual change would likely be in the private repository at https://github.com/Microsoft/vscode-website

**Comment by gregvanl** [comment]
Hi @qayshp Thank you for taking the time to enter this issue. There is already an open issue for this in the private vscode-website repo and you are correct, the fix needs to be made there.
