### ISSUE TITLE
[Tips-and-tricks] Search and replace using regular expressions

### ISSUE THREAD

**Issue by martinbydefault** [Microsoft/vscode-docs#1998]
Recently I had to edit some code files where I wanted to search for specific parts of code and append to it some other code/text (mantaining the original matched code).
The only way I found to achieve this in VSCode (aside from doing it by hand) was to use the search and replace function with regular expressions and use capturing groups.

I thinks this is something useful to add in the Tips and tricks section.

If you are ok with this contribution I can submit a PR adding this under Editing hacks: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_editing-hacks

Also I'm not sure if the correct place to propose this is here or at this other repo: https://github.com/Microsoft/vscode-tips-and-tricks

**Comment by gregvanl** [comment]
Hi @martinbydefault Thanks for your PR. Tips and Tricks has moved to vscode-docs and vscode-tips-and-tricks is no longer maintained.
