### ISSUE TITLE
Processing code open source?

### ISSUE THREAD

**Issue by bootstraponline** [Microsoft/vscode-docs#2]
Is the code that processes the docs open source? Is there a way to run a local instance of the docs to see how they'll look?

**Comment by gregvanl** [comment]
Sorry, the portal code is not open source and there isn't a way to see the translated docs on a private portal.  Using the VS Code Markdown preview should give you a good idea how your doc updates will appear.

**Comment by bootstraponline** [comment]
:cry:

**Comment by bootstraponline** [comment]
looks like the [build scripts](https://github.com/Microsoft/vscode-docs/commit/7705250e5cd6e4e3a60b5a9d36dec7bec64c864c) have been open sourced?

**Comment by gregvanl** [comment]
To implement our continuous integration build, we had to put our web page generation scripts in the vscode-docs repo.  These scripts have a dependency on our private website repository so they won't work standalone.

**Comment by bootstraponline** [comment]
😭

**Comment by yurenhen** [comment]
:sob:
