### ISSUE TITLE
What about localization for the documentation ?

### ISSUE THREAD

**Issue by Bug38** [Microsoft/vscode-docs#2004]
Code itself is localized, but I can't find any documentation other than english one...

**Comment by gregvanl** [comment]
Hi @Bug38, currently we don't localize the VS Code website.

**Comment by gregvanl** [comment]
Reopening in order to track feedback

**Comment by gregvanl** [comment]
VS Code doesn't plan on localizing the website while it is on code.visualstudio.com.

**Comment by endingly** [comment]
VS code team can turn over to the community if there is enough demand.
