### ISSUE TITLE
Explain top-right icons in User Interface

### ISSUE THREAD

**Issue by lorensr** [Microsoft/vscode-docs#2021]
`/docs/getstarted/userinterface.md`

https://code.visualstudio.com/docs/getstarted/userinterface

I think this would be a good place to explain what these icons are called and how to remove / change them:

![image](https://user-images.githubusercontent.com/251288/47116132-b3b34900-d22e-11e8-9924-a5a5ede661f6.png)

**Comment by gregvanl** [comment]
These buttons are fixed and can not be removed or changed for the editor view. Each button has a tool tip on hover showing the button name and keyboard shortcut if available.

**Comment by lorensr** [comment]
Thanks! Found the FR: https://github.com/Microsoft/vscode/issues/46403
