### ISSUE TITLE
Adding new settings UI details

### ISSUE THREAD

**Issue by aayushbisen** [Microsoft/vscode-docs#2025]
Since VS Code now has a GUI for editing settings. I think instructions on _User and Workspace Settings_ page have a room for improvements.

**Comment by gregvanl** [comment]
@aayushbisen Thanks for entering an issue, which will help with tracking. It has been on our todo list for some time.

**Comment by aayushbisen** [comment]
Great. I would also like to contribute.

**Comment by aayushbisen** [comment]
#2081

**Comment by aayushbisen** [comment]
added some improvements.
