### ISSUE TITLE
Broken links within Introductory section

### ISSUE THREAD

**Issue by jamesgeorge007** [Microsoft/vscode-docs#2029]
The video previews within the [introductory videos section](https://github.com/Microsoft/vscode-docs/blob/master/docs/getstarted/introvideos.md) is broken within the repository. It is just fine on the website part. 
Was this ignored for the repository?

If it's not the case, I'm happy to submit a fix :smile:

**Comment by gregvanl** [comment]
Hi @jamesgeorge007, Yes the embedded HTML on the intro videos page doesn't render on GitHub but does once converted to handlebars on our website.
