### ISSUE TITLE
Linking to an API call should automatically expand it

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-docs#204]
I can send a link to an API call such as the following to a user.

https://code.visualstudio.com/Docs/extensionAPI/vscode-api#1036 (registerCompletionItemProvider)

IMO the API call should be expanded once that page is opened.

**Comment by peterblazejewicz** [comment]
On the page load something along, as it uses BS toggle triggered collapse:
```js
document.getElementById(window.location.hash.replace(/#/, '')).click()
```

**Comment by gregvanl** [comment]
Closing old issue, no upvotes
