### ISSUE TITLE
List of CSS variables accessible in an extension WebView

### ISSUE THREAD

**Issue by tetchel** [Microsoft/vscode-docs#2060]
Hi, I am creating a WebView as part of my extension and want to style my WebView buttons to look like the VSCode buttons.

From https://code.visualstudio.com/docs/extensions/webview#_theming-webview-content I see that there is CSS exposed to my extension that I can use, and that's great - just what I need.

However, I've done some digging in the main repository I cannot find a list of the names of the CSS variables (the example given is `editor.foreground`) that I can use. 

I've found [this file](https://github.com/Microsoft/vscode/blob/17454d4e88886404af130639b979498b227a9167/src/vs/editor/standalone/common/themes.ts) which provides the names of a few more color variables I can access:
```
		[editorBackground]: '#FFFFFE',
		[editorForeground]: '#000000',
		[editorInactiveSelection]: '#E5EBF1',
		[editorIndentGuides]: '#D3D3D3',
		[editorActiveIndentGuides]: '#939393',
		[editorSelectionHighlight]: '#ADD6FF4D'
```
but I feel like there must be more available (such as button background color!).

Please let me know where I can find a list of exposed CSS variables (if it exists), and consider pointing to it from the docs section I've linked above.

Thanks for reading!

**Comment by tetchel** [comment]
Well, I've found what seems to be an exhaustive list in the theme json files, eg [here](https://github.com/Microsoft/vscode/blob/31f86f72bd027dc90347bf7459111550604582b4/extensions/theme-monokai/themes/monokai-color-theme.json).

I still think this list should be added to the docs, but my issue personally is resolved :)

**Comment by kcclemo** [comment]
Would it make sense to place a markdown document for this list under `docs/customization`? Or is it better to just link to the raw .json file?

**Comment by kcclemo** [comment]
And actually, in reading through this, I think this color reference would be an appropriate document to link to from the https://code.visualstudio.com/docs/extensions/webview#_theming-webview-content article:
https://code.visualstudio.com/docs/getstarted/theme-color-reference

I'd be happy to submit a pull request with this change if that's OK.

**Comment by tetchel** [comment]
Hi kcclemo,

The theme-color-reference is exactly what I had in mind. A link to that from the theming-webview-content docs would be really helpful.

That being said, I was hoping for more CSS than just colors. It would be great if I could just apply a (for example) `vscode-button` class to my buttons, and have them fit right in - I still haven't figured out how to create 'editor buttons' (like the [Add Configuration... button](https://code.visualstudio.com/assets/docs/editor/debugging/launch-json-intellisense.png), so let me know if you can point me to how I can style buttons like those, either an editor or within a webview.

Thanks!

**Comment by tetchel** [comment]
Fixed #2075

**Comment by usernamehw** [comment]
There is an extension now that adds css variables available in webview to autocomplete:

https://marketplace.visualstudio.com/items?itemName=connor4312.css-theme-completions

**Comment by jedwards1211** [comment]
Still having trouble figuring out where the color of the `5 results in 2 files` text in the search/replace view comes from

**Comment by andreamah** [comment]
I think you'd be looking to change `sideBar.foreground` to change to color of the `x results in y files` text.

**Comment by jedwards1211** [comment]
@andreamah the actual element appears to have opacity applied, whereas `--vscode-sideBar-foreground` is just a solid color.  So it seems like theme colors aren't the whole story in that case

**Comment by andreamah** [comment]
Right, I took another look and it looks like it's hard-coded to use 0.65 opacity (https://github.com/microsoft/vscode/blob/ce4aed5bf1917a86a6dfe1a71bdf51314bcc9afc/src/vs/workbench/contrib/search/browser/searchView.ts#L2015), but uses the foreground color. Are you trying to change it, or just get the color?

**Comment by jedwards1211** [comment]
@andreamah I just want to match it in an extension I'm writing to provide a structural search and replace view.  I was mostly just wondering if there's a more developer-friendly way of looking up how given elements of the built-in views get their theme colors.  If the builtin views were styled with CSS variables then I'd be able to tell where the colors are coming from in the debug tools instead of having to dig through the source code.

**Comment by andreamah** [comment]
Unfortunately, there's not really an easier way to do it than looking in devtools and looking in the source code when necessary. Sorry about that!
