### ISSUE TITLE
Editor Decoration should not be documented in the Theming page

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#2063]
The section on editor decoration (see below) is currently shown in https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/theming. 

Editor decorations are not related to theming. They should be documented in the editor.

![image](https://user-images.githubusercontent.com/172399/47489946-02bd3780-d848-11e8-99d5-4498349e3a70.png)

**Comment by octref** [comment]
Thanks - took it out of that topic.
