### ISSUE TITLE
Clarify that "python.unitTest.autoTestDiscoverOnSaveEnabled" applies to all test frameworks

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#2068]
Microsoft/vscode-python#3004

The phrasing at https://code.visualstudio.com/docs/python/unit-testing#_test-discovery and https://code.visualstudio.com/docs/python/unit-testing#_unittest-configuration-settings suggest that `"python.unitTest.autoTestDiscoverOnSaveEnabled"` only applies to `unittest`, when in fact it works with all the test runners.

**Comment by thernstig** [comment]
@kraigb @jgierer12 @brendonotto As part of this (as described in https://github.com/Microsoft/vscode-python/issues/3004) the following section indicates settings for only the "unittest" framework: https://code.visualstudio.com/docs/python/unit-testing#_unittest-configuration-settings

Pytest (https://code.visualstudio.com/docs/python/unit-testing#_pytest-configuration-settings) and Nose (https://code.visualstudio.com/docs/python/unit-testing#_nose-configuration-settings) have their own sections as can be seen.

As such, the configurations under "Unittest configuration settings" are mixing both the the unittest (the framewor) settings and unit test (general) settings.

Should the section be split into one "general" and one for "unittest"?

**Comment by jgierer12** [comment]
Good point, I too believe there should be a separate section for general settings. @kraigb?

**Comment by kraigb** [comment]
@jgierer12 Yes, a separate section on general settings is the pattern to follow.

**Comment by thernstig** [comment]
@kraigb @jgierer12 please see https://github.com/Microsoft/vscode-docs/issues/2113
