### ISSUE TITLE
WebView documentation should mention that links using the "command:" protocol are supported

### ISSUE THREAD

**Issue by tetchel** [Microsoft/vscode-docs#2076]
[The WebView example](https://code.visualstudio.com/docs/extensions/webview) should mention that VSCode commands can be invoked by traditional HTML links in a WebView by using the "command" protocol. Maybe the `catCoding.doRefactor` command could be bound to a button.

I figured out that this is possible from [the source for the Welcome page](
https://github.com/Microsoft/vscode/blob/ff13d20dc488cc41e80f61c9525da21c89368af0/src/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page.ts#L26), and it's super useful.
It does not appear to be possible to pass parameters to these commands. If that _is_ possible, please document that too :)

**Comment by eunicode** [comment]
Hi, can I try tackling this?

**Comment by gregvanl** [comment]
Talking with the VS Code engineers, they discourage firing commands directly from a webview as that could allow running unsafe commands. The recommended approach is to use postMessage as documented in the tutorial.
