### ISSUE TITLE
Confusing layout & syntax in /master/docs/getstarted/introvideos.md

### ISSUE THREAD

**Issue by LeMorrow** [Microsoft/vscode-docs#2084]
Very strange syntax appears in [introvideos.md](https://github.com/Microsoft/vscode-docs/blob/master/docs/getstarted/introvideos.md).

I won't be fixing it myself since I'm not sure if there's a specific reason for this behaviour (perhaps this same file is used somewhere else but styled with css that fixes it?).

- Titles and descriptions appear **under** the videos (they should be placed above).
- Bullet points appear next to the images, rather than next to the titles.
- All of the videos' duration appear in the format `X min minutes`.

Screenshot for reference:
![](https://i.imgur.com/34h3SYU.png)

**Comment by marcoandredinis** [comment]
> (perhaps this same file is used somewhere else but styled with css that fixes it?).

I think that's exactly what's happening: https://code.visualstudio.com/docs/getstarted/introvideos

**Comment by LeMorrow** [comment]
Ah, looks like it. I'm going to assume that the priority is the docs on the web, not the layout here on Github. Closing the issue.
