### ISSUE TITLE
Can typings be installed while Code is running?

### ISSUE THREAD

**Issue by JanKok** [Microsoft/vscode-docs#209]
Any explanation? Should the nodejs doc warn users to stop Code before installing typings?

While reading and following along the nodejs documentation page, I ran the command "npm install -g typings" while Code was running. NPM sat there spinning the cursor for several minutes. After a while I ran the "top" command in another terminal window and saw that the machine was not busy and NPM was taking less than 1% of the CPU. Then I stopped Code and watched top but NPM didn't get more active. I then restarted the npm command, and it it installed typings in about a minute (npm also showed up in top at 40-50%). Here's what this part looked like in the terminal window:

jan@i5:~/sandbox/myExpressApp$ code .&
[2] 2613
jan@i5:~/sandbox/myExpressApp$ bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

jan@i5:~/sandbox/myExpressApp$ npm install -g typings
\
^C
[2]+  Done                    code .
jan@i5:~/sandbox/myExpressApp$ 
jan@i5:~/sandbox/myExpressApp$ npm install -g typings
/home/jan/Apps/nsolid-v1.2.2-linux-x64/bin/typings -> /home/jan/Apps/nsolid-v1.2.2-linux-x64/lib/node_modules/typings/dist/bin/typings.js
typings@0.6.10 /home/jan/Apps/nsolid-v1.2.2-linux-x64/lib/node_modules/typings
├── array-uniq@1.0.2
...

I then removed typings, restarted Code, and reinstalled typings. Unlike the first time, this time typings installed in less than a minute.

└── insight@0.7.0 (object-assign@4.0.1, async@1.5.2, tough-cookie@2.2.1, lodash.debounce@3.1.1, configstore@1.4.0, os-name@1.0.3, inquirer@0.10.1, request@2.69.0)
jan@i5:~/sandbox/myExpressApp$ npm remove -g typings
unbuild typings@0.6.10
jan@i5:~/sandbox/myExpressApp$ 
jan@i5:~/sandbox/myExpressApp$ code .&
[2] 2911
jan@i5:~/sandbox/myExpressApp$ bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

jan@i5:~/sandbox/myExpressApp$ npm install -g typings
/home/jan/Apps/nsolid-v1.2.2-linux-x64/bin/typings -> /home/jan/Apps/nsolid-v1.2.2-linux-x64/lib/node_modules/typings/dist/bin/typings.js
typings@0.6.10 /home/jan/Apps/nsolid-v1.2.2-linux-x64/lib/node_modules/typings
├── array-uniq@1.0.2

**Comment by gregvanl** [comment]
You shouldn't need to stop VS Code to install typings.  The typings file installs shouldn't be interacting with VS Code at all.  I think the delays you are seeing can be explained by the network traffic delays to pull down the typings files from DefinitelyTyped repository.
