### ISSUE TITLE
Language identifiers page looks out of date

### ISSUE THREAD

**Issue by alvinsight** [Microsoft/vscode-docs#2109]
Hello, 
It looks like the languages listed in the list of supported [language identifiers](https://code.visualstudio.com/docs/languages/identifiers) is missing a few languages.

For example, the official page about using Emmet references `vue-html` and `javascriptreact`:
<img width="769" alt="screen shot 2018-10-29 at 14 54 08" src="https://user-images.githubusercontent.com/4254030/47658329-bc8b0f80-db8a-11e8-8ea3-8e38d3ecb712.png">

I've also seen template strings use `styled-css` when working with styled components.

Thank you,
Alvin

**Comment by gregvanl** [comment]
vue-html and styled-css are language identifiers added by extensions (vue-html comes from Vetur, not sure about styled-css). javascriptreact is a language identifier in the product so will add it.

**Comment by gregvanl** [comment]
JavaScript React identifier added with https://github.com/Microsoft/vscode-docs/commit/2f39e439f9f86248c92256267911571f05aca60c

**Comment by alvinsight** [comment]
Hey @gregvanl thank you for doing this!

How about JSX ? 
It might be wrong but it looks like it's another language

![screen shot 2018-11-08 at 11 45 48](https://user-images.githubusercontent.com/4254030/48196967-0672b300-e34c-11e8-8eb5-0d92d33246b8.png)
![screen shot 2018-11-08 at 11 45 37](https://user-images.githubusercontent.com/4254030/48196971-0b376700-e34c-11e8-9136-197dd2a854d3.png)

I'm basically trying to get our snippets to work inside JSX tag props and CSS template strings, but I can't find a list of langauges to target these scenarios.

**Comment by gregvanl** [comment]
The "jsx" identifier is not built into VS Code and is likely added by an extension. I see it for the Babel JavaScript extension (mgmcdermott.vscode-language-babel) which also adds language id "styled-css".
You can always check the installed language identifiers by running the **Change Language Mode** command for a file and reviewing the drop-down list.

![image](https://user-images.githubusercontent.com/12818376/48292679-22e81b80-e430-11e8-8c15-b5d026b2bbcc.png)
