### ISSUE TITLE
Separate Python unit test settings from the unittest framework settings

### ISSUE THREAD

**Issue by thernstig** [Microsoft/vscode-docs#2113]
The following section indicates settings for only the "unittest" framework: https://code.visualstudio.com/docs/python/unit-testing#_unittest-configuration-settings - i.e. `autoTestDiscoverOnSaveEnabled` seems to indicate it can only be configured for unittest (the framework).

Pytest (https://code.visualstudio.com/docs/python/unit-testing#_pytest-configuration-settings) and Nose (https://code.visualstudio.com/docs/python/unit-testing#_nose-configuration-settings) have their own sections as can be seen.

As such, the configurations under "Unittest configuration settings" are mixing both the the unittest (the framework) settings and unit test (general) settings.

It is recommended to split the section into one "general" and one for "unittest"

Discussion started in https://github.com/Microsoft/vscode-python/issues/3004

**Comment by thernstig** [comment]
@brettcannon As part of this, would it be an idea to rename `python.unitTest.` to `python.test.` in the actual settings? It would then be more clear to have general settings under `python.test.` and framework specific settings under `python.test.unittest`, `python.test.pytest` and `python.test.nose`.

All the documentations at https://code.visualstudio.com/docs/python/unit-testing seems to indicate that only unit testing is feasible. But I'd say that even functional testing (integration testing) is also part of e.g. pytest.

**Comment by brettcannon** [comment]
@thernstig it's off-topic in this repo, but there's already an open issue to clean up our setting naming scheme and part of that includes our test settings.

**Comment by kraigb** [comment]
@thernstig Thanks for filing this issue! Apologies for taking a few weeks to come round to it, but I've corrected the docs.
