### ISSUE TITLE
Line height in /api is smaller than in other pages

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-docs#2117]
Testing Microsoft/vscode#62106

https://vscode-ext-docs.azurewebsites.net/api

The line height in this page is smaller than all other docs pages.

**Comment by octref** [comment]
Good eyes. Will fix that and also make the `/api` page generated from a markdown in vscode-docs.

**Comment by octref** [comment]
Fixed line-height and the Overview page is now generated from `api/index.md` file at https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/index.md.
