### ISSUE TITLE
Docs: /api clarifications

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-docs#2118]
Testing Microsoft/vscode#62106

> Unlike other editors, VS Code do not provide DOM access to extension authors to ensure the responsiveness and performance of VS Code. VS Code does, however, offer a lot of ways for extension authors to customize the editor. Here are some extension ideas and links for more information:

**Suggested alternative:**

VS Code is an Electron based app, so its UI is built using HTML, CSS and JavaScript using the usual browser DOM API. Unlike other editors, VS Code does not provide DOM access to extension authors in order to ensure its responsiveness and performance. Instead, an extensive extension API is exposed in order to customize the editor. Here are some examples of what you can achieve using this API:

---

> You can find a more detailed overview of "What can extensions do" at the Extension Capabilities Overview topic.

**Suggested alternative:**

If you'd like to learn more about the Extension API, refer to the Extension Capabilities Overview page.

---

> Once you have landed on an idea, here are some resources that would help you building the extension.

**Suggested alternative:**

If you have an idea for an extension and do not know how to start, the following resources can help you.

**Comment by octref** [comment]
All great points — I took them all. Thanks!
