### ISSUE TITLE
Search on the website doesn't highlight matches.

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-docs#2121]

**Comment by gregvanl** [comment]
Hi @usernamehw Good suggestion and there is an existing issue in our private website build repo. I gave it a +1. Thanks

**Comment by Haroenv** [comment]
Hey Greg, could you give it another +1 for me please? Not to sound shilly or whatever, but it would be really nice if the reference could use [DocSearch](https://community.algolia.com/docsearch/), like some other big open source projects.

**Comment by gregvanl** [comment]
Hi @Haroenv, I linked to your comment in the website issue.
