### ISSUE TITLE
The "code .” command  call in the  python tutorial page.

### ISSUE THREAD

**Issue by abetancort** [Microsoft/vscode-docs#2124]
The terminal command`code .` in the target folder does not work, obviously, in macOS environments. 

That is because the Visual Studio is installed by default (using Anaconda) in `~/applications `under the name `Visual Studio Code.app` and no aliases or symlink named code are created to the `electron` executable inside or outside the Visual Studio package. More over in macOS neither the applications directories nor the path to the executable within each app package are part of the standard PATH environment variable. 

**Please unambiguously clarify instructions for macOS users.**

**Comment by kraigb** [comment]
@abetancort Is there any means to start VS Code in a folder from the CLI on a Mac? Or are you recommending that it's better (and more universal) to instruct people to start VS Code and open the folder via the UI?

**Comment by jrkoch** [comment]
Hi, I can open a PR that links to elsewhere in the documentation for setting this up

**Comment by jrkoch** [comment]
Drat, I was hoping for a hacktoberfest win.

Instructions for setting up `code .` on macOS are found here: https://code.visualstudio.com/docs/setup/mac#_preferences-menu

**Comment by mikeweilgart** [comment]
Same exact issue for the C++ tutorial page: https://code.visualstudio.com/docs/cpp/config-clang-mac#_create-hello-world

It may be an issue for other tutorials also.
