### ISSUE TITLE
Use "Visual Studio Code" in titles, H1, and first use; "VS Code" in later text

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2142]
Found while testing #https://github.com/Microsoft/vscode/issues/62107

**Comment by octref** [comment]
> Should say "Visual Studio Code Marketplace"

The whole Extension API section uses the word VS Code, not Visual Studio Code.

> Use "Visual Studio Code" in titles, H1, and first use; "VS Code" in later text

I changed the title to be `Overview | VS Code API` for the top page.
Also opened https://github.com/Microsoft/vscode-docs/issues/2145.
