### ISSUE TITLE
Advance Topics section

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2147]
Testing https://github.com/Microsoft/vscode/issues/62107
A couple of suggestions:
- Publishing extensions isn't an advanced topic, it is mainstream for working with extensions. I would move it, perhaps into Get Started.
- Advanced topics should be at the bottom and only contain really advanced topics like testing and proposed API.

**Comment by octref** [comment]
> Publishing extensions isn't an advanced topic, it is mainstream for working with extensions. I would move it, perhaps into Get Started

Yep, we did that.

> Advanced topics should be at the bottom and only contain really advanced topics like testing and proposed API.

We did that too! https://github.com/Microsoft/vscode-docs/issues/2192
