### ISSUE TITLE
Use yeoman generator rather than cloning a repo

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2148]
Testing https://github.com/Microsoft/vscode/issues/62107

I think people are very comfortable with yeoman and other application generators so I would stick with using the Yeoman generator to create the project. We already require Node.js and npm so using Git doesn't eliminate that dependency.

The new generator removes asking for a publisher so that confusion is gone.

A generator makes it very easy for people to create multiple extensions quickly and try out the different flavors.

**Comment by octref** [comment]
Yeoman generator:

- 2 more dependencies to install
- A bunch of files beginners don't care (tests, workspace settings, etc)
- Source is not inspectable on GitHub
- Get outdated, user need to update dependency from time to time

I'll add more information for using yeoman generator. However, samples with descriptions should be the starting point.
