### ISSUE TITLE
Get Started TOC

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2149]
Testing https://github.com/Microsoft/vscode/issues/62107

Suggestions:

Change "Your First Extension" to "Hello World"
* People with expect to see "Hello World" under Get Started and know exactly what the topic does.
Change "Extension Anatomy" to "Anatomy of an Extension"
I'm not sure if Tools of the Trade is a good title or if the topic is needed. I would pull out vsce into a publishing topic, use the Yeoman generator for Hello World, and include debugging in Hello World.

**Comment by octref** [comment]
> People with expect to see "Hello World" under Get Started and know exactly what the topic does.

Discussed with Kai and Joh, this is fine.

> Change "Extension Anatomy" to "Anatomy of an Extension"

I would like to avoid propositions on navigation.

> I'm not sure if Tools of the Trade is a good title or if the topic is needed. I would pull out vsce into a publishing topic, use the Yeoman generator for Hello World, and include debugging in Hello World.

Tools of the trade is gone. Other changes already made it in.
