### ISSUE TITLE
Build support

### ISSUE THREAD

**Issue by JanKok** [Microsoft/vscode-docs#215]
I'm trying to do C code development using gcc and make and using WebFreak001's gdb debugger extension. I added `"preLaunchTask": "make"` to launch.json and

```
{
	"version": "0.1.0",
	"command": "make",
	"isShellCommand": false,
	// Show the output window only if unrecognized errors occur.
	"showOutput": "always", //"silent",

	// use the standard tsc problem matcher to find compile problems
	// in the output.
	"problemMatcher": "$tsc"
}
```

in tasks.json and now make runs each time I click start, which is pretty good. But,
1. If there are compile errors (resulting in make returning an error value), Code doesn't stop. It tries to run the program anyway.
2. The make output window appears momentarily but is replaced with the debug console (which BTW displays the cryptic message `undefined=thread-group-added,id="i1"`). I'd like the output window to remain visible if there are make errors.
3. F8, Ctrl-Shift-M etc., don't work to let me visit the errors in my source code. What does it take to make that work?

**Comment by egamma** [comment]
>1. If there are compile errors (resulting in make returning an error value), Code doesn't stop. It tries to run the program anyway.

Does the problem matcher work and return the errors properly. You can test this by opening `View > Show Errors and Warnings`.

@isidorn @dbaeumer  any other ideas?

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode#3826
