### ISSUE TITLE
Intro to Extension Capabilities / Theming topic too complex

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2150]
Testing https://github.com/Microsoft/vscode/issues/62108 scenario 1
 
The first sentence has several unexplained references to Component Identifier and Text Token Identifier. 
"A mapping from both UI Component Identifier and Text Token Identifier to colors. "
The implementation details should be later once the user decides this is the extension point they are interested in.

Above the fold image is too small and complex and shows unexplained token visualizer.

There is no mention of the customizations settings which may satisfy most users.

I think the existing Themes content https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-color-theme does a better job of bringing the user up to speed.

In less than one minute, I could change the color of JavaScript keywords and generate a theme with the existing documentation.

**Comment by octref** [comment]
> "A mapping from both UI Component Identifier and Text Token Identifier to colors. "

The below sentence immediately explains it: Color theme allows you to apply your favorite colors to both VS Code UI Components and the text in the editor.

> Above the fold image is too small and complex and

I can make the images larger, but I think it illustrates what could be a whole page.

>  shows unexplained token visualizer.

Here is the text right above it: If you want to change the color of text in your editor, you need to know how the text is tokenized. VS Code provides a handy command Developer: Inspect TM Scopes that shows you the TextMate scopes of each syntax token in the editor.

> I think the existing Themes content https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-color-theme does a better job of bringing the user up to speed.

The point of the Extension Capabilities is to guide user to the right place, not to dive into details. The content of the original guide belongs to https://vscode-ext-docs.azurewebsites.net/api/extension-guides/color-theme.

Once the Color Theme guide is complete, I'll point it from the Extension Capabilities / Theming topic.

> In less than one minute, I could change the color of JavaScript keywords and generate a theme with the existing documentation.

Are we looking at the same page?
![image](https://user-images.githubusercontent.com/4033249/47893664-6254ad80-de1b-11e8-906c-246664a583a3.png)

**Comment by octref** [comment]
However, I do agree that some complex content should go into https://vscode-ext-docs.azurewebsites.net/api/extension-guides/color-theme.

Nobody is writing that guide, guess I have to do it...

**Comment by octref** [comment]
Made that simpler:

https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/theming

This will be the more detailed guide:

https://vscode-ext-docs.azurewebsites.net/api/extension-guides/color-theme
