### ISSUE TITLE
Testing: hello code

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#2151]
Testing #62107

## Overview:
The documentation introduce the term 'static language support' and 'dynamic language support', this is misleading terminology. Both language features are dynamic. For our existing extensions we use the terms: Basic and 'Language Features'. 
![image](https://user-images.githubusercontent.com/172399/47858408-4c7bc400-ddec-11e8-9ea8-bc3305b2e768.png)
We should follow the terminology of LSP.

'Basic concepts such as Contribution Points and Activation Points'
Activation Point should be Activation Event

## Hello Code

'When you type a URL and press Enter in a browser, you go to a website. However, a lot happens behind that seemingly simple action. Simiarly,'

This sentence doesn't add value and should be removed.

The section behind the scenes provides to much implementation detail information up front that the user will not be able to digest. This is a good section that comes much later, at this point the tutorial the user just wants to implement an extension and does not have to know about preLaunch tasks, the extension host etc. Let's give the user an early success rather than drowning the user in details.

The existing hello world section is OK to me https://code.visualstudio.com/docs/extensions/example-hello-world and gives the user a much earlier success. My proposal is to keep the existing hello example and add the behind the scenes section after this tutorial.

**Comment by octref** [comment]
> the term 'static language support' and 'dynamic language support',

They are changed to "Declarative Language Support" and "Programmatic Language Support" now throughout the doc.

> When you type a URL and press Enter in a browser, you go to a website. However, a lot happens behind that seemingly simple action. Simiarly,'
This sentence doesn't add value and should be removed.

Done. Now it's simply 3 gifs that help you quickly getting started.

While syncing with Kai, we feel there should be an "Advanced Topics / Behind the Scenes" topic that explains the implementation details, what "Extension Host" is, and some topics from https://vscode-ext-docs.azurewebsites.net/api/references/principle-and-patterns. That is tracked in https://github.com/Microsoft/vscode-docs/issues/2202.
