### ISSUE TITLE
Announcement about new Insider build on docs pages is a little haphazardly placed for screenreaders

### ISSUE THREAD

**Issue by zersiax** [Microsoft/vscode-docs#216]
I was asked by Chris Dias to review the accessibility docs over at http://code.visualstudio.com/docs/editor/accessibility just now. They are fine and neatly structured, the only issue I found is the announcement about the new insider build, which reads:

The VS Code February Release is now available along with hundreds of cool extensions and themes!

This appears somewhere below the main navigation and has no structural or semantic significance. My guess is that this shows up rather obviously visually, so I recommend preceding this announcement by some kind of heading element. Also, and I'm really nitpicking now, the little X-symbol to close that announcement is actually read out as 'Times'  by screenreader and therefore may not always be very clear in its meaning. I'm personally fine with it and I think 9 out of 10 others will be as well, but I decided to put it here nonetheless. :)

**Comment by bgashler1** [comment]
@zersiax great feedback!  Thanks.  We will be addressing this.

**Comment by gregvanl** [comment]
Moved this issue to vscode-website https://github.com/Microsoft/vscode-website/issues/130 since it involves the website banner.
@zersiax our website source lives in a separate private repo from our docs.  Sorry if you lose visibility but I'm sure Brad will keep you updated.

**Comment by zersiax** [comment]
Figured it was separate from the docs itself, but saw no better place
to post it. Thanks for moving it. :)

**Comment by bgashler1** [comment]
@zersiax I just addressed all the pain points you raised here in my latest commit, but these changes aren't live in the production website yet.  @gregvanl and I will update you once they are up, and I'd love it if you could try it out one more time and verify.  Thanks for your help!

**Comment by zersiax** [comment]
No problem :) Just let me know, I'll keep an eye out :)

**Comment by bgashler1** [comment]
@zersiax it's up and running.  Thanks again for verifying the fixes :)

**Comment by zersiax** [comment]
Looks much better, nice one :)
