### ISSUE TITLE
Docs suggestion - add ability to maximize pictures

### ISSUE THREAD

**Issue by FreHu** [microsoft/vscode-docs#2162]
Often the pictures are screenshots full of text which can be hard to read. As an example, look at the screenshots with the debugger attached at https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by octref** [comment]
Thanks - I have had this in mind for a while. Probably gonna add something like lightbox.

**Comment by gregvanl** [comment]
Closing old issue with few upvotes. Pinch zoom lets you do quickly zoom into an image.
