### ISSUE TITLE
Add git integration to documentation

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#217]
https://github.com/Microsoft/vscode/issues/744 is landing in the **March release** which will allow code to be used as the default editor for git on the command line. This is doing running the following:

```bash
git config --global core.editor "code --wait"
```

**Comment by Tyriar** [comment]
Using code as a diff tool also works, see test plan https://github.com/Microsoft/vscode/issues/4006

```
[diff]
    tool = default-difftool
[difftool "default-difftool"]
    cmd = code-alpha --wait --diff $LOCAL $REMOTE
```

**Comment by gregvanl** [comment]
git config --global core.editor "code --wait" not working on Windows for me?

C:\Users\gregvanl>git config --global core.editor "code-alpha --wait"

C:\Users\gregvanl>git config --global -e
/c/Program Files (x86)/Microsoft VS Code Alpha/bin/code-alpha: line 7: realpath: command not found
/c/Program Files (x86)/Microsoft VS Code Alpha/bin/code-alpha: line 10: ./Code - Alpha.exe: No such file or directory
error: There was a problem with the editor 'code-alpha --wait'.

**Comment by Tyriar** [comment]
@gregvanl does `"core-alpha.cmd --wait"` (or  full path) work? If not I'd move this to vscode and assign to @joaomoreno

**Comment by joaomoreno** [comment]
@gregvanl This was filed by @SofianHn in #4214. We now show a warning if you have git < v2, which is the root cause for what you are witnessing.
