### ISSUE TITLE
Tasks schema doesn't mention `isWatching`

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#218]
If you look at the example build task at https://code.visualstudio.com/docs/languages/markdown you will notice the use of `"isWatching"` in the task, but the task schema at https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/tasks_appendix.md doesn't mention such an attribute.

**Comment by gregvanl** [comment]
Looks like tasks_appendix.md is pretty stale.  Needs to be reviewed and updated to latest task interfaces.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/7dfde0f7810bb1dc1f43c02d749bf7c0ad2c9ffa
This was done in vnext so it will be several weeks before this goes to our live site.

Thanks for entering the issue.

**Comment by gregvanl** [comment]
Refreshed tasks_appendix.md with internal versions of several types.  Reopening.
