### ISSUE TITLE
Update the image of extensions at the homepage

### ISSUE THREAD

**Issue by stone-zeng** [microsoft/vscode-docs#2183]
The following [image](https://code.visualstudio.com/assets/images/Hundreds-of-Extensions.png) show hundreds of extensions for VS Code:

![Hundreds-of-Extensions](https://code.visualstudio.com/assets/images/Hundreds-of-Extensions.png)

However, some of the extensions are outdated. For example, the [VSCode-LaTeX](https://marketplace.visualstudio.com/items?itemName=ms-vscode.latex) has been labeled as DEPRECATED and has been replaced by the new [LaTeX](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) (previously called LaTeX workshop) extension. So, please consider to update this image.

**Comment by gregvanl** [comment]
@auchenberg Looks like we should to a review of this list (also see the deprecated spell checker). If you can come up with a list (based off recommended extensions?), then we can ask @misolori to create a new image.

**Comment by misolori** [comment]
Would be even better if this list could be dynamically updated (either curated or based on popularity) so we didn't have to worry about updating a static image.

cc @octref

**Comment by octref** [comment]
If I can get a marketplace API to retrieve the top extensions and their icons, I can dynamically generate these.

**Comment by octref** [comment]
Otherwise, we should take some time to go through the images. https://github.com/Microsoft/vscode-docs/issues/1822 and there's one for the topmost image at homepage too.

**Comment by auchenberg** [comment]
I like that idea @misolori, we should pull top 20 extensions from the marketplace ("most popular) which is by install numbers, but at least consistent in product, on marketplace website and our website.

**Comment by gregvanl** [comment]
The extension image list looks up to date to me. I don't see the Latex extension mentioned in the intial comment and even the Go extension image is refreshed.
