### ISSUE TITLE
Add a simple guide / sample for Commands

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#2189]
Writer: @mjbvz 
Reviewer: @octref / @jrieken 

---

Add a guide to Extension Guides / Command, and a sample at vscode-extension-samples.

- Explain 3 things: How they relate to each other, what's the use of each
  - `vscode.commands.executeCommand`
  - `vscode.commands.registerCommand`
  - `contributes.commands`
- Point to https://vscode-ext-docs.azurewebsites.net/api/references/commands

**Comment by jrieken** [comment]
don't forget 

* menus, 
* keybindings
* when clauses
* arguments 
* the fact that *anyone* can call your commands

**Comment by octref** [comment]
@jrieken I think you understand what the emphasis of this document should be more than I do, so adding you as a reviewer.

**Comment by mjbvz** [comment]
Fixed by e87428b8554108460ae57369248187ab18ef19ed

**Comment by octref** [comment]
LGTM. @jrieken if you have more feedback please open new issues.
