### ISSUE TITLE
Need to document Thenable

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#219]
doc feedback verbatim:
You need to document Thenable. I can find no documentation on it. The top result on Google for "vscode.Thenable" is this coy garbage:  https://code.visualstudio.com/docs/extensions/patterns-and-principles

**Comment by egamma** [comment]
Not sure what is meant here. The doc states that:

`Being independent of a specific promise library is expressed in the API by the Thenable-type.`

// @jrieken

**Comment by jrieken** [comment]
Sounds easy to me ;-) Maybe we should add another sentence so that it reads: `Being independent of a specific promise library is expressed in the API by the Tenable-type. It represents the common denominator which is the then-property.`

**Comment by egamma** [comment]
:+1:
