### ISSUE TITLE
Explore reorganizing js/ts docs

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-docs#2190]
Explore reorganizing the end user JavaScript and TypeScript docs. These language pages are currently quite long and difficult to browse. We should consider splitting the pages up and refreshing the content

**Comment by gregvanl** [comment]
Should have a look at https://github.com/Microsoft/vscode-docs/issues/613 during the review

**Comment by mjbvz** [comment]
**Ideas**

- Make the js/ts languages section just have the value prop @mjbvz 
- Move eslint to linter topic @gregvanl 
- JS topics will go under node/javascript (working with js) @mjbvz 
    - Intellisense and ata 
    - jsconfig 
    - Type checking?
    - tasks? 
    - Common questions

- TS will get new TS TOC node 
     - Getting started (tutorial)  @gregvanl 
     - configuration / settings (tsconfig, new ts versions) @mjbvz 
     - Compiling and debugging 
     - Debugging recipes
     - Extensions?

**Todo**
- Figure out how redirects from old headers should work
- Update fwlinks

**Comment by gregvanl** [comment]
This work has been done in the vnext branch and will go live at the 1.31 release
