### ISSUE TITLE
nuke "Programmatic Language Features" guide

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-docs#2191]
https://vscode-ext-docs.azurewebsites.net/api/language-extensions/programmatic-language-features is the most confusing thing. 

* it mixes LSP with vscode-API which doesn't make any sense at all. When would I ever implement an extension that uses LSP logic for a hover and plain extension logic for suggestions? 
* it uses a cropped real world sample, go lang, which does help. the only non boilerplate part of the code snippets is `GO_MODE` and `GoXYZProvider`. If I don't know go and if I don't know language selectors I have no clue what GO_MODE would be.
* every sample is super shallow, it only shows the invocation of `registerXYZProvider` (and LSP config) complemented with a gif. what is the point of those samples? From the API doc we already link from provider to the doc explaining what a provider is for. 

I don't really know what we wanna achieve with that guide but I would do things different

* **Clearly** separate between LSP and vscode-api, explain when and why to use what
* explain concepts instead of enumerating `registerXYZ`-calls
* use a dummy language that allows for simple but real provider implementation assuming anybody things that useful
* explain language provider ideas (without code sample) and how we utilise them, e.g. format provider is used for formatting command *and* format on save etc...

**Comment by octref** [comment]
> Clearly separate between LSP and vscode-api, explain when and why to use what

That is taken care upfront: https://vscode-ext-docs.azurewebsites.net/api/language-extensions/overview#Programmatic-language-features

> it mixes LSP with vscode-API which doesn't make any sense at all. 

I think the purpose of the doc is more telling people the mapping from our UI to the related vscode API and LSP methods. 

> If I don't know go and if I don't know language selectors I have no clue what GO_MODE would be.

Agreed. Will fix.

> use a dummy language that allows for simple but real provider implementation assuming anybody things that useful

That's a good idea. I'll try to do a plaintext Language Server Sample.

> explain language provider ideas (without code sample) and how we utilise them, e.g. format provider is used for formatting command and format on save etc...

Why "without code sample"?

I do think we need some clarification on formatting, rangeFormatting, onTypeFormatting. People are confused for them.

**Comment by jrieken** [comment]
> I think the purpose of the doc is more telling people the mapping from our UI to the related vscode API and LSP methods.

I don't know useful multiple page document is for that. In `vscode.d.ts` we usually have a lead-comment for the providers, like so:

<img width="667" alt="screenshot 2018-11-16 at 12 26 21" src="https://user-images.githubusercontent.com/1794099/48618847-e621a480-e99a-11e8-92b8-83bf0ed148c7.png">

That then links to user doc where the feature is explained in depth. I think that's sufficient but if you still wanna enumerate them all I would create a large table (in the references section) with feature-name, vscode-api-function, lsp-config. 

> Why "without code sample"? 

I don't think that a toy formatter sample will teach an author of a real language brain anything. Those people are experts and they wanna know details, pitfalls and things to watch out for.  

>I do think we need some clarification on formatting, rangeFormatting, onTypeFormatting. People are confused for them.

Honestly, in the last years I had no one asking me how to add a XYZ-provider. Finding these interfaces is easy but the details are tricky and that's where we need to provide guidance. 

My proposal would be use this query to understand where more guidance is needed: https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+label%3Aapi+question+is%3Aclosed+. That's more or less all API questions we have seen. From the top of my head I know that IntelliSense details aren't well communicated but we'll surely find more in there

**Comment by octref** [comment]
> I don't know useful multiple page document is for that. In vscode.d.ts we usually have a lead-comment for the providers, like so:

I can try to shorten that doc a bit. Let's take two more nuanced features, Signature Help and Folding.

- How do we make people realize these features are extensible by extensions?
- How can people find names such as signature help, and its corresponding API/LSP method if he doesn't know it already?
- How do we convey that folding is by default based on indentation, but you can make your language server to dynamically generate that?

> I would create a large table (in the references section) with feature-name, vscode-api-function, lsp-config.

OK, I'll include a large table towards the top. When people click into the items, they go to the anchored sections in the long document or redirected to https://microsoft.github.io/language-server-protocol/.

**Comment by octref** [comment]
@kieferrm

**Comment by octref** [comment]
As a first step, I added a table. (@dbaeumer FYI, please keep it up to date)

![image](https://user-images.githubusercontent.com/4033249/49320940-6aa31580-f4b9-11e8-92c0-9c1625534caa.png)

What sections are missing from the listing:

- TypeDefinition
- DocumentLinks
- FoldingRange

I'll add them for December.

Extras:

- Convert `go` to `plaintext`
- Publish a sample that calls these API and provides a "Hello World" minimal implementation for each language feature provider, and point people to the sample from this topic.

**Comment by dbaeumer** [comment]
@octref Thanks!
