### ISSUE TITLE
Publishing an extension should really not be an advanced topic

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-docs#2192]
https://vscode-ext-docs.azurewebsites.net/api/advanced-topics/publishing-extension I like the content but if publishing is categorised as advanced by use than we are doing something fundamentally wrong. It should (and IMO is) easy to publish an extension and it should be part of "Get Started"

**Comment by octref** [comment]
The top-voted issue in yo generator is https://github.com/Microsoft/vscode-generator-code/issues/50.

We already take out publisher out of initial extension creation, so people have less frustration upfront for creating issues. Publishing shouldn't be really involved in "Get Started". Imagine iOS beginner tutorial including content for creating developer account and publishing to iOS store.

> if publishing is categorised as advanced by use than we are doing something fundamentally wrong. 

I agree publishing shouldn't be hard and categorized as "advanced usage". Me and @kieferrm were saying "Advanced Usage" was a misnomer but we couldn't come up with a better name yet. Testing / Publishing is like "working with extensions", but some topics like "Proposed API" is clearly advanced...

What do you think about adding one more section "Working with extensions" under "Get started"? The content is all "how do I do X for my extension".

- Testing
- Publishing
- Continuous Integration
- Profiling
- Bundling (your webpack work)

Advanced section is more "how do I use this advanced thing inside my extension".

- Proposed API
- Exposing API
- Using Native Modules
- Using WASM

**Comment by octref** [comment]
Did that, and most people in Redmond like it so I'm pushing.

![image](https://user-images.githubusercontent.com/4033249/48586895-1eb37680-e8e6-11e8-9bb0-1c237c70e4c1.png)

![image](https://user-images.githubusercontent.com/4033249/48586890-19eec280-e8e6-11e8-9d10-31eac8b079ed.png)
