### ISSUE TITLE
Issue with Tree View Guide

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#2194]
https://vscode-ext-docs.azurewebsites.net/api/extension-guides/tree-view

- The guide should explain upfront what is Tree View and what is View Container (best with a illustration like https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/extending-workbench)
- Does not mention `test` as one of the location. Where is it?
- Does not explain `contributes.views.tree-view`. 
- Sample code do not match the latest code in https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/package.json.
- View Actions have no image showing what/where they are

**Comment by sandy081** [comment]
> Sample code do not match the latest code in Microsoft/vscode-extension-samples:tree-view-sample/package.json@master.

Not sure what you mean by that? Tree view sample in the master is the latest. Shall I have to update the extdocs branch?

**Comment by octref** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/4033249/48635302-9e8c2000-e97c-11e8-91dd-8d20d3be1f4a.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/4033249/48635339-b663a400-e97c-11e8-83ae-b458c1ba6781.png">

I mean in the doc, use sample code that people can find in the samples. This way they won't get confused when looking for the example in the sample.

**Comment by octref** [comment]
For the sake of consistency I'll try to make illustrations and explain View / View Container. @sandy081 you can just focus on addressing the rest of the feedback. Thanks!

**Comment by sandy081** [comment]
@octref Got it. I updated the tree view guide with necessary explanation of views, view containers and actions. Also added screenshots for better understanding.

Updated the code in master to be in sync with sample. This was a copy paste issue.
