### ISSUE TITLE
Review Workbench topic

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#2196]
https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/extending-workbench

@isidorn Please do a read through and fact checking for the topic. Point out anything you don't like.
For smaller changes, feel free to directly make changes.

**Comment by bpasero** [comment]
@octref I think there is more to extending the workbench:
* adding entries to menus
* adding actions to toolbars (e.g. editor)

Other workbench pieces useful to know about (not really "extendind"):
* notifications
* progress
* pickers
* status bar message
* input wizards
* modal dialogs (including file dialogs)
* output channels
* source control provider
* debug adapter (?)

**Comment by octref** [comment]
- notifications
- progress
- pickers
- modal dialogs (including file dialogs)

These are covered in https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/common-capabilities. 

- status bar message

That's the last one in the workbench topic, right?

- input wizards

Not sure which one is this. 

- output channels: We don't have anything for it. We can either put together a simple guide for it, or just briefly mention it in https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/common-capabilities.

- source control provider: See https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/overview#core-extensions and https://vscode-ext-docs.azurewebsites.net/api/extension-guides/scm-provider

- debug adapter: In [this topic](https://vscode-ext-docs.azurewebsites.net/api/extension-guides/debug-extension) and Andre'll [update](https://github.com/Microsoft/vscode-docs/issues/2195) it

**Comment by bpasero** [comment]
> That's the last one in the workbench topic, right?

Yeah, could be added to that topic. But probably not worth mentioning given that progress can now also be displayed much better using notifications. But this is a progress message that shows up in the status bar, which is different from status bar items.

> Not sure which one is this.

All the API  @chrmarti added to ask the user for input through pickers.

**Comment by octref** [comment]
> input wizards

I see, QuickInput is mentioned in https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/common-capabilities#quick-pick. Created https://github.com/Microsoft/vscode-docs/issues/2214.

**Comment by octref** [comment]
`OutputChannel` is a simple concept and I just briefly mentioned it in https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/common-capabilities.

All other feedback are either addressed or have tracking issues.
