### ISSUE TITLE
Write the color theme topic

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#2197]
Writer: @Tyriar (Please ping the reviewer once you are done with writing)
Reviewer: @bpasero 

Instructions are at: https://vscode-ext-docs.azurewebsites.net/api/extension-guides/color-theme
File to edit: https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/color-theme.md

**Comment by Tyriar** [comment]
Done, ready for review @bpasero. I mainly migrated the content over from https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-color-theme and did a bit of clean up.

**Comment by bpasero** [comment]
Thanks, LGTM
