### ISSUE TITLE
Advanced Topics / Behind the Scenes topic

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#2202]
- Explain the details of "what happens when you press F5 on the hellocode sample"
- Explain what is "ExtensionHost"
- Some contents from https://vscode-ext-docs.azurewebsites.net/api/references/principle-and-patterns.

**Comment by gregvanl** [comment]
Principle and Patterns was moved into the generated API reference. Rather than a new topic, we could add more explanation there. Closing old issue.
