### ISSUE TITLE
Find a good place for content in Principles and Patterns

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#2203]
The current content of https://vscode-ext-docs.azurewebsites.net/api/references/principle-and-patterns is a hodgepodge, addressing a wide range of audiences:

- Some contents are very basic for **beginners**, like "Using Node.js modules with Extensions".
- Some content are for **every extension developers**, like "No access to DOM", "Extension Isolation / Stability"
- Some contents are for **API readers**, like "Pormises", "Cancellation Tokens", etc

We should split these contents into meaningful places. For example:

- Some content can go to a new topic "Advanced Topics / Extension Host" that explains the extension host runtime
- Some content can become a top section of https://vscode-ext-docs.azurewebsites.net/api/references/vscode-api

**Comment by octref** [comment]
Related https://github.com/Microsoft/vscode-docs/issues/2202

**Comment by gregvanl** [comment]
Some telemetry: 
- ranked #123 in terms of pageviews with only 2K page views in November
- only 4 ratings for November 3/4 smiles.
Given the low page views, we may want to look at pulling out those sections we think are important for extension authors and move them to other topics.
