### ISSUE TITLE
Guide for using contributes.menus

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#2207]
Position: Extension Guides / Menu

This should be one of the options visually explained in https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/extending-workbench.

Move content from https://vscode-ext-docs.azurewebsites.net/api/references/contribution-points#contributes.menus to this guide, as the reference should stay succinct.

**Comment by gregvanl** [comment]
Closing old work item issue with no upvotes. As mentioned contributes.menus is currently covered.
