### ISSUE TITLE
Update tree-view illustrations

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#2208]
https://code.visualstudio.com/api/extension-guides/tree-view

It should follow the same style as the ones in the Workbench illustration.

**Comment by gregvanl** [comment]
This extension guide page is currently at 25% CSAT and there have been several negative doc feedback comments.

**Comment by gregvanl** [comment]
Fixed with recent updates including https://github.com/microsoft/vscode-docs/commit/73885458bce562c6ac7e7874d7b5bcb812fff83d, which adds an image with caption below.
