### ISSUE TITLE
Document using native modules

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#2211]
Ref: https://github.com/Microsoft/vscode/issues/658

Next time someone really asks for using native modules, please write a doc instead of responding in GitHub issues.

Todo:

- [ ] Put enough warnings upfront
- [ ] Put together a sample, maybe using sass or oniguruma?
- [ ] Explain pitfalls of using native modules

**Comment by stef-levesque** [comment]
Alternatively, having documentation for using WebAssembly in VSCode Extensions would be helpful too!

**Comment by octref** [comment]
@stef-levesque Oh I was just about to create that issue, did that with #2212

**Comment by anurbol** [comment]
Any progress on this? 

I can't remember if I ever was as sad and disappointed by a technology as in recent days, when I have been trying to figure out why my native module doesn't work with (different versions of) VSCode. I've invested so many time into it to realise that it is not going to work without an additional ridiculous process of building and testing against every single possible version of VSCode, and checking if new ones are released etc.

I know they had their reasons, but why did Electron team made this (I am sorry) stupid restriction on native modules when node.js itself doesn't have one? Just a rant.

**Comment by gregvanl** [comment]
Closing old issue. No recent upvotes
