### ISSUE TITLE
Document using WASM in extensions

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#2212]
- [ ] Put together a sample using a WASM module (maybe onigasm?)
- [ ] Document how to use WASM in VS Code, and related pitfalls, etc

**Comment by lawrencegripper** [comment]
Is this work still ongoing? About to attempt doing some stuff with WASM generated by Golang then being used in an extension.

**Comment by freebroccolo** [comment]
@lawrencegripper I'm not sure if it's relevant to what you're interested in but I made an example WASM extension in Rust [here](https://github.com/interfaces-rs/vscode-sys/tree/master/examples/hello). Seems to work fine.

**Comment by lawrencegripper** [comment]
@freebroccolo Thanks will have a play , I've nearly got a sample together with GoLang

**Comment by gregvanl** [comment]
Closing old work item issue without upvotes.
