### ISSUE TITLE
matplotlib installation troubles - macOs

### ISSUE THREAD

**Issue by susanin76** [Microsoft/vscode-docs#2213]

**Comment by gregvanl** [comment]
Hi @susanin76 Can you provide more details about your issue? Thanks

**Comment by susanin76** [comment]
Hi,  VScode novice, tried to install matplot lib by entering line command "sudo python3 -m pip install matplotlib" as suggested, but  "NameError: name 'plt' is not defined"
Ran debugger, here attached what I came across at the outputs end:

ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

I then realised Matplotlib was already installed, maybe that's the reason why this second action didn't work out, but can't really make it out how to proceed  to fix it. 
Thanks for your kind suggestions

**Comment by kraigb** [comment]
Can you try adding `import matplotlib` before the line `import matplotlib.pyplot as plt`? This StackOverflow thread suggests that might be the solution: https://stackoverflow.com/questions/37859104/name-plot-is-not-defined.

**Comment by susanin76** [comment]
Tried it, but didn't work( should I uninstall from anaconda distribution
and have another try via Vscode?

Il giorno mar 20 nov 2018, 23:36 Kraig Brockschmidt <
notifications@github.com> ha scritto:

**Comment by kraigb** [comment]
Hmmm. I really don't know offhand. Did you investigate any of the other referenced material in the error message, e.g. the  'Working with Matplotlib on OSX' in the Matplotlib FAQ? (https://matplotlib.org/faq/osx_framework.html)

**Comment by Eelman** [comment]
Hi susanin76,

I'm a complete novice as well and I'm guessing you are following along here (https://code.visualstudio.com/docs/python/python-tutorial)?  

I was having the same issue when selecting "Run Python File in Terminal" but it works when I Select All (Ctrl-A) then Run Code (Ctrl-Alt-N) so I guess it's just that this can't be run using that command? Not sure.

I'm on a Windows 7 machine 64-bit
