### ISSUE TITLE
Turn QuickInput sample into a guide

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#2214]
The QuickPick API is the only way for extension author to easily get user input. It's mentioned in https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/common-capabilities#quick-pick and has a sample, but I think it's worth it to write up a short guide explaining various usages of the API.

**Comment by chrmarti** [comment]
The `createQuickInput` API is advanced. We should first check how many usages there are.

**Comment by octref** [comment]
@chrmarti It can have advanced and simple usages. `Common` in this case means `essential` because this remains the only viable way for ext author to collect user input.

It's in the extensibility backlog, so no hurries. Maybe next time when someone asks you how to use the QuickPick API, instead of writing a GH issues write it as a guide here.

**Comment by gregvanl** [comment]
Closing old work item issue without upvotes.
