### ISSUE TITLE
Documentation examples for snippets format if/else

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-docs#2215]
Would if be possible to add some more examples in the snippets configuration documents?

I would particularly like to understand how to add an alternative to the format transform.

At the moment whatever I try just seems to repeat each character of the capture group with my alternative text?

**Comment by gregvanl** [comment]
Closing older issue. I think this is covered in https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples.
