### ISSUE TITLE
Document the “icon” option of extension commands

### ISSUE THREAD

**Issue by FranklinYu** [microsoft/vscode-docs#2220]
Some extension has commands with icons, such as [GitLens](https://github.com/eamodio/vscode-gitlens/blob/4ddb871459a3a1a1e132c8bdf83ac12e3b699649/package.json#L1546-L1554) (warning: large JSON file). Snippet of that section:

```json
{
    "command": "gitlens.diffWithNext",
    "title": "Compare File with Next Revision",
    "category": "GitLens",
    "icon": {
        "dark": "images/dark/icon-next-commit.svg",
        "light": "images/light/icon-next-commit.svg"
    }
}
```

Is this documented somewhere? [Current documentation](https://github.com/Microsoft/vscode-docs/blob/c3e701ffb9e77c7831d5796a01de2bd27a8c9c52/docs/extensionAPI/extension-points.md#contributescommands) seems to only cover command, title, and category.

**Comment by gregvanl** [comment]
https://code.visualstudio.com/api/references/contribution-points#contributes.commands does mention icons.
