### ISSUE TITLE
Where are command descriptions displayed?

### ISSUE THREAD

**Issue by tetchel** [Microsoft/vscode-docs#2225]
The example at https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands makes clear how the "title" and "category" attributes are shown to an extension's user. 
However, I don't see anywhere in the UI where the command's "description" is presented. Where does this show up? Could it be added to the example page above?

Thank you

**Comment by tetchel** [comment]
Realizing now that I never saw anything from Microsoft that references this attribute, and that it isn't in the package.json schema. I think I might have just started using this because another extension I was using as an example uses this - but it might only be for the extension's developers. 

Am I just wasting time by setting this? 😄

**Comment by gregvanl** [comment]
Hi @tetchel I just double-checked with the product team and you're correct that there isn't a "description" attribute used by VS Code.

**Comment by tetchel** [comment]
That's embarrassing, thanks 😄

**Comment by gregvanl** [comment]
@tetchel Not at all. Thanks for taking the time to bring up a possible doc issue.

**Comment by tetchel** [comment]
They actually are displayed if you open an Extension README in the editor, although this doesn't play nicely with using `package.nls.json`!

![image](https://user-images.githubusercontent.com/8888438/51191899-638e6600-18b3-11e9-83ee-e9a5d9f96b98.png)
