### ISSUE TITLE
API topics missing ms.ContentId in header

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2234]
ms.ContentId is a fixed GUID which uniquely identifies the topic and is used by content team DEVDIV reporting.

Currently it comes from the ContentId field in the topic metadata header.

```
Order: 5
Area: extensionapi
TOCTitle: Contribution Points
ContentId: 2F27A240-8E36-4CC2-973C-9A1D8069F83F
PageTitle: Visual Studio Code Extension Contribution Points - package.json
DateApproved: 11/8/2018
```

**Comment by gregvanl** [comment]
@octref @kieferrm Thinking about this more, I think we should keep the ContentId GUID in the document header rather than put it in the TOC.json for a couple of reasons:
- We should keep the identifier with the object it identifies, which is the topic.
- It will clutter the TOC.json. The TOC.json should just show the layout of the topics and not their metadata. Right now the TOC.json is very clear with just the structure and TOC text.
- This separation matches the repos for docs.microsoft.com. Per page metadata is in the topic, TOC structure in a TOC.yaml.
- As long as this field is documented in CONTRIBUTING.md, I don't think it will confuse writers.

**Comment by octref** [comment]
I tried **very hard** to make it simple for our team member to write `/api` doc without having to remember strange rules:

- Unlike GitHub links, I have to add `.md` to each Markdown link
- I need to add a `DateApproved` to each file although I have no idea what that is for, so I should probably just put the current date
- Now I even need to get a GUID for just writing a new topic

In my initial version someone from VS Code team can `touch my-topic.md` and write standard Markdown to create a new topic. He can easily modify topics in `toc.json`.

Now he already needs to suffer from managing a `DateApproved`. Can we spare him from having to manage yet another property that he doesn't know or care about and focus on, like, writing the docs?

Making it hard to start a new topic gradually generates mega topics that's hard to read, like https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers. That's also (my guess) why people prefer to write in vscode-wiki, like:
- @bpasero on https://github.com/Microsoft/vscode-wiki/blob/master/Adopting-Multi-Root-Workspace-APIs.md
- @jrieken on [Proposed API](https://github.com/Microsoft/vscode-wiki/blob/master/Extension-API-process.md)
- @aeschli even started writing **on the wiki of a private vscode repo** on the topic of embedded language

I want to make it easy for team members to create, move and breakdown the topics in `/api`, which they'll be the main contributors.

**Comment by octref** [comment]
In short, I think it's the complicated process that prevents team members from easily:

- Add a topic
- Break down a large topic
- Rename a topic
- Move topic in TOC

that resulted in the mess in `/docs/extensions` and `/docs/extensionAPI`. The current TOC does not make sense, and in the two years I'm here the only new topic I see is Webview.

**Comment by octref** [comment]
Done.
