### ISSUE TITLE
API topics relative topic links aren't navigatable from GitHub

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#2236]
Relative links need to have `.md' so that they work as links on GitHub, where a surprising number of users read out topics.

We already support this in the /docs topics but the current logic to preprocess out '.md' from relative topic links doesn't include 'api'. It is a one line fix to make the build aware of the new /api location.

from vscode-website gulpfile.common.js:

```
fileContents = fileContents.replace(/\(\/(blogs|updates|docs|tutorials).+\.md\)/g, function(str) { return str.replace(/\.md\)/g, ')'); } );
```

**Comment by octref** [comment]
These are URLs, not path-to-files. They are not designed to be working on GitHub.

Anyone clicking onto links such as `/api/references/vscode-api#commands` will fail. We should not try to support those use cases.

**Comment by gregvanl** [comment]
It's a one-line change to support GitHub. I don't understand why we wouldn't want to do it. We already support it for /docs and users really like it.

**Comment by octref** [comment]
1. When we link to `(/license)`, we mean to guide users to `https://code.visualstudio.com` + `/license`, not `https://github.com/Microsoft/vscode-docs` + `/license.md`
2. GitHub handles hash links differently than our website. All the `#_` links never work for GitHub.

**Comment by gregvanl** [comment]
Have a look at vscode-website gulpfile.common.js. There is code there to remove .md and also handle .md#.

```
    // remove .md file extensions from topic links (only our relative links)
  fileContents = fileContents.replace(/\(\/(blogs|updates|docs|tutorials).+\.md\)/g, function(str) { return str.replace(/\.md\)/g, ')'); } );

  // need to remove embedded .md before # section tags and place _ underscore after for cshtml navigation
  fileContents = fileContents.replace(/.md#/g, "#_");
```
H2 header links work for our docs on GitHub. It's not pretty but it works.
I guess it's your call if you don't want to support GitHub navigation for the /api topics.

**Comment by octref** [comment]
Thanks for understanding. I read through the last commits in ext-docs by 5 others. None of the new contents written uses .md. It's not part of standard Markdown and we should not have weird compile rules that team members and contributors can't find info anywhere.

**Comment by gregvanl** [comment]
Reopening as it turns out docs.microsoft.com content allows GitHub navigation and uses relative topic links with the .md extension.

**Comment by octref** [comment]
I don't think we reached an agreement here. Can we move this to December? This does not block shipping.

>  people click on what appear to be broken links ;-)

I would be more worried that we deviate from standard markdown so contributors need to learn weird rules for contributing.

**Comment by gregvanl** [comment]
Closing as haven't heard any users asking for GitHub navigation for the /api docs.
