### ISSUE TITLE
No mention of .vscode/extensions folder in API topics

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2240]
There was a section in the removed yocode.md topic. 

Do we want extension authors to side-load an extension under development (as described in the "Test a new Color Theme" section in api/extension-guides/color-theme topic) or should they always rebuild a VSIX and install that way (does that involve having un-install and two reloads?).

**Comment by octref** [comment]
It's possible to specify a launch.json for color themes, and it's much easier to test it that way. I've fixed the color theme guide.

Meanwhile the `.vscode/extensions` content is still useful. Now it's at publishing extensions topic right after "Packaging Extensions".
