### ISSUE TITLE
/docs and /api are using different style H2 header links

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2243]
/docs use topic#_header while /api uses topic#header (no underscore)

docs/setup/setup-overview#_cross-platform
api/get-started/your-first-extension#developing-the-extension

I'm not sure why code.visualstudio.com is using the underscore but if we change /docs to not have the underscore, we will break any existing hard-links created externally (include VS Code product links).

**Comment by octref** [comment]
As discussed:

- /api will have no underscore. /docs will continue to have it.
- For this release, we'll make sure redirects works (such as /docs#_foo to /api#foo)
- We can look into deprecating `_` links in /docs later. Old `#_foo` links will continue to work and point to the same location as `#foo`, but if you click `#` sign next to headers on the updated pages, it should go to anchors without `_`

**Comment by octref** [comment]
This is implemented, and redirects are available.

https://vscode-ext-docs.azurewebsites.net/docs/extensions/example-tasks#_task-definition
