### ISSUE TITLE
Need to do a full pass on relative topic links in /api

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2244]
We need to check for broken links across all the topics after the redirects are implemented.

Some H2 links aren't working since `topic.md#header` is not being converted.

For example in api/extension-guides/command, in the Controlling when a command shows up in the Command Palette section the when clause link 404s since it is docs/getstarted/keybindings.md#when-clause-contexts

**Comment by gregvanl** [comment]
Closing as will be covered during testing of https://github.com/Microsoft/vscode-docs/issues/2165

**Comment by gregvanl** [comment]
The /api topics need a full pass on links. See https://github.com/Microsoft/vscode-docs/issues/2293.
Doesn't look like this testing was covered with https://github.com/Microsoft/vscode-docs/issues/2165

**Comment by tuttieee** [comment]
Hello,

The link below

> - How to add [integration tests](/api/working-with-extensions/testing-extensions) for your extension

in https://code.visualstudio.com/api/get-started/wrapping-up ( https://github.com/Microsoft/vscode-docs/blob/master/api/get-started/wrapping-up.md ) goes nowhere.

I think this should point to /api/working-with-extensions/testing-extension, not /api/working-with-extensions/testing-extension**s**

**Comment by octref** [comment]
@tuttieee Fixed, thanks!

**Comment by gregvanl** [comment]
Closing as community is finding broken links and either entering issues or PRs.
