### ISSUE TITLE
Should /api topic description be full sentence rather than TOC title | section

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2245]
Under /docs, we can use the MetaDescription header field to add a full sentence of text to the web page header 'description' and 'og:description' fields.

For example: /docs/extensions/example-hello-world:

```
<meta name="description" content="Create your first Visual Studio Code extension (plug-in) with a simple Hello Word example." />
```

Now under /api, we use the TOC title with the section name:

```
<meta name="description" content="Your First Extension | Visual Studio Code API" />
```

Having a longer description lets us add alternate terms for example 'plug-in' for extension. Will the shorter format affect SEO?

**Comment by octref** [comment]
```
---
# Please summarize the whole topic in less than 300 characters for SEO purpose
MetaDescription: 'This topic explains Debugging'
---
```

**Comment by octref** [comment]
`MetaDescription` is now available for `/api` docs. If it's not set, it falls back to `${ Title } | VS Code API`.
