### ISSUE TITLE
Just need shortcut about : 'workbench.action.gotoSymbol.category' 

### ISSUE THREAD

**Issue by zhuzhuyule** [Microsoft/vscode-docs#2246]
int the key bindings setting, I can find those:
![](https://i.loli.net/2018/11/30/5c00d2d94ef38.png)
![](https://i.loli.net/2018/11/30/5c00d2d94076f.png)

but not find keybinding command support this
![](https://i.loli.net/2018/11/30/5c00d3b5e316f.png)

I want add shortcut to binding: open command and input '@:'.

Can you help me?

**Comment by gregvanl** [comment]
Here's a way from one of the VS Code dev team:

```son
    {
        "key": "cmd+1",
        "command": "workbench.action.quickOpen",
        "args": "@:"
    }
```

**Comment by zhuzhuyule** [comment]
@gregvanl 
Thanks you!
You are right, thank you very much.

**Comment by gregvanl** [comment]
@zhuzhuyule You're welcome. Might be good to add to the tips and tricks topic at https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_go-to-symbol-in-file. Are you interested in submitting a PR?
