### ISSUE TITLE
/api Markdown has hard-coded paths to staging server

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2247]
There are a lot of links to https://vscode-ext-docs.azurewebsites.net in the Markdown files.

The generated api/extension-guides/overview table "Guide on VS Code website" and "API & Contribution" columns use the absolute URL.  

The samples table in https://github.com/Microsoft/vscode-extension-samples also has the same staging server links.

**Comment by octref** [comment]
Trakced in #2165.
