### ISSUE TITLE
Open in VC github project from section Python/Unit Testing

### ISSUE THREAD

**Issue by matiaso11** [Microsoft/vscode-docs#2251]
How can I open project from https://github.com/gwtw/py-sorting repository ? I got "[pylint] Unable to import ..." errors for all local files. How I can run tests ? I have added to Workspace Settings: 
    "python.unitTest.unittestEnabled": true,
    "python.unitTest.pyTestEnabled": false,
    "python.unitTest.nosetestsEnabled": false
But after run test I got:
    File "c:\Users\Dev\python\py-sorting\test\selection_sort_test.py", line 5, in <module>
        from base_custom_comparison_sort_test import BaseCustomComparisonSortTest
    ModuleNotFoundError: No module named 'base_custom_comparison_sort_test'
    FAILED (errors=15)

How should I configure Workspace Settings ??

**Comment by matiaso11** [comment]
I think that general question is: How to open in Visual Code existing Python/Django project?

**Comment by kraigb** [comment]
Open the project using File > Open Folder on your cloned folder. After that, you can right-click any of the _test files and select **Run Python File in Terminal**. That successfully ran each test file. That should work.
