### ISSUE TITLE
self.log_date.strftime in section "Python/Django Tutorial" chapter "Define models"

### ISSUE THREAD

**Issue by matiaso11** [Microsoft/vscode-docs#2252]
In [section "Python/Django Tutorial" chapter "Define models"](https://code.visualstudio.com/docs/python/tutorial-django#_define-models) there is pylint [E1101]:
[pylint] Instance of 'DateTimeField' has no 'strftime'...

Refering to [stackoverflow](https://stackoverflow.com/questions/11909071/using-strftime-on-a-django-datetime-produces-a-utc-time-in-the-string)
"timezone.localtime" function has fixed the problem.

**Comment by kraigb** [comment]
Thanks for that suggestion! I'll admit I hadn't noticed the linter detail, so I'll fix it in the sample and the docs both.
