### ISSUE TITLE
Storage. Db is automatically generated

### ISSUE THREAD

**Issue by changmu811** [Microsoft/vscode-docs#2255]
Storage. Db is automatically generated.
Every time when vscode is running, close the folder and open the folder again, the.db file will be generated in the directory of c disk C:\Users\???\AppData\Roaming\Code\User\workspaceStorage
The effect that does not generate before, thank!!!

**Comment by gregvanl** [comment]
Hi @changmu811 This is related to our migration to SQLLite. You can follow the progress at https://github.com/Microsoft/vscode/issues/64142
