### ISSUE TITLE
The theme color reference is a bit of a mess

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode-docs#2264]
I'm maintaining a [theme](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-monokai-night) with the stated goal that it themes every single themeable color. While developing and maintaining it I'm finding a few issues with the whole [color reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference) thing.

### Colors missing from the reference 

My theme is currently theming the following colors:

- breadcrumb.background
- editorGroup.background

They are not even mentioned in the reference, I guess I got them from a release note, who knows.

### Missing colors from release notes (maybe?)

In my theme's first release I've themed every single color, and I've always paid attention to the release notes for any added colors. Still, quite surprisingly to me, all these colors are now present in the reference but my theme is not customizing them:

- diffEditor.border
- diffEditor.insertedTextBorder
- diffEditor.removedTextBorder
- editor.findRangeHighlightBorder
- editorOverviewRuler.commonContentForeground
- editorOverviewRuler.rangeHighlightForeground
- editorOverviewRuler.selectionHighlightForeground
- editorRuler.foreground
- editorUnnecessaryCode.border
- editorUnnecessaryCode.opacity
- editorWidget.resizeBorder
- gitDecoration.addedResourceForeground
- gitDecoration.submoduleResourceForeground
- list.inactiveFocusBackground
- list.invalidItemForeground
- merge.border
- merge.commonContentBackground
- merge.commonHeaderBackground
- panel.dropBackground
- peekViewEditor.matchHighlightBorder
- statusBar.debuggingBorder
- statusBar.noFolderBorder
- tab.hoverBackground
- tab.hoverBorder
- tab.unfocusedHoverBackground
- tab.unfocusedHoverBorder

Maybe I did a very poor job on my first release and left out all of them, but I think it's more likely that they have been added over time but they have not been mentioned in the release notes. If that's the case that's a problem, we can't be expected to keep monitoring the reference for updates.

### Difficult to theme properties

Most properties are obvious, but some of them I didn't immediately understand what they were theming, like: 

- editor.focusedStackFrameHighlightBackground
- editor.stackFrameHighlightBackground

Some more screenshots would be appreciated.

Also in order to theme some colors, like:

- notification.errorBackground
- notification.errorForeground
- terminal.ansiBlack
- terminal.ansiBlue

We need to see how they are actually being used, i.e. we need to trigger all kinds of custom notifications and have a script that uses all colors in the terminal. It might be good to develop some "official" scripts for this or at least link to third-party's scripts we could use.

### Incomplete colors support

The whole set of provided themeable colors seems incomplete to me. It seems to me almost like unless a particular color in a particular state is not themed explicitly by VSCode itself then that color isn't themeable at all by themes.

One quick example, tabs now have a top border, and they can be in one of these states: active, inactive, unfocused-active, unfocused-inactive.

If we want to customize the top border for active tabs we have tab.activeBorderTop, for unfocused-active tabs we have tab.unfocusedActiveBorderTop, and the other states just aren't themeable (or I guess those properties aren't mentioned in the reference?). 

### Poorly searchable/manipulable properties

Coming up with these lists of properties was a bit painful, it would be better if there was a JSON file or something that listed all of them, so that I could diff my theme's settings with it. Also seeing what values are assigned to those properties by default would be useful. Maybe this file exists already somewhere in the repo, if it does it should be mentioned in the reference as well.

**Comment by fabiospampinato** [comment]
> editorUnnecessaryCode.opacity: Opacity of unnecessary (unused) source code in the editor. For example, "#000000c0" will render the code with 75% opacity.

@aeschli This looks pretty weird to me, is the schema non able to handle this use case properly? It doesn't make sense to explicitly pass a red, green and blue components for the opacity.

**Comment by aeschli** [comment]
@mjbvz added this, but IMO it's a pragmatic solution that avoids adding another data type to theme descriptions (now they are all a set of colors).

**Comment by fabiospampinato** [comment]
> it's a pragmatic solution that avoids adding another data type to theme descriptions

Why would anyone want that though? The point of types is to help catch errors and help the person who's using them. The fact that we are expecting a color for the opacity doesn't make sense and made me (and probably other people who attempted to customize that too) waste time on this.

**Comment by gregvanl** [comment]
We now have tooling to detect missing theme colors which is run during each end game.
