### ISSUE TITLE
Tracking issue for /api metadata

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2270]
topic metadata | header metadata | issue | comment
--- | --- | --- | ---
DateApproved | ms.date | https://github.com/Microsoft/vscode-docs/issues/2233 | done
ContentId | ms.ContentId | https://github.com/Microsoft/vscode-docs/issues/2234 | goes in topic
MetaDescription | description og.description | https://github.com/Microsoft/vscode-docs/issues/2245 | done
MetaSocialImage | og.image |  | leave as is https://code.visualstudio.com/opengraphimg/opengraph-docs.png

Described in https://github.com/Microsoft/vscode-docs/blob/master/CONTRIBUTING.md#topic-metadata

**Comment by octref** [comment]
All done.
