### ISSUE TITLE
Add documentation on setting up ESLint

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#229]
Since we no longer provide built-in linting we should document that we recommend to install a linter and use ESLint as an example.

This can be harvested from the change notes.

```
We strongly recommend that you install and configure a JavaScript linter if your project hasn't done so already.

Here are the steps to set up eslint:

npm install eslint to install eslint into your workspace or npm install -g eslint to install it globally.
install the VS Code eslint extension.
use eslint --init to create an initial eslint configuration by answering questions or by picking a popular configuration.
Tip: If you use JSON as the format of the eslint configuration file, then VS Code can provide you with IntelliSense when you edit the .eslintrc.json file.

```

**Comment by gregvanl** [comment]
There is a Linters section in JavaScript.md so I believe this is completed.
Please reactivate if we need to add an ESLint section somewhere else (maybe the Node.js runtime topic where we just list ESLint as a useful extension?).

**Comment by egamma** [comment]
Agreed this is now covered.
