### ISSUE TITLE
Many broken links on Extensions Guides overview page

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#2293]
For example:

The Sample column links don't look like they are meant to be links and 404.
There is no Status Bar guide to link to.
The https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#language-client--language-server link creates a new wiki page.

**Comment by octref** [comment]
These are all auto-generated. They are fixed now.
