### ISSUE TITLE
Python - Django tutorial runserver config single threaded causes loop with chrome

### ISSUE THREAD

**Issue by c-yco** [Microsoft/vscode-docs#2303]
The debug profile here: [https://github.com/Microsoft/vscode-docs/blob/master/docs/python/tutorial-django.md](url)

can be problematic together with chrome:
https://code.djangoproject.com/ticket/16099
https://code.google.com/p/chromium-os/issues/detail?id=13043

Chrome creates two request when trying to connect, which hangs the testserver in a loop in single threaded mode. 

removing "--nothreading" from the debug configuration fixed this.

**Comment by kraigb** [comment]
Thanks @c-yco. I'll add a note with that warning.
