### ISSUE TITLE
Python tutorial: plot closes right after script ended

### ISSUE THREAD

**Issue by SCBuergel** [Microsoft/vscode-docs#2318]
The plot window in the tutorial closes immediately after the script is done running. This is probably expected but very different from what is described there, this should be at least mentioned. When I instead single-step through the code, I can see the plot for that step.

- VSCode Version: Version 1.30.1 (1.30.1)
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Follow your [python tutorial](https://code.visualstudio.com/docs/python/python-tutorial). 
2. At the end of section [install and use packages](https://code.visualstudio.com/docs/python/python-tutorial#_install-and-use-packages) it tells me that `after a few moments a plot window appears with the output`. This is only partially true, the plot window opens and immediately closes again (not even visible).

**Comment by kraigb** [comment]
@SCBuergel Can you try changing the last line of the code to `plt.show(block=True)`? https://stackoverflow.com/questions/40061044/keep-pandas-matplotlib-plot-open-after-code-completes suggests that should do the trick. (It's a Mac-specific behavior, it seems.)

Let me know if that works and I'll update the docs accordingly.

**Comment by SCBuergel** [comment]
In the meantime I did the update to VS 1.30.2 and the issue seems to be resolved. The plot remains open upon completion of the script without any changes to the code that is given in your [tutorial](https://code.visualstudio.com/docs/python/python-tutorial#_install-and-use-packages). I have to admit this is a bit of a mystery to me. I did not try again on a clean installation though.

**Comment by DoudiCoder** [comment]
Hello.
I'm experiencing the same issue now. 
With the same code snipped from the tutorial, using plt.show() or plt.show(block=True) causes the script to pause until the plot window is closed; if I stop the execution then the plot window closes. Using plt.show(block=False) or not putting plt.show() altogether results in no plot being displayed.

VS Code 1.74.3 on MacOS 13.1
Python 3.9.6
matplotlib 3.6.3

Thanks!
