### ISSUE TITLE
Review and update PHP topic

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#2322]
The languages/php topic gets a moderate number of pageviews (ranked 30) but has a higher than expected number of rating and comments indicating an engaged community.
Review the topic and doc feedback verbatim and update the topic.
- mention that need to install PHP (not included in VS Code install)
- address https://github.com/Microsoft/vscode-docs/issues/2365

**Comment by oriash93** [comment]
@gregvanl I think you referenced the wrong issue/PR, could it be?

**Comment by gregvanl** [comment]
Hi @oriash93, Thanks for pointing this out. It was meant to be the topic pageview rank not a link.

**Comment by gregvanl** [comment]
Pageviews seem to be going down (ranked 38) and not many recent comments (mostly smiles). Closing.
