### ISSUE TITLE
global search: backreferences are not supported

### ISSUE THREAD

**Issue by xiaoqianghaochi** [microsoft/vscode-docs#2325]
global search: backreferences are not supported；
eg:  (\w.+):\ \1

**Comment by gregvanl** [comment]
Hi @xiaoqianghaochi Yes, this is true that backreferences are not supported by default but you can try the search.usePCRE2 setting to use the PCRE2 regex engine.

https://code.visualstudio.com/updates/v1_29#_backreferences-and-lookahead-in-search

**Comment by frnk94** [comment]
Hello ! I ran into this issue so I added the following config to my `settings.json`: 
```json
{
  "search.usePCRE2": true,
}
```

Adding this line result in my editor telling me this message:
> Deprecated. PCRE2 will be used automatically when using regex features that are only supported by PCRE2.

I don't mind the warning but I just wanted to point out that the warning is actually not true because if the setting is not there my editor wont fallback to `PCRE2` and instead I will have this error message:
> backreferences are not supported

**Comment by gregvanl** [comment]
@frnk94 Thanks for reporting this. We'll try to get this sorted out.

**Comment by JoeyRxy** [comment]
I got this error, too. I find you can use backreference in single file searching, but not in global searching. Why? I remember there have been a setting to use pcre2, then WHY YOU CANCEL IT? I really confused why people will destroy the advantages of their product?

**Comment by jstlroot** [comment]
+1 for bringing back that feature, it was very handy.

**Comment by frnk94** [comment]
@JoeyRxy I think they tried to make a default fallback to PCRE2 but just didn't cover global searching look like a bug and not them removing features. Instead of commenting negatively on a  free Open source project why not contributing.

**Comment by mightyiam** [comment]
Please re-open?

**Comment by roblourens** [comment]
This is fixed in Insiders

**Comment by gregvanl** [comment]
You can download the Insiders builds from https://code.visualstudio.com/insiders to try it out.

**Comment by mightyiam** [comment]
Thank you so much. Keep up the excellent work.
