### ISSUE TITLE
CLI parameters not working on Windows

### ISSUE THREAD

**Issue by stefanfritsch** [Microsoft/vscode-docs#2328]
# The Problem

If I enter

```
code --version
```

or any other command line parameter on Windows the editor window pops up and the parameter has no effect

# What I expected to happen

According to [the docs](https://code.visualstudio.com/docs/editor/command-line) `code --version` prints the version string. Plus there are dozens of useful parameters.

# What I assume is the issue

Entering code in a shell references `Code.exe` in the vscode-folder and not `code` in `bin/`. This should be reflected in the docs for Windows.

# Version

VSCode 1.30.2
Windows 1809

**Comment by gregvanl** [comment]
Hi @stefanfritsch The --version command line switch is working for me.

![image](https://user-images.githubusercontent.com/12818376/51014567-6b4db380-151d-11e9-91c1-444da35888c0.png)

This doesn't seem like a VS Code documentation issue but if you have a consistent repro, you can enter an issue in the VS Code product repository https://github.com/Microsoft/vscode
