### ISSUE TITLE
404: expand.svg

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#234]
Mousing over the left navigation on https://code.visualstudio.com/Docs/?dv=win gives the following js error:

```
(anonymous function)
@ download.js:80fire
@ jquery.js:3182self.fireWith
@ jquery.js:3312jQuery.extend.ready
@ jquery.js:3531completed
@ jquery.js:3547
expand-down.svg:1 GET https://code.visualstudio.com/stylesheets/expand-down.svg 404 (Not Found)
```

**Comment by gregvanl** [comment]
Website issues like this should be entered in vscode-website issues. https://github.com/Microsoft/vscode-website/issues/
Moved to https://github.com/Microsoft/vscode-website/issues/142
