### ISSUE TITLE
do not display the text in terminal

### ISSUE THREAD

**Issue by sureshirajapakse** [Microsoft/vscode-docs#2341]
yesterday i installed VS Code latest version to do Python.I did some basics by creating a folder.But when I today tried to print "hi" it was not displayed in terminal.

C:\Users\name-PC\Documents\hello>app.py

though I gave my folder name app.py and pressed shift+enter nothing showed.plz can someone help?

**Comment by kraigb** [comment]
Thanks for the report, @sureshirajapakse. It looks like this is a known issue, which I reproduced: see https://github.com/Microsoft/vscode-python/issues/3397. The Shift+Enter keyboard mapping is shared between two different commands, and the one for Jupyter code cells seems to be getting picked up first.

So like the issue suggests, go to File > Keyboard Shortcuts, search for "Shift+Enter", then change the "Run Current Cell and Advance" keybinding to something like Shift+Alt+Enter. Then Shift+Enter worked for me as expected.
