### ISSUE TITLE
Document that "debugStdlib" is needed to debug 3rd-party code for Python

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#2342]
https://code.visualstudio.com/docs/python/debugging#_debugoptions doesn't mention that `"debugStdlib"` is what it takes to step into 3rd-party code.

/cc @Microsoft/pyvsc  as I'm going to be offline starting tomorrow.

**Comment by DonJayamanne** [comment]
Closing as this should not be documented, it's available for a backwards compatibility.
The work in the extension had not yet been finished
https://github.com/Microsoft/vscode-python/issues/2087

**Comment by kraigb** [comment]
Per @DonJayamanne 

Closing as this should not be documented, it's available for a backwards compatibility.
The work in the extension had not yet been finished

Microsoft/vscode-python#2087

**Comment by qubitron** [comment]
@DonJayamanne @kraigb we need to document how to do this, Don, please add a "justMyCode" setting that is equivalent to debugStdLib if you are hesitant to change the documentation

**Comment by DonJayamanne** [comment]
@kraigb 	Lets go with the updates to the documentation for now.
When #2087, we can update the docs accordingly.

**Comment by bj00rn** [comment]
#2087 is now merged. Maybe document this option?

**Comment by kraigb** [comment]
@JoshuaPartlow This is for you now.

**Comment by DonJayamanne** [comment]
@kraigb Please do not document `debugStdlib`, that's been deprecated in favor of `justMyCode` and that has been documented here https://code.visualstudio.com/docs/python/debugging#_justmycode.

I.e. nothing to do with regards to updating docs.

**Comment by kraigb** [comment]
Oh, of course. Thanks for the reminder. Closing again.
