### ISSUE TITLE
runOptions is not give in schema for task.json

### ISSUE THREAD

**Issue by vvavrychuk** [Microsoft/vscode-docs#2344]
Seems there is runOptions property https://code.visualstudio.com/docs/editor/tasks#_run-behavior. But somehow it has not managed to get into https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/tasks-appendix.md

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/pull/2353
