### ISSUE TITLE
Online documentation error in https://code.visualstudio.com/docs/python/environments#_choose-a-debugging-environment

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vscode-docs#2345]
@jcrmatos commented on [Sun Dec 23 2018](https://github.com/Microsoft/vscode-python/issues/3789)

The online documentation at
`https://code.visualstudio.com/docs/python/environments#_choose-a-debugging-environment`
states
`Note: The python:pythonPath setting doesn't affect debugging. See Choose a debugging environment.
`and then below it states
`The python.pythonPath setting specifies the Python interpreter to use for debugging.`

Those 2 cannot be correct.

**Comment by d3r3kk** [comment]
@kraigb could you have a look?

**Comment by kraigb** [comment]
@d3r3kk Right you are...the first statement is in error (it once was true, but that changed some time ago). I'll correct it.
