### ISSUE TITLE
Document Errors In Language Extensions Highlighting Guide

### ISSUE THREAD

**Issue by bpruitt-goddard** [Microsoft/vscode-docs#2359]
The section on [using YAML to write a grammar](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#using-yaml-to-write-a-grammar) goes against the YAML spec in 2 crucial ways.

1. A multiline string will either be separated with a newline or a space, depending on the [block scalar](https://yaml.org/spec/1.2/spec.html#id2795688). In the example screenshot, this is separated by a whitespace, which results in unexpected behavior when converting to json. For example, the first few lines of the regex become (note the space between the two lines, the newline is due to the indentation and can be ignored):

```yaml
match: >
    (?x)
        /s*
```

Converted:
```json
{ "match": "(?x)\n  /s*\n" }
```

The only way to ensure no whitespace between the lines is to use a string literal like below with a linebreak, but this will result in escaping many of the regex characters. Note this particular example won't need additional escaping.

```yaml
match: "
    (?x)\
        /s*"
```

Converted:
```json
{ "match": " (?x)/s*" }
```

2. Comments inside of a multi-line string are not supported in YAML. They cannot be escaped, meaning they will appear in the resulting string. From the example screenshot:

```yaml
match: >
    (?x)
        /s*     # Leading whitespace
```

Converted:
```json
{ "match": "(?x)\n  /s*   # Leading whitespace\n" }
```

I think this section needs to either be re-written to only highlight the general readability/conciseness of yaml, or indicate that something like the above can be achieved using `js-yaml`'s [custom types feature](https://github.com/nodeca/js-yaml/wiki/Custom-types). Note I was able to achieve the example screenshot using the [following custom type](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/blob/master/build/CustomYamlTypes.js#L9) and would be happy to share it somewhere if desired.

**Comment by mjbvz** [comment]
We are using extended regular expressions here (marked by the `(?x)`). This means that \#comments are supported and whitespace is generally ignored. You can also write these same extended regular expression in json but there isn't much point since it all has to be on the same line anyways

Please submit a docs PR if you feel this could be made more clear
