### ISSUE TITLE
[pylint] Unable to import 'flask' [E0401]

### ISSUE THREAD

**Issue by Cmumbi** [Microsoft/vscode-docs#2366]
Even after installing flask, I still get the above error.
Kindly assist.
![image](https://user-images.githubusercontent.com/25196422/51788645-8b25de00-2191-11e9-93a0-90c96bcce0e8.png)

**Comment by kraigb** [comment]
@Cmumbi How are you attempting to run your code? From the graphic here, I'm unsure whether you've installed Flask into the global Python 3.7 environment (indicated by the path), or a virtual environment (indicated by the "(env)" at the prompt). Either way, running the code successfully needs that same environment activated. If you're running the program within VS Code, then that same environment needs to be selected and activated in VS Code.

Let me know.

**Comment by Cmumbi** [comment]
I realized I wasn't installing it in the same environment and I've fixed
that.
Thank you.

*Kind regards,*
*Cynthia Muiga - **Web Developer*

**Comment by kraigb** [comment]
Yep, that would do it! One of the bits of Python that you get used to after a while. :)

**Comment by abasilim** [comment]
So how did you resolve please! I am having a similar issue here

**Comment by Cmumbi** [comment]
Are you installing Flask in a global environment or a virtual one? @abasilim
