### ISSUE TITLE
Anchor link broken on site but works when viewing .md on GitHub 

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode-docs#2370]
On [this page](https://code.visualstudio.com/api/references/contribution-points#contributes.views), the link for **Custom view containers** does not work but if you view the Markdown on GitHub [here](https://github.com/Microsoft/vscode-docs/blob/master/api/references/contribution-points.md#contributesviews), it works.

**Comment by gregvanl** [comment]
Note, the /API doc relative links will not work on GitHub, they only resolve on the actual website. See https://github.com/Microsoft/vscode-docs/issues/2236
