### ISSUE TITLE
Python Flask Tutorial

### ISSUE THREAD

**Issue by muckisg** [Microsoft/vscode-docs#2371]
Hi,

the follwoing code does not work, there is a 404 if no name is given via url.
Tutorial: https://code.visualstudio.com/docs/python/tutorial-flask#_use-a-template-to-render-a-page
Step 5

_templates/hello_there.html_
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Hello, Flask</title>
    </head>
    <body>
        {%if name %}
            <strong>Hello there, {{ name }}!</strong> It's {{ date.strftime("%A, %d %B, %Y at %X") }}.
        {% else %}
            What's your name? Provide it after /hello/ in the URL.
        {% endif %}
    </body>
</html>
```
Any hints?

Thx,

Maurice

**Comment by kraigb** [comment]
@muckisg Thanks for the report, and sorry for the belated response (I've been away for a few days). The correction is actually in the routing to the view in views.py. Change:

@app.route("/hello")

to

@app.route("/hello/")

and the app should work for /hello, /hello/, and /hello/<name>.

I'll correct this in the docs and the associated sample.
