### ISSUE TITLE
Installing matplotlib in VS code tutorial

### ISSUE THREAD

**Issue by SarcasticWatermelon** [Microsoft/vscode-docs#2372]
I was following a tutorial (https://code.visualstudio.com/docs/python/python-tutorial), and to complete it, I needed to install and run the process: 
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 20, 100)  # Create a list of evenly-spaced numbers over the range
plt.plot(x, np.sin(x))       # Plot the sine of each x point
plt.show()                   # Display the plot
The tutorial then told me to install the package matplotlib, by running the code: sudo python3 -m pip install matplotlib in the terminal. This does not work and all I am left with a blank screen in the terminal (the picture below) where I can type anything. I have looked at other problems filed with this, but can't find anything relating to my issue.
![screen shot 2019-01-30 at 8 03 04 am](https://user-images.githubusercontent.com/22984723/51990402-3078d480-2466-11e9-8f2e-3d8551797801.png)

**Comment by muckisg** [comment]
Hi @SarcasticWatermelon,

do you get the same result by just going to the console an use:
'''
pip install matpltlib
'''
Be sure you have the right version of pip installed (if you have different python versions (2 & 3) installed.

Hope it helps,

Maurice

**Comment by SarcasticWatermelon** [comment]
> Hi @SarcasticWatermelon,
> 
> do you get the same result by just going to the console an use:
> `pip install matplotlib`
> Be sure you have the right version of pip installed (if you have different python versions (2 & 3) installed.
> 
> Hope it helps,
> 
> Maurice

I think it is an error on my part. I am working on this on a school computer, so therefore it will not allow me to install things. I will try this on my home computer to see if this works and get back to you with any further issues in the future. Thanks for your help, though!

**Comment by kraigb** [comment]
Yes, if you don't have admin privs on a computer, then sudo elevation won't work. In that case you need to use a virtual environment instead, in which you can install anything. I'll make a note about that in the documentation.

**Comment by ngock** [comment]
I had the same issua. For python3 , try
pip3 install matplotlib
the same for other package such as imutils
pip3 install imutils

**Comment by CarmenRuppach** [comment]
I had a similar issue. I has to upgrade the pip version in a first step ("pip install --upgrade pip") and then use "pip3 install matplotlib"
