### ISSUE TITLE
Visual Studio Code using remote JupyterHub notebook

### ISSUE THREAD

**Issue by lgonzalezsa** [Microsoft/vscode-docs#2376]
Looking at this article: [Visual Studio Working with remote Jupyter Notebook,](https://code.visualstudio.com/docs/python/jupyter-support#_connect-to-a-remote-jupyter-server) wondering and trying with JupyterHub API but was not able to make a connection from Visual Studio Code.

It is possible to open a remote session in a JupyterHub server? seems to me a nice feature to have.

[Related question](https://stackoverflow.com/questions/54428958/visual-studio-code-new-feature-connect-to-jupyter-notebook-it-is-possible-to-co)

**Comment by kraigb** [comment]
@lgonzalezsa Thanks for the issue. I think it's best answered through the issues on the repo for the Python extension directly: https://github.com/Microsoft/vscode-python/issues/. Your particular question might already be covered by https://github.com/Microsoft/vscode-python/issues/3954, but again, best to clarify with the engineering team there. Do reference this docs issue, though, and report back if there are doc changes that are necessary.

Closing in the meantime. Thanks.
