### ISSUE TITLE
Failure to run debug in setting up Python at VS vode

### ISSUE THREAD

**Issue by davidecon123** [Microsoft/vscode-docs#2386]
a new set up following the instructions under : https://code.visualstudio.com/docs/python/python-tutorial
when I reach the step for testing the debug, my case failed to show up a " yellow arrow" when the debug ran. May I know which part I shall correct my setting?

**Comment by kraigb** [comment]
Hi @davidecon123. The yellow arrow shows the next line to be executed. It appears either on a breakpoint (in which case the red dot is above it), on the first line if you have "stopOnEntry": true in the debug configuration, or on any other line as you use the stepping tools.

Can you be more specific about the steps you've taken, and what you're expecting to see? I'm assuming you got to the point of starting the debugger with F5 or by using the green arrow in the debug explorer. But tell me, what debug configuration do you have selected (that is, what shows in the drop-down)? Did you set a breakpoint? Did the program run all the way through? What appears in the Terminal output?

Thanks

**Comment by davidecon123** [comment]
![debug](https://user-images.githubusercontent.com/47423678/52481803-82e68d80-2bea-11e9-9fd4-20ea8ce59e36.jpg)

![launch json](https://user-images.githubusercontent.com/47423678/52481903-c6d99280-2bea-11e9-998c-2c6e65635d5d.jpg)

Sorry, I am new to programming, so I wasn;t specify enough in my query.

I am on the step of running the debug by pressing F5. But, it doesnt show the "Local variables" and there is no yellow arrow shown on the left margin. It seems that the debugging is not working. Not sure which part of the configuration goes wrong.

**Comment by kraigb** [comment]
Yes, it looks like the debugger is hung up or not responding, given that nothing appears in the debug explorer, and neither does the program run and give output.

Let's try a few other variations to run the program in different ways. Let me know which of these work or don't:

1. Right-click in the editor and select "Run Python File in Terminal". This should display "Hello World" in the output window.
2. Select the Debug > Start Without Debugging menu command, which should also display the message in the output window.
3. Switch to the debug configuration "Python: Current File (External Terminal)", then select Debug > Start Without Debugging again. This should run the program in a separate command window.
4. Using the same configuration, try F5 again (starting the debugger).

**Comment by kraigb** [comment]
You can also try closing VS Code, then deleting the .vscode folder from your project directory, restarting VS Code, opening that directory, then recreating the debug configurations file (launch.json).

**Comment by davidecon123** [comment]
Thanks! Kraigb! After deleting the .vscode folder in the project directory. 

I try again by not adding a "stopOnEntry": true setting to the "Python: Current File" configuration in launch.json. And, the debugging process is fine. And, the debugger stops at the breakpoint (the line with red dot on the left). 

kinda interesting.....

**Comment by kraigb** [comment]
Great! So deleting the .VSCode folder worked, correct? I did suspect that there was some errant setting that was causing problems. Were you able to get stopOnEntry to work correctly?

By the way, do you still have the launch.json and settings.json files in your recycle bin? If so,

**Comment by geekgamer2001** [comment]
I did the same thing and it did not work it got rid of launch.json and after I remade as according to in the tutorial and set "stopOnEntry": true i got the same issue but when I set it to false the whole debugger runs but doesn't run one bit when it is on...... odd

**Comment by kraigb** [comment]
After VS Code just updated to 1.31.1, I found the same behavior: with "stopOnEntry" : true the debugger hangs. Definitely a bug in the extension, then, and it seems like https://github.com/Microsoft/vscode-python/issues/4223 covers it. I'm closing this doc issue, then.
