### ISSUE TITLE
Update Python extension docs to explain how .env files support variable substitution

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/vscode-docs#2389]
With https://github.com/Microsoft/vscode-python/pull/4267 the Python extension now supports variable substitution in `.env' files.  The [docs for "Environment variable definitions file"](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file) should indicate this.

Relevant details:
* substitution uses a similar syntax to what is used by shells (`<VARNAME>=...${<VARNAME>}...`)
* the curly braces are required (in shells they are often optional)
* lines with unsupported syntax are left as-is
* only simple substitution is supported, so no nesting (e.g. `${_${OTHERVAR}_EX}`)
* the `$` character can be escaped with a backslash (e.g. `\${MYVAR}`)
* substitution happens regardless of quoting of the value (e.g. `MYVAR='${OTHERVAR}'`)
* the ordering in the `.env` file is respected
* substitution will use the variables set on previous lines and the process-global environment variables, with precedence given to the `.env` file
* recursive substitution is supported (e.g. `PYTHONPATH=$PROJ_DIR:${PYTHONPATH}`)

**Comment by kraigb** [comment]
@ericsnowcurrently Just to clarify, the substitution referred to here is using already-defined environment variables (within the system or earlier in the .env file) to define other variables in the .env file, correct?

**Comment by kraigb** [comment]
@ericsnowcurrently Actually, the second to last bullet says that already, so ignore my previous comment.

**Comment by akvadrako** [comment]
I find this doc rather confusing because it uses `$PROJ_DIR` as an example environmental variable but that doesn't seem to exist and there is no way to get the path of the current project.

Are there any present variables, like the path of the current workspace?
