### ISSUE TITLE
Please review https://github.com/Microsoft/vscode-docs/blob/dbaeumer/lsif/blogs/2019/02/lsif.md

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-docs#2391]
Hi Greg,

can you please review the above blog post. You can directly edit the md and push. I am out on vacation next week.

Thanks Dirk

**Comment by gregvanl** [comment]
Hi @dbaeumer I made an edit pass with https://github.com/Microsoft/vscode-docs/commit/83286bb77b46dd50969025b06d7440a0f726f961.
Let me know what day you'd like it published and I can update the final path and date.

**Comment by dbaeumer** [comment]
@gregvanl thanks. Will let you know when ready for publish
