### ISSUE TITLE
Cross file IntelliSense not working

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#241]
_From @gregvanl on March 21, 2016 5:5_

- VSCode Version: 0.10.11 stable, 0.10.12 alpha
- OS Version:Windows 8

Steps to Reproduce:

1. Go through the Node.js runtime walkthrough (/docs/runtimes/nodejs.md) to "adding a jsconfig.json file" step.
2. After adding jsconfig.json and restarting VS Code, try to get IntelliSense on `routes`. 

No Express.Router specific IntelliSense comes up.  This should be provided by:
    var routes = require('./routes/index');

This was initially reported by a customer through DocFeedback verbatim.

_Copied from original issue: Microsoft/vscode#4487_

**Comment by egamma** [comment]
This works when using `tsd install node express`. It doesn't work when using `typings --ambient`.

We should mention this in the docs and describe the work around.

![image](https://cloud.githubusercontent.com/assets/172399/13912155/5f724622-ef3a-11e5-9572-dc968c0b6518.png)

**Comment by jrieken** [comment]
@gregvanl As outlined in #4487 more dependencies must be installed, with `typings install --ambient node express serve-static express-serve-static-core`
