### ISSUE TITLE
Azure DevOps Pipelines documentation is broken for static websites

### ISSUE THREAD

**Issue by mikedouglasdev** [Microsoft/vscode-docs#2414]
When navigating from the Azure documentation for static websites
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website#next-steps
The following link is broken.
https://code.visualstudio.com/tutorials/static-website/deploy-VSTS

Thanks,
Mike

**Comment by gregvanl** [comment]
Hi @mikedouglasdev I moved this issue to https://github.com/MicrosoftDocs/azure-docs/issues/25069.
I don't think the Azure Pipelines link should be going to the VS Code website.
