### ISSUE TITLE
Add a page with the available localized languages

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#243]
pls see: https://github.com/Microsoft/vscode/issues/4170#issuecomment-199682102

This page is linked from locale.json file and it should enumerate the 9 available languages.
The link defined in the fwlink points to `https://code.visualstudio.com/docs/customization/locales`

**Comment by egamma** [comment]
// @dbaeumer

**Comment by gregvanl** [comment]
Added with https://github.com/Microsoft/vscode-docs/commit/edc637f4ffa49d07d80197401ff96534d090542c

**Comment by gregvanl** [comment]
locale.json fwlink will 404 until we merge vnext to master and publish the websites for March release.
