### ISSUE TITLE
SOURCE CONTROL - quick start in documentation missed

### ISSUE THREAD

**Issue by Georg-M** [Microsoft/vscode-docs#2432]
I have fresh VSCode (1.31.1) installed on Windows 10 (1803).
And I have Git client (2.17.0 in CygWin) available from everywhere over Windows PATH env variable.

*Problem 1*
VSCode has nothing VCM/Git related, except `"Initialize Repository"` option.
SOURCE CONTROL pane shows: `"No source control providers registered"`.
Option `"Initialize Repository"` works, but nothing changes in VSCode UI.

*Problem 2*
[VSCode documentation](https://code.visualstudio.com/docs/editor/versioncontrol) hasn't **"Quick Start"** for using Git VCM.
I can apply nothing from this document

Maybe this duplicates #2323

**Comment by Georg-M** [comment]
Maybe this duplicates #2323

**Comment by gregvanl** [comment]
Hi @Georg-M I wasn't able to reproduce your issue where there is no UI change after running "Initialize Repository". You might check that you have a hidden .git folder under your project folder after the init finishes.
#2323 is meant to provide a step-by-step tutorial for users new to both Git and VS Code at the same time.
