### ISSUE TITLE
Does window.showMessage support newlines?

### ISSUE THREAD

**Issue by tetchel** [Microsoft/vscode-docs#2436]
Sorry for the question (not an issue) but I couldn't find any info on this. 

Does `vscode.window.show(Information|Warning|Error)Message` support newlines? 

I tried `\n`, `\n\n`, and `\\n`. The first 2 got rendered as spaces, and the latter was printed as literally "\n" as I expected.

I won't be surprised if this isn't supported, since the messages shown here are generally concise, but I wanted to make sure.

**Comment by gregvanl** [comment]
Hi @tetchel show{}Message does not support newlines. See https://github.com/Microsoft/vscode/issues/48900
