### ISSUE TITLE
Add note how to associate files with json

### ISSUE THREAD

**Issue by SimonSiefke** [Microsoft/vscode-docs#2439]
I was looking at https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation but it wasn't clear how I could associate for example ".jshintrc" files with JSON. 
I eventually found it on the prettier-vscode repository, but maybe we could add a note to the docs. Something like:

To associate the ".jshintrc" file with JSON syntax, add the following to the "contributes" configuration:
```json
"languages": [
  {
    "id": "json",
    "filenames": [".jshintrc"]
  }
]
```

Another option would be to add a reference to "contributes.languages", something like:

To associate the ".jshintrc" file with JSON syntax, see "contributes.languages"

**Comment by KamasamaK** [comment]
I think the proper way to do this is using the `files.associations` setting. See [Adding a file extension to a language](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language). The approach you are using should be reserved to contributing a new language.

**Comment by gregvanl** [comment]
Thanks for answering @KamasamaK.

**Comment by SimonSiefke** [comment]
Sorry if I wasn't clear, what I meant was: When I want to create an Extension that provides a schema for `.jshintrc` files, the docs should also include how to associate ".jshintrc" files with JSON from a extension point of view. The users of the extension can do that manually with the `files.associations` setting, but it would be better if the extension would automatically do that via `contributes.languages`

**Comment by KamasamaK** [comment]
Perhaps, but again, that did not seem to be the way you should use `contributes.languages` based on my understanding. It would be nice to have clarified exactly how this _should_ be done. If that's a supported use, then it would of course be nicer to have the association be statically defined.

By the way, the suggestion was not to have users manually configure settings. There is an [API](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration) for this.
