### ISSUE TITLE
doc(review)athon

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#244]
### Goals
- check the doc for accuracy
- add missing tips
- add new contents if appropriate

### Guidelines from @gregvanl 

- Update the docs in vscode-docs vnext branch.  
  - You can commit directly and don’t need to create pull requests.  
  - You can be pretty fast and loose and I’ll follow up with an extensive edit and formatting pass afterwards.

- Write the content targeting the March release. 
  - For walkthrough flow, use the new features available in 0.10.12 (e.g. jsconfig.json creation, tasks.json dropdown, jsconfig.json autoload,etc).
  - Focus on likely user scenarios and workflows.  Corner cases or less used features can be called out in the Common Questions section at the end.
  - If you find that you are adding a lot of Tips and Tricks which interrupts a topic’s flow, consider adding a Tips and Tricks section at the bottom of the topic.

- Try to use separate commits for separate changes and docs.
  - This will make it easier to cherry pick commits that we want to move to master before we merge vnext at the 1.0 release.

#### Editor

- Overview 
  - [x] @egamma
- Setup 
  - [x] @Tyriar 
  - [x] @joaomoreno
- Basics
  - [x] @bpasero 
- Extension Gallery
  - [x] @joaomoreno
- Editing Evolved
  - [x] @alexandrudima 
  - [x] @aeschli - add section on Folding
- Version Control
  - [x] @joaomoreno
- Debugging
  - [x] @weinand 
  - [x] @isidorn 
- Tasks
  - [x] @dbaeumer 
- Accessibility
  - [x] @alexandrudima 
- Why VS Code
  - [x] @egamma

#### Customization

- Overview
  - [x] @egamma
- Workspace Settings
  - [x] @aeschli 
  - [x] @bpasero 
- Keybindings
  - [x] @alexandrudima 
- Snippets
  - [x] @aeschli 
- Colorizer
  - [x] @aeschli 
- Themes
  - [x] @aeschli 

#### Languages

- Overview
  - [x] @egamma
- JavaScript
  - [x] @egamma
  - [x] @dbaeumer 
  - [x] @jrieken 
- JavaScript example on github https://github.com/jrieken/es6-vscode-sample
  - [x] @jrieken - removed the reference to the sample
- C#
  - [x] @jrieken  
- JSON
  - [x] @aeschli 
- HTML
  - [x] @aeschli 
- PHP
  - [x] @alexandrudima 
  - [x] @aeschli 
- Markdown
  - [x] @bpasero 
  - [x] @dbaeumer (generation of HTML using tasks) 
- TypeScript
  - [x] @dbaeumer 
  - [x] @jrieken 
- CSS, LESS, SAA
  - [x] @aeschli 
- Dockerfile
  - [x] @alexandrudima 

#### Runtimes

- Node.js
  - [x] @weinand 
- ASP.net Core
  - [x] @jrieken 
- Unity
  -  @seanmcbreen 
- Office
  -  @seanmcbreen 

#### Extensions

- Overview
  - [x] @egamma
- Hello World
  - [x] @jrieken 
- Word Count
  - [x] @alexandrudima 
- Language server
  - [x] @dbaeumer 
- Example debuggers
  - [x] @weinand 
- Principles Patterns
  - [x] @jrieken 
- Running and Debugging
  - [x] @bpasero 
  - [x] @weinand 
- Installing Extensions
  - [x] @joaomoreno
- Testing Extensions
  - [x] @bpasero 
  - [x] @weinand 
- Our Approach
  - [x] @egamma

#### Extensbility Reference

- Overview
  - [x] @egamma
- Extension Manifest
  - [x] @joaomoreno
- Contribution Points
  - [x] @alexandrudima 
  - [x] @weinand 
- Activation Events
  - [x] @alexandrudima 
  - [x] @jrieken 
- API vscode name space
  - [x] @gregvanl - updated vscode.d.ts commit id
- API complex commands
  - [x] @jrieken 
- API debugging
  - [x] @weinand 

#### Tools

- Publishing tool
  - [x] @joaomoreno
- Extension generator
  - [x] @aeschli 
- Samples
  - [x] @egamma

**Comment by gregvanl** [comment]
Boxes all checked.
