### ISSUE TITLE
Decode

### ISSUE THREAD

**Issue by drayus34** [Microsoft/vscode-docs#2445]
Vscode is not supported by Android I have tried get extensions but can't use it someone please fix this I only have my phone soon I will have a chromebook or a Microsoft laptop the only reason I'm trying programming is to make an program to take individual pages of comics and merge into an e-book or to be self published but won't get anywhere without this change

**Comment by gregvanl** [comment]
Hi @drayus34, VS Code currently only supports the Windows, macOS, and Linux platforms. Hopefully, you will find VS Code useful for your project if you are able to use a supported platform.
