### ISSUE TITLE
add FAQ for legal doc locations on disk

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#245]
can we add a FAQ that says where to find the legal documents on disk?  license, thirdpartynotices.txt, and the credits***.html file for chromium.

this would be different for each platform probably, i know mac/windows definitely, not sure where they are on linux.

**Comment by gregvanl** [comment]
Looks like we should call out on Windows:
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\LICENSE.txt
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\ThirdPartyNotices.txt
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\Credits_45.0.2454.85.html

**Comment by chrisdias** [comment]
license will be in a licenses folder, so it will look something like this:

ThirdPartyNotices.txt
Credits...html
licenses\license.txt
licenses\license-cht.txt
licenses\license-chs.txt
licenses\license-fra.txt
licenses\license-ita.txt
licenses\license-deu.txt
etc.

This should be in vnext, not in master.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/bf9948e2c36f7ea098d8f71d00210f1a43ee8169

**Comment by gregvanl** [comment]
This will need to be verified once Chris's pull request is merged and we have a new build with the new localized licenses under resources\app\licenses.
