### ISSUE TITLE
update asp.net doc to point to official asp.net docs on VS code

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#246]
the asp.net v5/1.0 docs are more complete than our docs, and are being maintained by the right team. Let's remove our document and replace it with a short blurb on ASP.NET and point to their docs:

- Setup: `https://docs.asp.net/en/latest/getting-started/index.html`
- Walkthrough: `https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-app-using-vscode/`

**Comment by egamma** [comment]
:+1:
