### ISSUE TITLE
Hosting like VSCode Docs

### ISSUE THREAD

**Issue by dscharnagl** [Microsoft/vscode-docs#2465]
Hey there!

Which CMS are you using to host VSCode Docs and VSCode in general?
I'm aware of Jekyll and Hugo to host markdown like pages or you're using your own CMS?

Thanks in advance!

**Comment by gregvanl** [comment]
Hi @dscharnagl, we host our own website on Azure. The markdown files are converted to HTML via markdown-it and we are using Express as the server.
