### ISSUE TITLE
tasks.json documentation innacurate?

### ISSUE THREAD

**Issue by David-Woodward** [Microsoft/vscode-docs#247]
[https://code.visualstudio.com/docs/editor/tasks](url) [vscode-docs/docs/editor/tasks.md] states:

> You can also reference environment variables through ${env.Name} (e.g. ${env.PATH}).

But, I this doesn't seem to work for me.

The following tasks.json creates output that actually says "${env.PATH}" rather than substituting the PATH environmental variable.

```
{
	"version": "0.1.0",
	"command": "cmd",
	"isShellCommand": true,
    "tasks": [
        {
            "taskName": "Run shell command",
            "args": [ "/C", "ECHO", "${env.PATH}" ]
        }
    ]
}
```

I also tried using "${env.COMSPEC}" in place of "cmd" for the task command and VSCode throws an error saying:

> '${env.COMSPEC}' is not recognized as an internal or external command, operable program or batch file.

(First timer here - sorry if this is posted in the wrong place/format)

**Comment by gregvanl** [comment]
Hi David,

Thanks for entering this issue.  I've contact the VS Code dev team and am waiting to hear back if this is a bug or documentation issue.

**Comment by dbaeumer** [comment]
Actually under Windows the path variable is written Path. So $env.Path does the right thing. @gregvanl can you please open a bug in vscode so that we check the case sensitiveness of env variables on all platforms to decide what the correct behavior would be.

**Comment by gregvanl** [comment]
@dbaeumer is correct.  env.Path and env.ComSpec work correctly on Windows.
