### ISSUE TITLE
Plugins often fail

### ISSUE THREAD

**Issue by yiluxiangbei87110** [Microsoft/vscode-docs#2476]
### Plugins often fail，it works when i uninstalll plugins and retry install。
![image](https://user-images.githubusercontent.com/23131032/54260130-0527f000-45a3-11e9-8fd4-fc6e9f896a21.png)

**Comment by gregvanl** [comment]
Hi @yiluxiangbei87110 This looks like an issue with the VS Code product, not the VS Code documentation. You can open an issue in the VS Code product repo at https://github.com/Microsoft/vscode
