### ISSUE TITLE
Outdated Keyboard Shortcuts Reference PDFs

### ISSUE THREAD

**Issue by kbehlers** [Microsoft/vscode-docs#2477]
February 2019 Release (see https://code.visualstudio.com/updates/v1_32) changed the "Select current line" command on Linux, Windows, and macOS (see https://github.com/Microsoft/vscode/pull/67178) to be an `L` instead of `I`.

The cheat sheets (see https://github.com/Microsoft/vscode-docs/issues/645) need to be updated with the new keybinding.

**Comment by kbehlers** [comment]
Additional Reference Link https://github.com/Microsoft/vscode/issues/59003

**Comment by gregvanl** [comment]
Updated with https://github.com/Microsoft/vscode-docs/commit/e3ba3e367fdbbe4159ff8f37870dc2634b875166.
Will publish new PDFs shortly.
