### ISSUE TITLE
Document python/poetryPath

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode-docs#2478]
**Extension: Python Extension**
The setting will be available in `settings.json` as follows:
```js
"python.poetryPath":"<path>"
```
* Currently it defaults to `poetry` (assuming it is in the current path)
* Use by the extension to install packages when `poetry` is available
* We determine whether to use `poetry` or not based on the existence of `poetry` and the existence of the `poetry.lock` file in the workspace folder.

**Comment by kraigb** [comment]
@DonJayamanne Has this already shipped, or is it upcoming? (I ask because of the "The setting will be..." language.)

**Comment by DonJayamanne** [comment]
Not yet shipped

**Comment by DonJayamanne** [comment]
Will be shipped today.
