### ISSUE TITLE
"Search Docs" displaying no results for any term

### ISSUE THREAD

**Issue by luabud** [Microsoft/vscode-docs#2481]
I tried searching with many different terms and for all of them the Search returns "No results". 

![image](https://user-images.githubusercontent.com/45497113/54373490-94ccad80-463a-11e9-8637-96df4f9de6a7.png)

**Comment by gregvanl** [comment]
@luabud Thanks for reporting this. We are investigating.

**Comment by gregvanl** [comment]
Should be fixed now.
