### ISSUE TITLE
Flask tutorial's launch.json does not match the default settings

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docs#2482]
The current settings are https://github.com/Microsoft/vscode-python/blob/81a079cb6b87837af3f2d66a5a256b1bb63af501/package.json#L840-L860

**Comment by kraigb** [comment]
Is this accurate for the current release of the extension? Trying it just now, I see the following:

        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        },

I don't see the two other environment variables, however. Perhaps those have been added in March?

**Comment by brettcannon** [comment]
@kraigb according to https://github.com/Microsoft/vscode-python/blame/master/package.json they have been in there for several months, but I just filed an [issue](https://github.com/Microsoft/vscode-python/issues/4774) about how the group of default configurations is like what you have but if you explicitly select Flask you get what I linked to.

**Comment by kraigb** [comment]
Yes, I see that now. I'll make mention of that difference.

**Comment by kraigb** [comment]
I've added notes on the distinct Flask config; if the configs in the extension get consolidated, we can remove those notes.
