### ISSUE TITLE
Update Readme. How to install

### ISSUE THREAD

**Issue by CBtiger** [Microsoft/vscode-docs#2485]
VS Code runs fine of my offline PC. But no help feature work without internet. Even the Help/keycodes are only a link to an online page. 

By chance I saw this docu repository. I read your Readme. You are telling about how to limit download size which is nice. But why is there no information at all on how to install that package? I mean install it so that it works with my local VC Code installation. If that is not possible, it might be worth adding that fact to the readme, because then the purpose of the repository could be unclear to some people (including me). 

Thanks.

PS: I know its a small group of people who to have to do develop on offline computers, but they exist. As you provide a great documentation (thanks for that excellent job), mabye its an idea to add an "Offline" section where all important information for that use case could be collected. Even for normal devs, they sometimes are not online (on site or on travel) and would setup an offline features as fallback. Diskspace is rarely a limit.
The section could tell about stuff already there (like *.vsix downloads) and what is not there yet [maybe integrated offline docs?] and some ideas. For example for Linux users one can clone the latest files from 'packages.microsoft.com/repos/vscode' and move them to an intranet repository. Although the full repo is large (30GB), only the last versions are a few hundred megs only.

**Comment by gregvanl** [comment]
Hi @CBtiger For offline reading, you can clone the vscode-docs repository to your local machine. VS Code has a nice Markdown preview and the repository directory structure closely matches the website TOC so you can use the File Explorer to navigate through documentation. The vscode-docs repo is fairly large so you can do a git clone --depth 1 to just get the latest content.

**Comment by CBtiger** [comment]
Thank you for you information. Important information I could not have guessed.

Since you closed the item without referring to an update of the main ReadMe.md can I read from that you do not think this kind of information is useful for others?

I would think many people (including me) would love to read your answer (perfectly with a step-by-step) in the front part of that document.
