### ISSUE TITLE
In "Getting Started with Python in VS Code"，when I select green arrow again, VSCode will report an error.

### ISSUE THREAD

**Issue by tianjidiaobao** [Microsoft/vscode-docs#2488]
I follow the documentation（https://code.visualstudio.com/docs/python/python-tutorial#_configure-and-run-the-debugger）

![image](https://user-images.githubusercontent.com/26198425/54473400-2c382900-4812-11e9-8d82-3a88129985c3.png)

VSCode will report a error, like this:

![image](https://user-images.githubusercontent.com/26198425/54473358-d6fc1780-4811-11e9-8044-81db36a757e7.png)

Is it wrong in the documentation? It should be “Select the blue arrow to run the program to completion. ”

![image](https://user-images.githubusercontent.com/26198425/54473338-60f7b080-4811-11e9-9b0d-acb2d853fcfd.png)

**Comment by kraigb** [comment]
@tianjidiaobao Right you are! Thanks for catching that overlooked detail.
