### ISSUE TITLE
Visual Studio Code not using the selected Python environment

### ISSUE THREAD

**Issue by Dazzerman** [Microsoft/vscode-docs#2490]
Hi,

Apologies for the newbie question, but I don't understand why VSC is not consistently using the Python Interpreter that I have selected.

I have uploaded a pair of screenshots to show the different ways that I have run the very basic python code to display the python version being run.  The top screenshot shows the Output panel when running the code via "ctrl-alt-n", and you can see that the output displays 2.7.13 while the selected python interpreter displays 3.7.2 in a virtual environment I have set up.

The bottom screenshot shows the Terminal panel results when I ran the code via Terminal > Run Active File, displaying 2.7.13, and then shows 3.7.2 when I executed the "python venv\test.py" command.  Note that when I select Python 3 without it being part of a virtual environment, then  the "python venv\test.py" command also displays 2.7.13.

I expect that part of the answer relates to Python 2 being in the Path earlier than Python 3, but if the functionality to select a python environment is there within VSC, there must be a way for the correct environment to be selected and used via the different built-in functionality in VSC.  Plus, without using virtual environments, how else will either python version be selectable if its location is not specified within the Path?

Thank you in advance.

![VSC_WrongPython](https://user-images.githubusercontent.com/48651100/54493229-50087700-48c5-11e9-9e39-c66a365b962f.jpg)

**Comment by Dazzerman** [comment]
P.S. I am using Windows 8 on my current machine, and VSC version : 
Version: 1.32.1 (user setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.3.9600

**Comment by kraigb** [comment]
@Dazzerman You want to run the code using the Python: Run Current File in Terminal command rather than Terminal > Run Active File. The latter relies on the file type association of Windows for .py files, which in your case must be associated with Python 2. (When I tried it, in fact, I didn't have an association, so Windows popped up the dialog asking me to set one.) 

The Python: Run Current File in Terminal command, on the other hand, always uses the interpreter you've selected in VS Code. If you find that's not the case, then file an issue on https://github.com/Microsoft/vscode-python (where the Python extension itself lives).

Let me know if this works for you.

**Comment by Dazzerman** [comment]
@kraigb Thank you for your advice.  I have tried using Python: Run Current File in Terminal command, and this works.  This is definitely an improvement on having to type "python venv\test.py", so that is great.

Is it also possible to get code-runner to use the selected interpreter?  The Ctrl-Alt-n shortcut is easier and quicker to use than Right-Click > Run Python File In Terminal, so to have both options would be fantastic.

Thanks again.

**Comment by kraigb** [comment]
To get the other command to run using the selected interpreter probably requires an engineering change. I suggest taking that one up with the vscode-python issues on GitHub as noted before.

However, it's probably easier (and better) to just assign a new keyboard shortcut to the Python-specific command. You could reassign Ctrl+Alt+n, in fact; I don't believe it's actually a default keystroke...at least in my install it wasn't assigned to anything, and I know I haven't used it before.

In the meantime, I'm closing this issue as I believe it's resolved. Thanks.

**Comment by Dazzerman** [comment]
Thank you again.
