### ISSUE TITLE
Broken anchors for parametrized types in the API docs

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode-docs#2491]
Next to types in the API docs, there's a `#` that changes the URL to an anchor that directly scrolls to that type. For parametrized types, this changes the address bar to the following:

![](https://i.imgur.com/Aph7K1A.png)

When I copy that link, I end up with this in my clipboard, since the `<` / `>` is being escaped:

https://code.visualstudio.com/api/references/vscode-api#TreeDataProvider%3CT%3E

That link doesn't actually work and just takes me to the top of the API docs. However, if I simply omit the `<T>` from the URL, the anchor works as intended:

https://code.visualstudio.com/api/references/vscode-api#TreeDataProvider

(note: using Chrome)

**Comment by gregvanl** [comment]
Closing as there is a workaround by removing the parameterized type suffix.
