### ISSUE TITLE
API docs have anchors for fields, but they're hidden

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode-docs#2492]
As I mentioned in #2491, the API docs have convenient `#` links next to types and namespaces to obtain the anchor for them.

![](https://i.imgur.com/qO8vNyv.png)

Individual fields actually also have anchors, but I suspect almost nobody knows about this since there isn't any way to obtain the link as far as I can tell. There's no `#`, and clicking the name just expands/collapses the docs.

(the anchor for fields is simply `TypeName.fieldName`, for instance https://code.visualstudio.com/api/references/vscode-api#CodeActionKind.Empty)

**Comment by gregvanl** [comment]
Closing old issue, no upvotes
