### ISSUE TITLE
readonly attribute doesn't show up in the API docs

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode-docs#2493]
Many fields in the VSCode API are declared `readonly`, for instance:

```ts
export interface CodeActionContext {
	/**
	 * An array of diagnostics.
	 */
	readonly diagnostics: Diagnostic[];
	/**
	 * Requested kind of actions to return.
	 *
	 * Actions not of this kind are filtered out before being shown by the lightbulb.
	 */
	readonly only?: CodeActionKind;
}
```

However, this isn't reflected in the API docs, so there's no way to tell the difference between regular and `readonly` fields.

https://code.visualstudio.com/api/references/vscode-api#CodeActionContext

The API docs for the Haxe externs of the VSCode API have a "read only" badge to indicate this, something similar might work for the official docs:

![](https://i.imgur.com/lPHQyAQ.png)

(http://vshaxe.github.io/vscode-extern/vscode/CodeActionContext.html)

**Comment by gregvanl** [comment]
Closing old issue. No current;y planned investment in generated API reference
