### ISSUE TITLE
how to clone correctly

### ISSUE THREAD

**Issue by CBtiger** [Microsoft/vscode-docs#2494]
The Readme said
> Cloning
> We have adopted Git LFS to store the images in this repo. Bare git clone will take 1.4GB+, and we recommend the following setup:
> ...

but when I type
> git clone https://github.com/Microsoft/vscode-docs.git

which I think was meant with "bare clone" I will get this output

>Cloning into 'vscode-docs'...
>remote: Enumerating objects: 547, done.
>remote: Counting objects: 100% (547/547), done.
>remote: Compressing objects: 100% (507/507), done.
>remote: Total 2612 (delta 88), reused 131 (delta 37), pack-reused 2065
>Receiving objects: 100% (2612/2612), 1.97 MiB | 1.23 MiB/s, done.
>Resolving deltas: 100% (93/93), done.
>Checking connectivity... done.

Looks ok to me, at least I can see no error mesasge. But the downloaded folder size is 36MB, not 1.4GB. What did I do wrong?

**Comment by octref** [comment]
You probably already has Git LFS installed. What happens if you try to open an image in the repo?

**Comment by CBtiger** [comment]
I have not LFS installed. For that reason I was expecting to download 1.4GB of data. I hoped I could manage with standard git.

When I open an image in the repo (=in my browser) the image opens in the same document (no separate window, no download). Thats what I would expect to happen.

**Comment by octref** [comment]
So your local clone is 36MB, and you cannot open images in local repos, is that correct?

For example, here's what happens if I try to open `docs/editor/images/accessibility/high-contrast.png`:

![image](https://user-images.githubusercontent.com/4033249/54549409-3c155180-4967-11e9-8b52-fe96486f1855.png)

Can you also run `git config --list --global` and show me `lfs` related settings, if there's any?

**Comment by CBtiger** [comment]
Sorry, I misunderstood you. I tried to open a image in the repository on your server via my bowser. 

In my downloaded 36MB repository I can not open the image, because its not an image the file 
> vscode-docs/images/MDPreviewButton.png

actually contains

>version https://git-lfs.github.com/spec/v1
oid sha256:5e7898162b491988d4ffe858005b8f95dbdf1c5720d2973df45945989cea3bd7
size 44885 

I ran your command in the repository but also in the home folder and it did not file a /home/username/.gitconfig. I just installed git with all defaults and did not modify any settings.

**Comment by octref** [comment]
That's very peculiar. You cloned the repo without `GIT_LFS_SKIP_SMUDGE=1`, and if you type `env`, you cannot find any `GIT_LFS_SKIP_SMUDGE`, can you?

Also, which OS are you on?

Finally, if you run `GIT_LFS_SKIP_SMUDGE=0 git clone git@github.com:Microsoft/vscode-docs.git`, what happens?

**Comment by CBtiger** [comment]
Well, thats correct. I just did what I gave in the first line. I did not use your GIT_LFS paramter. When I run
> env |grep LFS
> env|grep GIT 

I get no output. I am on Ubuntu 16.04 LTS.  As I said above, I did _not_ install the LFS extension of git. I just have plain git installed. Maybe I misread your ReadMe.md, but to me it suggests that the LFS extension is optional not mandatory. 

Maybe that adds to the confusion. Here is a screenshot when I open the folder of the downlaoded repro, VC Code does not seem to recognise the Markdown. I just see plain text files.
![image](https://user-images.githubusercontent.com/17408411/54551522-8f5ec280-49ae-11e9-8699-97a86abb00ca.png)

**Comment by octref** [comment]
> VC Code does not seem to recognise the Markdown. I just see plain text files.

You need to run Ctrl+Shift+P and "Markdown: Open Preview to the Side". See https://code.visualstudio.com/docs/languages/markdown#_markdown-preview

> LFS extension is optional not mandatory.

If you don't plan to touch images/videos, it's optional.

I see where the confusion comes from. It's optional in the sense that you can clone vscode-docs and contribute by changing MD files without LFS.

If you plan to update the images/videos, you need to install Git LFS.

After installing Git LFS:

- `git clone` will fetch all binary files by default
- `GIT_LFS_SKIP_SMUDGE=1 git clone` won't fetch all binary files by default

**Comment by CBtiger** [comment]
>You need to run Ctrl+Shift+P and "Markdown: Open Preview to the Side". 

Thank you. With that seeting open as context/OpenPreview works. 

>If you don't plan to touch images/videos, it's optional.
Sorry for my bad english, but "touch" would mean "modify in any way"? Then, no I do not indend to change anything. Just trying to read the help content.. 

>I see where the confusion comes from. It's optional in the sense that you can clone vscode-docs and contribute by changing MD files without LFS.

Maybe part of the confusion is that here are 2 very different use cases. You guys seem to deal in 99.999% of all cases with people who try to correct or enhance the VS Code documentation. I would say for this use case the ReadMe.md is very good.
But I am a guy with the other use case. I just want to read the documentation. I am not yet at a point where I can correct anything. I just downloaded VS Code and realized that without internet I have virtually no documentation at all. So I sit on my flight and can not even see my key codes. No single link of those help function works. Maybe I was wrong here, but I was thinking that I could donwload the help and get the whole think working offline as well. 
As Fallback I could even put it somehwere on my disk and browse the "Getting started" manually. 

If you look at it from that perspective you would understand that a download of 36MB with no images and no videos (at least the MD text parts) is not as great as I hoped for. So please bear with me. 

I can see two ways. Either there is no way to get this usefully to work offline with VS Code. Then maybe it would help to put a slim sentence in the end of the readme and say this is not for offline reading (as in "consuming"), but only for people to work on the documentation. Or, on the other hand,  if it works for that use case my feeling is its not really the most trivial thing I have ever done and maybe it would need some further Q&A.

**Comment by octref** [comment]
No worries, that's a totally fine usage.

It's just that we have moved to LFS for managing binary files. May I ask why you don't want to install LFS?

For your case, you can try cloning https://github.com/Microsoft/vscode-docs-archive. You can also install LFS and checkout binary files in this repo. Hope that answers your question.

**Comment by CBtiger** [comment]
> For your case, you can try cloning https://github.com/Microsoft/vscode-docs-archive. You can also install LFS and checkout binary files in this repo. Hope that answers your question.

Thanks. That helps me to download the file. 

It also means that in your Readme.md
>...Bare git clone will take 1.4GB+...

Is not fully correct. it will not. It will donwload texts only.


> It's just that we have moved to LFS for managing binary files. May I ask why you don't want to install LFS?

Because installing another tool just for doing sth that can be done with another existing tool is just adding complexity. I had to reinstall too many PCs to like to depend on too many tools. Less is more :-).

**Comment by octref** [comment]
Thanks for the feedback. I have updated the contributing guide to reflect what's happening with and w/o LFS when you run `git clone`.
