### ISSUE TITLE
"This site uses cookies ..." cannot be removed on Chrome on Android

### ISSUE THREAD

**Issue by bersbersbers** [Microsoft/vscode-docs#2495]
Visit https://code.visualstudio.com/docs on Chrome on Android - notice the top banner saying "This site uses cookies for analytics, personalized content and ads. By continuing to browse this site, you agree to this use. Learn more."

This banner cannot be removed and - unlike on Chrome on Windows 10 - does not disappear after using the site, for example, reloading or navigating.

Chrome 72.0.3626.121 on OnePlus 3T with Android 8.0.0, same on Huawei Mate 10 Pro with Android 9.

I originally posted this as https://github.com/MicrosoftDocs/visualstudio-docs/issues/2885#event-2210674178, but was (correctly) sent here instead.

**Comment by gregvanl** [comment]
Hi @bersbersbers I can reproduce this issue on desktop Chrome on Windows and Edge if I shrink the browser window such that the TOPICS drop down appears. I think the issue is with that control not clearing the banner.

A workaround is to use the triple bar control in the upper right, which navigates the top menu. After expanding the top menu list and selecting a section such as Docs or API, the banner disappears.

**Comment by bersbersbers** [comment]
@gregvanl I am not sure we are talking about the same issue here. For me, the issue does not reproduce on Windows. Furthermore, the problem is not that I cannot navigate - the problem is that even when navigating, the cookie banner is shown on every single page.

**Comment by gregvanl** [comment]
@bersbersbers Does the banner remain if you navigate to Updates or Blog with the triple bar dropdown in the upper right?

**Comment by bersbersbers** [comment]
I believe the issue has been fixed somehow: I could repro it consistently on two independent devices, but not any longer. Banner text disappears on the current page upon any navigation click, then banner is gone on next page. Therefore, closing this.

**Comment by gregvanl** [comment]
I can still repro the issue. The TOPICs dropdown doesn't clear the banner but the top navigation does.

![bannerRepo](https://user-images.githubusercontent.com/12818376/54845933-e8bd3f00-4c97-11e9-8490-e95886314f3c.gif)

**Comment by gregvanl** [comment]
Fixed and published.
