### ISSUE TITLE
Update PDF Document about Keyboard Shortcut Reference for: "Move line up/down".

### ISSUE THREAD

**Issue by maurobonfietti** [Microsoft/vscode-docs#2505]
Hi Team!

In the official PDF document about Keyboard Shortcut for Windows says: "Alt + ↑ / ↓    Move line up/down".

But in Visual Studio Code Version 1.32.3 for Win 10, the real key for Move line up/down is: "Shift + Alt + ↑ / ↓".

(In VSC v1.32.3 if you press: Alt + ↑ / ↓, you get instead: Add cursor Above/Below).

I send some screenshots...

Best regards.,

Mauro.-

_Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134_

<img width="960" alt="Screenshot_79" src="https://user-images.githubusercontent.com/24535949/54636369-13738180-4a65-11e9-9b01-7d0dee074679.png">
<img width="609" alt="Screenshot_80" src="https://user-images.githubusercontent.com/24535949/54636376-18d0cc00-4a65-11e9-912c-cb099cc6c661.png">

**Comment by gregvanl** [comment]
Hi @maurobonfietti The move up/down keybindings are Alt+up/down for my 1.32.3 install on windows.

![image](https://user-images.githubusercontent.com/12818376/54700274-ec15c680-4aef-11e9-8efd-2b1160789a75.png)

Might you have an extension installed which has modified those keybindings? Can you try running "code --disable-extensions" to see if you still see these keybindings with extensions disabled?

You can also look in the Keyboard Shortcuts editor to see if the keybinding Source for those commands is not Default.

**Comment by maurobonfietti** [comment]
**Hi Greg, you are right!**

**I have installed Netbeans Keymaps v0.0.4**

_Name: Netbeans Keymaps
Id: grogdunn.netbeans-keybindings
Description: Bring Netbeans default keymap to VS Code.
Version: 0.0.4
Publisher: Grogdunn
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=grogdunn.netbeans-keybindings_

Was my fault I am sorry :-)

Thank you very much!
