### ISSUE TITLE
Inconsistent code style in language server guide

### ISSUE THREAD

**Issue by SimonSiefke** [Microsoft/vscode-docs#2512]
In the section https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#explaining-the-language-server the code looks like this:
```ts
// This handler resolves additional information for the item selected in
// the completion list.
connection.onCompletionResolve(
  (item: CompletionItem): CompletionItem => {
    if (item.data === 1) {
      item.detail = 'TypeScript details';
      item.documentation = 'TypeScript documentation';
    } else if (item.data === 2) {
      item.detail = 'JavaScript details';
      item.documentation = 'JavaScript documentation';
    }
    return item;
  }
);
```

And in the section https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#adding-additional-language-features the code looks like this:
```ts
// This handler resolves additional information for the item selected in
// the completion list.
connection.onCompletionResolve(
  (item: CompletionItem): CompletionItem => {
    if (item.data === 1) {
      (item.detail = 'TypeScript details'),
        (item.documentation = 'TypeScript documentation');
    } else if (item.data === 2) {
      (item.detail = 'JavaScript details'),
        (item.documentation = 'JavaScript documentation');
    }
    return item;
  }
);
```

The second code block looks a bit weird, I could make a pull request if you want.

**Comment by octref** [comment]
They are formatted with prettier, so on mobile screen where there aren't much width to display the code, there is less wrapping happening:

![image](https://user-images.githubusercontent.com/4033249/54942325-14386780-4eec-11e9-907a-1532b6424750.png)

**Comment by SimonSiefke** [comment]
But why this:
```typescript
(item.detail = 'TypeScript details'),
  (item.documentation = 'TypeScript documentation');
```
instead of this:
```typescript
item.detail = 'TypeScript details';
item.documentation = 'TypeScript documentation';
```

**Comment by octref** [comment]
I'm sorry, somehow I totally missed that part. Fixed in docs and sample. Will publish soon.

**Comment by Leenai0425** [comment]
// This handler resolves additional information for the item selected in
// the completion list.
connection.onCompletionResolve(
  (item: CompletionItem): CompletionItem => {
    if (item.data === 1) {
      item.detail = 'TypeScript details';
      item.documentation = 'TypeScript documentation';
    } else if (item.data === 2) {
      item.detail = 'JavaScript details';
      item.documentation = 'JavaScript documentation';
    }
    return item;
  }
);

**Comment by Leenai0425** [comment]
item.detail = 'TypeScript details';
item.documentation = 'TypeScript documentation';

**Comment by Leenai0425** [comment]
https://github.com/microsoft/vscode-docs/issues/2512#issuecomment-476309745

**Comment by Leenai0425** [comment]
item.detail = 'TypeScript details';
item.documentation = 'TypeScript documentation';
