### ISSUE TITLE
Variable Reference suggests variable substitution is available in inputs

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/vscode-docs#2514]
The [docs](https://github.com/Microsoft/vscode-docs/blob/9f3bc5f100195ae6880a34efef98e974d519ce65/docs/editor/variables-reference.md) state with the example below ( no gif though... ) - ${workspaceFolder} in the pickTest input command.  Introduced in this [commit](https://github.com/Microsoft/vscode-docs/commit/4f1699f351629a68a4b49a84d6c8587bf47a795a)

`{
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Run specific test",
            "program": "${workspaceFolder}/${input:pickTest}"
        }
    ],
    "inputs": [
        {
            "id": "pickTest",
            "type": "command",
            "command": "extension.mochaSupport.testPicker",
            "args": {
                "testFolder": "${workspaceFolder}/tests",
            }
        }
    ]
}`

Does not work for me with vscode 1.32.3 and there is an open issue on the vscode repository - [consider to allow for variable substitution in the inputs section](https://github.com/Microsoft/vscode/issues/64358).

**Comment by alexr00** [comment]
I think the idea with this example is that the extension would handle that argument, but it is confusing.
