### ISSUE TITLE
Add property name to completion types table

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-docs#2518]
Testing https://github.com/Microsoft/vscode/issues/71084

For the [Types of completion table](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions) in our docs, it would be beneficial to have a column for the property name of each item so that it's explicit. Though you can search through intellisense, we shouldn't leave any amount of uncertainty when setting this.

**Example**
<img width="795" alt="image" src="https://user-images.githubusercontent.com/35271042/55020364-ecacd200-4fb3-11e9-8e0d-42120f672e8a.png">

Additionally, I wasn't able to find the following items (from the table) in the settings list:
- Global Identifiers
- Words
- Miscellaneous

**Comment by sbatten** [comment]
This was fairly confusing as some of the items seem to map to multiple and some had no match. 

Methods and Functions had individual matches, but what does constructors belong to?
Also, suggestions revealed values that didn't have direct matches in this documentation.

I think we are re-using existing documentation here, but if we are pointing to something as a reference, it should probably be 1:1
