### ISSUE TITLE
Add a formatter guide under "Language Extensions"

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#2522]
- Talk about document formatter, selection formatter, format on paste/save
- Point out 2 approaches: use API vs LSP
- Stress on dynamic registration/disablement on setting

Provide a sample too. One I can think of:

- Doc formatter: Remove trailing empty line
- Range formatter: Remove trailing whitespace characters

**Comment by gregvanl** [comment]
@octref Do we still need this? Looks like it is partially covered in https://code.visualstudio.com/api/language-extensions/programmatic-language-features#format-source-code-in-an-editor

**Comment by gregvanl** [comment]
Closing old work item issue without upvotes
