### ISSUE TITLE
ts-ignore for import fails on multi-line import statements.

### ISSUE THREAD

**Issue by alfnielsen** [Microsoft/vscode-docs#2523]
Why ts-ignore?
We use it for import statement for js modules that have no typing, 
but also for import modules written in typescript but where the source-code are made with NoImplicitAny:false and therefore returns a module that gives the error: 'has implicit any...'

We want to use formatting tools like Prettier and they (at least Prettier) split import statement into multiple line, and ts-ignore fails on that!

What we would write is:
```typescript
//@ts-ignore
import { a, b } from 'MyNonTypedModule'
```
But it's converted to:
```typescript
//@ts-ignore
import { 
  a, 
  b 
} from 'MyNonTypedModule'
```
And ts-ignore fails here. (We would still get the error for 'MyNonTypedModule')

We can fix this by writing: 
```typescript
import { 
 a, 
 b
//@ts-ignore
 } from 'MyNonTypedModule'
```
But now auto import stop working.
If we import a new part from 'MyNonTypedModule' let say 'c',
it will be added as a new import statement
```typescript
import { 
 a, 
 b
//@ts-ignore
 } from 'MyNonTypedModule'
import { c }  from 'MyNonTypedModule'
```
So I think ts-ignore written on the line before an import statement, 
should ignore the import statement regardless of whether or not the import statement is written as a single line or over multiple line.

**Comment by gregvanl** [comment]
Hi @alfnielsen I'm not sure I understand your issue. This repo is for VS Code documentation hosted on code.visualstudio.com and you can create issues here related to the docs.
Reading your comment, it appears to be feedback for TypeScript and their implementation of ts-ignore. Would the TypeScript repo be a better place for this issue? https://github.com/Microsoft/TypeScript/issues

**Comment by alfnielsen** [comment]
Oh sorry!
Wrong place then, I thought I was written it in Typescript' issues...
