### ISSUE TITLE
Update screenshots on Python testing docs

### ISSUE THREAD

**Issue by luabud** [Microsoft/vscode-docs#2528]
We introduced new icons for the test explorer on the March release. It'd be nice if we could update the screenshots that are on the [docs](https://code.visualstudio.com/docs/python/unit-testing) to the new ones: 

![image](https://user-images.githubusercontent.com/45497113/55265558-1aa14900-5236-11e9-9539-c73c161929f1.png)

**Comment by kraigb** [comment]
@gregval These should go to @JoshuaPartlow now.
