### ISSUE TITLE
VS Code unable to select Python virtualenv

### ISSUE THREAD

**Issue by ideologysec** [Microsoft/vscode-docs#2532]
macOS 10.14.4
VS Code 1.32.3
Python Extension 2019.3.6215

```
$ brew install python3
$ /usr/local/bin/python3 --version
Python 3.7.2
$ mkvirtualenv --python=/usr/local/bin/python3 --always-copy vscode
$ workon vscode
$ python --version
Python 3.7.2
```
- Attempt to select Python interpreter in VS Code.
- Success!
 - Python 3.7.2.
 - I can pip install packages in the virtualenv in Terminal or the builtin  VS Code terminal, everything is hunky dory.

Then, sometime later: 
```
$ brew upgrade
==> Upgrading 1 outdated package:
python 3.7.2_2 -> 3.7.3
==> Upgrading python
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.3.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring python-3.7.3.mojave.bottle.tar.gz
==> /usr/local/Cellar/python/3.7.3/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/
==> /usr/local/Cellar/python/3.7.3/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/
==> /usr/local/Cellar/python/3.7.3/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.7.3: 3,867 files, 59.8MB
Removing: /usr/local/Cellar/python/3.7.2_2... (8,464 files, 118.4MB)
Removing: /Users/user/Library/Caches/Homebrew/python--wheel--0.33.0.tar.gz... (18.3KB)
Removing: /Users/user/Library/Caches/Homebrew/python--3.7.2.tgz... (21.8MB)
Removing: /Users/user/Library/Caches/Homebrew/python--pip--19.0.2.tar.gz... (1.3MB)
```

which is all well and good!
but: VS Code is no longer happy about the virtual environment. "Select Python Interpreter"
even though I specified _copy all files_, even though I can `workon vscode` and that brings up the old 3.7.2 python virtualenv, all packages still installed,

VS Code refuses to use the old virtualenv. Even manually specifying the interpreter in the user settings.json and the workspace settings.json file, VS Code keeps yelling about "Select Python Interpreter." It seems to have stopped believing that the virtualenv is valid.

![configured not recognized](https://user-images.githubusercontent.com/790061/55358536-80831000-5484-11e9-8ed1-d607c66a6ded.png)

How do I get VS Code to keep using virtualenvs I create after I upgrade my homebrew python version? This is really annoying; I don't want to keep recreating virtualenvs every time python updates (nor do I want to lock my homebrew system python from upgrading).

Per the documentation at https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments 
> If you have any problems with VS Code recognizing a virtual environment, please file an issue in the documentation repository so we can help determine the cause.

I am having trouble getting VS Code to recognize a virtual environment. Please help me determine the cause. :)

**Comment by gregvanl** [comment]
@JoshuaPartlow You may need to loop in the feature team to help investigate @DonJayamanne @brettcannon

**Comment by DonJayamanne** [comment]
Issue moved to [Microsoft/vscode-python #5062](https://github.com/Microsoft/vscode-python/issues/5062) via [**ZenHub**](https://www.zenhub.com/)
