### ISSUE TITLE
Add "Configure Unit Tests" to the Python docs

### ISSUE THREAD

**Issue by luabud** [Microsoft/vscode-docs#2534]
On the February release of the Python extension we added a new command to "Configure Unit Tests". More details on the blog post: https://devblogs.microsoft.com/python/python-in-visual-studio-code-february-2019-release/

It'd be great if we could add that to our docs page: https://code.visualstudio.com/docs/python/unit-testing

**Comment by gregvanl** [comment]
@luabud While @JoshuaPartlow is ramping up, feel free to provide content or a PR.
