### ISSUE TITLE
Keyboard Shortcuts out of date

### ISSUE THREAD

**Issue by geyzon** [Microsoft/vscode-docs#2541]
Some items of the menus are with your keyboard shortcuts out of date relative to the PDF https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf. That document is updated and it was my salvation. (VSCode v1.32.3)

**Comment by gregvanl** [comment]
Hi @geyzon, I'm not sure if you are reporting an issue or thanking VS Code for updating the Windows keyboard shortcut PDF? Is there a specific keyboard shortcut which is out of date? We updated the PDF last month so perhaps you're just showing your appreciation.

**Comment by gregvanl** [comment]
Closing as no clarifaction after 4 days. Feel free to reopen if there is a documentation issue.

**Comment by geyzon** [comment]
No @gregvanl , I meant was that the keyboard shortcut tips next to the menu items are outdated, for example, in the Edit menu, the Comment in Block item and the Comment in Line item. Do You understand now?

**Comment by gregvanl** [comment]
I wonder if you have a keymap extension installed?
When I look at the Edit menu for the 1.33 release on Windows, I see the same keyboard shortcuts as the Windows PDF.

![image](https://user-images.githubusercontent.com/12818376/55737065-604dd680-59d9-11e9-8649-7f41fc4e00eb.png)

![image](https://user-images.githubusercontent.com/12818376/55737123-7c517800-59d9-11e9-8d29-491d6b2da9d0.png)

You can check if an extension is changing the keybinding by looking in the Keyboard Shortcuts editor and examining the Source column. It should say "Default".

![image](https://user-images.githubusercontent.com/12818376/55737328-d3efe380-59d9-11e9-86e2-b1cf61867878.png)
