### ISSUE TITLE
Computer caton

### ISSUE THREAD

**Issue by xiaodoubaoldl** [Microsoft/vscode-docs#2544]
The new version caused the computer to freeze

**Comment by gregvanl** [comment]
Hi @xiaodoubaoldl This repository is for VS Code documentation issues. If you have a VS Code product issue, you can enter a bug in the vscode repo https://github.com/Microsoft/vscode. Please search for existing issues before creating a new one and provide as much information as possible (type of project working on, extensions installed, any repro steps).
