### ISSUE TITLE
无法将“/K”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。

### ISSUE THREAD

**Issue by mfdy** [Microsoft/vscode-docs#2548]
Unable to compile cpp files
> Executing task: clang++ 'd:\Code\code of VS code\C C++\1.cpp' -o 'd:\Code\code of VS code\C C++/1.exe' -g -Wall -static-libgcc -fcolor-diagnostics --target=x86_64-w64-mingw -std=c++17 <

/K : 无法将“/K”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ /K chcp 65001 >nul -Command clang++ 'd:\Code\code of VS code\C C++\1. ...
+ ~~
    + CategoryInfo          : ObjectNotFound: (/K:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by mfdy** [comment]
everything is ok after deleted C:\User\…\code

**Comment by gregvanl** [comment]
Hi @mfdy This repository is for the VS Code documentation. Is your issue with the C++ extension for VS Code (https://marketplace.visualstudio.com/itemdetails?itemName=ms-vscode.cpptools)? If so, you should enter an issue in the extension repo https://github.com/Microsoft/vscode-cpptools/issues.

**Comment by gregvanl** [comment]
Closing as no follow up from issue creator

**Comment by victoryning** [comment]
我在vs中打开终端的时候也会出现这个问题，也不知道为什么
