### ISSUE TITLE
Java with Kubernetes in VS Code link doesnt work

### ISSUE THREAD

**Issue by rangv** [Microsoft/vscode-docs#2552]
Points to this URL https://code.visualstudio.com/docs/java/java-kubernetes. Link is broken

**Comment by gregvanl** [comment]
Hi @rangv The topic was moved to https://code.visualstudio.com/docs/azure/kubernetes. Where do you see the old URL?

**Comment by gregvanl** [comment]
I do see it still in Google search:

![image](https://user-images.githubusercontent.com/12818376/55844031-49e66e80-5af0-11e9-8df2-f6beb851fe57.png)

I'll add a redirect to the new location.

**Comment by gregvanl** [comment]
Fixed with a redirect.
Thanks for reporting this!
