### ISSUE TITLE
overlapping content in extension manifest site 

### ISSUE THREAD

**Issue by SimonSiefke** [Microsoft/vscode-docs#2554]
![screenshot](https://user-images.githubusercontent.com/23744935/55901537-cc8f2c80-5bc9-11e9-9083-49a4f31d0703.png)
The table on the [extension manifest site](https://code.visualstudio.com/api/references/extension-manifest) is overlapping with the navigation menu on the right.

**Comment by gregvanl** [comment]
Looks like the fix for https://github.com/Microsoft/vscode-docs/issues/2275 has unintended consequences. Should probably revert the fix and try more testing.

**Comment by octref** [comment]
Fixed by reverting fix for #2275.
