### ISSUE TITLE
Java with Docker in VS Code link doesn't work

### ISSUE THREAD

**Issue by bharadwaj-pendyala** [Microsoft/vscode-docs#2558]
In Java Overview tab in VS Code there is a link as shown in imaeg below which is pointing to *Java with Docker in VS Code* - "https://code.visualstudio.com/docs/java/java-container" is broken.

Issue with link:

![image](https://user-images.githubusercontent.com/4959529/56045802-89ff5880-5d5f-11e9-9285-a8be0654b979.png)

Error Image: 

![image](https://user-images.githubusercontent.com/4959529/56045846-a00d1900-5d5f-11e9-9e99-81375a64771a.png)

**Comment by gregvanl** [comment]
The Java with Docker in VS Code topic was deprecated in favor of https://code.visualstudio.com/docs/azure/docker.
Fixed with website redirect
