### ISSUE TITLE
Can't Select Python Interpreter

### ISSUE THREAD

**Issue by scoat22** [Microsoft/vscode-docs#2562]
I'm using Visual Studio Code to try and make a new project using Python, but everytime I try to use "Python: Select Interpreter", there's no options and it just says "current: python"

**Comment by scoat22** [comment]
Nevermind, just needed to re-open Visual Studio Code

**Comment by SKrishnan2006** [comment]
I had the same problem. Re-opening Visual Studio Code did not fix it. When I use "Python: Select Interpreter", it gives me a dialog box.
