### ISSUE TITLE
The command for "Dynamic previews and preview locking" is expired.

### ISSUE THREAD

**Issue by U03251111** [Microsoft/vscode-docs#2566]
The command "Markdown: Toggle Preview Locking" has changed to "Markdown: open locked preview to the side" or others in "windows version 1.33.1".

**Comment by U03251111** [comment]
I have pulled a request "update the expired command #2567" for this issue.

**Comment by gregvanl** [comment]
Hi @U03251111 The command "Markdown: Toggle Preview Locking" is still available but only available if you have a Markdown preview open.

![image](https://user-images.githubusercontent.com/12818376/56160907-2bafc100-5f7d-11e9-9b33-b17a4f7bdd7e.png)
