### ISSUE TITLE
Update Debugging Documentation for Python to include multi-threading

### ISSUE THREAD

**Issue by Anapo14** [Microsoft/vscode-docs#2569]
Based on [this ](https://github.com/Microsoft/ptvsd/issues/1189#issuecomment-468406399) user-filed issue, we should include a note about multi-threaded debugging in the python debugging for vscode documentation [here](https://code.visualstudio.com/docs/python/debugging#_troubleshooting).

**Comment by gregvanl** [comment]
@Anapo14 PRs welcome. @JoshuaPartlow can review and merge.
