### ISSUE TITLE
Update docs to modify console type string from "none" to "internalConsole"

### ISSUE THREAD

**Issue by karrtikr** [Microsoft/vscode-docs#2572]
### PYTHON EXTENSION - DEBUGGING

Please check [here](https://code.visualstudio.com/docs/python/debugging#_console) in the docs.

Console type string "none" is to be replaced by "internalConsole". (PR [#5245](https://github.com/Microsoft/vscode-python/pull/5245/files#r275565168)).

**Comment by gregvanl** [comment]
@karrtikr PRs welcome. @JoshuaPartlow can help review and merge.

**Comment by kraigb** [comment]
@JoshuaPartlow FYI, I added a commit (see above) to another PR to handle this one.
