### ISSUE TITLE
[Python] Update debug config recipes and link to them.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode-docs#2573]
We are removing the [debugger configuration snippets](https://github.com/Microsoft/vscode-python/blob/b25eeed7bb6d1b16279965ce7ac93d0d57162ed8/package.json#L843) from the Python extension's package.json.  We need the following:

- [ ] ensure all those snippets are on [the recipes page](https://github.com/Microsoft/vscode-recipes/tree/master/debugging%20python)
- [ ] update that page reflect how the generated launch.json no longer has all those snippets automatically added
- [ ] link back to the recipes in [the appropriate docs page](https://code.visualstudio.com/docs/python/debugging#_debugging-specific-app-types)

Thanks!

**Comment by JoshuaPartlow** [comment]
Not sure if there's still a doc action needed here, so closing. If there's work that should still be done, please reopen.
