### ISSUE TITLE
[C++] Include errors detected, cannot open source file "wchar.h" (dependency of "iostream")

### ISSUE THREAD

**Issue by zry9056** [Microsoft/vscode-docs#2574]
After following the steps in "Using Clang in Visual Studio Code" section, I ran into an include error when adding a source code file in the very first line "#include <iostream>". I tried editing c_cpp_properties.json file as stated in docs and deleting it entirely, but this errors does not go away. The error message goes like:

**#include errors detected. Please update your includePath. IntelliSense features for this translation unit (projects/helloworld/helloworld.cpp) will be provided by the Tag Parser.
cannot open source file "wchar.h" (dependency of "projects/helloworld/helloworld.cpp")** 

Any ideas on how to solve this issue?

**Comment by mikeblome** [comment]
@zry9056 is this the same wchar.h as the one in the C standard library, and is it in the default location? If so, are you seeing other headers? As a general rule, you should delete the "IncludePath" setting completely unless you have header files that are not in the standard locations or in your workspace folder.

**Comment by prideout** [comment]
I've seen this intermittently as well, but have been unable to diagnose the issue.  In general I feel it would be nice for users to get better insight into where Intellisense runs afoul when searching for headers.  I often see a green squiggly in the copyright comment in a header file with a highly generic error like:

```
#include errors detected. Please update your includePath. IntelliSense features for this translation unit (/path/to/main.cpp) will be provided by the Tag Parser.
```

@mikeblome sometimes it helps to open the problems pane with `View: Focus Problems`.

**Comment by mikeblome** [comment]
@zry9056 I'm closing this but feel free to reopen if you are still having problems.
