### ISSUE TITLE
shortcuts 404

### ISSUE THREAD

**Issue by xgqfrms** [Microsoft/vscode-docs#2575]
# shortcuts 404

https://code.visualstudio.com/shortcuts/

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows

![image](https://user-images.githubusercontent.com/7291672/56261453-a1e32d80-610d-11e9-9a48-f9a6a22522ed.png)

**Comment by xgqfrms** [comment]
https://codepen.io/xgqfrms/full/GyEGzG/

**Comment by gregvanl** [comment]
Hi @xgqfrms This folder and Markdown file was created to generate the initial keyboard shortcuts for the keyboard shortcut PDFs. The file is not used to generate an HTML page on the website so you get 404 if you try to navigate there. We keep the file in the vscode-docs repo in case we need to regenerate the keyboard shortcuts.
I don't understand you second comment with the codepen.io URL.
