### ISSUE TITLE
Update Python linting docs w/ updated Language Server info

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#2577]
[This](https://code.visualstudio.com/docs/python/linting) page should be updated with the following modifications:

- Modify the current introduction section such that it explains the differences between static analysis and linting. This section should also distinguish the Language Server’s capabilities from those of Jedi.
- The statement “By default, linting for Python is enabled in Visual Studio Code using Pylint” should be updated to “By default, stylistic and syntactical code detection is enabled by the Language Server. If you require third-party linters for additional problem detection, however, you can enable them by using the Python: Enable Linting command and selecting the appropriate linter.” 
-  Include details on the behavior a user should expect when using our language server in conjunction with a third-party linting tool (i.e. real-time problem messages vs problem messages displayed upon save).

**Comment by gregvanl** [comment]
Closing old issue.
