### ISSUE TITLE
Update Editing Python Code Docs

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#2578]
Update the [editing python code](https://code.visualstudio.com/docs/python/editing) page to include: 

- Include an example of how a user might configure their settings.json file and what the expected result should be (i.e. if a user decides that “unknown-parameter-name” should be categorized as an error, the instructions should show a user how the LS handles this).
- We should include a note that the Language Server provides real-time problem detection and that you can hover over a squiggle for more info.

**Comment by gregvanl** [comment]
@Anapo14 PRs to vscode-docs welcome. @JoshuaPartlow can help merge and publish updates.

**Comment by Anapo14** [comment]
If I can find the time I will, but was hoping Josh would be able to give it a go and loop me in for questions/assistance.
