### ISSUE TITLE
Octicon animation

### ISSUE THREAD

**Issue by KamasamaK** [Microsoft/vscode-docs#2579]
I cannot find any documentation on the animations that can be applied to Octicons used in the status bar. For example, the `$(sync)` icon can be `$(sync~spin)` to add a spinning animation. I'm not sure if there are others. It would probably fit best in [Icons in Labels](https://code.visualstudio.com/api/references/icons-in-labels).

**Comment by misolori** [comment]
Fixed via https://github.com/Microsoft/vscode-docs/commit/3a821ff98849388281d68215c3cb1873ee271ead
