### ISSUE TITLE
misunderstang command: Compare Selected

### ISSUE THREAD

**Issue by U03251111** [Microsoft/vscode-docs#2587]
## questions
I cannot  find the command in "GET STARTED->User Interface->Explorer->Multi-selection".
> If you select two items, you can now use the Compare Selected command to quickly diff two files.
## steps
* select two files in "OPEN EDITORS" or "my_folder" of explorer
* open command palette
* olny find such three commands like “File: Compare Active File With ...”
## version 
windows version 1.33.1

**Comment by gregvanl** [comment]
Hi @U03251111 Thank you for calling out this potential confusing text. The Compare Selected command is on the Explorer context menu not the Command Palette.

![image](https://user-images.githubusercontent.com/12818376/56437935-15b04200-6296-11e9-8be7-cae4a3c269a5.png)

I'll update the documentation to make that clear.
