### ISSUE TITLE
[Improvement] C/C++: Configure debug settings -> more dynamic sourceFileMap

### ISSUE THREAD

**Issue by n3rd4i** [Microsoft/vscode-docs#2590]
The C/C++ docs for [setting up debugging](https://code.visualstudio.com/docs/cpp/config-wsl#_configure-debug-settings) could be improved to change:
Original:
```json
"sourceFileMap": {
	"/mnt/c": "c:\\",
	"/usr": "C:\\Users\\<path to WSL directory which you will place here later>"
}
```

Improved:
```json
"sourceFileMap": {
	"/mnt/c": "${env:systemdrive}/",
	"/usr": "C:\\Users\\<path to WSL directory which you will place here later>"
}
```

**Comment by mikeblome** [comment]
@n3rd4i thanks yep that is better. I'll make this change today.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/eb1c5b8a6d317fbe7d236293242102aab0e2c554
