### ISSUE TITLE
Add a nice search experience

### ISSUE THREAD

**Issue by s-pace** [microsoft/vscode-docs#2596]
👋 team,

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [react](https://reactjs.org/), [Bootstrap](https://getbootstrap.com/), [Brew](https://brew.sh/) or [jQuery](https://jquery.com/).

I have created [a preview of how DocSearch can help vscode](https://code_visualstudio-docsearch.surge.sh/) and what DocSearch on the vscode website could will look like here. Feel free to try it and let us know what you think. Please note the learn-as-you-type experience and the typo tolerance:

[![demo of DocSearch + vscode](https://cl.ly/c7d676ae74da/download/Screen%20Recording%202019-04-24%20at%2004.09%20PM.gif)](https://code_visualstudio-docsearch.surge.sh/)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/code_visualstudio.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to *analytics on the most searched terms* or those with *no results*. All of this is of course *entirely free*.

**Comment by octref** [comment]
Hi 👋 @s-pace, this is something I looked into a while ago and I have an issue in the backlog tracking it. Do you have an email I can reach out to?

**Comment by s-pace** [comment]
Sure @octref, docsearch@algolia.com

**Comment by s-pace** [comment]
Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '6b2c081dfef89c243c734385ec254885',
  indexName: 'code_visualstudio',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
````

- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/styling.html)
- You can also check your configuration in our GitHub repo (https://github.com/algolia/docsearch-configs/blob/master/configs/code_visualstudio.json).

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by gregvanl** [comment]
Closing as no plans to update the website search experience
