### ISSUE TITLE
Create docs for Python Extension Variable Explorer

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-docs#2598]
We'll need documentation for the new Variable Explorer in the Python extension. I can be the point of contact for documenting this. It's also lightly outline in the announcement blog post here:
https://devblogs.microsoft.com/python/python-in-visual-studio-code-april-2019-release/

**Comment by JoshuaPartlow** [comment]
Content updated with PR https://github.com/microsoft/vscode-docs/pull/2739
