### ISSUE TITLE
Need documentation on what to do if .deb package fails to install on Linux

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode-docs#260]
@gregvanl it's possible when a user attempts to install the `.deb` package file for Linux that it may fail if a user doesn't manually run a command first in their terminal.

Please see
https://github.com/Microsoft/vscode/issues/4922#issuecomment-205947986

Could we add a section to the docs on what to do if this happens?

All they need to do is run `sudo apt-get update` and then try reinstalling.  Then it should work.

**Comment by Tyriar** [comment]
Something like this:

> If you experience issues installing, open a terminal and run `sudo apt-get update` and try again.

**Comment by gregvanl** [comment]
Added to FAQ by https://github.com/Microsoft/vscode-docs/commit/c1ff6fafa2fc00e7d866b5dff708c1fb40a775a3#diff-77bc57d3dd82925601c5482c757ae3f5
