### ISSUE TITLE
Configure VS Code for Microsoft C++

### ISSUE THREAD

**Issue by hellozhaihy** [Microsoft/vscode-docs#2600]
I have followed this step https://code.visualstudio.com/docs/cpp/config-msvc to compile C++ in vscode, using MSVC compiler. Anything looks fine. But in the final step "Start a debugging session", i get a warning
```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'C:\Users\hello\Desktop\projects\helloworld\build.exe'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
The thread 3604 has exited with code 0 (0x0).
```
I'd like to know how to solve this warning. Thank you.

**Comment by mikeblome** [comment]
@hellozhaihy The "you may only use..." message is always put there. Not an error. You can also ignore the warnings about the pdb files. You don't need them unless you are trying to do low-level debugging in the Windows system DLLs. I can see how this might be confusing for new users. I'll update the topic to mention it.
