### ISSUE TITLE
WorkspaceConfiguration.inspect API documentation isn't very useful

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#2601]
```
* Refer to [Settings Inheritance](https://code.visualstudio.com/docs/getstarted/settings)
* for more information.
```

Settings inheritance doesn't appear on the page.

Also one of the properties is `globalValue`, but this is referred to as "user settings" throughout the docs.

**Comment by sandy081** [comment]
It talks about the inheritance but did not cover workspace folders. Will add it.

![image](https://user-images.githubusercontent.com/10746682/56719347-d45ddd80-6740-11e9-9aee-cb5ad38dc858.png)

Documentation of the `WorkspaceConfiguration` API talks about the hierarchy of values. I can duplicate it for `inspect` api too.

**Comment by Tyriar** [comment]
The main problem is that it's referring to both "inheritance" and "globalValue", both of which do not appear on that page. vscode.d.ts should mention at the very least that `globalValue` is the _user_ settings value.

**Comment by gregvanl** [comment]
I think there is enough context in the opening comments for WorkspaceConfiguration that explains global settings come from User Settings.
Created https://github.com/microsoft/vscode/pull/83166 to address mentioning "inheritance".
