### ISSUE TITLE
Consider optimizing GIFs in release notes

### ISSUE THREAD

**Issue by danilaml** [microsoft/vscode-docs#2628]
Each release notes contain several big (1+ MB, some are even close to 10MB) GIF animations.
The size can be reduced significantly by either switching the image format (to APNG, for example) or using some clever GIF compression techniques (simple transparency optimization with minimum fuzzing is often enough to reduce the image size by half).

**Comment by shamak12** [comment]
I cant understand

**Comment by gregvanl** [comment]
Reduced using ezgif.com default Lossy GIF compression to shrink about 30% for 1.34 .gifs
