### ISSUE TITLE
Cannot find name 'angular'.

### ISSUE THREAD

**Issue by ericwang1902** [Microsoft/vscode-docs#263]
I use angular-fullstack-generator to generate my project , everything is ok.
But when I import the project into VSC , in the controller.ts, the error happened ,info of error is
` "Cannot find name 'angular'."`
how can I solve the problem ?

**Comment by gregvanl** [comment]
Have you included the Type Definition files for angular in your project?
You can use the Typings tool (https://github.com/typings/typings/blob/master/README.md)

npm install -g typings
typings install angular --ambient

There is a discussion of Typings in the Node.js runtime walkthrough which installs the typings for Node.js and Express. https://code.visualstudio.com/docs/runtimes/nodejs

**Comment by gregvanl** [comment]
This worked for me when I added the angular typings.
You'll also need to create a jsconfig.json file in the project root per the instructions in the Node.js walkthrough.

**Comment by gregvanl** [comment]
Hi Eric,
I'm closing this issue but feel free to reactivate it if you think there is a documentation issue.
