### ISSUE TITLE
VSCode can't find virtual environment

### ISSUE THREAD

**Issue by paymog** [microsoft/vscode-docs#2636]
I have a workspace set up like:

![image](https://user-images.githubusercontent.com/1986950/57343915-39252900-7180-11e9-8bd4-fb1095e0f3ad.png)

and I'm having problems getting VSCode to use the interpreter from my virtual environment, `.venv`.  I've tried setting `python.venvPath` to the absoloute path of the venv with `/Users/paymahn/<company>/ml-pipeline/intent/.venv` and I've also tried setting `python.venvPath` with relative paths like `.venv` and `./.venv` and none seem to work. This problem doesn't exist in another one of my workspaces where the virtual env was automatically detected. The other workspace has a directory structure like:

![image](https://user-images.githubusercontent.com/1986950/57344145-f152d180-7180-11e9-9813-bcc373b0c60c.png)

**Comment by paymog** [comment]
Ah, I think I found the problem. I recently performed some library upgrades and I think it broke virtual environments across my entire machine. Here's the output when I tried to use this environment from pycharm:

```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/paymahn/solvvy/ml-pipeline/intent/venv/bin/python
  Reason: image not found
```

I'm going to destroy my virtual env and recreate.

**Comment by paymog** [comment]
Yup, that fixed it. I think when I did the library upgrades some symlinking with pyenv got messed up. It would be nice if this failure was reported to the user when searching for virtual environments.

**Comment by gregvanl** [comment]
Hi @paymog, this sounds like a suggestion for the Python extension (ms-python.python). If so, you can open a suggestion in the extension repo https://github.com/Microsoft/vscode-python/issues.
