### ISSUE TITLE
Remove common error case 20001

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#264]
https://code.visualstudio.com/docs/supporting/errors#_20001

Error removed by omnisharp in latest release https://github.com/OmniSharp/omnisharp-vscode/issues/116#issuecomment-208520820

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/a4987cf559017bb414dabf1970aa99ed6cfc4ac7

**Comment by 777777716** [comment]
My version is 1.3.1, yesterday my VSCode was good, but today tell me this error.

**Comment by Tyriar** [comment]
@777777716 do you have the C# extension installed?

**Comment by 777777716** [comment]
OS: macOS
VSCode's version: 1.3.1
Run with: Unity5.3.5f1

@Tyriar No, I only have the Legacy C# Support.
Few days later, this error disappeared. 
But three days ago, this error appeared again, and I fixed it.
How:
1. I try to removed all about VSCode's files in my project, include *.csproj.
2. Add dotBunny/VSCode.cs to the Assest/Plugins/.
3. Open project in Unity and open my code by VSCode.
4. Then this error disappeared again.

**Comment by Tyriar** [comment]
If you had legacy support installed that would be the reason as it's the old code which had the error, it's since been fixed in the latest version of the C# extension.
