### ISSUE TITLE
A11y_code.visualstudio.com(CELA-P1)_Download VSCode_Keyboard: Focus order is navigating from "Snap Store" link to  "MAC" link instead of navigating from  ".rpm link to "MAC" link

### ISSUE THREAD

**Issue by Arjun553** [microsoft/vscode-docs#2651]
**Check out Keros!** - Identify accessibility bugs before check-in and make bug fixing faster and easier.
**Environment Details:**
code.visualstudio.com/download
Browser: Edge, Chrome

**Repro Steps:**
1)Hit the URL:code.visualstudio.com/download
2)Verify whether focus order is properly navigating inside the page (i.e. from left to right and from top to bottom)

**Actual Result:**
Focus order is navigating from "Snap Store" link to  "MAC" link instead of navigating from  ".rpm link to "MAC" link

**Expected Result:**
Focus order should navigate from ".rpm link to "MAC" link and focus should follow proper logical order (i.e. from left to right and from top to bottom)

**User Impact:**
Keyboard users will face difficulty in understanding and accessing the controls if   Focus order is navigating from "Snap Store" link to  "MAC" link instead of navigating from  ".rpm link to "MAC" link

**Mas reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}

**Comment by Arjun553** [comment]
[Bug_2651_Focus order.pptx](https://github.com/microsoft/vscode-docs/files/3162020/Bug_2651_Focus.order.pptx)

**Comment by auchenberg** [comment]
The focus order will now follow the column structure, and each sub-link like all the 32 and 64bit links will be navigated too before moving on to the next column.

**Comment by fsteffi** [comment]
GitHubTags:#CAITestPass_June’19;
