### ISSUE TITLE
A11y_code.visualstudio.com(CELA-P1)_VS Code FAQ_Keyboard:Keyboard focus is going to the non interactive element i.e "in this article"

### ISSUE THREAD

**Issue by Amlan454** [microsoft/vscode-docs#2653]
Check out Keros!- Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Environment Details**:
code.visualstudio.com/docs/supporting/faq
Browser: chrome, edge

**Note:
This issue is observed through out the application:**
code.visualstudio.com/docs
 code.visualstudio.com/docs/supporting/faq
 code.visualstudio.com/docs/setup/linux
 code.visualstudio.com/docs/getstarted/settings
 code.visualstudio.com/docs/python/python-tutorial
 code.visualstudio.com/updates/v1_30
 code.visualstudio.com/docs/editor/whyvscode
 code.visualstudio.com/docs/getstarted/tips-and-tricks
 code.visualstudio.com/updates/v1_29
 code.visualstudio.com/docs/editor/integrated-terminal
 code.visualstudio.com/docs/editor/debugging
 code.visualstudio.com/docs/editor/versioncontrol

**Repro Steps:**
1)Hit the URL(code.visualstudio.com/docs/supporting/faq)and login by using appropriate credential
2)Tab till the in this article and check keyboard focus is going to non interactive element or not

**Actual Result:**
Keyboard focus is going to the non interactive element i.e. "in this article"

**Expected Result:**
Keyboard focus should not go to any non interactive element

**User Impact:**
Keyboard users will get confused if the focus will be landed on  the non interactive element  

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}

**Comment by Amlan454** [comment]
[Bug_2653_Keyboard focus is going to noninteractive element.pptx](https://github.com/microsoft/vscode-docs/files/3162006/Bug_2653_Keyboard.focus.is.going.to.noninteractive.element.pptx)

**Comment by Amlan454** [comment]
![Bug_2653_1](https://user-images.githubusercontent.com/42638683/57602055-bdf6b500-757b-11e9-8fce-217d13ba6d5c.png)

**Comment by Amlan454** [comment]
![Bug_2653_2](https://user-images.githubusercontent.com/42638683/57602147-fac2ac00-757b-11e9-89ed-2d423607404c.png)

**Comment by Amlan454** [comment]
![Bug_2653_3](https://user-images.githubusercontent.com/42638683/57602528-f8148680-757c-11e9-9d6a-eff87677aec8.png)

**Comment by gregvanl** [comment]
This tab stop was added to support accessibility and enable screen readers to read "In this article, there are X sections".
