### ISSUE TITLE
A11y_code.visualstudio.com(CELA-P1)_Visual Studio Code User and Workspace settings_Screen Reader: NVDA is reading "List table" when focus lands on the "Search edit box".

### ISSUE THREAD

**Issue by Chandan5555** [microsoft/vscode-docs#2655]
Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
**Environment Details:**
**URL**:code.visualstudio.com/docs/getstarted/settings
**Browser**:Chrome 74.0.3729.131
**Screen Reader**: NVDA

**NOTE:** 
This issue is present in the below pages in the application.
code.visualstudio.com/docs                                                      
code.visualstudio.com/download                                                  
code.visualstudio.com/docs/supporting/faq
code.visualstudio.com/docs/setup/linux
code.visualstudio.com/docs/getstarted/settings
code.visualstudio.com/docs/python/python-tutorial
code.visualstudio.com/updates/v1_30
code.visualstudio.com/docs/editor/whyvscode
code.visualstudio.com/docs/getstarted/tips-and-tricks
code.visualstudio.com/updates/v1_29
code.visualstudio.com/docs/editor/integrated-terminal
code.visualstudio.com/docs/editor/debugging
code.visualstudio.com/docs/editor/versioncontrol

**Repro Steps:**
1.Hit the URL:code.visualstudio.com/docs/getstarted/settings
2.Swith on the NVDA and tab till the "Search edit box" control
3.Verify if the NVDA is reading the "Search edit box" control properly or not.

**Actual Result:**
NVDA is reading "List table" when focus lands on the search edit box.

**Expected Result:**
NVDA should not read "List table" when the focus lands on the search edit box.

**User Impact:**
Screen reader users will find difficulties while navigating the controls if the screen reader will not read the proper information about the "Search edit box"

**Mas Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by Chandan5555** [comment]
![Bug_2655_nvda is reading list table](https://user-images.githubusercontent.com/50437119/57452021-60fbb600-7280-11e9-96b7-f6e4d5d7fd14.png)

**Comment by Chandan5555** [comment]
![bug_2655_NVDA is reading list table for search](https://user-images.githubusercontent.com/50437119/57602729-986aab00-757d-11e9-9813-940ea3427d64.png)

**Comment by Chandan5555** [comment]
![Bug_2655_nvda issue](https://user-images.githubusercontent.com/50437119/57606906-8beb5000-7587-11e9-85b0-073605473aad.png)

**Comment by auchenberg** [comment]
I can't reproduce this with VoiceOver, so this seems to be NVDA specific. Gotta try to get a Windows box going.

**Comment by gregvanl** [comment]
Not sure why the search button, search form, and download button are contained in a list but that seems to be what NVDA is calling out. Maybe we can try another arrangement or silence the reader?

**Comment by fsteffi** [comment]
GitHubTags:#CAITestPass_June’19;
