### ISSUE TITLE
A11y_Code.Visualstudio.Com(CELA-P1)_User Guide Page_Usability:Github Star is given as link,but not appearing as link and Narrator is reading as Github star button link Star on Github.

### ISSUE THREAD

**Issue by Ashwinipola26** [microsoft/vscode-docs#2656]
Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
**Environment Details:**
https://code.visualstudio.com/docs/editor/whyvscode

**Note:**
This issue is present in the below pages in the application.
code.visualstudio.com/docs
code.visualstudio.com/download
code.visualstudio.com/docs/supporting/faq
code.visualstudio.com/docs/setup/linux
code.visualstudio.com/docs/getstarted/settings
code.visualstudio.com/docs/python/python-tutorial
code.visualstudio.com/updates/v1_30
code.visualstudio.com/docs/editor/whyvscode
code.visualstudio.com/docs/getstarted/tips-and-tricks
code.visualstudio.com/updates/v1_29
code.visualstudio.com/docs/editor/integrated-terminal
code.visualstudio.com/docs/editor/debugging
code.visualstudio.com/docs/editor/versioncontrol
​
**Version:​**
Microsoft Edge 44.18362.1.0
Version 74.0.3729.131 (Official Build) (64-bit)
Narrator
​
**Repro Steps:​**
1)Hit the URL - code.visualstudio.com/docs/editor/whyvscode
2)Tab till GitHub Star and check whether it is appearing as link or not.
3)Start Narrator/NVDA to check whether Screen reader is reading the correct role assigned to it or not 
​
**Actual Result:​**
GitHub Star is given as link, but not appearing as link and Narrator is reading as GitHub star button link Star on GitHub.

**Expected Result:​**
GitHub star should be appearing as link to the user and also Narrator should read the role as link instead of both button and link in order to avoid confusion to the user.

**User Impact:​**
Keyboard users will face difficulty if the role is not matching with the appearance and also if the narrator is reading two roles ,users will get confused what action need to be performed.

**Comment by Ashwinipola26** [comment]
[bug_2656_GitHub Star is given as link.pptx](https://github.com/microsoft/vscode-docs/files/3162025/bug_2656_GitHub.Star.is.given.as.link.pptx)

**Comment by Ashwinipola26** [comment]
**Environment Details:**
https://code.visualstudio.com/docs/editor/whyvscode
​
**Version:​**
Microsoft Edge 44.18362.1.0
Version 74.0.3729.131 (Official Build) (64-bit)
​
**Repro Steps:​**
1)Hit the URL - code.visualstudio.com/docs/editor/whyvscode
2)Tab till GitHub Star and check whether it is appearing as link or not.
3)Start Narrator/NVDA to check whether Screen reader is reading the correct role assigned to it or not
​
**Actual Result:​**
GitHub Star is given as link, but not appearing as link and Narrator is reading as GitHub star button link Star on GitHub.

**Expected Result:​**
GitHub star should be appearing as link to the user and also Narrator should read the role as link instead of both button and link in order to avoid confusion to the user.

**User Impact:​**
Keyboard users will face difficulty if the role is not matching with the appearance and also if the narrator is reading two roles ,users will get confused what action need to be performed.

**Comment by Ashwinipola26** [comment]
**Environment Details:**
https://code.visualstudio.com/docs/editor/whyvscode
​
**Version:​**
Microsoft Edge 44.18362.1.0
Version 74.0.3729.131 (Official Build) (64-bit)
​
**Repro Steps:​**
1)Hit the URL - code.visualstudio.com/docs/editor/whyvscode
2)Tab till GitHub Star and check whether it is appearing as link or not.
3)Start Narrator/NVDA to check whether Screen reader is reading the correct role assigned to it or not
​
**Actual Result:​**
GitHub Star is given as link, but not appearing as link and Narrator is reading as GitHub star button link Star on GitHub.

**Expected Result:​**
GitHub star should be appearing as link to the user and also Narrator should read the role as link instead of both button and link in order to avoid confusion to the user.

**User Impact:​**
Keyboard users will face difficulty if the role is not matching with the appearance and also if the narrator is reading two roles ,users will get confused what action need to be performed.

**Comment by Ashwinipola26** [comment]
Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
Environment Details:
https://code.visualstudio.com/docs/editor/whyvscode
Note:
This issue is present in the below pages in the application.
code.visualstudio.com/docs
code.visualstudio.com/download
code.visualstudio.com/docs/supporting/faq
code.visualstudio.com/docs/setup/linux
code.visualstudio.com/docs/getstarted/settings
code.visualstudio.com/docs/python/python-tutorial
code.visualstudio.com/updates/v1_30
code.visualstudio.com/docs/editor/whyvscode
code.visualstudio.com/docs/getstarted/tips-and-tricks
code.visualstudio.com/updates/v1_29
code.visualstudio.com/docs/editor/integrated-terminal
code.visualstudio.com/docs/editor/debugging
code.visualstudio.com/docs/editor/versioncontrol
​
Version:​
Microsoft Edge 44.18362.1.0
Version 74.0.3729.131 (Official Build) (64-bit)
Narrator
​
Repro Steps:​
1)Hit the URL - code.visualstudio.com/docs/editor/whyvscode
2)Tab till GitHub Star and check whether it is appearing as link or not.
3)Start Narrator/NVDA to check whether Screen reader is reading the correct role assigned to it or not
​
Actual Result:​
GitHub Star is given as link, but not appearing as link and Narrator is reading as GitHub star button link Star on GitHub.
Expected Result:​
GitHub star should be appearing as link to the user and also Narrator should read the role as link instead of both button and link in order to avoid confusion to the user.
User Impact:​
Keyboard users will face difficulty if the role is not matching with the appearance and also if the narrator is reading two roles ,users will get confused what action need to be performed.

**Comment by Ashutoshsahoo164** [comment]
GitHubTags: #P1_A11y_code.visualstudio.com_Apr2020;
