### ISSUE TITLE
A11y_code.code.visualstudio.com(CELA-P1)_Visual Studio Code User and Workspace settings_Screen Reader: Narrator/NVDA is not reading a proper role of "Get Started" control.

### ISSUE THREAD

**Issue by Chandan5555** [microsoft/vscode-docs#2658]
Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
**Environment Details:**
**URL**:code.visualstudio.com/docs/getstarted/settings
**Browser**: Microsoft Edge 44.18362.1.0, Chrome  74.0.3729.131 
**Screen Reader**: Narrator

**NOTE:**
This issue is present in the below pages in the application.
code.visualstudio.com/docs                                                      
code.visualstudio.com/download                                                  
code.visualstudio.com/docs/supporting/faq
code.visualstudio.com/docs/setup/linux
code.visualstudio.com/docs/getstarted/settings
code.visualstudio.com/docs/python/python-tutorial
code.visualstudio.com/updates/v1_30
code.visualstudio.com/docs/editor/whyvscode
code.visualstudio.com/docs/getstarted/tips-and-tricks
code.visualstudio.com/updates/v1_29
code.visualstudio.com/docs/editor/integrated-terminal
code.visualstudio.com/docs/editor/debugging
code.visualstudio.com/docs/editor/versioncontrol

**Repro steps:**
1.Hit the URL:code.visualstudio.com/docs/getstarted/settings
2.Switch on Narrator and tab till the "Get Started" dropdown control
3.Verify whether the screen reader is reading the proper role of "Get Started" control

**Actual result:**
Narrator is not reading a proper role of "Get Started" control.

**Expected result:**
Screen reader should read a proper role about the "Get Started" control as it is a "dropdown" or" combo box"

**User impact:**
Screen reader user will not get proper information about which type of control he is navigating if there is no proper role for the control.

**MAS Reference**:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by Chandan5555** [comment]
[Bug_2658_role for get started is not correct.pptx](https://github.com/microsoft/vscode-docs/files/3162045/Bug_2658_role.for.get.started.is.not.correct.pptx)

**Comment by Chandan5555** [comment]
![bug 2658_nvda issue_no proper rol for Get started link](https://user-images.githubusercontent.com/50437119/57599455-55580a00-7574-11e9-881b-6f175d13dfbf.png)

**Comment by Chandan5555** [comment]
![Bug_2658_issue through out the application](https://user-images.githubusercontent.com/50437119/57600911-b7b30980-7578-11e9-8ede-6fe70b074b1f.png)

**Comment by auchenberg** [comment]
The solution here seems to mark the control in the left sidebar as a "accordion" as the "getting started" link functions as a toggle to hide/show the accordion panel 

https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

https://www.hassellinclusion.com/blog/accessible-accordion-pattern/

**Comment by gregvanl** [comment]
I tried adding role="drop down" to portaldocs-nav-template.html in various elements but never got Narrator to call out the role.

**Comment by gregvanl** [comment]
Going with a simple `aria-label="{$ area.title $} drop down"` approach

**Comment by fsteffi** [comment]
GitHubTags:#CAITestPass_June’19;
