### ISSUE TITLE
Provide heading anchors for <h3>s too

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#266]
I'd like to link to a particular section of the Linux FAQ but there is no heading anchor https://code.visualstudio.com/docs/supporting/faq#_linux-faq

**Comment by Tyriar** [comment]
Ping @waderyan, it's sucks not being able to link people to the terminal section in the release notes. I have to link https://code.visualstudio.com/updates/May_2016#_workbench currently

**Comment by waderyan** [comment]
Create an issue in vscode-website. https://github.com/Microsoft/vscode-website/issues/400

**Comment by gregvanl** [comment]
Microsoft/vscode-docs@f301c81#diff-dc364d630c02883b58fd561853a77f7e put ids on h3 headers to support h3 relative links for in-product release notes. 
This issue is now dependent on  Microsoft/vscode-website#400
