### ISSUE TITLE
Update Python docs to refer to things as "testing" and not "unit testing"

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#2663]
With #2621 done, the next step is to update the docs to not refer to all test-related things as "unit tests", e.g. the "Unit Testing" section should be named "Testing".

**Comment by JoshuaPartlow** [comment]
@brettcannon Should anything still be referred to as Unit Testing? Some content within the current Unit Testing topic for example, is about describing what a Unit Test is.

**Comment by brettcannon** [comment]
@JoshuaPartlow probably not. While the explanation of what a unit test is is nice, the testing support in the extension covers more that unit testing, so it seems to be scoped a bit too small to warrant keeping up-to-date.

**Comment by gregvanl** [comment]
@JoshuaPartlow updated terminology with https://github.com/microsoft/vscode-docs/commit/6372d4ad424f739e1c12878c6d60d59971882167
@gregvanl renamed python/unit-testing.md to python/testing.md with https://github.com/microsoft/vscode-docs/commit/6d52858073c305e8d133cd5ff91498fdbdbe3ada

**Comment by gregvanl** [comment]
Redirects added to the website
