### ISSUE TITLE
A11y_Code.Visualstudio.Com(CELA-P1)_Getting Started_Screen Reader:Narrator is reading as two form landmarks and two navigation landmarks without the appropriate name to differentiate between two landmarks

### ISSUE THREAD

**Issue by Ashwinipola26** [microsoft/vscode-docs#2666]
Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
**Environment Details:**
https://code.visualstudio.com/docs

**Note:**
This issue is present in the below pages in the application.
code.visualstudio.com/docs
code.visualstudio.com/docs/supporting/faq
code.visualstudio.com/docs/setup/linux
code.visualstudio.com/docs/getstarted/settings
code.visualstudio.com/docs/python/python-tutorial
code.visualstudio.com/updates/v1_30
code.visualstudio.com/docs/editor/whyvscode
code.visualstudio.com/docs/getstarted/tips-and-tricks
code.visualstudio.com/updates/v1_29
code.visualstudio.com/docs/editor/integrated-terminal
code.visualstudio.com/docs/editor/debugging
code.visualstudio.com/docs/editor/versioncontrol

**Version:​**
Microsoft Edge 44.18362.1.0
Version 74.0.3729.131 (Official Build) (64-bit)
Narrator
​
**Repro Steps:​**
1)Hit the URL - https://code.visualstudio.com/docs
2)Start Narrator  and press D to check whether Narrator is reading the Navigation landmarks with proper names.

**Actual Result:​**
Narrator is reading as two form landmarks and two navigation landmarks without the appropriate name to differentiate between two landmarks

**Expected Result:​**
Narrator should differentiate between landmarks to the user with appropriate names added to it.

**User Impact:​**
Screen reader users will face difficulty in understanding what landmark is for what purpose.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by Ashwinipola26** [comment]
[Different names for different landmarks-first video.pptx](https://github.com/microsoft/vscode-docs/files/3165004/Different.names.for.different.landmarks-first.video.pptx)
[Different names for different landmarks-second video.pptx](https://github.com/microsoft/vscode-docs/files/3165005/Different.names.for.different.landmarks-second.video.pptx)

**Comment by Ashwinipola26** [comment]
[2666_bug_Different names for different landmarks-first video.pptx](https://github.com/microsoft/vscode-docs/files/3165012/2666_bug_Different.names.for.different.landmarks-first.video.pptx)
[2666_bug_Different names for different landmarks-second video.pptx](https://github.com/microsoft/vscode-docs/files/3165015/2666_bug_Different.names.for.different.landmarks-second.video.pptx)

**Comment by Ashwinipola26** [comment]
**Environment Details:**
https://code.visualstudio.com/docs

**Version:​**
Microsoft Edge 44.18362.1.0
Version 74.0.3729.131 (Official Build) (64-bit)
​
**Repro Steps:​**
1)Hit the URL - https://code.visualstudio.com/docs
2)Start Narrator and press D to check whether Narrator is reading the Navigation landmarks with proper names.

**Actual Result:​**
Narrator is reading as two form landmarks and two navigation landmarks without the appropriate name to differentiate between two landmarks

**Expected Result:​**
Narrator should differentiate between landmarks to the user with appropriate names added to it.

**User Impact:​**
Screen reader users will face difficulty in understanding what landmark is for what purpose.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by Ashwinipola26** [comment]
[2666_bug_Different names for different landmarks-first video.pptx](https://github.com/microsoft/vscode-docs/files/3165065/2666_bug_Different.names.for.different.landmarks-first.video.pptx)
[2666_bug_Different names for different landmarks-second video.pptx](https://github.com/microsoft/vscode-docs/files/3165067/2666_bug_Different.names.for.different.landmarks-second.video.pptx)

**Comment by gregvanl** [comment]
@Ashwinipola26 Fixed

**Comment by fsteffi** [comment]
GitHubTags:#CAITestPass_June’19;
