### ISSUE TITLE
A11y_Code.Visualstudio.Com(CELA-P1)_ VS Code tips and tricks_Screenreader: Narrator is reading list items 1 and 4 in the 'Find extensions' section 2 times in scan mode

### ISSUE THREAD

**Issue by saiprasanna93** [microsoft/vscode-docs#2669]
**Environment Details:**
URL: code.visualstudio.com/docs/getstarted/tips-and-tricks
Browser Details: Microsoft Edge 44.17763.1.0 (Official Build) (64-bit)

**Note:**
Similar issue is observed in different sections in the URL:code.visualstudio.com/updates/v1_29 
mentioned below
Narrator is reading all list items 2 times in 'Workbench navigation commands' section and Narrator is reading all list items 2 times in 'Notable Fixes' section and also Narrator is reading list item 1 in 'Contributions to inno-updater' section 2 times

**Repro Steps:​**
1)Hit URL:  code.visualstudio.com/docs/getstarted/tips-and-tricks and log in with appropriate credentials.​
2)Tab till 'Extensions' section in the page
3)Start the Narrator
4)Turn on scan mode
4)Verify how narrator is reading the list items 1 and 4 in the 'Find extensions' section in scan mode

**Actual Result:**  
Narrator is reading list items 1 and 4 in the 'Find extensions' section 2 times in scan mode

**Expected result:** 
Narrator shouldn't read list items 1 and 4 in the 'Find extensions' section 2 times in scan mode

**User Impact:** 
Screen reader users will find difficulties while using this application when Narrator is reading list items 1 and 4 in the 'Find extensions' section 2 times in scan mode

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by saiprasanna93** [comment]
[Bug_2669_Narrator is reading list items 1 and 4 in the 'Find extensions' section 2 times in scan mode.pptx](https://github.com/microsoft/vscode-docs/files/3165357/Bug_2669_Narrator.is.reading.list.items.1.and.4.in.the.Find.extensions.section.2.times.in.scan.mode.pptx)

**Comment by saiprasanna93** [comment]
![Bug_2669_Narrator is reading  list item 1 in 'Contributions to inno-updater' section 2 times in scan mode](https://user-images.githubusercontent.com/50437422/57511631-56482c00-7327-11e9-880c-9ffeeac4f04d.png)

**Comment by saiprasanna93** [comment]
![Bug_2669_Narrator is reading all list items 2 times in 'Notable Fixes' section in scan mode](https://user-images.githubusercontent.com/50437422/57511708-8099e980-7327-11e9-9046-c194e0d88dcf.png)

**Comment by saiprasanna93** [comment]
![Bug_2669_Narrator is reading all list items 2 times in 'Workbench navigation commands' section in scan mode](https://user-images.githubusercontent.com/50437422/57511729-8d1e4200-7327-11e9-9d42-a81b44676c3f.png)

**Comment by gregvanl** [comment]
@saiprasanna93 I haven't been able to reproduce this issue. For me list items are only read once in scan mode. Could this be an issue with Narrator or Narrator configuration on the test machine?

**Comment by gregvanl** [comment]
Closing per Alexandria Reynold's recommendation.

**Comment by saiprasanna93** [comment]
@gregvanl  
Regressed this issue in the below URL and found the issue is still repro and not fixed. Hence reopening this issue.
https://code.visualstudio.com/docs/getstarted/tips-and-tricks

**Comment by saiprasanna93** [comment]
[Bug_2669_Issue not resolved Narrator is reading list items 1 and 4 in the 'Find extensions' section 2 times in scan mode.pptx](https://github.com/microsoft/vscode-docs/files/3235679/Bug_2669_Issue.not.resolved.Narrator.is.reading.list.items.1.and.4.in.the.Find.extensions.section.2.times.in.scan.mode.pptx)

**Comment by gregvanl** [comment]
@saiprasanna93 Still can't repro the issue. I'm using the default Narrator settings. Could you have some non-default settings enabled?

**Comment by saiprasanna93** [comment]
@gregvanl ..I haven't changed any Narrator settings and the issue is still repro and not fixed can you please add the video recording from your end for this issue which is no repro at your end.

**Comment by gregvanl** [comment]
@saiprasanna93 I can repro this now if I use scan mode with the P paragraph navigation. It does not repro if I go through the list with scan mode up/down keys. I think this is an issue with Narrator. I don't hear any problems when I move through the list with NVDA.

**Comment by gregvanl** [comment]
I can repro the issue with a baby HTML page:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <ol>
        <li>Hello <a href="">Marketplace</a></li>
        <li>Hello <a href="">Marketplace</a>.</li>
        <li>Hello <a href="">Marketplace</a> .</li>
    </ol>
</body>

</html>
```

The second item, which has a period directly after the link, is twice with P paragraph scan mode. The first link, without a period, and the third, with a space before the period, are not read twice.

**Comment by gregvanl** [comment]
This is a Narrator issue and I'm following up to see about entering a Narrator bug.

**Comment by gregvanl** [comment]
Here's the Narrator issue https://microsoft.visualstudio.com/OS/_workitems/edit/22125218

**Comment by gregvanl** [comment]
The Narrator issue was resolved as a Duplicate so this is a known issue.

**Comment by saiprasanna93** [comment]
As per the Screen Reader External Bug Process(https://microsoft.sharepoint.com/teams/ceacc/SitePages/External%20Bug%20Process.aspx), if one of the free screen readers is working fine we can close the bug as NVDA is reading properly the list items 1 and 4 in the 'Find extensions' section only once in scan mode and added attachment for reference

**Comment by saiprasanna93** [comment]
![Bug_2669_NVDA is reading properly the list items 1 and 4 in the 'Find extensions' section only once in scan mode](https://user-images.githubusercontent.com/50437422/59425722-1f68a880-8df4-11e9-9ef6-deaa09040af2.png)

**Comment by BhanuPrakashGit** [comment]
GithubTag:#A11ySev2;

**Comment by Roopesh-T** [comment]
#Closed;

**Comment by fsteffi** [comment]
GitHubTags:#CAITestPass_June’19;
