### ISSUE TITLE
FAQ on license changes

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#267]
We should do a FAQ on the change to the licenses.

For Stable 1.0, these are the differences:

- The TIME-SENSITIVE SOFTWARE clause has been removed and the product will no longer stop running on 31/12/2016 (day/month/year). 

- The PRE-RELEASE SOFTWARE qualification has been removed.

- The license no longer prohibits you from opting out of data collection. You can turn of crash reporting, automatic updates, and usage reporting (insert links)

- The license clarifies that extensions downloaded are covered by the license provided by the extension author, not the VS Code license.

Stable License: https://code.visualstudio.com/license?lang= where lang is the two or three character language code ('en', 'de', 'fr', 'zh-cn', 'zh-tw', 'ko', 'ja', 'ru', 'es', 'it').

For Insiders, these are the changes:

- The TIME-SENSITIVE SOFTWARE clause which indicated that the software will stop running on 31/12/2016 (day/month/year) has been changed to a TERM clause which specifies the license agreement is for 90 days.

- The license clarifies that extensions downloaded are covered by the license provided by the extension author, not the VS Code license (same as stable).

Insiders License: https://code.visualstudio.com/license/insiders, there are no localized Insider licenses.

**Comment by gregvanl** [comment]
http://code.visualstudio.com/Updates#_licensing-changes
