### ISSUE TITLE
Document the support for JS Doc 

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-docs#2672]
Suggest to document the support the JS extension provides for entering JSDoc, i.e., 
entering '/**'

**Comment by carlos-menezes** [comment]
https://code.visualstudio.com/docs/languages/javascript#_jsdoc-support

**Comment by gregvanl** [comment]
It would be good to also add mention in the Working with JavaScript topic.

**Comment by gregvanl** [comment]
JSDoc support is mentioned in https://code.visualstudio.com/docs/nodejs/working-with-javascript#_intellisense
