### ISSUE TITLE
Adopt CI instructions also for JavaScript extensions

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-docs#2673]
https://code.visualstudio.com/api/working-with-extensions/continuous-integration is targeted for extensions written in TypeScript, e.g. it references the `compile` script only present in TypeScript extensions.

It would be good toexplain what has to be checked for extensions written in JavaScript.
https://github.com/microsoft/vscode-generator-code/issues/169 asks for info on what

**Comment by gregvanl** [comment]
Closing old issue with no upvotes
