### ISSUE TITLE
Add Step 5 to Getting Started with Python in VS Code (Install and Use Packages Section)

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#2681]
In [this](https://code.visualstudio.com/docs/python/python-tutorial#_install-and-use-packages) section, we should add a step 5 that reads:

5. To deactivate the virtual environment, simply type `deactivate` in the terminal window.

**Comment by JoshuaPartlow** [comment]
Updated. https://github.com/microsoft/vscode-docs/commit/cc9a42c7a2dc8de28d8e15cc1babf115c877a0e1
