### ISSUE TITLE
System Requirements - `.NET` Framework

### ISSUE THREAD

**Issue by RoyiAvital** [microsoft/vscode-docs#2688]
Hello,

In the [Requirements page](https://code.visualstudio.com/docs/supporting/requirements) it is written that VS Code requires `.NET` framework on Windows.

Is there a reason for this?
As VS Code is Electron based I don't see how could it require `.NET`.

Is written for the case the user wants to use it for `C` / `C++` / `C#` development on windows including Debugging?

**Comment by gregvanl** [comment]
Hi @RoyiAvital Thank you for checking on us. .NET is required on Windows and we call this out since some users on Windows 7 didn't have .NET installed. I forget the exact dependency but I believe it was related to a native file watcher module included in VS Code.

**Comment by RoyiAvital** [comment]
Could we remove this dependency?

**Comment by gregvanl** [comment]
Are you having an issue? .NET ships with recent versions of Windows and so shouldn't require any manual install. We included the requirement to help folks on Windows 7.
