### ISSUE TITLE
Django Tutorial in Visual Studio Code

### ISSUE THREAD

**Issue by mstrass** [microsoft/vscode-docs#2696]
In the article: "Django Tutorial in Visual Studio Code"

Section: Use the database through the models 
Sub Section: #15

home_list_view = views.HomeListView.as_view(
    _queryset=LogMessage.objects.order_by("-log_date")[:5],  # :5 

An error appears: Class 'LogMessage' has no 'object' member
![image](https://user-images.githubusercontent.com/48228083/58296201-92e44080-7d87-11e9-8c9f-39acfd48b438.png)

![image](https://user-images.githubusercontent.com/48228083/58296213-a2fc2000-7d87-11e9-990f-d62142b6efdc.png)

**Comment by gregvanl** [comment]
I believe this is a PyLint warning that can be safely ignored. The tutorial assumes that you don't have Pylint enabled. 

![image](https://user-images.githubusercontent.com/12818376/58738398-71540c00-83ba-11e9-9ad1-9ac576ad0e7d.png)


You can disable all Python linting with the setting Python > Linting: Enabled or just Pylint with Python > Linting: Pylint Enabled.
You can also install the pylint-django plug-in and configure pylint to use it through

```json
"python.linting.pylintArgs": ["--load-plugins", "pylint_django"]
```
Note that with pylint-django configured you may now see other warnings.

See https://code.visualstudio.com/docs/python/linting#_commandline-arguments-and-configuration-files.
