### ISSUE TITLE
ext install: gettomg ECONNREFUSED error

### ISSUE THREAD

**Issue by cheers00** [Microsoft/vscode-docs#270]
I am getting the following error when run `ext install PowerShell`

Error
`connect ECONNREFUSED 10.7.211.16:80
`

**Comment by gregvanl** [comment]
You should try setting up a [proxy explicitly](https://code.visualstudio.com/docs/supporting/faq#_proxy-server-support).
There is also an open issue https://github.com/Microsoft/vscode/issues/4827 where VS Code will detect this issue and prompt with this suggestion.
