### ISSUE TITLE
Uneccesary <p></p> tags in Django Tutorial

### ISSUE THREAD

**Issue by waderoberts123** [microsoft/vscode-docs#2702]
I was looking through the Django Tutorial as I am currently thinking of switching to using VS Code instead of Pycharm, and I noticed in [this section](https://github.com/microsoft/vscode-docs/blob/63214cd2616f9edca20adefe4593859617720b78/docs/python/tutorial-django.md#use-the-code-snippet-to-add-pages) that it instructs users to enter `<p>Home page for the Visual Studio Code Django tutorial.</p>` in the `{% block title %}` section, but the `<p><\p>` tags are not necessary because the `{% block title %}` section is already included inside of the `<title></title>` tags in the template. Doing as instructed, the `<p></p>` tags are rendered in the tab header as plain text.

**Comment by endormi** [comment]
I'm working on an quick fix. Making a PR request shortly.

**Comment by gregvanl** [comment]
Hi @waderoberts123 According to the tutorial, the snippet `<p>Home page for the Visual Studio Code Django tutorial.</p>` should go in the "content" block, not the "title" block. 

![image](https://user-images.githubusercontent.com/12818376/58735956-0520da80-83b1-11e9-9319-a39008a8b47e.png)

Only the "Home" string goes in the title block:

```html
{% extends "hello/layout.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}
<p>Home page for the Visual Studio Code Django tutorial.</p>
{% endblock %}
```
While the <p> tags are not strictly necessary for the content block they do add a new line to the output.

**Comment by lankjan007** [comment]
Hi gregvanl,

I have just arrived to this part of the python and Django tutorial and I triple checked my code but I can't seem to be able to render the following page 

![image](https://user-images.githubusercontent.com/13496263/79750304-02084300-8311-11ea-9ae2-9ec93c19d991.png)

please can you confirm the url I should be entering into the webpage is it 127.0.0.1:8000/hello/VSCode?

Thank you in advance for your help,

**Comment by JoshuaPartlow** [comment]
Hi @lankjan007 - The tutorial should use localhost on port 8000 throughout. What output are you seeing in the terminal when you run Django?

**Comment by lankjan007** [comment]
Hi Joshua, thank you for the reply,

I am getting a Page not found (404) output when entering the following in the browser,
127.0.0.1:8000
127.0.0.1:8000/home

When entering the below, I get a (Hello, there name/VSCode! It's Tuesday, 21 April, 2020 at 14:26:31.) in the browser
127.0.0.1:8000/hello/name
127.0.0.1:8000/hello/VSCode

Hope that's helpful, look forward to your reply

**Comment by JoshuaPartlow** [comment]
Hi @lankjan007 - For the 404, my first thought would be to check your urls.py file and make sure you're still defining a route for "" and home. For the issue rendering that final step, you might try comparing your files against those in the completed version of the sample on [GitHub](https://github.com/Microsoft/python-sample-vscode-django-tutorial).

**Comment by lankjan007** [comment]
Hi,

Yes, looks like i will have to was just wrecking my brain all day today over this issue. I redo the tut and also refer to the completed code,

Thank you very much for your advice

👍🏼

**Comment by JoshuaPartlow** [comment]
Happy to help. If you're still having problems after checking, feel free to open an issue or comment here again.

**Comment by lankjan007** [comment]
Hi Josh,

managed to fix that issue, i now have another issue come up.
Class 'LogMessage' has no 'objects' member appearing in the urls.py code | home_list_view function queryset statement, any ideas?

Appreciate the help, newbie here 🤫

**Comment by JoshuaPartlow** [comment]
Hi @lankjan007 - Where are you seeing that message? Is the django app actually crashing when you run it? I haven't seen that message before, and I'm not seeing it when I run the tutorial from GitHub.

**Comment by lankjan007** [comment]
Hi Josh,

I get this error from the problems tab as the below,

https://photos.app.goo.gl/3CXNjc34Qk8xX7TL9

After creating the home_list_view function

Thanks!

**Comment by JoshuaPartlow** [comment]
Hi @lankjan007 - I believe that message is actually a warning from pylint that is a false positive. Pylint isn't aware of some aspects of Django. I think everything should still run ok. For a little more awareness of django with linting, there's the pylint-django plugin.

**Comment by lankjan007** [comment]
Best day ever 💪💯

Finally, got it working after installing django lint plugin and reviewing my code again,

Thank you so much Josh (topman) for all your advice, this is what keeps me interested in coding and pursuing my goals,

Cheers 🍺

**Comment by JoshuaPartlow** [comment]
Excellent @lankjan007 glad to hear you got it working! If you have any further problems working through our tutorials or feedback on them, feel free to open an issue.
