### ISSUE TITLE
I can't seem to get the VScode on my Linux7.5 system to locate the correct interpreter. I have tried to change the python.Path  to where i believe th einterpreter for pythin 3.6 lives but it does not klet it use that.

### ISSUE THREAD

**Issue by InterceptorF** [microsoft/vscode-docs#2706]

**Comment by InterceptorF** [comment]
I have tried to change the python.Path  to where i believe the interpreter for python 3.6 lives but it does not use that.

Where does the installation of python3.6 put the interpreter by default?  what would allow VScode to use it

**Comment by gregvanl** [comment]
The setting for the VS Code Python extension is `python.pythonPath` not `python.Path`.

Python binaries are usually under /usr/local/bin/python by default on Linux.

From a bash terminal, you can type `whereis python` to check the location.
