### ISSUE TITLE
jsconfig and module resolution default

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-docs#2710]
Hi,

According to https://code.visualstudio.com/docs/languages/jsconfig the examples show that `"target": "es6"` should/could be used. Normally one would probably want es6(es2015)/es2016/es2017.

I find two issues here:

1. The documentation shows there is a es2018 (check the end in the above link), but according to https://www.typescriptlang.org/docs/handbook/compiler-options.html this is not a valid value. It might be that the typescriptlang.org is outdated.
2. But more importantly, setting e.g. `"target": "es6"` implies that `--moduleResolution: "Classic`. If you check https://www.typescriptlang.org/docs/handbook/compiler-options.html and the `--moduleResolution` the defaults are:

```json
module === "AMD" or "System" or "ES6" ? "Classic" : "Node"
```

For `--module` the defaults are:

```json
target === "ES3" or "ES5" ? "CommonJS" : "ES6"
```

This means with target set to e.g. es6, module will be es6 which means moduleResolution will be Classic. This is a legacy solution so I assume it should be hinted in the jsconfig documentation that one should set moduleResolution to Node?

(A change here might also need to be done in https://code.visualstudio.com/docs/nodejs/working-with-javascript)

**Comment by gregvanl** [comment]
1. es2018 is a valid value
2. Thanks for pointing this out. We've added "module": "commonjs" explicitly to the jsconfig.json examples.

**Comment by gregvanl** [comment]
@thernstig Thanks for keeping with this. I've added mention of moduleResolution to the table as well as a link to the TypeScript compilerOptions doc. https://github.com/microsoft/vscode-docs/commit/873f8adcfc0514f412124c22eb57c79b278c7485
I'm leaving our jsconfig.json examples with just target and module as that if how we set our generated jsconfig.json with the extension generator.
