### ISSUE TITLE
Extensions Testing: mention running tests from within VSCode too

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docs#2714]
I am looking at https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/testing-extension.md and it does not seem to mention how to actually run tests within VSCode which is the preferred way of running tests because of debugging support. The CLI script should only be useful in CI environments mostly.

**Comment by octref** [comment]
There's a video on the debugging section (hidden on GitHub). See the `video` tag here: https://raw.githubusercontent.com/microsoft/vscode-docs/vnext/api/working-with-extensions/testing-extension.md.

**Comment by octref** [comment]
I think you missed the video (as it's a `<video>` tag and not shown in GH). Debugging in VS Code has the caveat of `"type": "extensionHost"` causing the test to be run with globally installed VS Code.
