### ISSUE TITLE
Unclear theme color customization section (settings/properties)

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode-docs#2719]
The docs doesn't seem very clear about what settings properties belong to, in [theme color customization](https://code.visualstudio.com/api/references/theme-color#editor-colors) section: `editor.tokenColorCustomizations` or `workbench.colorCustomizations`?

https://github.com/microsoft/vscode/issues/74610

**Comment by thmeyer-msft** [comment]
Hey inward, 

did you had a look on [https://code.visualstudio.com/docs/getstarted/themes](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme) ?

To set the colors of VS Code UI elements such as list & trees (File Explorer, suggestions widget), diff editor, Activity Bar, notifications, scroll bar, split view, buttons and more, use `workbench.colorCustomizations`

To tune the editor's syntax highlighting colors, use `editor.tokenColorCustomizations` in your user settings `settings.json` file

Use `workbench.colorCustomizations` to modify the Theme outside the Editor (e.g. menu bar) and `editor.tokenColorCustomizations` for inside the Text window (e.g. Font-Color for Comments ...) 

Best regards, 
Thomas

**Comment by inwardmovement** [comment]
For me it was not easy to guess that "editor background color" belonged to `workbench.colorCustomizations` and not to `editor.tokenColorCustomizations`, but thanks anyway!
