### ISSUE TITLE
Small nit in JS docs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#272]
_From @SteveALee on April 15, 2016 13:40_

on https://code.visualstudio.com/docs/languages/javascript it says

..." all you need is that the typings folder is a sibling or child of the jsconfig.json file to get IntelliSense"

files do NOT have children, only folders. Makes it a bit difficult to parse.

_Copied from original issue: Microsoft/vscode#5341_

**Comment by gregvanl** [comment]
Fixed by https://github.com/Microsoft/vscode-docs/commit/007ec7d2c7d3a43ddca3bd9313efddef5db11be3
