### ISSUE TITLE
C++ configuration is not working.

### ISSUE THREAD

**Issue by munoas** [microsoft/vscode-docs#2724]
Hello, I am new in visual studio code, and currently trying to code in here. i have follow the steps given from https://code.visualstudio.com/docs/cpp/config-msvc , but some instructions are not well clear to me. 

1. Start VS Code from the Developer Command Prompt
i have open the developer prompt , and try to copy it out from the given code in the instruction but it does not work for me, so i try it another way by putting the directory file together to create the file and it works. But when i try to use command _code ._ , it only open the VSC without the folder that i just make it before. 

2. i try to immitate the code that they give for making the _c_ccc_properties.json, launch.json, tasks.json_ eventhough when using the command pallette is does`nt show any of the intrstruction given. so i just make new file, with the same name and copy the code and put it at .vscode file in the working space file. 

3. of course when all doesnt seem very well to follow through, error just pop out when i try to run the test code. so, how do i fix this. ?or there is any way that is easy for me to learn how to use vscode for C++ and other languages? i am from sublime user and just trying to use vscode because many said it was the easiest and compact platform for coding and integrating other codes. 

please help me to learn how to use vscode for C++, python, html, css, Js n so on. huhu

**Comment by mikeblome** [comment]
@munoas Sorry to hear you are having trouble! Did you download the Visual Studio Build tools as described in this step: Install the Microsoft C++ (MSVC) compiler toolset? The developer command prompt is not the same as a regular command prompt; it has special environment variables to find the compiler.

**Comment by gregvanl** [comment]
No response from user in 3 days.

**Comment by munoas** [comment]
Sorry for late reply, i will try it.
