### ISSUE TITLE
editor.detectIndentation

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#273]
It might be good to have a section in the [editing evolved](https://code.visualstudio.com/docs/editor/editingevolved) doc on how `editor.tabSize`, `editor.detectIndentation`, and `editor.insertSpaces` all work together. 

Here is my understanding, we should run by Alex and friends to validate:

`editor.detectIndentation` is true by default and it overrides `editor.insertSpaces` and `editor.tabSize` for the file. Here’s why: The most likely scenario when you start editing a file is that you want to use the same formatting that exists in the file already. This is so you don’t start mixing tabs and spaces, as well as the tab size. 

what about `editor.tabSize`?  That value is the default when you have a new file or if we don’t guess 2, 4, 6, or 8 (again, based on my quick scan of the `guessIndentaion` function).

if you always want `"editor.tabSize": 3` (for example) to be used you can turn off `editor.detectIndentation` in your settings file, and every file you open will have tab size set to 3.

**Comment by gregvanl** [comment]
This came up during a review of doc feedback verbatim
