### ISSUE TITLE
Add sentence specifying users can set up a default Python interpreter in user settings

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#2732]
Would it be possible to add a sentence to one paragraph in [this](https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment) section:

'Selecting an interpreter from the list adds an entry for python.pythonPath with the path to the interpreter inside your Workspace Settings. Because the path is part of the workspace settings, the same environment should already be selected whenever you open that workspace.  **If you’d like to set up a default interpreter for your applications, you can add an entry for python.pythonPath inside your User Settings instead (View > Command Palette > Open Settings (JSON) or View > Command Palette > Open User Settings and look for “Python: Python Path”.'**

Or something around that line?

**Comment by JoshuaPartlow** [comment]
Sure @luabud, topic updated and changes merged.
