### ISSUE TITLE
Why cant i code in visual studios?

### ISSUE THREAD

**Issue by BjorneX** [microsoft/vscode-docs#2745]
when i type in commands nothing happens and yes i do click at the run Icon and all of the commands is right but for examle if i were to type import turtle and the wn = turtle.Screen() nothing would happen.. pls someone respond ive been stuck on this for years :(

**Comment by gregvanl** [comment]
Hi @BjorneX Can you provide more details as to which topic on code.visualstudio.com you are having trouble with? Also which language extensions do you have installed?

**Comment by BjorneX** [comment]
Hey :D i use python. whenever i type in commands in the command field then nothing happens. The only code editor i can use is python idle but that doesnt allow mainloop :(

**Comment by gregvanl** [comment]
Hi @BjorneX Have you tried working through the Python tutorials? Start with https://code.visualstudio.com/docs/python/python-tutorial which should help you set up a working Python environment with VS Code and the Python extension.
