### ISSUE TITLE
view as dataframe like in pycharm

### ISSUE THREAD

**Issue by lfjbb** [microsoft/vscode-docs#2748]

**Comment by lfjbb** [comment]
debug a dataframe in vscode is hard

**Comment by gregvanl** [comment]
@brettcannon This looks like a Python extension feature request.

**Comment by brettcannon** [comment]
@gregvanl yep

@lfjbb would you mind opening issue at https://github.com/microsoft/vscode-python/issues? Although do note our [data viewer landed in our April release](https://devblogs.microsoft.com/python/python-in-visual-studio-code-april-2019-release/).
