### ISSUE TITLE
Integrated Terminals crashed

### ISSUE THREAD

**Issue by changmu811** [microsoft/vscode-docs#2754]
The version of the system version of Windows "Pro 1903 (18362.175) Vscode is 1.35.1,
Click Terminal (new terminal) Vscode
Running to turn off all extensions, the previous version was used without the same problem.

**Comment by gregvanl** [comment]
Hi @changmu811 This sounds like a VS Code product issue and not related to the VS Code documentation. For product issues, you can open a bug at https://github.com/microsoft/vscode/issues
