### ISSUE TITLE
Docs for jsconfig options are missing some properties

### ISSUE THREAD

**Issue by alexilyaev** [microsoft/vscode-docs#2755]
Looking at the docs for [jsconfig options](https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options), I don't see some of the properties that are available in the auto-completion, like `jsx` property.

I see there are many more, are they documented somewhere else?

**Comment by mjbvz** [comment]
PRs welcome.

All the properties are documented in intellisense. More detailed descriptions are here: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by alexilyaev** [comment]
@mjbvz Can we just add a link to that page?  
Or should we have a more complete table of options for `jsconfig.json`?

**Comment by gregvanl** [comment]
Added a link with https://github.com/microsoft/vscode-docs/commit/873f8adcfc0514f412124c22eb57c79b278c7485
