### ISSUE TITLE
Include Link to Troubleshooting Steps in Reference Page.

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#2768]
[Here](https://code.visualstudio.com/docs/python/settings-reference) we should add a link to our [troubleshooting page](https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md).

**Comment by JoshuaPartlow** [comment]
@Anapo14 Are you looking to have this linked in the [Language Server section](https://code.visualstudio.com/docs/python/settings-reference#_python-language-server-settings) ?

**Comment by kraigb** [comment]
@Anapo14 As I'm filling in for Josh while he's on leave, can you be more specific where you think we should be linking to troubleshooting?

**Comment by kraigb** [comment]
@Anapo14 Can you answer Josh's question from earlier so we can address this issue?

**Comment by Anapo14** [comment]
Yes! That section seems most appropriate for now!
