### ISSUE TITLE
Webview API debugging

### ISSUE THREAD

**Issue by PedersenThomas** [microsoft/vscode-docs#2770]
[The Webview API documentation](https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews) states that you can open up the developer tools and by clicking on console you can pick the frame, however that didn't work for me.

However what I found instead was the electron repository had the issue electron/electron#2285 which recommended using `$0.openDevTools()` from the console when the element is selected and that worked out for me.

**Comment by mjbvz** [comment]
The webviews contain an iframe. You need to first open the developer tools on the webview (or using the `Open Webview Developer tools` command) and then select the correct iframe inside of that

Let me know if that does not work
