### ISSUE TITLE
Update `python.testing.pyTest*` to `python.testing.pytest*`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-docs#2772]
We have changed the `T` in `python.testing.pytest` to a lower case.
E.g. change the `pyTest` to `pytest` in the following section and others:

<img width="749" alt="Screen Shot 2019-06-20 at 13 53 34" src="https://user-images.githubusercontent.com/1948812/59880830-de781300-9362-11e9-9d1d-e89dbb3ea1a7.png">

See here https://code.visualstudio.com/docs/python/unit-testing#_pytest-configuration-settings

**Comment by JoshuaPartlow** [comment]
Instances should be updated to lower case T with commit [3692a5cd](https://github.com/microsoft/vscode-docs/commit/3692a5cdef4907c93d172bc441b8cdc7009709f2)
