### ISSUE TITLE
Remove references to `"--nothreading"` in Django Debugging

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-docs#2773]
The argument `"--nothreading"` is no longer required when debugging Django Apps.
Please remove references to this argument, see below:
https://code.visualstudio.com/docs/python/tutorial-django#_create-a-debugger-launch-profile

<img width="748" alt="Screen Shot 2019-06-20 at 13 56 33" src="https://user-images.githubusercontent.com/1948812/59880962-3b73c900-9363-11e9-8ce5-5ab2e10cb66a.png">

**Comment by JoshuaPartlow** [comment]
Should be addressed with the following commit : [5195991c5](https://github.com/microsoft/vscode-docs/commit/5195991c55ddefece51f0d6268df0b3005326449)
