### ISSUE TITLE
Call out in release notes that run test task is losing its keybinding?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#278]
https://github.com/Microsoft/vscode/pull/5106 is stealing the command's keybinding away, currently without any replacement. This should probably be called out in docs.

/cc @dbaeumer

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/bae2906bf50fede5b89eb555418ad61ce4f52eb6
