### ISSUE TITLE
[Python] Update arguments to run parallel tests with pytest-xdist

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#2787]
Having ["-n", "4"]  in pytestArgs not working properly in some cases due to a bug. Current workaround is to change ["-n", "4"] to ["-n 4"]. Can we make this minor change in the docs? 

Related: https://github.com/microsoft/vscode-docs/issues/2551

**Comment by gregvanl** [comment]
@luabud PRs welcome. @JoshuaPartlow can help you fork vscode-docs and submit a PR.
https://help.github.com/en/articles/fork-a-repo

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/2d5f49cbe6c63b7ec2cb8bada828a58109130fe8
