### ISSUE TITLE
Comment that pytest-xdist docs are working around a bug

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#2812]
In #2804 the documentation was updated to explain how to run tests in parallel in the Python extension. The documentation does work, but it's working around Microsoft/vscode-python#6293. It might be worth documenting that having a space in the string like the docs have is not how you normally handle that sort of thing and this is because of a bug (e.g. don't do this in other instances where command-line settings can still be specified).

One way to work around this is to document [adding the setting](https://pypi.org/project/pytest-xdist/) in a [pytest.init file](https://docs.pytest.org/en/latest/customize.html#adding-default-options).

/cc @luabud @microsoft/pyvsc

**Comment by luabud** [comment]
We could change item 2 [here](https://code.visualstudio.com/docs/python/unit-testing#_run-tests-in-parallel) to:

"
Next, create a file named ```pytest.ini``` in your project directory and add the content below, specifying the number of CPUs to be used. For example, to set it up for 4 CPUs:

    ```
    [pytest]
    addopts=-n4
    ```
"

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/f2b0dbdadc607b4eb7b82053c10ac13c1621ff5a
