### ISSUE TITLE
Bad transition in API docs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#282]
The expand/collapse events/variables/etc. section in https://code.visualstudio.com/docs/extensionAPI/vscode-api is not smooth on Chrome. Looks like it's to do with margin or padding being in the element being animated.

**Comment by GeorgySerga** [comment]
The website is not opensource, there is no way to fix it.

**Comment by Tyriar** [comment]
@GeorgySerga moved it over there, thanks 👍
