### ISSUE TITLE
clang error c++ on mac in vscode

### ISSUE THREAD

**Issue by gitdudek** [microsoft/vscode-docs#2821]
Hello, i'm trying to use clang to work with c++ in vscode on my mac and followed every step of the tutorial (https://code.visualstudio.com/docs/cpp/config-clang-mac).

When I build the 'helloworld.cpp' file I get the following errors in my console:

`Executing task: clang++ -std=c++17 -stdlib=libc++ helloworld.cpp -o helloworld.out --debug <

clang: error: no such file or directory: 'helloworld.cpp'
clang: error: no input files
The terminal process terminated with exit code: 1`

**Comment by mikeblome** [comment]
@gitdudek sorry to hear you are having problems. I just verified that the exact instructions work for me. Can you see your helloworld.cpp file in Finder in the expected location?

**Comment by gitdudek** [comment]
@mikeblome the '.vscode' directory is hidden but I can see the helloworld.cpp file in my finder as you can see on the screenshot. 
<img width="838" alt="screen" src="https://user-images.githubusercontent.com/52252651/60208674-2b735200-9859-11e9-8bc4-29acd4ceb05a.png">

**Comment by mikeblome** [comment]
@gitdudek thanks for that image! Move helloworld.cpp up one level. Only the .json files should be in the .vscode folder.

**Comment by gitdudek** [comment]
@mikeblome thanks a lot. Now it's working.

**Comment by rmcclain31** [comment]
Found this old thread that helped me with the same problem.  Thank you! 

Do you happen to know what we're supposed to do if we want to put source files into sub-directories?  Is there a way to tell vscode where we've stored .cpp, .lib, .h files?

**Comment by T-RoyGit** [comment]
Me too thanks

**Comment by realironman101** [comment]
If you are using vs code and facing this issue which says clang: error: no such file or directory: 'filename'
clang: error: no input files.[error while running files][1]

I solved this issue by removing the space or replacing the space with *underscore*(_)**in the filename** *.extension* 

Hope this works for you also

  [1]: https://i.stack.imgur.com/Kvk4T.png

**Comment by LilTurkProdigy** [comment]
> If you are using vs code and facing this issue which says clang: error: no such file or directory: 'filename' clang: error: no input files.[error while running files](https://i.stack.imgur.com/Kvk4T.png)
> 
> I solved this issue by removing the space or replacing the space with _underscore_(_)**in the filename** _.extension_
> 
> Hope this works for you also

Thank you so much I've been looking for a solution to this problem I was having

**Comment by Aryan1405** [comment]
my named c files show -
clang: error: no such file or directory: 'Case'
clang: error: no such file or directory: '2'
clang: error: no such file or directory: '2'
clang: error: no input files

all the named files are not working even with the fresh code just because they are named . any tips?

**Comment by Aryan1405** [comment]
> > If you are using vs code and facing this issue which says clang: error: no such file or directory: 'filename' clang: error: no input files.[error while running files](https://i.stack.imgur.com/Kvk4T.png)
> > I solved this issue by removing the space or replacing the space with _underscore_(_)**in the filename** _.extension_
> > Hope this works for you also
> 
> Thank you so much I've been looking for a solution to this problem I was having

now working thnx
