### ISSUE TITLE
Fix shelljs security alert

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#2822]
https://github.com/microsoft/vscode-docs/network/alert/yarn.lock/shelljs/open

**Comment by octref** [comment]
https://github.com/shelljs/shelljs/issues/945#issuecomment-506019725

We control all `$.exec`'s input. There's no user input so it's fine.
It's kinda silly to say "a library to execute shell commands will have arbitrary code execution security problem".

**Comment by Tyriar** [comment]
Oh cool, you can dismiss them 😄
