### ISSUE TITLE
Live editing link for React tutorial is broken

### ISSUE THREAD

**Issue by eloekset** [microsoft/vscode-docs#2838]
This issue is about a link in this paragraph: [Live editing and debugging](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_live-editing-and-debugging)

The link to a blog post about live editing works, but that blog post only links to the webpack documentation, which has moved. It's better to link directly to the correct part of the webpack docs from VSCode docs.

I think maybe this is the part that was previously linked to from the blog post, but I'm not sure: https://webpack.js.org/guides/hot-module-replacement/

**Comment by gregvanl** [comment]
Hi @eloekset Thanks for pointing this out. I can't update the blog post but I'll add a link to webpack's HMR docs in the same sentence.
