### ISSUE TITLE
python file execution issue

### ISSUE THREAD

**Issue by devparkk** [microsoft/vscode-docs#2843]
As I run any file , everything works fine  , but i'm getting these 5-6 lines of codes (in pink ) in the terminal which is quite irritating , and moreover i have no clue what's going on ...
plz help me out ...
thanks...

![pic_1](https://user-images.githubusercontent.com/45322627/60398964-cdf24480-9b7b-11e9-9491-5ca012ab18ab.jpg)

**Comment by kraigb** [comment]
@devparkk It looks like VS Code is trying to run the "conda" command, but it's not finding that command on the system PATH anywhere. If you have either conda or miniconda installed, then you should have a conda.exe on your system. For example, on my computer I have miniconda installed as part of Visual Studio (the full VS, not VS Code), and so the folder containing conda.exe is C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64\Scripts\. That folder is part of my PATH, and so I can type "conda" on the command line.

For you, then, it's a matter of finding that containing folder and adding it to your PATH. I suggest running "where /r \ conda.exe" to find the conda.exe location, then go into Control Panel to add that location to the PATH.

**Comment by devparkk** [comment]
![Untitled](https://user-images.githubusercontent.com/45322627/60500333-c8117600-9cd7-11e9-859c-4c644ea4a054.jpg)
I tried adding path variable , but it didn't work out , some other problem showed up . so  i installed anaconda and reinstalled it . This time i clicked on the option where it asks to add to the path variable while installing ...yet i'm getting this different  problem .. plzz look into that ...

**Comment by kraigb** [comment]
It looks like conda is running properly, at least. For help with that other error, follow the link that's in the error itself. It's a matter of PowerShell permissions, which isn't an issue that I can help you with here because it's well beyond the scope of the VS Code/Python documentation. In the meantime, then, I'm closing this particular issue because the original problem is resolved.
