### ISSUE TITLE
Downloads page: update minimum required macOS version to 10.10

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docs#2861]
![image](https://user-images.githubusercontent.com/900690/60724378-86323b00-9f36-11e9-93a6-fd831a0dd14c.png)

https://github.com/microsoft/vscode-docs/tree/vnext/release-notes

With the Electron 4 update we lost the ability to run on macOS < 10.10. We should update the download page asap.

**Comment by gregvanl** [comment]
Fixed
