### ISSUE TITLE
Clash between two extensions using same language alias

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#2862]
Version: 1.30.2 (user setup)
OS: Windows_NT x64 10.0.16299

(also present in 1.31.0-insider)

I am developing a language extension (not yet published in Marketplace). It contributes three language IDs:
![image](https://user-images.githubusercontent.com/6726799/52194303-2af70200-284b-11e9-94e2-d64a34df061b.png)

I have also installed a Marketplace extension intended for the same language, which contributes three different language IDs but assigns one of them the same name (ObjectScript) as one of mine:
![image](https://user-images.githubusercontent.com/6726799/52194434-a953a400-284b-11e9-800c-048683acc4e1.png)

When both extensions are enabled and I open the 'Select Language Mode' picker there is only one 'ObjectScript' entry despite every list entry also displaying the language ID in parentheses as a suffix, i.e.
![image](https://user-images.githubusercontent.com/6726799/52194746-fab06300-284c-11e9-8550-6982a4bfa80c.png)

Combined, the two extensions offer only five choices rather than six.

The documentation at https://code.visualstudio.com/docs/languages/identifiers didn't help me understand whether what I'm seeing is intentional. Nor does it say how the ```aliases``` array is supposed to function.

**Comment by gregvanl** [comment]
Closing as no PR submitted.

**Comment by pecigonzalo** [comment]
I have a similar/related question. How are the users able to select between two extensions providing the same language?
I'm developing one that provides only syntax highlighting and grammar, but I would like to be compatible with the existing one, so I'm using the same language `id` but despite changing the aliases lists and other tricks, I cant seem to get it to display both and let the user choose.
Ideally, be able to set file associations to my extension so grammar and syntax is pulled from it but completion/etc uses the other extension.

**Comment by alexdima** [comment]
@pecigonzalo What you desire is currently not possible.

**Comment by pecigonzalo** [comment]
That is quite unfortunate, what is the current solution for this? To ask
the dev to also split their Lang part and just bundle it?

I understand this is not supported at the moment, but then I believe we
should stop bundling Lang and completion and LSP in a single plugin like
it's done in the official Go and Python ones.

**Comment by alexdima** [comment]
@pecigonzalo There is no user-facing picker for grammars (in case multiple extensions register multiple grammars for the same language). But extensions are currently processed in alphabetical order. If extension `B` comes after extension `A` alphabetically, then extension `B` has a chance to override certain contributions done by extension `A`.

That being said, it is unlikely that we will build a user-facing picker for grammars. IMHO, for the wide community, it is far better to contribute a PR to the established grammar than to start a grammar from scratch, so I would like to ask why do you write a new grammar from scratch for Go and Python. Why don't you contribute to the existing ones, to improve them for all of the users of those extensions?

**Comment by pecigonzalo** [comment]
@alexdima There is the `files.associations` section. Isnt that the picker?

It is better in many cases to contribute to centralized grammar, but I might want to submit a different grammar, which some users might prefer and some don't, so I would just create a new grammar extension. Ideally, users should be given the ability to choose, as we do in all software and linters and etc.

IMO It would be a lot better to stop bundling 30 functions in 1 extension, like grammar/syntax with LSP and linter/formatter as they could be safely decoupled. 

Just to clarify, I'm not trying to do a Go or Python syntax, but rather a Terraform one. https://github.com/mauve/vscode-terraform the most widely used one, but there is also https://github.com/4ops/vscode-language-terraform and some others. So it would be great to use and support mauve functionality on formatting and integration to LSP but use a different syntax.

**Comment by pecigonzalo** [comment]
@alexdima any thoughts on this? Could we maybe re open the issue?

**Comment by dionjwa** [comment]
As example: browser Typescript, and Deno. Both use the `.ts` extension, but the std lib for each is completely different, and requires a different language mode.

**Comment by alexdima** [comment]
@dionjwac We don't currently have any other setting than `files.associations`. That can be defined at the user level, per-folder or per-workspace.

**Comment by GitMensch** [comment]
> Should we offer a user setting that would be respected in case of clashes?

Yes, for example a variante to the language identifier as it is done in the [SARIF spec](https://github.com/oasis-tcs/sarif-spec), you can even use the extension name for that and this way have

```json
"files.associations": {
	"*.S": "asm/some.extension",
	"*.asm": "asm/other.ext",
}
```

**Comment by andreagentili** [comment]
A situation in which one would need to have two grammars with same ids and names but different file extensions is this: a single extension for a language that needs to offer different icons for specific files (e.g. a `.lang` for programs in that language and `.langnb` for notebooks in that language). As of today there is no way to specify two different icons within the same language in `package.json`, you need to duplicate it.
