### ISSUE TITLE
remote release notes link opens github

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-docs#2872]
In https://code.visualstudio.com/updates/v1_36#_remote-development-preview, click on the remote release notes link

![image](https://user-images.githubusercontent.com/6461412/60799029-a4847a80-a172-11e9-9c89-3544d807ea86.png)

brings you to the vscode-docs repo. Is that intended?

Also can we make the remote release notes more prominent? It's very well hidden.

Maybe we can also mention it on https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack

**Comment by gregvanl** [comment]
The work to integrate the remote release notes is covered by https://github.com/microsoft/vscode-website/issues/853
