### ISSUE TITLE
Feature request: Find panel documentation is missing

### ISSUE THREAD

**Issue by atiris** [microsoft/vscode-docs#2873]
The lack of documentation makes it impossible to determine whether the Find Panel functionality is correct.

I expect this behavior:

**Find panel intialization phase** (open the Find panel if it was closed)

- If there is no selection, active word (under the cursor) is copied into Find input after open Find panel, Search in selection is disabled (since there is no selection evidently).

- If selection is in one line (the selection does not exceed the line break), after open Find panel, selected string is pre-filled in input field and Search in selection is disabled. (The most common use case for this situation is that you want to search for a tagged word.)

- If more than 1 line is selected, after open Find panel, nothing is copied into find input (if anything has previously been searched, it will remain preserved but marked for overwriting), Search in selection is active. (The most common use case for this situation is that you want to search for a word inside of the selection.)

**Find panel actions** (Find panel is already opened)

- Any action in Find panel must retain the original selection until the searched value is confirmed / selected or find panel is closed or user manually change the selection.

- If user type anything, find panel search for the first occurrence (from cursor, or in selection from beginning of selection) and mark it as active. Find panel has focus.

- If user press ENTER, find panel search the next occurrence and select it. Find panel has focus.

- If user press SHIFT + ENTER, find panel search for the previous occurrence and select it. Find panel has focus. 

- If user press CTRL + ENTER (confirmation), active search selection is "transferred to the document", document get focus, active occurence is selected and find panel is closed. (Now alternative to this is ESC, however, this is not intuitive, that ESC is confirmation to last selection.)

- If user press ALT + ENTER (confirmation) all occurences are selected, cursor is multiplied, document has focus, Find panel is closed.

- If user press ESC (cancellation), find panel will be closed, original selection is restored, so searching is canceled.

- Initial selection must not be changed if user navigate in occurences, enable or disable "Find in selection" or enable or disable any search feature like "Match case", "Match whole word" or "Regexp". Active occurence should be highlighted in a different way than the active selection.

- Changes in selection should be reflected in the search results update (count and active occurence highlight) in the Find panel immediately after the selection changes.

**Connected bugs to Find panel**

The consequences of missing documentation are reflected in bugs (however, due to a lack of documentation, I am not sure if any of this is a bug):

- [Unusable pre-filed value after openning the Find panel](<https://github.com/microsoft/vscode/issues/76857>)
- [Selection is changed when using Find and Replace panel](<https://github.com/microsoft/vscode/issues/76859>)
- [Find and replace panel will end up in an inconsistent state](<https://github.com/microsoft/vscode/issues/76860>)

**Request history**

_The originally reported feature request ["Find panel in the guide"](<https://github.com/microsoft/vscode/issues/70210>) was ignored for 4 months, so I reviewed it, split the request for documentation and errors and I checked it on the last version of VSCode._

**Comment by greggman** [comment]
I don't see a way to upvote this but think I mostly agree with the design above. Came because of the selection bugs. If I try to select after opening the find UI it's all pretty whacky and non-intuitive. This often happens because I start typing the thing to find and my selection gets lost so I have to reselect but re-selecting while find is active is unintuitive. The find results don't update to reflect that I've changed the selection even with find in selected highlighted.

**Comment by gregvanl** [comment]
Hi @atiris Thank you for logging this issue and providing the behavior description. I don't think documenting the behavior is necessary as most users will learn the behavior via trial and error and are unlikely to consult the documentation. There is also the maintenance cost of keeping the documentation up to date, for example, multi-selection was recently added to the search panel. Closing this suggestion for now.

**Comment by atiris** [comment]
Ok @gregvanl the problem here is that everyone can say that the find panel behavior is wrong, because

1) in the tools he used before it was different and 
2) there is no general description of how it should work.  

I tried to write it wisely and as broadly as possible so that this principle would "never" have to be modified over time. But I understand that having described the principles of functioning of some part of the software is not common and probably nobody will include it anywhere. For me it's fine that this request will be closed. Anyway, since I reported these things, the behavior of the find panel has changed slightly. Thank you for reading and evaluating the contribution.

Although I would prefer the described behavior in the case of selection, I can work with the current situation. **Much more important is to make sure that VSCode does not tell me that it has replaced all occurrences of something, and in fact made the modification only in part**, such erroneous behavior was quite serious bug for the code editor.

**Comment by gregvanl** [comment]
@atiris Thanks also for the detailed issues you have created. I have been able to repro the last two but perhaps the first is fixed. I also notice that the behavior of 'Find in Selection' may have changed as is no longer sticky when you reopen the editor Find panel.
