### ISSUE TITLE
JSDoc links need to be updated

### ISSUE THREAD

**Issue by mfulton26** [microsoft/vscode-docs#2881]
https://usejsdoc.org/ has moved to https://jsdoc.app/. Some files can be updated:

https://github.com/microsoft/vscode-docs/blob/e35e7d9901f8f5262a4f42671e09b03f9e455874/docs/languages/typescript.md#L60
https://github.com/microsoft/vscode-docs/blob/e35e7d9901f8f5262a4f42671e09b03f9e455874/docs/languages/javascript.md#L71
https://github.com/microsoft/vscode-docs/blob/4cad3e9673372c442e4ae282c6131989a3346643/release-notes/v1_10.md#L263

**Comment by gregvanl** [comment]
Thanks for pointing this out!
