### ISSUE TITLE
https://code.visualstudio.com/docs/python/python-tutorial inconsistently names virtual environments

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#2885]
Some of it mentions using the name `.venv`, other parts say `env`. It should be `.venv` consistently throughout.

**Comment by kraigb** [comment]
@brettcannon In python-tutorial, the only two instances of "env" are in the two commands to create the environment. ".venv" is used only once as an example. From what I can tell, then, the only change for this issue would be using .venv in the commands. Are you seeing something more in this article?

**Comment by brettcannon** [comment]
@kraigb nope, not the command inconsistency.

**Comment by kraigb** [comment]
OK, I already changed the commands to use .venv in https://github.com/microsoft/vscode-docs/pull/2894/commits/591bc668718d02357e41448a701e8a9a4c2b78a0, so if there's nothing else, I'll consider this closed.
