### ISSUE TITLE
Wrong setting description for external terminal

### ISSUE THREAD

**Issue by germansak** [Microsoft/vscode-docs#289]
Hi. On the example for launching preferred shell there´s an error. It says

```
{
    "externalTerminal.windowsExec": "powershell",
    "externalTerminal.linuxExec": "terminator"
}
```

and the way it works is

```
{
     "terminal.external.windowsExec": "powershell",
    "terminal.external.linuxExec": "terminator"
}

```

**Comment by gregvanl** [comment]
Thank you for taking the time to open the issue. You are correct with the current Insiders build but this was changed recently and will be "externalTerminal" on the next Insiders build.
