### ISSUE TITLE
Doesn't Remote-Containers/SSH works well when target containers/hosts' network (to Internet) is not available

### ISSUE THREAD

**Issue by bro3cat** [microsoft/vscode-docs#2906]
Hi, vscode guys.
I have got 2 questions that:
Does Remote-Containers/SSH need to download/install extensions every each time ?
Does the target container/host need network to internet when Remote-Containers/SSH connecting to them?

Every time I connect to my docker container in my ubuntu-server, it reports like following:
----------------------------------------------------------------------------------------------------------
Setting up container with 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Run: docker cp 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159:/etc/passwd -
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 test -d /root/.vscode-server-insiders
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 test -d /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 test -d /root/.vscode-server-insiders/extensions
Run: docker exec -w /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8 -e VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8/server.sh --install-extension MS-CEINTL.vscode-language-pack-zh-hans
**_Installing extensions..._**

-------------------------------
It looks like nothing wrong, But the **"installing extensions" continues for about 2-3 minutes**  when the container's network is not available( I mean network to the Internet is not available ). Well, It is not the first time to connect to my container, but still **"installing extensions..."**

After connected, logs are as following:
-------------
**Installing extensions...
connect ETIMEDOUT 13.107.6.175:443
Extension host agent is already running.**
Run: docker exec -w /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 /bin/sh -c cat .devport 2>/dev/null
42263
#-------------------------
Published Ports:
22/tcp -> 0.0.0.0:16201
8888/tcp -> 0.0.0.0:16801
#-------------------------

Now I have set up network (to Internet), and connect to the same docker container. It takes only about 10 seconds, logs are:
------------
Setting up container with 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Run: docker cp 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159:/etc/passwd -
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 test -d /root/.vscode-server-insiders
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 test -d /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8
Run: docker exec 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 test -d /root/.vscode-server-insiders/extensions
Run: docker exec -w /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8 -e VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8/server.sh --install-extension MS-CEINTL.vscode-language-pack-zh-hans
**Installing extensions...
Extension 'ms-ceintl.vscode-language-pack-zh-hans' is already installed.
Extension host agent is already running.**
Run: docker exec -w /root/.vscode-server-insiders/bin/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8 05910fd40ca02b7ec1052938128e0b9779b46d29f81866bb249b146b0713d159 /bin/sh -c cat .devport 2>/dev/null
42263
#-------------------------
Published Ports:
22/tcp -> 0.0.0.0:16201
8888/tcp -> 0.0.0.0:16801
#-------------------------

**Comment by Chuxel** [comment]
> Does Remote-Containers/SSH need to download/install extensions every each time ?
Does the target container/host need network to internet when Remote-Containers/SSH connecting to them?

Yes, it needs internet access currently. See [here for connection requirements](https://code.visualstudio.com/docs/remote/ssh#_what-are-the-connectivity-requirements-for-the-vs-code-server-when-it-is-running-on-a-remote-machine-vm).  There's also a feature request around some of this [here](https://github.com/microsoft/vscode-remote-release/issues/161) and [here](https://github.com/microsoft/vscode-remote-release/issues/15) that you can upvote if you are interested.
