### ISSUE TITLE
i can not build the hello word on WSL task which is the demo in vscode Using C++ and WSL in VS Code

### ISSUE THREAD

**Issue by hzgoin** [microsoft/vscode-docs#2907]
i configure my vscode c++ extension follow the document, but nothing happens except the output on vscode terminal when i press Ctrl+Shift+B.the build command looks like stuck.

![image](https://user-images.githubusercontent.com/6188755/61684213-40091400-ad4b-11e9-8e73-c5803bbb5a9a.png)

![image](https://user-images.githubusercontent.com/6188755/61684268-72b30c80-ad4b-11e9-994f-07f2a1ddc084.png)

![image](https://user-images.githubusercontent.com/6188755/61684695-db4eb900-ad4c-11e9-92f7-62682bc3e995.png)

![image](https://user-images.githubusercontent.com/6188755/61684236-5911c500-ad4b-11e9-9caa-4600d1582563.png)

**Comment by lang-wang** [comment]
I have the same problem。

**Comment by mikeblome** [comment]
@lang-wang @hzgoin You need to remove the /mnt/... part of the path to helloworld.cpp. Just the filename like this:

**Comment by hzgoin** [comment]
> @lang-wang @hzgoin You need to remove the /mnt/... part of the path to helloworld.cpp. Just the filename like this:
> "args": [
> "-g",
> "-o",
> "/home//projects/helloworld/helloworld.out",
> "helloworld.cpp"
> ],

it doesn't work to me.
 the /mnt/...part is the absolutely path in wsl. the build command "g++ -g -o... /mnt/..." which output in vscode terminal  can executed corrently directly in wsl and the vscode remainds this "the task ... is already active" when i run the build task again.

**Comment by gregvanl** [comment]
Closing as no recent updates. Please reopen if you are still having issues.
