### ISSUE TITLE
when clause info hard to find

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-docs#2911]
the `when` clause is pretty powerful in the API, but finding information on how to use it is pretty hard.  there are a lot of references to the `when` clause but i only found 1 link in the API docs to the key bindings section 

for example, in the treeview documentation https://code.visualstudio.com/api/extension-guides/tree-view#tree-view it says "You can also control the visibility of the view by providing the when context value." but there is no link on `when`."

Searching for the term `when` in the docs uber search at the top of the page is futile :).

So, I manually went through each of the API doc pages and did a find looking for `when` and only found a link to `clauses` here https://code.visualstudio.com/api/references/contribution-points#contributes.commands, which then takes me out of the API docs to the keybindings page.

It would be ideal to have a top level topic in the API docs that explains how to use the `when` clause and wherever we reference `when`, link to it.

**Comment by gregvanl** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

**Comment by chrisdias** [comment]
ya i found that, but when i am in the API docs and i see many references to the when clause, i have no idea that i need to go look under the regular docs/keybindings

**Comment by liang2zhu1** [comment]
I filed a similar and get duped (which is all right) so just share how to use the configuration you created in contribution, in case anyone searches this - 
you can add `config` prefix to the config name and use that same way as a built-in one, eg `config.myextension.configX`

**Comment by gregvanl** [comment]
Closing in favor of https://github.com/microsoft/vscode-docs/issues/3960
