### ISSUE TITLE
Bad image on editing evolved page

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#293]
This image... doesn't look great. 

![image](https://cloud.githubusercontent.com/assets/2449568/14990508/b8059f0c-1111-11e6-973b-46bb9aed38e9.png)

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/cd33dca1890b07a70c38211feca83fb3ef3aff8e currently in vnext
