### ISSUE TITLE
New Python in VS Code Feature: Jupyter Notebook Cell Debugging

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#2949]
We just announced a new feature [yesterday](https://devblogs.microsoft.com/python/python-in-visual-studio-code-august-2019-release/): Jupyter Notebook Cell Debugging by way of a 'Debug Cell' code lens. It would be great if we could get this feature documented. I'm thinking [here ](https://code.visualstudio.com/docs/python/jupyter-support#_debug-a-jupyter-notebook) would be a great spot!

**Comment by kraigb** [comment]
@Anapo14 I've updated the article in #2977, namely to highlight Debug Cells with the other adornments, and to note that option in the debugging section.
