### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by sirrus** [Microsoft/vscode-docs#297]
Images are not shown when I use URL style Image links (which are needed for Seafile).

Example:
`[display name](https://seacloud.cc/lib/341cd700-a9f2-424e-ae1d-fdd52449bb9e/file/images/IMG_2505.JPG?raw=1)`

URL:
https://forum.seafile-server.org/t/seafile-server-v5-0-1-beta-is-ready-bug-fix-and-updated-markdown-support/3332

**Comment by sirrus** [comment]
Sorry - here is the code:
```[display name](https://seacloud.cc/lib/341cd700-a9f2-424e-ae1d-fdd52449bb9e/file/images/IMG_2505.JPG?raw=1)```

**Comment by sirrus** [comment]
Update - this is the ticket for seafile:
https://forum.seafile-server.org/t/seafile-server-v5-0-1-beta-is-ready-bug-fix-and-updated-markdown-support/3332/6

**Comment by gregvanl** [comment]
Not sure I understand the issue here.  VS Code's markdown preview can handle URL style image links for example:

```
![car](https://static.pexels.com/photos/54278/pexels-photo-54278.jpeg)
```

**Comment by gregvanl** [comment]
I get a log prompt when I try to user the seacloud.cc link above.

**Comment by sirrus** [comment]
It's not working with local images an a question mark:
```?raw=1``` -  which is necessary for seafile

**Comment by gregvanl** [comment]
I just tried adding ?raw=1 to the above car link ![car](https://static.pexels.com/photos/54278/pexels-photo-54278.jpeg?raw=1)
