### ISSUE TITLE
Update docs to remove 'outputWindow' under testing settings

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-docs#2974]
@maximlt commented on [Tue Aug 13 2019](https://github.com/microsoft/vscode-python/issues/6951)

While looking for a way to get colorized pytest log output (https://github.com/microsoft/vscode-python/issues/5767), I've found out that the docs mention an `outputWindow` testing setting, which seems to be deprecated (as in https://github.com/microsoft/vscode-python/issues/513 and https://github.com/microsoft/vscode-python/issues/650).

These two pages should be updated accordingly:
https://code.visualstudio.com/docs/python/settings-reference#_testing-settings
https://code.visualstudio.com/docs/python/testing#_test-configuration-settings

Given some guidelines I could submit a PR in vscode-docs.

Thanks for VSCode :)

**Comment by gregvanl** [comment]
@maximlt Contributing is pretty easy. You can learn more in the README and https://github.com/microsoft/vscode-docs/blob/master/CONTRIBUTING.md

**Comment by kraigb** [comment]
@maximlt Thanks for pointing out the deprecated settings; I've removed them.
