### ISSUE TITLE
Broken link for multi-cursor selection doc in "Getting Started" landing page carousel

### ISSUE THREAD

**Issue by somaritane** [Microsoft/vscode-docs#298]
Link to "multi-cursor selection" documentation in "Fast, powerful editing" carousel panel is broken, seems like link href attribute is missing the leading "slash": `href="docs/editor/editingevolved#_selection-multicursor"`.
Should be `href="/docs/editor/editingevolved#_selection-multicursor"`.

**Comment by gregvanl** [comment]
You are correct that the link should have a leading slash.  Interestingly I don't see the broken link on Chrome, Edge or IE.  With which browser are you seeing this issue?

**Comment by gregvanl** [comment]
Fixed with vscode-website https://github.com/Microsoft/vscode-website/commit/eb97d3c47ce487fd2efb29faa1bab0c133ac98a8

**Comment by somaritane** [comment]
I'm using Opera, however I think the issue was not browser-specific. It happened after redirection from main page on clicking "Download for Windows" link (so resulting URL for Docs page was: https://code.visualstudio.com/Docs/?dv=win)

**Comment by gregvanl** [comment]
You are absolutely right.  The fix will be published today.  Thanks for your help.
