### ISSUE TITLE
Reduce 'Verify the Python Installation' section of 'Getting Started' tutorial

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#2994]
For [this ](https://code.visualstudio.com/docs/python/python-tutorial#_verify-the-python-installation)section, we should:

-  remove the information related to putting Python on the PATH and instead link to official Python documentation for more information related to paths. 

- remove information related to installing Python from the Windows Store. 

Overall, this section should read something like 'to verify that Python was successfully installed, do X', where X is the existing terminal commands for Linux/MacOS and Windows.

**Comment by gregvanl** [comment]
@Anapo14 This looks like a fairly small change and PRs are welcome.
Have a look at CONTRIBUTING.md for details on forking the vscode-docs repo and submitting a PR.

**Comment by JoshuaPartlow** [comment]
Fix being worked on as part of PR https://github.com/microsoft/vscode-docs/pull/3181

**Comment by JoshuaPartlow** [comment]
PR merged
