### ISSUE TITLE
Promote Headings on 'Getting Started with Python in VS Code' Tutorial

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#2995]
Instead of having a prerequisites section here, it would be great to promote some of the bullets/sections within this block to full-on headers. For example, **Install the Python Extension**, **Install a Version of Python 3**, and **Verify the Python Installation** sections should be promoted to a main header such that they appear within the 'In the Article' outline on the righthand side of the tutorial.

**Comment by JoshuaPartlow** [comment]
Fix being worked on as part of PR https://github.com/microsoft/vscode-docs/pull/3181

**Comment by JoshuaPartlow** [comment]
PR merged
