### ISSUE TITLE
Improve URL handling documentation

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode-docs#3004]
The documentation for URL handlers is out of date.

From [here](https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls):
> On Windows and macOS, you can also open projects and files using the platform's URL handling mechanism

Linux support was added in https://github.com/microsoft/vscode/pull/56727

The docs talk about `vscode://` but `vscode-insiders://` exists too. It is only mentioned [here](https://code.visualstudio.com/api/references/activation-events) in the extension API docs.

I would like to have one place gathering all information:
- Supported platforms (Windows, linux, macOS)
- Supported schemes (vscode and vscode-insiders)
- Ways to use URL handlers:
  - Open files with `vscode://file`
  - Trigger extensions with `vscode://publisher.extensionName/...`

Is there any other way to use URL handlers? Right now I'm not sure.

I browsed the issues to gather information:
https://github.com/Microsoft/vscode/issues/4883
https://github.com/Microsoft/vscode/issues/48528
https://github.com/Microsoft/vscode/issues/46256
https://github.com/microsoft/vscode/issues/48426
https://github.com/Microsoft/vscode/issues/59244
https://github.com/microsoft/vscode/pull/56727

Related to https://github.com/microsoft/vscode-docs/issues/791

Thank you

**Comment by gregvanl** [comment]
Hi @sguillia Thank you for pointing out the stale content. 
From my commit, you can see that I opted not to add more description for triggering extensions via URL since it doesn't feel like an end user scenario and is primarily for extension authors.
I checked with the engineering team and did not find any other ways to use URL handlers beside the two you mention.

**Comment by sguillia** [comment]
Thank you @gregvanl for the confirmation.

I am an extension author and I was looking for all ways to utilise URL handlers.

For reference, the scheme `vscode-exploration://` also exists.

**Comment by sguillia** [comment]
@gregvanl In https://github.com/Microsoft/vscode/issues/20289, I found another way to use the URL handlers.
Example to open an extension in the marketplace:
```
vscode:extension/ms-vscode.csharp
```

**Comment by westurner** [comment]
- https://code.visualstudio.com/updates/v1_23#_git-clone-improvements :
  > `vscode://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode-vsce.git`
- https://github.com/microsoft/vscode/issues/4883#issuecomment-270141535 :
  > Open a file to a specific line and column number:
  > `vscode://file/path/to/file/file.ext:L:C`
  > Example: Open `file.ext` to line `55` and column `20`:
  > `vscode://file/path/to/file/file.ext:55:20`
  > 
  > Open a project, workspace, or folder with directory contents:
  > `vscode://file/path/to/project/`
