### ISSUE TITLE
latest.md summary should mirror blog post summary

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#301]
In the blog post we changed the bullets to be more descriptive.  the latest.md still has the terse bullets.  we should be consistent here.

cc @waderyan

**Comment by gregvanl** [comment]
I don't think we need these to match.  The release notes have the full details below so we just need to give a brief overview and let the reader continue.  Since the blog stands on it's own, it's fine to put more details there.

**Comment by chrisdias** [comment]
I respectfully disagree :).  We have 30 seconds to catch the reader's attention so they can learn more and to do that I think we need to (always) show the value right away.

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/09a670a20fe68c8b9dcfe00a6d33be91cbc28ac9
