### ISSUE TITLE
Keybindings: Context keys are not up to date

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docs#3039]
While adding a few new context keys I added during this milestone I noticed that our [documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) ([raw file](https://github.com/microsoft/vscode-docs/blob/vnext/docs/getstarted/keybindings.md)) around context keys is missing some newer contexts we added.

@microsoft/vscode I did a quick check over our context keys and here are most of them that are either missing or need review. Please check this out during endgame and see if a key should be added. I do not think we should add each and every key, but some may be useful for users to know:

`cancellableOperation`
`editorTabMovesFocus`

`canUndo`
`canRedo`
`findInputFocussed`
`replaceInputFocussed`
`markersNavigationVisible`
`referenceSearchTreeFocused`
`hasNextTabstop`
`hasPrevTabstop`
`atEndOfWord`
`hasWordHighlights`
`accessibilityHelpWidgetVisible`
`accessibilityModeEnabled`
`multiCursorModifier`
`callHierarchyVisible`

`breadcrumbsPossible`
`breadcrumbsVisible`
`breadcrumbsActive`

`webviewFindWidgetVisible`
`webviewFindWidgetFocused`

`terminalA11yTreeFocus`
`terminalTextSelected`
`terminalFindWidgetVisible`
`terminalFindWidgetInputFocused`
`terminalFindWidgetFocused`

`taskRunning`

`commentThreadIsEmpty`
`commentIsEmpty`
`commentEditorFocused`

`searchViewletFocus`

`problemsViewFocus`
`problemFocus`
`problemsFilterFocus`
`relatedInformationFocus`

`remoteAuthority`
`remoteName`
`remoteConnectionState`
`remoteFileDialogVisible`

There are lots of keys defined in these files too:
`src/vs/workbench/contrib/debug/common/debug.ts` @isidorn 
`src/vs/workbench/contrib/search/common/constants.ts` @roblourens 
`src/vs/workbench/contrib/files/common/files.ts` @isidorn

**Comment by bpasero** [comment]
@octref I think it would not be good to add all of the keys we have, we should make a careful case by case decision because a lot of these keys are only added e.g. to have conditional menu items.

What I find odd for context keys is that I cannot put a description to them when creating, unlike our workbench theme colors.

> I also noticed our theme color keys get outdated.
Well, at least you get intellisense for them when writing a theme. There is no UI to tell you the keyboard context keys available unfortunately.

**Comment by dbaeumer** [comment]
I opt to keep `taskRunning` internal since it is only used to control state for actions the core contributes.

**Comment by alexr00** [comment]
`remoteFileDialogVisible` is used to add the ctrl+O keybinding to open local when the remote file dialog is visible doesn't have much use externally.

**Comment by jrieken** [comment]
> What I find odd for context keys is that I cannot put a description to them when creating, unlike our workbench theme colors.

We could actually tackle that. Context keys are usually defined via `RawContextKey` and we could add a description property and a flag if they are user-facing or not

**Comment by gregvanl** [comment]
Created https://github.com/microsoft/vscode/issues/114867 as a feature request to add a description and user-facing flag to RawContextKey.
