### ISSUE TITLE
Add insiders channel setting to supported settings list for the Python extension

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3043]
We added a *user* setting (not workspace) called "python.insidersChannel":  that can be either "daily" or "weekly", and that opts users in our insiders program (more about it in the [blog post](https://devblogs.microsoft.com/python/python-in-visual-studio-code-august-2019-release/)).  We just need to document these as valid settings

**Comment by JoshuaPartlow** [comment]
@luabud - I added a small section to [the Python overview](https://code.visualstudio.com/docs/languages/python) and the setting to the general section of the [Settings reference](https://code.visualstudio.com/docs/python/settings-reference). Could you take a look at the changes in the [PR ](https://github.com/microsoft/vscode-docs/pull/3079/files) and make sure they're good before I merge?

**Comment by luabud** [comment]
Looks good :)

**Comment by JoshuaPartlow** [comment]
Merged PR https://github.com/microsoft/vscode-docs/commit/c4f963f97b548581201515ea34a6f155ae3b3e63
