### ISSUE TITLE
Add "Just my code" option to the Jupyter debugging doc

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-docs#3053]
Need to add the following to the doc: https://code.visualstudio.com/docs/python/jupyter-support

In the August release, we added the ability to debug Jupyter notebook cells where you can step into user code. In the Sept release, this feature is enhanced with the option to also step into non-user code if needed. To enable, open the settings page (File > Preferences > Settings), search for “Data Science: Debug Just My Code” and uncheck the option. 
 
![image](https://user-images.githubusercontent.com/26419852/64214430-5f748000-ce65-11e9-80e4-0d1897982f80.png)

**Comment by JoshuaPartlow** [comment]
Added note about unchecking Debug Just My Code if you want to debug non-user code. Commit https://github.com/microsoft/vscode-docs/commit/be453052d461d0c73c2ec539d854521c99d337a1
