### ISSUE TITLE
The height of cell in Data View window clicked from python interactive

### ISSUE THREAD

**Issue by over-shine** [microsoft/vscode-docs#3055]
![image](https://user-images.githubusercontent.com/30746603/64223165-62bf4880-cf05-11e9-93d4-a3054b25160b.png)

**Comment by ronglums** [comment]
@over-shine, thanks for sending this. Looks like a bug in the product. Do you happen to have steps for a repro?

**Comment by over-shine** [comment]
> Do you happen to have steps for a repro?

Now，it has been  solved but I don't do anything.
