### ISSUE TITLE
Unable to run Django command after restarting MS Comand Prompt.

### ISSUE THREAD

**Issue by Ganesh-star** [microsoft/vscode-docs#3061]
I installed Django through MS Command Prompt and closed Command Prompt. After restarting my Command Prompt I'm unable to use Django command. Please help me.
![Screenshot (7)](https://user-images.githubusercontent.com/52710919/64509441-5409d480-d2fd-11e9-9983-8a26924ee09b.png)
![Screenshot (7)](https://user-images.githubusercontent.com/52710919/64509476-6d128580-d2fd-11e9-9a9b-578819917feb.png)

**Comment by JoshuaPartlow** [comment]
Hi @Ganesh-star - Are you using VS Code? Our [VS Code Django tutorial](https://code.visualstudio.com/docs/python/tutorial-django) walks through creating a Django project. That includes setting up the virtual environment, installing Django in the virtual environment, activating the environment, and creating/running a minimal Django app.

**Comment by JoshuaPartlow** [comment]
Hi @Ganesh-star - I hope the Django tutorial is helpful to you. I'm closing this issue now, but if you have problems with the documentation, please feel free to open an issue.
