### ISSUE TITLE
Update flask tutorial to account for new debugging experience

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3065]
https://code.visualstudio.com/docs/python/tutorial-flask

Main changes will be on paragraphs below:
![image](https://user-images.githubusercontent.com/45497113/64578678-ff824b80-d334-11e9-85cf-a09d67c121e3.png)

**Comment by JoshuaPartlow** [comment]
Confirmed changes and will work to update next week.

**Comment by JoshuaPartlow** [comment]
@luabud - Flask tutorial debugging section is updated with commit https://github.com/microsoft/vscode-docs/commit/7cc460934735b916e9d8c17016f6254bf09a1e2a
