### ISSUE TITLE
Missing quotes in launch.json reference

### ISSUE THREAD

**Issue by utsavm9** [microsoft/vscode-docs#3071]
In https://code.visualstudio.com/docs/cpp/launch-json-reference#_args about double escaping arguments given to program, it states that

> `["{\\\"arg1\\\": true}]` will send `{"arg1": true}` to your application.

I think that example is missing a quote and should be `["{\\\"arg1\\\": true}"]`

**Comment by gregvanl** [comment]
Thanks for pointing this out.
Fixed with https://github.com/microsoft/vscode-docs/commit/7ff429c2a813f492eb9d0881e6da1a1c4260bf36
