### ISSUE TITLE
Add Information about Creating a new folder using VS Code UI

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#3073]
In the getting started with python in VS Code tutorial, we should add a tidbit somewhere here showing users how to create a new folder using the 'create new folder' icon. (even a small note: would suffice). 

[This ](https://code.visualstudio.com/docs/python/python-tutorial#_start-vs-code-in-a-project-workspace-folder) is potentially a good spot for it.

**Comment by JoshuaPartlow** [comment]
@Anapo14 - Do you mean the icon that shows on a folder in the VS Code Explorer window when you have an initial folder open? Or is there another icon?

**Comment by Anapo14** [comment]
I mean that users can use this icon 
![image](https://user-images.githubusercontent.com/10341823/67014348-8f8c8100-f0a9-11e9-9230-c8f56b8b9013.png) to create a new folder instead of going to File > Open Folder and then creating a new folder in their workspace that way.

**Comment by gregvanl** [comment]
We've found the best flow for tutorials is for users to create a new folder or generate a project from the command line/terminal and then learn about 'code .' to open VS Code scoped to the context of that folder. The document location you call out above does just that. I don't think you want to reverse the order (start VS Code first and then create the folder and then have to reopen VS Code in the scoped context of that folder).

**Comment by JoshuaPartlow** [comment]
This item isn't about creating a workspace folder, that part would stay the same, it's about adding an additonal note/section about using the folder icon within a workspace to create subfolders.

**Comment by gregvanl** [comment]
Does the tutorial require the user to create a subfolder? If not, I wouldn't add instructions to do so.

**Comment by JoshuaPartlow** [comment]
Fix being worked on as part of PR https://github.com/microsoft/vscode-docs/pull/3181

**Comment by JoshuaPartlow** [comment]
PR merged
