### ISSUE TITLE
task.json schema is not correct

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#3081]
I think the file `docs/editor/tasks-appendix.md` is not up to date with the latest version of VSC.

* You are allowed to have a task list without operating system keyword at the base level
```typescript
interface TaskConfiguration extends BaseTaskConfiguration {
    version: "2.0.0";
    windows?: BaseTaskConfiguration;
    osx?: BaseTaskConfiguration;
    linux?: BaseTaskConfiguration;

    tasks?: TaskDescription[];
}
```

* The `options` field is missing in the `interface TaskDescription`

```typescript
interface TaskDescription {
   label: string;
   type: "shell" | "process";
   command: string;
   isBackground?: boolean;
   args?: string[];
   group?: "build" | "test" | { kind: "build" | "test"; isDefault: boolean };
   presentation?: PresentationOptions;
   problemMatcher?: string | ProblemMatcher | (string | ProblemMatcher)[];
   runOptions?: RunOptions;

   options?: CommandOptions;
}
```

**Comment by gregvanl** [comment]
Hi @rioj7 Thanks for alerting us. We actually going to deprecate the tasks-appendix page in favor of recommending using IntelliSense in tasks.json to see the latest tasks schema (which is what you likely did to notice the discrepancy :-) ). You can see the comments in https://github.com/microsoft/vscode-docs/issues/2480.
