### ISSUE TITLE
offline documentation

### ISSUE THREAD

**Issue by i164j9** [microsoft/vscode-docs#3087]
Issue Type: <b>Feature Request</b>

It would be nice to have offline documentation for VSCode most of the time i am without internet access and needing documentation on how or what to change in VSCode for customization or configuration of which then pushes me back to a text editor or command line for coding.the same applies to visualstudio downloadable pdfs would be handy.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 5.1.6-200.fc29.x86_64

**Comment by gregvanl** [comment]
No current plans to support offline documentation.
