### ISSUE TITLE
How to change colors in settings.json?

### ISSUE THREAD

**Issue by David263** [microsoft/vscode-docs#3092]
None of the many themes work for me. How do I edit settings.json to change the background color of edit panes, etc.? I can find no documentation or commands to change colors. Maybe this information is in a theme-writing guide. Where could I find this?

**Comment by gregvanl** [comment]
Hi @David263 Have a look at https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme.
For your example of changing the editor background color, you can add color overrides in the  workbench.colorCustomizations array by adding to your user settings in settings.json:

```json
    "workbench.colorCustomizations": {
        "editor.background": "#ff0000"
    }
```

**Comment by David263** [comment]
I've found the documentation in the REFERENCES section of the API (which I guess means "internals" here). I think most VSCode users will want to find this: https://code.visualstudio.com/api/references/theme-color .
