### ISSUE TITLE
Possible error in Release Notes 1.38.1

### ISSUE THREAD

**Issue by Hammerstad** [microsoft/vscode-docs#3093]
Hello.

While reading through the release notes for version 1.38.1, I happened to notice that the Polish and Norwegian localization contributors are identical. All names look Polish to me. This may be a copy-paste error.

Release notes: https://github.com/microsoft/vscode-docs/blob/master/release-notes/v1_38.md#thank-you

**Comment by barnabasn** [comment]
I just fixed the Norwegian contributors and created a PR: https://github.com/microsoft/vscode-docs/pull/3095. Please confirm this issue if you find the fix appropriate.

**Comment by Hammerstad** [comment]
Excellent, thank you :)
