### ISSUE TITLE
After upgrading to VS Code 0.9.2 on Linux (64) it still says 0.9.1 in Help About

### ISSUE THREAD

**Issue by bkbonner** [Microsoft/vscode-docs#31]
I downloaded code from here:  http://go.microsoft.com/fwlink/?LinkID=534108  or from here:  https://code.visualstudio.com/Download  (click on Linux 64).  It says it's 0.9.1.

Thoughts?

**Comment by scottaddie** [comment]
You'll have more luck posting your issue [here](https://code.visualstudio.com/Issues/List), as I believe this repo is dedicated to the actual documentation.

**Comment by bkbonner** [comment]
Thanks.  I posted a bug out there.
