### ISSUE TITLE
Add warning to Python docs about risk of having a publicly open debugger port 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3102]
[Here ](https://code.visualstudio.com/docs/python/debugging#_remote-debugging) we could warn users about potential dangers of having a publicly open debugger port. That's why by default the debugger works on localhost, so that users don't to expose a port to the network unless they really mean to. 

cc @karthiknadig

**Comment by luabud** [comment]
cc @Anapo14

**Comment by JoshuaPartlow** [comment]
The latest debugging topic has the following note that calls out that this is a risk. If we think more info is needed please feel free to reopen.

> **Note**: Be aware that when you specify a host value other than `127.0.0.1` or `localhost` you are opening a port to allow access from any machine, which carries security risks. You should make sure that you're taking appropriate security precautions, such as using SSH tunnels, when doing remote debugging.
