### ISSUE TITLE
Use of setx to update path variable

### ISSUE THREAD

**Issue by BradleyHall** [microsoft/vscode-docs#3117]
The documentation for configuring MinGW [here](docs/cpp/config-mingw.md) instructs the user to use setx to update the environment path variable. This command is VERY dangerous as it truncates anything longer than 1024 characters. I found this out the hard way. Could a different set of instructions be supplied?

**Comment by gregvanl** [comment]
@BradleyHall Thanks for calling this out. Updated with https://github.com/microsoft/vscode-docs/commit/45e0bcf14fa0303ad14a42706ea18dcd9aa39a9d to play it safe and recommend using the Windows Settings UI.
