### ISSUE TITLE
Refactor setup.md with platform specific topics

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#312]
This could move existing setup and FAQ content to a single page.
https://code.visualstudio.com/Docs/supporting/faq#_linux-faq
https://code.visualstudio.com/docs/editor/setup#_linux
We could also have a walkthrough getting Node.js "HelloWorld" running in VS Code (install Node.js, typings).
This may be important to remove download and retention friction for Linux users.

**Comment by gregvanl** [comment]
We might want to move Setup out from under Editor and create separate topics for general setup and platform specific topics.

**Comment by gregvanl** [comment]
Here's some comments from a Linux user new to Node.js https://github.com/Microsoft/vscode-docs/issues/187

**Comment by Tyriar** [comment]
My thinking was above the Editor item in the navigation on the left there would be a Setup something like this:

Setup
- Windows
- Mac
- Linux
- FAQ
Editor
...

The platform content from the current setup page could be split into the 3 setup pages and the platform-specific FAQ could be put in there as well.
