### ISSUE TITLE
Extension continuous integration should also instruct how to publish to the Marketplace

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-docs#3125]
Related: https://github.com/microsoft/vscode-vsce/issues/361

From @Raagh:

> Hi @joaomoreno thanks for your response, already read that unfortunately only covers the part about CI, not the CD. CI was not the problem. The problem was how to make a release pipeline upload the extension to the marketplace using proper publisher id and personal access token.
>
> in case somebody comes here and its interested I manage to solve it by after a build pipeline that publish the packaged vsix as an artifact. Adding 2 artifact references(github repo and packaged vsix) to the release pipeline and having 2 tasks on this pipeline, one npm for installing vsce globaly and a command line for running vsce publish -p {{PERSONAL ACCESS TOKEN}}.

From @moshfeu:

> And in case your extension is public and you don't want to expose PAT to the world, follow this answer: https://stackoverflow.com/q/58192624/863110

**Comment by moshfeu** [comment]
I can help

**Comment by moshfeu** [comment]
@joaomoreno should it be in a separate doc or add the CD part in the end of the CI doc?
Also, could that solution be the "official" way? 

I mean the combination of both of the answers: 
- https://stackoverflow.com/a/58195815/863110
- https://stackoverflow.com/a/58196092/863110

**Comment by joaomoreno** [comment]
Let's keep it in the same doc but in a separate section. Something like `Automated publishing`.

**Comment by moshfeu** [comment]
Ok
