### ISSUE TITLE
Document how to update to a newer version of the API

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#313]
https://code.visualstudio.com/updates/vJanuary#_extension-authoring
- Document how to migrate an extension that is older than January to the new update process.
- Check/review whether we document how to consume a new version of the VSCode API

@gregvanl @weinand can provide more background and should review.

**Comment by gregvanl** [comment]
I think this is covered now by https://vscode-ppe.azurewebsites.net/docs/extensions/publish-extension#_visual-studio-code-compatiblity
