### ISSUE TITLE
Document tree view filtering

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-docs#3133]
VS Code has gotten an amazing feature that let you filter files and folders in a Tree view such as the Explorer https://github.com/microsoft/vscode/issues/66497. Unfortunately it isn't documented anywhere that I could find.

I suggest to document it in the Explorer section in User Interface (since I don't know about any other documentation of the Explorer) https://code.visualstudio.com/docs/getstarted/userinterface#_explorer

It also works in Debug Console

**Comment by samrae7** [comment]
@Sti2nd I would like to take this on. I can see how the feature works in the left hand menu but not in the terminal. Can you tell me how it works there?

**Comment by Sti2nd** [comment]
@samrae7 My bad, it isn't the terminal, it is the Debug Console! Updated my original comment.

**Comment by samrae7** [comment]
@Sti2nd ok thanks I will take this task

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/3fd6676ecd378dbda9824fcaa840815cdaf500c7
