### ISSUE TITLE
Java setup with VS Code Insiders

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-docs#3134]
I only have VS Code insiders on my machine.  The following article only works with VS Code, not insiders.  It would be great if I was given the option to run this with Insiders.

https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/java.md

![image](https://user-images.githubusercontent.com/2163001/66227409-fc5b5080-e691-11e9-8ae9-de6f41797f1d.png)

@gregvanl
@hexiaokai

**Comment by gregvanl** [comment]
Hi @jongio Thank you for the suggestion. Java Installer issues and suggestions should go to https://github.com/Microsoft/vscode-java-pack/issues.
