### ISSUE TITLE
Document new setting for disabling A/B test experiments with the Python extension

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3137]
The new setting is called python.experiments.enabled and can be either true or false. If it's set to false, then users won't get the A/B tests features and experiments anymore. This setting is available only on the **user setting context** (i.e. if you try to change it on the workspace .vscode/settings.json fiole,  it won't recognize the setting because it needs to be on the settings.json file for the User settings). If you look on the UI page, this is what it shows: 
![image](https://user-images.githubusercontent.com/45497113/66327839-581b1900-e8e0-11e9-8744-3f6455b0bcc8.png)

**Comment by gregvanl** [comment]
We usually don't document experiment settings. Such settings are still discoverable in the product through the Settings editor and extension Contributions pane but usually you want to have users leave the experiment enabled and the setting is only a backdoor for users who really want to turn the experiment off.

**Comment by JoshuaPartlow** [comment]
We document settings around enabling/disabling Insider builds and telemetry. This seems similar, as some users may or may not want to participate. @luabud - what do you think?

**Comment by luabud** [comment]
I agree with Joshua, it's similar to disabling Insider builds. But if this isn't done for VS Code in general then I'd rather be consistent :)  Thank you both!
