### ISSUE TITLE
Update the web view API to documentation to mention the minum VScode version requirement.

### ISSUE THREAD

**Issue by samrat-gavale** [microsoft/vscode-docs#3138]
I tried following the [Cat coding example](https://code.visualstudio.com/api/extension-guides/webview) in my extension but was not able to use the use the vscode.window.createWebViewPanel function because I was referring to VSCode engine 1.18.0 It took me some time to realize that I need to refer to version 1.23.0 or higher in my package.json If would be useful and time saving if this version dependency was explicitly called out in the documentation. 

I can go ahead and create a PR for this if it sounds reasonable.

**Comment by gregvanl** [comment]
Hi @samrat-gavale Thank you for the suggestion and I'm sorry you were initially stuck while trying an example. VS Code is already on version 1.38 (1.39 coming this month), so I don't think referencing a version as old as 1.23 is necessary (released April 2018).
