### ISSUE TITLE
Stop moving update page links

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#314]
After every release, links to https://code.visualstudio.com/Updates become broken as the page is replaced. The pages are also inconsistently named and we seem to have adopted a `v<month>` naming structure which is bad because next year contains duplicate months :smiley: 

I suggest the following:
- https://code.visualstudio.com/Updates redirects to the latest notes
- We update all release notes to be of the format https://code.visualstudio.com/updates/v1_0_0 (`v<major>_<minor>_<patch>`) and keep this format going forward.

**Comment by Gigabyte-Giant** [comment]
I like the current `v<month>` naming structure, however I do see the problem(s) that will be faced with a new year.

I do like the `v<major>_<minor>_<patch>` format, however, I think I'm actually more fond of this format: `https://code.visualstudio.com/updates/<month><year>`

I also think the `v` is redundant in both cases, therefore I dropped it entirely from my suggestion.

**Comment by gregvanl** [comment]
Will try <month>_<year>.md instead of always using latest.md for the most recent.

**Comment by Tyriar** [comment]
Reopening as there is still no redirect, /Updates should redirect to the current latest so links are not broken a month later (eg. https://twitter.com/code/status/751181199372984320) and cached social metadata does not break Tweets (eg. https://twitter.com/__ted__/status/751413817049952258)

**Comment by gregvanl** [comment]
Will be handled by vscode-website https://github.com/Microsoft/vscode-website/issues/457
