### ISSUE TITLE
The value of embedded languages is wrong in language-extensions api.

### ISSUE THREAD

**Issue by iuyoy** [microsoft/vscode-docs#3141]
When I try to develop a extension to highlight inline sql and other language code, the `embeddedLanguages` doesn't work as it mentioned in the doc [syntax-highlight-guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide).
 
After some searching,  I find out the value of `meta.embedded.block.javascript` can't be `source.js` but `javascript` in part [Embedded languages](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages). There are two more same problems in the same page.

It doesn't work for
![image](https://user-images.githubusercontent.com/11738832/66483133-0c7e9000-ead7-11e9-8cb6-1e2e9e315dbb.png)

It works for
![image](https://user-images.githubusercontent.com/11738832/66483186-2cae4f00-ead7-11e9-926e-6fd153d496fc.png)

PS: the  last number in the [picture](https://github.com/microsoft/vscode-docs/blob/master/api/language-extensions/images/syntax-highlighting/scope-inspector.png) of `Scope inspector` should be ④  not ①;

**Comment by mjbvz** [comment]
Sounds correct. Do you want to submit a PR that fixes this

**Comment by gregvanl** [comment]
I've updated the numbering in the image https://github.com/microsoft/vscode-docs/commit/ea0dc3b1cd91ef3c1e0e111db63fb1add3121db4

**Comment by iuyoy** [comment]
> Sounds correct. Do you want to submit a PR that fixes this

Sure.
