### ISSUE TITLE
What's the font in the screenshot which from release 1.39?

### ISSUE THREAD

**Issue by shaocongliang** [microsoft/vscode-docs#3145]
![image](https://user-images.githubusercontent.com/30583506/66529943-04a30800-eb38-11e9-9e43-9db18fd3a295.png)

**Comment by RMacfarlane** [comment]
Hey @shaocongliang, this should just be the default editor font family: "Menlo, Monaco, 'Courier New', monospace"

**Comment by RMacfarlane** [comment]
Actually, I may have taken this with "Roboto Mono". The two look very similar to me, I have trouble distinguishing them 😄
