### ISSUE TITLE
The dropdown on release notes pages starts on "Latest" regardless of the page

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#315]
Load https://code.visualstudio.com/updates/vMarch and observe the dropdown is on Latest, this means users can't navigate to the latest using the dropdown.

![image](https://cloud.githubusercontent.com/assets/2193314/15451377/1ccd8cb8-1f74-11e6-89cb-602176fb6c31.png)

**Comment by gregvanl** [comment]
This is true of all the pages.  The dropdown always displays the top most item under the left navigation.
If we want to fix this, it is a vscode-website issue.

**Comment by gregvanl** [comment]
Moved to https://github.com/Microsoft/vscode-website/issues/553
