### ISSUE TITLE
In Jupyter files, vs quickly deletes recent changes with no way back

### ISSUE THREAD

**Issue by tbrodbeck** [microsoft/vscode-docs#3151]
I am referring to the vscode-docs/docs/python/jupyter-support.md Jupiter support of vs code. 

When I press 'Z' while not inserting, the most recent changes are undone. This would not be such a big of a problem, if there would be a way to get the undone changes back (e.g. in case 'Z' is pressed mistakenly). I could not find a way.

**Comment by jmew** [comment]
Thanks for bringing this up to our attention. We currently do not have a redo keyboard shortcut, I will bring this issue up with the team.

**Comment by JoshuaPartlow** [comment]
Thanks @tbrodbeck and @jmew. Since this is now tracked separately and not doc related, I'll close this issue.

**Comment by tbrodbeck** [comment]
Where is this issue tracked now? Sorry for putting it into the wrong category

**Comment by JoshuaPartlow** [comment]
@jmew to confirm, but I believe it's tracked at https://github.com/microsoft/vscode-python/issues/7999
