### ISSUE TITLE
Update proxy doc for extensions

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-docs#3167]
https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support
> Extensions don't benefit yet from the same proxy support that VS Code supports. 

That's no longer true with @chrmarti work a while ago.

@chrmarti It would be good to know if/how the old settings (`http....`) are still used.
Also some steps on how to test whether the proxy settings work.

**Comment by chrmarti** [comment]
The existing settings still work for extensions. The 'strict SSL' one has never been supported widely and is ignored by the code I added (my feeling is that we should remove that setting).

Proxy support for extensions is not on the same level as the built-in support from Chromium. (Proxy authentication in particular is still lacking.)

**Comment by chrmarti** [comment]
Actually my work doesn't use `http.proxyStrictSSL` nor `http.proxyAuthorization`. Previously extensions would have to read and implement these themselves, so maybe there are not many extensions supporting them.

**Comment by chrmarti** [comment]
@aeschli Should we remove the `http.proxyStrictSSL` and `http.proxyAuthorization` settings?

**Comment by aeschli** [comment]
@chrmarti We need to make a search through all extensions to see if anyone is using it.

**Comment by gregvanl** [comment]
Closing, please reopen if there are any doc updates necessary.
