### ISSUE TITLE
Docs on using PYTHONPATH misleading/wrong

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#3168]
https://code.visualstudio.com/docs/python/environments#_use-of-the-pythonpath-variable suggests that setting PYTHONPATH per shell will affect tooling. While it **will** affect any tools the user executes manually through the terminal, it **won't** affect anything the extension does on the user's behalf. (This was brought up in Microsoft/vscode-python#7841.)

**Comment by brettcannon** [comment]
And to be absolute clear, this setting won't affect anything the extension does on the user's behalf that isn't sent into the terminal (e.g. file execution and debugging will be affected, but things like running a formatter or linter for the user will not).

**Comment by JoshuaPartlow** [comment]
Updated with PR https://github.com/microsoft/vscode-docs/pull/3282
