### ISSUE TITLE
Tables are not responsive and overlap with the sidebar

### ISSUE THREAD

**Issue by eunicode** [microsoft/vscode-docs#3175]
Steps to reproduce
1. Visit this link https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations#_textmate-themes
2. Reduce the browser width
3. Observe that the table extends past the width of its parent container and overlaps with the right sidebar

Expected behavior

Tables don't overlap with the sidebar at any browser width.

Actual behavior

Tables overlap with the right sidebar at a certain range of browser widths. 

<img width="968" alt="table-overlap-sidebar" src="https://user-images.githubusercontent.com/28845173/67157727-0b264200-f2e5-11e9-981c-67a96dce1815.png">

**Comment by gregvanl** [comment]
Hi @eunicode Thank you for reporting this issue. It looks like the blog post is using embedded HTML rather than a Markdown table, as we do in most of our documentation. Given that this is an older blog post with relatively low page views, I don't think we will fix this.
