### ISSUE TITLE
Docker container for Bottle

### ISSUE THREAD

**Issue by c-rei** [microsoft/vscode-docs#3179]
I am reading "Create Docker containers for Python" (https://code.visualstudio.com/docs/python/tutorial-create-containers), that contains "how to configure those servers for both Django and Flask web apps".
But I want to known how about Bottle web apps with VS Code. Could you give any advises?

My goal is to deploy Bottle web apps to Azure with VS Code.

Thanks your any helps.

**Comment by prashanthmadi** [comment]
While others help you with answer for your query.. leaving below sample i wrote long back on running bottle app in azure app services windows. 

https://github.com/prashanthmadi/azure-bottle-httpplatformhandler

**Comment by brettcannon** [comment]
The instructions on getting started are exactly the same, just change your `requirements.txt` file to not specify Django or Flask and specify Bottle instead.

**Comment by c-rei** [comment]
Hi, MR. prashanthmadi
Thanks for your responses. I'v read your sample, I think it's a sample for windows, but I wand a sample for Linux. Because the Python on Azure with windows is not recommend.

**Comment by c-rei** [comment]
Hi, MR. brettcannon
Thanks your advises, I'll try it, and give your results.
Thanks a lot.
Best Regards.

**Comment by c-rei** [comment]
I tried to deploy a bottle sample with Visual Studio Code. But I got an error while I deploy my app like below.
17:21:09 az4jsc-webapp13: Creating zip package...
17:21:14 az4jsc-webapp13: Starting deployment...
17:21:47 az4jsc-webapp13: Fetching changes.
17:21:47 az4jsc-webapp13: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/dd7f4ab8-3356-4a37-b7c1-f9e2d0b95619.zip (7.46 MB) to /tmp/zipdeploy/extracted
17:21:58 az4jsc-webapp13: Updating submodules.
17:21:58 az4jsc-webapp13: Preparing deployment for commit id 'f7d21f725c'.
17:21:58 az4jsc-webapp13: Generating deployment script.
17:21:58 az4jsc-webapp13: Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"'.
17:22:00 az4jsc-webapp13: Generating deployment script for Web Site
17:22:00 az4jsc-webapp13: Generated deployment script files
17:22:00 az4jsc-webapp13: Running deployment command...
17:22:00 az4jsc-webapp13: Command: "/home/site/deployments/tools/deploy.sh"
17:22:00 az4jsc-webapp13: Handling Basic Web Site deployment.
17:22:00 az4jsc-webapp13: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
17:22:00 az4jsc-webapp13: Copying file: 'auth.py'
17:22:00 az4jsc-webapp13: Copying file: 'example.py'
17:22:00 az4jsc-webapp13: Copying file: 'requirements.txt'
17:22:00 az4jsc-webapp13: Copying file: 'startup.txt'
17:22:00 az4jsc-webapp13: Deleting file: 'hostingstart.html'
17:22:00 az4jsc-webapp13: Copying file: '.vscode/settings.json'
17:22:00 az4jsc-webapp13: Copying file: '__pycache__/auth.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/pyvenv.cfg'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/bottle.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/easy_install.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/mccabe.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/six.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/__pycache__/bottle.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/__pycache__/easy_install.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/__pycache__/mccabe.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/__pycache__/six.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__init__.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pkginfo__.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/_ast.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/arguments.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/as_string.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/bases.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/builder.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/context.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/decorators.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/exceptions.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/helpers.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/inference.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/manager.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/mixins.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/modutils.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/node_classes.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/nodes.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/objects.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/protocols.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/raw_building.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/rebuilder.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/scoped_nodes.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/test_utils.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/transforms.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/util.py'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/__init__.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/__pkginfo__.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/_ast.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/arguments.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/as_string.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/bases.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/builder.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Copying file: 'env/Lib/site-packages/astroid/__pycache__/context.cpython-37.pyc'
17:22:01 az4jsc-webapp13: Omitting next output lines...
17:22:02 az4jsc-webapp13: Error: ENOENT: no such file or directory, stat '/tmp/zipdeploy/extracted/env/Lib/site-packages/bottle-0.12.17.dist-info/bottle.cpython-37.pyc,,
17:22:02 az4jsc-webapp13: '
17:22:02 az4jsc-webapp13: An error has occurred during web site deployment.
17:22:02 az4jsc-webapp13: Kudu Sync failed
17:22:02 az4jsc-webapp13: \n/opt/Kudu/Scripts/starter.sh "/home/site/deployments/tools/deploy.sh"
17:22:03 az4jsc-webapp13: App container will begin restart within 10 seconds.
17:22:14 az4jsc-webapp13: Waiting for long running command to finish...
17:22:15: Deployment to "az4jsc-webapp13" completed.

It looks can't find a bottle.cpython-37.pyc file in the folder env/Lib/site-packages/bottle-0.12.17.dist-info.

**Comment by prashanthmadi** [comment]
try setting below as app setting in app ... looks its failing during unpacking of zip..

WEBSITE_RUN_FROM_PACKAGE=1

**Comment by JoshuaPartlow** [comment]
Closing since it seems like this question was answered. Feel free to reactivate if that's not the case or you have additional feedback on the docs.
