### ISSUE TITLE
vs code 开发 (development) java

### ISSUE THREAD

**Issue by CharlesChaos** [microsoft/vscode-docs#3184]
我以前开发.net,后来被换部门开始学习java开发。我一直觉得微软的开发工具好用，就用vscode进行开发vscode，一开始没有遇到什么问题，后来有一天打开项目（项目是spring-boot maven项目），vscode显示一致加载刷新项目的过程中
![image](https://user-images.githubusercontent.com/30902613/67547584-11c41780-f732-11e9-815f-1799f545c5e2.png)，目前一直没有解决这个问题，现在不得不用intellij来进行开发项目，所有想请问怎么解决这个问题呢

**Comment by gregvanl** [comment]
Google translate text: 
I used to develop .net, and then I switched departments to start learning java development.
I have always thought microsoft's development tools are useful, with vscode to develop vscode, initially did not encounter any problems, and then one day open the project (the project is spring-boot maven project), vscode shows the consistent loading of refresh project sin
{image},
has not solved this problem, now have to use intellij to carry out the development project, all want to ask how to solve this problem?

**Comment by gregvanl** [comment]
Hi @CharlesChaos This looks like an issue with the Java extension rather than with the VS Code documentation. I recommend opening an issue in the Java extension repo https://github.com/redhat-developer/vscode-java/issues.
