### ISSUE TITLE
VS Code doesn't see virtual environment during the Flask tutorial in VS Code

### ISSUE THREAD

**Issue by alanwatson** [microsoft/vscode-docs#3191]
Following the VS Code Flask tutorial, [here](https://code.visualstudio.com/docs/python/tutorial-flask)

During steps 4 & 5 VS code does not see the created virtual environment.

**Comment by JoshuaPartlow** [comment]
Hi @alanwatson - When you say VS Code doesn't see the created virtual environment, do you not even see a directory for it in the VS Code File Explorer? I've run through the step and verified it should work as written. One other thing you could try is deleting the environment folder (if you have one), opening the workspace folder in VS Code and try creating the environment from the VS Code terminal. You should even be prompted after the creation to set it as the default for the workspace (automatically activates the environment for any new terminal). If you want to use the terminal you created it in, you should just need to use the activate script. Does that help?

**Comment by JoshuaPartlow** [comment]
Closing since there hasn't been a response. Feel free to reopen if you're still having a problem.
