### ISSUE TITLE
Connect to a remote Jupyter server

### ISSUE THREAD

**Issue by ShujiMIYOSHI** [microsoft/vscode-docs#3195]
I have one clarification.

[Here](https://code.visualstudio.com/docs/python/jupyter-support#_connect-to-a-remote-jupyter-server) you describe how to connect to a remote Jupyter server.

Is there anyway to connect Azure Notebooks?
If yes, please write the method.
If no, please write the information. For example, Azure Notebooks is not supported.

**Comment by JoshuaPartlow** [comment]
Hi @ShujiMIYOSHI - Azure Notebooks doesn't support that scenario. If you have additional questions about Azure Notebooks, you can open an issue on their [repo ](https://github.com/Microsoft/AzureNotebooks/issues) or [docs](https://docs.microsoft.com/en-us/azure/notebooks/azure-notebooks-overview).
