### ISSUE TITLE
The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was  included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by LarryInfiniteMX** [microsoft/vscode-docs#3198]
"
> python -m venv venv
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ python -m venv venv
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
"

This error is shown after installing and adding python to the path. It is simply there and does not let me work and set the environment. The extensions are added too.

Do you have any suggestions on how to fix it?
Thanks in advance,

**Comment by JoshuaPartlow** [comment]
Closing since there hasn't been a response. Feel free to reopen if you're still having a problem.

**Comment by MarvelZGB** [comment]
Hi! Same problem here, installed Python 3.8 and the latest version of VS Code, I'm using Windows 10  and Python is recognized both in Command prompt and Powershell but In VS Code I get the above mentioned error...

**Comment by JoshuaPartlow** [comment]
Hi @MarvelZGB - Thanks for confirming it's working for you at cmd and in PowerShell. Could you also let us know which distribution of the Python interpreter you're using? (Python.org, Anaconda, etc)

**Comment by MarvelZGB** [comment]
Hey, figured it out, you just type py for starting python in Visual Studio Code in Win 10. I'm using Python.org interpreter.

**Comment by JoshuaPartlow** [comment]
Hi @MarvelZGB  - That was what I was asking, thanks for clarifying. I'm glad you got the Python launcher working. I'll take a look at if there's a way to make that usage clearer in the tutorial.

**Comment by kk348** [comment]
Hi All,installed Python 3.7.4 and the latest version of VS Code, I'm using Windows 10 and Python is recognized in Command prompt a but In VS Code I get the above mentioned error...

**Comment by russianmax** [comment]
Instead of python cmd in the shell use py

**Comment by fahadismail053** [comment]
if it says 'python' is not recognized use 'py' and vise versa.

**Comment by ihatemylifeAC** [comment]
Hi , I have this problem too because I download python from python.org and I test it on command prompt and powershell but in visual studio I can't programming.

**Comment by JoshuaPartlow** [comment]
Hi @ihatemylifeAC - Have you tried walking through the [Python tutorial for VS Code](https://code.visualstudio.com/docs/python/python-tutorial), it does a good job of helping with initial setup and getting started.

**Comment by Pushkar222-n** [comment]
Hi @JoshuaPartlow is using py instead of python some sort of problem, or error caused due to fault in downloads or what??

**Comment by docentYT** [comment]
The same problem.

**Comment by HS-1** [comment]
using py solve my problem, eg instead of 
python -m pip install matplotlib 
this is working
py -3 -m pip install matplotlib

**Comment by yaxye8123** [comment]
I think I get it fist install the browser with python3 then you can use cmd command is python3 then here you go

**Comment by Analystdeveloper** [comment]
Nobody can figure out this problem, i'm sick of pyhton shit

**Comment by ebadilla10** [comment]
@Analystdeveloper have you tried to add python in the enviroment variables?

**Comment by Analystdeveloper** [comment]
Hi , I did but still not working 
"I’m thankful for my struggle because without it, I wouldn’t have stumbled across my strength."

 

    On Saturday, July 3, 2021, 03:24:34 PM EDT, Esteban Badilla A. ***@***.***> wrote:  
 
 


@Analystdeveloper have you tried to add python in the enviroment variables?

**Comment by 1-Nikita** [comment]
I am facing the same problem in vscode ,i have Anaconda and python.org installed,i have selected python3.9 as my interpreter  and set it to default path, also added python to environment variables 
can anyone help me?

**Comment by shiffananazeema** [comment]
SOLVED...
     If it was not working that means it was not ON to activate the python 
1. Open Settings
2. Search for 'Manage app execution alias'
3. Turn On the python that you need to Use  :)

**Comment by SPMLSanower** [comment]
> if it says 'python' is not recognized use 'py' instead and vise versa.

worked for me in pycharm

**Comment by WldGeese** [comment]
> if it says 'python' is not recognized use 'py' instead and vise versa.

Would you be able to clarify where I use 'py' instead of 'python'?

**Comment by 9964658622** [comment]
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ python face_rec.py
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by MoosaZK** [comment]
How can I set it to py?

**Comment by Authier** [comment]
> SOLVED... If it was not working that means it was not ON to activate the python
> 
>     1. Open Settings
> 
>     2. Search for 'Manage app execution alias'
> 
>     3. Turn On the python that you need to Use  :)

I changed this portion from
"python": "python -u",
to
"python": "py -u",

**Comment by rsrnov21** [comment]
I have tried to create project using cookiecutter in powershell. But it thru an error as 

cookiecutter : The term 'cookiecutter' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cookiecutter gh:cjolowicz/cookiecutter-hypermodern-python \ --checkou ...
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cookiecutter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by maharanavikas** [comment]
I have python 3.11 installed on my system.
I also set the environment variables still I'm getting this error while running odoo.conf

python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python get-pip.py
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by IshaSiddharth** [comment]
> I have python 3.11 installed on my system. I also set the environment variables still I'm getting this error while running odoo.conf
> 
> python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1
> 
> * python get-pip.py
> * ```
>     + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

Hi,
I am using pycharm IDE to practice python and in the terminal, i was the below error :

PS C:\Users\ishas\Desktop\My Python> helloworld.python                
helloworld.python : The term 'helloworld.python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ helloworld.python
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (helloworld.python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

My file name was helloworld.py
but when i tried running helloworld.py, i got the above error
however, when I tried phython helloworld.py
it worked.

sharing the result below :

PS C:\Users\ishas\Desktop\My Python> python helloworld.py
hello world!
PS C:\Users\ishas\Desktop\My Python>

**Comment by Winz-ai** [comment]
I have same issue in VS, can't run program via button on right top corner or right click mouse menu, but I can run it by typing run command in terminal "py filename.py"

**Comment by TriTechX** [comment]
I have a solution that worked for me. I opened the Python console, and typed in the following, which for some reason worked when the terminal wouldn't.
>>> import os
>>> os.system("python -m venv venv")

hope that helped!

**Comment by FXTrader-py** [comment]
> I have same issue in VS, can't run program via button on right top corner or right click mouse menu, but I can run it by typing run command in terminal "py filename.py"

Good day have you been able to solve this problem, I'm having a similar issue

**Comment by rohagul** [comment]
> SOLVED... If it was not working that means it was not ON to activate the python
> 
> 1. Open Settings
> 2. Search for 'Manage app execution alias'
> 3. Turn On the python that you need to Use  :)

thank you! This works

**Comment by rossp2000** [comment]
I’m having trouble running a programme in python can anyone help ? I click new terminal and type py <filename.py> and nothing happens

**Comment by tprajwol** [comment]
I also had similar problem but going through different documentation I didn't get much help but
Single website help well to me to solve this problem
https://docs.python.org/3/library/venv.html
 I did face the problem while creating virtual environment.
![Screenshot 2024-03-09 062642](https://github.com/microsoft/vscode-docs/assets/138902317/6573cd98-7c15-4c69-aac7-668af3c555aa)
While going through documentation of venv and trying to solve the problem 
**c:\>python -m venv c:\path\to\myenv**
![Screenshot 2024-03-09 062717](https://github.com/microsoft/vscode-docs/assets/138902317/ebce4433-54a2-43f0-8815-d05bba1c4780)
this is the code that you should try if you are facing this problem 
then go to the created path by 
follow this command one by one:
**cd path** 
**ls**
**cd do**
**ls**
**cd myenv**
**ls**
**cd scripts**
**ls**
Here you can find the activate.bat file
![Screenshot 2024-03-09 062947](https://github.com/microsoft/vscode-docs/assets/138902317/473eb0af-7ed4-4f8e-a0b6-42391e5ea771)

**./activate.bat**
