### ISSUE TITLE
[Python] Add section about supported substitutions to settings page.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode-docs#3199]
While VS Code does not support much [variable substitution in settings](https://code.visualstudio.com/docs/editor/variables-reference#_is-variable-substitution-supported-in-user-and-workspace-settings), the Python extension does.  However, I didn't find any mention of this in the extension's documentation.  There is a ["settings reference"](https://github.com/microsoft/vscode-docs/blob/master/docs/python/settings-reference.md) page, but it doesn't say anything about substitution, other than the fact that some of the default values use the substitution syntax.

So a section on that page about supported variable substitution would be a useful addition, along with a one-sentence mention at the top of the page about that support (presumably the new *section* would be added to the bottom).  I'd expect the new section to briefly explain how substitution works and then enumerate the supported variables.  Since it's pretty much the same as what VS Code does, I expect it would be enough to give a brief summary, link to [the VS Code docs](https://code.visualstudio.com/docs/editor/variables-reference), and show a minimal table.

Here are relevant details:

* the extension applies variable substitution to all its settings
   * that even applies to nested settings, e.g. "python.autoComplete.extraPaths"
   * see use of `systemVariables.resolveAny()` in [the code](https://github.com/microsoft/vscode-python/blob/master/src/client/common/configSettings.ts)
* the substitution behavior is the same as that of VS Code
* the supported variables mostly mirror the [predefined variables of VS Code](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables)
* code for the supported variables: https://github.com/microsoft/vscode-python/blob/master/src/client/common/variables/systemVariables.ts#L119-L177

**Comment by ericsnowcurrently** [comment]
@luabud

**Comment by JoshuaPartlow** [comment]
@luabud @ericsnowcurrently - Updated with PR https://github.com/microsoft/vscode-docs/pull/3282. Please take a look and feel free to reopen if you think more is needed or something needs additional clarification.
