### ISSUE TITLE
Dead link in blog post

### ISSUE THREAD

**Issue by tborychowski** [microsoft/vscode-docs#3205]
In the [latest blog post](https://code.visualstudio.com/blogs/2019/10/31/inspecting-containers) there's a link to a gh repo: 
`https://github.com/microsoft/vscode-express-sample.git`.
That repo doesn't seem to exist.

**Comment by gregvanl** [comment]
OK, I can't reach it if I'm not signed into GitHub. I'll contact the owner to make it public.

**Comment by gregvanl** [comment]
@tborychowski Can you try again? The repo should be public now.

**Comment by tborychowski** [comment]
works now, thanks!
