### ISSUE TITLE
How to add auto-completion function to VSC in node?

### ISSUE THREAD

**Issue by fantasyKing** [Microsoft/vscode-docs#321]
I want to use VSC to program node.But I don't konw how to add auto-completion function to VSC just like webstorm does.

**Comment by Gigabyte-Giant** [comment]
IntelliSense can be, and is, provided to Visual Studio Code, for many APIs (including Node's), through the use of TypeScript Definition (`*.d.ts`) files.

I've found [this document](https://code.visualstudio.com/Docs/runtimes/nodejs#_intellisense-and-typings) to be a great reference for answering this exact question, so perhaps it will be of use to you...

-- Brynden

**Comment by gregvanl** [comment]
Please reopen if you see any issues.
