### ISSUE TITLE
Extension manifest's contributes.configuration section is poorly documented

### ISSUE THREAD

**Issue by devbubba** [microsoft/vscode-docs#322]
Greetings,

Over the past week, I decided to try and create an extension for Visual Studio Code, to familiarize myself with the extension framework.
I'm pleased to report that all went [fairly] well, however, I found that the `contributes.configuration` side of an extension's manifest, [is poorly documented](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration).

Yes, Visual Studio Code's IntelliSense does provide _some_ information about properties that can be used within `contributes.configuration`, **I feel there should be quite a bit more documentation on the topic**.

Due to lack of documentation, I ended up spending roughly 2.5 hours, just trying to create [this](https://github.com/Gigabyte-Giant/vscode-file-header-comment-helper/blob/5c3e9be3788caee19e909ee42ef4909f209de7d6/package.json#L44-L83) seemingly simple configuration.

To me, the ability to harness Visual Studio Code's built-in configuration system, from directly within an extension, is one of the most powerful features of the extension API (so far, at least).

-- Brynden

**Comment by gregvanl** [comment]
Closing. Please reopen if you feel the documentation is still insufficient. It has had several review passes and updates by the VS Code team .

**Comment by HerbCaudill** [comment]
This really needs to be reopened. There is no comprehensive documentation of the
`contributes.configuration` API, just a couple of examples. (I'm looking at
[this page](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) -
maybe there's more information elsewhere?)

Here are some specific questions I have that the documentation doesn't answer:

- Where do the titles of the configuration settings come from? As far as I can tell, they're broken
  out from the property name, e.g. `"gitlens.advanced.blame.dateFormat": {...}` becomes

  > Gitlens > Advanced > Blame: **Date Format**"

  but there's no way to figure that out other than trial and error. There's also no indication of
  whether there's an override for providing more control over things like capitalization.

- What does it mean when an array of types is provided? e.g.

  ```json
  "type": [
    "object",
    "array"
  ]
  ```

- What's the deal with `enum` and `items`? In other extensions' manifests, sometimes I see

  ```json
  "items": {
      "type": "string",
      "enum": [
          "gutter",
          "line",
          "overview"
      ],
      "enumDescriptions": [
          "Adds a gutter glyph",
          "Adds a full-line highlight background color",
          "Adds a decoration to the overview ruler (scroll bar)"
      ]
  },
  ```

  but sometimes I just see the `enum` and `enumDescriptions` as direct properties of the config.

- Other properties I've seen that are completely undocumented:
  - `maxItems` and `minItems`
  - `uniqueItems`

**Comment by HerbCaudill** [comment]
In response to a question about the configuration manifest in #22375, someone points out that this is JSON Schema (or a superset thereof, I guess?). Anyway this should really be made more clear in the docs. I'll submit a PR.
