### ISSUE TITLE
There's no way to reach a hash-link for headings

### ISSUE THREAD

**Issue by in-in** [microsoft/vscode-docs#3225]
It is impossible to reach a hash-link for _H2_ element with a mouse because the link is too far away

browser: Firefox 70

https://code.visualstudio.com/updates/v1_40#_editor

![193121573199148](https://user-images.githubusercontent.com/8797432/68458892-f3234d80-0214-11ea-88f1-3da9e8e52ff4.png)

![v-2019-11-08_10 43 30](https://user-images.githubusercontent.com/8797432/68458935-0afad180-0215-11ea-8bb0-00412a8f0b1b.gif)

**Comment by JamesMudidi** [comment]
Having a similar issue with Google chrome Version 78.0.3904.108 (Official Build) (64-bit)

@gregvanl As mentioned in [2492](https://github.com/microsoft/vscode-docs/issues/2492) and [2491](https://github.com/microsoft/vscode-docs/issues/2491), I am happy to help in fixing the issue but I do have a couple of followups.

> Do we make it visible? [2491](https://github.com/microsoft/vscode-docs/issues/2491)
> Do we make it expand and collapse? [2491](https://github.com/microsoft/vscode-docs/issues/2491)
> Do we make it a dropdown? [2492](https://github.com/microsoft/vscode-docs/issues/2492)
>Do we have another solution to this?

**Comment by gregvanl** [comment]
Doesn't appear to repro on Safari on macOS

**Comment by gregvanl** [comment]
Fixed in vscode-website private repo.

**Comment by gregvanl** [comment]
Looks to be fixed. Tested on Windows 10 with Chrome and Edge.
