### ISSUE TITLE
Update to Settings Reference

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode-docs#3227]
The page [here ](https://github.com/Microsoft/python-language-server#linting-options-diagnostics) should be updated to match [this ](https://github.com/Microsoft/python-language-server#linting-options-diagnostics) table.

**Comment by JoshuaPartlow** [comment]
@Anapo14 - Thanks for the pointers, I'll get on that soon.

**Comment by JoshuaPartlow** [comment]
@Anapo14 - It looks like those links are actually the same? I assume the first should be the settings page https://code.visualstudio.com/docs/python/settings-reference#_python-language-server-settings ?

**Comment by JoshuaPartlow** [comment]
Updated with PR https://github.com/microsoft/vscode-docs/pull/3282
