### ISSUE TITLE
Debug adapter process has terminated unexpectedly 

### ISSUE THREAD

**Issue by mariuswang007** [Microsoft/vscode-docs#323]
I run php in windows 10.
I have downloaded related xdebug.dll base on my php version, and put it to the php/ext folder.
and installed the php debug tool in vs code which default port is 9000.
Then I set the port of the website to 9000(whatever, just same as php debug tool launch.json) in IIS.
now, when I open debug on vs code, it throw error like the title.
if I set the different port for the IIS website. it could open the debug mode in VS code. but the question is how could I post the request to port 9000 and debug into the code?

I am the new guy for both php and VS Code， I need your help. 
thx so much

**Comment by bekirmavus** [comment]
Does anyone has an answer?

**Comment by egamma** [comment]
This is a question about php debugging which is provided by the php-debug extension. Therefore please ask you question in the corresponding repository https://github.com/felixfbecker/vscode-php-debug/issues.
