### ISSUE TITLE
Send feedback when offline cause weird alert

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode-docs#3230]
Issue type: **Bug**

**Steps**

1. Go to a random doc ([For example](https://code.visualstudio.com/api/extension-guides/webview))
1. Scroll down to the feedback section.
1. Disconnect to the internet (simulate it by Chrome or any other way)
1. On the question `Was this documentation helpful?` click `Yes`.
1. Then click on `Submit` or `Skip this`.

**Expected result**
The website will show a "not connected to the internet" message.

**Actual result**
The website shows an alert with only `undefined` in it.
<img width="670" alt="Screen Shot 2019-11-10 at 0 53 14" src="https://user-images.githubusercontent.com/3723951/68536087-ed815100-0355-11ea-942e-7a6e8fa1b654.png">

**Comment by gregvanl** [comment]
Hi @moshfeu Thank you for submitting an issue. Given that this relates to feedback for online documentation, while a valid issue, I don't think this is a common scenario.

**Comment by moshfeu** [comment]
Your call :)
Didn't try to simulate this but, this alert will probably shows when the feedback server is down. I hope it's a rare case either but what is error handling if not for rare cases :)
