### ISSUE TITLE
Missing key highlights in v1.40 release note

### ISSUE THREAD

**Issue by thinkerdu** [microsoft/vscode-docs#3231]
Reading highlights is much more efficient than reading every change.
![image](https://user-images.githubusercontent.com/28700378/68539711-9b2a4980-03c2-11ea-8f98-c7930b320010.png)
![image](https://user-images.githubusercontent.com/28700378/68539715-aaa99280-03c2-11ea-8e6b-46789b104c61.png)

**Comment by gregvanl** [comment]
Hi @thinkerdu You noticed! Given there were mostly small features in 1.40 and the main message was about GitHub housecleaning, we tested whether folks would miss a highlight section. And you did. We'll be sure to have a highlights section in future release notes.
For 1.40, you can see a highlights list in the social image (used for Twitter) at https://github.com/microsoft/vscode-docs/blob/master/release-notes/images/1_40/release-highlights.png
