### ISSUE TITLE
suggestion for resetting line endings

### ISSUE THREAD

**Issue by matcha440** [microsoft/vscode-docs#3238]
In the docs on remote development, there is a section talking about making line endings consistent between Windows and a container or WSL.

> [Finally, you may need to clone the repository again for these settings to take effect.](https://github.com/microsoft/vscode-docs/blame/master/docs/remote/troubleshooting.md#L480)

I don't feel re-cloning a repo is necessary in this case or even recommended in my opinion.  I would recommend doing the following, which will reset all affected files to use LF line endings without the need to re-clone.
```bash
git rm -rf --cached .
git reset --hard HEAD
```

Would it be possible to add this to the document?

**Comment by gregvanl** [comment]
Hi @matcha440 Thanks for the suggestion. Cloning is probably the simplest way for the settings to be applied and least confusing to beginners. Advanced users will likely know they can just remove the cache and reset.
