### ISSUE TITLE
Recommend SCSS extension for more visibility

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#3240]
It should be on this page: https://code.visualstudio.com/docs/languages/css

For https://github.com/microsoft/vscode/issues/6734

**Comment by octref** [comment]
Updated to include mrmlnc.vscode-scss and mrmlnc.vscode-less.

**Comment by NoelAbrahams** [comment]
@octref I suggest removing this extension from the recommended list as it just does not work:

![image](https://github.com/microsoft/vscode-docs/assets/1106823/96952d80-d3ab-4f9f-8d21-6f628dc1a640)

## Docs Link
https://code.visualstudio.com/docs/languages/css

This is giving people the wrong impression that go-to-definition in external files is possible to achieve in VS Code.
