### ISSUE TITLE
Documentation error in SyntaxHighlightGuide

### ISSUE THREAD

**Issue by InsulinShock** [microsoft/vscode-docs#3258]
On page https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide,
the order is incorrect in the json-yaml conversion:

# Install js-yaml as a development only dependency in your extension
$ npm install js-yaml --save-dev

# Use the command-line tool to convert the yaml grammar to json
$ npx js-yaml syntaxes/abc.tmLanguage.yaml > syntaxes/abc.tmLanguage.json

Should be:
$ npx js-yaml syntaxes/abc.tmLanguage.json > syntaxes/abc.tmLanguage.yaml

**Comment by gregvanl** [comment]
Hi @InsulinShock The documentation is correct. js-yaml is a YAML parser which will output JSON.
Feel free to reopen this issue, if I have misunderstood your issue.
