### ISSUE TITLE
support Korean and other localized documentation

### ISSUE THREAD

**Issue by ChungSangHee** [microsoft/vscode-docs#3260]
Issue Type: <b>Feature Request</b>

I need to support 'Korean help document(tag, tutorial, ect......)' more than now~ PLZ~~

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:57:43.593Z)
OS version: Darwin x64 18.7.0

**Comment by gregvanl** [comment]
Closing old issue, not planning to localize the current version of the website.
Localization will be considered in future versions of code.visualstudio.com
