### ISSUE TITLE
Best practices in handling .code-workspace files

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode-docs#3264]
Semantically a workspace is hierarchically above the folder concept, i.e. a workspace contains (zero or more) folders. This being the case, it makes sense for a .code-workspace file to be outside it's root folders/repositories, even when it's a single folder workspace, like so:
```
/Repos/
    /repository1/           <= Source controlled
    /repository2/           <= Source controlled
    repos.code-workspace    <= Not source controlled
```
So how do you keep .code-workspace files source controlled and how do you share them with your team?

I would love to know how you guys solve this problem and if there's a good solution, I think this would be a very important piece of information that should be added to the documentation.

[Relevant StackOverflow question](https://stackoverflow.com/questions/58985137/how-do-you-source-control-code-workspace-files).

**Comment by gregvanl** [comment]
Hi @andrecasal We don't have any real recommendations for using multi-root workspaces. The feature isn't widely used and repository sets tend to be dev-specific even on the same team depending on the features individual devs are working on (language services, Git integration, debuggers, etc).
A team could decide one repo is the main repo and put a .code-workspace file in that repo and use relative paths to the companion repos they wanted included in the multi-root workspace.

For example using `..` to reference the parent folder works:

```json
	"folders": [
		{
			"path": "."
		},
		{
			"path": "..\\vscode-docs"
		}
```

Another option would be a small repo which just holds the .code-workspace file and README. A team could have several .code-workspace file repos for different development scenarios which might have different repos and settings defined.

**Comment by andrecasal** [comment]
Hi @gregvanl Yeah, as SVC tools (like Git and GitHub) stand, there isn't an integrated and logically coherent way to share workspace files, but those workarounds are useful, thanks!

**Comment by gregvanl** [comment]
Another use of .code-workspace within a repo is to filter folders if you have a large repo. For example, at the root of the vscode-docs repo, you could have a .code-workspace that only includes the docs and release-notes folder:

```json
	"folders": [
		{
			"path": "docs"
		},
		{
			"path": "release-notes"
		}
	]
```

The File Explorer will only include those folders and scope search to those folders. Git will still detect changes outside those folders in the repo (which you could argue is a good thing).

**Comment by andrecasal** [comment]
Hey @gregvanl! Thanks for the use-case. That does seem to violate the modularity principle though: if the repo is so large that it would be helpful to filter folders, it should be modularised instead.

**Comment by mewc** [comment]
Helpful if your managing lots of repos, or you want to reference various code across many repos. 
Going into somewhere new, im finding this helpful

a repo for workspaces that are for different contexts across many repos, or subdividing by path for different use cases.

speed of use, particularly for unfamiliar territory
