### ISSUE TITLE
Why I can't watch the vector msg in tutorial?

### ISSUE THREAD

**Issue by ShawnLinLoveLife** [microsoft/vscode-docs#3265]
Hi all, I am following the tutorial below:
https://code.visualstudio.com/docs/cpp/config-clang-mac

However, I can not watch the value of vector **msg**. It shows that the size of **msg** is 0. I could see the value of **word**. Do I config LLDB wrong or misconfig something else?

Thanks in advance!

![image](https://user-images.githubusercontent.com/9366170/69472860-46d39080-0dea-11ea-9c76-2b529f130704.png)

My launch.json file:
```
{
    "version": "0.2.0",
    "configurations": [

      {
        "name": "(lldb) Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/helloworld.out",
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": true,
        "MIMode": "lldb",
        "logging": {
          "trace": true,
          "traceResponse": true,
          "engineLogging": true
        }
      }
    ]
}
```

My lldb version:
```
(lldb) version
lldb-1000.0.38.2
  Swift-4.2
```

My VS Code related information:
```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by gregvanl** [comment]
I can watch msg with the config-wsl setup. Might be something related to macOS setup.

**Comment by gregvanl** [comment]
Hi @ShawnLinLoveLife Thank you for reporting this. This looks like a known issue and you can track it at https://github.com/microsoft/vscode-cpptools/issues/1768 in the C++ extension repo.
