### ISSUE TITLE
Improving readability in introductory video page

### ISSUE THREAD

**Issue by waterpolymer** [microsoft/vscode-docs#3268]
The opening paragraph found on the [Introductory Video page](https://github.com/Microsoft/vscode-docs/blob/master/docs/getstarted/introvideos.md) is a little awkward to read and feels inconsistent with the atmosphere it tries to set up by opening with "Start your journey."

The reasoning for using JavaScript in the videos is strange since VS supports other languages out of the box as well. It might be more fitting to simply state the videos will use JavaScript without needing to justify itself.

Lastly some of the descriptions for each listed video explains little and could use more meaningful text (e.g. "Extend VS Code with extensions" to "Add features, themes and more to VS Code with extensions!")

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/3287
