### ISSUE TITLE
Document that environment variables should be strings when configuring the Python debugger

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3269]
When users set the "env" variable in their launch.json, the debugger will fail if they don't add string values to the variables. 
We should document here that it expects strings: https://code.visualstudio.com/docs/python/debugging#_env

For example, as we see in issue https://github.com/microsoft/ptvsd/issues/1950, the user had this configuration:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "env": {
                "Hello": 10
            },
            "console": "integratedTerminal"
        }
    ]
}
```

This config fails because the value for "Hello" should be "10" instead of 10, but we don't have that documented.  

cc @Anapo14 @int19h

**Comment by JoshuaPartlow** [comment]
Updated the env section with PR https://github.com/microsoft/vscode-docs/pull/3283 to read:
Sets optional environment variables for the debugger process beyond system environment variables, which the debugger always inherits. The values for these variables must be entered as strings.

If you think additional is needed, just reopen and let me know.
