### ISSUE TITLE
I have tslint vscode-tslint extension which surfaces annoying errors

### ISSUE THREAD

**Issue by foxjazz** [Microsoft/vscode-docs#327]
I have tslint vscode-tslint extension which surfaces annoying errors
How do I get it to stop displaying the error items or how do I remove an extension?

**Comment by gregvanl** [comment]
Hi Joe,
You can uninstall an extension through the Extensions: Show Installed Extensions and then click the X for the extension you want to remove
You can disable the TSLint extension with the 'tslint.enable' setting in your user or workspace [settings](https://code.visualstudio.com/docs/customization/userandworkspace).
