### ISSUE TITLE
Mention Debugger for Firefox in ReactJS Tutorial

### ISSUE THREAD

**Issue by khalibloo** [microsoft/vscode-docs#3270]
The ReactJS tutorial mentions Debugger for Chrome and Debugger for Edge in the debugging section. It does not mention Debugger for Firefox, however, leading me to incorrectly assume Firefox was unsupported. https://github.com/Microsoft/vscode-docs/blob/master/docs/nodejs/reactjs-tutorial.md#debugging-react

**Comment by gregvanl** [comment]
@khalibloo Thanks for pointing this out since we mention the Firefox debugger extension in other places in the documentation.
Fixed with https://github.com/microsoft/vscode-docs/commit/1ce08df2a301aaa5f5f05fe83d90969231583f6b
