### ISSUE TITLE
Document new setting for activating terminal when Python extension loads

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3272]
There is now a new setting called "python.terminal.activateEnvInCurrentTerminal" that is set to false by default. But if it's set to true and the extension is activated, then when the user opens a terminal it will activate it. This is different than what we used to do because we would only activate the environment if users created a new terminal. 

More details here: https://github.com/microsoft/vscode-python/issues/5330 and here: https://github.com/microsoft/vscode-python/pull/7665.

This will be out in the next month's release

**Comment by gregvanl** [comment]
Looks like this was updated with the referenced PR
