### ISSUE TITLE
[API Docs] Incorrect withProgress type signatures in docs

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode-docs#3278]
The API Docs website says the type signature is
```
withProgress<R>(options: ProgressOptions, task: (progress: Progress<{increment: number, message: string}>, token: CancellationToken) => Thenable<R>): Thenable<R>
```

However, the real signature has `Progress<{increment?: number | undefined, message?: number | undefined}>`.

It seems there's a bug in whatever code is used to generate the docs.

**Comment by gregvanl** [comment]
Closing old issue with no upvotes. Unfortunately the API generation does not preserve the optional "?" declaration.
The workaround is to review vscode.d.ts and see the actual method signature with IntelliSense in the editor.
