### ISSUE TITLE
[Python] Virtual envs not detected in remote-WSL

### ISSUE THREAD

**Issue by neocruiser** [microsoft/vscode-docs#3296]
Connecting remotely to a linux WSL is working. Loading files and setting a working python interpreter also operational. However, once a new virtual environment is created VS does not detect it. Either automatically or after specifying a path under pythonPath in user settings. 

Virtual environments were created on WSL using conda, venv, and virtualenv. None worked on windows10 with python 3.7.4, and latest python extension 2019.

Cheers

**Comment by neocruiser** [comment]
[Resolved] Virtual envs are only recognized if created in VS terminal. If done though an external bash terminal, virtual envs wont be detected.

I will be closing this issue if agreed on. Cheers

**Comment by gregvanl** [comment]
Hi @neocruiser Glad you got this sorted out. If you are using the Python extension, that repo https://github.com/Microsoft/vscode-python/issues is a good place to search for known issues.
