### ISSUE TITLE
Unknown option listed in ES6 Support docs

### ISSUE THREAD

**Issue by scottaddie** [Microsoft/vscode-docs#33]
In the "ES6 Support" section of the Languages --> JavaScript docs, there's mention of a `javescript.validate._surpressSuperWithoutSuperTypeError` option. This doesn't seem to exist.

**Comment by gregvanl** [comment]
This is an internal switch so it doesn't show up in the usual user settings.  Better ES6 support is coming and this switch will likely be removed.  
Thanks again for keeping a close eye on our docs.  There a lot of new content for extensibility which we hope you'll enjoy.
