### ISSUE TITLE
'variables-reference' page not found in left side navigation

### ISSUE THREAD

**Issue by v3470** [microsoft/vscode-docs#3302]
unlike other pages can view title in left side under the USER GUIDE section(like https://code.visualstudio.com/docs/editor/codebasics), https://code.visualstudio.com/docs/editor/variables-reference can only found via search and other pages' reference.

**Comment by gregvanl** [comment]
Hi @v3470 This is by design. We often keep our reference pages out of the main TOC, where space is limited. Did this make it hard for you to find the information you needed?

**Comment by v3470** [comment]
@gregvanl not really hard yet. The reason I found this state is that when I try to know more detail about the `${file}` variable. while directly search the token can not find it but search `variable` does. Comparing with the `emmet` page, just I think the priority of `variables-reference` should be higher.

**Comment by gregvanl** [comment]
Given the current code.visualstudio.com TOC limitation of only two levels, we keep reference topics out of the TOC for now. Reference topics are still visible to search and we link to them where appropriate. We may revisit this if we update our website infrastructure.
