### ISSUE TITLE
For a Microsoft product, you never mention Windows package managers like Scoop and Chocolatey

### ISSUE THREAD

**Issue by Restia666Ashdoll** [microsoft/vscode-docs#3305]
Almost everytime when Windows users have to install something, you ask them to download and install it manually when we can just use Scoop or Chocolatey like `scoop install gcc` or `scoop install node-js`. Heck, sometimes like in Python you even mention Homebrew but not Scoop.

**Comment by gregvanl** [comment]
Hi @Restia666Ashdoll Thank you for the suggestion. PRs are welcome if you have an idea how to integrate your suggestions into the existing document flows. Perhaps a mention in the /docs/setup/additional-components topic?

**Comment by Restia666Ashdoll** [comment]
@gregvanl I made a pull request for Python and it was closed
https://github.com/microsoft/vscode-docs/pull/3223
