### ISSUE TITLE
LINE_COMMENT doesn't behave as shown

### ISSUE THREAD

**Issue by A-Matt** [microsoft/vscode-docs#3306]
I'm gonna put this here as more of a question, but either leads to a Bug-report on Visual Studio Code or a Mistake and a update on here.

--------

Within the [User defined Snippet Document](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/userdefinedsnippets.md) it specifies of a snippet called LINE_COMMENT which allows for people to have a single line comment within their snippet.
> LINE_COMMENT Example output: in PHP // or in HTML 

This works fine in VB `'` + PHP `//` which both have Line comments.
However the HTML example got me confused, as it doesn't support a "Prefix only" line comment.
Testing it in HTML it returns nothing, no console error or anything in Dev Tools.

**Is this something that previously existed, as no Issue on either repository suggests that it did exist, or is this simple a mistake within the documentation?**

Test Sample:
```json
"Large Divider": {
    "prefix": "lgdiv",
    "body": [
        "$LINE_COMMENT ========================================================="
    ],
    "description": "A Large Comment divider."
}
```

**Comment by gregvanl** [comment]
@A-Matt Thanks for pointing this out! It was indeed a documentation mistake.
