### ISSUE TITLE
What's the font in the screenshot which from release 1.41?

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [microsoft/vscode-docs#3308]
<img width="734" alt="WX20191214-235459@2x" src="https://user-images.githubusercontent.com/26108004/70851196-456b2480-1ecd-11ea-8b0c-2c2408ceef51.png">

**Comment by gregvanl** [comment]
Hi @xiaolongGitHub1498, I think the font is InputMono as used in the previous HTML and CSS screenshots. 
@octref can confirm.

**Comment by xiaolongGitHub1498** [comment]
@gregvanl Thanks, I tried, But they have different brackets.
<img width="514" alt="WX20191215-004315@2x" src="https://user-images.githubusercontent.com/26108004/70851766-684d0700-1ed4-11ea-8ae3-3b6360363d22.png">
<img width="753" alt="WX20191215-004626@2x" src="https://user-images.githubusercontent.com/26108004/70851767-684d0700-1ed4-11ea-836f-c95cb240d048.png">

**Comment by octref** [comment]
@xiaolongGitHub1498 Customize "Customize your download", where you can change how certain characters looks: https://input.fontbureau.com/download/
