### ISSUE TITLE
Interpreter is not provided in drop-down to select, though I have configured virtual path for python.exe in my settings file

### ISSUE THREAD

**Issue by yogendramaarisetty** [microsoft/vscode-docs#3310]
```
{
    "python.pythonPath": "venv\\Scripts\\python.exe",
    "prettier.proseWrap": "always"
}
```

**Comment by JoshuaPartlow** [comment]
Hi @yogendramaarisetty - Could you provide some more information. Did you set the value in your user or workspace settings? When you say the virtual environment doesn't appear in the drop-down, where did you create it? Is it part of your workspace and do you have that workspace opened? The following section in the docs provides some information about where the Python extension looks for environments, https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments, which might help as well.

**Comment by JoshuaPartlow** [comment]
Closing due to no reply. If this is still an issue, please reopen.
