### ISSUE TITLE
Document "python.condaPath" in Python environments page

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#3314]
https://code.visualstudio.com/docs/python/environments doesn't mention the [`"python.condaPath"` setting](https://code.visualstudio.com/docs/python/settings-reference).

Brought up as part of https://github.com/microsoft/vscode-python/issues/9190.

**Comment by JoshuaPartlow** [comment]
Added a note to the Conda environments section of environments page w/ PR https://github.com/microsoft/vscode-docs/pull/3335. Please reopen if additional info is needed.
