### ISSUE TITLE
Property miscategorized as event in API doc

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode-docs#3318]
The example I've found is that [`CodeActionContext.only`](https://code.visualstudio.com/api/references/vscode-api#CodeActionContext) is miscategorized as an event by [doc writer](https://github.com/microsoft/vscode-docs/blob/master/api/references/vscode-api.template), but I imagine (without seeing the code) that any property starting with "on" would have this issue.

**Comment by gregvanl** [comment]
@KamasamaK Thanks for pointing this out. Updated API reference will be published shortly.
