### ISSUE TITLE
https://code.visualstudio.com/docs/python/tutorial-django#_create-a-django-app

### ISSUE THREAD

**Issue by brettagreen** [microsoft/vscode-docs#3323]
step 3.
code snippet 'from hello import views' should be 'from . import views'
otherwise, some error about an 'unresolved import' is given

**Comment by JoshuaPartlow** [comment]
Hi @brettagreen - Thanks for trying the tutorial. I ran through the steps to double check and the code works fine for me as written. The hello package is created in step 1 when you run the "python manage.py startapp hello" command. Did everything work fine when you created the Django project in the first section? Your directory structure should be the following at the end of the Create a Django App section:

- venv
- .vscode
- hello
   - \_\_pycache\_\_
   - migrations
   - \_\_init\_\_.py
   - admin.py
   - apps.py
   - models.py
   - tests.py
   - urls.py
   - views.py
- web_project
   - \_\_pycache\_\_
   - \_\_init\_\_.py
   - asgi.py
   - settings.py
   - urls.py
   - wsgi.py
- db.sqlite3
- manage.py

**Comment by brettagreen** [comment]
hi Joshua,

My difficulties may have had something to do with the fact that I did not
create a virtual environment for my project. If so, I apologize for taking
your time with this. My directory structure matches yours save the venv
directory.

Brett

**Comment by JoshuaPartlow** [comment]
Hi @brettagreen - No problem, thanks for providing feedback. I'm not really sure why you had the problem, but I'll close the issue for now. Feel free to reopen it though or start another if you're still having problems.
