### ISSUE TITLE
Snippets in JSON Schema documentation issue

### ISSUE THREAD

**Issue by PetaSoft** [microsoft/vscode-docs#3325]
The documentation of the definition of snippets in JSON schemas at https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas lacks some important information: <br>
The last sentence says:
> Note that defaultSnippets is not part of the JSON schema specification but a VS Code-specific schema extension.

As it is not part of the JSON schema specification You must provide the information how to use such *defaultSnippets* but I cannot find that information anywhere in the JSON language documentation. Normally, a snippet defition in VS Code has a `prefix`part, e.g. (https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets)
```json
{
  "For Loop": {
    "prefix": ["for", "for-const"],
    "body": ["for (const ${2:element} of ${1:array}) {", "\t$0", "}"],
    "description": "A for loop."
  }
}
``` 
It that case, when I want to use that snippet, I type one of the strings which are part of the `prefix` section of the snippet, and I get a suggestion with the `description` part of the snippet. When I now press `Enter`, the body of the snippet is inserted into the document. <br>
However, how do I use one of the `defaultSnippets` defined in a JSON schema file? There is no `prefix` part, and the `label`part does not work, too. That information should be part of the documentation. Otherwise, I cannot use `defaultSnipperts`.

**Comment by PetaSoft** [comment]
@aeschli Well, You used `"defaultSnippets"` as part of a property definition. I just tested it, and it works, but the example in the documentation defines the `"defaultSnippets"` part outside of the `"properties"` part, and that does not work for me. In that case, I do not get the body of the `"defaultSnippets"` part. and I entered many things to get the result but I failed. <br>
Furthermore, the meaning of the `"defaultSnippets"` part in Your example is different from the example in the documentation. In the example in the documentation, I want to enter something and get the stringified `"body"` of the `"defaultSnippets"` part together with the defined tab stops. The schema defines an array of key bindings, and each key binding is an object. The `"defaultSnippets"` part defines such a complete object, and I would expect that I have to enter something, get a suggesting `New keybinding`, and afterwards the object defined by the stringified `"body"` of the `"defaultSnippets"` part is inserted.

**Comment by PetaSoft** [comment]
@aeschli Currenly, I found the solution: I only needed to press `Ctrl+Space` after the opening square brackets to get a suggestion for the `"defaultSnippets"` part of the example at https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas in the documentation. I always tried to enter something to get a suggestion for the default snippet with label `New keybinding` because I only remembered snippets which are triggered by entering a part of a keyword but that is not true in this case. Maybe, You can add a hint in the documentation that one gets a suggestition for the default snippets by pressing `Ctrl+Space` after the opening square bracket. <br>
Furthermore, thank You very much for Your additional example which is different from the original one in the documentation and highlights another kind of default snippets in JSON schema files. You are doing a great job!

**Comment by qbsho** [comment]
I have the issue that the "defaultSnippets"  works with local configuration (pointing to local file), but not with remote (on point to https, http url).

**Working**
````json
{
    "json.schemas": [
        {
            "fileMatch": [
                "*.custom.json",
            ],
            "url": "Users/xxx/custom.vscode.schema.json"
            
        },
        {
            "fileMatch": [
                "*.ldp.json",
            ],
            "url": "Users/xxx/custom.loader.schema.json"
            
        }
    ]
}
````

**JSON Schema working, but suggestion for default not**

**Working**
````json
{
    "json.schemas": [
        {
            "fileMatch": [
                "*.custom.json",
            ],
            "url": "https://example.com/custom.vscode.schema.json"
            
        },
        {
            "fileMatch": [
                "*.ldp.json",
            ],
            "url": "[Users/xxx/dcupl.loader](https://example.com/custom).schema.json"
            
        }
    ]
}
````

Additional vscode-configuration like `json.schemaDownload.enable` didn't fix the issue. 
Which Content-Type should be provided from the server?
