### ISSUE TITLE
Syntax Highlight Guide broken: no grammar provided for source.abc

### ISSUE THREAD

**Issue by brandonkal** [microsoft/vscode-docs#3327]
https://github.com/Microsoft/vscode-docs/blob/master/api/language-extensions/syntax-highlight-guide.md#scope-inspector

After creating the extension and evaluating it in another window with <kbd>F5</kbd>, nothing seems to work. 
Running the command `Developer: Inspect ™ Scopes` returns this warning message:
No grammar provided for <source.abc>

**Comment by mjbvz** [comment]
Did you add the contributions? Please share the extension in its current, non-working state.

**Comment by brandonkal** [comment]
This is my extension in its current (now working) state:
https://github.com/brandonkal/vscode-yaml-embed

If you look at commits 1-4, you can see me following the docs without success.
From commits 5+, you can see I managed to figure things out using lit-html as a starting point. So the issue is that the docs are not perfectly clear.

**Comment by mjbvz** [comment]
I checked out out 9bb96a0f9401ee762a8261a9d756d7d5c3e2af1a

There is a syntax error in one of the grammars (a trailing comma). Once I fixed that, it seems to work:

![Screen Shot 2020-01-24 at 5 35 36 PM](https://user-images.githubusercontent.com/12821956/73114500-f3f08500-3ecf-11ea-8b20-8e623f61f9d5.png)

What specifically wasn't working?

**Comment by brandonkal** [comment]
That's embarrasing. Thank you for looking into this.
It's just that I wasn't able to figure out how to make the grammar working from from the docs but it was the stray comma the whole time!
