### ISSUE TITLE
Pycodestyle docs need some more transition away from old pep8 name

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#3332]
https://code.visualstudio.com/docs/python/linting#_pep8-pycodestyle still links to old doc pages instead of http://pycodestyle.pycqa.org and mentions config files having a `[pep8]` section when its actually now `[pycodestyle]`. Basically anything saying "pep8" that isn't in reference to that being the old name is quite possible outdated and now wrong.

**Comment by gregvanl** [comment]
@brettcannon With @JoshuaPartlow being out, is there someone on the Python extension team who'd like to submit a PR to get this issue updated sooner?

**Comment by brettcannon** [comment]
@gregvanl maybe. It's not a big rush, I just noticed this today.

**Comment by JoshuaPartlow** [comment]
Fixed by https://github.com/microsoft/vscode-docs/pull/3695
