### ISSUE TITLE
https://code.visualstudio.com/docs/python/tutorial-django#_create-a-django-app

### ISSUE THREAD

**Issue by adrian29630** [microsoft/vscode-docs#3334]
Hi
I have been working through the above and had no problem seeing the successful Django page appear when reaching that point in the tutorial.
However, immediately I began to add code I received a "Problem" notice everywhere django was mentioned, for example, [from django.urls import include, path] with an advice that said"message": "unresolved import 'django.urls'".  Severity was noted at 4

Despite this when I completed and sent this to Localhost the code ran correctly and Hello, Django! correctly appeared as expected.

Not sure why this is happening unless it is because I am using Python 3.8.1, which is the most up to date version and your tutorial is older than this (3.8.1. did not appear in the Python select interpreter list for example so I had to write it in).

I am just a bit curious as to why a problem appears but does not seem to stop the code from running correctly.

**Comment by JoshuaPartlow** [comment]
@Anapo14 - any ideas about these warnings with the Django tutorial?

**Comment by brettcannon** [comment]
Is the warning coming from Pylint or "python"/Microsoft Python Language Server? Regardless, it means your configuration isn't set in a way that lets either of those tools find the files, and so it's flagging the imports as trying to pull in something. Are you somehow adjusting `sys.path` manually or `PYTHONPATH`? And if its coming from the Microsoft Python Language Server then  a simple restart of VS Code may solve it.

**Comment by adrian29630** [comment]
Hi. Sorry I meant to get back to you on this. I had to restart VS Code with a new project and the problem did not appear so I am thinking that maybe when installing something, either Django or Python it failed to load correctly and that caused this to happen. Anyway, bottom line is it resolved itself
