### ISSUE TITLE
Update screenshot for debugging part of the Python tutorial 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3339]
https://code.visualstudio.com/docs/python/python-tutorial

This is what shows now:
![image](https://user-images.githubusercontent.com/45497113/71910585-06746b80-3127-11ea-99ec-3e6eef93a879.png)

This is what is in the tutorial:
![image](https://user-images.githubusercontent.com/45497113/71910504-df1d9e80-3126-11ea-8565-b0c29b922896.png)

This week I'll submit a PR for this

**Comment by JoshuaPartlow** [comment]
Addressed by PR https://github.com/microsoft/vscode-docs/pull/3453
