### ISSUE TITLE
vscode does not find python in virtual environment

### ISSUE THREAD

**Issue by jhaggle** [microsoft/vscode-docs#3341]
I moved a folder with a virtual environment to another location. After that vscode can not find the python version. 
It does not show when I press ctrl+shift+p and choose "python:selct interpreter".
Neither does the following work the launch.json file in the debugger:
"pythonPath": "/home/virtualenvs/m12_env/bin/python3"

I use ubuntu 19.10 in a virtual machine on windows 10.

**Comment by brettcannon** [comment]
Virtual environments are not designed to be relocatable. You will have to rebuild the virtual environment so that the symlinks work again.

**Comment by gregvanl** [comment]
Closing as support request answered
