### ISSUE TITLE
Fail to use MSVC to compile C++

### ISSUE THREAD

**Issue by Zeege-0** [microsoft/vscode-docs#3345]
I followed the steps in the tutorial to configure VSCode to use the MSVC compiler and debugger on Windows. However,  it fail to execute "c1xx" `(error D8027)` . The error still occurs after I attempted clicked the "repair" in VS2019 installer. I checked the [documentation](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/command-line-error-d8027?view=vs-2019) for this error but still have no idea about it.

Using `MSVC/14.24.28307/bin/Hostx64/x64/cl.exe` currently.

**Comment by bobbrow** [comment]
Just to double check...  when you opened VS Code, did you do it from the Developer Command Prompt window (e.g. by typing `code` and pressing Enter)?  Without the proper environment variables set, the compiler will not work.

**Comment by gregvanl** [comment]
Closing as no response
