### ISSUE TITLE
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the  spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by kk348** [microsoft/vscode-docs#3347]
Hi All,i have python 3.7.4(python.org) and latest  version of VS Code, I'm using Windows 10 and Python is recognized in Command prompt and  but In VS Code I get the above mentioned error...

**Comment by gregvanl** [comment]
Hi @kk348 Does 'py', the python launcher, work from VS Code? I think with the default Windows python installation from python.org, you only get the py launcher installed in a global location (C:\Windows\py.exe).
You could also try restarting VS Code from your command prompt (`code .`).

**Comment by kk348** [comment]
> Hi @gregvanl thanks for ur response ...i restarted  but issue did not resolve

**Comment by MickeyElZouhery** [comment]
Need any help here

**Comment by YassinElZouhery** [comment]
Hi need any help here

**Comment by JoshuaPartlow** [comment]
Hi @kk348 / @YassinElZouhery - Have you selected a python interpreter via the Command Palette? You would see the selected interpreter in the lower left hand corner (ie. Python 3.7.3, etc). Assuming you have, are you seeing the same response when you try to run using the methods discussed [here](https://code.visualstudio.com/docs/python/python-tutorial#_run-hello-world)?

**Comment by JoshuaPartlow** [comment]
Closing given no recent reply. If you still have problems though, please feel free to re-open.
