### ISSUE TITLE
is how to 'disable trusted domains' documented?

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-docs#3357]
searched for: `disable trusted domains` on this repo. and the site.

looked in https://github.com/microsoft/vscode-docs/tree/master/docs/editor https://github.com/microsoft/vscode-docs/tree/master/docs/getstarted https://github.com/microsoft/vscode-docs/tree/master/docs/customization, doesn't seem like there's anything there.

----

relevant issue threads(according to me):
https://github.com/microsoft/vscode/issues/80595 [locked now]
https://github.com/microsoft/vscode/issues/80592 [locked now]

found the main reason it has to be enabled:
https://github.com/microsoft/vscode/issues/80592#issuecomment-531863343
>There's a legal requirement for Microsoft software for linking to websites that Microsoft has no control on.
from https://github.com/microsoft/vscode/issues/80592#issuecomment-531874887
>Yeah, unfortunately you would have to do it at least once on each machine. But the requirement is MS product has to acquire explicit user consent before it can direct users to other domains it has no control of.

----

I understand its a legal requirement. please, could it be documented?

**Comment by reconix23** [comment]
maybe it will go in https://github.com/microsoft/vscode-docs/blob/master/docs/supporting/faq.md

**Comment by reconix23** [comment]
in vscode press shortcut for 'Show Command Palette'
-  `Manage Trusted Domains` is the relevant option
- press Enter to open it.

The document is actually formatted as json file.


vscode:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:59:13.638Z
----

current workaround is to put 
```
```
