### ISSUE TITLE
Version 1.2 access? Only 1.1.1 (OSX)

### ISSUE THREAD

**Issue by mikeerickson** [Microsoft/vscode-docs#336]
The download links while implying they are 1.2 are actually still 1.1.1 (at least on OSX).

Is there a different location for the 1.2 release?

**Comment by Tyriar** [comment]
@mikeerickson you need the insiders build which are preview builds. I believe 1.2.0 is being released to stable (the blue icon) in 2 days.

http://code.visualstudio.com/insiders

**Comment by mikeerickson** [comment]
@Tyriar Awesome, thx for information!
