### ISSUE TITLE
Review and update C++ language topic

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#3361]
The C++ extension overview topic is consistently in the top 5 pageview topics for code.visualstudio.com but CSAT is relatively low at 60%.

https://code.visualstudio.com/docs/languages/cpp

C++ is still a popular language for education and the VS Code C++ tutorials get high page views and community interaction as seen by number of ratings and comments.

Review verbatim and the topic flow to see what can be done to improve CSAT.

**Comment by capSAR273** [comment]
Is there a way to view specific CSAT details such as the survey results users can provide?

**Comment by gregvanl** [comment]
Hi @capSAR273 We don't currently have a way to publically share user ratings and comments. The best visibility into user sentiment is through reviewing active GitHub issues for vscode-docs.

**Comment by gregvanl** [comment]
Add mention of CMake extension
Add mention of using a devcontainer
