### ISSUE TITLE
Jest test runner

### ISSUE THREAD

**Issue by bmealhouse** [microsoft/vscode-docs#3363]
`mocha` is the only documented VS Code test runner for extensions.

Would you be willing to accept a PR documenting how to use `jest` as a test runner?

I recently released an npm package [jest-runner-vscode](https://github.com/bmealhouse/jest-runner-vscode) that simplifies this process, and I'd be happy to open a PR to document this. The package is currently in use by my VS Code extension: [shifty](https://marketplace.visualstudio.com/items?itemName=bmealhouse.shifty).

**Comment by gregvanl** [comment]
Adding @octref to have a look at your jest test runner.

**Comment by bmealhouse** [comment]
Great, thanks for looking into it!

Let me know If the test runner falls short in any way. I'd be happy to make improvements!

**Comment by octref** [comment]
I look forward to your PR. This will help https://github.com/microsoft/vscode-test/issues/23 and https://github.com/microsoft/vscode-test/issues/37

**Comment by bmealhouse** [comment]
Great, I will get started on this.

**Comment by bmealhouse** [comment]
@octref - I'm also discussing this package with the Jest team, so can we hold off on merging this to make sure everything is clear? See https://github.com/facebook/jest/pull/9542.

**Comment by bmealhouse** [comment]
@octref - Both PRs are ready for review.

`jest-runner-vscode` was not invoked by Jest, so I had the package name wrong (according to the Jest [`runner` documentation](https://jestjs.io/docs/en/configuration#runner-string)).

Since that could be a common source of confusion, I've renamed the package to [`vscode-jest-test-runner`](https://github.com/bmealhouse/vscode-jest-test-runner) and updated the docs accordingly.

Please let me know if you have any questions.

**Comment by gregvanl** [comment]
Closing until the upstream PRs are merged. We can reopen this PR is Jest support is added to the test runner.
