### ISSUE TITLE
Document the PowerShell command necessary to activate Python virtual envrionments

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#3383]
It's covered in https://code.visualstudio.com/docs/python/python-tutorial#_install-and-use-packages (specifically `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process`), but it should probably also be covered in https://code.visualstudio.com/docs/python/environments.

**Comment by gregvanl** [comment]
Fixed by https://github.com/microsoft/vscode-docs/pull/3382
