### ISSUE TITLE
Documentation search can return false positives

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode-docs#3392]
1 At https://code.visualstudio.com/Search, enter `redo` and press Enter
2 Click _Visual Studio Code Tips and Tricks_
3 Using browser Find... or eye, search for `redo`

Expected: documentation on redo
Observed: none

Windows 7 and Google Chrome

Please do not mistake this as a duplicate of https://github.com/microsoft/vscode/issues/90173 .

**Comment by gregvanl** [comment]
This specific case no longer reproduces but it certainly could happen.
This sort of issue may be fixed if we move to another search engine, see https://github.com/microsoft/vscode-docs/issues/2596

**Comment by arusergithub** [comment]
> closed 

Why??
