### ISSUE TITLE
CTRL+V missing from "Key Bindings for Visual Studio Code" page

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode-docs#3394]
Steps:

1 View "Key Bindings for Visual Studio Code" page https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing

Expected: Ctrl+C, Ctrl+X and Ctrl+V (amongst others)
Observed: Ctrl+C, Ctrl+X ... and no Ctrl+V

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/dda18761752af76a53f8dc05b0c8cbd94c60d3a3
