### ISSUE TITLE
CTRL+V missing from "Keyboard shortcuts for Windows" PDF

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode-docs#3395]
Steps:

1 View "Visual Studio Code - Keyboard shortcuts for Windows" PDF https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference

Expected: Ctrl+C, Ctrl+X and Ctrl+V (amongst others)
Observed: Ctrl+C, Ctrl+X ... but no Ctrl+V

Note: Please do not mistake this as a duplicate of https://github.com/microsoft/vscode/issues/90334

**Comment by gregvanl** [comment]
The PDF is a subset of keyboard shortcuts (given limited number of shortcuts that can fit on the page) so leaving off keyboard shortcut that matches platform defaults.

**Comment by chrisjj** [comment]
> The PDF is a subset of keyboard shortcuts (given limited number of shortcuts that can fit on the page) so leaving off keyboard shortcut that matches platform defaults.

So including Ctrl+C and Ctrl+X which match platform defaults is in error?

**Comment by gregvanl** [comment]
Those two keyboard shortcuts are included since they call out that they work on the current line when there is no selection, which is non-default behavior.

**Comment by chrisjj** [comment]
OK, so how about `Home / End Go to beginning/end of line`? Those look like platform defaults to me.
