### ISSUE TITLE
Folding docs seemingly use "region" (undefined) to mean "range"

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode-docs#3396]
https://web.archive.org/web/20200203013511/https://code.visualstudio.com/docs/editor/codebasics

e.g.
You can fold regions of source code using the folding icons on the gutter between line numbers and line start.  ,,, Folding ranges are by default evaluated based on the indentation of lines.

**Comment by chrisjj** [comment]
At least one comment has disappeared from this issue. Is there any way to view all?

**Comment by gregvanl** [comment]
Hmm, not sure why a comment would disappear. Might have been lost when the issue was transferred from the vscode product repo to the vscode-docs documentation repo. What comment is missing?

**Comment by chrisjj** [comment]
> What comment is missing?

At least whatever triggered the bot's https://github.com/microsoft/vscode-docs/issues/3396#issuecomment-581459124 . Assuming the bot isn't deciding itself.
