### ISSUE TITLE
Incorrect Github Actions example section

### ISSUE THREAD

**Issue by kanevk** [microsoft/vscode-docs#3397]
1. Open https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
2. Check this part of the config is incorrect:
```yml
    runs-on: $
```

It should be `runs-on: ${{ matrix.os }}`.

*Note: As I see it's correct in [master](https://github.com/microsoft/vscode-docs/blob/master/api/working-with-extensions/continuous-integration.md#github-actions), but I'm not sure is it some kind of bug or it's just not deployed yet to the website.*

**Comment by gregvanl** [comment]
Likely the website rendering was broken by the double curly braces. I'll try adding an escape character.
