### ISSUE TITLE
Python extension: Document that disabling telemetry also disable A/B tests experiments. 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3401]
To help clarify the issue described here: https://github.com/microsoft/vscode-python/issues/10008. I'll send a PR some day this week 😊.

**Comment by bersbersbers** [comment]
This is obsolete given https://github.com/microsoft/vscode-python/pull/10936, right? I also tested that experiments are working with `"telemetry.enableTelemetry": false`.

**Comment by gregvanl** [comment]
@luabud Can you confirm?

**Comment by luabud** [comment]
Yes that is correct. Sorry that I missed closing this issue! Thanks @bersbersbers for bringing it up.
