### ISSUE TITLE
vscode在macOSV10.15.2安装不了

### ISSUE THREAD

**Issue by sylyie** [microsoft/vscode-docs#3403]
![image](https://user-images.githubusercontent.com/5829395/74392877-6a373600-4e43-11ea-8bdb-14d989641a8f.png)
![image](https://user-images.githubusercontent.com/5829395/74392916-84711400-4e43-11ea-9925-45080f04ec7e.png)

**Comment by gregvanl** [comment]
Hi @sylyie This should be fixed soon. There is a workaround posted at https://code.visualstudio.com/docs/setup/mac#_unable-to-open-on-macos-Catalina.
