### ISSUE TITLE
C++ in VS code no output when running .exe

### ISSUE THREAD

**Issue by Brits420** [microsoft/vscode-docs#3407]
I just installed vs code and set up minw to run my c++ code. I followed all of the steps in the guide. It creates the .exe file and shows up when I run dir. but when I execute it with .\main.exe there is no output in the terminal. 
Please help!
![Capture](https://user-images.githubusercontent.com/53366317/74595232-b2bf4100-5047-11ea-91e1-a32ec44a1f39.PNG)

Brits420!

**Comment by gregvanl** [comment]
Hi @Brits420 Looks like you either need to add `cout << endl` or cout.flush() to output the cout buffer.

**Comment by gregvanl** [comment]
Closing as suggestions given.
