### ISSUE TITLE
Building Gradle Project using VSCode

### ISSUE THREAD

**Issue by n8s16** [microsoft/vscode-docs#3409]
I can't seem to find a solution to this problem so I think this might be a bug. Before, I can easily run my _spring boot gradle project_ in **VSCode** (with Java and Spring Boot extensions) _migrated_ from **STS3**.  I tried to setup VSCode and project (the same way how I setup before) to a new machine. And I encountered this issue:

```
Could not fetch model of type 'BuildEnvironment' using Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip'.
The specified Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip' does not exist.
https://downloads.gradle-dn.com/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip
```

To my understanding, VSCode cannot fetch the specific gradle distribution. But when I tried to build and run the code to STS3 again, it's seems working properly. Thanks in advance.

**Comment by akaroml** [comment]
@n8s16 thanks for reaching out.
This issue is related to Java language support. I created redhat-developer/vscode-java#1285 to further discuss.

**Comment by gregvanl** [comment]
Closing as external issue
