### ISSUE TITLE
Static linking in vscode

### ISSUE THREAD

**Issue by Azri99** [microsoft/vscode-docs#3411]
I have a problem trying to link the header file that i download from the internet.

T have try to include the path in the configuration but it still does not work.

![Capture](https://user-images.githubusercontent.com/61195302/74794166-74eb4280-52fd-11ea-97d0-b86011b4f7d9.PNG)

![Capture1](https://user-images.githubusercontent.com/61195302/74794169-79aff680-52fd-11ea-9aab-10dcef5ab5ef.PNG)

**Comment by bobbrow** [comment]
Adding the path to your `c_cpp_properties.json` configuration does not automatically add it to your build command.

Try adding `-I C:\SQLAPI\include` to your g++ command.

**Comment by gregvanl** [comment]
Closing as suggestion provided.
