### ISSUE TITLE
example-language-server.md needs updating for 2.2.x API changes

### ISSUE THREAD

**Issue by Seairth** [Microsoft/vscode-docs#342]
The document still refers to `TextDocumentIdentifier` instead of `TextDocumentPositionParams`, and `ITextDocument` instead of `TextDocument`.  There may be other issues, but these were the ones I immediately spotted.

**Comment by gregvanl** [comment]
@dbaeumer, I'll update the walkthrough in preparation for PJ's upcoming blog post.

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/06cfd24fe65484240b3c57778e0615e55cfc1081
