### ISSUE TITLE
Accepted keys

### ISSUE THREAD

**Issue by kingma-sbw** [microsoft/vscode-docs#3420]
Add this to accepted keys: ¨

**Comment by gregvanl** [comment]
Hi @kingma-sbw I think you wanted umlaut added to the list of keys available to keybindings on https://code.visualstudio.com/docs/getstarted/keybindings#_accepted-keys. I checked with the engineering team and the key list presented there isn't open-ended and so you wouldn't be able to use umlaut in a keyboard shortcut.

**Comment by kingma-sbw** [comment]
The Umlaut is bound on a swiss German keyboard layout (open Terminal) and hence it is an allowed key. Your enigneering team is wrong

**Comment by alexdima** [comment]
Hi @kingma-sbw 

The section https://code.visualstudio.com/docs/getstarted/keybindings#_accepted-keys from the documentation describes the file format of `keybindings.json`, and the keys that will be parsed from the field `key` of a keybinding item from that file.

Please accept that the documentation is correct, an umlaut will not be parsed into a valid keybinding from a `keybindings.json` file. Your screenshot is from the keybindings editor, not from a `keybindings.json` file, so it is not relevant to the respective documentation section.
