### ISSUE TITLE
'onDidChangeActiveTextEditor' cannot work for ipynb file

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-docs#3424]
I'm currently using onDidChangeActiveTextEditor: Event<TextEditor | undefined> to do vscodeextension project. This works for 'py' and 'hql' file. However, if I use ipynb file, this cannot work. I think the main reason for this is that "*.ipynb" file is not a texteditor, so it could not be treated equally. Could you help enhance this api's capability? Thanks in advance!
As shown below, these two are differently treated by the api.
@octref 

![image](https://user-images.githubusercontent.com/46309533/75333497-30454580-58c1-11ea-9aac-5c4939cd78e1.png)
![image](https://user-images.githubusercontent.com/46309533/75333539-4226e880-58c1-11ea-9bb2-25f558dd7a22.png)

**Comment by zesluo** [comment]
or we can enhance the capability of 'TextEditor ' to let it include 'ipynb' file

**Comment by octref** [comment]
This is impossible for now. You can ask the Python extension which implemented the ipynb support. You can also wait for the upcoming notebook API: https://github.com/microsoft/vscode/issues/90382.

**Comment by zesluo** [comment]
@octref do we have any plan for updating this API? We currently still need to have this one for supporting our tool. Thank you!

**Comment by octref** [comment]
You should ask @rebornix

**Comment by zesluo** [comment]
thank you @octref

**Comment by zesluo** [comment]
pinging. @rebornix  Thanks

**Comment by rebornix** [comment]
`onDidChangeActiveTextEditor` will only be emitted when a text editor becomes active, the Notebook Editor in your case is a webview contributed by Python extension, so it's not covered by this event.

**Comment by zesluo** [comment]
Thanks for your reply! Is it possible to convert webview to text editor or apply webview to the API?

**Comment by rebornix** [comment]
@zesluo I don't think so. cc @mjbvz

**Comment by zesluo** [comment]
@rebornix @mjbvz , or any other recommendation? thanks

**Comment by zesluo** [comment]
@rebornix , @mjbvz , is there any suggestion/workaround about it? I think we still need this. Thanks in advance!
