### ISSUE TITLE
[Python] Update documentation for debugpy

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3425]
in the March release we'll update ptvsd to [debugpy](http://github.com/Microsoft/debugpy).

This will require changes on our documentation:
- https://code.visualstudio.com/docs/python/debugging#_attach-to-a-local-script
- https://code.visualstudio.com/docs/python/debugging#_remote-debugging 
- https://code.visualstudio.com/docs/python/debugging#_google-app-engine-debugging
- https://code.visualstudio.com/docs/python/debugging#_troubleshooting

**Comment by JoshuaPartlow** [comment]
Updated with PR https://github.com/microsoft/vscode-docs/pull/3560
