### ISSUE TITLE
[Python] Add conditional breakpoints to debugging documentation

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3426]
To improve discoverability, we could add a section about conditional breakpoints in the [debugging docs](https://code.visualstudio.com/docs/python/debugging). 

We can link to the VS Code docs on this: https://code.visualstudio.com/docs/editor/debugging#_conditional-breakpoints, but I'd like to highlight what we accept as hit count. For example, it accepts whole numbers and also the formats below:

![image](https://user-images.githubusercontent.com/45497113/75410988-8a9ad200-58d2-11ea-8547-db03c9ac1911.png)

**Comment by JoshuaPartlow** [comment]
Addressed by PR https://github.com/microsoft/vscode-docs/pull/3449
