### ISSUE TITLE
CELA P1_A11y_code.visualstudio.com_WCAG2.1_Homepage_Orientation: When the orientation is changed to portrait, 2 scroll bars appears One vertical and another horizontal bar.

### ISSUE THREAD

**Issue by khansahab15** [microsoft/vscode-docs#3428]
“[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-shbagl%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847575447&sdata=XQqvaO2rFh7p/7F2DmzFj2wgJSiYHGuJV73Xg8hPVbA%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags: #A11ySev1; #A11yTCS; #A11yWCAG2.1; #Benchmark; #CELA P1; #ChromiumEdge; #Orientation; #DesktopWeb; #MAS1.3.4; #Win10; #Visual Studio Code; #CELA P1_A11y_code.visualstudio.com_WCAG2.1

**Environment Details:**
Application Name: code.visualstudio.com
#URL:https://code.visualstudio.com/
Windows Version: Windows10
Browser version: Microsoft Edge 80.0.361.5
Chrome:Version 80.0.3987.106

**Repro Steps:**
1.	Launch the application URL: https://code.visualstudio.com/
2.	Home screen will open
3.	Navigate to display in setting-->system-->display orientation-->portrait. 

**Actual:**
When the orientation is changed to portrait, 2 scroll bars appears One vertical and another horizontal bar.

**Expected:**
When the orientation is changed to portrait, only 1 scroll bars should appear vertical or horizontal.

**User Impact:**
Users will find it difficult to view the data in a single layout .

**Attachment:**
[#3428.zip](https://github.com/microsoft/vscode-docs/files/4260397/3428.zip)

**Comment by gregvanl** [comment]
Hi @khansahab15 This seems to be the behavior for any website on Edge if the zoom level is large enough. I don't think this is specific to the VS Code website. I see two scroll bars when I look at this issue on the GitHub site.

**Comment by khansahab15** [comment]
As received input from SME regarding orientation the requirement was to check if there is any data loss in portrait mode and if the scrollbars were accessible to view data, since the requirement is passing hence closing this bug.

**Comment by Yashi1201** [comment]
As per above comment "As received input from SME regarding orientation the requirement was to check if there is any data loss in portrait mode and if the scrollbars were accessible to view data, since the requirement is passing hence closing this bug."

Adding the closed tag
**GithubTags**:#Closed;

**Comment by 12-shweta** [comment]
CELA_code.visualstudio.com_WCAG2.1_FEB2020;

**Comment by InduPriya1805** [comment]
GithubTags:#CELA_code.visualstudio.com_WCAG2.1_FEB2020;
