### ISSUE TITLE
Integrated terminal documentation should explain different between shell and terminal using git bash

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#343]
See https://github.com/Microsoft/vscode/issues/7286 for context.

The documentation doesn't exist yet but something like this should be added to it when it is.

**Comment by Tyriar** [comment]
Another useful tip, running as administrator in Windows https://github.com/Microsoft/vscode/issues/7407

**Comment by Tyriar** [comment]
Ubuntu Bash on Windows https://github.com/Microsoft/vscode/issues/7691#issuecomment-226126621

**Comment by gregvanl** [comment]
I think there is still more to document. For example, the stdin/stdout/stderr requirement for shells to work in integrated terminal.  Reopening.

**Comment by gregvanl** [comment]
Updated integrated-terminal.md with https://github.com/Microsoft/vscode-docs/commit/ab22263297b8b4c7489dc26c7e3f008501fb4b31
