### ISSUE TITLE
[cpp] Document how to load natvis files into a debug session

### ISSUE THREAD

**Issue by lostgoat** [microsoft/vscode-docs#3440]
The natvis documentation does not explain how to add a natvis file to a project.

For linux this involves setting up the `visualizerFile` field in `launch.json` here:
https://docs.microsoft.com/en-us/cpp/build/launch-vs-schema-reference-cpp?view=vs-2019#c-linux-properties

For windows, I'm not really sure. Some comments online seem to indicate it will be done automatically if the natvis file is in the project root?

It would be great if this information was captured in:
https://code.visualstudio.com/docs/cpp/natvis

**Comment by pus711** [comment]
How to hack bank account

**Comment by WardenGnaw** [comment]
Thank you for pointing out that the docs need to be updated.

`visualizerFile` will also work for the windows c++ debugger (`cppvsdbg`). See [package.json](https://github.com/microsoft/vscode-cpptools/blob/471f9b3701c4f4adef272f1d4abb97aa16fe91cd/Extension/package.json#L1316)

**Comment by gregvanl** [comment]
Closing old issue with only one upvote.
