### ISSUE TITLE
Conda environment not activated

### ISSUE THREAD

**Issue by EzzEddin** [microsoft/vscode-docs#3441]
I have activated a conda environment in vscode and I'm sure it has `pymongo` but it seems vscode doesn't see the interpreter path yet although the status bar shows that the interpreter I'm using is the conda environment that I've activated. So when I import `pymongo` I get this error: `ImportError: No module named pymongo`

**Comment by JoshuaPartlow** [comment]
@EzzEddin - Just to confirm, in the VS Code terminal window you're seeing your activated conda environment. Meaning each line is prepended with parenthesis and the environment name? 

@luabud - any ideas what might be wrong?

**Comment by EzzEddin** [comment]
> @EzzEddin - Just to confirm, in the VS Code terminal window you're seeing your activated conda environment. Meaning each line is prepended with parenthesis and the environment name?

Yes, it's activated on the VS Code terminal window as well.

**Comment by EzzEddin** [comment]
@JoshuaKGoldberg There is a workaround for this; it worked with me on a notebook `.ipynb` not a python file `.py`. So can I run the python file on the conda environment that I want?

**Comment by JoshuaKGoldberg** [comment]
...and by "JoshuaKGoldberg" you meant @JoshuaPartlow, right? 😛

**Comment by EzzEddin** [comment]
Yeah, thank you. Sorry for that! :D

**Comment by JoshuaPartlow** [comment]
Hi @EzzEddin - Have you looked at the troubleshooting section of the [linting docs](https://code.visualstudio.com/docs/python/linting#_troubleshooting-linting). There's a mention there that you might see that message if you have an issue with Pylint and the Python extension.

**Comment by luabud** [comment]
Hi @EzzEddin! Do you get the error when you're running the script manually in the terminal or through the Python extension (e.g. by the play button on the top right?) 

One easy way to make sure it's installed is to go to the activated terminal and enter "python" to open the REPL. then enter "import pymongo". 

If this does seem like a bug in the Python extension to you, would you mind filing an issue on our [repo](https://github.com/microsoft/vscode-python/issues/new?labels=classify%2C+type-bug&template=2_bug_report.md)? And then please fill up the template we have there with your environment information so we can try to understand what's going on (screenshots are also very helpful!)

Thank you! 😊

**Comment by EzzEddin** [comment]
> Hi @EzzEddin - Have you looked at the troubleshooting section of the [linting docs](https://code.visualstudio.com/docs/python/linting#_troubleshooting-linting). There's a mention there that you might see that message if you have an issue with Pylint and the Python extension.

@JoshuaPartlow No the error is `ImportError: No module named pymongo` not the one in the troubleshooting section of linting.

> Hi @EzzEddin! Do you get the error when you're running the script manually in the terminal or through the Python extension (e.g. by the play button on the top right?)

@luabud I get the error when I play the button on the top right corner (or `ctrl+shift+N` shortcut)

> If this does seem like a bug in the Python extension to you, would you mind filing an issue on our repo? 

I did another issue [here](https://github.com/microsoft/vscode-python/issues/10462).

Thank you for your time! :)

**Comment by JoshuaPartlow** [comment]
Closing because it looks like this was addressed in the linked issue (https://github.com/microsoft/vscode-python/issues/10462). If you need anything else though, feel free to open another issue or reactivate this one.
