### ISSUE TITLE
Update Accessibility Conformance Documentation

### ISSUE THREAD

**Issue by khansahab15** [microsoft/vscode-docs#3446]
GitHubTags: #A11ySev1; #A11yTCS; #A11yWCAG2.1; #CELA P1; #Visual Studio Code; #CELA P1_A11y_code.visualstudio.com_WCAG2.1; #A11yAAT;

Recommendation: "Fix and close other bugs before starting accessibility conformance documentation. Any bug that will not be fixed and closed within SLA must be declared in the AAT. The SLA for this bug is also 60 days."

Link to the current AAT entry - https://cela-ra-aat-prod.azurewebsites.net/#/workflow/cfc131ce-9c62-468a-8a59-b4bd5d7421e0

[Update and Republish conformance documentation ](https://microsoft.sharepoint.com/teams/ceacc/SitePages/Update%20and%20re-publish%20conformance%20document.aspx)

**Comment by gregvanl** [comment]
Hi @khansahab15 I'm not really sure what to do with this issue. The AAT entry links looks like it is for NuGet and not the code.visualstudio.com website?

![image](https://user-images.githubusercontent.com/12818376/79180741-9168a000-7dbf-11ea-85a7-1e949566f8c9.png)

If I try to search for code.visualstudio.com in the Find Products section, I don't find anything.

![image](https://user-images.githubusercontent.com/12818376/79180844-cecd2d80-7dbf-11ea-91bc-b35138729f28.png)

**Comment by gregvanl** [comment]
OK, I've done a little more searching and I think the correct AAT entry is https://cela-ra-aat-prod.azurewebsites.net/#/workflow/42189bbd-e2a0-4372-915a-67e8b06d1684.
@khansahab15 Please advise if this is correct.

**Comment by gregvanl** [comment]
My mistake the AAT entry above if for the VS Code product not the VS Code website at code.visualstudio.com.

**Comment by gregvanl** [comment]
Per discussions CELA guidelines at https://microsoft.sharepoint.com/sites/accessibility/SitePages/Accessibility-Assessment-Tool-FAQ.aspx, the code.visualstudio.com website should not need an accessibility conformance report. Specifically siting: "Is the website targeted to enterprise, but available to the general public?  If yes, NO conformance statement required (e.g., community.dynamics.com; azure.microsoft.com/status, msdn.com), but see bullet above pertaining to sites localized for France."
The VS Code website code.visualstudio.com is similar to msdn.com (now docs.microsoft.com) and is not localized for France.
