### ISSUE TITLE
how to deploy this docs site?

### ISSUE THREAD

**Issue by kennethzhu** [microsoft/vscode-docs#3463]
I couldn't visit the fllowing URLs, and I wonder how to deploy this docs contents to my private web site?

const URL = `https://${GITHUB_TOKEN}@github.com/microsoft/vscode-website`
const TAS_URL = `https://${GITHUB_TOKEN}@github.com/microsoft/TryAppServiceClient`

Thanks.

**Comment by gregvanl** [comment]
Hi @kennethzhu, vscode-website is our private website infrastructure repository. We don't provide a way for the community to build or run our website directly.
