### ISSUE TITLE
Checking ssh skips correct version

### ISSUE THREAD

**Issue by aftersought** [microsoft/vscode-docs#3465]
I am running Remote-SSH on Windows, using [OpenSSH for Windows](https://github.com/PowerShell/Win32-OpenSSH/releases).

Starting from today, it broke down, as it now skips over default `ssh` installed in the system and goes to various other non-functioning ssh versions:

```
[16:15:13.906] Using commit id "b0791e5236f462fbb785e9a00319705607cefb9d" and quality "insider" for server
[16:15:13.907] Install and start server if needed
[16:15:13.911] Checking ssh with "ssh -V"
[16:15:13.979] > OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
[16:15:13.980] Checking ssh with "C:\windows\System32\OpenSSH\ssh.exe -V"
[16:15:13.982] Got error from ssh: spawn C:\windows\System32\OpenSSH\ssh.exe ENOENT
...
```

I have checked manually that `ssh` command works in cmd. In fact, it seems it works for Remote-SSH as well, but for whatever reason it is unhappy with the version and tries other SSH versions. 

Please advise how to disable version checking so I can use the default `ssh` again for development.

**Comment by aftersought** [comment]
Managed to solve the issue by manually specifiying path to correct ssh in settings.json: `"remote.SSH.path": "C:/Program Files/OpenSSH/ssh.exe"`.

**Comment by roblourens** [comment]
Could you share the full log and tell me what the actual issue is? We prefer using an ssh that isn't `OpenSSH_for_Windows` due to bugs in it, but should fall back on it if another one isn't found.

**Comment by aftersought** [comment]
Unfortunately the other ssh **is** found, and the extension then requests password due to the fact that other SSH does not support YubiKey. 

If the other SSH were not found, I can imagine you would come back to the one found in the first instance, so I see why you might think this is correct behavior. I am happy to use my workaround above, but I can see this being a source of confusion for other users as well.

Please point me to where the logs for previous sessions are stored, if you still need them after this explanation.

**Comment by roblourens** [comment]
Your workaround is the best solution for now, thanks for the explanation. There are a bunch of issues being filed related to this right now and I will probably rethink this.
