### ISSUE TITLE
What is "machine scope"?

### ISSUE THREAD

**Issue by NatoCMI** [microsoft/vscode-docs#3473]
In [settings-sync](https://code.visualstudio.com/docs/editor/settings-sync), there's this information about *machine settings*.

> Machine settings (with `machine` or `machine-overridable` scopes) are not synchronized by default. You can also add or remove settings you want to this list from the Settings editor or using the setting `sync.ignoredSettings`.

What's a "`machine` scope"? How do I give such a scope to a setting?

**Comment by gregvanl** [comment]
Hi @NatoCMI These are user and workspace settings that are specific to machine. For example, an executable path which might be different on different machines.
https://code.visualstudio.com/updates/v1_34#_machinespecific-settings
