### ISSUE TITLE
`workbenchState` when clause not documented

### ISSUE THREAD

**Issue by Denis-net** [microsoft/vscode-docs#3480]
Hello everyone !
I was studying the sample app while i discovered in this [package.json](https://github.com/microsoft/vscode-extension-samples/blob/master/fsprovider-sample/package.json) the following when clause:
```JSON
{
	"command": "memfs.init",
	"when": "workbenchState == workspace"
},
```
it should indicate whether the current VSCode instance is in 'workspace mode' or not.
In [when clauses](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) it's not mentioned.
Given that `workspaceFolderCount` context exists, should this be considered deprecated ?
Or is it still valid but not yet documented ?

Side question related to this:
a `setContext` command is available to extensions in order to set contexts like the above `workbenchState`, is there a `getContext` or `getAllContexts`-like command ?

The only thing i understood was that there is a `Developer inspect context keys` palette's command which upon user click write all the available contexts in DevTools.

Thanks

**Comment by bpasero** [comment]
`workbenchState` can have these values:
* `empty`: no folder or workspace opened
* `folder`: 1 folder opened (no workspace)
* `workspace`: workspace opened

**Comment by Denis-net** [comment]
Hey @bpasero ! 😊👋🏼

After you said that i realized: `Developer inspect context keys` allow us to see all of the extensions' configurations and i've found `workbenchState` and `workspaceFolderCount` closer in the list.
I've checked and when `workbenchState` has a value, `workspaceFolderCount` has a more precise and numeric one:
|`workspaceFolderCount`|`workbenchState`|
|:---:|---|
|0|`empty`|
|1|`folder`|
|2|`workspace`|
|3|`workspace`|
|...|`workspace`|
|n|`workspace`|

Maybe `workspaceFolderCount` was added after the [1.14](https://code.visualstudio.com/updates/v1_14#_preview-multi-root-workspaces) release to accompany multi-root feature while `workbenchState` was already present.
I think here we fall back in "style versus performance" !
