### ISSUE TITLE
Document that Anaconda users should launch VS Code from an activated conda environment

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#3481]
To make the experience better for conda users, we should advise them that they should launch VS Code from the activated conda environment they are going to be using. That way the environment is already set up from a shell perspective.

/cc @luabud @microsoft/pvsc-team

**Comment by JoshuaPartlow** [comment]
@luabud / @brettcannon - Looks like if you use a conda prompt, navigate to your directory, and use **code .** to launch VS Code it ensures the terminal has an activated environment, but it doesn't look like that carries over to the selected interpreter. Is there a way to get that to happen from the command line too? Or is that a step folks will still need to take once VS Code is up?

**Comment by brettcannon** [comment]
@JoshuaPartlow it's a possibility. I've opened https://github.com/microsoft/vscode-python/issues/10668 about the idea.

@luabud should we hold off on documenting this until we have such support in place?

**Comment by luabud** [comment]
@brettcannon ugh sorry, I completely missed this. I think it's still fair to document that this is a workaround that folks can try, and then add that they can select the interpreter by clicking on the status bar (or running the command). This workaround doesn't work on remote scenarios though 😟

**Comment by JoshuaPartlow** [comment]
Have a PR in progress that adds this as a note to the conda environment section of the environments topic.

**Comment by JoshuaPartlow** [comment]
Update included in above PR. If we get to microsoft/vscode-python#10668 let me know or reopen the issue.
