### ISSUE TITLE
There is already a debug configuration "NodeJS" running.

### ISSUE THREAD

**Issue by csafu** [microsoft/vscode-docs#3484]
I use VScode debug the Node.js express code.  It's always popup "There is already a debug configuration "NodeJS" running."
step1.  run -> start debugging
           then, It is look like running. but I can see anything in "Debug Console".
step2.  then I click the "stop(Shift+F5)" button, 
step3.  rerun "start debugger" then "There is already a debug configuration "NodeJS" running." message is show!

**Comment by gregvanl** [comment]
Hi @csafu Are you on the latest VS Code release, 1.43? There have been issues in the past restarting debugging but they should be fixed in the latest version.

**Comment by isidorn** [comment]
@csafu this seems like incorrect behavior. Please make sure you are using the latest vscode and if you can reproduce with it please open an issue in VS Code repository.
Closing this one for now. Thanks

**Comment by gregvanl** [comment]
VS Code repository for product issues is at https://github.com/microsoft/vscode/issues
