### ISSUE TITLE
Missing libraries debugging Django REST Framework app

### ISSUE THREAD

**Issue by neil89** [microsoft/vscode-docs#3486]
I'm trying to debug my rest-framework django app with no success at all. I followed the higly detailed guide in here [https://code.visualstudio.com/docs/python/tutorial-django](https://code.visualstudio.com/docs/python/tutorial-django) but I'm getting errors with my libraries. My settings.INSTALLED_APPS is this:

```
INSTALLED_APPS = [
    ...
    'rest_framework',
    'corsheaders',
    'django_filters',
]
```
My launch.json configuration file is next:
```
{
    "version": "0.2.0",
    "configurations": [

        
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "integratedTerminal",
            "args": [
                "runserver",
                "--noreload"
            ],
            "django": true,
            "host": "127.0.0.1",
            "port": 8000
        }
    ]
}
```

My first error running in debug is this:

`ModuleNotFoundError: No module named 'corsheaders'`

Just to try, I commented out this library in my settings, and my next error was

`ModuleNotFoundError: No module named 'django_filters'`

Ready to get at the end of the hole, I commented out that line too, and my new error is this:

`django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?`

I'd need some hints to include my custom libraries and/or properly configure MySQL client.

Thanks in advance

**Comment by JoshuaPartlow** [comment]
Hi @neil89 - Could you provide some more detail. Are you using a virtual environment with those packages installed? If so, is that environment activated and selected for your interpreter?

**Comment by neil89** [comment]
I updated original post with my launch.json configuration too. Yes those packages are installed and working fine in a common `python manage.py runserver` execution. About interpreter, now you mention it, is [a step of the guide I mentioned before which failed](https://code.visualstudio.com/docs/python/tutorial-django#_create-a-project-environment-for-the-django-tutorial), but I didn't expect to be so important: 

4. Select Python interpreter from the Command Palette, this is ok.
![image](https://user-images.githubusercontent.com/1921323/76997193-2c9e5f00-6953-11ea-96bc-ccede2494936.png)
5. Select virtual environment interpreter, which is not shown for me
![image](https://user-images.githubusercontent.com/1921323/76997432-90c12300-6953-11ea-8b0b-3c2c80a55216.png)

How can I see my `./env` interpreter?

**Comment by JoshuaPartlow** [comment]
There's some guidance [here](https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments) about where VS Code looks for environments. Is the virtual environment within the same folder as your project, like the tutorial, or is it elsewhere?

**Comment by neil89** [comment]
My virtual environment is in `D:\...\backend\env\Scripts\activate`. My manage.py is in `D:\...\backend\api\manage.py`.

Following the documentation you mentioned, I tried to [manually set my env/ folder path](https://code.visualstudio.com/docs/python/environments#_manually-specify-an-interpreter). My workspace settings.json file looks like this (paths are shortened):

```
{
    "python.pythonPath": "C:\\Users\\...\\Programs\\Python\\Python38\\python.exe",
    "python.envFile": "D:\\...\\backend\\env\\Scripts\\activate"
}
```

Still not working, probably because that _activate_ file is not what `envFile `variable is expecting... I don't have any default `.env` file or `dev.env` file in my project, as indicates [here](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file). Is something I should create?

**Comment by JoshuaPartlow** [comment]
Hi @neil89 - Can you try setting the python.pythonPath to the Python interpreter that's part of your environment. So for example if my virtual environment was myenv and on my c drive.     
"python.pythonPath": "c:\\TestEnv\\myenv\\Scripts\\python.exe"

The python.envFile is about setting environment variables, not a Python environment. I think you might have been thinking about python.venvPath, which I believe you could also use and would point to the folder that contains your virtual environments. In your case it looks like that would be the D:\\...\backend\\ folder.

**Comment by neil89** [comment]
Hi again @JoshuaPartlow . Still no effect on getting the `.env` interpreter... I updated `python.envFile` as you mentioned to my `python.exe` inside _backend/env/Scripts_ and still no effect:

![image](https://user-images.githubusercontent.com/1921323/77095076-b27ee080-6a0d-11ea-81fb-de6ea8df062d.png)

I don't know what `venvPath `is and what's it's used for... Sorry for my maybe basic questions, I'm still learning Python...

Thanks in advance!

**Comment by JoshuaPartlow** [comment]
Hi @neil89 - 

No problems, hopefully we can figure this out. 

python.envFile is not related to Python virtual environments, it's for pointing to a file with environment variables. The two settings we're interested in are python.pythonPath and/or python.venvPath. ([Docs for settings](https://code.visualstudio.com/docs/python/settings-reference#_general-settings))

The setting python.pythonPath allows you to set a path to the Python interpreter that you'd like to use. In this case, you want to point it to the one that's part of the virtual environment that you created for your Django project. 

The setting python.venvPath is a setting that allows you to specify a folder that contains virtual environments. In this case you just have the single one, but if you were to create multiple under that backend directory, it should find them all. 

So for your json file and the paths you showed, you'd want something like the following...

{
    "python.pythonPath": "D:\\...\\backend\\env\\Scripts\\python.exe",
    "python.venvPath": "D:\\...\\backend\\"
}

Does that help?

**Comment by neil89** [comment]
It worked now!! The only thing I had to change is my port in _launch.json_. I guess it has to use a different port than my app is running. 

Thanks a lot for your huge help.

**Comment by JoshuaPartlow** [comment]
Excellent, glad to hear it's working now. If you have any other issues with the docs, let us know.
