### ISSUE TITLE
containers.md: short URL(node-mongo) reference looks old(404).

### ISSUE THREAD

**Issue by mkontani** [microsoft/vscode-docs#3499]
issue part is below.
https://code.visualstudio.com/docs/remote/containers#_docker-compose-dev-container-definitions

<https://aka.ms/vscode-remote/samples/node-mongo> redirects to <https://github.com/Microsoft/vscode-dev-containers/tree/master/containers/javascript-node-lts-mongo> (404 not found).

**Comment by gregvanl** [comment]
Thanks for calling this out! Fixed.
