### ISSUE TITLE
improve learning speed

### ISSUE THREAD

**Issue by Ioannis-K** [microsoft/vscode-docs#3500]
It seems to be an excellent tool ONCE you are familiar with it.
What will make the real difference vis-a-vis the competitors' tools is to find a way for increasing the learning of the editor's use.
As you know the enemy of good is the best and your tool is really good and it must compete itself to become best.
By lengthy experience I can assure you that this is feasible no matter how difficult it sounds in a first glance.
Watching learning videos is a common method and once you go to the next one you have probably forgotten the most of the previous(es) ones.
Just implement a tool where on one side you name abilities and on the other you describe ways to do them.
Simple? No!
Useful? Yes!
Important? Yes!
What do you need to remember? the link containing the abilities of the tool. The rest will be learned by the time, little by little and according to the needs each user has. Memorizing things, procedures, shortcuts etc it is IMPOSSIBLE.
Be well,
Take care of the sneaky virus and all invisible invaders.

**Comment by gregvanl** [comment]
Thank you for the detailed suggestions. We are actively working on a new Welcome experience, which we hope will make it easier for new users to learn and adopt VS Code.
