### ISSUE TITLE
Documentation for "Using C++ on Linux in VS Code"

### ISSUE THREAD

**Issue by Build-coder** [microsoft/vscode-docs#3507]
I'm suggesting an edit to the documentation for "Using C++ on Linux in VS Code":

Just above the headline "Debug helloworld.cpp" there is a sub-headline that reads "Modifying tasks.json". Within the text of that sub-headline there is a suggestion that one can substitute "*.cpp" for ${file} if one wishes to build multiple C++ files instead of one. However, I believe the correct substitution should be "${fileDirname}/*.cpp" for ${file} if one wishes to build multiple C++ files instead of one.

^^ For some reason the asterisks are not appearing when I submit this comment but just so you know there are asterisks before the ".cpp"  ^^

**Comment by gregvanl** [comment]
Thanks for pointing this out!

**Comment by Build-coder** [comment]
You're welcome. Thanks for all you do. Love VS code
