### ISSUE TITLE
Please mention what style of regex to use in regex101 playground

### ISSUE THREAD

**Issue by SamPovilus** [microsoft/vscode-docs#3510]
I was trying to use a regular expression for problem matching. in vscode-docs/docs/editor/tasks.md it mentions that "Tip: We have found the RegEx101 playground to be a great way to develop and test regular expressions." but when I tried to make a regex that matched my linker output "^.*\/path\/(\\S+):(\\d+): (.*)" it works in vscode but dosn't work in RegEx101. and now I'm wondering which flavor I'm supposed to use because none work with that regex, but again, it does work to match the problem.

**Comment by roblourens** [comment]
You have correctly escaped your backslashes for the JSON task file, but in the regex playground, backslashes should not be escaped. This matches for me:

![image](https://user-images.githubusercontent.com/323878/77828984-40c52780-70dc-11ea-9722-3ae77ad46439.png)

**Comment by gregvanl** [comment]
Closing as answered
