### ISSUE TITLE
Possible "Integrated Terminal" documentation errors

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-docs#3511]
1. https://code.visualstudio.com/docs/editor/integrated-terminal#_why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched says:

> and when an Integrated Terminal launches, it will run another login shell

Is this true? I started an integrated terminal (using fish shell) and it does not say it is a login shell while executing `status --is-login; and echo yes; or echo no`. The terminal defaults to login shell on macOS since the `terminal.integrated.osx.shellArgs` setting defaults to `["l"]`.

2. https://code.visualstudio.com/docs/editor/integrated-terminal#_why-is-vs-code-shortcut-x-not-working-when-the-terminal-has-focus says:

> Currently the terminal consumes many key bindings, preventing Visual Studio Code from reacting to them. Some examples are F1 to open the Command Palette and Ctrl+P for Quick Open on Linux and Windows.

I am running VS Code remote ssh towards an Ubuntu host. There are two faults as I see it.
a) `Ctrl+P` is not `Quick Open`. `Ctrl+P` is the command `Go to File...`. (`Ctrl+Q` is `View: Quick Open View`).
b) When I press `Ctrl+P` while in the terminal, it does open the `Go to File...` and `Ctrl+Q` does open `View: Quick Open View`. So the terminal does not consume those as it says.

**Comment by Tyriar** [comment]
@thernstig 

1. Yes it is still true on macOS only and that is the reason for the issue in the FAQ. The outer "login shell" is driven by [this code](https://github.com/microsoft/vscode/blob/5b7aa98201cf9442ce0252052268a8f3d9502fda/src/vs/code/node/shellEnv.ts#L33) (VS Code's isn't in a login shell, but it runs a login shell to define its environment).
2. a) Go to file would be more correct yes, "Quick Open" is the name of the underlying widget so I sometimes use that to refer to it. b) These examples are out of date, the commands are included in the `terminal.integrated.commandsToSkipShell`.

I'll update the example in 2.
