### ISSUE TITLE
Visual Studio Code do not allow me to write in terminal nor powershell section

### ISSUE THREAD

**Issue by dselak** [microsoft/vscode-docs#3515]
Visual Studio Code do not allow me to write in terminal nor powershell section? Ia have traid different solutions but without sucess. Screen shoot attched. Thank you in advance for assistance!

![image](https://user-images.githubusercontent.com/45334599/77908598-1914c180-728c-11ea-9a98-69cb18972136.png)
![sc](https://user-images.githubusercontent.com/45334599/77908637-2e89eb80-728c-11ea-9e9e-ae7009d6dfd1.JPG)

**Comment by gregvanl** [comment]
Hi @dselak You might need to put focus in in the terminal and press Enter a few times. There was an issue with some version of Windows that required a carriage return to get the terminal output to show.

**Comment by gregvanl** [comment]
Closing as no reply and this looks like a product issue, not a documentation issue.
If you still have trouble with the integrated terminal, you can open a VS Code product issue at https://github.com/microsoft/vscode/issues.
