### ISSUE TITLE
[Python] Incorrect value in pylint setting example.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode-docs#3517]
See https://code.visualstudio.com/docs/python/linting#_specific-linters.

In that section there is an example of Python extension settings for custom CLI arguments for linters:

```
"python.linting.pylintArgs": ["--reports", "12", "--disable-msg", "I0011"],
"python.linting.flake8Args": ["--ignore=E24,W504", "--verbose"]
"python.linting.pydocstyleArgs": ["--ignore=D400", "--ignore=D4"]
```

The pylint setting says `--disable-msg`, but it should be just `--disable`.  (See [the pylint docs](http://pylint.pycqa.org/en/latest/technical_reference/features.html#messages-control-options).)

**Comment by JoshuaPartlow** [comment]
Thanks Eric. Docs are updated with https://github.com/microsoft/vscode-docs/commit/c070d0732610a3ddae080f0c52e3ca51026e2c74
