### ISSUE TITLE
Embedded languages: Don't use fsPath on non-file URIs

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-docs#3521]
Testing microsoft/vscode#93809

https://github.com/Microsoft/vscode-docs/blob/master/api/language-extensions/embedded-languages.md

In `Request Forwarding sample`

`const originalUri = uri.fsPath.slice(1).slice(0, -4);`

fsPath should only be used for `file` uris. On windows it will return a path `\`

You want to use `uri.path`

**Comment by aeschli** [comment]
Also I thing you need to use `decodeURIComponent`

**Comment by octref** [comment]
Good catch, thanks.
