### ISSUE TITLE
Provide adequate API overview for Welcome content API

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-docs#3528]
refs microsoft/vscode#93747:

Hunting down the documentation of the "Welcome content API" feature I found:
- basically a [picture](https://code.visualstudio.com/updates/v1_43#_welcome-view-content-api)
- and a link to the [API discussion](https://github.com/microsoft/vscode/issues/89080) which does not contain a lucid explanation of the final API.

For the March release notes I suggest to provide something more tangible. 

[A tip: when I create a test item for new extension API, I start with the release notes entry first, and then I copy that into the test item.]

**Comment by alexr00** [comment]
Added here: https://github.com/microsoft/vscode-docs/blob/vnext/api/extension-guides/tree-view.md#welcome-content
Which is also pointed to by the release notes.
