### ISSUE TITLE
Typo in 1.44 release notes

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#3532]
vnext branch
release-notes/v1_44.md L216

`window.getEnviornmentVariableCollection`

**Comment by gregvanl** [comment]
Thanks for catching this. Will be updated shortly.

**Comment by gregvanl** [comment]
https://github.com/microsoft/vscode-docs/commit/3585280f68d54ed201a91339ec367579fbf349b2
