### ISSUE TITLE
Docs Refers To Document Which Not Exist

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/vscode-docs#3535]
The page at https://code.visualstudio.com/docs/editor/settings-sync refers to https://code.visualstudio.com/docs/editor/updates/v1_34#_machinespecific-settings in the paragraph:

> Machine settings (with machine or machine-overridable scopes) are not synchronized by default, since their values are specific to a given machine. You can also add or remove settings you want to this list from the Settings editor or using the setting sync.ignoredSettings.

The word "scopes" is linked to there.

However opening the link gives 404 not found. It seems that the link should refer to https://code.visualstudio.com/updates/v1_34#_machinespecific-settings instead, since the url pattern https://code.visualstudio.com/docs/editor/updates/* does not contain the updates' release notes but they're in https://code.visualstudio.com/updates/*.

**Comment by gregvanl** [comment]
Thanks for pointing this out.
https://github.com/microsoft/vscode-docs/commit/0284a24b0c99d9608bfb481883e1bbf3aad20709
