### ISSUE TITLE
Explicitly say that .env files aren't evaluated for variable substitution on settings 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3550]
On step 3 of [this section,](https://code.visualstudio.com/docs/python/environments#_manually-specify-an-interpreter) we say users can use an environment variable on our settings (in this case, the pythonPath one but that works on other settings too). However, users expect it to work with variables defined in .env files (see https://github.com/microsoft/vscode-python/issues/10533), which we currently not use for variable substitution. 
So we can make clear that .env files are not resolved for variable substitution in the settings.

**Comment by gregvanl** [comment]
PRs welcome

**Comment by JoshuaPartlow** [comment]
Have a PR in progress with the following note added to that section.
> **Note**: Variable substitution is only supported in VS Code settings files, it will not work in `.env` environment files.

**Comment by JoshuaPartlow** [comment]
Updated with the above PR.
