### ISSUE TITLE
External Libraries (SFML) not including properly

### ISSUE THREAD

**Issue by Miszau** [microsoft/vscode-docs#3555]
I wanted to start working on a Simple SFML Project in VS Code - i previously used Code::Blocks and everything worked fine.
I am using the piece of code from SFML's site
```
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
}
```

And i get the error:
![obraz](https://user-images.githubusercontent.com/45367292/79031091-e24c7e80-7b9c-11ea-9d46-4d4d19e8db36.png)

I added this to my c_cpp_properties.json file:
![obraz](https://user-images.githubusercontent.com/45367292/79031129-07d98800-7b9d-11ea-875f-5018a6a11ab4.png)

Which is the correct path in order to use <SFML/Graphics.hpp>

Should i link all .a files in the Compiler Args or is there a different solution i am not seeing?

**Comment by bobbrow** [comment]
You need to add `"-I", "./SFML-2.5.1/include"` to your task arguments to tell the compiler where the header files are.  `c_cpp_properties.json` does not feed this information to the compiler.

**Comment by Miszau** [comment]
That fixed the "No such file or directory" error but made a new one:
`C:\Users\User\AppData\Local\Temp\cchO4VDu.o: In function `main':
e:/cpp/SFMLAnim/main.cpp:5: undefined reference to `_imp___ZN2sf6StringC1EPKcRKSt6locale'
e:/cpp/SFMLAnim/main.cpp:5: undefined reference to `_imp___ZN2sf9VideoModeC1Ejjj'
e:/cpp/SFMLAnim/main.cpp:5: undefined reference to `_imp___ZN2sf12RenderWindowC1ENS_9VideoModeERKNS_6StringEjRKNS_15ContextSettingsE'
e:/cpp/SFMLAnim/main.cpp:6: undefined reference to `_imp___ZN2sf11CircleShapeC1Efj'
e:/cpp/SFMLAnim/main.cpp:7: undefined reference to `_imp___ZN2sf5Color5GreenE'
e:/cpp/SFMLAnim/main.cpp:7: undefined reference to `_imp___ZN2sf5Shape12setFillColorERKNS_5ColorE'
e:/cpp/SFMLAnim/main.cpp:9: undefined reference to `_imp___ZNK2sf6Window6isOpenEv'
e:/cpp/SFMLAnim/main.cpp:12: undefined reference to `_imp___ZN2sf6Window9pollEventERNS_5EventE'
e:/cpp/SFMLAnim/main.cpp:15: undefined reference to `_imp___ZN2sf6Window5closeEv'
e:/cpp/SFMLAnim/main.cpp:18: undefined reference to `_imp___ZN2sf5ColorC1Ehhhh'
e:/cpp/SFMLAnim/main.cpp:18: undefined reference to `_imp___ZN2sf12RenderTarget5clearERKNS_5ColorE'
e:/cpp/SFMLAnim/main.cpp:19: undefined reference to `_imp___ZN2sf12RenderStates7DefaultE'
e:/cpp/SFMLAnim/main.cpp:19: undefined reference to `_imp___ZN2sf12RenderTarget4drawERKNS_8DrawableERKNS_12RenderStatesE'
e:/cpp/SFMLAnim/main.cpp:20: undefined reference to `_imp___ZN2sf6Window7displayEv'
e:/cpp/SFMLAnim/main.cpp:5: undefined reference to `_imp___ZN2sf12RenderWindowD1Ev'
e:/cpp/SFMLAnim/main.cpp:5: undefined reference to `_imp___ZN2sf12RenderWindowD1Ev'
C:\Users\User\AppData\Local\Temp\cchO4VDu.o: In function `ZN2sf11CircleShapeD1Ev':
E:/cpp/SFMLAnim/SFML-2.5.1/include/SFML/Graphics/CircleShape.hpp:41: undefined reference to `_imp___ZTVN2sf11CircleShapeE'
E:/cpp/SFMLAnim/SFML-2.5.1/include/SFML/Graphics/CircleShape.hpp:41: undefined reference to `_imp___ZTVN2sf11CircleShapeE'
E:/cpp/SFMLAnim/SFML-2.5.1/include/SFML/Graphics/CircleShape.hpp:41: undefined reference to `_imp___ZN2sf5ShapeD2Ev'
collect2.exe: error: ld returned 1 exit status
The terminal process terminated with exit code: 1`

**Comment by Miszau** [comment]
That fixed the "No such file or directory but created a new one:

undefined reference to `_imp___ZN2sf6StringC1EPKcRKSt6locale'

After googling it I found out that I need to link .o or .a files - which i did in tasks.json:
![obraz](https://user-images.githubusercontent.com/45367292/79160319-def20680-7dd9-11ea-9264-0fcbf4cd9f24.png)

But that created an error : 
cannot find -lE:\cpp\SFMLAnim\SFML-2.5.1\lib\libsfml-main.a

**Comment by sean-mcmanus** [comment]
Does that file exist? Otherwise, can you remove the line that references the libsfml-main.a?

I'm not familiar with how that library is supposed to be built/referenced.

**Comment by gregvanl** [comment]
Closing as no response
