### ISSUE TITLE
python on vs code

### ISSUE THREAD

**Issue by DanzariaAhmad** [microsoft/vscode-docs#3557]
Select Interpreter keeps showing at the bottom of the IDE

**Comment by JoshuaPartlow** [comment]
Hi @DanzariaAhmad - Just to confirm, are you working on a Python project in a workspace and have you selected a Python interpreter (via the command palette or bottom of the screen)? Thanks.

**Comment by JoshuaPartlow** [comment]
Closing as a few days have gone by. If you're still having an issue though, please feel free to reopen.
