### ISSUE TITLE
Using the command line extension manager example is ambiguous

### ISSUE THREAD

**Issue by glennsarti** [Microsoft/vscode-docs#356]
In https://github.com/Microsoft/vscode-docs/blob/master/release-notes/May_2016.md#command-line-extension-management it mentions that you can use the command line to install extensions e.g

```
code --list-extensions
code --install-extension ms-vscode.cpptools
code --uninstall-extension ms-vscode.csharp
```

However `code` is not available in the search path when you first install VS Code.  It is also confusing as `code.exe` exists in `C:\Program Files (x86)\Microsoft VS Code`.  If this exe is used, the examples above do not work.

Instead the user should be using `C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd`. 

In this case I think a simple documentation change is all that is required and note that the `code` mentioned in the example is available at `<VS Code Install Dir>\bin\code.cmd` or something to that affect.

**Comment by gregvanl** [comment]
Closing an old issue. I haven't seen user comments around the command line install of extensions. It is now covered in https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management.
`code` should be available on the search path for Windows after installing. You might need to start a new command prompt for the PATH update to take effect.
