### ISSUE TITLE
[Python] Document that users should avoid opening a virtual environment folder as the root folder in VS Code

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3562]
If users open a venv folder on VS Code, they can still selected it for the workspace but it will confuse the Python extension and things won't work properly. Maybe we could state this somewhere in the documentation?

**Comment by JoshuaPartlow** [comment]
Have a PR in progress that will include a note to the environments topic that says:
> **Note**: While it's possible to open a virtual environment folder as a workspace, doing so is not recommended and might cause issues with using the Python extension.

**Comment by JoshuaPartlow** [comment]
Update included in above PR.
