### ISSUE TITLE
The run/debug icon in /docs/ is out of date

### ISSUE THREAD

**Issue by Tyler-H** [microsoft/vscode-docs#3566]
The [docs for debugging VS Code](https://code.visualstudio.com/docs/editor/debugging) start out with an image of the IDE indicating the 'run' button:

> ![](https://code.visualstudio.com/assets/docs/editor/debugging/debugging_hero.png)

However, that button's been gone for a long time. It's now on the left side menu as a bigger arrow with a bug in one corner:

![](https://i.stack.imgur.com/o5kkL.png)

While a minor issue (hopefully), this is leading [to some confusion with developers](https://stackoverflow.com/questions/61230942/where-is-the-vscode-debug-icon) and should be fixed at some point.

**Comment by timskau** [comment]
Hi, i noticed this issue. I also see that other images in this documentation section also contains what appears to be older images of the VS Code IDE, like this one under "launch configurations" 
![image](https://user-images.githubusercontent.com/28575673/79357606-9143de00-7f40-11ea-90b7-4101e7d6bbe7.png)

In my VS Code the left menu looks like this (on Ubuntu 18.04)
![image](https://user-images.githubusercontent.com/28575673/79358042-09120880-7f41-11ea-80c9-4e483e86a9f4.png)
