### ISSUE TITLE
VSCode not able to recognize new python environment

### ISSUE THREAD

**Issue by rajnil-guha01** [microsoft/vscode-docs#3567]
I have created a virtual python environment from the terminal and reloaded the window. After that when I try to select the interpreter from the command Palette the environment doesn't appear in the options.
I used below command on the terminal:-

cd GCP/my-projects
/usr/local/bin/python3 -m venv penvir 

After running above commands I don't get the environment penvir

![Screenshot 2020-04-16 at 12 18 31 AM](https://user-images.githubusercontent.com/25716925/79376462-d800fa80-7f77-11ea-8cb8-a07797683fdb.png)

**Comment by brettcannon** [comment]
Did you open `GCP/my-projects` as your workspace in VS Code?

**Comment by mkonstanty** [comment]
I have the same issue, so I have 3 pythons installed:

1. python2.7 from the ubuntu apt:
```
$ which python
/usr/bin/python
$ ls -la /usr/bin/python
lrwxrwxrwx 1 root root 9 Apr 16  2018 /usr/bin/python -> python2.7
```

2. python3.6 from ubuntu apt:
```
$ ls -la /usr/bin/python3
lrwxrwxrwx 1 root root 9 Dec  3 11:26 /usr/bin/python3 -> python3.6
```
3. python3.7 from source:
```
$ which python3
/usr/local/bin/python3
$ ls -la /usr/local/bin/python3
lrwxrwxrwx 1 root root 24 Dec  2 17:27 /usr/local/bin/python3 -> /usr/local/bin/python3.7
```

VS Code python extension does not see python 3.7 when I'm trying to select interpreter, in addition when I create virtual environment with this python 3.7 it does not see it neither.

**Comment by rajnil-guha01** [comment]
As was mentioned by @brettcannon in the first comment.
When you create the virtual environment you need to select the folder where you had created the virtual environment or in other words set your workspace to that folder. Once you do that your Python:Select Interpreter will be able to recognise all virtual environments in that workspace.

**Comment by brettcannon** [comment]
Please note the appropriate place to file bugs on the extension is https://github.com/microsoft/vscode-python.

@mkonstanty please check the Output panel to see if the extension executes its interpreter details code with your `python3.7` code and whether it succeeds.

**Comment by mkonstanty** [comment]
@rajnil-guha01 when I added folder to a workspace and saved workspace and vs code has restared, python plugin has started to discover pythons properly.
thanks!

**Comment by brettcannon** [comment]
@rajnil-guha01 are you still having your problem?

**Comment by rajnil-guha01** [comment]
@brettcannon -- After adding the folder as my workspace vscode was able to recognise the python virtual environments. So not facing the issue anymore. Thanks for your help.

**Comment by JoshuaPartlow** [comment]
Sounds like things are working for everyone, so I'm closing the issue. If that's incorrect, please feel free to reopen.
