### ISSUE TITLE
Update Python debugging docs for debugpy

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#3568]
The next release of the Python extension is going to use [debugpy](https://code.visualstudio.com/docs/python/debugging) as its debugger and not ptvsd.

/cc @int19h @karthiknadig

**Comment by JoshuaPartlow** [comment]
Hi @brettcannon - Just fyi, I have a PR in progress with @luabud, @karthiknadig, and @int19h for debugpy (and other) debugging updates. Please feel free to take a look and add on if you have feedback.
