### ISSUE TITLE
PLEASE Make It Possible To Scroll Through The VSCode Blogs

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/vscode-docs#3569]
If I want to see older blogs at https://code.visualstudio.com/blogs I have a problem, since the posts list doesn't have a simple scroll bar. I have to click on one of the posts in the list and drag to not load that post, than I'm in focus on the list and can scroll with the keyboard arrows. That's very annoying. Please add a scroll bar!!!!

**Comment by jai-dewani** [comment]
I am able to scroll perfectly by placing my cursor above the list (without clicking) and then using my scroll wheel to scroll, could you specify your browser and version.

I am using Microsoft Edge version 81.0.416.58

**Comment by ChayimFriedman2** [comment]
I'm using a laptop without a scroll wheel...

**Comment by gregvanl** [comment]
Closing as no upvotes
