### ISSUE TITLE
how opening in a wall is recognized by pythan imported y ifc file

### ISSUE THREAD

**Issue by 4470** [microsoft/vscode-docs#3575]

**Comment by gregvanl** [comment]
Hi @4470 Can you provide more details? I think this is related to Python but could you specify if your question is about a specific topic on code.visualstudio.com. 
If your question is about a particular VS Code extension, could you describe which extensions you are using? 
I am unfamiliar with ifc files. Is that the file extension? What type of source code do ifc files contain?
Thanks

**Comment by gregvanl** [comment]
Closing as no reply from user. Please reopen if more information is available.

**Comment by 4470** [comment]
how opening[window or door space]  in a wall is recognized by which pythan.extension and python interpreter in visual code actually i have imported an ifc.model in python using import ifcopenshell library unable to detect opening in output

**Comment by gregvanl** [comment]
Looks like you are using IfcOpenShell (http://www.ifcopenshell.org/python) and BIM (https://www.autodesk.com/solutions/bim/benefits-of-bim) perhaps for building or architectural modeling? I'm not sure if the Microsoft Python extension supports these tools.
I do see an Ifc extension on the Marketplace https://marketplace.visualstudio.com/items?itemName=alanrynne.ifc-syntax

**Comment by 4470** [comment]
thanks for guiding
