### ISSUE TITLE
Remove dead/unused branches

### ISSUE THREAD

**Issue by aaronfranke** [microsoft/vscode-docs#3594]
I noticed that this repo currently has 51 branches on it, most of which were previously feature branches that have since been merged. 

Currently, all 51 of these branches are cloned when someone forks the repo, and Git clients need to fetch information for tons of branches whenever they perform a fetch. This is sub-optimal.

Ideally, these branches should be deleted since they aren't used anymore. It would de-clutter the repo, de-clutter forked repos, and improve the performance of Git clients.

**Comment by gregvanl** [comment]
Thanks for calling attention to this. Cleaned out stale branches. Thanks.
