### ISSUE TITLE
tweak version in migrating testing topic

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-docs#3596]
this caused me a little bit of confusion, so to be more explicit in the [Migrating from **vscode**](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode) topic suggest change

> ...install `@types/vscode@1.30`.

to

> "...install `"@types/vscode": "^1.30.0"`

**Comment by gregvanl** [comment]
@octref Do you agree with Chris' suggestion?

**Comment by octref** [comment]
Agree and fixed
