### ISSUE TITLE
${activeEditorLanguage} missing from variables list.

### ISSUE THREAD

**Issue by mbomb007** [microsoft/vscode-docs#3599]
`${activeEditorLanguage}` can be used for getting the active editor language, useful for this setting: `"files.defaultLanguage": "${activeEditorLanguage}"`.

https://github.com/microsoft/vscode/issues/89233

**Comment by gregvanl** [comment]
Hi @mbomb007 Thank you for taking the time to open an issue. This value is specific to the `files.defaultLanguage` settings and is not a general variable. It can not be used in `tasks.json` or `launch.json`. It is documented in the `files.defaultLanguage` setting description.
