### ISSUE TITLE
CELA P1_A11y_code.visualstudio.com_VisualStudioCode_HomePage_ColorContrast: Color contrast ratio of "Search for records" text box focus border is 2.787:1.

### ISSUE THREAD

**Issue by mspatil110** [microsoft/vscode-docs#3605]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#CELAP1_A11y_code.visualstudio.com;#A11ySev2;#A11yTCS;#A11yWCAG2.1;#Benchmark;#ChromiumEdge;#DesktopWeb;#MAS1.4.11;#Win10;#Visual Studio Code;#CELAP1_code;#ColorContrast;

**Environment Details:**
Application Name: code.visualstudio.com
#URL:https://code.visualstudio.com/docs/python/python-tutorial
Windows Version: Windows10
Browser version: Microsoft Edge Version 84.0.488.1 (Official build) dev (64-bit)

**Repro Steps:**
1)Launch the application url :
https://code.visualstudio.com/
2)Visual Studio Code will get open.
3)Go through "Code editing Redefined".
4)Launch AI4D.
5)Navigate up to search text box and verify the the Color contrast ratio of focus border of "Search for records" text box with no keyboard focus .

**Actual:**
Color contrast ratio of "Search for records" text box focus border is 2.787:1 i.e. less than required 3:1.

**Expected:**
Color contrast ratio of the  "Search for records" text box focus border must be at least 3:1.
 

**User Impact:**
Low vision user would find it difficult to identify  "Search for records" text box.

**Attachment link for Reference:**
![3605_CELA P1_A11y_code visualstudio com_VisualStudioCode_HomePage_ColorContrast](https://user-images.githubusercontent.com/51433293/80188435-c7fbb180-862e-11ea-8c8f-3d8f3692b04a.png)

**Comment by gregvanl** [comment]
Could not reproduce.

![image](https://user-images.githubusercontent.com/12818376/82615012-1f356900-9b7e-11ea-8602-469f4f0a3bbd.png)

**Comment by khansahab15** [comment]
GitHubTags:#A11y_MAS;

**Comment by khansahab15** [comment]
GitHubTags:#P1_A11y_April2020

**Comment by mstechie** [comment]
GitHubTags:#P1_A11y_April2020;

**Comment by ManishaC1** [comment]
Verified the issue in below environment.
#URL: https://code.visualstudio.com/
The issue is fixed.
Github tags:#Closed

![Screenshot (430)](https://user-images.githubusercontent.com/105198219/216931597-ddc5f1dd-a8f3-4e20-bcfb-db6ff22e58e8.png)

**Comment by mstechie** [comment]
GitHubTags:#P1_A11y_code.visualstudio.com_Apr2020

**Comment by InduPriya1805** [comment]
GitHubTags:#P1_A11y_code.visualstudio.com_Apr2020;
