### ISSUE TITLE
Can't find article sidebar on mobile

### ISSUE THREAD

**Issue by Tschrock** [microsoft/vscode-docs#3606]
Maybe I'm just missing something, but I've looked everywhere and I can't find the list of articles/topics when looking at the api docs on mobile. Trying to use desktop mode in the browser doesn't help. On an actual desktop it shows up as a left sidebar.

https://code.visualstudio.com/api/references/vscode-api
![Screenshot_20200424-053832](https://user-images.githubusercontent.com/2406499/80198894-b98da580-85ee-11ea-8714-868aae912fc4.png)
![Screenshot_20200424-053911](https://user-images.githubusercontent.com/2406499/80198901-bc889600-85ee-11ea-832e-6077687028a8.png)

https://code.visualstudio.com/api/extension-capabilities/overview
![Screenshot_20200424-054542](https://user-images.githubusercontent.com/2406499/80199627-8d265900-85ef-11ea-8d85-ce4b527df1dd.png)

**Comment by gregvanl** [comment]
Hi @Tschrock This is a known bug and needs to be fixed in our vscode-website infrastructure repo. I'll leave this issue open as a tracking issue in the public vscode-docs repo. Thanks.

**Comment by gregvanl** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/12818376/80895316-712e5180-8c98-11ea-87e5-14e3e4728d24.png)
