### ISSUE TITLE
Update Accessibility Conformance Documentation

### ISSUE THREAD

**Issue by fsteffi** [microsoft/vscode-docs#3607]
GitHubTags:#CELA P1_A11y_code.visualstudio.com;#A11ySev1;#A11yTCS;#A11yMAS;#A11yAAT#Benchmark;#DesktopWeb;#Win10;#Visual Studio Code;#CELAP1_code;

Bug Description: 
Recommendation: "Fix and close other bugs before starting accessibility conformance documentation. Any bug that will not be fixed and closed within SLA must be declared in the AAT. The SLA for this bug is also 60 days."

Link to the current AAT entry - https://cela-ra-aat-prod.azurewebsites.net/#/workflow/42189bbd-e2a0-4372-915a-67e8b06d1684

Update and Republish conformance documentation

**Comment by gregvanl** [comment]
Per discussions CELA guidelines at https://microsoft.sharepoint.com/sites/accessibility/SitePages/Accessibility-Assessment-Tool-FAQ.aspx, the code.visualstudio.com website should not need an accessibility conformance report. Specifically siting: "Is the website targeted to enterprise, but available to the general public? If yes, NO conformance statement required (e.g., community.dynamics.com; azure.microsoft.com/status, msdn.com), but see bullet above pertaining to sites localized for France."
The VS Code website code.visualstudio.com is similar to msdn.com (now docs.microsoft.com) and is not localized for France.
See earlier issue from the Feb 2020 test pass. https://github.com/microsoft/vscode-docs/issues/3446
