### ISSUE TITLE
Steps documented to create Personal Access Token needs to be updated

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-docs#361]
Currently the steps to create Personal Access Token asks the reader to click on "My Profile" which is supposed to take the reader to a page where the reader is to click on the "Security" tab. 
The latest release for Visual Studio Team Services takes the reader to a totally different place if "My Profile" is clicked. Instead the reader should be told to click on "My Security".

**Comment by gregvanl** [comment]
Fixed by https://github.com/Microsoft/vscode-docs/commit/3e9647a42b18b3aeb5136d43a944841753b7e1d3
