### ISSUE TITLE
ERROR: PC register is not available when starts debugging C/C++ programs on Visual Studio Code

### ISSUE THREAD

**Issue by RodrigoCharni** [microsoft/vscode-docs#3610]
followed these instructions: https://code.visualstudio.com/docs/cpp/config-mingw

But, when I try debugging (F5), it shows this kind of error on the bottom of the Debug Console and never starts to debug.

I searched on Google, but I can't find the solution.

The previous steps worked out 

How can I solve this problem?

Thanks.

Screenshot attached: ERROR: PC register is not available
![ERROR-PC](https://user-images.githubusercontent.com/42945141/80234730-42700580-861e-11ea-91b6-fbb557c7b3f1.png)

The MinGW tools are in my PATH:
![PATH](https://user-images.githubusercontent.com/42945141/80235452-5b2ceb00-861f-11ea-93a0-c5920a7b2dc2.png)

I tested the g++ and the gdb with --version on the console.
![g++ and gdb test](https://user-images.githubusercontent.com/42945141/80236013-1eadbf00-8620-11ea-9082-ee7fb61f1894.png)

**Comment by gregvanl** [comment]
Hi @RodrigoCharni, Here's advice from the C++ extension engineering team:
"This is an error with GDB itself on Windows on versions 7.3 - 7.6. See https://sourceware.org/bugzilla/show_bug.cgi?id=14018
Can they either downgrade to 7.2 or upgrade to 7.7?"

It does look like you are on GDB version 7.6.1.

**Comment by RodrigoCharni** [comment]
Hi @gregvanl 

Thanks for replying to me.

I checked it out but, sincerely I didn't understand it. I thought that I could find a link for an upgrade or something like that, so I couldn't figure out.

I'm new to programming.

I found this, but I don't know what do I have to do:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=230109e7ff8ad9b1268d251cba1fa26a24efde64

Greetings.

**Comment by gregvanl** [comment]
Hi @RodrigoCharni It looks like the current SourceForge MinGW installer will install 8.1.0 by default. There is a version dropdown during the install flow, which lets you select an earlier version, but the 7.* versions with the issue are not included. 
You could try uninstalling your current version of MinGW (Control Panel > Uninstall a program) and then reinstall MinGW from the SourceForge link.

**Comment by gregvanl** [comment]
@RodrigoCharni I'm using the same installed version (with 'dwarf' in the name).
Do you need to restart your command prompt and VS Code to take advantage of the new install?
What do you see now when you do `gdb --version`?
You might also double check the location of the new install and the paths to g++.exe and gdb.exe (`where gdb.exe`). You might still have an old version of gdb.exe around.

**Comment by RodrigoCharni** [comment]
Hi @gregvanl 

I closed the VS Code and the command prompt before the installation after that I restarted my laptop.

I changed my system variable from this: C:\MinGW\bin to C:\MinGW\mingw32\bin

The mingw32 folder wasn't in the 'MinGW folder' before the last installation.

The version of gdb is:

C:\Users\Estrategias\projects>gdb --version
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

When I do this step:
[Debug helloworld.cpp
Next, you'll create a launch.json file to configure VS Code to launch the GDB debugger when you press F5 to debug the program. From the main menu, choose Run > Add Configuration... and then choose C++ (GDB/LLDB).

You'll then see a dropdown for various predefined debugging configurations. Choose g++.exe build and debug active file.]

My dropdown list appears like this:
![dropdownlist1](https://user-images.githubusercontent.com/42945141/80824689-9477d480-8ba4-11ea-814f-9f17bc5b84f3.png)

The g++.exe appears three times, I don't know why.

So, I chose the first.

This is my launch.json file:
![launch json](https://user-images.githubusercontent.com/42945141/80825094-57601200-8ba5-11ea-89f8-8179e7989b08.png)

The launch.json file looks good like from the tutorial

I did this step:
[Start a debugging session
Go back to helloworld.cpp so that it is the active file.
Press F5 or from the main menu choose Run > Start Debugging. ]

It appears a NEW error:

![VS Code Error](https://user-images.githubusercontent.com/42945141/80825742-99d61e80-8ba6-11ea-8a91-c264aae51acb.png)

:(

**Comment by gregvanl** [comment]
Hi @RodrigoCharni It looks like the launch can't find the `preLaunchTask`, which uses the name of the task. What does your `task.json` look like?
I notice that generated `launch.json` is using a localized Spanish name for the configuration. I wonder if your `tasks.json` is also using a Spanish name but the generated `preLaunchTask` value is English.

**Comment by gregvanl** [comment]
Looking around I see that there can be issues if you have a Display Language set but are missing a Language Pack.
Can you run the command Configure Display Language and see if that drop down is set to Spanish?
It might be that VS Code doesn't have the Spanish Language Pack installed and falls back to English but the C++ extension is able to display in Spanish.

**Comment by RodrigoCharni** [comment]
Hi @gregvanl 

Talking about the language 
I don't recall if I installed a language pack.

![2020-05-01 (3)](https://user-images.githubusercontent.com/42945141/80834353-289e6780-8bb6-11ea-87a0-3b85fa1fc164.png)

I selected 'en'  and the VS Code restarted.

The drop-down list appears with the option three times yet, now in English
![2020-05-01 (4)](https://user-images.githubusercontent.com/42945141/80834870-32749a80-8bb7-11ea-8ecb-f945c899c5e2.png)

Now, I'm re-follow the steps from beginning

**Comment by RodrigoCharni** [comment]
Hi @gregvanl 

Finally.

![Finally](https://user-images.githubusercontent.com/42945141/80836155-c5163900-8bb9-11ea-9f93-8ee14e69b015.png)

So, I think that to solve the issue was...

To double-check the MinGW (gdb and g++) updated using this installer:
https://bit.ly/2KM0fMR

To verify the system variable 'PATH': 
C:\MinGW\**mingw32**\bin

To make sure to use the Visual Studio Code in English using the command Configure Display Language selecting 'en' option.

![2020-05-01 (3)](https://user-images.githubusercontent.com/42945141/80836717-f6dbcf80-8bba-11ea-8da9-bc465507cea6.png)

But, the dropdown list with the option appears three times yet, I think is not a real issue, I can work with that.

I appreciate a lot your time @gregvanl for helping me.

**Comment by gregvanl** [comment]
@RodrigoCharni You're welcome. Glad you've got things sorted. I'll close this issue now.
