### ISSUE TITLE
Unable to set python path as a virtual environment

### ISSUE THREAD

**Issue by ArtemimM** [microsoft/vscode-docs#3615]
Hi
I tried to install matplotlib and I activated virtual environment but when I select it I get this massage:

> Failed to set 'pythonPath'. Error: Unable to write into folder settings. Please open the 'Python' folder settings to correct errors/warnings in it and try again. source: Python (Extension)
Any idea how can I fix that?

![pythonpath](https://user-images.githubusercontent.com/63196607/80272950-5893c980-86e3-11ea-8855-25d826ef4a6e.jpg)

**Comment by gregvanl** [comment]
Hi @ArtemimM, looking at your screenshot, `"python.pythonPath"` is the property and it looks like you have duplicated the property name.

See https://code.visualstudio.com/docs/python/environments#_manually-specify-an-interpreter for an example:

```json
"python.pythonPath": "c:/dev/ala/venv/Scripts/python.exe"
```

**Comment by ArtemimM** [comment]
Thanks a lot...I could make it with your advice.

**Comment by gregvanl** [comment]
@JoshuaPartlow Is there anything in the documentation or extension workflow that might lead users to get into this state, where the `python.pythonPath` property name can be included twice in settings.json?

**Comment by JoshuaPartlow** [comment]
@gregvanl - Nothing that I'm aware of. Adding @luabud in case this is something that might be an issue.
