### ISSUE TITLE
No interpreter shown in vs code

### ISSUE THREAD

**Issue by Akshat2006** [microsoft/vscode-docs#3619]
I have already downloaded python version 3.7 32-bit and a vs code extension python. But whenever i try to run a project, even a simplest one, it throws an error of selecting an interpreter and installing python. when i try to select an interpreter, I see that there is no interpreter shown.The window appears somewhat like this:
![Capture](https://user-images.githubusercontent.com/64460101/80457799-867c4680-894d-11ea-839a-62479bc23def.PNG)
![Capture](https://user-images.githubusercontent.com/64460101/80457853-9562f900-894d-11ea-94c8-8637a360bf9a.PNG)

I will be thankful for your help or support ....
.

**Comment by JoshuaPartlow** [comment]
Hi @Akshat2006 - Two questions, if you open a standard command prompt and try to run Python is it working as expected? Is python.pythonPath set within the settings.json file and, if so, what is it set to?

**Comment by Akshat2006** [comment]
hey @JoshuaPartlow - Firstly, yes it runs as expected . and I have set them as follows:
![ffggb](https://user-images.githubusercontent.com/64460101/80526488-747fbf80-89b0-11ea-9247-9ac4defe762e.PNG)

I have also added a specific path in environment variables but each time I start vs code, it throws these errors...

**Comment by JoshuaPartlow** [comment]
Hmm. What's the setting in the .env file? Just to confirm when you use the command palette Python: Select Interpreter you're not seeing any options?

**Comment by Akshat2006** [comment]
yeah. I don't see any options whenever I use  the command palette......

**Comment by JoshuaPartlow** [comment]
Thanks @Akshat2006 for confirming. @brettcannon and @luabud, any suggestions for why no Python interpreters are showing up as options in Command Palette and the error being seen above for the version that is installed?

**Comment by brettcannon** [comment]
What does the Output panel for the extension say?

Basically I would change your `"python.pythonPath"` setting to be an absolute path to the Python interpreter you want to use.

**Comment by Akshat2006** [comment]
okay.....@brettcannon- I tried to do that. but now, on running the code, I can see the errors are same and I got another error, saying that "the terminal shell path (path) is a directory"....
even though the path is correct .......it looks like this:
![Capture](https://user-images.githubusercontent.com/64460101/80678541-b3a93000-8ad8-11ea-9cf5-80cb4df1f396.PNG)

and the path like this:
![Capture](https://user-images.githubusercontent.com/64460101/80678615-e3f0ce80-8ad8-11ea-9457-ed2a90cc9415.PNG)

I don't know why I am getting these errors. Will be glad and thankful for your favour

**Comment by JoshuaPartlow** [comment]
Looks like you might possibly have a misplaced "s" at the end of the pythonPath. What happens if you define the path all the way down to the interpreter :       "python.pythonPath":"C:/Users/SONY/AppData/Local/Programs/Python/Python37-32/python.exe" ?

**Comment by Akshat2006** [comment]
It didn't.....

**Comment by brettcannon** [comment]
@Akshat2006 please open an issue at https://github.com/microsoft/vscode-python and fill out the issue template as we will be able to better help you over there with the requested information.
