### ISSUE TITLE
`vscode.version` field is not in the API reference

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode-docs#3620]
https://github.com/microsoft/vscode/blob/abb4a35cfc26102f93fd00df7b59ce1a19c2017a/src/vs/vscode.d.ts#L11

This field is not found in the API reference at https://code.visualstudio.com/api/references/vscode-api

**Comment by gregvanl** [comment]
Hi @iliazeus The vscode-api API reference on code.visualstudio.com won't be updated until the next release 1.45 when the new API is available.
I'll double-check that the API is available on the vscode-docs vnext staging server until then.

**Comment by gregvanl** [comment]
My mistake, this version constant isn't a new addition. You are correct, that constant is not in the generated API reference. Reopening the issue.

**Comment by gregvanl** [comment]
Closing old issue without upvotes.
Unfortunately, the API generation does not include constants outside an interface or namespace.
The workaround as you have found is to review vscode.d.ts or IntelliSense in the editor.
![image](https://user-images.githubusercontent.com/12818376/107468129-4d981180-6b1c-11eb-8c59-5d00bcf973f7.png)
