### ISSUE TITLE
function deactivate() in lsp-sample lead to error message "Type 'undefined' is not assignable to type 'Thenable<void>'."

### ISSUE THREAD

**Issue by JohannesKonings** [microsoft/vscode-docs#3621]
In language-server-extension-guide this coding section:
https://code.visualstudio.com/api/language-extensions/language-server-extension-guide
https://github.com/Microsoft/vscode-docs/blob/master/api/language-extensions/language-server-extension-guide.md

```javascript
export function deactivate(): Thenable<void> {
  if (!client) {
    return undefined;
  }
  return client.stop();
}
```
![image](https://user-images.githubusercontent.com/14806640/80484458-07d8d680-8958-11ea-9f4a-28ec4146a17e.png)

**Comment by JohannesKonings** [comment]
Here ist the solution: https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-sample/client/src/extension.ts

```javascript
export function deactivate(): Thenable<void> | undefined {
	if (!client) {
		return undefined;
	}
	return client.stop();
}
```

**Comment by gregvanl** [comment]
Thanks for pointing this out!
