### ISSUE TITLE
Add "File > open folder" to VS Code docs 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3623]
This will could sound like too obvious to be added to the docs, but on some QPs we've seen users get confused as to how they would open a project in VS Code (some try it through "open workspaces" first). I think it could also be great to have this documented so that there's a piece of the docs others can refer to when giving instructions on how to open a project in VS Code. 

I was thinking maybe a section here: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_basics ?

**Comment by luabud** [comment]
cc @kkampf

**Comment by gregvanl** [comment]
Closing old issue. PRs welcome if you still feel there is a documentation gap.
