### ISSUE TITLE
json.maxItemsComputed

### ISSUE THREAD

**Issue by NIATHFP** [microsoft/vscode-docs#3638]
population_data.json: For performance reasons, document symbols have been limited to 5000 items. Use setting 'json.maxItemsComputed' to configure the limit.

When I run a code about the .json, I got the 5000 items limit. How can I change the limit numbers of items.

**Comment by gregvanl** [comment]
Hi @NIATHFP I'm not sure I understand your question. Is the `json.maxItemsComputed` setting not working if you change the limit from the default of 5000? You would make the change in either your user settings or the workspace settings for your project.

![image](https://user-images.githubusercontent.com/12818376/80815824-2e2e8a00-8b83-11ea-9d2d-ae7d2fd5d381.png)

**Comment by gregvanl** [comment]
Closing, no response
