### ISSUE TITLE
using the built in jupyte notebook server makes other jupyter instances show no files

### ISSUE THREAD

**Issue by Prtfw** [microsoft/vscode-docs#3639]
I lost the ability to start a jupyter notebook server in a terminal and use my normal workflow... now if I start a server in terminal (in a venv or not) the browser shows this 
![image](https://user-images.githubusercontent.com/13193437/80831104-305f0b80-8bb8-11ea-8cc8-621be2b88ed0.png)
no matter what folder I am looking at I see no files or notebooks or subfolders.
and I could not open a new notebook 
![image](https://user-images.githubusercontent.com/13193437/80831148-3ce36400-8bb8-11ea-8618-fb0ef7d31148.png)
and this happens even after I shut down the server running in vscode
![image](https://user-images.githubusercontent.com/13193437/80831186-4e2c7080-8bb8-11ea-8f27-bdf27fa7c640.png)
via `jupyter notebook stop 8888`

installing this extension has f-ed up my python environment some how and I can't find any documentation on how to remove this extension / undo this change.

Please help. (This was a terrible experience.)

**Comment by JoshuaPartlow** [comment]
Hi @Prtfw - This [doc topic](https://code.visualstudio.com/docs/editor/extension-gallery) has the steps to uninstall an extension. For your bigger issue, given it isn't about the docs, could you open an issue at https://github.com/microsoft/vscode-python and fill out the issue template there? We will be able to better help you over there with the requested information in the template.
