### ISSUE TITLE
Document which shell `postCreateCommand` uses

### ISSUE THREAD

**Issue by hashtagchris** [microsoft/vscode-docs#3641]
https://github.com/microsoft/vscode-docs/blob/master/docs/remote/containers.md doesn't say what shell command will be used for `postCreateCommand` when a string argument is supplied. Based on brief testing, it appears to be `/bin/sh -c`. Specifying a [SHELL](https://docs.docker.com/engine/reference/builder/#shell) in my Dockerfile didn't change that.

**Comment by chrmarti** [comment]
@hashtagchris Just to better understand: Would you prefer it to use the SHELL specified in the Dockerfile?

**Comment by gregvanl** [comment]
Closing as no reply from user.
