### ISSUE TITLE
Documentation lacks information on Snippets for HTML, CSS and JS

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode-docs#3642]
The [HTML Snippets](https://code.visualstudio.com/docs/languages/html#_emmet-snippets) section of the documentation has a link to [Emmet's cheat sheet](https://docs.emmet.io/cheat-sheet/) showing all HTML and CSS snippets that VS Code supports.

As far as I can tell, Emmet does not support snippets for JavaScript. So I'd love to know where I can get a list of all JS snippets that VS Code supports, and suggest that we add this list to the documentation so people can see the available snippets for JS.

Cheers and keep up the awesome work 👍

**Comment by andrecasal** [comment]
I was checking the source code for VS Code. Does the `/vscode/extensions/javascript/snippets/javascript.code-snippets` file contain the full list of snippets for JavaScript?

**Comment by andrecasal** [comment]
I just realized VS Code does not support all of Emmet's snippets. CSS's `bg+` snippet doesn't work in VS Code, for example.

I've also ran a search on VS Code's source code for *.code-snippets files but could only find the JavaScript ones mentioned earlier.

**Comment by robole** [comment]
I was also looking for this information recently. It would be useful to have it documented. A lot of people install a snippet extension because they are not aware of this.

**Comment by gregvanl** [comment]
Closing old issue as snippets are discoverable and up-to-date in-product
