### ISSUE TITLE
Update to documentation

### ISSUE THREAD

**Issue by alan-hwp** [microsoft/vscode-docs#3645]
Would it be possible to highlight or otherwise emphasise, the way to prevent a mouse scroll wheel pasting random text into source files in the editor, somewhere prominent. This has been causing me major problems for ages, and today I came across the cure. I haven't seen it in normal usage docs.
https://github.com/microsoft/vscode/issues/14610#issuecomment-321495159
This stopped the problem. A problem on which I've wasted too many hours undoing random text changes added by scrolling up and down editor windows with a scroll wheel mouse.
Many thanks.

**Comment by alexdima** [comment]
@alan-hwp I'm sorry for the frustration this has caused. Here -- https://github.com/microsoft/vscode-docs -- is the docs repository. PR welcome if you find a good place where to mention this setting.

**Comment by gregvanl** [comment]
Closing as no PR submitted
