### ISSUE TITLE
Docs Use Incorrect Link In Markdown

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/vscode-docs#3654]
In the page https://code.visualstudio.com/api/extension-guides/custom-editors, several times there are references to the sample. However they're not marked as links, but `[custom editor extension sample][sample]`. I guess it was meant to be `[custom editor extension sample](sample)`, which will generate the link correctly.

**Comment by gregvanl** [comment]
Thanks for pointing this out!
