### ISSUE TITLE
Bad documentation page

### ISSUE THREAD

**Issue by ttwd80** [microsoft/vscode-docs#3655]
- VSCode Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. visit https://code.visualstudio.com/docs/setup/mac
2. Search for "Open the Command Palette"
3. It will say `F1`. It should say <kbd>Shift</kbd>+<kbd>⌘</kbd>+<kbd>P</kbd>.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gregvanl** [comment]
Hi @ttwd80 Thank you for taking the time to open an issue.
Both keybindings are supported and we wanted to promote `F1` in the macOS setup documentation. Our usual keybinding mapping will show the second keyboard shortcut `Shift+Cmd+P` as you see in View > Command Palette.

![image](https://user-images.githubusercontent.com/12818376/81415460-537c4480-90fd-11ea-93fc-928e0d22aaa9.png)
