### ISSUE TITLE
Document new setting "python.logging.level"

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-docs#3656]
### PYTHON EXTENSION

We've added a new setting,
```
"python.logging.level": {
    "type": "string",
    "default": "error",
    "enum": [
        "off",
        "error",
        "warn",
        "info",
        "debug"
    ],
    "description": "The logging level the extension logs at, defaults to 'error'",
    "scope": "machine"
}
```

Earlier all types of logs were dumped into the developer tools console. Now we've moved that to the Python output channel and only log error logs by default.

**Comment by JoshuaPartlow** [comment]
@karrtikr - Working on getting this into the docs. Could you give me a little more detail about the difference between the assorted logging levels so I can include that as well? Also, any preference on where this lives within the [settings](https://code.visualstudio.com/docs/python/settings-reference) topic. Thanks.

**Comment by karrtikr** [comment]
Thanks on working on this, there's no preference. The differences are,
- `"off"`: No extra detail other than the **basic info** will be logged into the Python output channel
- `"error"`: Everything logged in the previous level + **Errors** will be logged
- `"warn"`: Everything logged in the previous level + **Warnings** will be logged. Which means **Errors**+**Warnings**+**basic info**
- `"info"`: Everything logged in the previous level + Things like extra info, method execution times, return value etc. will be logged.
- `"debug"`: Currently we don't log anything at this level, but it will provide more details.

**basic info** refers to startup info like which LS is started and the commands that the extension runs on user behalf.

The greater level you choose, more are the things which are logged. It is recommended to not turn it `"off"`, as it won't let the users see any errors that might have occured.

**Comment by JoshuaPartlow** [comment]
Thanks, should have this out in an update shortly.

**Comment by JoshuaPartlow** [comment]
Update included in above PR.
