### ISSUE TITLE
Linting is being confused with IntelliSense

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode-docs#3660]
If we're [defining](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2019) [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense) as [contextual or intelligent code completion](https://en.wikipedia.org/wiki/Intelligent_code_completion) (code completion, parameter info, quick info, and member lists), in the [IntelliSense section of JavaScript](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_intellisense), we're mixing the concept of IntelliSense and Linting.

Even though JSDocs and TypeScript Type Declaration files provide both parameter info and information for type linting, they are functions under different contexts. Parameter info falls under the purview of IntelliSense while type linting falls under, well, Linting.

I think the documentation (or any conversation around this topic, really) would gain clarity if we talked about type linting in the context of Linting while keeping parameter info under the context of IntelliSense.

I would then suggest we add a section called Linting to talk about linting variable types (from Type Inferencing, JSDoc annotations or TypeScript Type Declaration files) and avoid talking about type linting under the context of IntelliSense. 🙂

**Comment by gregvanl** [comment]
Hi @andrecasal Nice to hear from you. I couldn't find any reference to linting in the IntelliSense section you pointed out.
If you have any ideas how to make that section clearer or explicitly mention Linting, pull requests are always welcome.

**Comment by andrecasal** [comment]
Hey @gregvanl glad to hear from you too! 😉 Yeah my suggestion is to add a Linting section to talk about Type Linting. But while we're at it, we could talk about all other built-in linting features in VS Code. I'd love to submit a PR for this, but it will take me a few weeks as I'm recording a course on VS Code and linting is one of the last subjects.

**Comment by gregvanl** [comment]
No PR arrived, no upvotes so closing old issue.
