### ISSUE TITLE
Clarify override order between envFile and env variables defined in launch.json

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3674]
We don't have it clearly documented the override order for envFile and env variables like mentioned on issue https://github.com/microsoft/vscode-python/issues/1724.
We could clarify it on [this section](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file) for our docs

> We also have a `python.envFile`setting (introduced in https://github.com/microsoft/vscode-python/pull/6773), so we should also be clear on the overriding order between
> - the `python.envFile` setting (user setting & workspace setting),
> - the `envFile` specified in `launch.json`, and
> - `env` variables defined in `launch.json`.

> _Originally posted in https://github.com/microsoft/vscode-python/issues/1724#issuecomment-532805643_

**Comment by JoshuaPartlow** [comment]
Have a PR in progress that will add the following note to the section you suggested. 

> **Note**: When environment variables are specified using multiple methods, be aware that there is an order of precedence. Environment variables contained in the `.env` file specified by the `python.envFile` setting (user or workspace) will override variables defined in the `envFile` specified in `launch.json`, as well as any `env` variables defined in the `launch.json` file itself. Similarly, environment variables defined in the `envFile` specified in `launch.json` will override `env` variables defined in the `launch.json` file.

**Comment by JoshuaPartlow** [comment]
Updated with above PR.

**Comment by xy9485** [comment]
> Have a PR in progress that will add the following note to the section you suggested.
> 
> > **Note**: When environment variables are specified using multiple methods, be aware that there is an order of precedence. Environment variables contained in the `.env` file specified by the `python.envFile` setting (user or workspace) will override variables defined in the `envFile` specified in `launch.json`, as well as any `env` variables defined in the `launch.json` file itself. Similarly, environment variables defined in the `envFile` specified in `launch.json` will override `env` variables defined in the `launch.json` file.

Actually the behaviour regarding precedence in practice is exactly in opposite as described in the doc.

My vscode:
Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
