### ISSUE TITLE
Update reference to deprecated 'vscode' module under extension-anatomy#extension-entry-file

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode-docs#3678]
https://code.visualstudio.com/api/get-started/extension-anatomy#extension-entry-file

The second paragraph references the deprecated `vscode` module which is no longer used:

> The vscode module contains a script located at node ./node_modules/vscode/bin/install. The script pulls the VS Code API definition file depending on the engines.vscode field in package.json. After running the script, you would get IntelliSense, jump to definition and other TypeScript language features in your code.

The source code generated by VS Code Extension Generator no longer contains the `vscode` module and uses `@types/vscode` and `vscode-test` instead.

**Comment by gregvanl** [comment]
Looks like the vscode module is still being used (perhaps the switch to @types/vscode was reverted?) and the install script location is accurate.
