### ISSUE TITLE
Bundling topic doesn't include the necessary information to enable debugging

### ISSUE THREAD

**Issue by neilenns** [microsoft/vscode-docs#3689]
The [Bundling Extension](https://github.com/Microsoft/vscode-docs/blob/master/api/working-with-extensions/bundling-extension.md) topic explains how to get webpack up and running, but leaves out important information that results in a broken debug configuration.

Specifically the following information is missing:

1. The `watch` script needs to include `--info-verbosity verbose` when calling webpack
2. The tasks.json file needs to include the `$ts-webpack-watch` problem matcher
3. I believe (but am not 100% sure) tasks.json should also include `"isBackground": true`
4. Developers need to install the [Typescript & Webpack Problem Matchers extension](https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher)

It would be useful to include a complete launch.json file as well to show the change to using the dist folder:

```{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run Extension",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": ["--extensionDevelopmentPath=${workspaceFolder}"],
      "outFiles": ["${workspaceFolder}/dist/**/*.js"],
      "preLaunchTask": "${defaultBuildTask}"
    }
  ]
}```

**Comment by gregvanl** [comment]
Closing older issue
