### ISSUE TITLE
Add Linux per-distro installation advice to Linux setup page

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#369]
Calling out the community AUR package for Arch Linux for example: https://code.visualstudio.com/docs/setup/linux

This can probably wait until the deb/rpm repositories are up https://github.com/Microsoft/vscode/issues/2973, https://github.com/Microsoft/vscode/issues/229

**Comment by gregvanl** [comment]
I think we have coverage for all available distributions.

**Comment by Tyriar** [comment]
We should call out the AUR package maintained by the community https://aur.archlinux.org/packages/visual-studio-code/

**Comment by gregvanl** [comment]
So far we've resisted calling out distributions that we don't directly produce. For example, we didn't take a PR to advertise Chocolatey https://github.com/Microsoft/vscode-docs/pull/802. This was after discussions with Chris and Kai. We're happy if users discover and use community provided distributions but we don't want to appear to guarantee things we don't control.

**Comment by Tyriar** [comment]
@gregvanl this one's a little special though as I've spoken with them and we don't offer anything on Arch Linux. Officially sponsoring would tell people that this is what we recommend.
