### ISSUE TITLE
Where do Automatic Type Acquisitions come from?

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode-docs#3694]
In the [Typings and Automatic Type Acquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition) of the [Working with JavaScript](https://code.visualstudio.com/docs/nodejs/working-with-javascript) page, it says:

> Many popular libraries ship with typings files so you get IntelliSense for them automatically. For libraries that do not include typings, VS Code's Automatic Type Acquisition will automatically install community maintained typings file for you.

Would I be correct in assuming these typings files come from https://definitelytyped.org/?

**Comment by gregvanl** [comment]
Hi @andrecasal, TypeScript gets the typings from npmjs at https://www.npmjs.com/~types.
