### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.

### ISSUE THREAD

**Issue by ludan1107743896** [microsoft/vscode-docs#3696]
File packaging is completed and introduced into vscode project：
```javascript
panel.webview.html = getWebViewContent(context, 'src/dist/index.html');
```
Page engineering blank page, prompt:   Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.

**Comment by gregvanl** [comment]
Hi @ludan1107743896, There isn't enough information in your issue for us to help you. Can you share your project (perhaps in a repo), so we can have a look and see how you have implemented getWebViewContent.
Are you following the webview extension guide at https://code.visualstudio.com/api/extension-guides/webview?

**Comment by ludan1107743896** [comment]
It should be my packing problem. I can use a different packing method. Thank you.
