### ISSUE TITLE
A11y_code.visualstudio.com_VisualStudioCode_HomePage_Screenreader: Screenreader reads as 7 rows wherever 4 rows are present on the table.

### ISSUE THREAD

**Issue by nirmalsahoo** [microsoft/vscode-docs#3698]
[Check out Accessibility Insights!](https://github.com/microsoft/AzureStorageExplorer/issues/url) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_Code.visualstudio.com_Benchmark;#A11ySev2;#A11yTCS;#A11yMAS;#Benchmark;#ChromiumEdge;#Chrome;#DesktopWeb;#MAS1.3.1;#Win10;#Visual Studio Code;#Narrator;#NVDA; #CAITestPass_May2020;#FTP;#STP

**Environment Details:**
Application Name: code.visualstudio.com
#URL:https://code.visualstudio.com
Windows Version: Windows10
Browser version: Microsoft Edge Version 84.0.488.1 (Official build) dev (64-bit)
Chrome Version: Version 83.0.4103.61 (Official Build) (64-bit)
Screenreader version
Narrator, NVDA[2020.1]
**Repro Steps:**
1)Launch the application URL :
https://code.visualstudio.com/
2)Navigate to Other platforms and insiders edition besides to Download for windows-Stable builds.
3)Open the drop down.
4)Open screenreader and check whether it reads the correct rows and column count.

**Actual:**
While navigating through keyboard, Screenreader reads as 7 rows wherever 4 rows are present on the table.

This issue is reproduced with Chromium Edge+ Narrator and Chrome + NVDA.

**Expected:**
Screenreader should read 4 rows as there are 4 rows present.

**Attachment link for Reference:**
https://microsoft-my.sharepoint.com/:v:/p/v-nisaho/ERUbKFeD5M9DhoXFN68MAIYB54a0jswRb6yRNaY2rQsiMA?e=gqpDQ7

**Comment by JacksonKearl** [comment]
Seeing 6 rows being read, which is correct (header, mac, windows, linux deb, linux rpm, other).
![image](https://user-images.githubusercontent.com/8586769/87459305-12525600-c5c0-11ea-81cf-840b561d4c5d.png)

However I cleaned up the table for screen readers, verifiers please verify that you can easily navigate the table using the screenreader's table navigation keys (ctrl+opt+Arrow on voiceover), and the contents read for each cell make sense.

**Comment by gregvanl** [comment]
Assigning to issue author per test plan guidelines
