### ISSUE TITLE
A11y_code.visualstudio.com_VisualStudioCode_Docs Get Started_Intro Videos_Keyboard: While navigating using keyboard tab key the focus is available on non interactive element 'In This Article'.

### ISSUE THREAD

**Issue by bhagwatshelke1047** [microsoft/vscode-docs#3700]
[Check out Accessibility Insights!](url) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_Code.visualstudio.com_Benchmark;#A11ySev2;#A11yTCS;#A11yMAS;#Benchmark;#ChromiumEdge;#Chrome;#DesktopWeb;#MAS2.4.3;#Win10;#Visual Studio Code;#Keyboard;#CAITestPass_May2020;#FTP;#STP.

**Environment Details:**
Application Name: code.visualstudio.com
#URL:[https://code.visualstudio.com](url)
Windows Version: Windows10
Browser version: Microsoft Edge Version 84.0.488.1 (Official build) dev (64-bit), Google Chrome 81.0.4044.138 (Official Build) (64-bit)

**Repro Steps:**
1. Launch the application Url :[https://code.visualstudio.com](url)
2. Navigate to "Docs" link.
3. From left navigation, select "Get Started".
4. Navigate to "Intro Videos" link.
5. Start navigating using keyboard tab key and check weather the focus available on 'In this article' text or not.

**Actual:**
While navigating using keyboard tab key the focus is available on non interactive element 'In This Article'.

**Same issue in the following page:**
1)Docs Get Started-->Tips and Tricks
2)Docs Get Started-->User Interface
3)Docs Get Started-->Settings
4)Docs Get Started-->Themes
5)Docs Get Started-->Display Language
6)Docs User Guide-->IntelliSense
7)Docs User Guide-->Emmet

**Expected:**
While navigating using keyboard tab key the focus should not be available on non interactive element 'In This Article'.

Attachment  for Reference:
![3700_A11y_code visualstudio com_VisualStudioCode_Docs Get Started_Intro Videos_Keyboard](https://user-images.githubusercontent.com/52443697/83011503-9b74f400-a037-11ea-9b53-328babc1e020.gif)

**Comment by fsteffi** [comment]
[3700-fixed.webm](https://user-images.githubusercontent.com/24580570/216554505-b9ba3f1b-a856-4e0f-9f06-21231435a685.webm)
issue is fixed in https://code.visualstudio.com/docs/getstarted/introvideos

**GithubTags:**#Closed;
