### ISSUE TITLE
Cannot get Debugger working while following https://code.visualstudio.com/docs/python/tutorial-django

### ISSUE THREAD

**Issue by ElSrJuez** [microsoft/vscode-docs#3702]
I am following the Django VSCode tutorial but I cannot get the Debugger to trigger my breakpoints.
https://code.visualstudio.com/docs/python/tutorial-django

Is there a step that I may be missing where to get the breakpoints working for Django?
This seems to work fine for the Flask tutorial.

**Comment by JoshuaPartlow** [comment]
Hi @ElSrJuez - One common issue that might cause something like that is if you've ended up with multiple instances of your Django app launched. The first instance continues to own the debugging port and, as a result, when you run the app in the debugger using the same port, the original running app handles all the requests and you won't see any activity in the app being debugged and the program won't stop at breakpoints. So a first thing to try is to make sure no other instances of your app are still running and the port has been released. Has debugging worked in Django at any point for you?

**Comment by ElSrJuez** [comment]
> Hi @ElSrJuez Has debugging worked in Django at any point for you?

Thank you @JoshuaPartlow - it started working afterwards, i want paying attention close enough to notice why.
Thanks for the quick reply tho! Im closing this issue.

**Comment by JoshuaPartlow** [comment]
Excellent, glad it's working for you now.
