### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by maxval94** [Microsoft/vscode-docs#371]
Mac OS X, zoom files
http://joxi.ru/Drlo1pgI4wXn4A

**Comment by gregvanl** [comment]
Hi Maxim,
Can you provide more details?  I couldn't see the issue from the screen shot. Also is this a documentation issue or an issue with VS Code itself.
Thanks

**Comment by maxval94** [comment]
When I change the multiple desktops is changing files Zoom

**Comment by maxval94** [comment]
I need to restart the editor

**Comment by mrmlnc** [comment]
@maxval94, Ты ошибся репозиторием. Этот репозиторий предназначен только для обсуждения проблем документации. Все проблемы редактора решаются в репозитории [vscode](https://github.com/Microsoft/vscode).

**Comment by gregvanl** [comment]
The Russian language comment above is correct.  Product issues should go to the vscode repo.

**Comment by mrmlnc** [comment]
@gregvanl, sorry that answered him on Russian language. It is the native language for @maxval94.

**Comment by gregvanl** [comment]
@mrmlnc, no worries, that was great.  Thanks for helping out!
