### ISSUE TITLE
Devcontainer performance

### ISSUE THREAD

**Issue by ankitbko** [microsoft/vscode-docs#3717]
Doc to improve - https://github.com/microsoft/vscode-docs/blob/master/docs/remote/containers-advanced.md#improving-container-disk-performance

In windows if using WSL2 the performance can also be improved if we bind mount the source code from wsl 2 filesystem instead of windows. That means keeping the source code in wsl 2 filesystem itself and doing a regular bind mount to it. Unless there is some magic happening between contianer -> bind mounted wsl 2 filesystem that I am not aware of, it should give similar performance as volume mounting.  
Although I haven't done extensive testing in my case it does give much better performance than mount binding host filesystem. 
https://github.com/docker/for-win/issues/6875#issuecomment-634017898

**Comment by Chuxel** [comment]
Good suggestion - we can add this in the 1.46 doc updates.
