### ISSUE TITLE
A11y_code.visualstudio.com_VisualStudioCode_Docs Get Started_Intro Videos_ScreenReader: Narrator reads unnecessary 'Table Table' after reading 'In this article text' while navigating using caps + arrow key.

### ISSUE THREAD

**Issue by bhagwatshelke1047** [microsoft/vscode-docs#3719]
[Check out Accessibility Insights!](url) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_Code.visualstudio.com_Benchmark;#A11ySev2;#A11yTCS;#A11yMAS;#Benchmark;#ChromiumEdge;#DesktopWeb;#MAS1.3.1;#Win10;#Visual Studio Code;#Narrator;#CAITestPass_May2020;#FTP

**Environment Details:**
Application Name: code.visualstudio.com
#URL:[https://code.visualstudio.com](url)
Windows Version: Windows10
Browser version: Microsoft Edge Version 84.0.488.1 (Official build) dev (64-bit)
Screen reader : Narrator

**Repro Steps:**
1. Launch the application Url :[https://code.visualstudio.com](url)
2. Navigate to "Docs" link.
3. From left navigation, select "Get Started".
4. Navigate to "Intro Videos" link.
5. Start narrator and check it reads 'table table after reading the 'In this article'  text while navigating using caps + arrow key.

**Actual:**
Narrator reads unnecessary 'Table Table' after reading 'In this article text' while navigating using caps + arrow key.

**This issue is observed only with Narrator + Chromium Edge. NVDA reads as expected.
Same issue in the following page:**
1)Docs Get Started-->Tips and Tricks
2)Docs Get Started-->User Interface
3)Docs Get Started-->Settings
4)Docs Get Started-->Themes
5)Docs Get Started-->Display Language
6)Docs User Guide-->IntelliSense
7)Docs User Guide-->Emmet
8.Home-->.Footer

**Expected:**
Narrator should not read unnecessary 'Table Table' after reading 'In this article text' while navigating using caps + arrow key.

**Attachment for Reference:**
https://microsoft-my.sharepoint.com/:v:/p/v-rojad/EXtXcFwDg59Bjreh8_8gjjsBCTsJ9bRDetOJpClHYQtrKA?e=LUry2d

**Comment by fsteffi** [comment]
issue fixed in https://code.visualstudio.com/docs/getstarted/introvideos

**GithubTags:**#Closed;

[3719-fixed.webm](https://user-images.githubusercontent.com/24580570/216557385-7f56da8d-d37b-4414-88ca-8ae06b3490f3.webm)
