### ISSUE TITLE
Blog - create a blog on extension best practices

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-docs#372]
There are a set of 'best practices' for a GREAT language extension.

Blogging this could be a good thing.  Alternatively we could think of a doc for this.

This is not an urgent item adding here for tracking purposes.

**Comment by gregvanl** [comment]
@kieferrm is working on an extension checklist which will be included in the docs.
From iteration plan:
 "Add the Language Extension Checklist to our docs @kieferrm"
