### ISSUE TITLE
Not able to Select python Interpreter

### ISSUE THREAD

**Issue by Anand111993** [microsoft/vscode-docs#3722]
I have tried all possible way to add Python interpreter but not successful .

**Comment by JoshuaPartlow** [comment]
Hi @Anand111993 - Could you give us a little more detail of what you've tried and what aspect isn't working? Are you able to work with the Python interpreter outside of VS Code at a cmd prompt for instance? Have you walked through our [getting started tutorial](https://code.visualstudio.com/docs/python/python-tutorial)? Thanks.

**Comment by Anand111993** [comment]
Hi Joshua,

I have install both Python 2.7 and Python 3 but VS code is not able to
detect interpreter automatically . I have tried all way which mention on VC
code web Side .

Same thing working on Pycharm .

Can you please help me to resolve this issue?

[image: image.png]

[image: image.png]

Regards,
Anand Singh
8800938843

**Comment by JoshuaPartlow** [comment]
Do you know which version of the Python extension you have installed? If you have the Python extension installed and no options are shown when you use the command palette (ctrl-shift-p or View->Command Palette...) **Python: Select Interpreter** command then can you please open an issue at https://github.com/microsoft/vscode-python and fill out the issue template. They'll be able to help there if it's an extension bug.

**Comment by JoshuaPartlow** [comment]
Closing this issue given time passed, but feel free to reopen it here or in https://github.com/microsoft/vscode-python if it looks like it might be an issue with the extension.
