### ISSUE TITLE
A11y_code.visualstudio.com_VisualStudioCode_HomePage_Keyboard:Keyboard focus is not clearly visible on the Previous and next button.

### ISSUE THREAD

**Issue by nirmalsahoo** [microsoft/vscode-docs#3725]
[Check out Accessibility Insights!](https://github.com/microsoft/AzureStorageExplorer/issues/url) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_Code.visualstudio.com_Benchmark;#A11ySev2;#A11yTCS;#A11yMAS;#Benchmark;#ChromiumEdge;#Chrome;#DesktopWeb;#MAS2.4.7;#Win10;#Visual Studio Code;#Keyboard; #CAITestPass_May2020;#FTP;#STP;

**Environment Details:**
Application Name: code.visualstudio.com
#URL:https://code.visualstudio.com
Windows Version: Windows10
Browser version: Microsoft Edge Version 84.0.488.1 (Official build) dev (64-bit)
Chrome Version: Version 83.0.4103.61 (Official Build) (64-bit)
**Repro Steps:**
1)Launch the application URL :
https://code.visualstudio.com/
2)Navigate to next and previous button on the carousel. 
3)Check whether Keyboard focus is clearly visible on the Previous and next button.

**Actual:**
While navigating through keyboard, Keyboard focus is not clearly visible on the Previous and next button.
 
This issue is reproduced with Chromium Edge+ Narrator and Chrome + NVDA.

**Expected:**
Keyboard focus should visible on previous and next button.

**Attachment link for Reference:**
![3725_A11y_code visualstudio com_VisualStudioCode_HomePage_Keyboard](https://user-images.githubusercontent.com/53940787/83119273-24019c00-a0ed-11ea-9c42-6b2c1ebef732.gif)

**Comment by JacksonKearl** [comment]
Thanks, fixed.

![asdfasdc](https://user-images.githubusercontent.com/8586769/87478630-f4481e00-c5de-11ea-8b11-b88b20c30e8b.gif)

**Comment by InduPriya1805** [comment]
Regressed the bug in below environment
URL: https://code.visualstudio.com/
The issue is fixed
Githubtags:  #Closed; 
![3725_Fixed](https://user-images.githubusercontent.com/42638450/215719115-f52eaaf1-30c0-4771-8e70-3aee472f2f05.gif)

**Comment by ManishaC1** [comment]
verified the issue in below environment.
#URL: https://code.visualstudio.com/
Github tags:#Closed
![Screenshot (442)](https://user-images.githubusercontent.com/105198219/217234717-b82990ad-3fba-4cbd-b6c1-87587eab1f61.png)

**Comment by ManishaC1** [comment]
Github tags:#Closed;
