### ISSUE TITLE
How to correctly set formatter for python when formatter for other language enabled?

### ISSUE THREAD

**Issue by krave1986** [microsoft/vscode-docs#3728]
My daily job is to write javascript.
So obviously one js formatter is already enabled for my vs code as editor.defaultFormatter.

I just start to setup vs code to write python by following your tutorials:
https://code.visualstudio.com/docs/python/editing

I have black installed in my virtual environment with this setting:
`"python.formatting.provider": "black",`

But whenever I save a hello.py file, I was told from vs code that 

> Extension 'prettier - Code formatter' cannot format "hello.py"

So I tried to add 
```
	"[python]": {
		"editor.defaultFormatter": "ms-python.python"
	}
```

I am not sure "ms-python.python" is the correct value for "editor.defaultFormatter" but the annoying message went away.

Can you confirm with me the correct way to have multiple formatters enabled same time for different languages?

**Comment by gregvanl** [comment]
Hi @krave1986, you got it right. You just need the language ID `python` and the extension ID `ms-python.python`.

https://code.visualstudio.com/updates/v1_33#_default-formatter-selection

**Comment by krave1986** [comment]
Hi @gregvanl , thank you for your confirmation.
