### ISSUE TITLE
the link address of downloading Mingw-w64 compressed archive file is wrong

### ISSUE THREAD

**Issue by lT-Tl** [microsoft/vscode-docs#3735]
the third point of prerequisities, the link address of downloading "Mingw-w64" will not download the compressed archive file this tutorial wants, the right link address is "https://sourceforge.net/projects/mingw-w64/"

**Comment by gregvanl** [comment]
Hi @lT-Tl, the link provided will download the mingw-w64-install.exe Windows installer, which it what people should use to install the MinGW toolset on Windows.
Perhaps the sentence just needs to be updated since we aren't pointing to an archive file.

**Comment by lT-Tl** [comment]
There always an error when i use the installer downloaded from that link, I found out that it was an online installer, so I decieded to download directly from [https://phoenixnap.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-win32/seh/x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z](url)

**Comment by TylerMSFT** [comment]
I've clarified the install steps (should be live by 7/22)
The installer link in the doc works for me. I used it at least a half-a-dozen times during the process of reworking some of the content in the topic.
