### ISSUE TITLE
Configuring VSCode for C++ with MinGW info does not match what packages do - Confused?

### ISSUE THREAD

**Issue by Boogieshoes58** [microsoft/vscode-docs#3737]
Having installed VSCode to try and go back to some C programming I am struggling with the so called help pages.  This link https://code.visualstudio.com/docs/languages/cpp gives 3 options for installing a C compiler.   GCC for (Linux or Windows), Microsoft C++ or CLang for Mac.

This link https://code.visualstudio.com/docs/cpp/config-mingw for GCC then says extract compressed file into a folder name with no spaces and indicates 'C:\mingw-w64'.     the download file doesn't give you that option and seems to want to use C:\Program files(x86)\Minw….   note the spaces  in 'Program files'.

I am getting totally confused is there a simpler place to find information about how to install VSCode and set it up compile C++ or is it a case of wading through page after page of contradictory and conflicting information, whilst trying this and ultimately ending up with a PC that is in need of a complete reinstall to use again?

Thank you.

**Comment by gregvanl** [comment]
Hi @Boogieshoes58, the documentation is confusing since it mentions an archive file but the actual link downloads a Windows installer version. We're working on getting that updated.

If you run the mingw-w64-install.exe, you should be able to set the installation path.

![image](https://user-images.githubusercontent.com/12818376/83363516-e2702b80-a34e-11ea-8328-967f4071c05e.png)

**Comment by Boogieshoes58** [comment]
Thank you for the reply Greg.

I have found so many variants of Mingw that I am completely confused and don't know what to trust or even if I should trust anything any more.   I got a mingw-w64-v7.0.0.zip file.... couldn't find anything in it that resembled a c compiler, then found a mingw-win-builds-1.5.0.exe file from their download area.... utterly bamboozling.  When things are this badly organised you have to question whether even putting VSCode on the machine is worthwhile,  It certainly isn't useful at the moment without any compiler associated with it.  I fell I'd be better of going back to building a Z80 based machine and writing raw assembler at least it worked and you didn't have to fight with thing like this.

Thanks again.

**Comment by Boogieshoes58** [comment]
Well I used the exe from the website as described, it does install G++ but not as the rest of the webpage describes.  It only seems to install a 32 bit version so the path has to be set to C;\MingW-w64\MingW32\Bin not as the tutorials describe.

Talk about garbage....

**Comment by gregvanl** [comment]
I'm sorry that you are finding installing the MinGW toolset frustrating. VS Code is a light weight editor and doesn't include language toolsets and supporting extensions by default.
You might try using a full-fledged programming IDE, which generally have full language support out-of-the-box.
