### ISSUE TITLE
[Python] Settings reference includes general testing settings in unittest settings

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3741]
#### Reported by @bersbersbers in https://github.com/microsoft/vscode-python/issues/11814

Compare the settings at 

https://code.visualstudio.com/docs/python/testing#_test-configuration-settings

and

https://code.visualstudio.com/docs/python/settings-reference#_testing-settings

The latter incorrectly has general settings such as `promptToConfigure` in the "unittest" section; a general section is missing.

**Comment by JoshuaPartlow** [comment]
Have a PR in progress that will correct this.

**Comment by JoshuaPartlow** [comment]
Update included in above PR.
