### ISSUE TITLE
[Python] Improve documentation for `"request": "test"` and `"console": "integratedTerminal"`

### ISSUE THREAD

**Issue by lsorber** [microsoft/vscode-docs#3742]
Based on https://github.com/microsoft/vscode-python/issues/12085, there is some unclarity regarding the `launch.json` options `"request": "test"` and `"console": "integratedTerminal"` in the Python documentation:

1. The Python > Testing documentation [1] mentions that it's possible to add a launch configuration with `"request": "test"` to `launch.json` to configure the running and debugging of tests, but it doesn't explain what settings are possible or what they do. Specifically, it is not clear that `"console": "integratedTerminal"` changes the default behaviour to run and debug tests in the integrated terminal.

2. The Python > Debugging documentation [2] does list the different options for the `"console"` setting in `launch.json`, but does not mention the possibility to configure the built-in debugger with `"request": "test"` (even though this is the debugging page).

[1] https://code.visualstudio.com/docs/python/testing#_debug-tests
[2] https://code.visualstudio.com/docs/python/debugging#_console

**Comment by JoshuaPartlow** [comment]
Hi @lsorber - Thanks for calling out the lack of clarity. I'll take a look at it and see what can be done to improve.

**Comment by luabud** [comment]
We will stop using `"request" : "test"` and will add a different argument for it instead (https://github.com/microsoft/vscode-python/issues/15790). We will need to update the documentation to reflect that for sure, but it will be different from what we have now.

**Comment by JoshuaPartlow** [comment]
Great, we'll track an update for the docs once those changes are made.
