### ISSUE TITLE
Python interpreter is not getting selected

### ISSUE THREAD

**Issue by shrey27tri01** [microsoft/vscode-docs#3746]
I have been having this problem for many weeks now. Whenever I open a python file in VSCode, an alert comes, saying : "Python is not installed. Please download and install Python before using the extension". So I tried uninstalling and then reinstalling python on my Windows system. But the problem still persists. Also, whenever I open a python file in VSCode, the status bar shows "Select Python Interpreter", and even after I select a particular interpreter, it still shows the alert. 

This is now becoming irritating, since everytime I open a python file, this problem occurs, although the code compiles and runs perfectly.

**Comment by JoshuaPartlow** [comment]
Hi @shrey27tri01 - Could you please open an issue at https://github.com/microsoft/vscode-python (repo for the extension itself) instead and fill out the issue template as we will be able to better help you over there with the requested information.

**Comment by shrey27tri01** [comment]
@JoshuaPartlow, thank you very much for your reply, I have opened the issue at the repo for the extension.

**Comment by JoshuaPartlow** [comment]
@shrey27tri01 - No problem, thanks for opening the issue. I'll close this one, but I'll keep an eye on https://github.com/microsoft/vscode-python/issues/12165 in case there ends up being changes needed for the docs.
