### ISSUE TITLE
Docs for  keyboard shortcut editor.action.showContextMenu

### ISSUE THREAD

**Issue by katelynienaber** [microsoft/vscode-docs#3749]
Hello, I cannot find anywhere documentation for standard keyboard shortcut `editor.action.showContextMenu`.

I am trying to execute the command with function `vscode.commands.executeCommand` and I should know what to pass to `executeCommand` so that it will `showContextMenu` on the correct element.

**Comment by gregvanl** [comment]
Hi @katelynienaber The command `showContextMenu` does not take any arguments.
Can you explain your use case in more detail, as there may be another way to accomplish it (for example, execute the context menu selected item directly)?
You can also open a feature request in the VS Code product repo https://github.com/microsoft/vscode, if you think adding this type of support would be helpful.

**Comment by katelynienaber** [comment]
Hello, I made a feature request there, I hope they will implement it!

I have a custom tree for my extension, and inside the tree are folders and files (nodes). I would like to open the context menu for a specific folder or file when the user clicks on a button in the node's toolbar.

So I thought I could run `editor.action.showContextMenu` when the user clicks on a custom function button in the toolbar:
````
function rightClick(customTree, node?) {
    vscode.commands.executeCommand("editor.action.showContextMenu");
}
````

But this doesn't work. In the documentation for `vscode.commands.executeCommand` it says:
_Note 1: When executing an editor command not all types are allowed to be passed as arguments. Allowed are the primitive types string, boolean, number, undefined, and null, as well as Position, Range, Uri and Location._

So I should be able to pass an argument, but I don't know what argument to pass.

**Comment by gregvanl** [comment]
Closing as not a documentation issue. User has opened a product feature request.
