### ISSUE TITLE
Getting started should list examples of additional runtimes

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-docs#375]
Like we list examples of additional languages.

https://code.visualstudio.com/docs/b?utm_expid=101350005-20.jAsCkEFcTeqvtdr0STCN9g.1&utm_referrer=https%3A%2F%2Fcode.visualstudio.com%2Fb

**Comment by gregvanl** [comment]
Added runtimes .NET and Unity with https://github.com/Microsoft/vscode-website/commit/af28109d4422fbd7ca51af22faf04afcc5cdec94
