### ISSUE TITLE
(C++)Where's the functions‘ instruction？

### ISSUE THREAD

**Issue by DereenMec** [microsoft/vscode-docs#3752]
I followed this(https://code.visualstudio.com/docs/cpp/config-mingw) instruction strictly. But why I dont have the function's introduction?
this is yours:
![msg-intellisense](https://user-images.githubusercontent.com/36854639/83948365-66df1480-a84f-11ea-8eb6-dd8910ed2351.png)
this is mine:
![微信图片_20200606233757](https://user-images.githubusercontent.com/36854639/83948370-6c3c5f00-a84f-11ea-9a90-aa3003115def.png)
Here is my C++ plugin settings:
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "C:/App/mingw64/bin/gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by gregvanl** [comment]
Hi @DereenMec, if you hover over the suggestion, you'll see a '>' chevron for **Read More** flyout.

You can toggle the suggestion details flyout with Ctrl+Space (Cmd+Space on macOS). 

![image](https://user-images.githubusercontent.com/12818376/83960746-2a0c2100-a841-11ea-92c4-9e1f04c74d60.png)
