### ISSUE TITLE
Vs Code Python doesn't detect venv environments

### ISSUE THREAD

**Issue by PooyaJln** [microsoft/vscode-docs#3755]
This issue is similar to  https://github.com/microsoft/vscode-python/issues/2470
but the solution doesn't apply to me.
I have tried 
"python.venvPath": "${workspaceFolder}/venv"
"python.venvPath": "${fileDirname}/venv/bin/python3"
"python.venvPath": "./venv/bin/python3"

in setting.json but it didn't help.
As it can be seen in the screenshot, I can use the virtual environment using terminal.

I also followed the instruction on:
https://code.visualstudio.com/docs/python/environments#_global-virtual-and-conda-environments
but the notification below doesn't even show up
![image](https://user-images.githubusercontent.com/37688424/83954313-7313a380-a848-11ea-8c6c-820433596e3d.png)

## Environment data

-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): 2020.5.80290
-   OS and version: ubuntu 18.04  (Linux x64 4.15.0-101-generic) also 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.6.9 also 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): true
-   Value of the `python.languageServer` setting: "Microsoft"

## Expected behaviour
Clicking on the interpretor on the left bottom should show all available interpretors including virtual environments.

## Actual behaviour
virtual environment are not detected.

## Steps to reproduce:

1. click on the interpretor selection on the left bottom
![image](https://user-images.githubusercontent.com/37688424/83866323-f2f61c80-a727-11ea-88c1-37556ff8568a.png)

**Comment by smasherprog** [comment]
I can also confirm this as well. Python support for virtual enviornments does not work at all. No environment is created for windows

**Comment by JoshuaPartlow** [comment]
Hi @PooyaJln - Is there a reason you're not opening the test_proj directory as your workspace? I could be mistaken, but given where your settings.json is located, I don't believe the paths you're showing would map to the location of the virtual environment.

**Comment by smasherprog** [comment]
I eventually got it to work in vs code, I dont know what I did, but It started working.

**Comment by PooyaJln** [comment]
Hi @JoshuaPartlow ,
What I discovered later was that VScode finds out the virtual environment if I open the project's folder itself but if I open a folder than contains several project folders it can't detect it.
What I understood from the setting environment guide was that it should be possible by using the correct ${} variable.

**Comment by JoshuaPartlow** [comment]
Hi @PooyaJln - A VS Code workspace is generally the root folder that you open. I believe the issue you were having above was that you were assuming the variable substitution would start from the directory of your sub-folder. For example, when you used "python.venvPath": "${workspaceFolder}/venv" there isn't actually a venv directory directory under the root workspace folder (python_by_corey_schafer). The venv folder is under the test_proj folder, so you would have needed something like ${workspaceFolder}/test_proj/venv I think.

**Comment by JoshuaPartlow** [comment]
@ericsnowcurrently @luabud - do either of you know if using ${fileDirname} in a settings.json file should work for setting python.venvPath? I tried myself and like @PooyaJln wasn't able to get it to work. With a python file open I used `"python.venvPath": "${fileDirname}\\test\\",` and `"python.venvPath": "${fileDirname}\\test\\.venv\\"` but neither worked.

**Comment by JoshuaPartlow** [comment]
Closing as it looks like this was answered at https://github.com/microsoft/vscode-python/issues/12164. If additional help is needed though, feel free to reopen.
