### ISSUE TITLE
launch-json-reference.md from vscode-docs/docs/cpp/ uses an invalid environment definition

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode-docs#3757]
The file [`launch-json-reference.md`](https://github.com/Microsoft/vscode-docs/blob/master/docs/cpp/launch-json-reference.md) mentions that environment variables can be injected into the debugged application via the following entry:
```json
{
   "name": "C++ Launch",
   "type": "cppdbg",
   "request": "launch",
   "program": "${workspaceFolder}/a.out",
   "args": ["arg1", "arg2"],
   "environment": [{"name": "squid", "value": "clam"}],
   "cwd": "${workspaceFolder}"
}
```

This is incorrect, instead the `env` parameter must be used with a different format:
```json
{
   "name": "C++ Launch",
   "type": "cppdbg",
   "request": "launch",
   "program": "${workspaceFolder}/a.out",
   "args": ["arg1", "arg2"],
   "env": {"squid": "clam"},
   "cwd": "${workspaceFolder}"
}
```

P.S.: I'd fix this myself, but you've got a CLA that needs to be signed and would need to go through legal first…

**Comment by TylerMSFT** [comment]
Hello @dcermak ,

The example is correct. We don’t handle ‘env’ but other extensions do. We require environment variables to be entered as “environment”:

**Comment by dcermak** [comment]
Would you consider to change this to be more consistent with the vanilla vscode behavior? Or add a note that other extensions/vanilla vscode use the `env` key?

I must say that this is all very confusing, because if you just search the web for passing environment variables to debugging sessions, you end up first on the page that I have linked. But that will simply not work in most cases and finding the right way to do it requires one to either look into the schema definition of launch.json or be lucky enough to find the correct question on StackOverflow.

**Comment by gregvanl** [comment]
@dcermak You can enter an issue with your suggestion in the C++ extension repo. https://github.com/microsoft/vscode-cpptools

**Comment by dcermak** [comment]
Then why is this file in the **vscode-docs** repository? To me it sounds like that file belongs into the vscode-cpptools repository instead.

**Comment by WardenGnaw** [comment]
@dcermak We initially had this documentation at [vscode-cpptools](https://github.com/microsoft/vscode-cpptools/blob/master/launch.md) but being in the repository made it difficult to find. The vscode-cpptools team decided to move our documentation to **vscode-docs** to increase visibility on the page and not have our tutorials link to github markdown files. 

We currently have an issue on supporting `env` at https://github.com/microsoft/vscode-cpptools/issues/116
Please react with a 👍 to that issue to indicate your interest of this feature being implemented.
