### ISSUE TITLE
[Python] Clarify that setting `inheritEnv` to false might impact other extensions

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-docs#3762]
Hello,

In the Python extension we display the following prompt if the selected interpreter is a conda environment (https://github.com/microsoft/vscode-python/issues/7607#issuecomment-543884896):

![image](https://user-images.githubusercontent.com/51720070/84090313-4aa1bb80-a9a6-11ea-81b6-b0539c953c21.png)

When clicking on "More info" they are redirected to https://code.visualstudio.com/updates/v1_36#_launch-terminals-with-clean-environments.

However, it turns out that setting `inheritEnv` to false may impact other extensions, for example the [vscode-remote](https://github.com/microsoft/vscode-python/issues/12176) one.

It would be helpful if the Python docs had a few lines explaining what `inheritEnv` does with regards to Python envs, along with a note that it may or may not conflict with other extensions (and after that we should update our "More info" link to point to this section instead of VS Code's release notes).

Thank you :)

**Comment by JoshuaPartlow** [comment]
Thanks for opening an issue @kimadeline. I'll take a look with @luabud and see what we can come up with.

**Comment by JoshuaPartlow** [comment]
Talked with @luabud and we're going to close this issue, but will track as part of https://github.com/microsoft/vscode-docs/issues/3951, which is a larger request for Conda specific content.
