### ISSUE TITLE
An unkown error occurred

### ISSUE THREAD

**Issue by OmarMohamed7** [microsoft/vscode-docs#3774]
Error in opening plugins

**Comment by gregvanl** [comment]
Hi @OmarMohamed7 Can you provide more details about your error and which extensions are failing to open?
The vscode-docs repo covers the VS Code documentation. Are you working through a specific tutorial when you run into problems?
If you are having a VS Code or an extension, you can create an issue in the VS Code product repo https://github.com/microsoft/vscode or perhaps track down the extension repo (often linked to from the Extensions view details page).

**Comment by OmarMohamed7** [comment]
Any extension I want to install , I am not able to view it from vs-code and must download and install manually
![image](https://user-images.githubusercontent.com/32777143/84418629-c0608e00-ac17-11ea-8655-fc7b5e9d3c2c.png)

**Comment by gregvanl** [comment]
Are you running behind a proxy server? Or having DNS issues?
This sounds similar to https://github.com/microsoft/vscode/issues/99649. In that issue, there are steps you can take to help debug the issue.

**Comment by gregvanl** [comment]
Haven't heard back from user and pointed them to a possible VS Code issue with diagnostic steps.
