### ISSUE TITLE
Documentation: Pin/Unpin Tab shortcuts shown in 1.46 release notes are outdated

### ISSUE THREAD

**Issue by weiliddat** [microsoft/vscode-docs#3780]
Not a big issue.
This is really just to reduce confusion over the actual shortcuts to pin/unpin tabs.

- VSCode Version: 1.46
- OS Version: N/A

Steps to Reproduce:

1. Go to https://code.visualstudio.com/updates/v1_46
2. Pin/Unpin tab commands show `⌘K ⌘Enter`
3. In VSCode it is instead `⌘K ⇧Enter`, also referenced in this issue https://github.com/microsoft/vscode/issues/99412

Does this issue occur when all extensions are disabled?: N/A

**Comment by bpasero** [comment]
I cannot explain this, I am using the usual syntax: `kb(workbench.action.pinEditor)`

**Comment by gregvanl** [comment]
I need to update the website keyboard shortcut mappings as the change to the pin/unpinEditor keybinding came after the 1.46 keybindings update.
Will fix shortly.

**Comment by gregvanl** [comment]
Fixed
![image](https://user-images.githubusercontent.com/12818376/84517901-c0e33e00-ac84-11ea-98d4-4742d9c3ec81.png)

Publishing soon.
