### ISSUE TITLE
The problem of code prompt sorting

### ISSUE THREAD

**Issue by 136323000** [microsoft/vscode-docs#3783]
I want  user snippets on top 
I made the following settings
![image](https://user-images.githubusercontent.com/49808133/84593027-4bda5900-ae7c-11ea-9120-220be043cc67.png)
The effect is as follows
![image](https://user-images.githubusercontent.com/49808133/84593035-5563c100-ae7c-11ea-8443-5e6cf1baf41b.png)
but when I want print <div></div> ：
![image](https://user-images.githubusercontent.com/49808133/84593054-7a583400-ae7c-11ea-8497-e125e2ccef51.png)
Prompt appears at the bottom

I just want the user snippets on top But I dont want  Other plug-in tips on top 
How do I set up？
thanks very much
by the way My English is so poor :-)

**Comment by mjbvz** [comment]
This is currently not possible. Please file a feature request against VS Code: https://github.com/microsoft/vscode/issues/new?template=feature_request.md
