### ISSUE TITLE
https://code.visualstudio.com/docs/cpp/config-clang-mac

### ISSUE THREAD

**Issue by MoonfacedBaboon** [microsoft/vscode-docs#3787]
Working from zsh in terminal.
Followed instructions to the letter then typed 
code . 

response
zsh: command not found: code

**Comment by gregvanl** [comment]
Hi @MoonfacedBaboon You need to make sure you have the VS Code install on your path.

There is a command **Shell Command: Install 'code' command in PATH** from the Command Palette for doing this on macOS.

See https://vscode-docs-master.azurewebsites.net/docs/setup/mac#_launching-from-the-command-line

**Comment by MoonfacedBaboon** [comment]
Thanks Greg, I’ve got that sorted now.
Kind regards
Jeremy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
