### ISSUE TITLE
[Python] Document that pipenv is only discovered after "select interpreter" is triggered

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3789]
This was raised here: https://github.com/microsoft/vscode-python/issues/12164#issuecomment-642975508.

We just need to update this section: https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments

😊

**Comment by gregvanl** [comment]
Hi @luabud Sounds like you know the update to make. Would you like to submit a PR? You can work with me or @JoshuaPartlow , if you have questions about creating a fork and submitting a PR. Thanks.

**Comment by JoshuaPartlow** [comment]
Hi Luciana - I have a PR in the works that includes this change. I updated that section to the below. If it needs further changes, just let me know.


The extension automatically looks for interpreters in the following locations:

- Standard install paths such as `/usr/local/bin`, `/usr/sbin`, `/sbin`, `c:\\python27`, `c:\\python36`, etc.
- Virtual environments located directly under the workspace (project) folder.
- Virtual environments located in the folder identified by the `python.venvPath` setting (see [General settings](/docs/python/settings-reference.md#general-settings)), which can contain multiple virtual environments. The extension looks for virtual environments in the first-level subfolders of `venvPath`.
- Virtual environments located in a `~/.virtualenvs` folder for [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/).
- Interpreters installed by [pyenv](https://github.com/pyenv/pyenv).
- Virtual environments located in the path identified by `WORKON_HOME` (as used by [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/)).
- Conda environments that contain a Python interpreter. VS Code does not show conda environments that don't contain an interpreter.
- Interpreters installed in a `.direnv` folder for [direnv](https://direnv.net/) under the workspace (project) folder.

You can also [manually specify an interpreter](#manually-specify-an-interpreter) if Visual Studio Code does not locate it automatically. 

> **Note**: Once the "select interpreter" flow is triggered, [pipenv](https://pipenv.readthedocs.io/) environments for the workspace folder will be searched for. If one is found, then no other interpreters are searched for or listed as pipenv expects to manage all aspects.

**Comment by JoshuaPartlow** [comment]
Update included in above PR.
