### ISSUE TITLE
Container debugging doc erroneously implies launch config alone will work

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docs#3791]
[This doc](https://code.visualstudio.com/docs/containers/debug-common) sort of implies that you can copy and paste the launch config and have a working debugging experience, but this is not the case. You need to use the commands `Docker: Add Dockerfiles to workspace` or if Dockerfiles are added already, `Docker: Initialize for debugging`.

For example, copying the launch config for Python (without the tasks that are also needed) results in a cryptic error: https://github.com/microsoft/vscode-docker/issues/2077

We should add text indicating that these commands are necessary, and either remove the examples or make it more clear that they alone are not enough.

**Comment by bwateratmsft** [comment]
I can't assign him but I believe @ucheNkadiCode is the right person to fix this. :smile:

**Comment by gregvanl** [comment]
Assigning to @ghogen to work with @ucheNkadiCode on updating that topic.

**Comment by ucheNkadiCode** [comment]
This is now being handled in #3816

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/ab31f64b2521b0d93acba6d2b7033f755f4f113d
