### ISSUE TITLE
[Python] Document launch.json "argsExpansion" property

### ISSUE THREAD

**Issue by int19h** [microsoft/vscode-docs#3793]
(https://github.com/microsoft/vscode-python/issues/11678)

The "argsExpansion" property allows the user to enable or disable shell expansion of arguments passed to the debuggee via the "args" property. Valid values are "none" and "shell".

If set to "shell" (default), when the app is run in integrated or external terminal, the arguments are passed via shell in that terminal, and various glob and substitution patterns (`*`, `?` globs, `$...` variable expansion etc) are applied by that shell. For example, assuming Linux+bash, this:
```json5
"args": ["/bin/*sh"],
"argsExpansion": "shell" // or omitted
```
would result in the debugged app seeing something like this in `sys.argv`:
```py
["/bin/bash", "/bin/dash", "/bin/rbash", "/bin/rzsh", "/bin/sh", "/bin/zsh"]
```

If set to "none", the arguments are passed directly, circumventing the shell. Thus, in the example above, the app will see `["/bin/*sh"]` in `sys.argv`.

The latter is useful for apps that do their own glob expansion - usually when the arguments are not meant to be filenames. For example, the standard `unittest` module allows matching tests by class/function name with a glob: `-k test_*bar` will match `test_foobar`. But if shell expansion is enabled, then the shell itself will try to expand that `*` as if it were a filename, and fail because there are no files matching the pattern.

**Comment by JoshuaPartlow** [comment]
Thanks @int19h I'll try to get this added soon and will follow up with any questions.

**Comment by int19h** [comment]
The feature itself has been regressed due to recent VSCode changes, and it's unclear whether we can implement it. It's not going to be surfaced in the Python extension for now, so it shouldn't be doc'd. I'll reopen if we find a way to light it up again.
