### ISSUE TITLE
Use matplotlib-cpp (C++ plotting library) with visual code 2019

### ISSUE THREAD

**Issue by Bourbaphy1989** [microsoft/vscode-docs#3796]
Hello everybody.
Is it possible to draw curves from c ++ using matplotlib in visual code?
On github, I only find matplotlib-cpp ( https://github.com/lava/matplotlib-cpp ), which works only for visual code studio 2017.
Thank you for your help

**Comment by gregvanl** [comment]
Hi @Bourbaphy1989 Looks like you've found some help in the library repo. https://github.com/lava/matplotlib-cpp
Closing this issue as there shouldn't be anything specific to the editor used.
