### ISSUE TITLE
Unable to load conda env

### ISSUE THREAD

**Issue by orakzai** [microsoft/vscode-docs#3797]
When I launch vscode from conda, there is still a prompt in the status bar to "Select python interpreter". I've uninstalled and reinstalled the conda, tried setting interpreter manually using command palette but the problem persists.

conda 4.8.2

VSCode
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.5.0

**Comment by JoshuaPartlow** [comment]
Hi @orakzai - When you say unable to load environment, is it just the setting of the interpreter that's not working? Meaning you're able to activate the environment, but when trying to select interpreter it doesn't work.

**Comment by orakzai** [comment]
Hi, @JoshuaKGoldberg - It shows in the command palette that my current environment is set. However, when I try to run a file from the debug menu, it gives an error that a Python interpreter was not set. 
![Screenshot 2020-06-23 at 12 29 46 AM](https://user-images.githubusercontent.com/2625277/85327748-eaa02e80-b4e8-11ea-9337-2efc03aa547b.png)
![Screenshot 2020-06-23 at 12 32 02 AM](https://user-images.githubusercontent.com/2625277/85327815-099ec080-b4e9-11ea-9368-f7e9dcb0706d.png)

**Comment by JoshuaPartlow** [comment]
Hi @orakzai - If you're selecting an interpreter and it's not working, then I'd suggest opening an issue on the Python extension repo at https://github.com/microsoft/vscode-python/issues. They should be better able to help you there. There's a somewhat similar sounding issue currently open about setting the interpreter that you might take a look at as well (https://github.com/microsoft/vscode-python/issues/12463).

**Comment by orakzai** [comment]
Turns out, uninstalling the extension, then reloading the window and reinstalling does the magic as described in the above issue. Thanks.

**Comment by JoshuaPartlow** [comment]
Happy to help, glad things are working now. I'll close the issue, but feel free to reopen or create a new one if you have any issues with the docs.
