### ISSUE TITLE
Right margin line

### ISSUE THREAD

**Issue by VijitCoder** [Microsoft/vscode-docs#38]
I don't see editor setting like "right margin". I suppose, it is usual feature for any IDE. Am I missing something or it is really absent?

**Comment by egamma** [comment]
Not yet supported, tagged as enhancement

**Comment by VijitCoder** [comment]
I tried to add it by myself, but obfuscated js-code is hard to explore. Pity. 
Issue is closed.

**Comment by mark0978** [comment]
Could someone reopen this issue so it doesn't get lost....

**Comment by egamma** [comment]
This is now supported, you can set rulers using the `editor.rulers` setting.
