### ISSUE TITLE
Extensions Documentation: References & Advanced Topics

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-docs#3803]
**References** 

By sidebar/menu title alone, I did not realize https://code.visualstudio.com/api/references/commands was an article listing pre-built commands. Once I clicked on it, saw the article's title "Built-in Commands" and began reading, I realized there are built-in commands we can leverage while creating extensions.
 
**References proposed change:**
- Rename article to "Built-in Commands" on left sidebar/menu. This would be more accurate and match the actual article's title. A previous page in a different topic is already called "Command," which is very similar to this current title.

**Advanced Topics**

As a side note, I believe there is a typo on https://code.visualstudio.com/api/advanced-topics/remote-extensions within https://code.visualstudio.com/api/advanced-topics/remote-extensions#debugging-in-a-development-container.

**Advanced Topics proposed change in bold:**
> Run yarn install or npm install in a new VS Code terminal window (Ctrl+Shift+`) to ensure the Linux versions Node.js native dependencies are **install**.

**Comment by ornellaalt** [comment]
The typo part of this issue has been fixed! Keeping open so we can address the other part.
