### ISSUE TITLE
It throws referenced error when building in Mac Os with VS code

### ISSUE THREAD

**Issue by jackxia123** [microsoft/vscode-docs#3805]
Executing task: /usr/bin/clang++ -std=c++1z -stdlib=libc++ -g /Users/charlieyue/Desktop/projects/trial/usesrck0.cpp -o /Users/charlieyue/Desktop/projects/trial/a.out <

Undefined symbols for architecture x86_64:
  "Stock::buy(long, double)", referenced from:
      _main in usesrck0-6f4236.o
  "Stock::sell(long, double)", referenced from:
      _main in usesrck0-6f4236.o
  "Stock::show()", referenced from:
      _main in usesrck0-6f4236.o
  "Stock::acquire(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long, double)", referenced from:
      _main in usesrck0-6f4236.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
终端进程已终止，退出代码: 1

终端将被任务重用，按任意键关闭。

> Executing task: /usr/bin/clang++ -std=c++1z -stdlib=libc++ -g /Users/charlieyue/Desktop/projects/trial/usesrck0.cpp -o /Users/charlieyue/Desktop/projects/trial/a.out <

Undefined symbols for architecture x86_64:
  "Stock::buy(long, double)", referenced from:
      _main in usesrck0-1812bb.o
  "Stock::sell(long, double)", referenced from:
      _main in usesrck0-1812bb.o
  "Stock::show()", referenced from:
      _main in usesrck0-1812bb.o
  "Stock::acquire(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long, double)", referenced from:
      _main in usesrck0-1812bb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gregvanl** [comment]
Hi @jackxia123 Does your project build if you run the command from a terminal?
Do you need to include a C++ file, which defines the Stock class?

**Comment by gregvanl** [comment]
No response from user.
