### ISSUE TITLE
[Python] Document launch.json "code" property

### ISSUE THREAD

**Issue by int19h** [microsoft/vscode-docs#3806]
(from https://github.com/microsoft/vscode-docs/issues/3251#issuecomment-561914382)

More detailed description of the feature: https://github.com/microsoft/vscode-python/issues/12500

**Comment by luabud** [comment]
We haven't added that to the Python extension yet, this issue is tracking it for once we do that. If folks from the docs team want to close it for now as it's not actionable, that's fine. I can create another one in the future when the time comes 😊
