### ISSUE TITLE
Add Editor Actions to the User Interface Docs

### ISSUE THREAD

**Issue by KyleMit** [microsoft/vscode-docs#3808]
Here's an example of the portion of the interface I'm referring to:

![editor-actions UI](https://user-images.githubusercontent.com/4307307/85452705-27ac0580-b569-11ea-99ca-e8a38f608bd9.png)

It's labelled as **Editor Actions** according to the Dev Tools window:

![editor actions dev tools](https://user-images.githubusercontent.com/4307307/85453522-f2ec7e00-b569-11ea-9f40-17f4d22bde30.png)

In the API reference, it's referenced via the [`contributes.menus`](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) as `editor/title`

> The editor title menu bar 

However, I can't find it officially referred to in the [User Interface Docs](https://code.visualstudio.com/docs/getstarted/userinterface) with similar UI elements like breadcrumbs, status bar, etc.

Can it be documented there?

**Comment by gregvanl** [comment]
Hi @KyleMit Thank you for creating an issue and PR. I'm not sure editor title bar actions need to be explicitly documented as title bar actions are common across most of the VS Code UI and readily discoverable by users.

**Comment by KyleMit** [comment]
@gregvanl , that's a good point on inherent discoverability.  My particular use case was actually one of taxonomy.  Because I have lots of installed extensions, my editor actions became very cluttered. I was trying to find a way to disable them one by one within each extension.  Without knowing how to refer to that part of the UI, it was difficult to find the correct search terms to identify if the issue was already entered for other VS Code extensions.  

Without a clear, common, and consistent language term, it makes it hard to search and refer to that particular set of features.
