### ISSUE TITLE
Start page: needs updated screenshots 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#381]
"Working Files" is replaced with "Opened Editors". There are more things in the status bar that changed too.

Also, you can no longer "ext install" in the command palette, but have to use the new viewlet.

**Comment by gregvanl** [comment]
This is calling out the home page hero shot.  Assigning to Brad to update.

**Comment by gregvanl** [comment]
Probably want to update the vscode repo README image at the same time https://github.com/Microsoft/vscode/issues/8759

**Comment by bgashler1** [comment]
We will have these new screenshots tomorrow.

**Comment by bgashler1** [comment]
Here are a couple of images to chose from for the README image..

1)
![screen shot 2016-07-06 at 9 05 16 pm](https://cloud.githubusercontent.com/assets/11839736/16642200/6624dde0-43bd-11e6-8595-c81885ba0dc2.png)

2)
![screen shot 2016-07-06 at 8 55 35 pm](https://cloud.githubusercontent.com/assets/11839736/16642174/0f371ce6-43bd-11e6-8d5f-33e74d589e4c.png)

**Comment by bgashler1** [comment]
Done
https://github.com/Microsoft/vscode-website/commit/a8fd656250853fb741730c89a5e1a17868bc5246
