### ISSUE TITLE
Debug tests section in python/testing page

### ISSUE THREAD

**Issue by pwinston** [microsoft/vscode-docs#3810]
The section **Debug tests**:
https://code.visualstudio.com/docs/python/testing#_debug-tests

It starts with "Because tests themselves are source code, they are prone to code defects just like the production code they test. For this reason, you may occasionally need to step through and analyze tests in the debugger.".

I think this mis-states why someone might want to debug a test. Almost all of the time I want to debug a test it's because my own code is raising an unhandled exception. That is, I'm using the debugger because the test is failing and I want to fix my code, not because I want to "step through and analyze tests in the debugger".

I would propose an opening covers both use cases: debugging the test or debugging the actual program. And does not imply debugging the test is the main reason to use a debugger. Not sure of exact wording I will try to think of something.

**Comment by pwinston** [comment]
Reading my comment it doesn’t have to be an unhandled exception. If a test is failing in anyway I might want to run that test in the debugger. To debug it, to fix it. 

So more than likely I’m debugging the code which is being tested, I’m not debugging the test code, although I could be. 

The confusion might be because the vscode command is called “Debug Test” but I think that means “debug the code that this test is testing” in many cases.

**Comment by JoshuaPartlow** [comment]
Hi @pwinston - Thanks for the feedback on the docs. I'll take a look at the language and see if we can make it clearer.

**Comment by JoshuaPartlow** [comment]
Rephrased the intro text to the section in above PR.
