### ISSUE TITLE
Short description of Common hostnames

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/vscode-docs#3818]
Hi, is it possible that we could have a short one line description of what each hostname is used for within vscode. We run vscode in an airgapped environment and allowing external access is normally not allowed unless there is a reason for it. This will allow us to approve whitelisting 

This page here: - 
https://code.visualstudio.com/docs/setup/network

**Comment by doc-han** [comment]
Hi @ross-p-smith I'll like to give this a try
