### ISSUE TITLE
Java Web Apps with Visual Studio Code, Build and deploy to a Web App, right-click to deploy a jar

### ISSUE THREAD

**Issue by HughDevlin** [microsoft/vscode-docs#3820]
Page: Java Web Apps with Visual Studio Code
The first sentence on this page identifies it as a tutorial.
Section: Build and deploy to a Web App
URL: https://code.visualstudio.com/docs/java/java-webapp#_build-and-deploy-to-a-web-app
Markdown: java-webapp.md
Statement: "Right-click on the name.war or name.jar file and choose Deploy to Web App, and follow the prompts to choose the Web App for your deployment."

For deployment via right-click on a jar to work, the jar MUST be named app.jar. Apparently, the context menu deployment does not do the required rename of the jar for you. If you right-click deploy a jar NOT named app.jar, you end up with your jar sitting there in wwwroot on the target web app service, but it does not execute.

**Comment by yaojinyang** [comment]
@HughDevlin, thanks for the feedback. This issue has been fixed.

**Comment by HughDevlin** [comment]
Thank you for your attention to this. What was fixed? The tutorial still illustrates right-clicking on an artifact named demo-0.0.1-SNAPSHOT.war and selecting "Deploy to Web App". Does this work? Or does the war have to be named app.war?

**Comment by yaojinyang** [comment]
For .war it works; for .jar, need to be app.jar.

**Comment by HughDevlin** [comment]
ok, thanks, please close
