### ISSUE TITLE
Java Web Apps with Visual Studio Code, Download and test the Spring Boot app, duplicate projects

### ISSUE THREAD

**Issue by HughDevlin** [microsoft/vscode-docs#3821]
Page: Java Web Apps with Visual Studio Code
The first sentence on this page identifies it as a tutorial.
Section: Download and test the Spring Boot app
URL: https://code.visualstudio.com/docs/java/java-webapp#_download-and-test-the-spring-boot-app
Markdown: java-webapp.md
Statement: "Paste https://github.com/spring-guides/gs-spring-boot.git as the URL of the remote repository and then decide the parent directory under which to put the local repository....the Java Extension Pack...will automatically build the project for you (this may take several minutes)."

Upon cloning, the project(s) are built automatically. Unfortunately for very early on in a tutorial, an error message "Duplicate projects" is unexpectedly issued. The source repository includes TWO projects with the same name, two pom.xml's, one in the "complete" directory and one in the "initial" directory. The tutorial does not warn of the repository being multi-project. 

In order to continue with the tutorial, a circumvention is to delete the "initial" directory.

**Comment by yaojinyang** [comment]
@HughDevlin, thanks for reporting the issue. We have already created a PR for fix. It may take two or more days to become effective.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/4122
