### ISSUE TITLE
Java Web Apps with Visual Studio Code, add Azure remote debugging

### ISSUE THREAD

**Issue by HughDevlin** [microsoft/vscode-docs#3822]
Page: Java Web Apps with Visual Studio Code
The first sentence on this page identifies it as a tutorial.
Section: Build and deploy to a Web App
URL: https://code.visualstudio.com/docs/java/java-webapp
Markdown: java-webapp.md

This page includes a section 
"Debug the application"
https://code.visualstudio.com/docs/java/java-webapp#_debug-the-application
which teaches local debugging,

...and includes a section
"Deploy Web Apps to the cloud"
https://code.visualstudio.com/docs/java/java-webapp#_deploy-web-apps-to-the-cloud
which teaches Azure deployment,

...but conspicuously absent is a tutorial on interactive debugging of web apps on Azure via Visual Studio Code.

Please add a subsection on using Visual Studio Code to debug Azure Web Apps.

**Comment by gregvanl** [comment]
Closing older issue without upvotes
