### ISSUE TITLE
Java Web Apps with Visual Studio Code, use one running example

### ISSUE THREAD

**Issue by HughDevlin** [microsoft/vscode-docs#3824]
Page: Java Web Apps with Visual Studio Code
URL: https://code.visualstudio.com/docs/java/java-webapp
Markdown: java-webapp.md

Early sections of this tutorial use a consistent running example, a "Hello, world" known as "the Spring Boot Getting Started sample project" described as "A simple Spring Boot Getting Started web app", cloned from a Spring.io "Spring Guides" repository:
"Scenario"
"Download and test the Spring Boot app"
"Make a change"
"Debug the application"

The next section "Deploy Web Apps to the cloud" switches to a project called "demo-0.0.1-SNAPSHOT" of unspecified origin.

The final section "Connect with data services" switches to "the Spring Data Azure Cosmos DB Sample Project."

Please use one running example project for this tutorial.

**Comment by gregvanl** [comment]
Closing older issue without upvotes.
