### ISSUE TITLE
Document exposing the interpreter path to other extensions using API

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-docs#3829]
Hi Python extension dev here👋

We're moving `python.pythonPath` setting to an internal VSCode storage. Hence users can no longer read the setting value and have to use this API to get it.

https://github.com/microsoft/vscode-python/issues/12596#issue-646434218 describes the API.

**Comment by brettcannon** [comment]
Please hold off on doing this; we may be tweaking this API in the next quarter or two.

**Comment by JoshuaPartlow** [comment]
Ok @brettcannon. @karrtikr - given timeframe this has been open and would be open, I'm going to close for now. Can you please re-open/create when we're ready.
