### ISSUE TITLE
Update screenshots in getting started

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#385]
The screenshots on https://code.visualstudio.com/Docs/?dv=osx#vscode-in-action are not up to date with our June changes (e.g. extensions viewlet).

**Comment by gregvanl** [comment]
The /docs carousel images need to be updated.  Assigning to Brad.

**Comment by bgashler1** [comment]
Done
https://github.com/Microsoft/vscode-website/commit/a8fd656250853fb741730c89a5e1a17868bc5246
