### ISSUE TITLE
how should i update your includePath ?

### ISSUE THREAD

**Issue by tariqawni** [microsoft/vscode-docs#3861]

**Comment by gregvanl** [comment]
Hi @tariqawni You can update the `includePath` in the C/C++ Configurations editor (use the C/C++: Edit Configurations (UI) command to open the configuration editor).

![image](https://user-images.githubusercontent.com/12818376/87208137-90fa7b00-c2c2-11ea-8569-31783f7997ad.png)

You can find the includePath setting there:

![image](https://user-images.githubusercontent.com/12818376/87208197-b8e9de80-c2c2-11ea-9c1b-00fb2f69f735.png)

**Comment by gregvanl** [comment]
Closing as haven't heard back from user.

**Comment by gregvanl** [comment]
Closing as haven't heard back from user.
