### ISSUE TITLE
Some links with fragments are broken on https://code.visualstudio.com/updates/v1_47

### ISSUE THREAD

**Issue by thierer** [microsoft/vscode-docs#3864]
Don't know of a better place to report this: Some links with fragments (where the fragment starts with a number?) are invalidated by a spurious underscore on https://code.visualstudio.com/updates/v1_47 (maybe other places as well, that's where I noticed it).

For example the second and third link [in the "hex editor"section](https://github.com/microsoft/vscode-docs/blob/master/release-notes/v1_47.md#hex-editor).

The Markdown is ok, so maybe your cms breaks them.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/01549a0b8697734c026e9a41cfe48a7a55344ace
Thanks for pointing this out.
And you're correct, the links were munged by our website CI build.
