### ISSUE TITLE
Python VS Code Jupyter docs should recommend secure remote server configurations

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-docs#3869]
👋 I'm a dev from the Python VS Code data science team. Our extension allows users to connect to and execute code on remote Jupyter servers, as described in the docs [here](https://github.com/microsoft/vscode-docs/blob/master/docs/python/jupyter-support-py.md#connect-to-a-remote-jupyter-server) and [here](https://github.com/microsoft/vscode-docs/blob/master/docs/python/jupyter-support.md#connect-to-a-remote-jupyter-server).

Would it be possible to update that documentation to recommend secure settings for configuring the remote Jupyter server that the user connects to? In particular, recommending that the user sets it up with tokens and SSL? These ensure that requests sent to the remote Jupyter server are authenticated and connections to the remote Jupyter server are encrypted, respectively.

Thanks so much! 😊

**Comment by tsutsumi41** [comment]
tey

**Comment by JoshuaPartlow** [comment]
Addressed by above PR.
