### ISSUE TITLE
Updates to Setup/Get Started documentation

### ISSUE THREAD

**Issue by ornellaalt** [microsoft/vscode-docs#3883]
On [Visual Studio Code on macOS](https://code.visualstudio.com/docs/setup/mac):
- The Launching from the command line section is outdated and inaccurate for macs running fresh installations (not upgrades) of Mojave and newer (e.g. Catalina) out of the box.
- zsh is the new default shell on Mojave and Catalina unless the mac was upgraded from an older OS with the bash shell as the default.

On [Requirements](https://code.visualstudio.com/Docs/supporting/requirements):
- Update Supported platforms

On [Settings](https://code.visualstudio.com/docs/getstarted/settings):
- Explain the format for launch.configurations and what it does, including examples.

**Comment by gregvanl** [comment]
Closing old issue without upvotes
