### ISSUE TITLE
Updates to API documentation

### ISSUE THREAD

**Issue by ornellaalt** [microsoft/vscode-docs#3892]
On https://code.visualstudio.com/api/language-extensions/language-server-extension-guide: 
- Out of date with respect to current definition of TextDocuments

https://code.visualstudio.com/api/references/extension-manifest#approved-badges
- List is out of date 

On https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide:
- Add explanation for how to differentiate between languages when using syntax highlighting, and changing colors in setting.json

**Comment by ARI925** [comment]
Good

**Comment by gregvanl** [comment]
Closing old issue without upvotes
