### ISSUE TITLE
Updates to various Editor topics

### ISSUE THREAD

**Issue by ornellaalt** [microsoft/vscode-docs#3894]
For https://code.visualstudio.com/docs/editor/intellisense:
- Is there a way to turn IntelliSense off for one file, not globally? If so, add details

On https://code.visualstudio.com/docs/editor/refactoring:
- Powershell extension not listed

Feedback for https://code.visualstudio.com/docs/editor/extension-gallery:
- Not accessible for beginners: add information about where to find extensions after they are downloaded

On https://code.visualstudio.com/docs/editor/variables-reference:
- Predefined variables out of date
- Update description for ${file}: expands to include the entire directory and the file with extension-- the user likely wants ${fileBasename}

**Comment by gregvanl** [comment]
Suggestion: Have a short quickstart showing how to search, install, and run a new extension.
I have seen verbatim saying a user has installed an extension but now what?

**Comment by gregvanl** [comment]
Closing as most of these seem to be small issues.
