### ISSUE TITLE
Side by side editing needs updates for tabs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#390]
Refs: https://code.visualstudio.com/docs/editor/codebasics#_side-by-side-editing

Screen shots should be made with tabs and we should mention that you can also DND tabs (not just to change their index but also to initiate a split action if you drag it enough to the side).

**Comment by gregvanl** [comment]
Duplicate of https://github.com/Microsoft/vscode-docs/issues/387
