### ISSUE TITLE
Unity.md: Unity Visual Studio Code Intellisense stops working in Unity 2020.1

### ISSUE THREAD

**Issue by 8ude** [microsoft/vscode-docs#3913]
It seems that projects created in the latest version of Unity no longer have Intellisense in VS Code.  I've tried making a few new project to no avail.  Intellisense is working in Unity 2019 projects without issue.  Updating VS Code does not solve the problem.

Is there an update to the .NET framework targeting pack, or some other extension, required for Unity 2020.1?

**Comment by gregvanl** [comment]
Hi @8ude Is this still an issue or have you found a workaround or additional dependency to get Unity IntelliSense to work?

**Comment by 8ude** [comment]
I believe some combination of updated vs code, deleting .vscode files, regenerating project files in Unity, and running "Developer: Reload Window" helped.  

I went through most fixes on this forum thread: https://forum.unity.com/threads/intellisense-not-working-for-visual-studio-code.812040/

Some of them worked for a time, but intellisense in VSCode continued to intermittently stop working without rhyme or reason, so I had switch back to Visual Studio :(

**Comment by gregvanl** [comment]
OK, sounds like a product issue if regenerating the Unity project files fixes IntelliSense. Thanks for adding a link to the forum thread in case other people run into this.
