### ISSUE TITLE
CLANG C++ error while first using lldb debugger through tutorial in VScode

### ISSUE THREAD

**Issue by mandarkolli** [microsoft/vscode-docs#3918]
Hi

I am trying to setup & follow this tutorial for setting up VScode to use CLANG.
https://code.visualstudio.com/docs/cpp/config-clang-mac

I was able to get through the initial steps fine of compiling & running the sample given in the above link.
But when I reached the part of setting up the lldb debugger, it gives compilation error for the same code, that built successfully without the debugger.

I am seeing issues when I reach the following step in the above wiki: Debug helloworld.cpp#
When I follow the steps in this section, it opens up the "launch.json" file for me & tries to compile the given sample program in debugger mode. It gives following error/warning:

``` 
Executing task: /usr/bin/clang++ -g /Users/Mandar/Documents/projects/hellow_world/helloworld.cpp -o /Users/Mandar/Documents/projects/hellow_world/helloworld <

/Users/Mandar/Documents/projects/hellow_world/helloworld.cpp:10:11: error: expected expression
    msg = {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};
          ^
/Users/Mandar/Documents/projects/hellow_world/helloworld.cpp:11:29: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const string& word : msg)
                            ^
1 warning and 1 error generated.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Note: When I execute the same code just by doing "clang++ build active file" it works fine.
When I execute the same by "clang++ - build & debug active file" the compilation fails with above errors.

**Comment by gregvanl** [comment]
Hi @mandarkolli Can you share the contents of your task.json and launch.json files? They should be located in a .vscode folder.

**Comment by mandarkolli** [comment]
Hi @gregvanl Thanks for the response.
Please find below the contents of both the files:

task.json:
```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
	  {
		"type": "shell",
		"label": "clang++ build active file",
		"command": "/usr/bin/clang++",
		"args": [
		  "-std=c++17",
		  "-stdlib=libc++",
		  "-g",
		  "${file}",
		  "-o",
		  "${fileDirname}/${fileBasenameNoExtension}"
		],
		"options": {
		  "cwd": "${workspaceFolder}"
		},
		"problemMatcher": ["$gcc"],
		"group": {
		  "kind": "build",
		  "isDefault": true
		}
	  }
	]
  }
```

launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ build active file"
        }
    ]
}
```

**Comment by gregvanl** [comment]
Hi @mandarkolli I wonder if there is an issue because the `preLaunchTask` value task name has a "C/C++: " prefix so it doesn't match your task?
Could you try changing to `"preLaunchTask": "clang++ build active file"`.

**Comment by mandarkolli** [comment]
Thanks @gregvanl it worked fine after the changes.

**Comment by gregvanl** [comment]
@mandarkolli I'm glad that worked for you. If the two files were autogenerated for you by the C++ extension and didn't work as created, could you open an issue in the C++ extension repo at https://github.com/microsoft/vscode-cpptools/issues.
