### ISSUE TITLE
"Working Files" is replaced with "Opened Editors"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#392]
Refs: https://code.visualstudio.com/docs/editor/codebasics#_working-files

This section should be rewritten and udpated to explain "Opened Editors" view.

The point about using "Close All Files" is also wrong because with the June update, entries just come and go based on opening or closing editors in the editor area.

**Comment by gregvanl** [comment]
Duplicate of https://github.com/Microsoft/vscode-docs/issues/377
