### ISSUE TITLE
Settings Sync documentation still uses "Preferences Sync"

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-docs#3923]
Testing microsoft/vscode#103613

Settings Sync documentation still uses "Preferences Sync":
<img width="418" alt="2020-08-05_13-04-58" src="https://user-images.githubusercontent.com/1898161/89405847-7e862c80-d71c-11ea-9c99-a8249e594c01.png">

**Comment by gregvanl** [comment]
Updated with https://github.com/microsoft/vscode-docs/commit/d03bb7e3af36b9ec097b0f4dd2dcad9587a7c323
