### ISSUE TITLE
there are PROBLEMS in my code.

### ISSUE THREAD

**Issue by gautsang** [microsoft/vscode-docs#3925]
My code always shows that there is a problem.

![image](https://user-images.githubusercontent.com/44471252/89489507-a42b3880-d7e5-11ea-9861-90f807b013d4.png)

The error means There need ")".

How can I solve this?

Thanks

**Comment by gregvanl** [comment]
Hi @gautsang, I'm not sure this is the best place to ask your question. This repository is for VS Code documentation and I don't recognize the code in the image as being from one of the VS Code tutorials.
What extensions do you have installed and is this warning coming from a specific extension or linter?
You might also try posting your question on StackOverflow for your programming language.

**Comment by gautsang** [comment]
> My code always shows that there is a problem.
> 
> ![image](https://user-images.githubusercontent.com/44471252/89489507-a42b3880-d7e5-11ea-9861-90f807b013d4.png)
> 
> The error means There need ")".
> 
> How can I solve this?
> 
> Thanks

**Comment by gregvanl** [comment]
@gautsang Looks like you found the C++ extension repo and entered an issue https://github.com/microsoft/vscode-cpptools/issues/5918.
