### ISSUE TITLE
Update Sort imports documentation for Python

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-docs#3928]
With upgrading to isort5, many old CLI flags and config options are outdated. Please update the doc [here ](https://code.visualstudio.com/docs/python/editing?source=post_page---------------------------#_sort-imports)to include the link to the [isort5 upgrade guide](https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/), which will help users coming from isort4 to migrate to isort5.

**Comment by JoshuaPartlow** [comment]
Added the following note to the linked section in the above PR.

> **Note**: For those migrating from isort4 to isort5, some CLI flags and config options have changed, refer to the project's [isort5 upgrade guide](https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/) on GitHub for guidance.

**Comment by karrtikr** [comment]
Apologies, looks like the older link to isort5 upgrade guide is suddenly no longer valid. I have made a aka.ms to point to the new link. Can you update to the new link instead: https://aka.ms/AA9j5x4
