### ISSUE TITLE
feature case-changing-in-regex-replace does not include global file replacements

### ISSUE THREAD

**Issue by Aypahyo** [microsoft/vscode-docs#3929]
Context:
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_47.md#case-changing-in-regex-replace

Setup: Have multiple files that contain the line `#include "function.h"`

(CTRL+H) When using Edit->Replace on one file by 
running the regex `#include "([a-z0-9]+.h)"` replace with `#include "\U$1"` the result is
`#include "FUNCTION.H" `as it should be.

(CTRL+SHIFT+H) When using Edit->Replace in files by 
running the regex `#include "([a-z0-9]+.h)"` replace with `#include "\U$1"` the result is
`#include "\U$1"` which seems unexpected.

I think this would be worth patching so all vscode regex tools behave in a consistent manner.

**Comment by gregvanl** [comment]
Hi @Aypahyo This looks like a feature request for VS Code. The release notes mention that this isn't currently supported. 
I think https://github.com/microsoft/vscode/issues/101454 covers your request, which you can upvote.

**Comment by irridia** [comment]
See #105101

**Comment by Aypahyo** [comment]
Thanks @gregvanl and @irridia
