### ISSUE TITLE
Integrated Terminal FAQ "Can I use Cmder's shell with the terminal on Windows?" update

### ISSUE THREAD

**Issue by robole** [microsoft/vscode-docs#3930]
For https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows , if you follow the suggested setting, it will cause issues with running tasks. A better version is: 

```json
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": ["/K", "C:\\cmder\\vendor\\bin\\vscode_init.cmd"]
```

which is actually suggested in the [cmder wiki](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration) link you have included! This tripped me up, so it can mislead others too! 

I can make a pull request if you wish?

**Comment by Tyriar** [comment]
@robole yes please 👍

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/a00efbab113ab30517eec334e9e9b7dfd5820288
