### ISSUE TITLE
Emmet supported languages not listed

### ISSUE THREAD

**Issue by robole** [microsoft/vscode-docs#3935]
Hi,

This is regarding the [Emmet in Visual Code User Guide](https://code.visualstudio.com/docs/editor/emmet). What are the supported languages for Emmet?

In the section [Emmet abbreviations in other file types](https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types), it explains: "To enable the Emmet abbreviation expansion in file types where it is not available by default, use the `emmet.includeLanguages` setting. Make sure to use language identifiers for both sides of the mapping."

In the section below it, [Emmet Configuration](https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration) has an explanation for `emmet.includeLanguages`: "Use this setting to add mapping between the language of your choice and one of the Emmet supported languages to enable Emmet in the former using the syntax of the latter. Make sure to use language ids for both sides of the mapping."

It is quite confusing! What are Emmet's supported syntaxes (languages) that go on the right-hand side of the mapping? I suggest adding a list for these. I was only aware of Emmet supporting HTML, CSS, and XSL; the values in your examples cover a bigger set.

Also, the example you use includes a Vue mapping. There is no `vue-html` ID in your [language ID doc](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers). Is this provided by the Vetur extension? Or is it missing from the docs? Either way a note about this would help clarify this. You shouldn't assume everyone has Vetur installed.

```json
"emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue-html": "html",
    "plaintext": "pug"
}
```

I'm happy to make a pull request if you want?

**Comment by gregvanl** [comment]
The list of supported language ids is listed at the beginning of the topic in https://code.visualstudio.com/docs/editor/emmet#_how-to-expand-emmet-abbreviations-and-snippets

![image](https://user-images.githubusercontent.com/12818376/99025757-6c3b3c00-251e-11eb-9da8-add3aeefb27a.png)

**Comment by robole** [comment]
Hi @gregvanl 

What you have referenced are not language IDs, they are file types. Is JSX === javascriptreact?

```
"emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue-html": "html",
    "plaintext": "pug"
}
```

Your response did not cover the other points I made. There is not a clear explanation of what the value on the right-hand side actually represents. Why am I assigning "javascript" to "javascriptreact"?

Also, I mentioned that it should be noted that if you want to use Emmet in Vue, you either need to add the Vetur extension, or add your own language ID. 

I will raise another issue with this.
