### ISSUE TITLE
Standardize version control/source control

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-docs#3936]
In the product, we use "Source Control" but there's a few places in the docs where we call it "version control". Can we standardize? https://code.visualstudio.com/docs/editor/versioncontrol

**Comment by gregvanl** [comment]
Closing as no upvotes. Reopen if you think there is user data suggesting this is confusing. Source control and version control are used interchangeably and "version control" may actually be a more approachable term. "Source control", while popular, is actually a  shorten term for "source code control".
