### ISSUE TITLE
[Python] Document new cell commands 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3940]
There were new commands and default shortcuts for cells in Python scripts that were introduced [by this PR](https://github.com/microsoft/vscode-python/pull/12529), and they're listed here: https://github.com/Microsoft/vscode-python/issues/12414#issuecomment-673597305. We should add them to our docs :)

cc @claudiaregio

**Comment by JoshuaPartlow** [comment]
Addressed by above PR.
