### ISSUE TITLE
Rename 'Open Repository in Container' to 'Clone Repository in Container Volume'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-docs#3948]
For 1.49 'Open Repository in Container' was changed to 'Clone Repository in Container Volume'.

**Comment by bamurtaugh** [comment]
@gregvanl I'm happy to make the change- does it make the most sense for me to identify locations in the docs where we say "Open Repository in Container," update it to the new wording, and then open a PR with the changes?

Also, if we're saying that the change is effective for 1.49, does that mean we should wait (to either create and/or merge the PR)? I just checked the extension, and I don't believe I saw the updated wording yet:

![image](https://user-images.githubusercontent.com/25310137/90836026-2007a380-e303-11ea-8cc8-89dddebdd349.png)

**Comment by Chuxel** [comment]
@bamurtaugh Yeah, we should wait until this is in stable. We'll potentially get bugs in the near term about it - last rename like this did cause confusion. However, VS Code stable users vastly outnumber insiders, so we should always favor stable for docs.
