### ISSUE TITLE
Add instructions on how to setup conda for VS Code Python extension

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-docs#3951]
Currently we don;t have a clear documentation on how people should set up conda. People seem to have different expectation of what the extension should and should not do to set up conda. Some of the set up steps are change how things works, for example `conda init powershell` sets up power shell to have a activated conda environment even outside  of VSCode. and depending on what users have installed in their environment this can impact how quickly powershell can start.

We should have some documentation on how users can set up conda, for some common cases. We should also recommend to users to launch VS Code from an activated conda environment.

**Comment by rjmolyneaux** [comment]
PR #5260 helps to close this issue
