### ISSUE TITLE
Add to C/C++ Configurations That the cppStandard Option Does Not Configure IntelliSense

### ISSUE THREAD

**Issue by joec58** [microsoft/vscode-docs#3953]
This is from issue [ #5985](https://github.com/microsoft/vscode-cpptools/issues/5985).

The _C/C++ Configurations_ section of [Using C++ on Linux in VS Code](https://code.visualstudio.com/docs/cpp/config-linux) refers to a GUI page titled _IntelliSense Configurations_. However, setting "C++ standard" there only updates the `cppStandard` option in _c_cpp_properties.json_ but IntelliSense will not be configured to use that standard until the `tasks.json` compiler argument for the standard is manually added.

**Comment by gregvanl** [comment]
Closing as external issue in the C++ extension repo is closed
