### ISSUE TITLE
'Other languages (C++, C#, Python, PHP)' sounds finite

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#396]
Ref: https://code.visualstudio.com/docs

Reading the sentence It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages (C++, C#, Python, PHP) and runtimes.

It feels to me like those are the only languages we support. I would expect 'many other languages' and some etc inside. Since we also have good support for Powershell, Go...

**Comment by gregvanl** [comment]
Website content

**Comment by waderyan** [comment]
Great catch. Change made.
