### ISSUE TITLE
Updates to remote containers documentation

### ISSUE THREAD

**Issue by komondor** [microsoft/vscode-docs#3968]
## Problem description

| details      | value                                                                                                                                             |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| Problem  | Inaccurate Api Doc                                                                                                                                |
| Link     | [Adding environment variables-Option 2: Use an env file](https://code.visualstudio.com/docs/remote/containers-advanced#_option-2-use-an-env-file) |
| Section  | Dockerfile or image: Edit devcontainer.json and add a path to the .env file relative to the location of devcontainer.json                         |
| Amendment    | .env file should be relative to the location of the root of the workspace, not devcontainer.js                                                    |

## Context information:

| details                    | value                                            |
| -------------------------- | ------------------------------------------------ |
| Task executed              | `Remote-Container: Reopen folder from container` |
| devcontainer.json location | `./devcontainer/devcontainer.json`               |

**Comment by gregvanl** [comment]
Reviewed the issue with engineering and the current documentation is correct. PR #4091 added for clarification.
