### ISSUE TITLE
Update isort5 upgrade guide link

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-docs#3973]
Apologies, looks like the older link to isort5 upgrade guide is suddenly no longer valid. I have made a aka.ms to point to the new link. Can you update to the new link instead: https://aka.ms/AA9j5x4

_Originally posted by @karrtikr in https://github.com/microsoft/vscode-docs/issues/3928#issuecomment-684603518_

**Comment by gregvanl** [comment]
Hi @karrtikr Do you also want to point https://github.com/timothycrosley/isort#configuring-isort to a documentation page as wel. That link for configuration is not 404ing but just goes to the root of the repo.

**Comment by gregvanl** [comment]
Fix the upgrade link with https://github.com/microsoft/vscode-docs/commit/f4ca2c7e2db199fc1452977be78cf875f8c7987e

**Comment by karrtikr** [comment]
> Do you also want to point https://github.com/timothycrosley/isort#configuring-isort to a documentation page as well?

No that's fine. Just this one, thanks!

**Comment by gregvanl** [comment]
Wouldn't it be better to point to https://pycqa.github.io/isort/docs/configuration/config_files than the root of the repo?

**Comment by karrtikr** [comment]
I think you're right. I have created the aka.ms link for that too so we can use that: https://aka.ms/AA9j6k4

**Comment by JoshuaPartlow** [comment]
@gregvanl - thanks Greg! much appreciated.
