### ISSUE TITLE
Variable erased in extension continuous integration documentation for GitHub Actions

### ISSUE THREAD

**Issue by TobiahZ** [microsoft/vscode-docs#3977]
Hello,

I was setting up my extensions CI using GitHub actions, and tried to follow this documentation:

https://code.visualstudio.com/api/working-with-extensions/continuous-integration

I noticed the variable `{{ secrets.VSCE_PAT }}` disappears

On the website, in the publish section for GitHub actions, after env, it shows this:

> `VSCE_PAT: $`

However, when I check the source document, it is clearly there on line 189

https://github.com/Microsoft/vscode-docs/blob/master/api/working-with-extensions/continuous-integration.md

> `VSCE_PAT: ${{ secrets.VSCE_PAT }}`

I suspect something is happening in the parsing between github and the documentation website.

**Comment by gregvanl** [comment]
@TobiahZ Thanks for calling this out. Indeed, we need to escape double leading curly braces otherwise our CI build drops the rest of the string. Fixing shortly.
