### ISSUE TITLE
VS Code extension docs: Approaches similar to the TreeItem example are flagged by Typescript 4.0

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-docs#3979]
The Python extension extends the `TreeItem` class in a way similar to what's described in [TreeView API docs](https://code.visualstudio.com/api/extension-guides/tree-view#tree-data-provider), however overriding the `tooltip` property with an accessor is flagged by the TypeScript 4.0 compiler (it's in their [announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-rc/#properties-overridding-accessors-and-vice-versa-is-an-error)):

![image](https://user-images.githubusercontent.com/51720070/92156473-e1331c80-eddd-11ea-8d51-a0f410ceb16f.png)

What would a TS 4.0-friendly snippet look like?

**Comment by gregvanl** [comment]
Hi @kimadeline What happens if you just set the tooltip property with the value you want, rather than creating an accessor?

**Comment by kimadeline** [comment]
What you suggest seems to be working if I have an accessor that returns a static value 👍 We have other properties (`tooltip` being one of them) that get computed depending on the data being passed to the class, so the logic was put in an accessor ([snippet](https://github.com/microsoft/vscode-python/blob/c4e65e3b47572f8b2675942d48fae92b01f02e6e/src/client/testing/explorer/testTreeViewItem.ts#L78-L116), although there's a lot going on in here. [Here](https://github.com/microsoft/vscode-python/blob/c4e65e3b47572f8b2675942d48fae92b01f02e6e/src/client/testing/explorer/testTreeViewItem.ts#L121-L123)'s an accessor that only contains a ternary condition). 

What would you suggest with regards to where this logic should live instead?

**Comment by alexr00** [comment]
I have updated the documentation, you can see the change [here](https://github.com/microsoft/vscode-docs/commit/efb1b2e7a359c80d289569ccd537bdb7374262fc)
