### ISSUE TITLE
Add ARM to main page download control

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#3980]
It would be good to put ARM as an option on the main code.visualstudio.com page download control.
Currently users need to go to the Other downloads to find the ARM links
ARM can also be added to the release notes link header

**Comment by chgray** [comment]
+1,  perhaps the download link could default to the ARM one (I believe it's doing that today for x86 and x64)

**Comment by gregvanl** [comment]
ARM has been added to the Download and Insiders download pages.

![image](https://user-images.githubusercontent.com/12818376/95486931-8777c200-0948-11eb-9064-9ac6aa7936e8.png)

What's left to do:
- add ARM to the website release notes versioned links
![image](https://user-images.githubusercontent.com/12818376/95487158-cd348a80-0948-11eb-8b9c-917f1d4107b2.png)
- detect that the reader is on ARM and change the default Download button to provide ARM as we do for other platforms

**Comment by joaomoreno** [comment]
@gregvanl On the release notes, it's hard to add just one or two Linux ARM links, since there's no obvious good choice. Could we change the structure of the release notes affordance to fit more downloads links?

For Windows, I suggest to replace the system setup with the arm64 user setup.

**Comment by gregvanl** [comment]
@joaomoreno How about including the Windows ARM 64 user link and then a general ARM link for Linux, which could link out to a new FAQ section describing the various installation URLs? We occasionally get asked for previous version download links and it would probably be could to include them in a FAQ. We still want to direct people to the latest version but we also don't want to prevent folks rolling back if they really need to.

Here's what the release notes would look like:

![image](https://user-images.githubusercontent.com/12818376/97215042-33ab0c80-1781-11eb-9945-68e45eeba972.png)

With highlighted ARM link going to a new FAQ section: 

![image](https://user-images.githubusercontent.com/12818376/97215319-8684c400-1781-11eb-96ad-59da1e7eeddb.png)

**Comment by joaomoreno** [comment]
Sounds great. You can also indicate that `{version}` can be replaced with `latest`, to get the latest bits.

**Comment by gregvanl** [comment]
https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions
