### ISSUE TITLE
Update doc for disabling crash reporter

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-docs#3989]
With https://github.com/microsoft/vscode/pull/102011 we have changed how crash reporter behaves and also added new ways to disable it. 

This should be updated in https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-crash-reporting

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/def9ca47009fdacb15f9faa26c449bf5f79dff15
