### ISSUE TITLE
VS Code python docs for Export should be modified to not say we will install Tex

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-docs#3994]
Docs say this:

```
Note: For PDF export, you must have TeX installed. If you don't, you will be prompted to install it when you select the PDF option. Also, be aware that if you have SVG-only output in your Notebook, they will not be displayed in the PDF. To have SVG graphics in a PDF, either ensure that your output includes a non-SVG image format or else you can first export to HTML and then save as PDF using your browser.
```

This makes it sound like we'll install Tex. Tex is not something we can support installing. It's very dependent upon the OS and the version of nbconvert. The user has to do this step.

We should probably change the wording on this paragraph to make this clearer. This sentence here could be interpreted as we'll install Tex for you:

```
 If you don't, you will be prompted to install it when you select the PDF option.
```

See discussion here:
https://github.com/microsoft/vscode-python/issues/13229

**Comment by JoshuaPartlow** [comment]
Addressed by above PR.
