### ISSUE TITLE
Django collectstatic STATIC_ROOT path out of date

### ISSUE THREAD

**Issue by pomalley08** [microsoft/vscode-docs#3997]
Django settings.py apparently no longer uses os to build paths as described in the file 

`Build paths inside the project like this: BASE_DIR / 'subdir'`

So it seems the code here: [https://code.visualstudio.com/docs/python/tutorial-django#_use-the-collectstatic-command](https://code.visualstudio.com/docs/python/tutorial-django#_use-the-collectstatic-command) should be updated from

`STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')`

to

`STATIC_ROOT = BASE_DIR / 'static_collected'`

**Comment by JoshuaPartlow** [comment]
Thanks for the feedback @pomalley08, I'll take a look at it shortly.

**Comment by JoshuaPartlow** [comment]
Addressed in above PR.
