### ISSUE TITLE
Why do we have system requirments?

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#401]
Refs: https://code.visualstudio.com/docs/supporting/requirements

Why do we have system requirments specified here? And how did we get to those numbers?
AFAIK neither sublime nor atom are exposing their system requirments.

My suggestion is to remove them, we are light weight and work everywhere that should be our marketing moto.

**Comment by gregvanl** [comment]
We received a lot of doc feedback verbatim asking for detailed system requirements so we added this.  Users coming from heavier IDEs (Visual Studio) are really concerned about requirements and download time.  We estimated the system requirements and they are there to let users know that VS Code is a fast download and small disk footprint.
