### ISSUE TITLE
Flask: Hard reset required to clear cached static files

### ISSUE THREAD

**Issue by pomalley08** [microsoft/vscode-docs#4017]
While working through the VS Code flask tutorial I noticed the css didn't apply after adding the navbar [https://code.visualstudio.com/docs/python/tutorial-flask#_run-the-app](https://code.visualstudio.com/docs/python/tutorial-flask#_run-the-app) 

According to this post [https://stackoverflow.com/questions/41144565/flask-does-not-see-change-in-js-file](https://stackoverflow.com/questions/41144565/flask-does-not-see-change-in-js-file) it seems static files served by flask are cached by the browser and require a hard reset or other trick to see the latest changes.

Figured it might be worth addressing this in the tutorial to avoid confusion

**Comment by JoshuaPartlow** [comment]
Hi @pomalley08 - thanks for the feedback on the Flask tutorial. I'll take a look and see if there's something we can do to make things clearer.

**Comment by JoshuaPartlow** [comment]
Addressed with above PR.
