### ISSUE TITLE
Python Virtual Environment

### ISSUE THREAD

**Issue by jsjohnson1** [microsoft/vscode-docs#4018]
Hello.  Hopefully someone can help with my inexperience with scripting and VS Code.  I have been trying to setup a virtual environment with Python on my Windows laptop and I keep running into errors.  I am able to build the directory with the command
"python -m venv venv_test1"
However, I keep running into issues trying to activate it.  I have watched several videos online and my results are not consistent with any of the videos.  This is the error I keep getting.

PS D:\> source .\VS_Code_Folder2\venv_test1\Scripts\activate.bat
source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.      
At line:1 char:1
+ source .\VS_Code_Folder2\venv_test1\Scripts\activate.bat
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException

Could someone please help me get going in the right direction?  Thanks.

**Comment by JoshuaPartlow** [comment]
Hi @jsjohnson1 - `source` is a Linux command, for Windows you should just need to do `venv_test1\Scripts\activate` from your command prompt (depending where you're sitting in the directory tree). If you haven't looked at it, the [VS Code Python tutorial](https://code.visualstudio.com/docs/python/python-tutorial) might be helpful. Let me know if that helps!

**Comment by jsjohnson1** [comment]
Thank you @JoshuaPartlow.
