### ISSUE TITLE
File encoding: update screenshot with encodings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#402]
Refs: https://code.visualstudio.com/docs/editor/codebasics#_file-encoding-support

We since added "UTF 8 with BOM"

**Comment by gregvanl** [comment]
Closing since the screenshot is accurate for "Reopen with Encoding" (https://github.com/Microsoft/vscode/issues/9101).  Reopen if you think we should instead show the dropdown for "Save with Encoding" instead.

**Comment by bpasero** [comment]
In this context the screenshot is right, thanks 👍
