### ISSUE TITLE
Python extension: Cannot copy-paste in jupyter notebook cells

### ISSUE THREAD

**Issue by aabrol** [microsoft/vscode-docs#4020]
Hi! I cannot copy-paste in jupyter notebook cells. Looked at the keyboard shortcuts and searched online, but couldnt find a fix specifically for this. Would highly appreciate any help on this.

I'm using Python v2020.8.109390 extension in VSC 1.50.0-insider on macOS Catalina (v10.15.6).

Version: 1.50.0-insider
Commit: 8c1015f5e1a7a686d19ec8a5f56a495332f16062
Date: 2020-09-21T07:56:21.563Z (6 hrs ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by aabrol** [comment]
Some more details on the issue:
1. Copy-paste (keyboard shortcuts and mouse) works well for the editor (*.py, *.m, *.txt, etc. files) but not for the jupyter notebook (*.ipynb) cells.
2. I tried a couple of extensions and they worked well for the editor except the notebook.

**Comment by aabrol** [comment]
For people who see this in future: I just found that commenting code blocks with `#%%` while working with .py files in VS creates interactive "cells" thus allowing the same level of interaction as jupyter notebooks. Hence, I would mark my problem as solved.

**Comment by JoshuaPartlow** [comment]
Hi @aabrol - I'll close the issue, but I believe standard copy/paste via keyboard should work within the native Jupyter notebook experience. Do you know if you marked your notebook as [trusted](https://code.visualstudio.com/docs/python/jupyter-support#_trusted-notebooks)?  If you're still having a problem, I'd suggest opening an issue on the extension at https://github.com/microsoft/vscode-python/issues
