### ISSUE TITLE
Search renders HTML in results

### ISSUE THREAD

**Issue by timtim17** [microsoft/vscode-docs#4031]
I was doing some searching through the docs when I stumbled upon this result for the May 2017 (v1.13) release notes, which include a `<textarea>` tag that gets rendered on the page and consumes the rest of the page's HTML.

![screenshot](https://user-images.githubusercontent.com/6354860/94336719-fe50aa80-ff99-11ea-8571-68bcd7618841.png)

[Searching for "<textarea>"](https://code.visualstudio.com/Search?q=%3Ctextarea%3E) reproduces the issue for me.

**Comment by aromalanil** [comment]
I just found the cause of the issue, when the markdown is processed, the text `<textarea>`  present in the markdown is converted into HTML.

***Pages Affected***
1. https://code.visualstudio.com/updates/vJanuary
2. https://code.visualstudio.com/updates/v1_13

This issue only occurs when the content of the pages are displayed as search results. The page itself has no issues.

**Comment by gregvanl** [comment]
Thanks @timtim17 for calling this out and @aromalanil for the sleuthing!

**Comment by aromalanil** [comment]
@gregvanl But the issue isn't solved yet. Why the bug was caused only in search? Why it act normal in the page itself?

**Comment by gregvanl** [comment]
Hi @aromalanil Thanks for your continued interest. 
For rendering Markdown files on the site, we use the markdown-it library, which handles embedded code blocks with HTML tags. 
For the search results, we're taking the text results from Bing and rendering them in a much simpler way, assuming the text will render. Not ideal, but works pretty well in most cases.
