### ISSUE TITLE
Build task broken using clang on macOS

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vscode-docs#4034]
- VSCode Version: 1.49.2
- OS Version: 10.15.7

Steps to Reproduce:

1. Follow the tutorial here: https://code.visualstudio.com/docs/cpp/config-clang-mac

Does this issue occur when all extensions are disabled?: Yes

![Screen Shot 2020-09-26 at 7 08 24 PM](https://user-images.githubusercontent.com/434849/94354001-ac586500-002b-11eb-9b94-4bd64b533867.png)
![Screen Shot 2020-09-26 at 7 09 06 PM](https://user-images.githubusercontent.com/434849/94354020-cdb95100-002b-11eb-9422-629544ee0ccd.png)

**Comment by gregvanl** [comment]
This error was also mentioned in a 8/26 verbatim.

**Comment by gregvanl** [comment]
Hi @acgetchell You have two build tasks defined and the second is the default build task (`isDefauld":true) and doesn't set the `--std=c++17` argument. The clang++ compiler default is c++11, which doesn't support that style of initialization.
The tutorial directs you to replace the contents of `task.json` with the code block provided, not add a second build task.
Try replacing `task.json` with the tutorial code block and you should be able to build `helloworld.cpp`
