### ISSUE TITLE
Mention VSCode update story and insiders in Setting Up page

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#404]
Refs: https://code.visualstudio.com/docs/setup/setup-overview

I would expect that the update story is mentioned in the overview - how we do monthly updates and that we also support insider releases (daily updates).
I see that currently the updates are per platform, while I would expect that this section is top level.

**Comment by waderyan** [comment]
This is a good thought. @gregvanl and I discussed adding a Note in the Cross Platform section to discuss the update story and the insiders.
