### ISSUE TITLE
Language Server Extension Guide sample doesn't compile

### ISSUE THREAD

**Issue by TymurGubayev** [microsoft/vscode-docs#4041]
The [guide](https://github.com/microsoft/vscode-docs/blob/master/api/language-extensions/language-server-extension-guide.md#lsp-sample---a-simple-language-server-for-plain-text-files) has following instructions.

```bash
> git clone https://github.com/microsoft/vscode-extension-samples.git
> cd vscode-extension-samples/lsp-sample
> npm install
> npm run compile
> code .
```

But executing `npm run compile` throws `src/extension.ts:28:5 - error TS2584: Cannot find name 'console'`.

On another note, it would be nice to have a warning the `npm install` takes a very long time.

**Comment by gregvanl** [comment]
Hi @TymurGubayev, I am unable to reproduce your compiler error and the current version of the lsp-sample doesn't have a call to console on line 28 of client\src\extension.ts.
Can you try recloning the vscode-extension-samples repository and see if you still run into issues?

**Comment by gregvanl** [comment]
Couldn't reproduce the build error.
