### ISSUE TITLE
Example from "Using YAML to write a grammar" doesn't work

### ISSUE THREAD

**Issue by TymurGubayev** [microsoft/vscode-docs#4042]
In [Using YAML to write a grammar](https://github.com/Microsoft/vscode-docs/blob/master/api/language-extensions/syntax-highlight-guide.md#using-yaml-to-write-a-grammar) there is a screenshot illustrating how a yaml grammar could look like. Unfortunately, it doesn't work that way.

```yaml
repository:
  test:
    match: >
      (?x)
        \s*          # Leading whitespace
        [ \t]*       # Optional whitespace
        (?:
            (test1)    # something
          | (test2)    # or else
        )?
        $
```

produces

```json
"repository": {
    "test": {
      "match": "(?x)\n  \\s*          # Leading whitespace\n  [ \\t]*       # Optional whitespace\n  (?:\n      (test1)    # something\n    | (test2)    # or else\n  )?\n  $\n"
    }
```

Even without comments, the best result will have spaces where linebreaks were.

**Comment by aeschli** [comment]
The conversion looks correct and I believe the produced sample works. 

New lines are allowed here as the regex starts with `(?x)`. That turns on the the freespacing mode (https://www.rexegg.com/regex-modifiers.html#freespacing), where whitespace is ignored.
Please speak up if I missed something.
