### ISSUE TITLE
error in vs code when using gcc on terminal

### ISSUE THREAD

**Issue by madhavaggarwal53** [microsoft/vscode-docs#4054]
C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x39): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status

please help
i am a vs code user and learning c programming
when i am trying to execute the code that error is showed on terminal.

mai jab terminal mai gcc first.c type karke enter kar rha hu toh ye ho rha hai
so what should i do in this case
please help!!!

**Comment by TylerMSFT** [comment]
Hi @madhavaggarwal53 ,

I'm not sure what to make of the error you are reporting. Can you clarify: "mai jab terminal mai gcc first.c type karke enter kar rha hu toh ye ho rha hai"  I tried a language translator but it didn't work out.

**Comment by TylerMSFT** [comment]
No response. #please-close

**Comment by anipaul2** [comment]
Hello @TylerMSFT He wants to say that when he runs Vs code with terminal using gcc with the file name it shows errors. What I mean to say is Mingw has been installed but in bin folder gcc.exe file is not present and hello world program cannot be executable.

**Comment by anipaul2** [comment]
Sir @TylerMSFT Can you call me please? This is my number 8876414060. It's urgent because I'm facing the same issue while doing in vs code. It'll be too much kind of you if you contact me sooner.

**Comment by TylerMSFT** [comment]
Hi, I'm sorry but we don't do dev support from here. Comments here are for improving documentation.  I suggest posting in the VS Developer community: https://developercommunity.visualstudio.com/spaces/62/index.html
