### ISSUE TITLE
VS code can't recognize virtual environment

### ISSUE THREAD

**Issue by joselluis7** [microsoft/vscode-docs#4055]
VS code does not list my virtual environment interpreter and when i set it manually changing the json settings it shows "warning:Select Python Interpreter"

**Comment by JoshuaPartlow** [comment]
Hi @joselluis7  - If you're selecting an interpreter and it's not working, then I'd suggest opening an issue on the Python extension repo at https://github.com/microsoft/vscode-python/issues. They should be better able to help you there. There's a somewhat similar issue about setting the interpreter that you might take a look at as well (microsoft/vscode-python#12463). Some users there had luck uninstalling/reinstalling the extension.

**Comment by joselluis7** [comment]
Hi @JoshuaPartlow - I'm not selecting the interpreter, the interpreter (that is the virtual interpreter located in my project "env" folder) does not apear in the list above, so when I try to set it manually shows the warning in the status bar (where is supposed to apear the selected interpreter).

**Comment by AmirrezaAsadi** [comment]
I have the same problem in mac too

**Comment by joselluis7** [comment]
@AmirrezaAsadi - I've solved this issue installing "pylance" and now it's working perfectly.

**Comment by JoshuaPartlow** [comment]
Hi @joselluis7 - Glad you were able to get things working, though I'm not sure why that would be the fix. If the problem reoccurs, please do open an issue on  https://github.com/microsoft/vscode-python/issues.
