### ISSUE TITLE
Editor section seems overloaded

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#406]
Refs: https://code.visualstudio.com/docs/editor/

Currently the editor section seems to contain some items which IMHO do not belong there, those are:
- extension marketplace
- debug
- tasks
- git
- integrated terminal

All those areas are not part of the editor. So my suggestion is either to rename the editor section to something more general, or to introduce a new section which would be a sibling to the editor section

**Comment by gregvanl** [comment]
Will be addressed during TOC update.
