### ISSUE TITLE
Fixing the continuous integration script for GitHub Actions

### ISSUE THREAD

**Issue by golf1052** [microsoft/vscode-docs#4060]
Regarding [this page](https://github.com/Microsoft/vscode-docs/blob/master/api/working-with-extensions/continuous-integration.md), currently if someone uses the continuous integration (CI) script for GitHub Actions, any failing npm tests will not fail the Actions build due to a bug in version 1.2 of GabrielBB/xvfb-action. Version 1.4 of the action fixes this bug but I also found out when browsing issues on the action's repo that xvfb is included in GitHub Actions Linux images now and can be run like so

```
- run: xvfb-run -a npm test
  if: runner.os == 'Linux'
- run: npm test
  if: runner.os != 'Linux'
```

I want to provide a PR to update the documentation but my question is should I just update the version number to point to v1.4 or should I update the script to use xvfb directly?

Also I've tested that both methods correctly fail the Action build if any tests fail as shown in this PR on my own extension https://github.com/golf1052/code-sync/pull/47

**Comment by joaomoreno** [comment]
@golf1052 A PR about using xvfb directly would be much appreciated! Thanks!
