### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by alexmachina** [microsoft/vscode-docs#4067]
In the section **Next Steps**, at https://vscode-docs.readthedocs.io/en/stable/editor/codebasics/, there are these links which are currently broken:

 [Editing Evolved](https://vscode-docs.readthedocs.io/docs/editor/editingevolved.md) 
 [Debugging](https://vscode-docs.readthedocs.io/docs/editor/debugging.md)
 [Customization](https://vscode-docs.readthedocs.io/docs/customization/overview.md)

**Comment by gregvanl** [comment]
Hi @alexmachina The VS Code team does not maintain the readthedocs content, which looks to be a fairly old version of the codebasics.md topic.
The Next steps links in the official topic on code.visualstudio.com are fine. https://code.visualstudio.com/docs/editor/codebasics#_next-steps
