### ISSUE TITLE
Cannot find virtual environment in Python interpreters

### ISSUE THREAD

**Issue by keegangood** [microsoft/vscode-docs#4072]
I'm on Manjaro 20.1.1 running VS Code version 1.49.1. I'm using pipenv and when I try to use `ctrl+shift+p` to set my Python interpreter, it only finds local versions and no virtual environments. The bottom taskbar is also missing the Interpreter selection drop-up menu as well. 

Please let me know if you need any more info on my setup.

Thanks

**Comment by JoshuaPartlow** [comment]
Hi @keegangood - So just to confirm, when you open the command palette and use the Python: Select interpreter command, you're only seeing the global Python installs? Also, you say you don't see the select interpreter option in the bottom left, do you have a workspace and Python file (.py) open?

Thanks!

**Comment by keegangood** [comment]
I figured out the issue. Somehow VS Code forgot where to look for virtual environments. I updated the path to the directory containing the environments and it worked after a restart. Thanks for the reply!
