### ISSUE TITLE
Global launch configuration is not ignored

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-docs#4079]
I regularly combine workspace and global launch configurations, and I am confident that global ones are not ignored when the workspaces ones are present. Hence, this statement feels incorrect:

> **Tip**: If a workspace contains a `"launch.json"`, the global launch configuration is ignored.

https://code.visualstudio.com/Docs/editor/debugging#_global-launch-configuration

**Comment by weinand** [comment]
Yes, this limitation had been removed when we added support for "multi root" workspaces.

I've just verified this by introducing an "echo" launch configuration in user settings, workspace settings, and individual folders:

![2020-10-29_11-22-40](https://user-images.githubusercontent.com/1898161/97555950-140e2100-19d9-11eb-91e7-cc4dce0ae3dd.png)

@gregvanl we should remove the "Tip".

/cc @isidorn
