### ISSUE TITLE
 "Change Cell to Code" shortcut error

### ISSUE THREAD

**Issue by rBatist4** [microsoft/vscode-docs#4084]
The shortcut "Ctrl + ç C" that changes the cell in Jupyter to code unfortunately does not work, even changing to another set of keys. In contrast, the shortcut "Ctrl + ç M" works perfectly and changes the cell to Markdown.

**Comment by JoshuaPartlow** [comment]
Hi @rBatist4 - Are you referring to code cells in the [interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py) or to the [Juptyer support](https://code.visualstudio.com/docs/python/jupyter-support) ?

**Comment by rBatist4** [comment]
Hello @JoshuaPartlow, how are you?
I happened to read your comment before it was edited, I was referring to Jupyter Notebooks.

**Comment by JoshuaPartlow** [comment]
Hi @rBatist4 - I think then that you might be using the wrong key combo. If you look at [this doc section](https://code.visualstudio.com/docs/python/jupyter-support#_switch-between-code-and-markdown) I believe it's actually just the **M** key for markdown and **Y** key for code when a cell is selected and in command mode. Does that work for you?

**Comment by JoshuaPartlow** [comment]
Also, I'm doing well thanks. Hope you are too.

**Comment by rBatist4** [comment]
It worked, you're absolutely right, I was looking at the wrong shortcuts.
Now I am much better thank you and have a great week.

**Comment by JoshuaPartlow** [comment]
Excellent, I'm glad that worked for you. If you run into other problems, please open an issue.
