### ISSUE TITLE
cannot see the output of hellowrld

### ISSUE THREAD

**Issue by smtanvirrahman** [microsoft/vscode-docs#4087]
make a step by step full detailed guide line

**Comment by gregvanl** [comment]
Hi @tanvir181002196 Can you provide more details about what type of tutorial you want? Are you looking for a tutorial for a specific programming language or specific scenario, such as building VS Code extensions?
We have hello world tutorials for C++, Java, Python, Node.js as well as creating your first extension on code.visualstudio.com.

**Comment by tanvir181002196** [comment]
I have installed visual studio code latest version and did as it is in https://code.visualstudio.com/docs/cpp/config-mingw but the code which is fine in codeblocks is not showing output in visual studio code... it is not showing any error that means everything is fine just cant not see the output :( so if some one can help in this regard by doing a full execution in VSC...

**Comment by gregvanl** [comment]
Which section of the tutorial isn't working for you? Can you share a screen shot of VS Code when you don't see any output?

**Comment by smtanvirrahman** [comment]
okay, I somehow solved the problem, but would you please tell me what the "output" is supposed to show ??

**Comment by gregvanl** [comment]
You should see build output for the build task when you run it and console output if you manually run helloworld.exe.
Sounds like you're unblocked so closing this issue.
