### ISSUE TITLE
Editing - Fast?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#409]
Refs: https://code.visualstudio.com/docs/editor/editingevolved#_editing-fast

I am not sure what this headline implies, maybe we should update it?

**Comment by gregvanl** [comment]
This was added to split the doc between code intelligence and power editor features in preparation to splitting into two topics.

**Comment by gregvanl** [comment]
Removed that section from editingevolved.md with https://github.com/Microsoft/vscode-docs/commit/6aeeb54d2f7c2e29e400298e900777873a288c0b
