### ISSUE TITLE
Unable to install Matplotlib (Vs code)

### ISSUE THREAD

**Issue by VENOMNBB** [microsoft/vscode-docs#4095]
I am currently working on a project that needs the functionalities of **MATPLOTLIB**.

I used to all the possible commands variations **pip install matplotlib**; **pip3 install matplotlib**; **pip3 install --user matplotlib**. All the above command showed the same error while i tried to install the package.

My system info:
OS: Windows 10
OS Build: 19042.610
OS Version 20H2
Vs code Version: 1.50.1 (system setup)
Python Version: 3.9.0

Need an urgent solution.

Error message that I get:

Collecting matplotlib
  Using cached matplotlib-3.3.2.tar.gz (37.9 MB)
Collecting certifi>=2020.06.20
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0.tar.gz (52 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\myusername\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\pip-install-7yu8hx30\\kiwisolver\\setup.py'"'"'; __file__='"'"'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\pip-install-7yu8hx30\\kiwisolver\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\MYUSERNAME\AppData\Local\Temp\pip-pip-egg-info-mrmmax8l'
         cwd: C:\Users\MYUSERNAME\AppData\Local\Temp\pip-install-7yu8hx30\kiwisolver\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\myusername\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\pip-wheel-ulic44pr\\cppy\\setup.py'"'"'; __file__='"'"'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\pip-wheel-ulic44pr\\cppy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', 
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\MYUSERNAME\AppData\Local\Temp\pip-wheel-_89mtg6q'
           cwd: C:\Users\MYUSERNAME\AppData\Local\Temp\pip-wheel-ulic44pr\cppy\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\myusername\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\tmpiaarbdfq', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MYUSERNAME\AppData\Local\Temp\pip-install-7yu8hx30\kiwisolver\setup.py", line 59, in <module>
        setup(
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
        return installer(requirement)
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\myusername\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\myusername\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\tmpiaarbdfq', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by JoshuaPartlow** [comment]
Hi @VENOMNBB - Python 3.9 was recently released and it looks like the matplotlib package (or it's dependencies) might not have been updated for that version. Your install error is when it tries to build one of the dependent packages since a wheel is not available. The matplotlib package on [pypi.org](https://pypi.org/project/matplotlib/) also doesn't list Python 3.9. If you look at matplotlib's GitHub page there are a few issues already opened. If you want to be able to do a pip install without building, it looks like you might need to use an earlier version of Python at this time.
`

**Comment by VENOMNBB** [comment]
I actually did see the fact that wheel is missing. Therefore I installed the wheel package using the command **pip3 install wheel**.  After that I narrowed the issue to a specific dependency named **kiwisolver**. This dependency although downloads under the command **pip3 install kiwisolver**. But could not build itself and stops the installation process showing an error saying **MSVC++ v14.0 or higher required**. Its strange because I already had the latest version of MSVC++ preinstalled into my system. 

Therefore I uninstalled the new python 3.9.0 64bit, and installed the python 3.8.6 64bit, and the problem persisted. Then I installed the 32bit version of the 3.8.6 and to my surprise everything was resolved and back to normal.

Thanks for the help but please look into the matter that I mentioned in the above statement.

**Comment by JoshuaPartlow** [comment]
Hi @VENOMNBB - Glad things are working for you now. Just to clarify, when I said wheel not available, I meant the pre-built package files (wheel files) of matplotlib and it's dependencies, not the wheel package itself. With Python 3.9 just released you might encounter packages that don't have compatible wheels yet for `pip install` to use. Thanks for bringing this to our attention though, I'll look into adding a note to clarify the version of Python to use in our tutorial until matplotlib can be installed with wheels for Python 3.9.

**Comment by VENOMNBB** [comment]
Thank you for the assistance.
