### ISSUE TITLE
Type constraints of providers are missing

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-docs#4097]
A type constraint in [`CompletionItemProvider<T>`](https://code.visualstudio.com/api/references/vscode-api#CompletionItemProvider) is missing . It should be `CompletionItemProvider<T extends CompletionItem>`, not just `<T>`. 

See https://github.com/microsoft/vscode/blob/5264ab94a337ea8acae51c550aefe1f0b578f656/src/vs/vscode.d.ts#L4032

We can see the same issue for  [`CodeLensProvider<T>`](https://code.visualstudio.com/api/references/vscode-api#CodeLensProvider) and other providers.

**Comment by gregvanl** [comment]
Thanks for pointing this out but unfortunately the API generation is limited and misses the full type constraint.
The workaround as you noted is to review vscode.d.ts or use IntelliSense within the editor
![image](https://user-images.githubusercontent.com/12818376/107569539-4533eb00-6b9d-11eb-806a-639d716e0d4a.png)
This issue may be reopened if there is an update to the API generation build.
