### ISSUE TITLE
Update problems panel label and action in Key bindings page 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-docs#410]
https://code.visualstudio.com/docs/customization/keybindings has old action and label: 

`ctrl+shift+M` Show Errors and Warnings `workbench.action.showErrorsWarnings,`

Update to 

`ctrl+shift+M` Problems `workbench.actions.view.problems`

**Comment by gregvanl** [comment]
Already updated in vscode-docs vnext
