### ISSUE TITLE
VS code can not find python interpreter

### ISSUE THREAD

**Issue by dmitterberger** [microsoft/vscode-docs#4108]
I was using conda and conda env till now in VSCode and now with no apparent reason, I can not select python interpreter. Even when I click and reselect the interpreter path it is not updated. 
Any ideas on how to proceed?

**Comment by JoshuaPartlow** [comment]
Hi @dmitterberger - Could you provide a little more information. When you say click and select the path, does that mean when you use the Command Palette your environment shows up as an option, but selection fails? If you attempt to set the path manually, does that work? Also, what version of the extension are you using? Thanks!

**Comment by dmitterberger** [comment]
Exactly - I was trying to select an environment via the command palette. there were no options shown (previously I saw all my conda environments), when trying to select "enter interpreter path" manually and selecting the .exe of my specific python environment, it is not showing up. I am using python extension 2020.10.332292344

**Comment by JoshuaPartlow** [comment]
Thanks @dmitterberger One thought I have might be to try setting the path in settings using the [python.venvFolders](https://code.visualstudio.com/docs/python/settings-reference#_general-settings) setting. Could you give that a try? If that doesn't work I can move this issue over to the extension repo for triage there.

**Comment by khrome666** [comment]
Greetings! 
I'm having a similar problem. I've recently reinstalled all my Windows 10 system, and all of a sudden VS Code can't find the Python interpreter. I've tried each and every solution I could find online, but to no success. Setting %PATH% and settings.json correctly, upgrading Code and the extensions, even reinstalling Python, nothing worked! 
Any ideas? Thanks.

**Comment by JoshuaPartlow** [comment]
Hi @khrome666 - You said you tried reinstalling Python. Did you also try reinstalling the Python extension?

**Comment by khrome666** [comment]
Hello, @JoshuaPartlow . Sorry for my late reply, I completely forgot I posted here :-)
I solved the issue by using Revo Uninstaller to remove every last bit of the VSCode installation, then reinstalling it again. After that, I reinstalled the extensions one by one, keeping an eye for a comeback of the problem. So far, so good. I'm still puzzled by it, though...

**Comment by JoshuaPartlow** [comment]
Closing this issue, but please re-open an issue on https://github.com/Microsoft/vscode-python if the issue reoccurs.
