### ISSUE TITLE
Which SSG does vscode-docs use?

### ISSUE THREAD

**Issue by smholvoet** [microsoft/vscode-docs#4109]
I'm curious as to which SSG is used to generate the different parts of the VS Code website (docs, release notes, etc) 🤔?

**Comment by gregvanl** [comment]
Hi @smholvoet, I'm not sure what 'SSG' stands for but our website uses markdown-it to convert the Markdown files to HTML and then embedded into various .handlebars template files to render on our site. We have a few hand-edited pages such as the landing page and /docs, but everything else is converted from the Markdown.

**Comment by smholvoet** [comment]
Cheers for the swift response 👍 

So [markdown-it](https://github.com/markdown-it/markdown-it) converts the markdown files to HTML. This is similar to what a static site generator (SSG) does, except markdown-it doesn't arrange page order, etc (which makes sense as it's not an SSG). 

I've noticed the markdown files do have metadata elements (YAML front matter) at the top:

```
---
Order: 6
Area: nodejs
TOCTitle: Angular Tutorial
ContentId: f6b7b0c2-ccbe-4e5f-8f2e-6c1ecea52f69
PageTitle: Angular JavaScript Tutorial in Visual Studio Code
DateApproved: 10/8/2020
MetaDescription: Angular JavaScript tutorial showing IntelliSense, debugging, and code navigation support in the Visual Studio Code editor.
MetaSocialImage: images/angular/Welcome-to-app.png
--- 
```

Which tool do you guys use to construct the order and do additional stuff like read out the metadata elements?

**Comment by gregvanl** [comment]
We use custom gulp tasks, which read the metadata (using the gulp-front-matter npm module), and fill in the navigation templates.
The website infrastructure repo (gulp tasks and templates) is home-made (and not pretty) and not public.
