### ISSUE TITLE
Document `sash.hoverBorder` in theme-color.md

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-docs#4111]
In the docs repo. Please make the change in vnext then pull into master.

**Comment by joaomoreno** [comment]
@JacksonKearl This feature is not part of 1.51, so it shouldn't go into `master`. I'll document it at the end of the iteration.

**Comment by Highaboveus2** [comment]
--- title: Try Flow permalink: /try/ section: try layout: try --- {% css 'tryFlow.css' %}

**Comment by gregvanl** [comment]
Fixed in vscode-docs vnext branch
