### ISSUE TITLE
Empty brace formatting options

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode-docs#4112]
https://code.visualstudio.com/updates/v1_51#_empty-brace-formatting-option-for-javascript-and-typescript

![same](https://user-images.githubusercontent.com/23744935/98416720-e469b380-207f-11eb-9bc4-d220fa8a704c.png)

The first option should look like [this](https://github.com/microsoft/vscode-docs/blob/master/release-notes/v1_51.md#empty-brace-formatting-option-for-javascript-and-typescript)

```ts
class Foo {
    doFoo() { }
}
```

But on the website the options look the same.

**Comment by gregvanl** [comment]
Hi @SimonSiefke Thanks for reporting this. This looks to be only on the website.

The space is preserved on the in-product release notes:

![image](https://user-images.githubusercontent.com/12818376/98417786-6f25c080-2036-11eb-81e8-fe91b9fe1dd4.png)

**Comment by gregvanl** [comment]
Before we render code blocks, we run the prettier formatter over JavaScript/TypeScript/JSON code blocks. Prettier removes the unnecessary extra spaces.
For this special case, where we want to expressly show the before code with extra spaces, I'll use another language id, which won't cause the prettier formatting to kick in.
