### ISSUE TITLE
v1.51 Release Notes: Incorrect setting

### ISSUE THREAD

**Issue by sventec** [microsoft/vscode-docs#4113]
In the v1.51 "October 2020" Release Notes, an incorrect setting is mentioned as being used for the Suggest box.

In the [Status bar for suggestions](https://code.visualstudio.com/updates/v1_51#_status-bar-for-suggestions) section, the `editor.suggestStatusBar.enable` is stated as being used to enable the Status Bar.

However, on my vscode (Win10, v1.51.0) the setting is actually `editor.suggest.showStatusBar`.

**Comment by ornellaalt** [comment]
Thanks! This has been fixed.
