### ISSUE TITLE
tsc-watch when debuggingtypescript

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode-docs#4114]
I can find any documentation about use tsc-watch when debug typescript win VScode.
Is it possible? 
If yes, should be interesting it be described in
  https://code.visualstudio.com/docs/typescript/typescript-debugging

**Comment by gregvanl** [comment]
Hi @alanlivio tsc-watch is the task problem matcher and described in https://code.visualstudio.com/docs/editor/tasks#_processing-task-output-with-problem-matchers.
PRs welcome if you'd like to add a mention in the TypeScript documentation.

**Comment by alanlivio** [comment]
Hi. Thank you.
When using ```tsc-watch --onSuccess "node ./dist/server.js"``` the program is started after changed.
I would like to do the same thing when debugging in vscode.

**Comment by gregvanl** [comment]
If I understand you correctly, you would like to automatically launch the debugger after a code change?

**Comment by alanlivio** [comment]
Yes @gregvanl. How can I do that?

**Comment by gregvanl** [comment]
I think you can do this with the nodemon utility. Have a look at https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited to see if that section covers your scenario.

**Comment by alanlivio** [comment]
Thanks again @gregvanl.
I was able to use it for TypeScript after install ts-node package and use .ts file in `program`.
However, I only could debug when the ts .file is on the project root and not in src/ folder.
Be precisely, this way the restart works:
```
      "program": "${workspaceFolder}/server.ts",
````
but this way don't:
```
      "program": "${workspaceFolder}/src/server.ts",
````

**Comment by gregvanl** [comment]
Hi @alanlivio I wonder if the debugger is having trouble finding the JavaScript output file? "program" should be pointing to the built .js file. That you can point to a .ts file, probably means the debugger is looking in likely locations for the .js output.
When the original server.ts isn't in the root of the project, the debugger might not know where to find the output.
Can you try setting "program" to the server.js file?

**Comment by alanlivio** [comment]
Thanks @gregvanl.
I use the same launch.json from the URL that you mentioned (https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited).
My comments bellow detail better the problem. 

```
{
  "name": "Launch via nodemon",
  "type": "node",
  "request": "launch",
  "runtimeExecutable": "nodemon",
  "program": "${workspaceFolder}/server.js"  // nodemon debug reload after edit server.js 
   // "program": "${workspaceFolder}/server.ts"  // nodemon debug reload after edit server.ts 
   // "program": "${workspaceFolder}/src/server.js" // nodemon debug do not reload after edit src/server.js
   // "program": "${workspaceFolder}/src/server.ts" // nodemon debug do not reload after edit src/server.ts
  "restart": true,
  "console": "integratedTerminal",
  "internalConsoleOptions": "neverOpen"
}
```
I also tried the launch.json option:
   "runtimeArgs": ["--watch", "./src/"],
But the also nodemon debug reload after change do not work.
