### ISSUE TITLE
Parameter hints only rarely working

### ISSUE THREAD

**Issue by carlschmidt26** [microsoft/vscode-docs#4120]
Hello,

I have trouble using the parameter hint when working with the Python extensions. 
I am rather new to VS Code, but so far I figured out that `CTRL + SHIFT + SPACE` should display the parameter hints.
Don't get me wrong, the shortcut works, however only in 5-10% (maybe less) of the cases, which makes VS Code rather unpleasant to use for me at the moment.

Does it make a difference where the cursor is located when pressing `CTRL + SHIFT + SPACE` (in front of/in between/after the parentheses of the method)?

The general suggestions `CTRL + SPACE` however work like a charm.

Any help is really much appreciated!

**Comment by gregvanl** [comment]
Hi @carlschmidt26 It does matter where you have the cursor. The cursor should be between the parentheses to get the most appropriate parameter help. With the cursor before or after the parentheses, you will either get no parameter hint or hints for the enclosing method.
