### ISSUE TITLE
Emmet includeLanguages explanation lacks clarity

### ISSUE THREAD

**Issue by robole** [microsoft/vscode-docs#4128]
For the section [Emmet abbreviations in other file types](https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types). It is not clear what the association is between the 2 language IDs.

```
"emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue-html": "html",
    "razor": "html",
    "plaintext": "pug"
}
```

What does the value on the right-hand side represent? 

I assume that all the associations above are adding Emmet HTML support to the languages listed as keys (left-hand side). Is this correct? Maybe, it would be easier to understand if you had `html` as the (right-hand side) value?

The `vue-html` language ID is provided by the Vetur extension. The Vetur extension takes care of adding Emmet support to the html template section of Vue files, adding the setting as per your example is not necessary. It's misleading to have this in the example. I would remove this part of the example and add a note about adding Emmet support for Vue using Vetur.

Also, 'pug'  is not a language ID, it is`jade` according to your docs. So this appears to be a mistake in the example. See [known language IDs](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers).

**Comment by gregvanl** [comment]
Hi @robole Thanks for your suggestions. I've got a pending commit to clarify that section.  
Fair point that vue-html is a poor example since Emmet is already supported by the popular Vetur extension.
I've added `pug` to the valid list of language identifiers in an earlier commit.
