### ISSUE TITLE
Missing language IDs

### ISSUE THREAD

**Issue by robole** [microsoft/vscode-docs#4129]
In the section ['Known language identifiers'](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers), there appears to quite a few missing language IDs. If you run the command **Change Language Mode**, you will see a longer list.

I would suggest adding the file types associated with a language ID to the table. It is hard to tell which file types are covered by a language in some cases.

What I noticed that is not referenced in this section but is elsewhere in the docs:
- stylus (not listed)
- slim (not listed)
- haml (not listed)
- vue (not listed)
- vue-html (this is added by Vetur)
- jsx (presumably is part of `javascriptreact` language ID)
- sass (doesn't appear to be a separate language ID, it is presumably covered under scss. Is this a doc mistake?)

**Comment by gregvanl** [comment]
Hi @robole Thanks for pointing these out. Most of these are provided by extensions and aren't language identifiers supported directly by VS Code, but good to list them so that extension authors use the recommended language identifiers.
