### ISSUE TITLE
Language ID inheritance not explained

### ISSUE THREAD

**Issue by robole** [microsoft/vscode-docs#4132]
In the section [Language Identifiers](https://code.visualstudio.com/docs/languages/identifiers), there is no mention of inheriting from other language IDs.

In the section [How to expand Emmet abbreviations](https://code.visualstudio.com/docs/editor/emmet#_how-to-expand-emmet-abbreviations-and-snippets), it lists the file types where Emmet is available. It says "as well as any language that inherits from any of the above like handlebars and PHP". It would be worthwhile explaining this concept in the Language Identifier section, and linking the topics.

![Emmet](https://user-images.githubusercontent.com/12818376/99025757-6c3b3c00-251e-11eb-9da8-add3aeefb27a.png)

**Comment by gregvanl** [comment]
The inheritance mentioned above is only for Emmet mapping and isn't a general VS Code language feature. 
You can see that the Emmet implementation explicitly maps only two language identifiers in getMappingForIncludedLanguages in https://github.com/microsoft/vscode/blob/master/extensions/emmet/src/util.ts 

```ts
export function getMappingForIncludedLanguages(): any {
	// Explicitly map languages that have built-in grammar in VS Code to their parent language
	// to get emmet completion support
	// For other languages, users will have to use `emmet.includeLanguages` or
	// language specific extensions can provide emmet completion support
	const MAPPED_MODES: Object = {
		'handlebars': 'html',
		'php': 'html'
	};

```
