### ISSUE TITLE
Using docker.host for remote docker devcontainer seems incorrect

### ISSUE THREAD

**Issue by ilmagico** [microsoft/vscode-docs#4139]
See https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host

This section says to set `"docker.host":"ssh://your-remote-user@your-remote-machine-fqdn-or-ip-here"` in `settings.json`, but that settings doesn't seem to exist anymore (using vscode 1.51.1 under linux). When setting it, nothing changes, and the editor even hints "Unknown Configuration Setting" when editing `settings.json`.

What worked for me instead was to change `"remote.containers.dockerPath"` to a command that connects to the remote host, using e.g. `-H ssh://remote-user@remote-host`.

Either way, the suggested way doesn't seem to work on linux and should be corrected.

**Comment by gregvanl** [comment]
Hi @ilmagico Do you have the Docker extension (ms-azuretools.vscode-docker) installed? I think the `docker.host` setting is provided by the Docker extension.
It looks like the documentation should call that out explicitly.

**Comment by ilmagico** [comment]
Hi @gregvanl ! No I don't, because I don't need it at the moment. If it's true that `docker.host` is a setting of the Docker extension, then even more the documentation is wrong and should be corrected, because it's talking about the "Remote - Containers" extension, which also uses docker but is a completely separate extension.

**Comment by gregvanl** [comment]
I've updated the documentation to mention this property comes from the [Docker extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker). In the future, this setting may move into the Remote - Containers extension.
Thanks for pointing out this doc gap.

**Comment by ilmagico** [comment]
@gregvanl  Are you sure changing that setting in a completely unrelated extension will actually achieve what is documented? I haven't tried, but my solution was completely different.
