### ISSUE TITLE
Version Control: Some screenshots show outdated UI

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#414]
Refs: https://code.visualstudio.com/docs/editor/versioncontrol

The ones showing the entire workbench should probably be updated since we added the extensions viewlet for example.

**Comment by gregvanl** [comment]
Cheating a bit here now that view icons are configurable. Having the Extension view icon visible isn't crucial for the topic flow so closing.

**Comment by gregvanl** [comment]
Closing as the screen shots don't affect the document flow and we now actually allow users to tune the Activity Bar and remove view icons.
The version control topic will also likely need a full refresh once we switch the new SCM provider implementation.
