### ISSUE TITLE
Inconsistent folder name usage: '.devcontainer' and 'devcontainer'

### ISSUE THREAD

**Issue by marckassay** [microsoft/vscode-docs#4141]
In vscode docs, it references the folder containing `.devcontainer.json` with the name of, `.devcontainer` and `devcontainer`. Perhaps either folder is valid, however docs explicitly state: 

> The dev container configuration is either located under `.devcontainer/devcontainer.json` or stored as a` .devcontainer.json` file (note the dot-prefix) in the root of your project. -[src](https://code.visualstudio.com/docs/remote/create-dev-container#_create-a-devcontainerjson-file)

The instance I found (there may be more) that invalidates this, is here (notice there isn't a dot-prefix on the folder name):

> ... and the folder containing `./devcontainer/devcontainer.json` ... -[src](https://code.visualstudio.com/docs/remote/containers-advanced#_changing-the-default-source-code-mount)

**Comment by gregvanl** [comment]
Hi @marckassay Thanks for pointing this out. Using `./devcontainer/` isn't allowed and you've pointed out some typos. Fixing shortly.
