### ISSUE TITLE
Advanced Container Configuration - tilde character in volume path mapping valid? 

### ISSUE THREAD

**Issue by marckassay** [microsoft/vscode-docs#4142]
In this [section ](https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild) of Advanced Container Configuration doc, it seems from what I just experienced, a tilde character is invalid for volume path mapping inside of a container. I received the error below stating to use only absolute paths. So I just expanded tilde to home directory.

For instance:
```
    volumes:
      - unique-vol-name-here:~/.vscode-server/extensions
```
to:
```
    volumes:
      - unique-vol-name-here:/home/jovyan/.vscode-server/extensions
```

From 'ms-vscode-remote.remote-containers' exthost log:
```
ERROR: for al-container  Cannot create container for service al: inv
alid volume specification: 'jovyan_devcontainer_al-vscode-vol:~/.vscode-se
rver/extensions:rw': invalid mount config for type "volume": invalid mount path:
 '~/.vscode-server/extensions' mount path must be absolute
```

**Comment by gregvanl** [comment]
@marckassay Thanks again!
