### ISSUE TITLE
API page doesn't fit into the doc structure

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-docs#415]
- _IN THIS ARTICLE_  is funky for a generated API doc page

![screen shot 2016-07-04 at 15 03 33](https://cloud.githubusercontent.com/assets/1794099/16561266/87419764-41f8-11e6-9f9d-9e69b5a5b1a9.png)

**Comment by gregvanl** [comment]
Users won't know that it is an auto-generated page and this way the right side section navigation has the same heading.  Closing unless you feel strongly we should add logic to the website to change the heading for this page.

**Comment by jrieken** [comment]
We should have at least the types in there. Now the doc useless unless you really know what you are looking for (<kbd>Cmd+F</kbd>). I don't think that someone can manage a task like 'Learn something about the TextDocument' or more generally read through the types that are exposed in the API. The API exposed over 500 symbols in total and we show 6

**Comment by Gama11** [comment]
FWIW, the API docs for our Haxe externs of the VSCode API have a nice search box:

http://vshaxe.github.io/vscode-extern/

Something like that would be very helpful to have in the official docs as well.

**Comment by gregvanl** [comment]
Closing as https://github.com/microsoft/vscode-docs/issues/416 calls out showing types in the TOC.
