### ISSUE TITLE
VSCode scripts path wrong in extension-anatomy

### ISSUE THREAD

**Issue by ced-mos** [microsoft/vscode-docs#4151]
In the documentation file for the extension anatomy ` vscode-docs/api/get-started/extension-anatomy.md` the path `./node_modules/vscode/bin/install` is wrong, respectively, it does not exist in my folder when going through the helloWorld extension example.

If this part is still important could you please update the path or otherwise remove it.

Used version:
- VS Code: 1.51.1
- npm: 7.0.14
- yo: 3.1.1

**Comment by gregvanl** [comment]
@ced-mos Thanks for pointing this out. Something odd is going on here. I see the install script in some cases when running `yo code` but not other. I'll investigate.

**Comment by gregvanl** [comment]
https://github.com/microsoft/vscode-docs/issues/3678 was also referencing this issue

**Comment by gregvanl** [comment]
Hi @ced-mos While investigating, I had different versions of the Yeoman code-generator. Once I got on the latest version, I saw that you were correct.

**Comment by ced-mos** [comment]
Perfect. Thanks for updating.
