### ISSUE TITLE
Debug error on windows OS

### ISSUE THREAD

**Issue by stefanwan** [microsoft/vscode-docs#4156]
I'm using VS code in my PC running window 10. When I debug my project, an error occured which shows `The prelaunchTask 'C/C++: g++.exe build active file' terminated with exit code -1`.
I did exactly as the docs says. The only difference is when I bulid my project, it creates `tasks.json` file where the task type is `cppbuild`  rather than `shell`. I have no idea what happened

**Comment by Krotli** [comment]
you should start debug on .cpp file . NOT let your editor is on json file  or other file because the tasks.json command args has ${file} which means telling g++ work on your opening file.

**Comment by TylerMSFT** [comment]
Hi @stefanwan ,
Which doc are you referring to? The last doc I worked on for the VS Code C++ code extension, calls out that you need to be on the .cpp file first. But this may be a different doc you are referring to.

**Comment by stefanwan** [comment]
[Of course, I was on the .cpp file. I did debug my .cpp file not the json file or other files. But the problem is still there. And when I change the task type from `cppbuild` to `shell` manually, the error is gone. 
By the way, I refered to  'GCC on Windows‘ doc on VS Code official website edited on July 20, 2020.

**Comment by stefanwan** [comment]
Hello @TylerMSFT，
sorry to bother you， but not sure  if you have read my comment. Do you have any idea how can I solve this problem？

**Comment by TylerMSFT** [comment]
Hi @stefanwan,

Unfortunately, we don't have the bandwidth to do support here. I recommend visiting the [vscode-cpptools github repo ](https://github.com/microsoft/vscode-cpptools/issues) and opening an issue. Tag it with **bug** and **question** and let's see what the development team has to say.

**Comment by gregvanl** [comment]
Hi @stefanwan It looks like the C/C++ extension (version 1.1.3) has changed slightly since the tutorial was written and now the generated tasks.json task type is 'cppbuild' by default.

Here's is what I see when I follow the tutorial for tasks.json.

```json
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: \"C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe\""
		}
	]
```

That tasks.json works for me but I do see the error dialog you describe if I don't have the helloworld.cpp as the active file. 

Below you can see that launch.json is the active file and the error dialog appears.

![image](https://user-images.githubusercontent.com/12818376/101435490-4b69ca80-38c1-11eb-8c23-f5cb778990aa.png)

Could you share your tasks.json and launch.json files and I can see if there is something else going on.

**Comment by stefanwan** [comment]
Hi @gregvanl 
Thank you for your patient reply. I forgot to say that I have two cpp files to build. That means that I have `helloworld.cpp` and `myfunc.cpp`, the `helloworld.cpp` uses the function of `myfunc.cpp` to print "hello world".
Here's my tasks.json.
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
			"args": [
				"-g",
				"${file}",
				"${fileDirname}\\myfunc.cpp",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: \"C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe\""
		}
	]
}
```
Here's my launch.json.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/42583038/101465826-63058980-397b-11eb-89f3-0620d31cec72.png)

**Comment by gregvanl** [comment]
Hi @stefanwan Looks like you have discovered a bug in the default tasks.json. I see the same error if I have the task type as "cppbuild" and it does work if I set the task type back to "shell".
One simplification to your tasks.json for when you have multiple .cpp files is to use ${workspaceFolder}\\*.cpp but what you have listing both the active file and myfunc.cpp will work but is fragile if helloworld.cpp isn't the active file.
Here's my working tasks.json:
```json
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
			"args": [
				"-g",
				"${workspaceFolder}\\*.cpp",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: \"C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe\""
		}
	]
```
With the tasks.json above, you can press F5 anytime to launch the debugger and don't need to worry about the active file.
I'll bring up your issue to an engineer on the C++ extension team.
Thank you for being persistent!

**Comment by gregvanl** [comment]
@jureid Here's the issue related to the new tasks.json `cppbuild` task type. You mentioned it might now be fixed.
