### ISSUE TITLE
API page doesn't list the important bits

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-docs#416]
The [API](https://code.visualstudio.com/docs/extensionAPI/vscode-api)-page list the namespaces only but doesn't list any of the actual types in the page TOC. That make it hard to read/discover things.

**Comment by jrieken** [comment]
@gregvanl @seanmcbreen ping - this is a *real* pain point and people are not finding important bits of the API (the same is true for the api commands) and we should tackle this

**Comment by arthurbdiniz** [comment]
@jrieken and @jrieken can i work on this issue?

**Comment by Gama11** [comment]
FWIW, the API docs for the Haxe externs of the VSCode API are a lot more convenient in this regard IMO:

http://vshaxe.github.io/vscode-extern/

**Comment by gregvanl** [comment]
Closing as old issue and no engineering resources currently available to improve generated API documentation.
