### ISSUE TITLE
Missing context operator

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-docs#4166]
`in` operator is missing from https://code.visualstudio.com/docs/getstarted/keybindings#_conditional-operators

https://github.com/microsoft/vscode/pull/104625

**Comment by usernamehw** [comment]
Context keys definitely deserve a separate page #3960

**Comment by usernamehw** [comment]
> Available contexts#
Below are some of the available when clause contexts, which evaluate to Boolean true/false.
The list here isn't exhaustive and you can find other when clause contexts by searching and filtering in the Keyboard Shortcuts editor (Preferences: Open Keyboard Shortcuts ) or reviewing the Default Keybindings JSON file (Preferences: Open Default Keyboard Shortcuts (JSON)).

Searching for context keys by `Keybindings Editor` is not a great experience. The documentation should probably mention **Developer: Inspect Context Keys** command that shows all context keys in developer console.

**Comment by gregvanl** [comment]
Added `in` operator during refactoring of when clause contexts into it's own topic with https://github.com/microsoft/vscode-docs/commit/f9159a7911016080ac12a3c5e59730cc3e042f4e
Also added section on **Developer: Inspect Context Keys**
New topic at https://code.visualstudio.com/api/references/when-clause-contexts
