### ISSUE TITLE
Add F# to docs and supported languages

### ISSUE THREAD

**Issue by jkone27** [microsoft/vscode-docs#4175]
currently F# is mostly supported by ionide, but being a .netcore and NET5 official language, would be nice it was mentioned and supported in vscode and have a microsoft extension as well as the opensource efforts, or back those efforts and integrate them? 

docs are here for using ionide:
https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode

but not here under the languages section: 
https://code.visualstudio.com/docs

**Comment by gregvanl** [comment]
Hi @jkone27 Thank you for opening an issue and your support of F#. We do include references to F# in our various programming language topics, such as mentioning the F# language identifier (`fsharp`) and folding regions, and in the .NET Core topic (https://code.visualstudio.com/docs/languages/dotnet#_create-an-f-hello-world-app), which also has a link to the docs.microsoft.com topic you mention above.
I'll add F# to the language overview list and link to the .NET Core section in a pending commit.
It is really up to the Microsoft .NET Core team as to whether they want to create their own VS Code extension or leave support to the F# community
