### ISSUE TITLE
What does loose files mean in this article?

### ISSUE THREAD

**Issue by krave1986** [microsoft/vscode-docs#4179]
Hi, what does "loose files" mean here?
https://code.visualstudio.com/docs/getstarted/userinterface#_can-i-hide-the-open-editors-section-in-the-explorer

**Comment by gregvanl** [comment]
Hi @krave1986 "Loose" files means any files that are opened or created when VS Code does not have an open folder. For example, you can open VS Code from a start menu or close an open folder, but still open individual files directly.

In the image below, I've closed the vscode-docs folder but opened the README directly with File > Open File:

![image](https://user-images.githubusercontent.com/12818376/102020114-e8968a00-3d2b-11eb-82b0-7e466118ff01.png)

I'll see if I can make the text clearer.

**Comment by krave1986** [comment]
@gregvanl Thank you for your clarification. It makes sense for me now. 👍

**Comment by gregvanl** [comment]
@krave1986 I tried to make the justification for displaying loose files clearer.

**Comment by krave1986** [comment]
@gregvanl Thank you! In my opnion, loose files refer to the files not belong to the opened folder(s) but being opened in the editor. So we can only show them in 'open editors' pane in order to further navigation.
