### ISSUE TITLE
The latest version of the program is unstable

### ISSUE THREAD

**Issue by mabidenengma** [microsoft/vscode-docs#4184]
1.52 always crash...    why?

**Comment by gregvanl** [comment]
Hi @mabidenengma This repository is for VS Code documentation content and issues and this sounds like a product issue.
A first step for diagnosing crashing issues is to disable extensions `code --disable-extensions` and see if you still see crashes. There is also the new "extension bisect" feature to help narrow down problematic extensions https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect.
You might also try uninstalling and reinstalling VS Code, in case you have a corrupt install.
If you still are having crashing problems you can create an issue in the VS Code product repo https://github.com/microsoft/vscode. There you will also find information on creating crash reports https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
