### ISSUE TITLE
Add documentation for subprocess debugging

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#4185]
#### Issue opened by @jonfen in the Python extension repo:

Is there any debugging subProcess documentation anywhere? I didn't see it on https://code.visualstudio.com/docs/python/debugging

![image](https://user-images.githubusercontent.com/56961/102408226-8a2b0f00-3faa-11eb-8015-39890f189575.png)
![image](https://user-images.githubusercontent.com/56961/102408254-931be080-3faa-11eb-8af5-7bf795f91b57.png)

I didn't know if this was a required _launch.json_ configuration [anymore], through my own testing I realized the behavior was the same either way.

```json
    "configurations": [
        {
            ...
            "subProcess": true
        }
    ]
`````

**Comment by JoshuaPartlow** [comment]
Addressed with above PR.
