### ISSUE TITLE
Readme link not working

### ISSUE THREAD

**Issue by Aryankpoor** [microsoft/vscode-docs#4188]
The link at the end of the readme.md of this repo does not work. 

**To be more precise:**
This is the line at the end of the readme and the word 'here' is the link. But it is a broken link.
reference line: 

> Steps for how to publish documentation changes can be found here in the (private) repository of the VS Code website.

**Comment by gregvanl** [comment]
Hi @Aryankpoor Thanks for taking the time to enter an issue. The link is to a private repo, which you don't have access to. This section is for the VS Code team so that they can quickly jump to how to publish a documentation update.
