### ISSUE TITLE
Tabs: mention that editor actions moved into the tab context menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#419]
Refs: https://code.visualstudio.com/docs/editor/tabs

When tabs are disabled, we show some editor actions in the right hand side (e.g. for a diff editor the actions to navigate to next/previous diff). 

With tabs enabled, we no longer show these actions. They move into the context menu on a tab. While this is not the final design, we should probably still mention this in the docs page for now.

**Comment by gregvanl** [comment]
Closing since the editor action buttons are coming back in the July release.
