### ISSUE TITLE
My intellisense is not able to find some functions although it builds fine

### ISSUE THREAD

**Issue by Snake-27** [microsoft/vscode-docs#4199]
![2020-12-26_22-25-44](https://user-images.githubusercontent.com/72086275/103155915-b6743600-47c9-11eb-95e2-4d964a294e67.png)
![2020-12-26_22-28-12](https://user-images.githubusercontent.com/72086275/103155916-b83df980-47c9-11eb-8b3f-ff6b5b2c6496.png)

**Comment by gregvanl** [comment]
Hi @Snake-27 This looks like an issue with the C++ extension rather than documentation or a tutorial. 
You can open an issue in the https://github.com/microsoft/vscode-cpptools repo
