### ISSUE TITLE
vscode.extensions.getConfigurationMemento() does not exist

### ISSUE THREAD

**Issue by willbar** [Microsoft/vscode-docs#42]
The contribution points documentation refers to vscode.extensions.getConfigurationMemento() which doesn't appear to exist. The Go extension instead uses vscode.workspace.getConfiguration('go'), is that the correct alternative?

**Comment by gregvanl** [comment]
You are correct.  I've updated the topic and it will be published shortly.  Thank you for calling out the issue.
