### ISSUE TITLE
Requirement for Windows Server?

### ISSUE THREAD

**Issue by T0biii** [microsoft/vscode-docs#4202]
In the Requirements stands that Visual Studio Code was tested against Windows 7-10, how about Windows Server 2016-2019?
https://github.com/microsoft/vscode-docs/blob/master/docs/supporting/requirements.md
The Background why I ask is our Software manufacturer only want to release VS Code for Servers if it is tested againts Windows Servers. So we are currently limited to installing VSCode on Windows 7-10

**Comment by gregvanl** [comment]
Hi @T0biii We don't know why VS Code wouldn't run on Windows Servers but we haven't explicitly tested on those versions of the Windows platform.
WIndows platforms need to have at least Microsoft .NET Framework 4.5.2 per https://code.visualstudio.com/docs/supporting/requirements#_additional-windows-requirements.
