### ISSUE TITLE
WSL2 and VSCode Python Virtual Environments are not popping up automatically from the plugin.

### ISSUE THREAD

**Issue by ProcrastinatingEntrepreneur** [microsoft/vscode-docs#4210]
Every time I create a virtualenv using either `virtualenv .venv` or `python3 -m venv .venv`, It doesn't pop up automatically asking if I want to switch to that interpreter. I got it working on the Windows side finally, but cannot get the WSL2 side to cooperate. I'm having to manually go into the interpreter and click find to find the interpreter in the .venv folder in my project.

My settings.json is as follows:
```
{
    "python.pythonPath": ".venv/bin/python",
    "python.venvPath": "${workspaceFolder}/.venv/",
    "python.terminal.activateEnvironment": true
}
```

**Comment by JoshuaPartlow** [comment]
Hi @ProcrastinatingEntrepreneur - Thanks for opening an issue. Given this problem isn't related to the documentation, could you instead open one on the Python extension at https://github.com/microsoft/vscode-python/issues There is information requested as part of opening an issue there that helps us figure out issues. If you could also @ mention me, I'll watch in case there is a documentation aspect that comes out of it.
