### ISSUE TITLE
Update JDK requirements from 8 to 11

### ISSUE THREAD

**Issue by 0dinD** [microsoft/vscode-docs#4222]
The Java extension needs at least JDK11 to run since a few months back, but some pages under the Java docs still mention JDK8 as the minimum requirement. I've found the following pages, but there may be more:
- https://code.visualstudio.com/docs/java/java-testing
- https://code.visualstudio.com/docs/java/java-spring-boot

It might also be a good idea to provide a link to https://code.visualstudio.com/docs/java/java-tutorial#_supported-java-versions to avoid confusion between the version requirement to run the extension vs your project.

**Comment by yaojinyang** [comment]
Thanks @0dinD for reporting the issue. PR has been filed to update version required from 1.8 to 11 on both docs. Reg., adding a link to the version section, I will take a closer look and decide the best approach to move forward. Feel free to let us know if you have other comments or suggestions.

**Comment by 0dinD** [comment]
I was just referring to the heated discussion surrounding the move to JDK11 for the Java extension, where many users mistakenly though that the requirement mean that they couldn't use older versions of Java for their projects. Not sure if it's necessary to add that information here, since the reader will hopefully already be aware of what the JDK11 requirement means by reading other documentation pages. But a small note for extra clarity on the matter probably won't hurt? I'll let you decide on that.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/4ede265c8fe7b871989509682595d9a884c8dae5
