### ISSUE TITLE
Broken Atom feed <updated> must be an RFC-3339 date-time

### ISSUE THREAD

**Issue by anaggh** [microsoft/vscode-docs#4225]
This bug is preventing RSS readers to parse the feed

URL: https://code.visualstudio.com/feed.xml

Validate Feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcode.visualstudio.com%2Ffeed.xml

Valid Example: https://blog.getbootstrap.com/feed.xml

**Comment by gregvanl** [comment]
Hi @anaggh, I've tried a couple of popular RSS feed readers on Windows 10 (Newsflow, newsXpresso) and they seem to read the VS Code RSS feed correctly. I also haven't heard of other users having trouble with the existing feed. The current format of the RSS feed has been available for several years.
Is there a particular RSS feed reader that doesn't work for you? And what platform OS are you working on?

**Comment by anaggh** [comment]
Hi Greg, thanks for looking into it!

The `<updated>` field is invalid.

I am using a custom RSS client which uses laminas-feed library (https://docs.laminas.dev/laminas-feed/) Whenever, it tries to parse vscode feed, it throws exception (Invalid date). 

I downloaded some Desktop RSS clients on Fedora Linux to see how these readers are parsing the invalid date. This is what I noticed.

Behavior when client comes across invalid dates
```
liferea.x86_64 : <updated> fallback to blank : ""
quiterss.x86_64 : <updated> fallback to current date
feedreader.x86_64 : <updated> fallback to current date
gnome-feeds.noarch : <updated> fallback to current date
newsboat.x86_64 : <updated> fallback to current date
```

Most of them fallback to current date. I modified the logic in my client as well to fallback to current date.

**Comment by gregvanl** [comment]
Hi @anaggh We fixed the W3C validation issues. Can you test the RSS feed with the laminas-feed reader and let us know if you still see issues? Thanks!

**Comment by anaggh** [comment]
Can confirm. Fixed! 🍺

**Comment by gregvanl** [comment]
@rzhao271 Looks like working for this reader.

**Comment by gregvanl** [comment]
@rzhao271 Looks like working for this reader.
