### ISSUE TITLE
[question] Definitive documentation of glob grammar used?

### ISSUE THREAD

**Issue by MatrixScenary** [microsoft/vscode-docs#4227]
I'd like to use a more complex glob pattern under my search.exclude object. I can't find however the full scope of the grammar documented or referenced. (It would involve an optional range of characters, like so in regex: '[0-9]+'.)

**Comment by gregvanl** [comment]
Hi @MatrixScenary, have a look at https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options and we also link to https://en.wikipedia.org/wiki/Glob_(programming).
