### ISSUE TITLE
Keybindings: How to remove a key binding from an action

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#423]
Refs: https://code.visualstudio.com/docs/customization/keybindings

I think @alexandrudima added an easier way for unbinding a key. He can chime in to explain how to unbind a key easier.

**Comment by alexandrudima** [comment]
It is in that page: https://code.visualstudio.com/docs/customization/keybindings#_removing-a-specific-key-binding-rule

Maybe we can remove the FAQ entry

**Comment by gregvanl** [comment]
Removed FAQ entry with https://github.com/Microsoft/vscode-docs/commit/1ba2e423d7431c6838b59166ba246402c6195697
