### ISSUE TITLE
New Contributor questions

### ISSUE THREAD

**Issue by jhomme** [microsoft/vscode-docs#4230]
Hi,
Once I fork the repository, do I need to keep my copy in sync with this one? If so, can you please point me to the right way to do this?

Thank you.

Jim

**Comment by gregvanl** [comment]
Hi @jhomme To contribute a PR to vscode-docs, you would follow the usual workflow for a public repo for which you don't have write access.  https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/working-with-forks
To keep your fork in sync with the upstream remote, you can follow https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork and https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
