### ISSUE TITLE
Kindly provide a working example of using PYTHONPATH variable in env file

### ISSUE THREAD

**Issue by AkshayRoyal** [microsoft/vscode-docs#4232]
**In the existing documentation on [using PYTHONPATH](https://code.visualstudio.com/docs/python/environments#_use-of-the-pythonpath-variable), it is not shown as to how to add the PYTHONPATH to the env file and not clear if VS code will override any global environment variables that are defined.** 
It might be clear to developers who are aware of using PYTHONPATH from somewhere else but for beginners, it is not at all clear as to how to use PYTHONPATH from the existing documentation.
**Kindly update the documentation on using PYTHONPATH**

**Comment by JoshuaPartlow** [comment]
Hi @AkshayRoyal - Thanks for your feedback. The [section prior](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file) to the one you referenced discusses .env files and talks about how they're created and used within Visual Studio Code. After looking at that section, does it make more sense or do you think something is still missing?

**Comment by AkshayRoyal** [comment]
Hi @JoshuaPartlow . Thanks for your response. The section that you mentioned does not contain examples for paths be it relative or absolute. I figured out how to create an .env file and then how to modify settings.json for modifying the PYTHONPATH.

![1](https://user-images.githubusercontent.com/10032879/104739046-458ec100-576c-11eb-8dcf-9d44e95aee8e.png)

This is my file structure. As you can see the way vs code shows the file structure is also confusing.  prod.env appears to be inside src directory but it is not the case, it is inside the workspace Folder. If you can improve that, it will be helpful too. 
Now coming back to the PYTHONPATH issue. 

my prod.env contains  `PYTHONPATH=${PYTHONPATH};.\src ( using ; as separator on Windows)`

and below are the contents of settings.json

```
{
    "python.envFile": "${workspaceFolder}/prod.env",
    "terminal.integrated.env.windows": {
        "PYTHONPATH": "${env:PYTHONPATH};${workspaceFolder}/src"
    },
    "terminal.integrated.env.linux": {
        "PYTHONPATH": "${env:PYTHONPATH}:${workspaceFolder}/src"
    }
}

```
If I use absolute path in prod.env everything works fine but if I use relative path which is the case right now. I am able to run the code in terminal but when I run the code on interactive jupyter notebook it would throw the error **"module not found"** whenever distance or Point module are imported

You can reproduce it and confirm the same. 

Another annoying part is that if .env file is updated vs code has to be restarted manually to apply the changes and to make it worse even with the correct settings.json and .env file pylance would always draw wiggly lines below the modules telling that import cannot be resolved while if we change the language server to Microsoft the imports would be resolved.

**Comment by AkshayRoyal** [comment]
Hi @JoshuaPartlow. Were you able to reproduce the issue?

**Comment by JoshuaPartlow** [comment]
Hi @AkshayRoyal - Thanks for the feedback around the docs for PYTHONPATH. Just to confirm I'm understanding the problem you're seeing, it's that when your env file uses a relative path it works fine normally, but not when running within the Python Interactive window?

@claudiaregio - do you know if that's expected or is it an issue?

**Comment by claudiaregio** [comment]
@luabud Are you able to assist with this?

**Comment by luabud** [comment]
I think there are two layers to this issue:
- There's a bug on the .env support with the Python and Jupyter extensions 
- We don't have a clear example of how to set PYTHONPATH in .env files in our docs. 

For the first one, it'd be great if you could file an issue on  https://github.com/Microsoft/vscode-python providing more details. I tried to reproduce the issue here but I couldn't - it worked for me.

For the second, I think @JoshuaPartlow and I can work on a sample where we show the contents of the .env file, as well as what it's added to settings.json.

**Comment by luabud** [comment]
@JoshuaPartlow thoughts on adding something around the paragraph below [in this section](pythonpath-variable), between those paragraphs?
![image](https://user-images.githubusercontent.com/45497113/122111801-032de680-cdd5-11eb-8e43-490dc9fe3708.png)


> In this example, you could create a .env file to your workspace in VS Code with the following content:
> ```
> PYTHONPATH=src
> ```
> 
> Then make sure your "python.envFile" is set to the the .env file path in the settings.json file. If it's in the workspace root, it would be:
> 
> ```
> "${workspaceFolder}/.env"
> ```

**Comment by JoshuaPartlow** [comment]
Example added in above PR.
