### ISSUE TITLE
Debug containerized C++ apps

### ISSUE THREAD

**Issue by emiliogq** [microsoft/vscode-docs#4238]
As the documentation says https://code.visualstudio.com/docs/containers/debug-common only Node.js, Python and .Net apps are supported.

What I would like to be able is to debug C++ executables using the visual code GUI.

Now what I'm doing is creating a container within the code Terminal and try to debug using the gdb command line.

Thanks in advance,

**Comment by emiliogq** [comment]
Hi @weinand ,

Thanks for rerouting me to the right documentation, I also checked the second link and tried in Visual Code.

However, I don't see the possibility to use the CMake program inside a customized docker (not the one provided by the cpp example). Is it already possible?

I found this launch.json file [here](https://github.com/microsoft/vscode-cmake-tools/blob/master/docs/debug-launch.md#debug-using-a-launchjson-file)
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            // Resolved by CMake Tools:
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [
                {
                    // add the directory where our target was built to the PATHs
                    // it gets resolved by CMake Tools:
                    "name": "PATH",
                    "value": "$PATH:${command:cmake.getLaunchTargetDirectory}"
                },
                {
                    "name": "OTHER_VALUE",
                    "value": "Something something"
                }
            ],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

But it did not work

**Comment by ucheNkadiCode** [comment]
Hey @emiliogq, I am the PM for the Docker extension for VS Code. After discussing this topic with our team, we do not have plans in the near future of providing scaffolding/debugging support for C++ executables. Thank you for your feedback!
