### ISSUE TITLE
Troubleshoot Terminal: Improve compatibility mode section

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#4241]
https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

This error message isn't accurate anymore: https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_the-terminal-exited-with-code-1-on-windows-10

Let's call it "Make sure compatibility mode is turned off", a screenshot would also be helpful.

**Comment by gregvanl** [comment]
The instructions could also be clearer for getting to the properties. In the text "right-clicking the executable" it isn't clear which executable. Is it the VS Code executable or the shell executable? 
There also isn't any help for finding the executable. Might be good to point out common locations for the popular shell executables.

**Comment by Tyriar** [comment]
This is the for VS Code executable:

![image](https://user-images.githubusercontent.com/2193314/105181557-ce955780-5ae0-11eb-80fa-e81110915889.png)

![image](https://user-images.githubusercontent.com/2193314/105181610-e076fa80-5ae0-11eb-9c03-7845ab781d2a.png)

![image](https://user-images.githubusercontent.com/2193314/105181653-ee2c8000-5ae0-11eb-8951-9df7d866ee69.png)
