### ISSUE TITLE
A new problem again

### ISSUE THREAD

**Issue by Bedwars-coder** [microsoft/vscode-docs#4243]
I use VS Code for my Python development. 
Whenever I start programming, I get a pop up saying "The Python server tool crashed 3 times and the server won't restart" I don't get suggestions too(intellisence)
Pls help. I am on windows 7.

**Comment by gregvanl** [comment]
Hi @Bedwars-coder You might want to have a look at issues in the Python extension repository at https://github.com/microsoft/vscode-python/issues

I searched for your error message and see several similar issues https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+%22The+Python+server+tool+crashed%22+is%3Aclosed

For example, issue https://github.com/microsoft/vscode-python/issues/13679 says that reinstalling the extension fixed the problem.

**Comment by JoshuaPartlow** [comment]
Hi @Bedwars-coder - If you're still having a problem, please open an issue on the [extension repo](https://github.com/Microsoft/vscode-python). They'll be better able to help you there.
