### ISSUE TITLE
How to bring up the signature and docstring of a class in Jupyter notebooks

### ISSUE THREAD

**Issue by MAYasin** [microsoft/vscode-docs#4246]
How to bring up the signature and docstring of a class in Jupyter notebooks ?
I tried using pylance and the intellisense is not too informative as the official Jupyternotebook using Shift + Tab

**Comment by JoshuaPartlow** [comment]
@claudiaregio - are you able to comment on this question?

**Comment by claudiaregio** [comment]
@MAYasin Are you using VS Code stable or VS Code Insiders?

**Comment by MAYasin** [comment]
> @MAYasin Are you using VS Code stable or VS Code Insiders?

I am using vs code stable version.

**Comment by claudiaregio** [comment]
@MAYasin have you updated to the latest version of VS Code and Python extension?

**Comment by MAYasin** [comment]
> @MAYasin have you updated to the latest version of VS Code and Python extension?

Yes

**Comment by claudiaregio** [comment]
And hovering over the function with your mouse does not bring anything up?

**Comment by MAYasin** [comment]
> And hovering over the function with your mouse does not bring anything up?

I rechecked just now, it does not

**Comment by JoshuaPartlow** [comment]
Closing this issue given time since last activity. If this is still a problem though, could you please reopen on the [VS Code Python extension](https://github.com/microsoft/vscode-python) repo
