### ISSUE TITLE
Update docs to clarify "python" vs "pythonArgs" arguments in launch.json  

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#4248]
This is a follow up item for https://github.com/microsoft/vscode-docs/issues/4161. 

In this [section of our docs ](https://code.visualstudio.com/docs/python/debugging#_python) we say that if users wish to pass arguments to the Python interpreter they can use an array of values for the "python" property. We changed that so that python only accepts a string, and we added a new setting called "pythonArgs" to pass arguments to the interpreter. 

More details here:
https://github.com/microsoft/vscode-python/issues/12462
https://github.com/microsoft/vscode-python/issues/13218

**Comment by gregvanl** [comment]
@luabud Documentation PRs welcome.
