### ISSUE TITLE
Themes: Update for extension viewlet

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#425]
Refs: https://code.visualstudio.com/docs/customization/themes#_adding-themes-from-the-extension-marketplace

We should probably mention the extensions viewlet instead of referring to the extension picker in the docs here.

**Comment by gregvanl** [comment]
Updated with https://github.com/Microsoft/vscode-docs/commit/b9bc89f6cf212179d212083e4cbef87a4c63b853
