### ISSUE TITLE
How to create a folder/file from the terminal window, for visual studio code, c++, linux mint

### ISSUE THREAD

**Issue by Mirixy17** [microsoft/vscode-docs#4250]
I am very new in programming and a new linux user. I was trying to get everything ready to code in VS Code and now I am stuck at the second step from this page: https://code.visualstudio.com/docs/cpp/config-linux

![image](https://user-images.githubusercontent.com/64924145/105064125-cd324380-5a7c-11eb-96bd-fd5b65abdf6c.png)

**Comment by gregvanl** [comment]
Hi @Mirixy17 Are you having trouble creating and navigating folders on Linux or having trouble opening VS Code via the `code .` command line?
You can consult https://code.visualstudio.com/docs/setup/linux for details on setting up VS Code on Linux installations.
If you are having trouble starting VS Code from a terminal, you might try creating a new terminal, which should have the VS Code installation path set.

**Comment by Mirixy17** [comment]
Good evening, thank you very much for your fast answer! I was having trouble creating and navigating folders on Linux, but now I got it finally!
