### ISSUE TITLE
Marketplace Problem

### ISSUE THREAD

**Issue by TaimurShahikhel** [microsoft/vscode-docs#4256]
Hello, can please you help me Im having issue with the market place I cant see anything despite having a very stable connection I also tried the alternative installing of extensions but still not working. Help please!!!

**Comment by gregvanl** [comment]
Hi @TaimurShahikhel Are you running your machine behind a proxy? If so, you may find https://code.visualstudio.com/docs/setup/network#_proxy-server-support helpful in getting through the proxy to the Marketplace.

**Comment by TaimurShahikhel** [comment]
No bro Im not using a proxy

**Comment by TaimurShahikhel** [comment]
What do you mean by proxy? Do you mean am I sharing connection from some
device? Yes, I have connected my phone to laptop.

**Comment by joaomoreno** [comment]
> with the market place I cant see anything

Can you share a screenshot of what you mean by this?

**Comment by gregvanl** [comment]
Closing as no reply from the user
