### ISSUE TITLE
Extension guidelines images look bad on standard DPI

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#4266]
The editor is blurry and the workbench names are too small. I would expect at least 50% of our users are on standard DPI, don't have actual numbers though.

![image](https://user-images.githubusercontent.com/2193314/105739202-b52f4980-5eec-11eb-9f86-1d93226d39c8.png)

**Comment by misolori** [comment]
I've increased the font-size in the graphic from 16px => 20px and also linked to the image source.
