### ISSUE TITLE
404 link on "when clause contexts"

### ISSUE THREAD

**Issue by ChildishGiant** [microsoft/vscode-docs#4267]
A link here on this post (https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch) with the text `language ID` goes to https://code.visualstudio.com/docs/languages/identifiers.md which is a 404 error
![image](https://user-images.githubusercontent.com/13716824/105747653-f51c1e00-5f38-11eb-9aaf-b3060796a890.png)

**Comment by gregvanl** [comment]
@ChildishGiant Thanks for catching this!

**Comment by ChildishGiant** [comment]
Sorry for linking the wrong page, thanks for the quick fix!
