### ISSUE TITLE
Source Control - GitHub screenshot now has a "Code" button instead of a "clone or download" button

### ISSUE THREAD

**Issue by zjalexander** [microsoft/vscode-docs#4269]
The screenshot at https://code.visualstudio.com/docs/editor/versioncontrol#_cloning-a-repository is no longer up to date as the wording on the green button has changed. This is minor but could potentially be confusing for people onboarding.

**Comment by gregvanl** [comment]
This will be fixed when https://github.com/microsoft/vscode-docs/pull/4236 is merged.

**Comment by gregvanl** [comment]
Fixed
