### ISSUE TITLE
Tab trapping should mention Toggle use of tab key for setting focus

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#427]
Refs: https://code.visualstudio.com/docs/editor/accessibility

We mention that ctrl + M frees the tab, however we should mention the name of the workbench action so users know that they can also trigger it from the command pallete.

![screen shot 2016-07-04 at 15 30 27](https://cloud.githubusercontent.com/assets/1926584/16561975/45547624-41fc-11e6-8cfc-ca6e196a7751.png)

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/402fe34fe7b470c76850abf868c27b1558c6e341
