### ISSUE TITLE
Snippets page isn't filter unpublished extensions from marketplace

### ISSUE THREAD

**Issue by fedehaust** [microsoft/vscode-docs#4280]
Snippets page is getting extensions that are unpublished in the marketplace
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_install-snippets-from-the-marketplace
![image](https://user-images.githubusercontent.com/13921860/106357894-c8288c00-62e7-11eb-9eda-83f68e6275a1.png)
![image](https://user-images.githubusercontent.com/13921860/106357914-dd051f80-62e7-11eb-866e-efe2cc773c81.png)
(Luckily that's unpublished)

**Comment by gregvanl** [comment]
Oh, that's funny. Will fix shortly. Thanks for calling this out.

**Comment by gregvanl** [comment]
Replace Marketplace query with in-product extension category search instructions.
Thanks again for alerting us!

**Comment by gregvanl** [comment]
Turns out No Code is showing up in a lot of Marketplace queries in our docs.

**Comment by fedehaust** [comment]
Well... Luckily it's really easy to fix... I tried to find where is the request to make a pull request, but I didn't find it.

**Comment by gregvanl** [comment]
The change to the query would need to be made in our private website infrastructure repository. But thanks for taking a look.
