### ISSUE TITLE
Issue: Python docs for .env files is not clear on what supports .env files.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-docs#4289]
.env files seem to only work for F5 scenarios. I cannot get them to work for running in a terminal.

This section here in the docs:
https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file

I cannot tell what .env files apply to.

**Comment by JoshuaPartlow** [comment]
Thanks for opening an issue @rchiodo. @luabud - Do you know what the supported scenarios for .env files are?

**Comment by luabud** [comment]
I believe it works for IntelliSense (@jakebailey - it works for Pylance, right?). But I don't think it works for testing, a workaround is always to create a `launch.json` file with `request`: `test` and add the path to the .env file to get it to be picked up.

**Comment by jakebailey** [comment]
Yes, this now works for Pylance; we get the same environment variables at the same time as the selected interpreter.

**Comment by JoshuaPartlow** [comment]
Trying to get something added to the docs for this. Is it accurate to add a sentence that says "Environment variable definitions files can be used for scenarios such as debugging and tool execution, but are not applied to the terminal." Anything else you'd want added on to that?

**Comment by luabud** [comment]
I think so! Perhaps we can add "... and tool execution, such as linters, formatters, IntelliSense and testing tools, but are not applied to the terminal" ?

**Comment by JoshuaPartlow** [comment]
Thanks @luabud - Updated the text to "Environment variable definitions files can be used for scenarios such as debugging and tool execution (such as linters, formatters, IntelliSense, and testing tools), but are not applied to the terminal."

**Comment by JoshuaPartlow** [comment]
https://github.com/microsoft/vscode-docs/pull/4417
