### ISSUE TITLE
RSS feed is not valid

### ISSUE THREAD

**Issue by chrbayer** [microsoft/vscode-docs#4290]
- VSCode Version: /
- OS Version: /

Steps to Reproduce:

1. Validate feed https://code.visualstudio.com/feed.xml

Does this issue occur when all extensions are disabled?: Yes/No

The feed https://code.visualstudio.com/feed.xml doesn't seem to be valid and can't be added to nextcloud news app because of this.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcode.visualstudio.com%2Ffeed.xml

**Comment by gregvanl** [comment]
https://github.com/microsoft/vscode-docs/issues/4225 also has more information

**Comment by gregvanl** [comment]
Hi @chrbayer This should be fixed now. Can you test the RSS feed with your NextCloud reader and let us know if you still see issues. Thanks for pointing this out!
