### ISSUE TITLE
Tutorial does not work: Get started with CMake Tools on Linux

### ISSUE THREAD

**Issue by ProfDan** [microsoft/vscode-docs#4302]
I am following the turorial: Get started with CMake Tools on Linux and I have found that the QuickStart section does not prompt me to enter in a project name. The only option I get is selecting a build architecture such as X64 and it's corresponding GCC version. Also I never see an option for library or executable as it is displayed in the tutorial.

**Comment by gregvanl** [comment]
Hi @ProfDan Can you paste a screenshot of the UI that you are seeing?

Are you seeing the Select Kit drop down?

![image](https://user-images.githubusercontent.com/12818376/107088278-91ec8000-67b1-11eb-85f3-acdc489ecf6f.png)

**Comment by ProfDan** [comment]
Yes but I have an answer. I found it using the debugging skills of a five year old. ie I clicked on stuff till it worked. I have no idea how or why this worked. I clicked on the settings gear icon that showed up next to the cmake:QuickStart drop down. That made some kind of windows pop up. I have no idea what that was. Then I tried running cmake:QuickStart again after that and a bunch of little "toast looking" pop ups showed up in the lower right of VS Code. I didn't argue with the toast popups which led to the "project name" window showing up. I always saw the "kit selection" drop down that you are asking about w/out any sort of issue. From there I was able to copy over my source from the repo that I started using good ole fashioned [make]. After that I combined DuckDuckGo w/ a bit more childlike debugging and I now off to the races. In summary I got lucky. I don't know if any of this helps you with your debugging/QA efforts but I am more than willing to meet you on discord or Teams so that you can poke around my machine. Thanks for the help.

**Comment by gregvanl** [comment]
@ProfDan Glad you are unblocked. I mostly work on the main VS Code editor documentation and don't have a lot of familiarity with the CMake extension. I've assigned this issue to @jureid, who works on the C++/CMake extensions team and she may want to reach out to you.
Thank you for your detailed notes and letting us know that the CMake:QuickStart workflow can be confusing. Valuable feedback.

**Comment by gregvanl** [comment]
Closing as you are unblocked. And thanks for the detailed feedback.
