### ISSUE TITLE
Doc gap: How are VCS credentials handled when using SSH?

### ISSUE THREAD

**Issue by zeen** [microsoft/vscode-docs#4310]
- VSCode Version: 1.52.1
- OS Version: Darwin x64 19.6.0

This is a documentation gap that I'm hoping to get fixed:

The [SSH documentation page](https://code.visualstudio.com/docs/remote/ssh) lacks any real mention of VCS handling. In particular: When developing over SSH with a Github repo, it's unclear if my Github credentials are copied to the remote box, or what capabilities the remote box gains as part of the process.

Being security minded, I'd like to understand how this works, so I can take appropriate precautions around key-rotation, compartmentalization, etc.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
We don't send your credentials anywhere. If you want this sort of thing, your best bet is to enable SSH agent forwarding in your SSH config, and that will work in the normal way.

**Comment by roblourens** [comment]
Well, let me add one thing which might be what you are thinking about. If you have logged in to github through VS Code's github support, then that github token will be accessible to extensions that you have granted access. Those can be local extensions, or remote extensions.

**Comment by zeen** [comment]
@roblourens Thanks for the response! How does the `Remote-Containers: Clone Repository in Container Volume...` feature work in that case? Is the repo cloned locally and copied to the remote volume, or does that attempt to clone remotely via somehow passing credentials over? Or does it only work with credential-less repos?

**Comment by roblourens** [comment]
I think that extension does share your credentials with the container, cc @chrmarti

**Comment by chrmarti** [comment]
It registers a Git credential helper in a temporary container that is created just for cloning the repository in the volume.

**Comment by gregvanl** [comment]
Closing as customers questions have been answered.
