### ISSUE TITLE
VS Code typeScript tutorial bug

### ISSUE THREAD

**Issue by effectivewang** [microsoft/vscode-docs#4312]
Hey VS Code Community,

As I am trying to follow the typescript guide through https://code.visualstudio.com/docs/typescript/typescript-tutorial

In the section "Change the build output", it says "**Rerun** the command `tsc"`, because it says `rerun` with no explanation. I rerun with `tsc hellowrold.ts` and there is no `out` folder, it confused me for some time.

Are the vscode articles open sourced? and can the tutorial be improved that it is a `run` not a `rerun`, and a bit more explanation to avoid confusion in the future?

Thanks,

**Comment by gregvanl** [comment]
Fixed with PR https://github.com/microsoft/vscode-docs/pull/4311
