### ISSUE TITLE
Update C++ mingw docs to reference Msys2 (gcc 10.2)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-docs#4319]
The page https://code.visualstudio.com/docs/languages/cpp#_example-install-mingwx64 refers to https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download which is an old 8.1 version of gcc. We recommend using https://www.msys2.org/ instead, which uses gcc 10.2.

See https://github.com/microsoft/vscode-cpptools/issues/6536 for more info.

The details of the installation and usage would need to be updated as well.

**Comment by gregvanl** [comment]
Also need to update the topics under /docs/cpp.
For example:
https://code.visualstudio.com/docs/cpp/config-mingw - installation steps need to be updated
Other topics as well reference MinGW

**Comment by sean-mcmanus** [comment]
FYI, the text references to MinGW may still be valid. Msys2 is just the platform for obtaining updated MinGW binaries for gcc/clang, e.g. doing F5 shows the binaries under a mingw64 path:

![image](https://user-images.githubusercontent.com/19859882/107428458-83ff6d80-6ad7-11eb-909f-3b6206d6230b.png)

**Comment by jureid** [comment]
https://github.com/microsoft/vscode-docs/pull/4645 addresses this
