### ISSUE TITLE
Accessibility: Update tab key navigation docs with new pattern for arrow keys in toolbars and tab lists

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/vscode-docs#4323]
[This section](https://code.visualstudio.com/docs/editor/accessibility#_tab-navigation) will need updating once https://github.com/microsoft/vscode/issues/116559 sticks and makes its way into 1.54.

**Comment by isidorn** [comment]
@marcozehe great catch

I can look into writing this once the changes are a bit more stable.
@gregvanl let me know if you would prefer to write it.

**Comment by isidorn** [comment]
Tackled via cf81c805
