### ISSUE TITLE
Recommended SFTP extension in SSH docs no longer works.

### ISSUE THREAD

**Issue by dnrm** [microsoft/vscode-docs#4325]
The recommended SFTP extension in the *Remote Development using SSH* page [here](https://code.visualstudio.com/docs/remote/ssh#_can-i-use-vs-code-when-i-only-have-sftpftp-filesystem-access-to-my-remote-host-no-shell-access), no longer works with VScode 1.53, since it throws the error "Extension host terminated unexpectedly". It would be good if it was changed to a working extension in order to not recommend a broken extension to anyone looking for help.

**Comment by gregvanl** [comment]
Hi @dnrm Sorry the latest release is causing problems. This looks like a known issue being tracked in the extension repo https://github.com/liximomo/vscode-sftp/issues/881.
Until it is fixed you can go back to VS Code 1.52 by the links on the top of the release notes https://code.visualstudio.com/updates/v1_52.
If the issue isn't fixed shortly, we can look into removing or updating the SFTP scenario recommendation.

**Comment by dnrm** [comment]
Thank you!
