### ISSUE TITLE
Debugging mono section should be removed

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#433]
Refs: https://code.visualstudio.com/docs/editor/debugging

We have a large section regarding mono debugging. My suggestion is to remove this section as the mono debugging experience is not a Tier 1 experience IMHO. It should be just mentioned in the other languages (like go, powershell...)

**Comment by weinand** [comment]
I will move the mono section into the [Readme.md](https://github.com/Microsoft/vscode-mono-debug/blob/master/README.md) that appears on the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug).

**Comment by gregvanl** [comment]
@weinand Were you going to move the Mono Debugging section to the extension README or did you want me to submit a PR?
