### ISSUE TITLE
Add OCaml language topic

### ISSUE THREAD

**Issue by smorimoto** [microsoft/vscode-docs#4330]
Goals:
  - Search "VSCode OCaml" finds out docs
  - "Language Overview" has OCaml link

Tasks:
  - [ ] Clarify the underlying tasks

**Comment by gregvanl** [comment]
Hi @smorimoto This looks primarily like an issue for an external team working on OCaml to improve the search optimization for their documentation.
It is also unclear what the "Clarify tasks" check box is for.
Closing for now but perhaps more information would help us understand better the request.
