### ISSUE TITLE
Error message when following c++ for mac configuration tutorial 

### ISSUE THREAD

**Issue by kmanpearl** [microsoft/vscode-docs#4332]
I have been trying to set up the c++ extension on my mac following this tutorial:
https://code.visualstudio.com/docs/cpp/config-clang-mac

When I try to run the helloworld code I get the following output:
`error: expected ';' at end of declaration
    vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};
                      ^
                      ;

/Users/keenanmanpearl/Desktop/VisualStudio/helloworld.cpp:11:29: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const string& word : msg)
                            ^`

I ended up changing the entire code to `cout << "Hello World << endl;` and the rest of the set up worked fine but I am not sure why the section of code copied and pasted directly from the tutorial was not running.

**Comment by gregvanl** [comment]
Hi @kmanpearl You have to make a change to the default tasks.json to have support for the later C++ standard.

https://code.visualstudio.com/docs/cpp/config-clang-mac#_compiler-and-linking-errors

You need to set `-std=c++17` in tasks.json:

```json
      "command": "/usr/bin/clang++",
      "args": [
        "-std=c++17",
        "-stdlib=libc++",
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}"
      ],
```
Feel free to reopen this doesn't fix your build issue.

**Comment by gregvanl** [comment]
@jureid Should the default tasks.json for clang++ be something other than c++98?

**Comment by kmanpearl** [comment]
@gregvanl my task.json file matches what you put exactly but I am still getting the same error

**Comment by kmanpearl** [comment]
This is my tasks.json file:
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
      {
        "type": "shell",
        "label": "clang++ build active file",
        "command": "/usr/bin/clang++",
        "args": [
          "-std=c++17",
          "-stdlib=libc++",
          "-g",
          "${file}",
          "-o",
          "${fileDirname}/${fileBasenameNoExtension}"
        ],
        "options": {
          "cwd": "${workspaceFolder}"
        },
        "problemMatcher": ["$gcc"],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]`

**Comment by gregvanl** [comment]
Hi @kmanpearl I reopened the issue. It may be a little while until I can try to reproduce this on a Mac.
I do have one suggestion to try: replace `"type": "shell"` with `"type": "cppbuild"` in tasks.json.
There have been some recent changes with the C++ extension and task types.

**Comment by gregvanl** [comment]
Hi @kmanpearl I tested the Clang tutorial on my Mac and the only way I can get your error is if I don't have `"-std=c++17"` set in the tasks.json. 
The default tasks.json created by the extension "clang++ build active file" build task option will also generate your error since it doesn't set  `"-std=c++17"`.
Is there a chance that you have two tasks.json files and you are editing one and building with another?

**Comment by kmanpearl** [comment]
This is my first time with visual studio so I cannot say with certainty that I have only one file; however there is only one file named "tasks.json" in the directory so I am assuming it's the only one. The file has `"label": "clang++ build active file"` but the args is `"-std=c++17"`. The code in the comment above was copy and pasted directly from my file.

**Comment by gregvanl** [comment]
Hmm, weird. The active tasks.json file should in a .vscode folder under the helloworld folder.
Per the tutorial, the folder structure would be:
helloworld
   .vscode
      tasks.json
 helloworld.cpp

**Comment by kmanpearl** [comment]
I have added a few other codes to the folder as well but this is what it looks like it. I did have some issues during the set up so I had to uninstall/reinstall the program a few times and start over. Maybe this caused some issue?

<img width="240" alt="Screen Shot 2021-02-19 at 2 37 30 PM" src="https://user-images.githubusercontent.com/66886906/108569002-00583480-72c0-11eb-80f5-d9107d9bfd69.png">

**Comment by gregvanl** [comment]
That folder structure looks correct and the tasks.json you have will build the active file.
I'm at a loss for further suggestions or investigations. By default, clang++ will build C++ files to the c++98 standard and maybe this is enough for you to carry on with your work.
If you have further issues with the C++ extension, you can also enter an issue in the extension repo at https://github.com/microsoft/vscode-cpptools/issues

**Comment by kmanpearl** [comment]
Thanks for your help. I'm glad I wasn't missing something obvious.
