### ISSUE TITLE
Python Create virtual environment does not set workspace correctlly  

### ISSUE THREAD

**Issue by K2AAE** [microsoft/vscode-docs#4338]
Following the Getting Started with Python in VS Code -> Using Python environments in VS Code  everything worked until: Create and activate the virtual environment. There was no pop-up asking about selecting the new virtual environment as the workspace folder. When you run the include example from VS Code you get the can not find errors but when running from the terminal: 
(.venv) PS C:\Users\Name\hello>python standardplot.py   it runs.
There is nothing about how to manually set the virtual environment as the current workspace.  
Python 3.9.1 MS Store, Windows 10 Pro Insider Preview 21313.rs_prerelease.210209-1440

**Comment by JoshuaPartlow** [comment]
Hi @K2AAE - Are you able to select your virtual environment by running the Python: Select interpreter command from the Command palette? When you say it runs from the terminal, did you activate the environment manually or was it activated for you?

**Comment by JoshuaPartlow** [comment]
Closing due to time with no reply. If this is still an issue, please reopen.
