### ISSUE TITLE
Debugging other languages section needs more love

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#434]
Refs: https://code.visualstudio.com/docs/editor/debugging

Currently it is possible to debug many languages, currently there is just a short section mentioning that. This section needs more love (at least links to the extensions that enable these debugging experiences)

fyi @weinand

**Comment by gregvanl** [comment]
Removed this section since we have a section at the top of the doc https://code.visualstudio.com/docs/editor/debugging#_debugger-extensions.
