### ISSUE TITLE
Why can't I install g++?

### ISSUE THREAD

**Issue by Cliff0317** [microsoft/vscode-docs#4350]
Hello everyone, I don't know if this is in the range of this repository, but I checked the documentation regarding C++, here - https://code.visualstudio.com/docs/cpp/config-mingw, but I clicked on the link regarding MinGW-w64, but when I tried to download it, it failed because my computer is x64 bit. Can anyone help? I am able to give any details regarding the problem.

**Comment by gregvanl** [comment]
Hi @Cliff0317 Sorry you are having trouble installing g++ via MinGW. 
The C++ extension team is now recommending using the MSY2 installation instead but the tutorials have not yet been updated. See https://github.com/microsoft/vscode-docs/issues/4319 for the recommendation and links to the C++ extension vscode-cpptools repo issue.
Here's the link to the MSYS2 toolset https://www.msys2.org.
I haven't tried it myself but would be curious if it works for you.

**Comment by gregvanl** [comment]
Closing as no response from author

**Comment by gregvanl** [comment]
Great, glad you are unblocked.
