### ISSUE TITLE
Unclear "editor.autoClosingBrackets": "languageDefined" description

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode-docs#4360]
On the [default settings page](https://code.visualstudio.com/docs/getstarted/settings#_settings-editor), the description for the  "editor.autoClosingBrackets": "languageDefined" option is unclear.

The docs:
```
  // Controls whether the editor should automatically close brackets after the user adds an opening bracket.
  //  - always
  //  - languageDefined: Use language configurations to determine when to autoclose brackets.
  //  - beforeWhitespace: Autoclose brackets only when the cursor is to the left of whitespace.
  //  - never
  "editor.autoClosingBrackets": "languageDefined",
```

What does `languageDefined: Use language configurations to determine when to autoclose brackets` mean?
Where does VS Code get this information from? Language-specific user settings or somewhere else?
If it gets this from language-specific user settings, does it get it from the `editor.autoClosingBrackets` or some other setting?
If it gets this configuration from the `editor.autoClosingBrackets` setting, what happens if you set it to `languageDefined` again - does it force the default behaviour?
What is the default behaviour for languages VS Code doesn't know about?

Cheers!

**Comment by gregvanl** [comment]
Hi @andrecasal Nice to see hear from you again!
`languageDefined` means that the closing behavior is specified by the language configuration in the extension manifest. You can find the details at https://code.visualstudio.com/api/language-extensions/language-configuration-guide.
Good question about the behavior for languages VS Code doesn't know about. I'll try to dig that up. VS Code does define autoClosing behavior for some 61 languages in the box (https://github.com/microsoft/vscode/blob/main/extensions/go/language-configuration.json) but new languages arrive all the time.

**Comment by andrecasal** [comment]
Hey @gregvanl Nice to see you too buddy! 😊
I see, so having "editor.autoClosingBrackets": "languageDefined" means VS Code will automatically define the behaviour (and what constitutes a bracket), according to the [language extensions installed](https://github.com/microsoft/vscode/tree/main/extensions).

I'm guessing the default behaviour for languages VS Code doesn't know about is to not auto close the brackets?

Outside of changing a language extension can the user have any control over this? Language specific settings perhaps?

**Comment by gregvanl** [comment]
Playing around with a `blah.blah` file, I think VS Code will always set a language mode and the default is `plaintext`, which does auto close brackets. I'm not sure where this behavior is defined but I think it is probably in the base Monaco editor.
I don't think the user can alter the auto closing bracket pairs via settings, only switch the behavior between the four strategies.
You can set this behavior with a language specific setting.

**Comment by andrecasal** [comment]
Exploring the language extensions source code, I don't see rules for **when** to autoclose brackets, only **which** brackets to autoclose.

Which begs two questions:
What strategy is used on the `languageDefined` option - beforeWhitespace?
What bracket pairs are considered on the `beforeWhitespace` option - (), [], and {}?

If that's true, `beforeWhitespace` is just a less useful form of `languageDefined`, as `languageDefined` can include things like `<!-- -->` pairs for HTML, for example.

**Comment by gregvanl** [comment]
Hi @andrecasal Sorry, I've been preoccupied and let this thread languish.
The beforeWhitespace closing strategy is very basic and only checks that the cursor isn't in front of any non-whitespace character. 
The languageDefined closing strategy can be more selective and allow closing when in front of certain language-important characters. For example, it can allow auto-closing in front of ';', ':', or ']', letting the user add open/close parentheses in cases like:
```
myMethod_; to become myMethod();
``` 
The Language Configuration Guide has a pretty good example https://vscode-docs-main.azurewebsites.net/api/language-extensions/language-configuration-guide of what these language configurations look like.

No matter what the auto-closing strategy, the current language defines what characters constitutes a bracket. For the fallback language `plaintext`, it looks like brackets are just (), {}, and []. I notice for Markdown <> is also added, so a language can define anything for the brackets.

I hope I've answered your latest questions.

**Comment by gregvanl** [comment]
Closing, feel free to post other questions.
