### ISSUE TITLE
finding python environment when using "Run Code"

### ISSUE THREAD

**Issue by mark-naylor** [microsoft/vscode-docs#4361]
Hi,
  I have conda created environments that I can see in the Select Interpreter dropdown and works when I select and run a few lines of code and press "shift return" on my Mac.
  However, if I instead right click on the code and choose "Run Code" it fails to find the packages to import which, I think, means it is not finding the interpreter correctly under this scenario. I think Run Code is finding the system installation of Python.
  Any thoughts?
Best wishes,
Mark

**Comment by gregvanl** [comment]
@luabud This looks like a Python extension issue, should @mark-naylor move this issue to https://github.com/Microsoft/vscode-python/issues?

**Comment by mark-naylor** [comment]
Appologies, I am new to managing issues in Git.
Should I go ahead and move this and might you be able to point me to how to move it.
Many thanks
M

**Comment by gregvanl** [comment]
Hi @mark-naylor I don't think there is a direct way to transfer the issue to vscode-python and it also looks like that repo has an issue template they would like filled out.
If you do create a new issue in vscode-python, you can mention it in a comment in this issue and they will be linked, which can be helpful for people searching for python issues in vscode-docs.

**Comment by luabud** [comment]
Hey @mark-naylor, I filed https://github.com/microsoft/vscode-python/issues/15532 to follow up on your issue. 

Feel free to close this one, @gregvanl! :)

**Comment by gregvanl** [comment]
Thanks @luabud! Will do.
