### ISSUE TITLE
Doc for the drag/drop of Panels and Views

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#4362]
It is now possible in VSC to drag/drop Panels and Views and make it possible to get multiple Panels side-by-side.

I was not able to find any reference on it in the doc but have read in the release notes and on [SO_1](https://stackoverflow.com/a/65504739/9938317) and [SO_2](https://stackoverflow.com/a/62948226/9938317)

I had to play with it and found that you drag/drop the non-current panel and make it a vertical split of the current Panel

Can we have some doc for this nice feature

**Comment by rioj7** [comment]
@gregvanl Until the full doc addition maybe a small mentioning of the feature and a link to the v1.46 release notes.

**Comment by gregvanl** [comment]
Oops, closed by accident when working on docs/editor/github.md

**Comment by GitMensch** [comment]
@gregvanl wrote:

> There may still be more work coming on this support but once it is finished, it will be added to the main documentation.

I _guess_ there won't be coming that much any more. What is the state on the documentation part?

**Comment by gregvanl** [comment]
Consider adding to "Advanced editing" topic https://github.com/microsoft/vscode-docs/issues/6393
