### ISSUE TITLE
Location of settings.json does not account for portable mode

### ISSUE THREAD

**Issue by smac89** [microsoft/vscode-docs#4365]
In the [documentation](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations) regarding location of `settings.json` file, it does not take into account the possibility of being located in vscode's [portable](https://code.visualstudio.com/docs/editor/portable#_migrate-to-portable-mode) directory for users who have setup/migrated to a portable installation.

**Comment by gregvanl** [comment]
Hi @smac89 Thank you opening an issue and your interest in the VS Code documentation.
Portable mode is a somewhat advanced feature so I don't think we want to confuse users in the basics setting documentation.  Given that portable defines a new location for VS Code user data, portable mode users should be able to infer that .settings.json will also be there.
