### ISSUE TITLE
No mention of new Snippet: Variables - Hide

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#4367]
In the [version 1.53](https://code.visualstudio.com/updates/v1_53#_editor) release notes there is mentioning that there are new snippet variables `${RELATIVE_FILEPATH}` and `${UUID}`.

They are not mentioned on the [Snippets doc (variables)](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) page.

Why is `${RELATIVE_FILEPATH}` not named `${TM_RELATIVE_FILEPATH}` like all other file related variables?

The new Snippet features from [version 1.52](https://code.visualstudio.com/updates/v1_52#_snippets) release notes are not in the [Snippets doc](https://code.visualstudio.com/docs/editor/userdefinedsnippets) page.

**Comment by gregvanl** [comment]
The missing snippet variables were added with https://github.com/microsoft/vscode-docs/pull/4434.
Still need to mention the Hide button
