### ISSUE TITLE
Why are there two extension samples?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-docs#437]
We have `Example-WordCount` and `Example-HelloWorld` which both serve as a simple sample. I suggest to get rid of _word count_. For more complex samples we have a dedicated repo

**Comment by gregvanl** [comment]
It is true that the word count topic is less popular than hello world (GA shows it 1/4 as popular) but I don't believe maintaining the second walkthrough has been a burden. Word count provides an introduction to events and modifying the UI (Status Bar). Unless there is a benefit to removing the walkthrough, I'd keep it.
