### ISSUE TITLE
virtual environment not appearing in command palate  

### ISSUE THREAD

**Issue by abwillingham** [microsoft/vscode-docs#4382]
With a new install of VS Code, the Python Extension, and Python 3.9.2 64bit, I am following the tutorials.
After creating and activating a new virtual environment inside a new terminal window, the new venv does not appear in the command palate as one of the Python interpreters. 
![svcode](https://user-images.githubusercontent.com/3596846/110727289-f18ede80-81e8-11eb-86b8-da752b0f7dab.PNG)

**Comment by JoshuaPartlow** [comment]
Hi @abwillingham - What workspace (folder) do you currently have open? Is it the same one within which you created the environment? Also, are you manually able to set it using the Command Palette if you use the first option in the image you included (Enter interpreter path...) ?

**Comment by JoshuaPartlow** [comment]
Closing given timeframe with no reply.
