### ISSUE TITLE
Starting Extension tests with a know folder/workspace

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#4387]
In the current doc for [VSC Extension testing](https://code.visualstudio.com/api/working-with-extensions/testing-extension) there is no mentioning how to open a folder/workspace that is needed to do the tests. If you do this in the test, the test is terminated after the `vscode.openFolder` statement.

In a [previous version of the doc](https://vscode-docs.readthedocs.io/en/stable/extensions/testing-extensions/#passing-arguments-to-the-extension-development-host) it was mentioned that you can add the folder/workspace path as argument to the launch configuration.

**Comment by gregvanl** [comment]
Looks like these are now covered in https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-script, which mentions the two CLI parameters `--extensionDevelopmentPath` and `--extensionTestsPath`.
The snippet comments explain their use.
It also covers how to set these parameters when using the vscode-test API.
