### ISSUE TITLE
Typo in SnippetString -> appendChoice

### ISSUE THREAD

**Issue by Daniel-Knights** [microsoft/vscode-docs#4393]
In [the documentation for `appendChoice`](https://code.visualstudio.com/api/references/vscode-api#SnippetString), there's a typo in the line:

> Builder-function that appends a choice (${1|a,b,c}) to the value of this snippet string.

Should be (extra pipe character at the end):

> Builder-function that appends a choice (${1|a,b,c|}) to the value of this snippet string.

**Comment by gregvanl** [comment]
Hi @Daniel-Knights, api/reference/vscode-api is generated from vscode.d.ts so the fix should be made in the VS Code product repo.
https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts
Feel free to submit a PR there.
Thanks for noticing and pointing this out.
