### ISSUE TITLE
onDidChangeActiveTextEditor: Event<TextEditor | undefined> cannot work for ipynb file

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-docs#4405]
If I use ipynb file, it cannot be treated as a texteditor. I'm trying to get the "editor.document.languageId" and editor.document.filepath. But this cannot work for me. I'm using vscode 1.54.3. Would you mind help with it?  Thanks!

**Comment by pepe-invest-git** [comment]
t

**Comment by rebornix** [comment]
@zesluo can you confirm that the ipynb file is not opened in a text editor? If so then it's as expected as it's opened either in a custom editor or a notebook editor, but not text editor.

**Comment by zesluo** [comment]
![image](https://user-images.githubusercontent.com/46309533/111940358-878c0880-8b09-11eb-8bab-bb243d162ffb.png)

Hello @rebornix , thanks for your reply! It opened like this.

**Comment by gregvanl** [comment]
The image shows the file opened in a notebook editor so this is expected behavior.
