### ISSUE TITLE
Can't find virtual environment among list of python interpreters

### ISSUE THREAD

**Issue by rogerjbos** [microsoft/vscode-docs#4408]
I created a virtual environment located in ~/env.  I can access it in the terminal with `source env/bin/active`, however it does not show up as an action when I attempt to select python interpreter.  As a first step to resolve, I added the env folder as a workspace and now it shows the `env` folder as a first option, but when I click that it shows the same list of python interpreters and doesn't include the path to `env/bin/activate`.
<img width="862" alt="Screen Shot 2021-03-21 at 9 56 07 AM" src="https://user-images.githubusercontent.com/4925977/111907729-02cbbc80-8a2d-11eb-9d50-6292ce5301cf.png">
<img width="867" alt="Screen Shot 2021-03-21 at 9 56 20 AM" src="https://user-images.githubusercontent.com/4925977/111907730-03645300-8a2d-11eb-9527-b8d61d8fb00d.png">

My underlying problem is a "ModuleNotFound" problem.  I installed eth-brownie, but when I try to import from it, I get the "ModuleNotFound" error:

>>> from brownie import SimpleCollectible, accounts, network, config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'brownie'

If I use `which brownie` in the terminal I can see the location is `/Users/rogerbos/.local/bin/`.  In the past I was always able to fix "ModuleNotFound" errors by explicitly adding the path as follows:
```
import sys
sys.path.append("/Users/rogerbos/.local/bin/")
```
but even that does not work, so I created the virtual environment and re-installed eth-brownie there, but it still doesn't work.
I know both eth-brownie installs worked because `brownie --version` returns the version number.
If anyone has any suggestions I would be very appreciative. Thanks in advance.

**Comment by JoshuaPartlow** [comment]
Hi @rogerjbos - Have you tried to set it using the "Enter interpreter path..." option in the command palette list you show in the image? You should also be able to specify the path to the folder with the virtual environment using the `python.venvPath` setting. Do either of those work for you?

**Comment by rogerjbos** [comment]
Thanks @JoshuaPartlow.  Adding `python.venvPath` did the trick.  Thanks for your help.

**Comment by JoshuaPartlow** [comment]
Excellent, glad to hear it's working now.
