### ISSUE TITLE
Document `workbench.enableExperiments`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-docs#4412]
We should mention `workbench.enableExperiments` in our docs. Maybe after https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting as is based on the telemetry support?

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/5df48e39e0a950715074e68ddf7b41a3cf258d85
