### ISSUE TITLE
Can not select Python interpreter for VS Code

### ISSUE THREAD

**Issue by TogrulKazimov** [microsoft/vscode-docs#4414]
I have been using the vscode for 1.5 years but never faced such an issue before, I have reinstalled the vscode but nothing changed. 
I definitely find Python.exe and select it, but nothing changes.

![image](https://user-images.githubusercontent.com/60192576/112206784-c1572f00-8c2f-11eb-8210-6d0eaee2bd17.png)

![image](https://user-images.githubusercontent.com/60192576/112207125-3165b500-8c30-11eb-9442-4ea59c166066.png)

**Comment by JoshuaPartlow** [comment]
Hi @TogrulKazimov - When you say nothing changes, do you mean that the lower toolbar continues to show "Select Python Interpreter" after you've selected one? Or do you mean that nothing works when you attempt to run your code? I'm wondering because I see the second image shows a current interpreter.

**Comment by luabud** [comment]
Hey @TogrulKazimov! Would you mind filing an issue at the Python extension repo, providing more information so we can investigate what is going on? https://github.com/microsoft/vscode-python/issues/new?assignees=&labels=classify%2C+type-bug&template=2_bug_report.md

In particular we're interested in the contents of your Python output channel:

![image](https://user-images.githubusercontent.com/45497113/112698908-f76efb80-8e47-11eb-947a-961d4df81b3d.png)

**Comment by JoshuaPartlow** [comment]
Will keep an eye out for any doc issues related to this, but closing for now.
