### ISSUE TITLE
No "bin" folder on project 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-docs#4415]
Not sure what to do. I've checked everything is installed in the terminal but the bin folder still does not appear. 

![Screen Shot 2021-03-23 at 3 57 01 PM](https://user-images.githubusercontent.com/81262683/112210024-8aadf400-8bf0-11eb-9853-ba3dff0b991b.png)

**Comment by gregvanl** [comment]
The author's account has been deleted (shows as ghost) so closing.
The next steps would be to check if there is a .vscode\launch.json and if so, whether it specifies building to a bin folder.
This project is also using a Makefile, which might define where the output executable should go.
