### ISSUE TITLE
Tree View API docs implicitly uses a non default TreeItemCollapsibleState

### ISSUE THREAD

**Issue by galesky** [microsoft/vscode-docs#4418]
Hello,

When going through the [Tree View Docs ](https://github.com/microsoft/vscode-docs/blob/8afbd5493c89a4cbdc6f09e3e6824d0398bbf80b/api/extension-guides/tree-view.md)I had an issue with rendering children `TreeItems`

The docs state that
> When the user opens the Tree View, the getChildren method will be called without an element. From there, your TreeDataProvider should return your top-level tree items. **getChildren is then called for each of your top-level tree items, so that you can provide the children of those items.**

The highlighted statement is only true if the `TreeItemCollapsibleState` of the `TreeItem` is not `None` (default), as we can see also indicated here on [DefinetlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts#L9067) (which matches the actual behaviour)

I would suggest updating the docs to something along the lines of 
> When the user opens the Tree View, the getChildren method will be called without an element. From there, your TreeDataProvider should return your top-level tree items. 
**In our example the TreeItemCollapsibleState is Collapsed, so getChildren is then called for each of your top-level tree items, so that you can provide the children of those items. TreeItemCollapsibleState determines if an item can be expanded. It defaults to `None` and in that case implies it has no children.**

And maybe also some reference after the code example itself

I can work on a PR if it's agreed it makes sense to update this doc

**Comment by alexr00** [comment]
@galesky that clarification makes sense. I would word it a little differently though. How about something like:

> In our example the `collapsibleState` of the top-level tree items is `TreeItemCollapsibleState.Collapsed`, meaning that the top-level tree items will show as collapsed. Setting a `collapsibleState` of `TreeItemCollapsibleState.Expanded` will cause tree items to show as expanded. Leaving the `collapsibleState` as it default of `TreeItemCollapsibleState.None` indicates that the tree item has no children. `getChildren` will not be called for tree items with a `collapsibleState` of `TreeItemCollapsibleState.None` .

**Comment by alexr00** [comment]
Also, a PR would be great!

**Comment by galesky** [comment]
Thanks for the Feedback @alexr00 , 

I'll work on the PR later today then

**Comment by gregvanl** [comment]
Hi @galesky Looks like you got busy so I went ahead and added the agreed upon text.
Thanks for calling out the confusion and working with Alex on a better explanation
