### ISSUE TITLE
Remove vscode-icons from a recommend list of extensions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#442]
refs: https://code.visualstudio.com/docs/customization/themes

vscode-icons extensions modifes the packaed content of vscode. This can lead to a lot of undesired behvaior and due to that I believe we should not recommend this extension anywhere

**Comment by gregvanl** [comment]
This list of extensions is returned by a Marketplace query showing the most popular extensions in a given category.  We can't currently filter out individual extensions to the list.  Assigning to Wade to look at when he comes back.

**Comment by gregvanl** [comment]
vscode-icons has been updated to use the supported extension point.  We're happy to promote it now.
