### ISSUE TITLE
Setup of VS code for C programing.

### ISSUE THREAD

**Issue by Achyutaryaa** [microsoft/vscode-docs#4433]
I don't know that how to run C program in VS code. I have installed VS code and extensions of C program. I don't know how to set variable environment also.
You can also reply me on [https://facebook.com/KingAchyutaryaa]

**Comment by logesh07** [comment]
First install using mingw zip file for system it give c++ complier ,debugger and c++ other library files
             https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/

Mark for install all **gnu c++ compiler**

check path in your sys   C:\MinGW  (windows)
if you downloaded search for  edit environment variables for your account and add this  **C:\MinGW\bin**  path in PATH variable

check  for
g++ --version
gdb --version

copy task & launch json. it build & execute  your c++ code
Note if you change directory or you can't see 2 files you should add it

Refer link for detail Explanation

https://code.visualstudio.com/docs/cpp/config-mingw

**Comment by gregvanl** [comment]
Closing as user was pointed to MinGW tutorial and hasn't responded.

**Comment by Achyutaryaa** [comment]
Okay! It is working now.

**Comment by yaxye8123** [comment]
Command isn't which I went
