### ISSUE TITLE
API structure is unclear

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-docs#444]
We have two sections: `Extensibility` and `Extensibility Reference` - the former is tutorial style and the latter is a reference. In VS Code, there are three kinds of extensions (1) extensions, (2) language server extensions, and (3) debuggers. The latter two integrates via defined protocols whereas the first uses an API.

The problem is that the `Extensibility Reference` talks mostly only about the _api extensions_, not about the protocol extensions. 

The structure should be more like this
- Extensions - explain the three ways of extending VS Code (API, protocol, debuggers)
- For Each Way of Extending have `Ext Ref`
  - API Docs
  - Debugging/Dev etc (how to debug a language server, etc)
  - etc

**Comment by gregvanl** [comment]
Extensions and Extensibility Reference TOC nodes were removed during the API refactoring, which was heavily reviewed for TOC layout.
