### ISSUE TITLE
Additional Components

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-docs#446]
Not sure why we would insist so much on node related things in this page:

https://code.visualstudio.com/docs/setup/additional-components

I have a feeling that: TypeScript and Typings should go under the Languages section

Additional Tools --- why do we link to them?

IMHO this page can be deleted.

**Comment by gregvanl** [comment]
Page sentiment high (83% smiles), viewing statistics seem good (6K per month) and verbatim generally positive so closing
