### ISSUE TITLE
Remove references to snippets for Python

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#4469]
E.g. https://code.visualstudio.com/docs/languages/python#_snippets

From https://github.com/microsoft/vscode-python/issues/15914.

**Comment by JoshuaPartlow** [comment]
Hi @brettcannon - I removed the section you referenced. I didn't touch the mentions in Flask/Django tutorials, because they were about user-defined snippets. If those should be removed as well, just let me know. Searching the MD files, I didn't see any other references.
