### ISSUE TITLE
Finding 'Debugging' (and others) is not intuitive 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docs#447]
I find it strange that a user who needs more information about "Debugging" has no top-level item for this but needs to search for it in some not-so-obvious sub-topics. Even an advanced topic like 'Extensibilty Reference' is more prominent than 'Debugging'.

![2016-07-04_17-31-43](https://cloud.githubusercontent.com/assets/1898161/16565448/8452d2ba-420d-11e6-843d-c317832bc430.png)

A somewhat obvious candidate to search for Debugging is "Tools", but this is a dead end.
So in the end a user will find it under 'Editor', but this does not seem to be very intuitive even if VS Code is considered an 'Editor' with support for the 'inner loop'.

One simple way to fix this would be by expanding the 'Editor' node automatically. With that it would become more apparent that some not-so-obvious functionality hides behind the 'Editor'.

/cc @isidorn @egamma

**Comment by isidorn** [comment]
I had a similar concern that I expressed here #406

**Comment by gregvanl** [comment]
Covered in Debug docathon. We're going to add a Debugging TOC node.
