### ISSUE TITLE
Leading doublequotes on 'Testing view colors' lines

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#4471]
Visible at https://code.visualstudio.com/api/references/theme-color#testing-view-colors

![image](https://user-images.githubusercontent.com/6726799/114467450-d9442200-9be1-11eb-91aa-a098a57e879f.png)

**Comment by gregvanl** [comment]
@gjsjohnmurray Thanks for noticing and calling this out!
