### ISSUE TITLE
Consider moving 'Node Debugging' section out of 'Debugging' 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docs#448]
IMO the 'Debugging' chapter has this purpose:
- give an overview of the runtime-independent debugging functionality of VS Code (some of this is shown for node.js because there is no 'generic' debugger),
- serve as a 'trampoline' for the builtin (or almost-builtin) debug extension for JS, TS and .NET Core,
- serve as a 'trampoline' for other debug extensions on the marketplace.

With this it does not make a lot of sense to have very detailed feature explanation for node.js inlined in this chapter. I suggest to move everything under 'Node Debugging' into 'Runtimes/Node.js'

/cc @isidorn @egamma

**Comment by isidorn** [comment]
Agree, we shuold try to keep the debuggin chapter general to all the languages and just shortly advertise all the languages we support. Some languages deserve a special section - like node already

**Comment by waderyan** [comment]
@gregvanl what if I pulled this section out of debugging and moved it to the JavaScript doc I am working on?

**Comment by gregvanl** [comment]
The section on Source Maps would make sense to add to the JavaScript doc but I don't think we want Node.js specific content there.  Aren't there other JavaScript runtimes besides Node.js?
I'm not sure about this issue in general and I'd like to think about it more before removing it from debugging.md.  I put it in this milestone so I would remember to consider this issue when reviewing the debugging topic. I think it is reasonable to put our in the box Node.js debugging content on this page.

**Comment by weinand** [comment]
@gregvanl the Chrome debugger (in chrome dev tools) is another JavaScript runtime which is supported by the ['Debugger for Chrome'](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome
) extension available on the Marketplace. There are plans to ship the Debugger for Chrome extension with VS Code because starting in version 7 node will support the Chrome Debugger protocol as well. So soon VS Code will ship with two debugger extensions.
In addition there is the Chakra JavaScript runtime which is compatible with node but supports additional features (e.g. back in time debugging).

**Comment by gregvanl** [comment]
I see your point now about keeping the debugging topic cleaner.
The issue I see is that the runtimes/Node.js topic is currently an entry level walkthrough to get people started and I worry if we put too much detailed debugging information there readers may get confused or frustrated. However the information on attaching could flow nicely with the walkthrough and then we could add an Advanced Debugging section later.
Another option is to have both a Node.js walkthrough and a separate Node.js reference topic.

**Comment by waderyan** [comment]
I like the idea of having a Node.js debugging guide, but I still don't see why it can't go in the JavaScript language guide. We should have something in JavaScript about debugging. I guess we can go with the Chrome Extension as an example of how to debug.

**Comment by gregvanl** [comment]
Moved function breakpoints out of Node Debugging section since other debug extensions may support function breakpoints. See https://github.com/Microsoft/vscode-docs/commit/13d7e7aafcf10cdc3e51821591edee86002b1a69#diff-644038a99f24b6b04db86f03f6f9e6d6

**Comment by gregvanl** [comment]
Node.js debugging is now it's own topic. Still need to add a new Debugging node to TOC.
