### ISSUE TITLE
Update Containers Getting Started doc to remove reference to Resources --> File Sharing

### ISSUE THREAD

**Issue by brooke-hamilton** [microsoft/vscode-docs#4487]
The doc at https://code.visualstudio.com/docs/remote/containers#_installation has Windows / macOS step 2, which says:

> 2. Right-click on the Docker task bar item, select Settings / Preferences and update Resources > File Sharing with any locations your source code is kept. See tips and tricks for troubleshooting.

The File Sharing option no longer exists in the Docker Desktop settings app, assuming we are using the WSL2 engine, which is a requirement for developing in a container. Please remove step 2 from the instructions.

**Comment by gregvanl** [comment]
Hi @brooke-hamilton Thanks for pointing that the File Sharing option isn't available after selecting the WSL 2 backend. I've reorder the steps to help avoid confusion.
