### ISSUE TITLE
Better documentation for launch.json (debugging.md)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docs#449]
- better explain what attributes are common across all debuggers and what are specific.
- explain variable substitution without referring to the task doc (variables are important, so users should see it here and not overlook this topic lightly).
- explain how to specify paths for different OSes and that all paths are absolute
- add new feature 'command variables'

And please see: https://github.com/Microsoft/vscode-docs/issues/230

/cc @isidorn

**Comment by isidorn** [comment]
We should also market our nice suggestions inside the launch.json better. I know we mention it in the current document but I would make it more prominent since it is a very helpful feature when users are setting up their `launch.json`

**Comment by gregvanl** [comment]
Still more work to be done here with attribute descriptions and OS path recommendations. Moving to November.

**Comment by gregvanl** [comment]
Covered in December doc-a-thon with debugging.md and node-debugging.md refresh. https://github.com/Microsoft/vscode-docs/issues/729
