### ISSUE TITLE
Feature description on View / Appearence / Show Menu Bar incorrect

### ISSUE THREAD

**Issue by kingma-sbw** [microsoft/vscode-docs#4496]
The text under https://code.visualstudio.com/docs/getstarted/userinterface#_hide-the-menu-bar-windows-linux incorrectly reads that by selecting and disabling Show Menu Bar the menu bar is toggled and is accesible temporarily by pressing the Alt key. This is not correct. View / Appearance / Show Menu Bar changes the setting "window.menuBarVisibility" to "compact". In compact the Alt key does not show the menu bar, only in "toggle". 
Remove the reference to the Alt key in this section or describe how the user can change the setting "Windows: Menu Bar Visibility" to "toggle" to arrive at the described behavior.

**Comment by josola** [comment]
I can submit a fix for this issue if needed.

**Comment by kingma-sbw** [comment]
That would be good.

I thing doc and product started to deviate on the after adding the compact menu mode (menu hamburger in Activity Bar). But as many stackoverflow and other resources attempt to help programmers stuck in a "missing-menu-bar-predicament" by indicating the Alt key for temporarily show the menu bar it would be good to help these with the documented behaviour. Apart from that, the action is called **View: Toggle Menu Bar** and setting **windows.menuBarVisibility** to "toggle" instead of "compact" would be prohably be more logical.
