### ISSUE TITLE
Found a typo in docs of "Example - Integrating Debuggers"

### ISSUE THREAD

**Issue by jakubsuchybio** [Microsoft/vscode-docs#45]
First sentense: (language agnostic)
Should probably be (language diagnostic) 
here: https://github.com/Microsoft/vscode-docs/blob/master/docs/extensions/example-debuggers.md

**Comment by gregvanl** [comment]
Hi Jakub, Thanks for reading our docs.  The sentence is correct.  VS Code is not bound to a specific programming language for its debug UI.  It displays debugging information in a generic way.
If you think this description is confusing, we may want to rewrite it.
