### ISSUE TITLE
Improve structure of 'Debugging' chapter

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docs#450]
In addition to adding some missing pieces I suggest the following more logical structure of the 'Debugging' chapter: 
- Launch Configurations 
  - 'setting up' especially important since new users will come for that
- Debug and Run
- Debug Actions
  - stepping (new: optional step back)
  - continue
  - restart
  - stop
- Current Location
  - Editor: arrow, current line (yellow and green)
  - Call stack: stop reason, stack frames, paging, multiple threads
- Breakpoints
  - Editor margin
  - breakpoints view: regular, functional, conditional
  - breakpoint actions
- Data inspection:
  - Variables view:
    - scopes
    - new: type hover
    - setting variable values
  - hovers
  - Watches
- Debug Console
  - data structure snap shots

@isidorn please correct and add more missing pieces

**Comment by isidorn** [comment]
@weinand I modified your comment with some of the missing pieces (threads, types of breakpoints, breakpoint actions) and added some minor comments

**Comment by isidorn** [comment]
@weinand @gregvanl it would be absolutetly awesome if we did this in October, since the newly generated launch.json will point to http://code.visualstudio.com/docs/editor/debugging#_launch-configurations

So this documentation needs to be as awesome as possible so new user easily figure out what they need to set in order to have a smoooth debugging experience

**Comment by isidorn** [comment]
@gregvanl has there been some progress on this? I think this is a key point in making the initial debug experience smoother

ping @weinand @chrisdias @waderyan

**Comment by gregvanl** [comment]
@isidorn Yes, you can track the progress in the vscode-docs vnext branch https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/debugging.md
I've done some reordering, updated to the new leaner launch.json and added descriptions for the required attributes.
Next is to fill out the variables substitution section and add more attribute descriptions.
The outline above is fairly exhaustive for all the debugging features, both those that are easily discoverable through the UI (for example : current location, stop reason, stack frame) and more advanced (multi-threaded, conditional breakpoints). The tricky bit is tuning the initial sections for the first time user (the goal for this milestone) without overwhelming them.

**Comment by gregvanl** [comment]
Still more work to be done here around variables view and advanced debugging like multithreaded. Moving to November.

**Comment by gregvanl** [comment]
Covered in December doc-a-thon with debugging.md and node-debugging.md refresh. #729
