### ISSUE TITLE
Improve the documentation https://code.visualstudio.com/docs/python/settings-reference#_pylint

### ISSUE THREAD

**Issue by danieltuzes** [microsoft/vscode-docs#4506]
According to the documentation, the description of pylintPath is
> The path to Pylint.

But it is not the path to pylint but the path to its setting file, e.g. to the folder where .pylintrc is or the path to .pylintrc file itself.

**Comment by JoshuaPartlow** [comment]
@luabud - Are you able to confirm the feedback in this issue. I notice that the Python extension settings for pylintPath match the doc description, so if wrong, this might need a clarification in both places.

**Comment by luabud** [comment]
Hi @danieltuzes, it turns out that it _should_ be the path to the pylint executable. if you tried it out and it didn't work, please file an issue on hub.com/Microsoft/vscode-python so we can investigate! Thanks 😊
