### ISSUE TITLE
Update screenshots in Python data science documentation

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-docs#4507]
Interactive window and data viewer screenshots are outdated in https://code.visualstudio.com/docs/python/jupyter-support-py
Data viewer screenshots are outdated in https://code.visualstudio.com/docs/python/jupyter-support#_variable-explorer-and-data-viewer

/cc @claudiaregio

**Comment by claudiaregio** [comment]
Thanks, was on this :)

**Comment by JoshuaPartlow** [comment]
Hi @claudiaregio - Is this something you were working on or would you like me to do it?

**Comment by claudiaregio** [comment]
@JoshuaPartlow Just messaged you about this

**Comment by JoshuaPartlow** [comment]
Talked with @claudiaregio and we'll track this along with some other updates, so closing for now.
