### ISSUE TITLE
A11y_Visual Studio Code_HomePage_Resize Text: At 200% zoom, when command bar is expanded and navigated in it focus comes out of command bar

### ISSUE THREAD

**Issue by NiharikaTipirishetty** [microsoft/vscode-docs#4514]
[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags:#A11y_Visual Studio Code#A11ySev2#A11yTCS#A11yMAS#Chrome#DesktopWeb#Win10#WCAG1.4.4#Resize Text#Zoom#Visual Studio Code Services#VisualStudioCode-Web-Apr2021

### Environment details:
Application Name: Visual Studio Code
URL:[Visual Studio Code](https://code.visualstudio.com/)
Windows Version: Version 20H2 (OS Build 19042.928)
Browser: Chrome Version 90.0.4430.85 (Official Build) (64-bit)

### Repro Steps:

1. Zoom the page to 200%
2. Hit [Visual Studio Code](https://code.visualstudio.com/) link
3. Navigate to command bar, press enter and tab inside command bar.
4. Verify that when command bar is expanded and while navigating inside command bar, keyboard focus comes out of it

### Note:
This issue is also observed for 'Download' dropdown in Home page

### Actual Result:
At 200% zoom, when command bar is expanded and navigated in it focus comes out of command bar

### Expected Result:
At 200% zoom, when command bar is expanded and while navigating inside command bar, keyboard focus should not come out of command bar. Keyboard focus should revolve inside command bar itself.

### User Impact:
Users with low vision who zoom the page for better visibility will not understand on which control focus is landing.

### Attachment:
[A11y_Visual Studio Code_HomePage_Resize Text (2).zip](https://github.com/microsoft/vscode-docs/files/6419610/A11y_Visual.Studio.Code_HomePage_Resize.Text.2.zip)

**Comment by kalpanah1** [comment]
# Closed;
Verified the issue in the below environment. The issue is fixed adding the attachment for reference.
[Bug_4514_Fixed.zip](https://github.com/microsoft/vscode-docs/files/10696718/Bug_4514_Fixed.zip)
