### ISSUE TITLE
Example - Debuggers: explain relation between Debug Adapters and Extension

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docs#452]
The chapter 'Example - Debuggers' seems to convey the message that Debug Extensions are very different from other extensions because they use debug adapters.

An introduction should be added to 'Example - Debuggers' that shows the 'whole picture' of a Debug extension. It should make clear the relation between the extension and the debug adapter: The extension can be used in limited ways (currently) for additional functionality like command, or process pickers but the debugger default implementation lives completely in VS Code and it is not possible to change this in the extension. This is different than the relation between an extension and a language server.

**Comment by octref** [comment]
You have fixed the issue yourself in the updated [Debugger Extension](https://vscode-ext-docs.azurewebsites.net/api/extension-guides/debugger-extension) topic 😉
