### ISSUE TITLE
Rust in Visual Studio Code

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-docs#4531]
Due to recent events and the growing popularity of **Rust**, I thought it would be worth adding **Rust** to **VSCode** documentation in the **Languages** ​​category.
As there are also **Rust** and **VSCode** tutorials in **Microsoft Learn**, it would make great sense to add **Rust** to the official documentation. What do you think about it? 
I am waiting for a response 😊

**Comment by harshit-dugar** [comment]
Hi 
I would like to contribute in this issue . Please allow me to contribute in this doc-enhancement as it is my first contribution to open source

**Comment by harshit-dugar** [comment]
Can anyone please tell do I have to add contentId in the rust.md file . If yes what will be that.

**Comment by gregvanl** [comment]
https://code.visualstudio.com/docs/languages/rust
