### ISSUE TITLE
Hi, participators, I have ever started a project for making a Chinese version of the docs and please help

### ISSUE THREAD

**Issue by CherryMill** [Microsoft/vscode-docs#454]
Thanks to Microsoft, I have ever found a great tool under the GUI.
But in China, few people may use this powerful tool because of the language, the same situation has happened in Linux for decades.
So I have ever started a project for making a Chinese version of the docs and really need your help, please help me to correct the mistakes and contribute something to make it better and quicker.

Wating for your help: VSCode-Docs-Chiness
https://github.com/CherryMill/VSCode-Docs-Chiness

**Comment by gregvanl** [comment]
The VS Code team has no plans at this point to create a localized version of the website.
Thank you for your interest and good luck with your project.
