### ISSUE TITLE
my console is not running the python code

### ISSUE THREAD

**Issue by gigilinostrich** [microsoft/vscode-docs#4546]
Hello. I just installed vs code along with python latest interpreter and extension. I tried to get the console to print "hello word", but all it printed me are file paths. Please help! Here are the screenshots

![image](https://user-images.githubusercontent.com/74795941/118067668-a28b3400-b366-11eb-83aa-4b08dad600db.png)

**Comment by gregvanl** [comment]
Hi @gigilinostrich Can you share the contents of your launch.json file? 

@luabud Can you help out while Josh is on vacation?

**Comment by gigilinostrich** [comment]
nevermind... It turned out that I used a wrong interpreter. Thanks for your reply!

**Comment by yaxye8123** [comment]
You can use the chrome insert or you can use also powershell
