### ISSUE TITLE
window.restoreFullscreen doesn't work in Workspace settings

### ISSUE THREAD

**Issue by JVimes** [Microsoft/vscode-docs#455]
`"window.restoreFullscreen": true` works great in User Settings, but doesn't have any affect in Workspace Settings.

Repro steps:

1. Make sure `"window.restoreFullscreen": true` is set in Workspace Settings and not in User Settings.
2. Run "Reload Window" to make sure the new setting is active.
3. Go full screen.
4. Close and reopen the app.

_Actual_: Window opens not in full screen.
_Expected_: Window opens in full screen.

I'm on:
* Windows 10
* VSCode 1.3.0-insiders

**Comment by gregvanl** [comment]
This is a product issue so moved to https://github.com/Microsoft/vscode/issues/8772

**Comment by JVimes** [comment]
Oops. Thanks @gregvanl!
