### ISSUE TITLE
Remote container docs: Demo code for adding a user will destroy sudoers file  

### ISSUE THREAD

**Issue by hegerdes** [microsoft/vscode-docs#4555]
The docs for adding a non-root user to your dev container suggests the following:

```Dockerfile
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
```

This will override and destroy the sudoers file. Use ">>" to append to the file instead of replacing it.

**Comment by gregvanl** [comment]
This code block is creating a new file under the /etc/sudoers.d folder in the container so I think using the single pipe character is fine. It shouldn't destroy the shared /etc/sudoers file.
https://linuxize.com/post/how-to-add-user-to-sudoers-in-ubuntu/ follows the same approach for creating a new user file.
