### ISSUE TITLE
Doc on Lambda debugging with VS Code

### ISSUE THREAD

**Issue by jayair** [microsoft/vscode-docs#4561]
Hi all,

Appreciate all the hard work with VS Code!

I'm one of the creators of [SST](https://github.com/serverless-stack/serverless-stack), a framework for building serverless apps. We created a way for folks to debug and set breakpoints in their Lambda functions using VS Code. You can see it in action:

https://www.youtube.com/watch?v=2w4A06IsBlU

Would you be open to me submitting a PR adding how to set this up here — https://code.visualstudio.com/docs/nodejs/nodejs-debugging.

Let me know and I can submit one.

Thank you!

**Comment by gregvanl** [comment]
Hi @jayair Thanks for reaching out. Maybe this might be better as a debugging recipe? We have a repo with a collection of small projects to serve as debugging recipes at https://github.com/microsoft/vscode-recipes.
We could then add a mention and pointer in https://code.visualstudio.com/docs/nodejs/debugging-recipes.
What do you think?

**Comment by jayair** [comment]
@gregvanl That makes a lot of sense!

I'll submit a PR to that repo and them submit a PR to that doc?

**Comment by jayair** [comment]
Awesome, here they are:

- Recipe repo https://github.com/microsoft/vscode-recipes/pull/299
- Docs repo https://github.com/microsoft/vscode-docs/pull/4570

Let me know if you want something changed.

**Comment by gregvanl** [comment]
@jayair Great! I've asked a VS Code engineer to review the debugging recipe. Once that's merged, I'll merge and publish the doc update.

**Comment by jayair** [comment]
Thanks!

**Comment by gregvanl** [comment]
All related PRs merged and published.
