### ISSUE TITLE
Download linkage is broken for June 2016 (version 1.3)

### ISSUE THREAD

**Issue by wangbourne** [Microsoft/vscode-docs#457]
Download linkage is broken in this site: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/June_2016.md.

**Comment by gregvanl** [comment]
Thanks for reporting this. These links are just placeholders until we actually release the June milestone build.  They will be updated once the release goes live.

**Comment by gregvanl** [comment]
@wangbourne The download links on the release notes should be good now.
