### ISSUE TITLE
Python docs for "Create a Django app" lists keyboard shortcut as "unassigned"

### ISSUE THREAD

**Issue by kerbrek** [microsoft/vscode-docs#4578]
https://code.visualstudio.com/docs/python/tutorial-django#_create-a-django-app

![Screenshot from 2021-05-29 20-35-53](https://user-images.githubusercontent.com/7583917/120081426-e77ccd80-c0bd-11eb-8926-f0414fbbe8ec.png)

**Comment by gregvanl** [comment]
Hi @kerbrek Thank you for pointing this out. It appears that that VS Code doesn't include the Save All command on Linux so no keybinding is found.
Can you confirm that you see the unassigned keybinding when viewing the documentation on Linux?

**Comment by kerbrek** [comment]
Yes, I'm on Linux (Ubuntu).
