### ISSUE TITLE
Missing f-string prefix in Python Django Tutorial

### ISSUE THREAD

**Issue by kerbrek** [microsoft/vscode-docs#4581]
https://code.visualstudio.com/docs/python/tutorial-django#_define-models
String in line
`        return "'{self.message}' logged on {date.strftime('%A, %d %B, %Y at %X')}"`
must be prefixed with `f`.

[microsoft/python-sample-vscode-django-tutorial/blob/master/hello/models.py#L11](https://github.com/microsoft/python-sample-vscode-django-tutorial/blob/master/hello/models.py#L11) is OK.

**Comment by JoshuaPartlow** [comment]
Thanks @kerbrek for noting the issue and opening a PR. PR is now merged.
