### ISSUE TITLE
cursorMove command doc missing nextBlankLine and prevBlankLine values for `to` argument

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode-docs#4583]
The built-in command documentation for `cursorMove` does not include the recently added `to` values:

`nextBlankLine`
`prevBlankLine`

See https://code.visualstudio.com/api/references/commands

Implemented here:  https://github.com/microsoft/vscode/blob/12808be8383305bd6bb307f20ff25339f2c2d269/src/vs/editor/common/controller/cursorMoveCommands.ts

**Comment by gregvanl** [comment]
Thanks for pointing this out!
