### ISSUE TITLE
Should update the terminal docs

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-docs#4586]
Testing microsoft/vscode#124836

While testing this issue I noticed that the documentation is still referring to deprecated settings, pls see:
https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows

**Comment by Tyriar** [comment]
:+1: we can also auto detect the profile now which we can do for June since the validation is a little different to the existing ones https://github.com/microsoft/vscode/issues/125387
