### ISSUE TITLE
Translating to Russian language

### ISSUE THREAD

**Issue by Hkr32** [microsoft/vscode-docs#4594]
Where can I get a website to translate docs into Russian?

**Comment by gregvanl** [comment]
Hi @Hkr32,
The VS Code website is currently only available in English. 
You can track localization of the website in issue https://github.com/microsoft/vscode-docs/issues/3260.

**Comment by Hkr32** [comment]
@gregvanl,
I need a website, you have documentation in this repository. I would translate it myself and put it on my domain, is this possible?

**Comment by gregvanl** [comment]
Hi @Hkr32 Sure, the VS Code documentation is open-source so you can use it. 
I believe there are some community sites around that translate the content to Japanese and Chinese. 
The VS Code teams doesn't work directly to translate the content but also doesn't stop people from translating the docs for their own use.
Our website infrastructure supporting code.visualstudio.com is not public so you would need to create our own site.
