### ISSUE TITLE
Request to make older versions (zip, no-admin) install available

### ISSUE THREAD

**Issue by sdlins** [microsoft/vscode-docs#4609]
I posted my question at Stackoverflow, but, there are already other question exactly like this over there since Feb 20, **2017** with no answer! So, it is definitely a *BUG* if you see by an user point view!

Please see it [here](https://stackoverflow.com/questions/42353255/how-to-download-older-version-of-vscode-portable) and mine [here](https://stackoverflow.com/questions/52810019/where-we-can-get-older-versions-of-vscode-like-1-25-in-zip-format).

I just cant see **why** MS dont use coherency in somethings. If a new VSCode is launched, it is made available in Source Code, Portable and Exe formats. But if we need an older version, only Source Code and Exe is available? Is there **any** logic on it?

Just to make it clear: I love VSCode. I just dont love MS. But I need it for Win64 because I have to use it in my work where I dont have admin privileges. (Linux at home).

Thank you.

**Comment by gregvanl** [comment]
Download page https://code.visualstudio.com/download now has a link "Get previous versions", which points to https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions.
The URLs to each download are provided there.
