### ISSUE TITLE
Copy / Paste from remote

### ISSUE THREAD

**Issue by vkubicki** [microsoft/vscode-docs#4616]
I open two instances of vscode, one as a remote host (SSH in my case), and a second one as a local session. I would like to be able to copy / paste folders between them. Currently, I must right click to download on the local computer, then move the files using the explorer. Can this be done transparently through copy / paste inside vscode, without resorting to using the OS interface ?

**Comment by gregvanl** [comment]
Hi @vkubicki I don't believe this is currently possible but there is an open issue discussing the possibility https://github.com/microsoft/vscode-remote/issues/640.

**Comment by vkubicki** [comment]
Thank you.
