### ISSUE TITLE
missing step in macos installation instructions

### ISSUE THREAD

**Issue by sndik16** [microsoft/vscode-docs#4617]
The installation instructions should have a step to unzip the .zip file that has been downloaded before "Drag Visual Studio Code.app to the Applications folder, making it available in the macOS Launchpad.". 

Installation#
Download Visual Studio Code for macOS.
Open the browser's download list and locate the downloaded archive.
Select the 'magnifying glass' icon to open the archive in Finder.
Drag Visual Studio Code.app to the Applications folder, making it available in the macOS Launchpad.
Add VS Code to your Dock by right-clicking on the icon to bring up the context menu and choosing Options, Keep in Dock.

**Comment by gregvanl** [comment]
Hi @sndik16 Thank you for entering an issue and your interest in the VS Code documentation.
When I install VS Code on a Mac, I don't see that a manual unzipping is required. The current steps documented work for me.
I do sometimes see a progress message indicating that the install is unzipping. Perhaps you just need to wait longer before selecting the magnifying glass?
I am on Big Sur version 11.4.
