### ISSUE TITLE
add a hlink to the download page for history version

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-docs#4624]
consider add the link `https://code.visualstudio.com/docs/supporting/FAQ#_previous-release-versions` to the downloads page:
https://code.visualstudio.com/#alt-downloads so that users can quickly find the way to downloads

![image](https://user-images.githubusercontent.com/1876302/122494279-a8d29700-d01b-11eb-94b4-da5d36926b83.png)

**Comment by gregvanl** [comment]
Good suggestion. Added to /download page.

![image](https://user-images.githubusercontent.com/12818376/129642124-2c3adf92-f6c3-48e5-befd-03e0b16a7a2b.png)
