### ISSUE TITLE
FAQ Section removed still referenced in latest version

### ISSUE THREAD

**Issue by lantrix** [microsoft/vscode-docs#4629]
A change to remove this section of the FAQ (2c4c72b3215e5081d1ec241a30eb9c056c9c612b ) was recently made.
However this is still linked to in current version of VSCode (`v1.57.1`) but now it links to nothing.

```
[2021-06-22 18:59:12.420] [main] [warning] Resolving your shell environment is taking more than 10s. Please review your shell configuration. Learn more at https://go.microsoft.com/fwlink/?linkid=2149667.
```

That link resolves to the now removed FAQ section. Not a good experience when this occurs.

**Comment by gregvanl** [comment]
Hi @lantrix Thanks for pointing this out. We did remove the FAQ section too early.
The next 1.58 release will remove the message and link entirely https://github.com/microsoft/vscode/commit/eaf29b7e243ca5d68c8cb472f82de6be7e777390 but we'll add it back until the next release goes out.
