### ISSUE TITLE
I cannot find OpenSettings.json in VScode

### ISSUE THREAD

**Issue by Eyeslipper** [microsoft/vscode-docs#4648]
Hi I'm trying to create a python development workspace and I am extremely new to coding and have 0 experience. I have been reading this book called "coding for dummies" and in the book it says that you need to click on the 3 dots in the top right corner of the screen. Then there will be an option that says opensettings.json. I can't find this and I have been looking everywhere for it and still cant find it. 
Also I have looked on youtube however the videos are poorly explained and they just cause more frustration.

**Comment by gregvanl** [comment]
Hi @Eyeslipper I'm not familiar with the book you mention. Is it specific to VS Code?
If you want to change VS Code user settings you can use the File > Preferences > Settings command (Code > Preferences > Settings on macOS) and that will open the Settings editor UI.
If you want to open the underlying `setttings.json` file you can use the  Preferences: Open Settings (JSON) from the Command Palette.
You might try starting with the VS Code documentation on settings at https://code.visualstudio.com/docs/getstarted/settings or watch the intro videos at https://code.visualstudio.com/docs/getstarted/introvideos

**Comment by gregvanl** [comment]
No response from user. Closing

**Comment by prakheneur** [comment]
@gregvanl Open settings(json) is not there

**Comment by gregvanl** [comment]
@prakheneur The command is now called "Open User Settings (JSON)"
![image](https://github.com/microsoft/vscode-docs/assets/12818376/ef0466fc-08e4-4648-ad1d-3ba91a0bd1a4)
