### ISSUE TITLE
alphabetize topics in Contribution Points?

### ISSUE THREAD

**Issue by boneskull** [microsoft/vscode-docs#4671]
I'd love it if the [contribution points](https://code.visualstudio.com/api/references/contribution-points) were sorted alphabetically.  Currently, it is exceedingly difficult to scan the sidebar ("In This Article"...) and find what I'm looking for. The list does not seem to be in any sort of obvious order.

If this is OK to change, I can send a PR to do so.

**Comment by gregvanl** [comment]
Hi @boneskull It has gotten out of hand and a PR would be great.

**Comment by gregvanl** [comment]
Hi @boneskull Such a good suggestion, I couldn't wait. Thanks for pointing this out!

**Comment by boneskull** [comment]
ty, sorry couldn't get to it
