### ISSUE TITLE
Ambiguous jsconfig options docs

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-docs#4676]
https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options states e.g.

> Tip: Do not be confused by compilerOptions. This attribute exists because jsconfig.json is a descendant of tsconfig.json, which is used for compiling TypeScript.

> target: Specifies which default library (lib.d.ts) to use
> module: Specifies the module system, when generating module code.

As the configs described on this page is mostly for the config of getting IntelliSense in VS Code, the `target` describes this good. In a Typescript world `target` would mostly mean which JavaScript version to transpile to. But for `module` it says "generating module code" which is not what is done when just using the `jsconfig.json` file for IntelliSense in VS Code. So these two descriptions differ in that regard.

I merely wonder if this cannot/should not be improved?

**Comment by gregvanl** [comment]
@thernstig Thanks for pointing out the confusion. Added more clarification for the tsconfig.json compilerOptions.
