### ISSUE TITLE
1.58 release notes - one GIF too low res

### ISSUE THREAD

**Issue by JohnVeness** [microsoft/vscode-docs#4678]
Hi. In the release notes for 1.58 (https://code.visualstudio.com/updates/v1_58#_contributions-to-extensions) in the section about Live Preview, screenshot [live-preview-summary-2.gif](https://media.githubusercontent.com/media/microsoft/vscode-docs/main/release-notes/images/1_58/live-preview-summary-2.gif) is considerably lower res than screenshot [live-preview-summary-1.gif](https://media.githubusercontent.com/media/microsoft/vscode-docs/main/release-notes/images/1_58/live-preview-summary-1.gif), making the former blurry/pixelated.

**Comment by gregvanl** [comment]
Hi @JohnVeness Thanks for creating an issue and your interest in the VS Code documentation. I agree that the second .gif is blurry but it still (hopefully) showcases the feature. Given that people can learn more in the extension's repo README, which has more short videos, I don't think we'll fix this. 
https://github.com/microsoft/vscode-livepreview#persistent-server-task-with-server-logging
