### ISSUE TITLE
Document more usages of Product Icons for extensions

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode-docs#4680]
I could not find anything in the [Product Icon Reference](https://code.visualstudio.com/api/references/icons-in-labels) or in the [Contribution Points](https://code.visualstudio.com/api/references/contribution-points) about using Product Icons in the contribution points. The main issue for this was microsoft/vscode#84695 and it was documented in the [release notes](https://code.visualstudio.com/updates/v1_42#_codicons-for-reuse) for commands only at the time.

**Comment by gregvanl** [comment]
https://code.visualstudio.com/api/references/contribution-points#contributes.commands now mentions icons

**Comment by KamasamaK** [comment]
Thanks. It should be noted everywhere that it can be used, though. For example, also with https://code.visualstudio.com/api/references/contribution-points#contributes.views.
