### ISSUE TITLE
How not pop a window for signing in Github 

### ISSUE THREAD

**Issue by KringMiao** [microsoft/vscode-docs#4682]
Hello, I forgrt when I enable the Gihub sign in, but now I want to close the poopups when I use thw VS Code every time.So I want to get your help about how not pop this window when I use the VS Code.I will upload the screenshot, and my VS Code version is 1.58.1.
![Snipaste_2021-07-15_22-37-17](https://user-images.githubusercontent.com/45806121/125809604-80545ff2-b218-4cc4-9bf3-7a1858964faa.png)

**Comment by KringMiao** [comment]
Oh，I almost forget.Thank you! Please excuse my poor english.

**Comment by gregvanl** [comment]
Hi @KringMiao Can you try the workflow with extensions disabled by launching VS Code with the `--disable-extensions` flag. I wonder if this might be happening due to a specific extension.
Can you also list which extensions you have installed?

**Comment by KringMiao** [comment]
Sorry, @gregvanl Back to you so late.These screenshots are the extensions which are using in my VS Code.And these days, I tried to reinstall the VS Code, and now it doesn`t pop the view of Github Sign up, so maybe I allow some settind when I used.Thanks for your helping, but I can`t remenber what I allowed.Thank you kindly.
![image](https://user-images.githubusercontent.com/45806121/126521742-0573980b-c9d3-4875-b752-a97bd1c66e8c.png)
![image](https://user-images.githubusercontent.com/45806121/126521788-f717bd20-331b-41f1-bc03-13c61cce0ad2.png)

**Comment by gregvanl** [comment]
@KringMiao Glad to hear that you are unblocked. Closing this issue but feel free to reopen if the issue reappears.
