### ISSUE TITLE
document using setKeysForSync in remote development

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-docs#4699]
In Gitpod we see many extensions are showing annoying webviews on start of a new machine: https://github.com/gitpod-io/gitpod/issues/4566 I believe it should be the same in Codespaces.

Usual issue that extensions do check previous version from the global state, but such key is not marked as sync.

It would be good to document such pattern in https://code.visualstudio.com/api/advanced-topics/remote-extensions#persisting-extension-data-or-state One could then reach out to extension devs to fix it.

**Comment by sandy081** [comment]
@akosyakov Thanks for coming up with a sample for how to sync global state by extensions. We would collect all such samples in our [vscode-extension-samples](http://github.com/microsoft/vscode-extension-samples) repo. 

We already documented about `setKeysForSync` api in our doc here - https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage. This is the appropriate place as it talks about data storage APIs.

I would suggest to move and create this sample in our sample repo and refer this sample from the above doc.
