### ISSUE TITLE
[How-to] Change Product Icons color

### ISSUE THREAD

**Issue by shariquekhan1997** [microsoft/vscode-docs#4709]
We have known vs-code for many great features, one of which is everything can be customized.

But, I haven't found anything regarding product-icon-color, I want to change the colors of vs-code-icons.

I have checked [Product Icon Reference](https://code.visualstudio.com/api/references/icons-in-labels)

**Comment by gregvanl** [comment]
Hi @shariquekhan1997 If you want to change the color of a codicon in your extension you can use ThemeIcon.

https://code.visualstudio.com/api/references/vscode-api#ThemeIcon

**Comment by gregvanl** [comment]
Believe user's question was answered. No reply back.
