### ISSUE TITLE
DataScience docs point to the wrong notebook UI for the overview page

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-docs#4711]
https://code.visualstudio.com/docs/datascience/overview

The first picture on that page is incorrect. It's showing the old webview UI.

**Comment by tanhakabir** [comment]
Similar to this too https://github.com/microsoft/vscode-docs/issues/4719

**Comment by joyceerhl** [comment]
Fixed via https://github.com/microsoft/vscode-docs/commit/7587945be143ddb790366d546ca4686a128f7d68
