### ISSUE TITLE
VSCode: settings.json file is not recognizing a terminal.integrated setting

### ISSUE THREAD

**Issue by afogarty85** [microsoft/vscode-docs#4717]
Why is this entry not recognized by VSCode? I have a very slow terminal output that I am hoping this will help fix:

`"terminal.integrated.rendererType": "experimentalWebgl"`

The above command is known to exist, here: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md

Here is my settings.json file:

```
{
    "atomKeymap.promptV3Features": true,
    "editor.formatOnPaste": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "python.pythonPath": "C:\\Users\\Andrew\\Anaconda3",
    "workbench.colorTheme": "Visual Studio Dark",
   "terminal.integrated.rendererType": "experimentalWebgl",  # grey'd out assuming its not a real command
    "workbench.iconTheme": "Monokai Pro Icons",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "python.defaultInterpreterPath": "C:\\Users\\Andrew\\Anaconda3",
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "debug.javascript.pickAndAttachOptions": {
    
    },
    "workbench.colorCustomizations": {
    
    }
}
```

**Comment by gregvanl** [comment]
Hi @afogarty85 I think this setting was recently replaced with the `terminal.integrated.gpuAcceleration` `canvas` value. 

See https://code.visualstudio.com/updates/v1_58#_explicitly-setting-canvas-renderer

**Comment by afogarty85** [comment]
Ah thanks so much for the find! I gave it a try but unfortunately has not settled my slow terminal output in VSCode. I will keep looking along this route now!

**Comment by gregvanl** [comment]
Hope you can find a solution. Closing this issue since I don't think it is a documentation issue.
