### ISSUE TITLE
Tabs images in release notes are blurry

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#473]
The tabs image looks very poor.

Chrome
![image](https://cloud.githubusercontent.com/assets/2449568/16928105/c43259e0-4ce5-11e6-8f12-e7e77b1c1f5c.png)

Better on Firefox and Safari, but still hard to read. 

Firefox
![image](https://cloud.githubusercontent.com/assets/2449568/16928124/dfa723e0-4ce5-11e6-9339-ed9dd4918681.png)

Safari
![image](https://cloud.githubusercontent.com/assets/2449568/16928140/f04ea02e-4ce5-11e6-8eb6-b6c845df00f3.png)

**Comment by Tyriar** [comment]
The image is too wide (1108px) for its container (617px).

**Comment by waderyan** [comment]
Another one from release notes. 

![image](https://cloud.githubusercontent.com/assets/2449568/16928263/94cf0e22-4ce6-11e6-9e73-cc3f274ab3f8.png)

**Comment by waderyan** [comment]
![image](https://cloud.githubusercontent.com/assets/2449568/16928393/39889d02-4ce7-11e6-9ef7-2736f8a21709.png)

**Comment by gregvanl** [comment]
Refers to June_2016 release notes which probably has low readership at this point.
