### ISSUE TITLE
can not find the keybinding in shortcut pdf ref

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-docs#4743]
vscode has add an new keybinding `ctrl+i` to trigger suggestion，same as `ctrl+space`，but we can‘t find it in the ref of PDF

https://github.com/microsoft/vscode/issues/105207

**Comment by gregvanl** [comment]
Still need to convert to PDF and publish live.

**Comment by gregvanl** [comment]
Published. Good suggestion to add that keybinding. Thanks!
