### ISSUE TITLE
VSCode vebsite still shows wrong info about macOS supported version

### ISSUE THREAD

**Issue by whitebear60** [microsoft/vscode-docs#4746]
[#123752](https://github.com/microsoft/vscode/issues/123752) still persists. On VSCode download page the website still shows that the program is supporting macOS 10.10, however, it does not, the minimum macOS version is 10.11. To be more precise, it shows wrong information [here](https://code.visualstudio.com/insiders/#osx), [here](https://code.visualstudio.com/Download) and [here](https://code.visualstudio.com/#alt-downloads).

**Comment by gregvanl** [comment]
Fixed. Thanks for keeping us honest :-)

**Comment by whitebear60** [comment]
This are places that I have noticed this bug, maybe the macOS version hasn't been updated in some other places that I  haven't found yet...
