### ISSUE TITLE
Update api/get-started/extension-anatomy.md

### ISSUE THREAD

**Issue by 38elements** [microsoft/vscode-docs#4769]
I did the following:
https://github.com/microsoft/vscode-docs/blob/571f43c71798111ec344bb2369179a1fd84c89a5/api/get-started/your-first-extension.md

```
yo code

# ? What type of extension do you want to create? New Extension (TypeScript)
# ? What's the name of your extension? HelloWorld
### Press <Enter> to choose default for all options below ###

# ? What's the identifier of your extension? helloworld
# ? What's the description of your extension? LEAVE BLANK
# ? Initialize a git repository? Yes
# ? Bundle the source code with webpack? No
# ? Which package manager to use? npm

code ./helloworld
```

There is `onCommand:extension.helloWorld` in [extension-anatomy.md](https://github.com/microsoft/vscode-docs/blob/571f43c71798111ec344bb2369179a1fd84c89a5/api/get-started/extension-anatomy.md). But, There is `onCommand:helloworld.helloWorld`, because `vscode-generator-code` is changed.

https://github.com/microsoft/vscode-generator-code/commit/d4f816df58ce1c68bb75945d6887b9755a9b5987#diff-3b83460af49cf83b16b5096f65a55d2f3222a410c7091f68499809df132ae682

**Comment by gregvanl** [comment]
Thanks for pointing this out!

**Comment by 38elements** [comment]
@gregvanl 
Thank you for updating. I created following issue because I feel unsuitable with `onCommand:helloworld.helloWorld`. I think `vscode-generator-code` may want it to be `onCommand:TypeScript.helloWorld`.

https://github.com/microsoft/vscode-generator-code/issues/297
