### ISSUE TITLE
Note in accessibility page that ctrl+m also works in terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#478]
https://github.com/Microsoft/vscode/issues/6731 adds support for ctrl+m to bubble tab/shift+tab up instead of having it consumed by the terminal https://code.visualstudio.com/docs/editor/accessibility#_tab-trapping

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/402fe34fe7b470c76850abf868c27b1558c6e341
