### ISSUE TITLE
Add a section for the R Extension for VS Code

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-docs#4784]
Inspired by the [announcement](https://twitter.com/OfficialLoganK/status/1431360850665918465) where [Julia](https://code.visualstudio.com/docs/languages/julia) is added as a section in the VS Code documentation as discussed in #4767, I would like to ask if a page for the R programming language could be added too? If so, it would be nice to see that all three major languages for data science supported in Jupyter appear in the same place.

The following extensions will be mentioned:

* [vscode-R](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r): Interacting with R sessions, language server, data/plot/widget/help/workspace viewer, R Markdown, etc.
* [R-Debugger](https://marketplace.visualstudio.com/items?itemName=RDebugger.r-debugger): Debugging R file and R package.

I would be glad to submit a PR similar to #4770.

**Comment by gregvanl** [comment]
Hi @renkun-ken We would be happy to have an R language topic under /docs/languages. Feel free to submit a PR and reach out if you have questions.
We can also look into providing either a section in the Jupyter documentation about the various language options or a new topic outlining how to configure languages.

**Comment by renkun-ken** [comment]
Thanks for getting back! I'll put up a PR soon.

**Comment by renkun-ken** [comment]
@gregvanl @rjmolyneaux 

I submit a PR to add the section of R extension. Please feel free to suggest or modify.
