### ISSUE TITLE
Feature Request: More Clear Information on Custom Intellisense Extensions in API Docs

### ISSUE THREAD

**Issue by Password-Classified** [microsoft/vscode-docs#4795]
I have been creating VS Code extensions, and have been loving ❤ using the JavaScript API. Unfortunately, I have run into a problem when attempting to create my own custom language extension. I can't seem to find any clear documentation on creating custom Intellisense 💡 or Hover Providers. I have been confused at some of the documentation 📖 and I can't find any clear examples. Any ideas, sources of information on this etc..?

**Comment by gregvanl** [comment]
Hi @Password-Classified Have you looked at https://code.visualstudio.com/api/language-extensions/programmatic-language-features and https://code.visualstudio.com/api/language-extensions/language-server-extension-guide?
I believe these topics provide documentation on CodeActions providers (light bulb) and hover providers. 
There are also many samples at https://github.com/microsoft/vscode-extension-samples.

**Comment by Password-Classified** [comment]
Thanks, I am just looking now.

**Comment by Password-Classified** [comment]
I think those links just about cover all of it. Thanks!
