### ISSUE TITLE
PHP docs need to be improved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#4800]
https://code.visualstudio.com/docs/languages/php

As mentioned by @zobo the author of php-debug extension our php docs need to be improved
Currently PHP users are hitting a lot of issues while setting up php on VS Code and none of this is documented.

@zobo could you let us know what those exact issues are? So we could work on improving the docs.

**Comment by gregvanl** [comment]
Closing older issue but PRs updating the PHP document are welcome.
