### ISSUE TITLE
Incorrect syntax for update-alternatives

### ISSUE THREAD

**Issue by Suven-p** [microsoft/vscode-docs#4804]
In the [debian-alternatives-system section](https://github.com/microsoft/vscode-docs/blob/main/docs/setup/linux.md#debian-alternatives-system) , the syntax for [update-alternatives](https://linux.die.net/man/8/update-alternatives) seems to be wrong. It should be `sudo update-alternatives --install /usr/bin/editor editor $(which code) 10` instead of `sudo update-alternatives --install editor /usr/bin/editor $(which code)`. Priority of 10 chosen randomly for manual mode.
The current syntax gives error on ubuntu 21.04:
`update-alternatives: --install needs <link> <name> <path> <priority>`

**Comment by gregvanl** [comment]
Thanks for pointing this out!
