### ISSUE TITLE
Trying to configure a debugger for C++ in Visual Studio Code

### ISSUE THREAD

**Issue by SkylerMime** [microsoft/vscode-docs#4810]
I'm a college student just starting off learning C++ and using Visual Studio Code. I'm having trouble figuring out how to debug the code, and I've been getting errors.

So far I've tried to follow these tutorials/documentation:
[C/C++ for Visual Studio Code](https://code.visualstudio.com/docs/languages/cpp)
[Using Clang in Visual Studio Code](https://code.visualstudio.com/docs/cpp/config-clang-mac)
[Debug C++ in Visual Studio Code](https://code.visualstudio.com/docs/cpp/cpp-debug)
[Configuring C/C++ debugging](https://code.visualstudio.com/docs/cpp/launch-json-reference)

I'm on macOS Big Sur, 11.5.2. I've installed xcode and the "C/C++" extension by Microsoft. I also accidentally had the extension "C/C++ Runner" by franneck94 installed for a while, but I uninstalled it in case it was causing me problems.

Currently the only way I can successfully run programs is by using a direct terminal command, e.g. `./helloworld`. If I try to use the "Start Debugging" or "Run Without Debugging" options from the Run menu, the program doesn't seem to output anywhere. It opens up two integrated terminals without any output and provides some information in the debug console, as seen in these pictures:

![image](https://user-images.githubusercontent.com/89657777/132067623-c514d10e-512d-4de4-bae2-bdc5d42798ea.png)

![image](https://user-images.githubusercontent.com/89657777/132067661-76eb7fa9-2962-4ff7-9fe8-cd9d3cb8a09a.png)

![image](https://user-images.githubusercontent.com/89657777/132067719-07b89bb4-c73d-432a-a7d3-31900e10bdb6.png)

There is also no place for me to put input into the program if asked.

But as I mentioned before, using `./helloworld` will run the program without issues:

![image](https://user-images.githubusercontent.com/89657777/132067802-c57bbbf8-ca50-4584-ba7f-8fb53698b6a7.png)

I'm a complete beginner, so I'm sure there's probably a simple fix I'm missing, but I'm not sure what else to try. Maybe I need to reconfigure the launch.json and task.json files??

Thanks in advance for the help,
Skyler

**Comment by gregvanl** [comment]
Hi @SkylerMime Are you able to set a breakpoint in the Hello World program and have the debugger stop on that line?
https://code.visualstudio.com/docs/editor/debugging#_breakpoints

**Comment by SkylerMime** [comment]
Hi gregvanl, that makes things a little better. When I run the debugger now, it stops on the breakpoint line and I can step through like I should! I also made stopAtEntry "true" in the launch.json file so that it does that automatically when it enters the main() function.

Unfortunately, I'm still not sure how to get it to run in a terminal or allow it to receive input while debugging. I tried changing the launch.json file to make externalConsole "true," and now a new terminal window opens in the background while I'm debugging. Unfortunately, this new terminal doesn't seem to respond to commands or do anything.

Here's my current launch.json file:
<img width="1257" alt="Screen Shot 2021-09-08 at 2 37 19 PM" src="https://user-images.githubusercontent.com/89657777/132589084-8031b618-524d-451d-87c6-a3bac836b139.png">

Here's what the debugging process looks like now:
<img width="1409" alt="Screen Shot 2021-09-08 at 2 40 21 PM" src="https://user-images.githubusercontent.com/89657777/132589375-9d5f6e2f-c211-4d51-a9a5-84e0a469cb7c.png">

**Comment by gregvanl** [comment]
It looks like running in the integrated terminal or taking user input might not be supported on macOS.
If I go to https://code.visualstudio.com/docs/cpp/cpp-debug and go to the Configuring C/C++ debugging link https://code.visualstudio.com/docs/cpp/launch-json-reference, the documentation for externalConsole at https://code.visualstudio.com/docs/cpp/launch-json-reference#_externalconsole says: 
"macOS: When set to true, it will spawn an external console through lldb-mi. When set to false, the output can be seen in VS Code's debugConsole. Due to limitations within lldb-mi, integratedTerminal support is not available."
You might want to reach out to the C++ extension authors at https://github.com/microsoft/vscode-cpptools. Looking at some of the issues there, you might be running into https://github.com/microsoft/vscode-cpptools/issues/6715

**Comment by gregvanl** [comment]
I also see that there is a mention of this issue in the Troubleshooting section.
https://code.visualstudio.com/docs/cpp/config-clang-mac#_terminal-wont-launch-for-input
There is a workaround but I haven't tried it.

**Comment by SkylerMime** [comment]
Thanks for the links! The workaround didn't completely fix the issue for me (I still don't have a way to put in input), so I'll see if the extension authors have any other workarounds.

**Comment by jureid** [comment]
@WardenGnaw - can you confirm that we don't support entering input during a debug session on macOS Big Sur? If that's the case, do you know why the [workaround mentioned in our docs](https://code.visualstudio.com/docs/cpp/config-clang-mac#_terminal-wont-launch-for-input) isn't working for @SkylerMime? Also, what are the challenges in supporting input for macOS?

**Comment by WardenGnaw** [comment]
That workaround was for the migration from Mojave to Big Sur. 

There is a [pinned issue](https://github.com/microsoft/vscode-cpptools/issues/8075) for v1.6.0 about issues with external window.

The workaround for this is using v1.5.1 until we release an update.

**Comment by gregvanl** [comment]
Closing as this is an extension issue and not a documentation issue.
To install a specific version of an extension, you can use the "Extensions: Install Specific Version of Extension..." command from the Command Palette. The command displays a dropdown with your installed extensions and lets you select a specific version after selecting an extension.
