### ISSUE TITLE
Please provide more details on how to prevent autoupdates on linux or else have the same setting that works on MacOS and Windows

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode-docs#4811]
Please provide more documentation on how to prevent autoupdates of VSCode on Linux platforms. The current documentation available at https://code.visualstudio.com/docs/supporting/FAQ does indicate that there is a setting in `settings.json` ( "update.mode": "none" )which the user can set to prevent updates, but that it only works on MacOS and Windows. If possible, please do provide the same option for disabling autoupdates on Linux as well. 

Linux specific document available at https://code.visualstudio.com/docs/setup/linux lets the user fend for himself when it says:

`If the VS Code repository was installed correctly, then your system package manager should handle auto-updating in the same way as other packages on the system.
`

I came into work this morning and lo and behold VSCode has autoupdated itself to 1.60.0 on Ubuntu 20.10 (despite having "update.mode": "none" in the settings.json file on this machine) Now I am trying to figure out how to disable that in the future specifically for Linux machines. I installed VSCode on this machine via the "Ubuntu Software" app. Images of that app on my machine are available https://imgur.com/8abmR6O and https://imgur.com/plp34tv . You may notice that there is no option to right click and disable auto updates for this specific app. I have raised this query on askubuntu forum as well.  I will update this thread if I get any resolution there.

Please do try to provide as uniform an interface as possible across MacOS, Windows and Linux.

Thank you for all your efforts in maintaining and continuing to develop this tool.

**Comment by gregvanl** [comment]
Closing as this doesn't seem like a documentation issue but more like a feature request. You can open product feature requests on the VS Code product repo at https://github.com/microsoft/vscode/issues
As explained above, different Linux package managers have different update behaviors so a universal Linux solution may not be possible.
