### ISSUE TITLE
how to run javascript

### ISSUE THREAD

**Issue by DharshithHari** [microsoft/vscode-docs#4812]

**Comment by gregvanl** [comment]
Hi @DharshithHari Can you provide more information about what you are trying to do with JavaScript?
For example, you can run JavaScript directly with the Node.js runtime or maybe you are running JS from an HTML page.
You can find information about the Node.js runtime and VS Code's support for running and debugging Node.js applications at https://code.visualstudio.com/docs/nodejs/nodejs-tutorial.
There is also a general Working with JavaScript topic at https://code.visualstudio.com/docs/nodejs/working-with-javascript.
There are also several tutorials on using JavaScript web frameworks such as Angular, React, Vue.js, and Ember. https://code.visualstudio.com/docs/nodejs/angular-tutorial

**Comment by gregvanl** [comment]
Closing as no response from user.
