### ISSUE TITLE
August changelog mentions the wrong theme

### ISSUE THREAD

**Issue by iamart** [microsoft/vscode-docs#4819]
I like the theme used in the first two screencasts of the August changelog but the wrong one is mentioned there, it does not seem to be the Panda Theme. Can we find the dev creating those animated screencasts to enlighten about the actual theme used?

**Comment by gregvanl** [comment]
Hi @iamart, I checked with the engineer, who created the .gifs, and they confirmed that they were using Panda Theme.
Can you explain why you think a different theme was used?

**Comment by iamart** [comment]
@gregvanl thank you for checking that up! Panda theme has more brownish tone to it, it is visible when comparing screencast in the changelog with the screenshot in the marketplace of the theme (or installing).
The changelog screencast is is on a darker side. I guess screencast has some filter applied that affects the colours.

**Comment by gregvanl** [comment]
@iamart I agree with you, the installed extension and Marketplace screen shot background color does look a little more brown.
As you mention, might be something with the .gif creation.
Closing as the engineer has confirmed that he was using Panda Theme.
If you want to make that's theme's background darker, you can override any color for a theme.
```
    "workbench.colorCustomizations": {
        "[Panda Syntax]": {
            "editor.background": "#0f0e0e"
        }
    }
```
