### ISSUE TITLE
Install an extension has a picture of Bracket Pair Colorizer (outdated)

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#4821]
https://code.visualstudio.com/docs/editor/extension-marketplace#_install-an-extension

These docs explain users how to install Extensions. The example is Bracket Pair Colorizer, and this is not a good example since we now have this functionality built in.
Instead I suggest to have an example with GitHub PR extension or Python.

**Comment by gregvanl** [comment]
Yep, we'll need to find another "highly visible" extension for the example.

**Comment by hediet** [comment]
Maybe [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)?

**Comment by gregvanl** [comment]
Not sure about Prettier since it will change the user's source code. 
I liked the Bracket Pair Colorizer since it add the very visible lines connecting the brackets.
I wanted to show an extension that would obviously be working without any setup and also have a light or no touch on source code.

**Comment by habarahonaa** [comment]
Perhaps something like [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)?

**Comment by gregvanl** [comment]
Switch to use the TODO Highlight extension as an example
