### ISSUE TITLE
Move the guide for Virtual Workspaces to the extension author docs

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-docs#4826]
Moving https://github.com/microsoft/vscode/wiki/Virtual-Workspaces to the extension guide docs

**Comment by aeschli** [comment]
Pushed a first version to vnext: https://github.com/microsoft/vscode-docs/blob/vnext/api/extension-guides/virtual-workspaces.md

@gregvanl I think it's good for review and addition the TOC

**Comment by gregvanl** [comment]
Edit pass and add to TOC https://github.com/microsoft/vscode-docs/commit/26ff3c80958f226666de31974688e0d3fe9f40da
