### ISSUE TITLE
IN 【NoteBook: Links between Markdown cells】，example is not working

### ISSUE THREAD

**Issue by feynmanpan** [microsoft/vscode-docs#4829]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version: Win10
https://code.visualstudio.com/updates/v1_60
In example of Link text,
(#_header-slug) should be (#header-slug) without underscore, Thanks

**Comment by mjbvz** [comment]
@gregvanl Looks like this was already fixed and we just need to republish 

![Screen Shot 2021-09-15 at 4 18 17 PM](https://user-images.githubusercontent.com/12821956/133525311-44c33fc0-ea22-4166-b402-84248ea36431.png)

**Comment by phongsit77** [comment]
ในวันที่ พฤ. 16 ก.ย. 2021 เวลา 06:18 Matt Bierner ***@***.***>
เขียนว่า:

**Comment by yaxye8123** [comment]
ok the contact me https://discord.gg/zbNnzU5Y

tor. 16. sep. 2021 kl. 11:19 skrev phongsit77 ***@***.***>:
