### ISSUE TITLE
Add recommendations for location of custom view containers

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-docs#4831]
While building my first extension and reading [this section](https://code.visualstudio.com/api/references/extension-guidelines#view-locations), I am wondering which is the right location to place my custom view container: Should I add it to the activity bar or to the panel on the bottom? Does this merely depend on the layout of the view container's views' contents or is there some general advice? It might be helpful to add a few dos and don'ts for this question to the section linked above.

**Comment by LinqLover** [comment]
Thanks, this explains it from a technical perspective. Nevertheless I think the docs should clarify this to avoid confusion. :-)

**Comment by daviddossett** [comment]
@LinqLover I recently updated the extension UX guidelines and there's actually a bit on View locations here: https://code.visualstudio.com/api/ux-guidelines/panel

> [Don't] Use for Views that are meant to be always visible since users often minimize the Panel

You can actually [add a View Container to the panel](https://code.visualstudio.com/assets/api/ux-guidelines/examples/panel-toolbar-multiple-views.png) now. It looks something like this: 

![panel-toolbar-multiple-views](https://user-images.githubusercontent.com/25163139/172921454-b2298c32-f293-46e9-8634-bc430b93f29a.png)

I'd recommend starting with the activity bar given it's discoverability unless you have a specific reason to use the Panel.

**Comment by LinqLover** [comment]
Thank you very much!
