### ISSUE TITLE
Unity doc : Version of Targeting Pack is outdated

### ISSUE THREAD

**Issue by hydriod** [microsoft/vscode-docs#4832]
https://code.visualstudio.com/docs/other/unity#_enabling-code-completion-for-recent-versions-of-unity

Unity 2018 or later need .NET Framework 4.7.1 Targeting Pack.

**Comment by daxter44** [comment]
@gregvanl Hi, I can't find path 4.7.1 Targeting Pack  to download. Should we put path for [.NET Framework 4.7.1 Developer Pack Offline Installer](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net471-developer-pack-offline-installer) which contain 4.7.1 Targeting Pack ?

**Comment by gregvanl** [comment]
Hi @hydriod @daxter44 @I asked around and consensus was to point people to the 4.7.1 Developer Pack at  https://dotnet.microsoft.com/download/dotnet-framework/net471.
I'll update the topic shortly. Thanks!
