### ISSUE TITLE
Chinese Locale Names

### ISSUE THREAD

**Issue by clarkttfu** [microsoft/vscode-docs#4848]
The Chinese locale names in [the page](https://github.com/microsoft/vscode-docs/blob/main/docs/getstarted/locales.md) has region name in upper case `zh-CN` / `zh-TW`. 

But the simplified Chinese language pack has the display language name `zh-cn` and environment variable `VSCODE_NLS_CONFIG` exposes the locale name 'zh-cn'? Also the `pt-br` in the page has lower case region 'br'?

![image](https://user-images.githubusercontent.com/385536/134761184-4c2bc84f-f660-4e83-af41-c529aaeabddb.png)

As VSCode extension developer, which standard should I follow?

Thanks,
Clark

**Comment by gregvanl** [comment]
Hi @clarkttfu Thanks for pointing this out. Looks like the Chinese Language Packs have switched to lowercase `zh-cn`, `zh-tw`.
We'll update the documentation shortly.
