### ISSUE TITLE
VS Code API docs do not account for `@linkcode` tag

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode-docs#4852]
There are many instances in the [vscode.d.ts](https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts) that use `@linkcode` instead of `@link`, and according to the JSDoc documentation for [`@link`](https://jsdoc.app/tags-inline-link.html) that is a valid synonym that additionally formats the link as code. The [VS Code API docs](https://code.visualstudio.com/api/references/vscode-api) do account for and properly link `@link` but not `@linkcode`.

**Comment by gregvanl** [comment]
@KamasamaK Thanks for pointing this out. We missed this in August but should have a fix shortly.

**Comment by gregvanl** [comment]
Should be fixed now.
