### ISSUE TITLE
Getting Started video needs refresh due to changes to the Get Started page

### ISSUE THREAD

**Issue by rjmolyneaux** [microsoft/vscode-docs#4854]
The content in this video is based on an older version of VS Code using the previous Welcome page 
The video uses some links that are not on the newest version of the in-product Get Started page. 
Regarding: https://code.visualstudio.com/docs/introvideos/basics

These aren't included:
- Welcome tab > Learn > Interface overview
- Customize > Tools and languages
- Customize > Settings and keybindings
- Customize > Color theme
-  
- Learn > Find and run all commands
- Learn > Interface overview
- Learn > Interactive playground

**Comment by theReynald** [comment]
This video has now been refreshed. Will close issue. https://youtu.be/B-s71n0dHUk
