### ISSUE TITLE
Improve documentation and messaging around Python Interpreter selection behavior

### ISSUE THREAD

**Issue by jan11011977** [microsoft/vscode-docs#4880]
Would it be possible to get better documentation and messaging around the new Python Interpreter selection behavior? Specifically:

- If a user selects a Python interpreter for a directory, and then selects a Python Interpreter for the whole workspace, does the workspace interpreter override the python interpreter?

- Is there any place to see what Python Interpreter the user has selected for each directory (our workspace has over 10 directories)

- What happens if the 'python.defaultInterpreterPath' is set to an incorrect path? Does it silently ignore it? Is there an error message when this happens?

- The documentation mentions the first place VSCode looks for venvs is in "Virtual environments located directly under the workspace (project) folder.". I tried putting a venv directory in the same directory as the .vscode-workspace file, but nothing happened. What does 'workspace (project) folder' mean exactly?

- Which macros are valid to use in the defaultInterpreterPath (if any?)

- Is it possible to set the defaultInterpreterPath relative to the directory settings? e.g. will this work
    "python.defaultInterpreterPath": "${fileWorkspaceFolder}\\..\\lang\\python\\win32\\python.exe"

- In the 'select interpreter' dialog box, one of the interpreters is "Recommended". How does VSCode decide which one is recommended, and is there any way to influence that behavior?

Many thanks

**Comment by rjmolyneaux** [comment]
Closing this issue due to timeframe.
