### ISSUE TITLE
Missing webpage link re WSL tutorial for VSCode gives 404 error

### ISSUE THREAD

**Issue by rickhenderson** [Microsoft/vscode-docs#4889]
The page https://code.visualstudio.com/remote-tutorials/wsl/getting-started is missing when I tried to access it.

The link was near the bottom of the Marketplace page for the Visual Studio Remote Development Pack located here:
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack

**Comment by gregvanl** [comment]
Should be fixed now. Thanks again for bringing this to our attention!
