### ISSUE TITLE
All users install extensions 

### ISSUE THREAD

**Issue by outforever** [microsoft/vscode-docs#4898]
Hey there,

Many web pages make reference to being able to install extensions for "all users" by calling VSIXInstaller.exe /admin (ref: https://www.alphr.com/vs-code-how-to-install-extensions/ ). 

However this program does not exist when installing VS code system or user. I have searched the hard drive and cannot find it. I can find it when installing full visual studio.

How does one install extensions for all users in this case? These are downloadable VSIX files. Do i need to install visual studio as well? The lab only needs VS code by what the teacher has told me and the documentation linked above says it should work with VS code, so what am i missing?

**Comment by gregvanl** [comment]
Hi @outforever VSIXInstaller is for VS IDE not VS Code, and you don't need it to install VS Code extensions.
You can install a VS Code extensions via the command line (--install-extension) or through the Extensions view.
https://code.visualstudio.com/docs/editor/extension-marketplace#_install-an-extension
https://code.visualstudio.com/docs/editor/extension-marketplace#_command-line-extension-management

**Comment by gregvanl** [comment]
Here's the open product issue https://github.com/microsoft/vscode/issues/56614 
and there looks to be a workaround with the `--extensions-dir` command line switch https://github.com/microsoft/vscode/issues/56614#issuecomment-437919240.
You would need to manually put the installed extensions into a shared directory and users would need to launch VS Code with the `--extensions-dir` switch.
You could create a batch script or alias to launch VS Code with that switch.
