### ISSUE TITLE
Review tasks.md topic

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#491]
There were a few comments on [HN](https://news.ycombinator.com/item?id=12228610#12230724) about the benefits of tasks and the limitations of the doc. This has been a known area to focus on for some time. Possibly we could get it into August's milestone?

**Comment by gregvanl** [comment]
Yep, I saw that comment as well as the consistent low ratings and frown verbatim.  This topic and the C# topic and flow are what I'd like to work on this month.

**Comment by gregvanl** [comment]
Still need to add a section explaining isWatching
