### ISSUE TITLE
Build Task Broken (Not Up Too Date C++ Version?)

### ISSUE THREAD

**Issue by austinhnelson12** [microsoft/vscode-docs#4917]
Hello,I was following the link followed here (https://code.visualstudio.com/docs/cpp/config-clang-mac) and ran into the following issue when I pasted in the code:
Simple errors in the tutorial code
<img width="1381" alt="Screen Shot 2021-10-27 at 9 52 49 AM" src="https://user-images.githubusercontent.com/89423626/139102241-b2184d6c-d89f-4b08-b865-ba96555c0c76.png">

This is my tasks.json file
<img width="1341" alt="Screen Shot 2021-10-27 at 9 54 19 AM" src="https://user-images.githubusercontent.com/89423626/139102297-b1e4672b-ba0b-4fca-9e72-537e25aebde8.png">

I have seen previous posts to mine but none coming to a solution that worked for me.

**Comment by gregvanl** [comment]
Closing as no reply, looks like a configuration issue
