### ISSUE TITLE
Review csharp.md topic

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#493]
This page is within in code.visualstudio.com top 10 but gets low ratings (<70%) and many frown verbatim.
Work for improvement:
Review csharp.md for flow to external documentation.
Consider simple Hello World example.
Direct other topics to this topic to get new users compiling and running C# programs quickly.

**Comment by tmds** [comment]
Deze cascade

Op 7-aug.-2016 00:34 schreef "Greg Van Liew" <notifications@github.com>:

**Comment by tmds** [comment]
T v.C.zz

Op 7-aug.-2016 00:34 schreef "Greg Van Liew" <notifications@github.com>:

**Comment by gregvanl** [comment]
Kendra Havens, the C# and .NET Core PM, is reviewing this doc. We'll provide her with vscodeBI data.
