### ISSUE TITLE
run the app outside of the VS Code debugger

### ISSUE THREAD

**Issue by Gabryus1974** [microsoft/vscode-docs#4941]
This part of the tutorial on MAC is not working

Set an environment variable for FLASK_APP. On Linux and macOS, use export set FLASK_APP=webapp; on Windows use set FLASK_APP=webapp.
Navigate into the hello_app folder, then launch the program using python -m flask run.

**Comment by gregvanl** [comment]
Hi @Gabryus1974,
Could you describe what is not working for you? Was there any output from `python -m flask run`?
What do you see when you type `echo FLASK_APP` after setting the environment variable in the terminal?
Are you running the python command in the same terminal where you set FLASK_APP?

**Comment by gregvanl** [comment]
Closing as no response from user.
