### ISSUE TITLE
Outdated GIF for "Add a JAR"

### ISSUE THREAD

**Issue by 0dinD** [microsoft/vscode-docs#4948]
On the ["Add a JAR" section of the Java projects documentation](https://github.com/microsoft/vscode-docs/blob/24e218fee4d41d8e19bd1edf9c443b4254fda145/docs/java/java-project.md#add-a-jar), the GIF shown is using an outdated version of the extension where the Java Projects view is still called "Java Dependencies". This is a minor issue, but could be confusing for new users (and all the other GIFs/screenshots are updated).

**Comment by nickzhums** [comment]
@jdneo for awareness
