### ISSUE TITLE
extension-manifest.md was not updated

### ISSUE THREAD

**Issue by lyndaidaii** [microsoft/vscode-docs#4954]
I noticed that the extension-manifest.md is not updated. 

It missing other categories like Testing, Product.

Please help update the list of categories.

**Comment by gregvanl** [comment]
Hi @lyndaidaii Thank you for pointing this out. I will add 'Testing' but I don't see a category for 'Product' when I look at package.json IntelliSense nor when I review VS Code sources in src\vs\platform\extensions\common\extensions.ts:

```ts
export const EXTENSION_CATEGORIES = [
	'Azure',
	'Data Science',
	'Debuggers',
	'Extension Packs',
	'Education',
	'Formatters',
	'Keymaps',
	'Language Packs',
	'Linters',
	'Machine Learning',
	'Notebooks',
	'Programming Languages',
	'SCM Providers',
	'Snippets',
	'Testing',
	'Themes',
	'Visualization',
	'Other',
];
```

Where do you see the category 'Product'?
