### ISSUE TITLE
Tautology in instructions to set up VS Code 2019 C/C++ Compiler

### ISSUE THREAD

**Issue by DRG01** [microsoft/vscode-docs#4962]
![image](https://user-images.githubusercontent.com/60378780/141834535-83ae5dc0-6b1a-4b7d-a946-cf6e0a150402.png)
How do I install the C/C++ compiler in VS Code 2019. The link they gave is tautologous. It directs me to a source that tells me that the compiler must be a prerequisite installation!!

**Comment by gregvanl** [comment]
Hi @DRG01 I might not understand your issue. The links in your screenshot are to tutorials for different combinations of C++ toolsets and platforms. The link you have highlighted is for the Microsoft C++ on Windows tutorial, so it is correct to list out the prerequisites which include the MSVC compiler.
If you think there is still an issue, this is probably better entered in the C++ extension repo at https://github.com/microsoft/vscode-cpptools/issues as the link is from the C++ extension README.
