### ISSUE TITLE
`file/newFile` menu contribution point is missing from Contribution Points reference 

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#4968]
https://github.com/microsoft/vscode-docs/blob/52717cdf56be02fcfe857c220c689e649b463a8f/api/references/contribution-points.md?plain=1#L677

The list in this section omits `file/newFile` which is documented in the 1.59 release notes [here](https://code.visualstudio.com/updates/v1_59#_contribution-point-for-new-file-menu).

**Comment by gregvanl** [comment]
Thanks for keeping us honest!
