### ISSUE TITLE
can't finish tutorial "Using GCC with MinGW"

### ISSUE THREAD

**Issue by naivej** [microsoft/vscode-docs#4993]
I feel I mush did something stupid but I really can't figure it out.

I followed step by step this tutorial https://code.visualstudio.com/docs/cpp/config-mingw
I can build helloworld.cpp successfully but running helloworld.exe doesn't print anything for me, like below
```
PS C:\something> .\helloworld.exe
PS C:\something>
```
If I just double click helloworld.exe, I got the error "entry point not found" and I also got errors if debug.

========================
Googling around I find the solution by adding `-static-libstdc++` when compiling.

**Comment by gregvanl** [comment]
Hi @naivej, I just tried the steps in the tutorial and didn't run into any issues.
I'm unsure why you would need to add the `-static-libstdc++` switch.
Can you provide more details about your setup and your final task.json configuration?

**Comment by naivej** [comment]
[cpp.zip](https://github.com/microsoft/vscode-docs/files/7715853/cpp.zip)
I simply follow the tutorial
1. Configure Default Build Task -> select g++ build active file
2. go back to code, Run Build Task
3. I got the "Build finished successfully." message
4. run into the problem described above unless I add -static-libstdc++ to build task

The solution I found is this one: https://stackoverflow.com/questions/42451175/entry-point-not-found-when-running-exe-c

I don't know if I miss something when installing MSYS2 since this looks like a compiler's problem.
But I also follow strictly https://www.msys2.org/ and am not sure what else to do.

**Comment by jureid** [comment]
Hey @naivej - just checking, did you add the mingw64 bin directory to your PATH environment variable?

Here are the steps to do so (in the prerequisite section of the [tutorial](https://code.visualstudio.com/docs/cpp/config-mingw):

1. In the Windows search bar, type 'settings' to open your Windows Settings.
2. Search for Edit environment variables for your account.
3. Choose the Path variable and then select Edit.
4. Select New and add the Mingw-w64 destination folder path to the system path. The exact path depends on which version of Mingw-w64 you have installed and where you installed it. If you used the settings above to install Mingw-w64, then add this to the path: C:\msys64\mingw64\bin.
5. Select OK to save the updated PATH. You will need to reopen any console windows for the new PATH location to be available.

**Comment by jureid** [comment]
Glad to hear your problem is fixed! @gregvanl - maybe we can update the tutorial to make it clear that it must be a User environment variable and not a System environment variable?

![image](https://user-images.githubusercontent.com/44306969/146775367-f7692b88-231d-456c-8825-1c32847b7562.png)
