### ISSUE TITLE
Screenshots in release notes are commonly taken with a ultra hd resolution (4k or more) and so they appear disproportionate and blurry when displayed in a lower resolution

### ISSUE THREAD

**Issue by darkred** [microsoft/vscode-docs#5000]
Commonly in the release notes some of/all the contained screenshots are apparently taken with an ultra hd resolution (4k or more) and so they appear disproportionate to the text and blurry when displayed in a lower resolution resolution.
My monitor is not ultra hd resolution, it's 1920x1200, and so I find such screenshots difficult to visually scan.

Here are some screenshot examples: 
<details>
<summary>Release notes for VSCode v1.60</summary>

https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_60.md
![2021-12-02_225506](https://user-images.githubusercontent.com/723651/144501602-97edaa89-4edd-4473-8c3d-9daf2d460d23.jpg)
</details>

<details>
<summary>Release notes for VSCode v1.63</summary>

https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_63.md
![2021-12-02_225620](https://user-images.githubusercontent.com/723651/144501740-5e425014-d645-4dc5-b267-b527c1ee02b9.jpg)
</details>

My suggestion is to make it "mandatory" for release notes authors to always use a more commonly used resolution for the screenshots they submit, such as 1920x1080 .

Thank you

**Comment by Lemmingh** [comment]
Looks like the screenshots are usually taken on [MacBook Pro](https://www.apple.com/macbook-pro-13/specs/) whose Retina display is well-known for high native resolution and high pixel density.

I'm also looking forward to a solution, as it takes a long time to load release notes on poor network connections due to these images.

**Comment by gregvanl** [comment]
Closing old issue without upvotes
