### ISSUE TITLE
strictOptionalProperties has been renamed to exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-docs#5001]
`strictOptionalProperties` has been renamed to `exactOptionalPropertyTypes`

https://github.com/microsoft/vscode-docs/blob/f518dcba092b4e71d83cfa73d8beff65487ca83b/release-notes/v1_63.md#L280-L288

- https://github.com/microsoft/TypeScript/pull/44626

cc: @mjbvz

**Comment by gregvanl** [comment]
@tamuratak Thanks for pointing this out! Fixed with https://github.com/microsoft/vscode-docs/commit/5c8a7313d7d48fc7cc32b0ef60fca1fc14f09cd7
