### ISSUE TITLE
Visual Studio Code - Javascript: jsconfig.json and the “out” attribute

### ISSUE THREAD

**Issue by tamin0** [Microsoft/vscode-docs#501]
I'm curious what is meant by the Visual Studio Code documentation when mentioning the "out" attribute on the following page:

[https://code.visualstudio.com/docs/languages/javascript](https://code.visualstudio.com/docs/languages/javascript)

I'm unable to find any references as to where this "out" attribute is defined.

Here is an excerpt from the page:

## Excludes

Whenever possible, you should exclude folders with JavaScript files that are not part of the source code for your project.

> Note: If you do not have a **jsconfig.json** in your workspace, VS Code will by default exclude the **node_modules** folder and the folder defined by the **out** attribute.

**Comment by waderyan** [comment]
Addressed in #542
