### ISSUE TITLE
Add module rename as another refactoring functionality  

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#5010]
We have another refactoring feature coming that is provided by Pylance, and I think it might be worth adding it to our documentation (around [this section](https://code.visualstudio.com/docs/python/editing#_refactoring)).   

This is a new rename refactoring experience, via Pylance. Previously, when users renamed a file/module, they would have search for references to that module in your codebase and update each location manually. As of this upcoming release, after renaming a Python file/module, Pylance will find all the instances that need to be updated and provide users with a preview of all the changes to be made. If users want to customize the references to be updated, they can toggle check boxes at the line or file level in the preview. They can also change their mind after seeing what would be changed at the preview stage and discard all changes.

https://user-images.githubusercontent.com/45497113/144949125-0f2886dc-5cc8-488a-b370-fefb69d40775.mp4

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/2ed0d2dc74ec1816d0f6b8f999e976bf002bccde
