### ISSUE TITLE
Document how to work without tabs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#503]
Usually I point users to this https://github.com/Microsoft/vscode/issues/6605 when they want to know how to work best without tabs in VS Code. I think since this question comes up more often we should add this to our Tabs docs page, maybe as full entry or just as FAQ.

Key points:
* the setting to disable tabs
* optional: disable the preview of editors
* optional: rebind keys to get as much back of the old experience as possible

/cc @egamma

**Comment by egamma** [comment]
In particular user are missing how to configure Ctrl+Tab to navigate in entire editor history.

**Comment by gregvanl** [comment]
Added https://vscode-eastus.azurewebsites.net/docs/editor/tabs#_working-without-tabs

**Comment by bpasero** [comment]
great!
