### ISSUE TITLE
Create git guides for beginners

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-docs#5033]
**Why:** The current [version-control](https://code.visualstudio.com/docs/editor/versioncontrol) page is just a generic overview, slightly flavored with git. The [github docs](https://code.visualstudio.com/docs/editor/github#_editor-integration) is also more a of UI and feature tour. Both assume git knowledge.

**What:** Beginner-focused content should walk through specific use cases that developers struggle with. By sticking to UI-based flows, those pages can lower the steep learning curve that most git guides have.

**How:** We'll add a new top-level `/git` docs category with a handful of short scenario-based articles. Anything that new developers need help with can be considered, prioritizing topics that cover most common _use cases_ and _pitfalls_.

🚧 Draft ideas for topics, to be discussed:

1. Track and commit changed files
2. Resolving merge conflict
3. Checkout a remote branch
4. Create a github pull requests
5. FAQ _for misc details_

TBD:
- [ ] Brainstorm initial topics and converge on a shortlist
- [ ] Outline for top 3
- [ ] Create articles (2 pager)

**What git issues do developers struggle with most?**

Search results on google are probably more driven by frustration than importance/frequency of the use case.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/8599/146317424-7a2dc7e1-2d9d-4a9a-a748-320a2dcf50ed.png">

<img width="274" alt="image" src="https://user-images.githubusercontent.com/8599/146317534-adb86abb-21da-4018-809b-40ce15ef0b85.png">

<img width="299" alt="image" src="https://user-images.githubusercontent.com/8599/146317656-5a09c52d-debf-4aac-8923-3c2829fcaff8.png">

cc @burkeholland @ItalyPaleAle @sana-ajani

**Comment by ItalyPaleAle** [comment]
Is this something we could work on with support for someone at GitHub? Like someone in Martin's team?

And do you think our docs would be a good place to also explain the _why_ of Git, in addition to the _how_ ?

**Comment by digitarald** [comment]
@ItalyPaleAle yes and yes (especially for use cases, so they make sense to their audience). Let's sync next year to pull in the right people to help write & review.

**Comment by nelsonmic** [comment]
hi @digitarald, I would like to help out with this, please can you help me get started?

**Comment by AriESQ** [comment]
This seems out of scope for VS-Code documentation.

**Comment by gregvanl** [comment]
Closing issue as not on any current milestone plan. We can reopen the issue when the work is resourced and scheduled.
