### ISSUE TITLE
Command to focus on Java Projects on the sidebar

### ISSUE THREAD

**Issue by mcrors** [microsoft/vscode-docs#5039]
Hello, 

I have installed the Java Extensions pack. I like the Java Projects sidebar, and would like to be able to jump to it using a shortcut. For example, I can create a key mapping to jump to the outline using the command outline.focus. Is there something similar for the Java Projects section?

Many thanks

**Comment by gregvanl** [comment]
You can add a keybinding to the Explorer: Focus on Java Projects View command (command ID javaProjectExplorer.focus).

For example, in the Keyboard Shortcuts editor, you can select the '+' and type a keyboard shortcut or chord. Below I've used Ctrl+J Ctrl+A.

![image](https://user-images.githubusercontent.com/12818376/146662808-851ce94c-e47d-411d-8e38-9d2e0316c054.png)

In your user keybindings.json: 

```json
    {
        "key": "ctrl+j ctrl+a",
        "command": "javaProjectExplorer.focus"
    }
```

**Comment by gregvanl** [comment]
Closing as an answer was provided and there were no further questions
