### ISSUE TITLE
Clang on macOS

### ISSUE THREAD

**Issue by usshas** [microsoft/vscode-docs#5052]
i can't configure or download clang on my macOS

**Comment by genzyy** [comment]
Try this: https://embeddedartistry.com/blog/2017/02/24/installing-llvm-clang-on-osx/

**Comment by gregvanl** [comment]
Closing as another user provided guidance and original issue author has not responded.
 
XCode should install Clang and you can use `xcode-select --install` per https://code.visualstudio.com/docs/cpp/config-clang-mac#_ensure-clang-is-installed
