### ISSUE TITLE
issue in terminal

### ISSUE THREAD

**Issue by divyanshv21** [microsoft/vscode-docs#5053]

**Comment by divyanshv21** [comment]
mkdir projects
cd projects
mkdir helloworld
cd helloworld
code .

On writing this on my mac's terminal it shows:
zsh: command not found: code

how to resolve this?

**Comment by habarahonaa** [comment]
Hey friend! This is not precisely a documentation issue, but you can solve it by adding **VSCODE to your shells's PATH**.

### Steps:

1. Open Visual Studio Code
2. In Visual Studio Code, open the **command palette** (⇧⌘P)
3. Type `shell command` in the search bar that opens up
4. First, select **Uninstall 'code' command from PATH**
5. Then, you can click on **Install 'code' command in PATH** command**

**Comment by gregvanl** [comment]
Closing as possible solution provided but no response from user. General issue with VS Code setup on macOS and not a documentation issue since macOS setup is covered in https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line
