### ISSUE TITLE
"jinja" and "code" are not mentioned as launch configuration option for Python debugging

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#5061]
In the section [Set configuration options](https://code.visualstudio.com/docs/python/debugging#_set-configuration-options) on Python debugging there is no mentioning of the `jinja` option.

It is mentioned in the Flask debugging section but Jinja can be used in any Python Web Framework.

Using the setting `"jinja":true` allows me to debug the template (if language set to Jinja) in a non-Flask framework. The template needs to be loaded with the Environment/File Loader.

**Comment by rioj7** [comment]
Also `code` is not mentioned as a possible alternative for `program` or `module`

**Comment by rjmolyneaux** [comment]
Thank you for contributing to the docs @rioj7! We've made the appropriate changes to the page.
