### ISSUE TITLE
VS Code Scala programming language document

### ISSUE THREAD

**Issue by DachuanZhao** [microsoft/vscode-docs#5068]
I notice that there is not a document about writing ```scala``` code at [https://code.visualstudio.com/docs/languages/overview](https://code.visualstudio.com/docs/languages/overview)  .  ```scala``` is a very important language for user who should write spark scripts .  

So is there an expert here who can write documents about  "use ```scala``` with vscode" ?

**Comment by gregvanl** [comment]
Closing older issue with no upvotes and no community engagement, however PRs are welcome

**Comment by dos65** [comment]
I'm going to work on this issue and cover [Scala (Metals)](https://marketplace.visualstudio.com/items?itemName=scalameta.metals) extension usage.

@gregvanl I'm thinking about the structure of content. Metals has a lot of features and it might be hard to cover all of them only in one page. Would it be ok to split the content and add a language tutorial in the same manner as there is for [nodejs](https://github.com/microsoft/vscode-docs/tree/main/docs/nodejs), [python](https://github.com/microsoft/vscode-docs/tree/main/docs/python) and others?

**Comment by tgodzik** [comment]
Metals (or MetaLS) is just a name of the extension, Maven is supported by it along with Gradle, sbt, mill and scalacli.

**Comment by gregvanl** [comment]
Hi @dos65 I would recommend starting with one topic under docs/languages and see how the writing goes and what the reaction is like once it is published. 
In general, topics under the Languages section of the table of content are for discovery and to present the features and value proposition of use a specific programming language in VS Code. The topics can link out to more detailed documentation in the extension repo or wiki. It is usually easier for extension authors to maintain content nearer the extension's source code.
