### ISSUE TITLE
theme-color/keybinding-label.png exist but is unreadable

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#5079]
In the section [Keybinding label colors](https://code.visualstudio.com/api/references/theme-color#keybinding-label-colors) is an image [keybinding-label.png](https://code.visualstudio.com/assets/api/references/theme-color/keybinding-label.png).

It exist but Google Chrome, Photoshop, Gimp, Windows Paint can't read it.

**Comment by gregvanl** [comment]
Thanks for noticing!
