### ISSUE TITLE
Improve the document: Getting Started with Python in VS Code

### ISSUE THREAD

**Issue by dkemlage** [microsoft/vscode-docs#5088]
The document [Getting Started with Python in VS Code](https://code.visualstudio.com/docs/python/python-tutorial) does not convey information to a beginner of Visual Studio Code and Python in an easy to understand manner. I suggest that this document have an overhaul. While this document does contain very useful information written by a team of very bright and talented people, it misses the mark to help a beginner be successful. I found going through the document took a long time and was difficult to understand in places. I encountered errors in using the tutorial which increased my frustration as a new user to using Python in Visual Studio Code. I wish I had more time to provide you with a complete example of what I am suggesting and the issues that I faced but making corrections to Microsoft documentation is not what I get paid for. I have already spent over 8 hours struggling to understand all of the concepts in this document and I cannot devote much more time to providing more feedback than what is about to follow:

---

(1) In the introduction, be clearer about what this document is all about, for example start with something like:

This tutorial teaches you several concepts including:
- How to test for an existing version of the of Python on your machine and directs you to where you can install Python if this is your first time.
- How to install and configure Visual Studio Code (VS Code).
- How to install and configure the Python Extension for VS Code.
- Using VS Code to create a simple Python "Hello World" application and how to use the debugger.
- Using VS Code to create a more complex Python application that requires installing and using Python packages.

---

(2) This document (Getting Started with Python in VS Code) attempts to do too much in one single document. It is trying to serve as a step-by-step walk-through tutorial, provide deep dive facts, and doing this for multiple Operating Systems (Windows, macOS, and Linux). Break these concepts into separate documents. Create one step-by-step walk-through for each operating system. If more detailed information (aka reference documentation) is needed, give a small tease about that information as a note and then link off into that more deep-dive document.

---

(3) Here is one example of what I mean by this tutorial trying to do too much. Consider the following screen shot:
  
![image](https://user-images.githubusercontent.com/5495810/147133018-71c568b1-e62d-43c7-a130-95ed4a161c3a.png)

It is mentioned about an `Anaconda distribution` but there is no link to what this is. Better yet, do not talk about Anaconda in this tutorial and create another tutorial specifically for Anaconda distributions and using Python in VS Code.

In the circled red graphic, you are told that "VS Code stores settings that are specific to that workspace in `.vscode/settings.json` ...". What is this? Is it a file? Where is it located? I did not see a `settings.json` file in the "hello" folder (or any sub-folder) on my hard drive when following steps. Provide a link to another document that discusses VS Code workspaces in more detail; including the differences of a local workspace -vs- something being stored globally (and where is that stored on disk).
  
If you are going to provide a step-by-step set of instructions, it is very distracting to tell the user to do the following steps and then give them another option to do the same thing. Hence the line "Alternately, you can run VS Code through the operating system UI, then use File > Open Folder to open the project folder." just serves as a distraction on how to accomplish a specific task for the first time. Having multiple way to do something is better in a reference document and not a step-by-step document.

---

(4) Here is another example of providing too much information in a tutorial document and confusing the user, consider the screen shot:

![image](https://user-images.githubusercontent.com/5495810/147135451-f3ca2c81-3bf9-44ef-9c06-0c99ab48488d.png)

Again, it is mentioned about an `Anaconda distribution` but there is no link to what this is. Better yet, do not talk about Anaconda in this tutorial and create another tutorial specifically for Anaconda distributions and using Python in VS Code.

In the red circled graphic, you are told about setting the workspace and the `python.defaultsInterpreterPath` user scope. What is this? Where is the link to another document where I can learn more about this? This is some really deep information that really may not be relevant for a step-by-step tutorial.

---

(5) Creating and activating the virtual environment in the **For Windows** section did not work for me. I think someone needs to try these steps (QA) and make sure that they are giving the user the right instructions. Perhaps as VS Code has evolved over the user the instructions that were here have become outdated/incorrect? Consider the following screen shot:

![image](https://user-images.githubusercontent.com/5495810/147136404-4c869294-03a4-4502-9f30-7ba7fff59b60.png)

I am on a Windows 10 machine and when I typed the following syntax on Terminal command line in VS Code ".venv\scripts\activate", I got the following error "bash: .venvscriptsactivate: command not found". I needed to use the following syntax: ".venv/scripts/activate" (note: that I needed to use forward slashes not back slashes).

![image](https://user-images.githubusercontent.com/5495810/147136951-96787412-2578-4a49-b588-29a54bc5baa9.png)

**Comment by rjmolyneaux** [comment]
Hi @dkemlage,
Thank you for contributing to the VS Code docs and bringing this to our attention! We always look for opportunities to improve our documentation and user experience. I've passed your findings over to the product team. Please don't hesitate to reach out again in the future.
