### ISSUE TITLE
Files association due to c/c++ extention

### ISSUE THREAD

**Issue by 2311kamal** [microsoft/vscode-docs#5091]
When a create a c file in vs code a json file is automatically created that converts the c file to cpp file 
here is the content of json file

{
    "files.associations": {
        "Q2.C": "cpp",
        "Q4.C": "cpp",
        "Q3.C": "cpp",
        "Q5.C": "cpp",
        "Q6.C": "cpp",
        "Q7a.C": "cpp",
        "Q7b.C": "cpp",
        "Q7c.C": "cpp",
        "Q7d.C": "cpp"
    }
}

I dont know why its happening please tell me 
<img width="572" alt="Screenshot 2022-01-12 215234" src="https://user-images.githubusercontent.com/96480223/149179968-4acc3c24-9c3f-44dd-8fb9-cd5e61200d36.png">

**Comment by gregvanl** [comment]
Hi @2311kamal, 
To help direct your question, which C++ extension do you have installed? Are you using the Microsoft C/C++ extension?
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

**Comment by jureid** [comment]
Hi @2311kamal,

The capital C file extension (.C) is intended for cpp files, not c files. I'd recommend switching your file extensions to lowercase ".c" if you want to code in c. But if you need capital C file extensions, you could add `C_Cpp.autoAddFileAssociations = "false"` to settings.json to disable the automatic file association.

**Comment by 2311kamal** [comment]
Thankyou very much!

**Comment by jureid** [comment]
@2311kamal - I previously wrote the wrong syntax for `"C_Cpp.autoAddFileAssociations": false`. I updated the comment and now it's correct.

**Comment by 2311kamal** [comment]
Thankyou very much for considering this small thing!

**Comment by gregvanl** [comment]
Closing as answer provided.

**Comment by 2311kamal** [comment]
Thanks a lot.
