### ISSUE TITLE
How to configure C++ and Kotlin etc for VS Code 

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode-docs#5093]
Issue Type: <b>Feature Request</b>

Well I would appreciate if Microsoft can come up with "How to Guides" on configuring compilers such as MinGW-w64 (for C/C++) and coding in the Kotlin language.  In fact, there should be one guide each for all the languages and compilers that VS Code supports.  In fact, these are the languages that I will be facing in my career apart from emerging tech - HTML5 & CSS3 (works), Java 17 (works), Python 3.10 (works), npm & gem (works), JS & TS (haven't tried), C++ (g++ not recognised), Kotlin (kotlinc not recognised), Ruby 2.7 (works), Golang, Clojure and Prolog (haven't tried it).  

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by j-martens** [comment]
@j-martens 

#reassign: @gregvanl

**Comment by gregvanl** [comment]
Hi @AGoh2019 You can find several tutorials for different platforms and C++ tool sets under https://code.visualstudio.com/docs/cpp.
For example, there are tutorials for configuring MinGW and MS C++ for Windows and Clang for macOS.
Documentation on code.visualstudio.com is available for languages supported by Microsoft extensions such as Python, Java, and C++. For other languages such as Kotlin, you can find popular VS Code extensions (as pointed out by @IllusionMH) and refer to the extension's documentation for help configuring and installing the required dependencies.
