### ISSUE TITLE
C++  .exe no output

### ISSUE THREAD

**Issue by Xinchengzelin** [microsoft/vscode-docs#5096]
I first use C++ in VSCode, I configure my computer as [here](https://code.visualstudio.com/docs/cpp/config-mingw)

When I run .exe file, no output, I don't know where the problem is.

![image](https://user-images.githubusercontent.com/30117686/149649051-0d8154c8-0cd0-48c8-9fc0-633a1f6cbaab.png)

OS: Windows7

tasks.json

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\msys64\\mingw64\\bin\\g++.exe",
			"args": [
				"-fdiagnostics-color=always",
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${fileDirname}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: C:\\msys64\\mingw64\\bin\\g++.exe"
		}
	]
}
```

**Comment by Xinchengzelin** [comment]
If I use code runner extension, all is OK.

**Comment by gregvanl** [comment]
Hi @Xinchengzelin I wonder if you have a problem with the C++ compiler on your path.
What happens if you run `g++ --version` from the VS Code terminal?

**Comment by gregvanl** [comment]
Closing as no reply from user.

**Comment by Xinchengzelin** [comment]
> Closing as no reply from user.



> Hi @Xinchengzelin I wonder if you have a problem with the C++ compiler on your path. What happens if you run `g++ --version` from the VS Code terminal?
```
(base) d:\Code\LearningCpp\ch1>g++ --version
g++ (Rev10, Built by MSYS2 project) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Xinchengzelin** [comment]
> > Closing as no reply from user.
> 
> > Hi @Xinchengzelin I wonder if you have a problem with the C++ compiler on your path. What happens if you run `g++ --version` from the VS Code terminal?
> 
> ```
> (base) d:\Code\LearningCpp\ch1>g++ --version
> g++ (Rev10, Built by MSYS2 project) 11.2.0
> Copyright (C) 2021 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

I found another question:
```
#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{

    cout << "hello world" << endl;

    vector<int> a{1,2,3};
    vector<int> b{4,5,6};
    for (auto e:a){
        cout << e << endl;
    }

}
```
I changed my os system to Windows10
if I commented the 5 lines code about the vector, the terminal could print out "hello world",  if not, nothing print out.  however it's normal in ubuntu system.
