### ISSUE TITLE
Tree View Welcome Content talks about that a View can have a "message"

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#5122]
On the Tree View page the [Welcome Content](https://code.visualstudio.com/api/extension-guides/tree-view#welcome-content) talks about

> An empty view is a view that has no **message** and an empty tree.

What is the **message** mentioned in this sentence?

The word **message** is not found on the page anywhere else (beside the `vscode.window.showInformationMessage`)

Is it possible to add a link to an Extension README page?

**Comment by gregvanl** [comment]
@rioj7 The `message` property is on the TreeView object https://github.com/microsoft/vscode/blob/1b4af18aa69083bf3cd545503e251c8bcc72a8c2/src/vscode-dts/vscode.d.ts#L10603-L10607
I'll update the documentation to add the scope for clarity.

Really appreciate that you read our documentation so carefully and take the time to open issues. Thanks!
