### ISSUE TITLE
Can not compile C

### ISSUE THREAD

**Issue by brucehacker66** [microsoft/vscode-docs#5135]
I can not compile C but can compile C++ after installing MSYS2 Mingw-w64 GCC compiler. 
It shows the following message:
![image](https://user-images.githubusercontent.com/88654703/152098568-c8f74f26-1498-428e-8f5d-1798829f1aca.png)

**Comment by gregvanl** [comment]
Hi @brucehacker66 Are you still having trouble compiling C source code or did you find a work around?

**Comment by gregvanl** [comment]
Closing as no response
