### ISSUE TITLE
Review performance and update Settings topic

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#5136]

**Comment by 69WileyCoyote69** [comment]
> _No description provided._

https://help.twitter.com/en.ht

>

**Comment by 69WileyCoyote69** [comment]
@69WileyCoyote69 
![FB_IMG_1643251388884](https://user-images.githubusercontent.com/99140582/152782949-3356e4e4-eb50-473c-bd31-432e89fdc0b4.jpg)
