### ISSUE TITLE
Error in Documentation: Debugging TypeScript

### ISSUE THREAD

**Issue by mavigozler** [microsoft/vscode-docs#5140]
In the [Debugging TypeScript](https://code.visualstudio.com/docs/typescript/typescript-debugging) article, in the section **Client-Side Debugging** using the HelloWeb example, the `launch.json` content appears to be missing at least one, possibly two, vital properties.

The current version of the article presents `launch.json` as:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-msedge",
      "request": "launch",
      "name": "Launch Edge against localhost",
      "url": "file:///C:/Users/username/deleteMe/HelloWeb/helloweb.html",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```
This launch configuration will not function if used, since the `helloweb.ts` file will not be tasked to compile with `tsc` and thus not generate the `helloweb.js` file in the proper directory.

The one vital missing property is `preLaunchTask` with value `tsc: build - tsconfig.json`. It is possible that the `outFiles` property is also missing, although the debugger runs properly without it. The corrected configuration of `launch.json` for the HelloWeb example is below, which includes the two properties.

```
{
   "version": "0.2.0",
   "configurations": [
      {
         "type": "pwa-msedge",
         "request": "launch",
         "name": "Launch Edge against localhost",
         "url": "file:///D:/dev/GeneralTesting/HelloWeb/helloweb.html",
         "preLaunchTask": "tsc: build - tsconfig.json",
         "outFiles": [
            "${workspaceFolder}/out/**/*.js"
         ],
         "webRoot": "${workspaceFolder}"
      }
   ]
}
```
Please confirm whether this information about documentation error is correct.

**Comment by gregvanl** [comment]
Hi @mavigozler Thank you for opening an issue and your interest in the VS Code documentation.
The tutorial mentions running `tsc` and checking the HTML with the compiled TypeScript earlier in the short tutorial.
While for real development, users would probably want to have a `preLaunchTask` specified, for this simple example, we'd like to keep the `launch.json` file as close to the generated version as possible for simplicity.

The tutorial is a little out of date, for example the Gear button has been replaced with a "create a launch.json file" link and the configuration has been renamed to "Web App (Edge)". I'll update the topic shortly.
