### ISSUE TITLE
Add sample implementation of "Do not show again" option for every notification

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-docs#5141]
The [Notification examples](https://github.com/microsoft/vscode-docs/blob/main/api/references/extension-guidelines.md#notification-examples) section of the docs says

> Add a **Do not show again option** for every notification

![image](https://user-images.githubusercontent.com/43425812/152590429-4bb13908-4c1b-4e08-aa25-f722a54663c7.png)

Where can I find a sample implementation of every notification having a functional **Do not show again** checkbox?

If one isn't readily available, can we add this to the documentation?

Also, what are your thoughts on adding a `Discussions` section to this repository for questions like these?

**Comment by gregvanl** [comment]
Closing as only one upvote and looks like the community has lost interest

**Comment by snehara99** [comment]
I would like an example of this as well.
