### ISSUE TITLE
A11y_Code.visualstudio.com_visual studio Learn page_Overview_Text spacing : On applying text spacing "Collaboration" text is getting overlapped with dropdown icon.

### ISSUE THREAD

**Issue by Samhitha66** [microsoft/vscode-docs#5157]
## GitHub Tags:
#A11yTCS;#Win10;#WCAG1.4.12;#DesktopWeb;#A11ySev2;#ChromiumEdge;#P1-VisualStudioCodeServices-Web-Feb2022;#P1_Visual Studio Code Services;#Visual Studio Code Services;

## Environmental Details:
#URL: https://code.visualstudio.com/learn

## OS & Browser Details :
Microsoft Windows 10 Enterprise
Version 10.0.19044 Build 19044
Microsoft Edge
Version 99.0.1150.7 (Official build) dev (64-bit)

## Repro Steps:

1. Hit the URL: https://code.visualstudio.com/learn
2. Apply Text spacing.
3. Check the  "Collaboration" text is getting overlapped with dropdown icon or not.

## Actual results:
On applying text spacing "Collaboration" text is getting overlapped with dropdown icon.

## Expected results:
On applying text spacing "Collaboration" text should not overlapped with dropdown icon.

## User Impact:
Users with low vision who applies text spacing will not be able to read the text if the content gets overlapped with icon.

## Attachments:

https://user-images.githubusercontent.com/99243079/153145599-03be2aca-95d9-49bd-9745-54ccd7dcddaa.mp4

**Comment by gregvanl** [comment]
Hi @Samhitha66 Can you provide the full configuration including any tools you are using in the video. For example, is there a specific tool or extension you use to have the "Text Spacing" button in the extra browser tool bar?
It's really helpful for us to know if we have provided a complete fix for your test scenario. Thanks

**Comment by Samhitha66** [comment]
@gregvanl 
Checked again this bug in the below environment
URL: https://code.visualstudio.com/learn

On applying text spacing "Collaboration" text is not  overlapping with dropdown icon.
So, the issue is fixed.
![Bug_5157](https://user-images.githubusercontent.com/99243079/157197751-17b1aa19-294a-48ab-b1a1-77dba5a12a08.png)
