### ISSUE TITLE
JavaScript - new doc structure

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#516]
I recommend the following for a new doc structure. 

# JavaScript

## IntelliSense

* put JavaScript projects and Typings under here
* move mixed TypeScript and JavaScript projects under JavaScript projects
* move compiling Javascript down level here
* move formatting here

## Recommended Extensions

* Change this list from a query to a curated list (I have built the curation)

## Next Steps

* Link to Intro Videos (might be done already in PR)

## Common Questions

* Add more here

**Comment by waderyan** [comment]
Put the in the box stuff up higher that doesn't require any setup.

**Comment by egamma** [comment]
We have some fwd links that point into the JS doc, we need to ensure that they still work after the restructuring.

**Comment by waderyan** [comment]
Good point. Any idea where those are? I can check them out. 

Maybe I should make a mapping from old sections to the new sections...

**Comment by waderyan** [comment]
Found one for jsconfig.json format. 

https://go.microsoft.com/fwlink/?LinkId=759670

**Comment by waderyan** [comment]
Fixed with PR #542
