### ISSUE TITLE
Cannot get C++ to compile, instruction page for how to get started with C++ is terrible.

### ISSUE THREAD

**Issue by wark77** [microsoft/vscode-docs#5163]
Steps to Reproduce:

1. install vscode and compile C++ on a new machine.

https://code.visualstudio.com/docs/languages/cpp 
doesn't seem to work.

while this : http://www.edparrish.net/common/npp4c.html
does.

**Comment by gregvanl** [comment]
Closing as no response. We are currently directing users to the MSYS2 MinGW install rather than cygwin, but people are free to use the toolset that they prefer

**Comment by wark77** [comment]
I have it working since this was closed, I was not seeing the mingw64 console instructions.
Thank you for replying.
