### ISSUE TITLE
Change Extension Marketplace to Extensions

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#517]
It seems like the Extension Marketplace doc has become more than information on the marketplace. What if we changed the name to Extensions?

**Comment by gregvanl** [comment]
Seems like a good idea. If we do this, we may want to consider renaming the "EXTENSIONS" node to "CREATING EXTENSIONS".
Looking at this for October. @waderyan

**Comment by gregvanl** [comment]
Chatted with Wade, not clear that people are confused by this topic title and "Marketplace" does imply that the user is going somewhere for existing extensions.
