### ISSUE TITLE
Which launch configuration is used by Auto Attach

### ISSUE THREAD

**Issue by mkamalkayani** [microsoft/vscode-docs#5170]
While working with auto attach debugging, I periodically get a suggestion to add outFiles in the launch.json file to speed up the debugger. However, it is not clear how this should be done and how the different processes would map to the different configurations in the launch.json file.

Is there any configuration to serve as an example?

**Comment by gregvanl** [comment]
Hi @mkamalkayani There is a description of when to use `outFiles` so VS Code can more quickly locate source maps in https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery

**Comment by mkamalkayani** [comment]
Hi @gregvanl Thanks for the link, it is helpful. 

I have several configurations in the launch.json file.  I am confused which configurations is used by the auto attach.

**Comment by gregvanl** [comment]
Any configuration with `"request": "attach"` handles auto attach versus `"request": "launch"` to explicitly start a debuggee.

**Comment by mkamalkayani** [comment]
As far as I understand, what you are suggesting applies to normal/manually triggered attach.

For auto attach, it is there in the docs, I overlooked it. [Auto attach additional configuration](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_additional-configuration)

 But the notification message is misleading. 

According to the docs, the auto attach setting is available at `debug.javascript.terminalOptions` in the settings. The notification suggests to add outFiles in the launch.json

**Comment by gregvanl** [comment]
Hi @mkamalkayani Sorry for the delay in responding, if you think the notification is misleading or could be clearer, you can open a suggestion in the vscode product repository at https://github.com/microsoft/vscode/issues
