### ISSUE TITLE
Reorder Editor TOC

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#518]
The current order is

![image](https://cloud.githubusercontent.com/assets/2449568/17634187/3964825c-6086-11e6-88e9-5148c92656a9.png)

I suggest we change the order to
- The Basics
- Editing Evolved
- IntelliSense (doc a WIP)
- Debugging 
- Extension Marketplace (any thoughts on changing the name to simply Extensions? see #517)
- Version Control
- Tasks
- Integrated Terminal
- Tabs
- Accessibility
- Why VS Code? (should we fold this under The Basics or even make it a blog post?)

As this is more in line with the priorities of the product's value prop.

**Comment by gregvanl** [comment]
We can look at this when we review our 6 months web site plans. We were deliberate when we put Extension Marketplace second when product extensibility was opened.
