### ISSUE TITLE
Documentation improvement: Debug Actions

### ISSUE THREAD

**Issue by IavTavares** [microsoft/vscode-docs#5180]
[On this page](https://code.visualstudio.com/Docs/editor/debugging) for the official docs for vscode, there's no explanation for what the Debug Toolbar options, like step over, etc.,  will do.

I suggest adding some information on it.

Thanks.

**Comment by IavTavares** [comment]
Hi @gregvanl, 

Since I'm just learning debugging by myself, I don't think so.

However, this [other link](https://docs.microsoft.com/en-us/visualstudio/debugger/navigating-through-code-with-the-debugger?view=vs-2022#BKMK_Step_over_Step_out) does help me.

**Comment by gregvanl** [comment]
Closing as the doc suggestion doesn't have any upvotes and looks like user found a general explanation for conventional debugging actions.
