### ISSUE TITLE
Vue: Guidance for recommended extensions differs from vuejs.org website

### ISSUE THREAD

**Issue by JeffJacobson** [microsoft/vscode-docs#5189]
I noticed that the [Vue tutorial] (`docs/nodejs/vuejs-tutorial.md`) recommends the **Vetur** extension whereas the [Vue website TypeScript guide] now recommends the **Volar** extension. It looks like the advice on the VS Code website might be outdated.

[Vue tutorial]:https://github.com/microsoft/vscode-docs/blob/main/docs/nodejs/vuejs-tutorial.md
[Vue website TypeScript guide]:https://vuejs.org/guide/typescript/overview.html#ide-support

**Comment by gregvanl** [comment]
@JeffJacobson Thanks for the heads up. We'll schedule a tutorial update and watch as the Volar extension gains in popularity

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/6925
