### ISSUE TITLE
Introduce a Linting doc

### ISSUE THREAD

**Issue by waderyan** [microsoft/vscode-docs#519]
In my interactions with customers (especially new coders) I have found that linting is frequently not understood or even recognized. 

I recommend we create a linting document in a similar pattern as IntelliSense and Debugging. Linting is a "check box" feature, meaning we don't add significant value over other tools, but its important enough in the coders inner loop that I believe it deserves a greater focus in our doc. 

With work finished to improve Errors and Warnings output (and it is very slick now) we should consider emphasizing this more with its own doc. Likely in the Editor section.

**Comment by gregvanl** [comment]
include a troubleshooting section https://github.com/Microsoft/vscode-tslint/blob/master/tslint/README.md#trouble-shooting

**Comment by gregvanl** [comment]
Closing old issue. Linting covered in several specific language topics and configuration details are in the linter extension READMEs.

**Comment by gregvanl** [comment]
Reopening as creating a new Linter topic (covering ESLint) as part of the JS/TS topic refactoring
