### ISSUE TITLE
bug : the latest version do not suppot xml file

### ISSUE THREAD

**Issue by shantj** [Microsoft/vscode-docs#52]

**Comment by gregvanl** [comment]
Thank you for calling out this issue.  If you are still able to reproduce this issue with the latest update to Visual Studio Code (0.10.2), please open an issue in the vscode repository http://github.com/Microsoft/vscode/issues.   There are already several issues about XML files so you may want to review these first. The vscode-docs repository is just for documentation issues and suggestions.

**Comment by shantj** [comment]
oh, yeah.  it is the same with #23
