### ISSUE TITLE
Editing Evolved and IntelliSense

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#520]
I am working on a new IntelliSense doc to address concerns found in usability studies. 

There is significant overlap between what _should_ go in the IntelliSense doc and what is already found in Editing Evolved. 

I recommend we find a resolution in the same pattern I took with the Intro Videos. Described below. 

IntelliSense takes from Editing Evolved
- Parameter Hints
- Go to Definition
- Go to Symbol
- Peek
- Reference Information (i.e. Find All References)
- Rename Symbol

Editing Evolved ends up with 
- Errors and Warnings (with a plug about Linters, although see #519 as a possible replacement for having this here)
- Multiple Selections
- Shrink / Expand Selections
- Column (box) text selection
- Folding
- Bracket Matching
- And other Tips and Tricks from github/micrsosoft/vscode-tips-and-tricks

I would make this section very heavy on animations as many of these features are better experienced in an animation than in writing. 

Essentially, I would suggest making Editing Evolved a Tips and Tricks doc. We don't need to rename it per `problems with renaming`

**Comment by waderyan** [comment]
We should consider having additional topics. 

Code Navigation
Refactorings

**Comment by gregvanl** [comment]
With the new TOC layout we have 
Basic Editing - selection, folding, 
IntelliSense - parameter hints
Code Navigation - Go to, Find All, Errors and Warnings, Rename
