### ISSUE TITLE
Announce `vscode-test` is deprecated

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-docs#5202]
As an extension author, I have not noticed that `vscode-test` had been deprecated for 7 months.  You had better announce that `vscode-test` is deprecated in the next release note of VS Code. It has not been announced in the past release notes.

See the download number for the last 7 days:

- https://www.npmjs.com/package/vscode-test:  27,051
- https://www.npmjs.com/package/@vscode/test-electron: 4,659

**Comment by gregvanl** [comment]
Hi @tamuratak Thanks for pointing this out. This will go out in the next 1.65 release notes.
https://github.com/microsoft/vscode-docs/commit/f789680b0f5da416c52e3a2b0ed16d8a7733a8d0
