### ISSUE TITLE
How to use graphics.h in vs code

### ISSUE THREAD

**Issue by 2311kamal** [microsoft/vscode-docs#5208]
Hlo I am Kamal 
Please tell me how to download and use graphics.h header file in vs code !!
Its urgent!

**Comment by gregvanl** [comment]
What platform and C++ toolset are you using?
Have you worked through one of the tutorials at https://code.visualstudio.com/docs/cpp?
For example, if you are on Windows and want to use the MinGW toolset, you can read https://code.visualstudio.com/docs/cpp/config-mingw.

**Comment by gregvanl** [comment]
No reply from user, closing
