### ISSUE TITLE
Drop "the" from "the basics"

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#521]
This is a small thing - why do we say "The Basics"? Nothing else has "The" in front of it
- The Basics
- The Extension Marketplace
- The Integrated Terminal

Seems like we have other nouns that could use emphasis...

**Comment by waderyan** [comment]
Or better yet, why don't we rename it to "Overview" to be consistent with the other TOC?

**Comment by gregvanl** [comment]
"Basics" by itself seems too small. People often talk about "the basics" or "covering the basics".
