### ISSUE TITLE
Notebook API docs reference unsupported built in renderer for 'application/json' mimetype

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode-docs#5216]
A breaking change In the Notebook API, as noted in  [#143300](https://github.com/microsoft/vscode/issues/143300) is not reflected in [this documentation](https://code.visualstudio.com/api/extension-guides/notebook):

Please change all mentions of 'application/json' to 'test/x-json' instead.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/650cc462639de28f40a32d7767773dc1208297ca
Thanks for calling this out!
