### ISSUE TITLE
Some control commands don't work for me in the terminal (Ctrl-R, Ctrl-A)

### ISSUE THREAD

**Issue by johnfn** [microsoft/vscode-docs#5221]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.63.2 
- OS Version: macOS Monterey, 12.1

Steps to Reproduce:

1. Open up Visual Studio Code
2. Open an integrated terminal
3. Type Ctrl-A

You expect this to bring the terminal cursor to the beginning of the line. However, this happens instead:

![image](https://user-images.githubusercontent.com/167745/151246231-4f536e8c-32cc-4659-8298-5f2cab7793c3.png)

Here's another command that doesn't work:

1. Open up Visual Studio Code
2. Open an integrated terminal
3. Type Ctrl-R

For this, literally nothing happens at all. Nothing gets inserted in the terminal. The desired result would be that bck-i-search starts, as it does in the normal terminal. However, that does not happen, either.

I've tried everything. I've disabled all my extensions. I've commented out all my user settings. I've disabled chording in the terminal. Nothing helps. 

Additionally, these commands work perfectly fine on my *other* laptop, which is also a macbook pro with apple silicon, and I use vscode settings sync, so I'm not sure what the difference is!

**Comment by wsshin** [comment]
I thank @miguelcoba.  I have been struggling with this issue, and you solution works.

**Comment by QuarticCat** [comment]
> Why this happens in vscode? I have no idea.

@miguelcoba I guess this is the case: you opened VSCode from an external terminal, thus the environment variables of this VSCode instance contain `EDITOR` & `VISUAL`, hence it's internal terminal contains them as well, and therefore the default viins keymap.

**Comment by hegdesaspect** [comment]
How to pass` Ctrl+Insert` ? I tried all the above methods. No luck. The log shows:

```
/ Soft dispatching keyboard event                                                                                                                                                                                                                                                           
| Resolving Enter
\ From 32 keybinding entries, no when clauses matched the context.
/ Received  keydown event - modifiers: [], code: Enter, keyCode: 13, key: Enter
| Converted keydown event - modifiers: [], code: Enter, keyCode: 3 ('Enter')
| Resolving Enter
\ From 32 keybinding entries, no when clauses matched the context.
/ Soft dispatching keyboard event
\ Keyboard event cannot be dispatched
/ Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
| Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
\ Keyboard event cannot be dispatched in keydown phase.
/ Soft dispatching keyboard event
| Resolving ctrl+Insert
\ No keybinding entries.
/ Received  keydown event - modifiers: [ctrl], code: Insert, keyCode: 45, key: Insert
| Converted keydown event - modifiers: [ctrl], code: Insert, keyCode: 19 ('Insert')
| Resolving ctrl+Insert
\ No keybinding entries.
+ Ignoring single modifier ctrl due to it being pressed together with other keys.
```

**Comment by Tyriar** [comment]
@hegdesaspect if ctrl+insert isn't working and no keybindings are found, you could try create a custom keybinding to send whatever you want: https://code.visualstudio.com/docs/terminal/advanced#_custom-sequence-keybindings

**Comment by hegdesaspect** [comment]
> [@hegdesaspect](https://github.com/hegdesaspect) if ctrl+insert isn't working and no keybindings are found, you could try create a custom keybinding to send whatever you want: https://code.visualstudio.com/docs/terminal/advanced#_custom-sequence-keybindings

Awesome! Thanks a lot. The following worked:

```
{
                "key": "ctrl+insert",
                "command": "workbench.action.terminal.sendSequence",
                "args": {
                    "text": "\u001b[2;5~"
                }
}
```

**Comment by johnfn** [comment]
This should be reopened because it's not fixed in VSCode. Although a workaround exists, there's no need for a workaround in any other terminal on my machine, so this is a VSCode bug. @Tyriar
