### ISSUE TITLE
CMake Tools on Linux :Debug hello world not stop on the break point

### ISSUE THREAD

**Issue by FuXiii** [microsoft/vscode-docs#5229]
When I follow the document: CMake Tools on Linux
When I mark a breakpoint on the std::cout line, and then run CMake: Debug command ,VSCode just jump over the breakpoint.
And I found the shortcut of CMake:Debug is Ctrl+F5, but In the  menu of Run the Ctrl+F5 is Run Without Debugging is that means the debugger will not stop at breakpoint？And I run CMake: Debug it just jump through the breakpoint.

**Comment by FuXiii** [comment]
I think I maybe found the answer:
In the github document of vscode-cmake-tools/debug-launch/quick debugging section, it said 
> Note: Only the debugger from Microsoft's vscode-ms-vscode.cpptools extension supports quick-debugging. See [Debug using a launch.json file](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#debug-using-a-launchjson-file), below, for information about launch.json and using other debuggers.

maybe I don't support the Microsoft's vscode-ms-vscode.cpptools extension. So I should use launch.json to run exe.

**Comment by gregvanl** [comment]
Hi @FuXiii Looks like you've found the CMake extension repository at https://github.com/microsoft/vscode-cmake-tools.
That is probably a better place to look for support, rather than the vscode-docs repository.
You might try creating an issue in vscode-cmake-tools to get help with your configuration.

**Comment by gregvanl** [comment]
Closing as no reply from user. They seem to have found the right repo for CMake Tools extension questions.
