### ISSUE TITLE
TypeScript/JavaScript 2.0 - switch from typings to npm install

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#524]
pls see:
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

TypeScript 2.0 will not be final for August.

**Comment by gregvanl** [comment]
Moving to November. May recommend ATA instead.

**Comment by gregvanl** [comment]
Covered in December doc-a-thon. Will do a final mop up of "typings" references with https://github.com/Microsoft/vscode-docs/issues/664
