### ISSUE TITLE
issue in running program in vs code

### ISSUE THREAD

**Issue by Manik400** [microsoft/vscode-docs#5249]
respected team
i am using vs code but it is not running .
i have download vs code and mingw both and path has been updated but not running prperly 
whenever i try to run a program in c language then a dropdown box open and the  i select c/c++(gdb/lldb) and then empty json.setting open only with curly brackets (refer picture ).
kindly help me what is the actuall problem 
i will be thankful to you.

![vscode prblm](https://user-images.githubusercontent.com/96019086/159556651-accdfd0e-b0d1-4c5b-84c5-7b27f0cdbcea.JPG)

**Comment by gregvanl** [comment]
Hi @Manik400 Sorry that you are having trouble running your C program.
To run and debug a C program, VS Code and the C++ extension should create a launch.json file. 
Do you have a .vscode folder in your project with a launch.json file?
The settings.json file in AppData is for your user settings and is not needed to run a C program.

**Comment by Manik400** [comment]
> Hi @Manik400 Sorry that you are having trouble running your C program. To run and debug a C program, VS Code and the C++ extension should create a launch.json file. Do you have a .vscode folder in your project with a launch.json file? The settings.json file in AppData is for your user settings and is not needed to run a C program.

@gregvanl  i have extension but may be i dont have .vscode folder with a launch.json file 
could you pls tell me what should i needed to do so that it run properly

**Comment by gregvanl** [comment]
To help you get started with MinGW, you can work through the tutorial at https://code.visualstudio.com/docs/cpp/config-mingw
While this tutorial focuses on C++, it does explain how to generate and use tasks.json for building a program in VS Code and launch.json for running and debugging a program.
If you get your configuration working for a simple C++ program, I think you should be able to also have a working configuration for C programs.

**Comment by gregvanl** [comment]
Closing as no response from user after providing a link to a tutorial
