### ISSUE TITLE
VS Code how to generate .vscode/settings.json automatically?

### ISSUE THREAD

**Issue by yjcreation** [microsoft/vscode-docs#5281]
Using a command prompt or terminal, create an empty folder called "hello", navigate into it, and open VS Code (code) in that folder (.) by entering the following commands:
`mkdir hello
cd hello
code .`
It does not generate a partial settings.json by opening the folder with the three commands above.

**Comment by gregvanl** [comment]
Hi @yjcreation If you change a user setting via the Settings editor (File > Preferences > Settings), a settings.json file will be created for you under your APPDATA folder.
The file is not created unless you have a setting value different than the default values.

**Comment by gregvanl** [comment]
Closing as explained when user settings.json is generated and no reply from user.
