### ISSUE TITLE
Add information about more languages to VSCode release notes

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode-docs#5293]
I would like to get information about other Microsoft extensions (like C++ or Java) that do not follow the VSCode release cadence in the VSCode release notes.

**Comment by gregvanl** [comment]
Hi @xiaoxi-david You can track updates to various extensions through their changelogs, viewable from the Extensions view Changelog tab.

![image](https://user-images.githubusercontent.com/12818376/165021275-5a7b2f94-77b3-4616-8d41-6e3e6034902c.png)

We do sometimes mention extension updates in the "Contributions to extensions" section of the release notes but only if there are significant updates or at the request of the extension's engineering team.

The release notes are already fairly long, it would be prohibitive to also include each Microsoft language extensions updates. Also, as you point out above, VS Code and the Microsoft programming language extensions release on a different cadence and not necessarily at the same time.

Thank you for the suggestion but closing as there have been no upvotes to this issue.
