### ISSUE TITLE
The `close` property and the `revealProblems` property are missing in the `presentation` property

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-docs#5296]
The `close` property and the `revealProblems` property are missing in the `presentation` property:

https://github.com/microsoft/vscode-docs/blob/7f86ed75689352e5ff9d2e8768755a0f80d60c1e/docs/editor/tasks.md?plain=1#L290-L304

- https://github.com/microsoft/vscode-docs/blob/main/docs/editor/tasks.md#output-behavior

See the following:

- https://github.com/microsoft/vscode/blob/fbdc6d03528cda982a3516b2c0b297917362f155/src/vs/workbench/contrib/tasks/common/jsonSchema_v2.ts#L120-L130

```
		revealProblems: {
			type: 'string',
			enum: ['always', 'onProblem', 'never'],
			enumDescriptions: [
				nls.localize('JsonSchema.tasks.presentation.revealProblems.always', 'Always reveals the problems panel when this task is executed.'),
				nls.localize('JsonSchema.tasks.presentation.revealProblems.onProblem', 'Only reveals the problems panel if a problem is found.'),
				nls.localize('JsonSchema.tasks.presentation.revealProblems.never', 'Never reveals the problems panel when this task is executed.'),
			],
			default: 'never',
			description: nls.localize('JsonSchema.tasks.presentation.revealProblems', 'Controls whether the problems panel is revealed when running this task or not. Takes precedence over option \"reveal\". Default is \"never\".')
		},
```

- https://github.com/microsoft/vscode/blob/fbdc6d03528cda982a3516b2c0b297917362f155/src/vs/workbench/contrib/tasks/common/jsonSchema_v2.ts#L162-L165

```
		close: {
			type: 'boolean',
			description: nls.localize('JsonSchema.tasks.presentation.close', 'Controls whether the terminal the task runs in is closed when the task exits.')
		}
```

**Comment by gregvanl** [comment]
Thanks for pointing this out!
