### ISSUE TITLE
Create a Walkthrough section

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#530]
We have walkthrough sprinkled in a lot of our topic pages. This is fine but can get too much as in the case of #448 

What we discussed is creating a "Walkthroughs" section, which is the natural place for the current Node.js walkthrough (rather than the Runtimes section). 

Before doing so we would want to create a couple more walk throughs. Namely, C#, C++, and Python are likely candidates.

**Comment by gregvanl** [comment]
We've decided not to add walkthroughs for other languages (C#, C++, Python) and only support landing/feature topics. Only our core languages TS/TS will have tutorials and they'll live under Node.js/JavaScript node
