### ISSUE TITLE
Environment doc improvements

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-docs#5300]
Some comments were made after https://github.com/microsoft/vscode-docs/pull/5260 was merged which got left out: https://github.com/microsoft/vscode-docs/pull/5260#pullrequestreview-937050267.

**Comment by rjmolyneaux** [comment]
Hey @karthiknadig, thanks for jumping in on this one! I updated the doc with PR #5308 ☺️. Let me know if I can add anything else.
