### ISSUE TITLE
Wrong statement and image

### ISSUE THREAD

**Issue by oriasis0** [microsoft/vscode-docs#5306]
Under:
https://code.visualstudio.com/docs/editor/extension-marketplace#_command-line-extension-management
There is the statement "You can see the extension ID on the extension details page next to the extension name." with corresponding image. In my VSC the id appear elsewhere.
There is another wrong iamge later, next to the statement "VS Code will provide you with auto-completion for installed extensions inside these files.".

**Comment by codewithdev** [comment]
@gregvanl Can you assign this to me. Can I work on this?

**Comment by codewithdev** [comment]
For the first statement, we need to replace the screenshot. Also the extension ID image is no longer supported in the current UI of VS Code.

**Comment by gregvanl** [comment]
Hi @codewithdev PRs are certainly welcome.

**Comment by gregvanl** [comment]
Fixed with #5313
