### ISSUE TITLE
md-file-rename.png and md-rename-header.gif seems to be the same

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode-docs#5321]
https://github.com/microsoft/vscode-docs/blob/1add2aab94d5c6863ed491d98a9d37798a0379fe/release-notes/images/1_67/md-file-rename.png
https://github.com/microsoft/vscode-docs/blob/1add2aab94d5c6863ed491d98a9d37798a0379fe/release-notes/images/1_67/md-rename-header.gif

https://github.com/microsoft/vscode-docs/blob/dc6d440590bfeabaf4c02cb5de524f1ebff6703c/release-notes/images/1_67/md-file-rename.png

It seems to be related to this: [History for release-notes/images/1_67/md-file-rename.png - microsoft/vscode-docs](https://github.com/microsoft/vscode-docs/commits/1add2aab94d5c6863ed491d98a9d37798a0379fe/release-notes/images/1_67/md-file-rename.png)

**Comment by gregvanl** [comment]
Thanks for pointing this out. There also looks like a duplicated link to the drop link .gif.
Will fix shortly
