### ISSUE TITLE
New language topic: ABAP

### ISSUE THREAD

**Issue by larshp** [microsoft/vscode-docs#5322]
Hi,
In the ABAP eco-system we have multiple plugins that are working pretty well and getting traction.

Are you open for a pull request adding ABAP to the language specific section, https://code.visualstudio.com/docs/languages/overview

https://marketplace.visualstudio.com/search?term=abap&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by gregvanl** [comment]
Hi @larshp Thanks for reaching out and your interest in the VS Code documentation.

I think you would actually get better engagement and page views on a site more scoped to the ABAP developer community. 
For example, when I search for "ABAP VS Code", I see results on the SAP community site, where there is an existing blog about configuring VS Code: https://blogs.sap.com/2019/12/06/abap-development-in-vs-code

You could also put documentation on one of the ABAP extension repos with a wiki or add a more detailed README.
Keeping documentation closer to extensions helps with maintenance as extension authors don't need to remember to go to another repo or site when there are extension updates.

A couple of other things you could think about are:
- create an ABAP Extension Pack, if there are several existing extensions that work well together
- create a verified publisher for the ABAP extensions https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher
These can help users install the right ABAP tools and know they are working with an established publisher

**Comment by larshp** [comment]
okay, closing
