### ISSUE TITLE
Improve Extension UX Guidelines

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-docs#5327]
Now that [UX Guidelines](https://code.visualstudio.com/api/ux-guidelines/overview) are a top-level API topic, I think it makes sense to continue improving the content. I'll address the following items:

- Improve Overview -> Architecture transition. Outline how to think about what an extension w/ UI can be and what the main pieces are in VS Code's UI. Could we take a lightweight visual "tour" through the UI and show what contributions could look like in each area?
- Show do/don't guidance visually. Link to/show samples where applicable.
- Clarify sidebar/panel/view container/view relationship
- Clarify quick pick/command palette relationship (while they are functionally different, their UI similarities can be confusing)
- Clarify our POV on when a webview is necessary
- Add guidance for:
  - Panel (e.g. when to contribute a view there)
  - Panel toolbar (if extensions can contribute here?)
  - View toolbar (e.g. # of icon buttons, icon buttons w/ menus vs. those opening quick pick)
  - Update images and use GIFs where appropriate

**Comment by gregvanl** [comment]
A couple other UX Guideline suggestions:
https://github.com/microsoft/vscode-docs/issues/4425
https://github.com/microsoft/vscode-docs/issues/4886

**Comment by daviddossett** [comment]
Closed via #5366
