### ISSUE TITLE
Common Issue with TypeScript

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#533]
From @dbaeumer in https://github.com/Microsoft/vscode/issues/10683#issuecomment-241354013

> if your project is based on https://github.com/AngularClass/angular2-webpack-starter then you need to tell VS Code that you want to use TS from the node_modules folder of the workspace folder. Angular2 webpack project don't work with TS 1.8.10 due to module resolving issues. You can instruct VS Code to use the TS from the local node_modules folder using the following setting: "typescript.tsdk": "./node_modules/typescript/lib"

The idea of changing the location of tsdk deserves a callout in the docs.

**Comment by gregvanl** [comment]
See https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions.
You may be able to generalize this section.

**Comment by waderyan** [comment]
A short paragraph describes this in PR #574
