### ISSUE TITLE
"code" is not listed as a supported launch config property

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-docs#5344]
`code` is documented here: https://code.visualstudio.com/docs/python/debugging#_module but not listed in the package.json as a config property for the "python" debug adapter.

Use this launch config:

```json
{
            "name": "demo bug",
            "type": "python",
            "request": "launch",
            "code":  "from json import loads; loads('123')",
            "console": "integratedTerminal"
}
```
Get this warning
![image](https://user-images.githubusercontent.com/323878/168138703-2a7e9fe4-33f4-4a83-8d89-f4aa72241774.png)

**Comment by gregvanl** [comment]
"code" was added to address this issue https://github.com/microsoft/vscode-docs/issues/5061
@rjmolyneaux can you chat with @karthiknadig about removing this mention in the topic?

**Comment by rjmolyneaux** [comment]
Thanks for the tag @gregvanl! I believe I removed the only mention of the `code` as an option -- @karthiknadig, are you able to double-check this please? ☺️

**Comment by karthiknadig** [comment]
@rjmolyneaux That looks right.

**Comment by rjmolyneaux** [comment]
Hi @roblourens, thanks for bringing this to our attention. You should expect to see the changes go live here, shortly. Please do not hesitate to reach out to us in the future!
