### ISSUE TITLE
Comments disappear under the video '/docs/introvideos/basics' on 'Youtube'

### ISSUE THREAD

**Issue by ilyachalov** [microsoft/vscode-docs#5345]
On the page:

https://github.com/microsoft/vscode-docs/blob/main/docs/introvideos/basics.md

video clip [is embedded](https://github.com/microsoft/vscode-docs/commit/1a60e97ea5db32e3639ad29cc0c269ccaae10b53) from 'Youtube':

https://www.youtube.com/watch?v=B-s71n0dHUk

Thus, this video has become part of the documentation [vscode-docs](https://github.com/microsoft/vscode-docs). That's why I'm writing about my problem here.

I tried to leave a comment under this video on 'Youtube':

![my-comment](https://user-images.githubusercontent.com/48008056/168652814-deda0eb9-f4aa-444f-8b4b-b10b3665dd37.png)

But my comment disappeared there:

![my-comment-disappeared](https://user-images.githubusercontent.com/48008056/168652819-fa29609f-643d-4420-9513-cc5eb88d210b.png)

Please tell me is this some kind of error or is it pre-moderation or is it a spam filter?

Thanks in advance.

**Comment by gregvanl** [comment]
Investigating. I'll reply here if I find out more.

**Comment by burkeholland** [comment]
Hey @ilyachalov! Following up on this per Greg's flagging of it on our internal chat. 

I looked into this and it doesn't seem like it was removed by the YouTube spam algorithm, and our vendor who does a manual sweep did not delete it either. Which means - we have no idea what happened!

My apologies that this happened. It means a lot that you took time to help another user.

**Comment by ilyachalov** [comment]
@burkeholland @gregvanl Thank you for your reply!

I now think 'Youtube' is responsible for this problem. Their forum ('YouTube Help Community') has collected thousands of descriptions of similar cases since July 2021:

https://support.google.com/youtube/thread/116351041/recent-reports-of-missing-comments
