### ISSUE TITLE
Forwarded Ports View documentation in Remote SSH docs wrong

### ISSUE THREAD

**Issue by damiangreen** [microsoft/vscode-docs#5351]
Issue Type: <b>Bug</b>

Im following the steps to connect to a machine over SSH. Which is successfully connected.
I'm trying to find the section to forward ports but it is nowhere to be found in the Remote [SSH] explorer

Extension version: 0.78.0
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Windows_NT x64 10.0.22000

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.47GB free)|
|Process Argv|--crash-reporter-id bf385c0d-6600-45a2-9b63-4fc215628c0a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: damo.zapto.org|
|OS|Windows_NT x64 10.0.22000|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3693)|
|Memory (System)|31.91GB (13.68GB free)|
|VM|29%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

![image](https://user-images.githubusercontent.com/1592820/166240245-12f47fe1-0678-40ee-8e56-3ff8cc05b452.png)

**Comment by stech11845** [comment]
I don't know if this is an issue with VS Code but um... it's something, maybe Docs.

**Comment by gregvanl** [comment]
The section on the new Ports view in the Panel was updated with 85b92c6ca9e1efffb1c65fdd469a001f87cc1136
