### ISSUE TITLE
[Extension Development] Please Provide Guidance for Extension README

### ISSUE THREAD

**Issue by ericdrobinson** [microsoft/vscode-docs#5357]
I am unable to locate any guidance on creating and managing a good README for a VS Code Extension I'm developing and plan to release on the [Marketplace](https://marketplace.visualstudio.com/vscode). Questions I would like this guidance to answer:

- What is a good default structure for the README?
- What type of information is recommended to include in the README?
- Are there any structural standards (e.g. lists vs tables) for documenting specific feature classes (e.g. commands, shortcuts)?
- Are there any standards for formatting specific features (e.g. commands, shortcuts)?
- Are the generated header-links that appear in the Marketplace the same as those that will appear in the Extensions View within VS Code?
  - In other words, can I rely upon both VS Code's Extensions View and the Marketplace to automatically add `id=header-name` to use the same exact algorithm in both cases such that I can use intra-page linking?
- What is the recommended way to add custom, non-header anchors to a page?
  - I.e. would something like:
    ```md
     - <a name="some-special-bullet-point"></a>**A Special Bullet Point**: Some description...
     ```
     result in a usable intra-page anchor that I could refer to elsewhere in the page with:
     ```md
     ... for more information, see [this bullet point](#some-special-bullet-point).
     ```
- What, if anything, is recommended to keep _out_ of a README?
- Are there any recommendations on sizing of images and/or what content to show with images?

And related. This information would be extremely helpful for any extension developer interested in delivering a well-documented product to the Marketplace.

**Comment by muditjuneja** [comment]
I can surely help with this @gregvanl. Let me know if you have a rough structure in mind, I can try and improve that.

**Comment by gregvanl** [comment]
Hi @ericdrobinson Thank you for entering a thoughtful issue and your interest in the VS Code documentation.
We haven't been prescriptive for extension READMEs mostly because given the wide range of VS Code extensions (simple command additions, themes, and keymaps all the way to full language services, debuggers, and embedded UI editors), there is a wide range of appropriate extension documentation. Some authors may have a brief explanation of their extension contribution or screenshot, while others spend time explaining the value proposition of their extension, provide short tutorials, and link out to other repos and wikis. What works well for one extension might not make sense for another.
Extension contributions such as commands, keybindings, and settings are automatically pulled from an extension's package.json and displayed in the Feature Contributions page in the Extensions view. While these are not shown on the Marketplace, I don't think authors should duplicate such tables and lists.
For formatting, you might want to follow the same Markdown formatting that we use for the VS Code documentation. You can review this at https://github.com/microsoft/vscode-docs/blob/main/CONTRIBUTING.md. For example, we use bold for UI elements and inline code blocks for files and settings.
Given the README is a Markdown file, you should be fine with header links as long as you conform to regular Markdown syntax.
When creating an extension README, I'd recommend reviewing the descriptions and rendering for some popular extensions that are of similar scope to your own.

**Comment by ericdrobinson** [comment]
@gregvanl Why was this closed? Does this somehow resolve the request for "documentation" for what a Marketplace README might contain (in both form and content)? You may have communicated something here to _me_, but it won't help others who follow (and don't think to search the Closed Issues in the VS Code Documentation site...).

Additionally, some direct responses:

> We haven't been prescriptive for extension READMEs mostly because given the wide range of VS Code extensions (simple command additions, themes, and keymaps all the way to full language services, debuggers, and embedded UI editors), there is a wide range of appropriate extension documentation.

I am not asking for prescription; I am asking for _guidelines_ (alternative word here: recommendations). Rather than "prescriptive", I'm looking for something "suggestive".

> Extension contributions such as commands, keybindings, and settings are automatically pulled from an extension's package.json and displayed in the Feature Contributions page in the Extensions view. While these are not shown on the Marketplace, I don't think authors should duplicate such tables and lists.

There are three aspects to this that I think your suggestion misses:

1. The Feature Contributions page is **unlinkable**. I cannot point a user to it and say "to enable feature X, use [this setting](#null)" or whatever. When I document, I like to err on the side of cross-linking concepts and features too much rather than too little and there is no affordance in the Feature Contributions page (especially as that isn't linked in the Marketplace - also... why not?).
2. The Feature Contributions descriptions support basically no formatting. Where I [duplicated such lists](https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug#advanced-configuration) in the documentation we provide in a table, the Description section includes intra-page links to other documentation and even bullet lists for easier-to-read descriptions of the features.
3. How many users do you think even _know to look for that page_?

> For formatting, you might want to follow the same Markdown formatting that we use for the VS Code documentation. You can review this at https://github.com/microsoft/vscode-docs/blob/main/CONTRIBUTING.md. For example, we use bold for UI elements and inline code blocks for files and settings.

This issue is about documenting this type of guidance in the extension development "manual". This helps me a bit here in this issue, but it is effectively undiscoverable guidance. Could this suggestion not be added to the docs somewhere instead of added in a comment to _request_ such documentation?

> Given the README is a Markdown file, you should be fine with header links as long as you conform to regular Markdown syntax.

No Markdown file uses "regular Markdown syntax". Part of this request is for you to add guidance/documentation that describes precisely what [flavor of Markdown](https://gist.github.com/vimtaai/99f8c89e7d3d02a362117284684baa0f) is recognized by the various systems that render the README file. Your [formatting](https://github.com/microsoft/vscode-docs/blob/main/CONTRIBUTING.md#formatting) page doesn't even mention whether it uses [GitHub Flavored Markdown (GFM)](https://github.github.com/gfm/) or not (I assume it does?). GFM itself is based on [CommonMark](https://spec.commonmark.org/), which _itself_ is finally based on the "original" [Markdown spec](https://daringfireball.net/projects/markdown/syntax).

There is no "regular Markdown syntax". Guidance here would be extremely helpful in determining what sorts of rendering is supported.

I would also like to point out that I found that [VS Code's Markdown preview feature](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) seems to respect intra-page links generated with `<a name="some-name">`. However, these appear to be _ignored_ in the Marketplace rendering. This is the type of thing I'd like to avoid having to figure out by publishing to the Marketplace and then having to publish a new version simply to fix "problems with the README".

> When creating an extension README, I'd recommend reviewing the descriptions and rendering for some popular extensions that are of similar scope to your own.

Sure? And that could be one suggestion that is documented in some form of "Extension README Guidance". 😄
