### ISSUE TITLE
The terminal process terminated with exit code: 259

### ISSUE THREAD

**Issue by KyanhdangVNP** [microsoft/vscode-docs#5377]
Help me, when I run my Python code, the terminal just crashes and showed up the message
"The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 259."
I have tried many ways to fix this but it didn't work, if anyone know how to fix it, please help me.
![image](https://user-images.githubusercontent.com/64181110/171557208-53cde4e0-d500-4a3e-adb5-016b5a2fd016.png)

**Comment by gregvanl** [comment]
Hi @KyanhdangVNP This looks like a terminal configuration or PowerShell issue and not specifically related to Python.
Here's a vscode product issue that talks about the error code you are seeing https://github.com/microsoft/vscode/issues/113738.
You can also select Open Help to go to https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch, which has some guidance on resolving terminal launch issues.

**Comment by KyanhdangVNP** [comment]
Wow, thank you so muck @gregvanl !
I have finnaly fixed it by killing some unused programs that run in background

**Comment by gregvanl** [comment]
Excellent! That makes sense since exit code 259 can mean STILL_ACTIVE, so killing some processes would help.
I can add a mention of this specific exit code in the "Troubleshoot Terminal launch failures" topic.

**Comment by gregvanl** [comment]
Here's the doc update to hopefully help other users in the future. Thanks for following up in this issue.
https://github.com/microsoft/vscode-docs/commit/3858007274cd5072fd13d9ed33584aac97a7bc39
