### ISSUE TITLE
Misleading section 'Navigation history' in article 'Visual Studio Code Tips and Tricks'

### ISSUE THREAD

**Issue by ilyachalov** [microsoft/vscode-docs#5378]
Section '[Navigation history](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_navigation-history)' in article '[Visual Studio Code Tips and Tricks](https://code.visualstudio.com/docs/getstarted/tips-and-tricks)' says
> Navigate entire history: `kb(workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup)`
> Navigate back: `kb(workbench.action.navigateBack)`
> Navigate forward: `kb(workbench.action.navigateForward)`

<br>**Issue 1.** These are two _different_ ways to navigate around the code. So you should write
> Navigate entire history: `kb(workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup)`
> 
> Alternatively, you can use 
> Navigate back: `kb(workbench.action.navigateBack)`
> Navigate forward: `kb(workbench.action.navigateForward)`

<br>**Issue 2.** The _essence_ of these ways of navigating the code is not described (or described incorrectly). You can write like this
> Navigate open files in current editor group: `kb(workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup)`
> 
> Alternatively, you can use (to navigate between edit locations in one or different files)
> Navigate back: `kb(workbench.action.navigateBack)`
> Navigate forward: `kb(workbench.action.navigateForward)`

<br>**Issue 3.** The _unusual_ use of keyboard shortcut in the first method of code navigation is not described. You can write like this
> Navigate open files in current editor group: `kb(workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup)`
> | `kbstyle(Ctrl)` | `kbstyle(Tab)` | Result of Command |
> | --- | --- | --- |
> | Down and hold... | Down and Up | Open the file list |
> | ...hold... | Down and Up | Moving through the file list |
> | ...up | - | Selecting a position in list and closing the file list |
> 
> Alternatively, you can use (to navigate between edit locations in one or different files)
> Navigate back: `kb(workbench.action.navigateBack)`
> Navigate forward: `kb(workbench.action.navigateForward)`
> 
> See [Quick file navigation](https://code.visualstudio.com/docs/editor/editingevolved#_quick-file-navigation) for details.

**Comment by gregvanl** [comment]
Closing as we want to keep the Tips and Tricks topic lightweight and easily scannable. See https://github.com/microsoft/vscode-docs/pull/5379 for more explanation.
