### ISSUE TITLE
Tasks Intro Section

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#538]
The new tasks document is an excellent improvement. Jumping into Hello World helped me understand tasks in a way I hadn't before (and I use tasks almost everyday). 

One suggestion is to make the contents of the document more explicit than the side nav. The hello world example is a great intro, but my impression is that some users will come to the page to use it as a reference to find examples for what they can do with tasks, such as in this [section](https://code.visualstudio.com/docs/editor/tasks#_examples-of-tasks-in-action). 

What if we created a short list at the end of the first section describing the contents of tasks document. 

First, we'll walk you through a simple Hello World example. Then we will show you ... Then this...

I believe this would help the reader find what they are looking for quicker.

**Comment by gregvanl** [comment]
Moving out of June as interns still actively investigating Tasks engagement.
