### ISSUE TITLE
Remove [Unsupported] references in supporting/faq

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#5380]
In the milestone https://github.com/microsoft/vscode/issues/151104 is done the docs will need an update: https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported

**Comment by Evavic44** [comment]
I understand. Will raise a PR for it now. Thanks.

**Comment by gregvanl** [comment]
Doc update merged into vscode-docs vnext
