### ISSUE TITLE
PR adding git commit message editing in the editor has been reverted and should be deleted from Release Notes mention

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode-docs#5385]
There is this line in the **Pull Requests** section:

[@JohnnyCrazy (Jonas Dellinger)](https://github.com/JohnnyCrazy): A full editor can be used as git commit message editor https://github.com/microsoft/vscode/pull/95266

but I believe that PR has been reverted and that functionality will not be vscode v1.68.

@lszomoru

**Comment by rmunn** [comment]
See discussion in https://github.com/microsoft/vscode/issues/150482 about the reversion.

**Comment by lszomoru** [comment]
I have removed the PR from the release notes, and marked it so that it gets included in the next release notes.
