### ISSUE TITLE
Problem running and debugging new c++ code on visual studio 

### ISSUE THREAD

**Issue by brother-antone** [microsoft/vscode-docs#5386]
I am new to coding and was setting up c++ on visual studio code for my mac.
I was following [this article](https://code.visualstudio.com/docs/cpp/config-clang-mac) step by step but my file is not running correctly.

In this article I made it all the way to the run hello world.cpp section up until step 4.
Step 4 shows that the code ran correctly and the tasks.json file was set up correctly.

However, when I run my code my computer shows this.
<img width="1632" alt="Screen Shot 2022-06-05 at 2 21 46 PM" src="https://user-images.githubusercontent.com/69770713/172064851-a70880de-50fc-4493-ac62-d776bda12a63.png">

I am really unsure what to do. Any help would be greatly appreciated.

**Comment by gregvanl** [comment]
Closing as pointed to troubleshooting section and no reply from user
