### ISSUE TITLE
CMake reports error, following installation of CMake Tools v1.11.25

### ISSUE THREAD

**Issue by BobT303** [microsoft/vscode-docs#5408]
I am running VSCode on Win10, building and running c++ on raspberry pi using gcc. Until today, everything worked fine.

The system is: Linux - 5.15.32-v7l+ - armv7l 

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

I have tried to uninstall CMake Tools v1.11.25 but the problem persists.
Thanks

**Comment by BobT303** [comment]
Found a workaround by adding the line below to my local settings.json, then deleting the contents of./build, then rebuilding everything.

"cmake.generator": "Unix Makefiles"

It looks like the default cmake generator is not being selected. Would be great if this was fixed.

**Comment by elahehrashedi** [comment]
Thank you for reporting this issue. Please follow the related issue from here  https://github.com/microsoft/vscode-cmake-tools/issues/2598.

**Comment by gregvanl** [comment]
Closing as linked to product issue.
