### ISSUE TITLE
Clarify that `.env` files are not read when doing environment variable substitutions in settings for the Python extension

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#5413]
Found via https://github.com/microsoft/vscode-python/discussions/19275#discussioncomment-2968020 . Essentially the confusion was thinking that something in a `.env` file could influence a setting, which it cannot.

**Comment by rjmolyneaux** [comment]
Hey @brettcannon! Can you shine your expertise to help me understand a little more? Does this note help or would you like me to work on the paragraphs above it? ☺️ 

![environment variables](https://user-images.githubusercontent.com/68129926/178837740-a452156c-f6d6-4a24-bc71-915d3276760a.png)

**Comment by rjmolyneaux** [comment]
Thank you for the clarification @brettcannon! I merged [5477](https://github.com/microsoft/vscode-docs/pull/5477) for this issue.
