### ISSUE TITLE
Misleading statement in vsce package/publish --pre-release docs

### ISSUE THREAD

**Issue by debonte** [microsoft/vscode-docs#5414]
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions says:

> For extensions to publish a pre-release version, a pre-release flag needs to be passed in the publish step:
> `vsce publish --pre-release`
> **Alternatively**, the pre-release flag can also be passed in the package step.

"Alternatively" implies that you can publish a pre-release package by packaging normally (`vsce package` without `--pre-release`) followed by `vsce publish --pre-release`. But if you do that, `vsce publish --pre-release` will fail with the following error:

> ERROR  Cannot use '--pre-release' flag with a package that was not packaged as pre-release. Please package it using the '--pre-release' flag and publish again.

Perhaps only doing `vsce package --pre-release` and then `vsce publish` without the `--pre-release` flag would work. I haven't tried that.

**Comment by isidorn** [comment]
@debonte thanks for filling this. I have just pushed a fix.
