### ISSUE TITLE
Minor typo in 'Node.js debugging in VS Code'

### ISSUE THREAD

**Issue by tramio** [microsoft/vscode-docs#5421]
In [Node.js debugging in VS Code](https://github.com/microsoft/vscode-docs/blob/main/docs/nodejs/nodejs-debugging.md), line 543, it looks like "Something" is to be replaced with "Sometimes".
> _Something_ you want to just log a message or value when code hits a certain location, rather than pausing. You can do this with logpoints. Logpoints don't pause, but rather log a message to the Debug Console when hit. In the JavaScript debugger, you can use curly braces to interpolate expressions into the message, like `current value is: {myVariable.property}`.

If possible, I'd like to work on this issue. 😃

**Comment by gregvanl** [comment]
Hi @tramio Thanks for spotting this! And feel free to submit a PR to fix the typo.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/7297942ffe8de24a844d7d20fea719a62b0fb11f
