### ISSUE TITLE
vscode-api doc page is crashing and slow to load

### ISSUE THREAD

**Issue by karthikmurakonda** [microsoft/vscode-docs#5429]
When an expandable is clicked on the [webpage](https://code.visualstudio.com/api/references/vscode-api#extensions) it becomes unresponsive for a few seconds, and chrome is not responding message is seen on the title bar of chrome.

https://user-images.githubusercontent.com/74945778/176257418-935bd2ef-eba6-4768-a727-09a33f4f46b0.mp4

Also, it takes much time to load all the page content(It is sometimes crashing on reloading too). It will be good if we use lazy loading or another solution.

**Comment by stech11845** [comment]
This might be a browser issue, you may need to report to Google Chrome.

**Comment by karthikmurakonda** [comment]
As I am in a different setup now everything is working fine. I guess something was wrong my side at that time,
