### ISSUE TITLE
Add a link to the new vscode discussions github repo

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-docs#5433]
Recently, a [VS Code Community Discussions](https://github.com/microsoft/vscode-discussions/discussions) GitHub repo was created for extension authors to ask questions and learn about updates to the extension ecosystem.

It would be great if this link was added to the [Looking for help](https://code.visualstudio.com/api#looking-for-help) section on the Overview page of the API docs.

cc @daviddossett

**Comment by hawkticehurst** [comment]
Also happy to make a PR with this change.

**Comment by isidorn** [comment]
Tackled via 93b5aa3de
fyi @olguzzar
