### ISSUE TITLE
Updates to Extension Manifest

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#544]
From @hamenon 
**Changes will go live next week so we should incorporate this in next Monday's website release**

We’ve fixed the issue where you wanted the resources link to the changed for VS Code extensions. Just to summarize the change:
Change "Support" to "Issues"
Change "Get Started" to "Repository"
Change "Learn" to "Homepage"
Here is a screenshot that highlights the change.
 
Previously the page showed:                                                                               
![image](https://cloud.githubusercontent.com/assets/2449568/18062105/4189814c-6dda-11e6-8372-113aae7560c5.png)

Now it shows:
 
![image](https://cloud.githubusercontent.com/assets/2449568/18062110/44e411cc-6dda-11e6-9107-03940609a384.png)

 
The **change will go live next week**, I just wanted to note that a documentation updated will be required here: https://code.visualstudio.com/docs/extensionAPI/extension-manifest
![image](https://cloud.githubusercontent.com/assets/2449568/18062119/52d9e586-6dda-11e6-8ded-42121e4a6124.png)
 

The first three will now need to see “Issues”, “Repository” and “Homepage”.

**Comment by gregvanl** [comment]
Moving to September as the Marketplace hasn't been updated yet.
