### ISSUE TITLE
use vscode.dev/theme where appropriate

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-docs#5448]
in the release notes we have a note for the theme being used for all the images/gifs. We should leverage vscode.dev/theme here so people can try out the theme.

![image](https://user-images.githubusercontent.com/1487073/177361727-b136d8b0-067c-4d0b-8a67-72fa70058680.png)

and in the doc page for themes, we could add a section on how to use vscode.dev/theme to share them.

https://code.visualstudio.com/docs/getstarted/themes

**Comment by gregvanl** [comment]
In the 1.71 release, we added a "(preview on vscode.dev)" link along with the Marketplace theme link.
We didn't want to replace the Marketplace link as that is most helpful for users wanting to install on VS Code desktop. The theme preview on vscode.dev, prompts user to install the theme on vscode.dev.
![image](https://user-images.githubusercontent.com/12818376/188166114-d09b093c-963c-4ad6-9d5b-15eeea0583f1.png)

**Comment by chrisdias** [comment]
cool, thanks! minor nit, suggest to make the whole line of text italicized...

![image](https://user-images.githubusercontent.com/1487073/188190850-91223a49-3803-4663-90ef-296143ea9ca7.png)

**Comment by gregvanl** [comment]
We started adding the "preview on vscode.dev" links in the August 2022 release notes 
https://code.visualstudio.com/updates/v1_71#_ffmpeg-codecs-support
