### ISSUE TITLE
Github extension link issue

### ISSUE THREAD

**Issue by Luximo** [microsoft/vscode-docs#5449]
Hi, I tried to click on the link
"[Install the GitHub Pull Requests and Issues extension]" 
The link isn't working, please fix it since I can't seem to find the extension directly from the extension store...
![image](https://user-images.githubusercontent.com/56436632/177377788-05ab03d1-ff96-41df-a9c6-b914cc9c6473.png)

**Comment by gregvanl** [comment]
Hi @Luximo Sorry, you're having trouble installing the extension via the website flow. What steps aren't working for you?
When you select the link, you should be prompted to open VS Code.

![image](https://user-images.githubusercontent.com/12818376/177386036-aa1d2bb4-bf4e-4cde-acb2-423d0a56b5f1.png)

Once VS Code launches, you should see the extension page for the GitHub Pull Requests and Issues extension should be displayed in the editor region with a blue button to install the extension.

![image](https://user-images.githubusercontent.com/12818376/177385781-f689763a-f984-43fc-a8d5-75b7009094f1.png)

Do you have VS Code installed on your machine?

**Comment by Luximo** [comment]
Yes, I do have vs code insider installed in my PC, I Just don't see any pop-up notification like yours though...

**Comment by Luximo** [comment]
I finally got it installed directly from my vscode insider market store, works fine now but I still can't install it directly from the link though...

**Comment by gregvanl** [comment]
What platform and browser are you using when you don't see the notification?

**Comment by Luximo** [comment]
I use chrome browser on windows 10

**Comment by gregvanl** [comment]
Works for me with the Chrome browser on Windows 11.
Do you have any browser settings that might be blocking the pop-up notification?

**Comment by Luximo** [comment]
It works on the stable release but not the insider... that normal...?

**Comment by gregvanl** [comment]
In this case, the URL in the link is `vscode:extension/GitHub.vscode-pull-request-github`, which launches VS Code Stable with the GHPRI extension selected.

The URL prefix would need to be `vscode-insiders:` to do the same for Insiders.

The URL launching syntax is covered in https://vscode-docs-main.azurewebsites.net/docs/editor/command-line#_opening-vs-code-with-urls

For the main docs, we expect most people will be using VS Code Stable or have both Stable and Insiders installed.

Very cool that you are an early adopter and using Insiders! I usually install both, which lets me have two isolated instances of VS Code. VS Code Stable for my main work and VS Code Insiders for testing new features.

In your case, to install on Insiders, you would need to search in the Insiders Extension view, either by the extension name or extension ID (GitHub.vscode-pull-request-github) and install from within Insiders.

**Comment by Luximo** [comment]
Oh... thanks for the info, I'll keep that in mind...

**Comment by Luximo** [comment]
I already have Vs code insider installed on my PC and it not showing that
pop up icon like yours...😰
