### ISSUE TITLE
wrong hyperlink

### ISSUE THREAD

**Issue by bighen** [Microsoft/vscode-docs#545]
This document vscode-docs/docs/setup/linux.md has ".deb" hyperlinked to amd64 package.
It should show all arch packages, Ihave spent a few hours running AMD64 binary on Intel...

**Comment by gregvanl** [comment]
Hi Henryk,
I'm not sure I understand your issue. Were you wanting the 32 bit versions of the packages?  
The Linux.md topic directs you to https://code.visualstudio.com/Download which has a link https://code.visualstudio.com/Download#linux32-downloads-stable.

**Comment by bighen** [comment]
Sorry, I was not much clear...
No, the problem is I want right Linux version.
There is a mess in Linux.md file.
The hyperlink under ".deb" goes to the amd64 file (code_1.4.0-1470329130_amd64.deb) and there is no other links to get the other architecture.Here:
https://code.visualstudio.com/docs/setup/linux
the hyperlink on the ".deb" label goes through this http://go.microsoft.com/fwlink/?LinkID=760868address, again wrong.
Playing with LinkID I managed to download a few install files including insiders 1.5 version but none of them was suitable for my Ubuntu 14.04...

So please sort it out :-)

**Comment by gregvanl** [comment]
Sorry, I still don't understand.  What do you mean by the "right Linux version"? The Download page has links to .deb, .rpm, and .zip for both 64 and 32 bit. I am running the 64 bit .deb version on my Ubuntu 14.04 installation without issue.
