### ISSUE TITLE
Broken extension link posted in VSCode v1.68 release notes

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode-docs#5452]
I was surprised and delighted to see my VSCode Web extension being featured in the VSCode v1.68 release notes: https://code.visualstudio.com/updates/v1_68

However when I clicked the link I realized that the URL seems to be broken an does not lead to any.
Posted: `https://marketplace.visualstudio.com/items?itemName=x`
Correct: `https://marketplace.visualstudio.com/items?itemName=Cloud-pipelines.pipeline-editor-vscode`
See https://github.com/microsoft/vscode-docs/commit/cd700465d2776b7e776db18a079d93c32598924d

Could there be an issue with the code that auto-generates this list?

P.S. If that's OK, I would be really happy if you could include the Pipeline Editor extension again (with the fixed link) in the next version release notes.
Thank you a lot for your great work!

**Comment by gregvanl** [comment]
We'll go ahead and add you to the next 1.69 release notes for good measure :-)

**Comment by gregvanl** [comment]
Added with https://github.com/microsoft/vscode-docs/commit/98eb119ec6edf7d1c4a6a4097f3d5ddf5ba8e0f3

**Comment by sandy081** [comment]
Sorry about this and Thanks @gregvanl for adding it to 1.69 release notes.
