### ISSUE TITLE
1.69 release notes contains confusing reference to 1.69.0 as next Insiders

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#5454]
https://github.com/microsoft/vscode-docs/blob/d0e306b7c8d29feb6b44f6b39d0bc095d233a50c/release-notes/v1_69.md?plain=1#L542

@sandy081 I think it will be odd when 1.69 ships if its release notes talk about 1.69 as the next Insiders.

**Comment by sandy081** [comment]
Good observation. Will correct it. Thanks.

**Comment by gregvanl** [comment]
Fixed in release notes
