### ISSUE TITLE
My change has not affected docs

### ISSUE THREAD

**Issue by stech11845** [microsoft/vscode-docs#5468]
I see this on my recent merged pull request #5467, with no change:
![image](https://user-images.githubusercontent.com/108250871/178644238-60e4b4e8-9b7a-4431-beb2-d287b83cc175.png)
Does it mean that they do it **after** the PRs are merged or what?

**Comment by gregvanl** [comment]
Publishing is a separate process from merging PRs. You change will likely go live sometime tomorrow.

**Comment by stech11845** [comment]
> Publishing is a separate process from merging PRs. Your change will likely go live sometime tomorrow.

Yeah, it has been a few hours since it was merged...
