### ISSUE TITLE
Command line page should explain how to install bash and zsh completions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#5482]
https://code.visualstudio.com/docs/editor/command-line doesn't mention completions but we have bash and zsh ones that are shipped to Linux (not macOS for some reason?). These would be good to have available on all platforms that support them. I don't have a machine atm to test if they're automatically picked up on Linux or need manually hooking up.

**Comment by joaomoreno** [comment]
Yeah makes sense. I think we never added them to macOS since that would require some sort of _installation step_. Maybe we pull it off by including them in `Contents` and have a command to install them, just like the CLI command.

**Comment by gregvanl** [comment]
Closing as not implemented for other platforms (macOS) and seems discoverable for Linux users used to command line completions.

**Comment by Tyriar** [comment]
Closing since the new terminal suggests won't depend upon this.
