### ISSUE TITLE
A more understandable 'available' symbol in the extension hosts page

### ISSUE THREAD

**Issue by danBamikiya** [microsoft/vscode-docs#5483]
The 'x' mark in the table showing which extension hosts are available in the various configurations of VS Code is confusing for users, spent several minutes trying to figure out if it meant 'available' or 'unavailable'. A more understandable symbol would be '✓':
![image](https://user-images.githubusercontent.com/58262528/179863777-39c33693-7317-4e6c-9e27-ccde740fe633.png)

**Comment by gregvanl** [comment]
Good suggestion!
