### ISSUE TITLE
Add new theme settings to VS code docs

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-docs#549]
In August release, we exposed following theme settings to theme writers. These needs to be added to our documentation so that users can find and use them while coming up with themes

https://code.visualstudio.com/docs/customization/themes

- `rangeHighlight`: Background color of range highlighted, like by Quick open and Find features.
- `selectionHighlight`: Background color of regions highlighted while selecting.
- `inactiveSelection`: Background color of selections when not in focus.
- `wordHighlight`: Background color of a symbol during read-access, like reading a variable.
- `wordHighlightStrong`: Background color of a symbol during write-access, like writing to a variable.
- `findMatchHighlight`: Background color of regions matching the search.
- `currentFindMatchHighlight`: Background color of the current region matching the search.
- `findRangeHighlight`: Background color of regions selected for search.
- `activeLinkForeground`: Color of active links.
- `hoverHighlight`: Background color when hovered.
- `referenceHighlight`: Background color of a reference when finding all references.
- `guide`: Color of the guides displayed to indicate nesting levels.

**Comment by gregvanl** [comment]
@sandy081 Let me know if you think this update to themes.md covers it.

**Comment by sandy081** [comment]
@gregvanl Yes, it looks good. Thanks.
