### ISSUE TITLE
Configuring VS Code problem

### ISSUE THREAD

**Issue by moistantiseptic** [microsoft/vscode-docs#5492]
hello
I have problem in Configuring VS Code.
https://code.visualstudio.com/docs/cpp/config-msvc
I read this and followed steps.

and finally I tried to build hello world.
but i got this messege.

" cl.exe /Zi /EHsc /nologo /FeY:\newlect\main.exe Y:\newlect\main.c++
cl : Command line warning D9024 : unrecognized source file type 'Y:\newlect\main.c++', object file assumed
Y:\newlect\main.c++ : fatal error LNK1107: invalid or corrupt file: cannot read at 0x47 "

I searched web to find similar case. 
but most of issues were happend during programming, not configuring
why did I got this LNK1107 error?

I am using this vsc version
Version: 1.69.2 (system setup)
OS: Windows_NT x64 10.0.19044

and vs 2019 version : 16.11.17

**Comment by gregvanl** [comment]
Hi @moistantiseptic It looks like the compiler is having trouble with the `.c++` filename extension. 
The tutorial recommends using the filename `helloworld.cpp`. What happes if you use the `.cpp` filename extension?

**Comment by moistantiseptic** [comment]
thank you!
I got out of the problem!
