### ISSUE TITLE
No content on using regular expressions for finding text?

### ISSUE THREAD

**Issue by nielsbom** [microsoft/vscode-docs#5496]
Hi,

I could write some docs for using regular expressions in VS Code, but I just wanted to check that I didn't miss any existing content.

What I did find:
* [Basic Editing](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options) mentions regex but doesn't explain it or point to more docs.
* [Tips and Tricks](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_search-and-modify) has a bit about using regexes to capture replace, but nothing basic.

Am I overlooking something? Is this something that's wanted?

Thanks!

**Comment by gregvanl** [comment]
Hi @nielsbom We mention the regex101 site in the Tasks documentation at https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher.
Maybe adding similar notes to Basic Editing and Tips and Tricks would be helpful.
I don't think the VS Code docs should go into too much detail teaching people about regex but a simple example in the Basic Editing search section might be nice.

**Comment by nielsbom** [comment]
Hi @gregvanl 👋 

Yeah that sounds doable.

I agree that "a course on regex" is not what the docs need.

I'll write something and then you can shoot at it :-)

**Comment by gregvanl** [comment]
Closing as interest has waned

**Comment by PeterConstable** [comment]
The Basic Editing page should at least have a pointer to documentation for the regex flavour being used. (I thought it used to have a pointer to .Net regex documentation.)
