### ISSUE TITLE
I can't run my python program in the VS code. 

### ISSUE THREAD

**Issue by mohammedALASAD** [microsoft/vscode-docs#5509]
every time I run my python code, the output screen give this massage:

[Running] python -u "/Users/mohammedalasad/Desktop/PY/F.py"
/bin/sh: python: command not found

[Done] exited with code=127 in 0.006 seconds

IDK what is the problem. I download the python and python extinction also. 
If you know the solution please tell me.

**Comment by gregvanl** [comment]
Hi @mohammedALASAD @rjmolyneaux Looks like VS Code is having trouble finding your Python installation.
You might try working through the Python Tutorial at https://code.visualstudio.com/docs/python/python-tutorial, which should walk you through installing Python and verifying the installation.
What platform (Windows, macOS, or Linux) are you on and does Python come already installed?

**Comment by gregvanl** [comment]
Closing as no response from user
