### ISSUE TITLE
Instructions on configuring vscode for chrome extensions debugging

### ISSUE THREAD

**Issue by ElderOrb** [microsoft/vscode-docs#5513]
**Is your feature request related to a problem? Please describe.**

At the moment it is not clear how to configure vscode for debugging chrome extensions (or whether it is even possible) so some simple tutorial would be helpful. 

**Describe the feature you'd like**

I'd like to get step-by-step instruction for configuring vscode for chrome extensions debugging

**Comment by gregvanl** [comment]
This isn't currently possible with VS Code but you can follow https://github.com/microsoft/vscode-js-debug/issues/945 to track progress
