### ISSUE TITLE
Clarify docs for Python venv

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/vscode-docs#5565]
In the [docs](https://code.visualstudio.com/docs/python/environments) it says:

> ## Where the extension looks for environments[#](https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments)
> Virtual environments located directly under the workspace (project) folder.

Could this be clarified? In what folder does the virtual environment have to be to be discovered?

**Comment by rjmolyneaux** [comment]
Hi @danielniccoli, thanks for bringing a potential issue to our attention. It appears the documentation is referring to the virtual environment that was selected for the project folder created. 

Are you able to provide us with more information, so that we can better address your concerns?

**Comment by danielniccoli** [comment]
Let me expand the quote:

> ## Where the extension looks for environments[#](https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments)
> The extension **automatically** looks for interpreters in the following locations:
>
>   - Standard install paths such as /usr/local/bin, /usr/sbin, /sbin, c:\\python27, c:\\python36, etc.
>   - **Virtual environments located directly under the workspace (project) folder.**
>   - Virtual environments located in the folder identified by the python.venvPath setting (see [General Python settings](https://code.visualstudio.com/docs/python/settings-reference#_general-python-settings)), which can contain multiple virtual environments. The extension looks for virtual environments in the first-level subfolders of venvPath.
> [...]

When you select something, this is a manual task. Of course the extension will then look where you told it to look. In my case, I had a virtual environment in the root folder and it was not selected automatically, so I tried to understand what condition must be met. Is the name of the venv folder relevant? Must it be a specific name? Can it be `venv-whatever-floats-your-boat`?

**Comment by karrtikr** [comment]
If no interpreter has previously been selected for the workspace, we autoselect the best one, which should be the virtual environment in the workspace in your case. Try clearing the selected interpreter using `Python: Clear Workspace interpreter setting` command, and remove python.defaultInterpreterPath from **User** settings.
