### ISSUE TITLE
Better Debug documentation for TypeScript

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/vscode-docs#5580]
I'm reading through https://code.visualstudio.com/docs/languages/typescript with the eyes of a TypeScript beginner and I believe [Debug Server-Side](https://code.visualstudio.com/docs/languages/typescript#_debug-server-side) should be improved.

It says:

> Debug Node.js in VS Code using the built-in debugger. Setup is easy and there is a [Node.js debugging tutorial](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial#_debug-your-express-app) to help you.

There are two things I would criticise:

1. If setup is easy, I'd expect that one of two things would work:
    - Start debugging by pressing <kbd>F5</kbd>, see it hit a breakpoint and see "Hello World" printed to the terminal.
    - Creating a default launch.json file with the before mentioned Node.js configuration, that leads to the same result as above when a debug session is started.
    Both achieve the same thing, with the difference then one stores the configuration in a file. But both call `node.exe ./helloworld.ts`, which naturally results in a SyntaxError. I would not call this "easy" in a documentation that is clearly targeted towards absolute beginners on "Hello World" level.

2. The link to the "[Node.js debugging tutorial](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial#_debug-your-express-app)" leads to a tutorial about how to debug a Express app. There are two things problematic with that:
    - The tutorial does not mention TypeScript compilation or debugging at all.
    - It doesn't help in the immediate attempt to setup a *TypeScript* debugger. Instead, it potentially overloads the reader with information about a framework that they are potentially unable to contextualise.

To improve the documentation, I would suggest that a basic or minimal working example is provided, so that after reading this tutorial, he is not only able to compile a Hello World, but also to set a break point, start the debugger and see the "Hello World" being printed to the server-side console.

**Comment by kinkeadian25** [comment]
Would it be alright if I made a PR for the change suggested by @weinand? Thanks!

**Comment by danielniccoli** [comment]
I think that's a good start! When the PR get's approved, this issue can be closed.

**Comment by kinkeadian25** [comment]
@danielniccoli, thanks a lot! Anything else you want to see changed I am happy to work on!

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/5807

**Comment by kinkeadian25** [comment]
@gregvanl Thanks so much!
