### ISSUE TITLE
Clarify extension unique name restriction

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#5584]
Extension authors are confused about duplicate name errors. This is due to the fact that the Marketplace decided to make extensions unique on the name, as opposed to the publisher.name until recently. It's not clear for ext authors that (1) this change was made and (2) what the error is really about.

We should create a central documentation location we can direct them to, which makes it clear that the rules have changed? And, could we have the MP return a better error message?

The docs should be on the VS Code side and a disclaimer in vsce's README.md.

Examples of issues:
https://github.com/microsoft/vscode-vsce/issues/682#issuecomment-1198351782
https://github.com/microsoft/vscode-vsce/issues/761

@prashantvc agreed to drive this :)

Once we have better docs we should comment on those GitHub issues and clarify the confusion?

fyi @joaomoreno

**Comment by prashantvc** [comment]
@isidorn I think we can close this

**Comment by isidorn** [comment]
Thanks for updating the docs to make this more transparent!
Let's go ahead and close this, and I commented in your PR with some polish items. @prashantvc can you please also tackle them? Thanks!
