### ISSUE TITLE
Document the `enumItemLabels` option

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docs#5585]
In https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema, there is a section entitled "enum / enumDescriptions" that discusses setting enum values for configuration in extensions. There is also an `enumItemLabels` options (PR here: https://github.com/microsoft/vscode/issues/117696) that should be added to the documentation. The key advantage is that it allows human-readable labels to be used in places of machine-readable values in the settings UI, while the actual setting value itself remains machine-readable.

**Comment by isidorn** [comment]
@rzhao271 since me added this in this milestone we can also document it in endgame.
If you are busy let me know and I can also take a look into documenting this. Thanks!

**Comment by rzhao271** [comment]
Closing the issue because the PR has been merged.
Maybe GitHub doesn't like that the PR isn't in main, yet.
