### ISSUE TITLE
Explain theme creation and vscode-specific tmTheme properties in extensibility reference

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#561]
One of the frustrations when adapting a theme for vscode is that it's difficult to know what it supports exactly. https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesthemes is rather lacking currently.

See https://github.com/Microsoft/vscode/issues/11354

**Comment by sandy081** [comment]
Duplicates #549
