### ISSUE TITLE
WSL docs use deprecated Chrome Debugger as extension example

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-docs#5628]
See https://code.visualstudio.com/docs/remote/wsl

<img width="774" alt="image" src="https://user-images.githubusercontent.com/8599/189698646-9be89b56-9f02-41fb-ba00-27afc4e2a336.png">

I propose to switch it to a different example. cc @bamurtaugh

**Comment by bamurtaugh** [comment]
Good call out. Maybe a language extension, like Python?

**Comment by gregvanl** [comment]
@digitarald @bamurtaugh The Python extension is now an extension pack including three extensions Jupyter, isort, and Pylance. 
How about a simpler language extension like the Go extension for the example.
Or could you think of another first party extension to use?

**Comment by gregvanl** [comment]
I decided to use the rust-analyzer language extension in the examples.

**Comment by bamurtaugh** [comment]
Thanks Greg! Sounds like we can close this issue?

**Comment by gregvanl** [comment]
In the PR review, Rob thought that the rust-analyzer was probably already a workspace extension.
Any ideas for a UI extension to use as an example?
