### ISSUE TITLE
请问这个是啥意思啊  不知道为啥出现找不到code的问题

### ISSUE THREAD

**Issue by Ouweiming** [microsoft/vscode-docs#5635]
教程：在macOS终端中，创建一个名为projects空文件夹，您可以在其中存储所有VS Code项目，然后创建一个名为helloworld的子文件夹，导航到其中，并通过输入以下命令在该文件夹中打开VS Code：

mkdir projects
cd projects
mkdir helloworld
cd helloworld
code .
问题：(已经安装了vscode的）<img width="168" alt="截屏2022-09-16 11 20 36" src="https://user-images.githubusercontent.com/113448684/190549825-4b2ded39-8dcd-4fe4-8148-f719984dfcc9.png">

**Comment by gregvanl** [comment]
Hi @Ouweiming You may need to add VS Code to your macOS PATH. 
You can do so with the "Shell Command: Install 'code' command in PATH" command available from the Command Palette.
https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

**Comment by Ouweiming** [comment]
你好@gregvanl   我还想请问下为啥我之后运行"Hello world"一直报错
<img width="259" alt="截屏2022-09-18 23 14 34" src="https://user-images.githubusercontent.com/113448684/190914426-db67e218-5bce-4d4f-898c-e6b57d20fb64.png">

<img width="500" alt="截屏2022-09-18 23 15 00" src="https://user-images.githubusercontent.com/113448684/190914428-ed8e9f4c-0950-4517-8f0b-784b7b09b50a.png">
<img width="533" alt="截屏2022-09-18 23 25 02" src="https://user-images.githubusercontent.com/113448684/190914940-ee032848-5393-4c31-bce9-8452d45565cf.png">

**Comment by Ouweiming** [comment]
Thanks a lot for your solution. @gregvanl

**Comment by gregvanl** [comment]
Closing as the recommendation helped the user.
