### ISSUE TITLE
Using GCC with MInGW

### ISSUE THREAD

**Issue by mailaenderl** [microsoft/vscode-docs#5636]
I'm using these instructions: https://code.visualstudio.com/docs/cpp/config-mingw

However, at Step 4, we are redirected to a MSYS2 website...the PACMAN step there is step 6, there is no PACMAN as a Step 7.

It's not clear how to use the instruction "especially Step 7, when you will install the actual Mingw-w64 toolset (pacman -S --needed base-devel mingw-w64-x86_64-toolchain)."

I skipped the 'pacman --needed...' and used some default selection.. this may be causing me a problem?

thanks.

**Comment by gregvanl** [comment]
Hi @mailaenderl Have a look at https://github.com/microsoft/vscode-docs/pull/5599. While not merged and published yet, it outlines the new instructions.
If these instructions works for you, it would be great to let us know in that PR.

**Comment by gregvanl** [comment]
You will also need to install the full Mingw-w64 toolchain (`pacman -S --needed base-devel mingw-w64-x86_64-toolchain`) to get the `gdb` debugger.

**Comment by gregvanl** [comment]
Instructions have been updated.
