### ISSUE TITLE
VS Code comes up as empty shell when launched

### ISSUE THREAD

**Issue by roddharris** [Microsoft/vscode-docs#566]
I've installed VS Code on 3 Windows 10 machines.  

1. No Visual Studio installed.  
2. Visual Studio 2015 installed.
3. Hyper V VM with Visual Studio 2015.

On both machines with VS 2015, when I launch VS Code, I get an empty shell with a menu bar -- no status bar, side bar, view bar, etc.  I can use the menu to open a folder and it will allow me to select the folder, but nothing ever opens.

The only install I've had success with is the install on a machine without a copy of Visual Studio.

Is it not possible to run VS Code side by side with Visual Studio 2015?

**Comment by gregvanl** [comment]
We haven't seen any problems with VS Code side by side with Visual Studio and they shouldn't be sharing any binaries or settings.
We have seen similar [symptoms](https://code.visualstudio.com/Docs/supporting/faq#_vs-code-main-window-is-blan) due to some types of GPU hardware acceleration. Give the `--disable-gpu` switch a try.

**Comment by roddharris** [comment]
That doesn't seem to help in the case of the VM.  I had tried that in earlier attempts and tried it again just now.  Interesting that the hyper-v host runs Code with no issues but the VM running inside the host does not.  You'd think they'd be using the same graphics hardware, etc.

**Comment by gregvanl** [comment]
I'm running VS Code side by side with VS 2015 on a VM with Windows 8.1 and not seeing any issues.  I just installed VS 2015 Update 3 to see if that would cause a problem but seems fine.
This isn't really a documentation issue, I'll close this. Feel free to open a new issue in the main vscode repository https://github.com/Microsoft/vscode/issues
