### ISSUE TITLE
Feature request: Show content of updates in RSS feed

### ISSUE THREAD

**Issue by theS1LV3R** [microsoft/vscode-docs#5663]
In the RSS feed provided on the updates page on the website (<https://code.visualstudio.com/feed.xml>) each entry is simply a link to the VSCode updates website, <https://code.visualstudio.com/updates/v1_71> in the case of the latest update. It would be really nice if the content was the actual update notes, i.e. the content on the update site.

**Comment by gregvanl** [comment]
Closing as no upvotes and putting the entire release notes in the feed might be problematic given the size of the rendered Markdown, images, and videos.
The release notes are rendered in-product via Help > Release Notes and on the website under code.visualstudio.com/updates.
