### ISSUE TITLE
Add doc to explain the benefit of Timeline view, especially when I commit my changes often

### ISSUE THREAD

**Issue by qiulang** [microsoft/vscode-docs#5664]
I run git commit quite frequently. So what benefits does the timeline provide in my case ?

Also https://code.visualstudio.com/updates/v1_44#_timeline-view mentioned "This is a unified view for visualizing time-series events (for example, Git commits, file saves, test runs, etc.) for a file."

What is test runs ? I feel I never see them.

Thanks.

**Comment by gregvanl** [comment]
The Timeline view is extensible so extensions in the future can contribute TimelineProviders (still a proposed API at this point https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.timeline.d.ts).
The release notes were written with this extensibility in mind. A test run TimelineProvider has not been implemented yet.

Right now you can filter a timeline to either Git History (commits) and/or Local History (file saves).

![image](https://user-images.githubusercontent.com/12818376/235256419-b835ed1d-a880-48ab-8b3e-f0d1f3c7dea8.png)
