### ISSUE TITLE
variables-reference page add ${fileDirnameBasename}

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-docs#5673]
added in https://github.com/microsoft/vscode/issues/78316
https://code.visualstudio.com/updates/v1_52#_new-variables-for-launchjson-and-tasksjson

**Comment by ahlinc** [comment]
Also it would make sense to do document another [`fileWorkspaceFolderBasename`](https://github.com/microsoft/vscode/pull/167983) variable that closes https://github.com/microsoft/vscode/issues/159795 when its PR becomes merged.
