### ISSUE TITLE
Document how the Python extension chooses an environment

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#5679]
https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments

**Comment by gregvanl** [comment]
@luabud @karthiknadig I can reorder the list if this is documented somewhere. Also happy to take a PR or email outlining the search order

**Comment by karthiknadig** [comment]
@karrtikr can provide the details.

**Comment by karrtikr** [comment]
There's no order guaranteed in which the extension performs the search, just whatever we get as soon as possible.


Generally conda environments take the most time to be found.

**Comment by karrtikr** [comment]
@brettcannon I think this issue can be closed, unless I'm missing the intent.

**Comment by brettcannon** [comment]
Someone was asking how we determine which interpreter we end up selecting. I naively was thinking it was influenced by order. I have tweaked the title accordingly. It also wouldn't hurt documenting we make no guarantees about search order.

**Comment by karrtikr** [comment]
Ah I see, perhaps https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments wouldn't be the best place for it then. Suggestion:

- Add a section below it saying "How the extension chooses an environment".
- The following text can start off the section:

  > You can also [manually specify an interpreter](https://code.visualstudio.com/docs/python/environments#_manually-specify-an-interpreter) if Visual Studio Code doesn't locate your interpreter automatically.
  
  If one isn't manually specified by the user, then the extension automatically selects the environment in the following fashion:
  - Virtual environments located directly under the workspace (project) folder.
  - Virtual environments related to the workspace (project) but stored globally. For eg. [Pipenv](https://pypi.org/project/pipenv/), [poetry ](https://python-poetry.org/)etc. create environments this way.
  - Globally installed interpreters.
  
  Within each group, interpreter with the highest version is selected. Note this may differ from what `python` refers to in your terminal.

Btw I noticed the text below is outdated and can be removed:

  > Note: Once the ["select interpreter" flow](https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment) is triggered, [pipenv](https://pipenv.readthedocs.io/) environments for the workspace folder will be searched for. If one is found, then no other interpreters are searched for or listed as pipenv expects to manage all aspects.

**Comment by eevmanu** [comment]
Hi @karrtikr 👋, I made the [question](https://twitter.com/eevmanu/status/1576974353853337611) and your answer here explain it in very precise way. Thanks.

---

> - Virtual environments located directly under the workspace (project) folder.
> - Virtual environments related to the workspace (project) but stored globally. For eg. [Pipenv](https://pypi.org/project/pipenv/), [poetry ](https://python-poetry.org/)etc. create environments this way.
> - Globally installed interpreters. For eg. the ones found in /usr/local/bin, c:\\python27, c:\\python36, etc.
> 
> Within each group, the interpreter with the highest version is selected.

This is really useful, makes sense with a comment I found in the logic to define the **Recommended** interpreter https://github.com/microsoft/vscode-python/blob/26b614b739745a620bec661e4e48b1d27392ea48/src/client/interpreter/configuration/environmentTypeComparer.ts#L33-L41 (which I assume is up to date).

---

(quick suggestion - probably not the best place to do it, sry about that -, looks like these comments talking about the **order of detection** https://github.com/microsoft/vscode-python/blob/26b614b739745a620bec661e4e48b1d27392ea48/src/client/pythonEnvironments/base/info/envKind.ts#L35-L54 are not fully inline of what you describe in lines above, or maybe I misunderstood them)

**Comment by karrtikr** [comment]
> order of detection

Yep that's a different thing, it's useful when detecting the kind of an environment, i.e which tool is responsible for creating it.

**Comment by gregvanl** [comment]
Closing as sounds like users shouldn't take a dependency on the order since it might change. 
Also no dedicated writing resources for the Python extension topics. Happy to review and merge a PR if someone feels that this order should be documented.
