### ISSUE TITLE
Using a newer version of JavaScript

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#568]
JavaScript is powered by TypeScript, Currently we only document how to use a newer version of TypeScript in the TypeScript section of the documentation. 
https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions
We cannot assume that a JavaScript developer reads the TypeScript documentation. Therefore we should also like the section 'how os use a newer version of TypeScript'  from the JavaScript section.

@waderyan

**Comment by waderyan** [comment]
Thanks @egamma. Dup of #553
