### ISSUE TITLE
Command code does not work

### ISSUE THREAD

**Issue by Leo-Maxwell** [microsoft/vscode-docs#5695]
I tried to follow the tutorial, but when executing command `code .`, it suggests that this command does not exist.
<img width="225" alt="image" src="https://user-images.githubusercontent.com/32949795/194736348-8083b4c5-f6aa-4769-ab8c-67c7c52fec14.png">
I use macOS 12.6 with M1 Max, and the latest VScode.
The tutorial I was following is https://code.visualstudio.com/docs/cpp/config-clang-mac

**Comment by gregvanl** [comment]
Hi @Leo-Maxwell Is VS Code on your PATH? You can add it via the "Shell Command: Install 'code' command in PATH"

https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

**Comment by Leo-Maxwell** [comment]
Thank you for your support and the problem is fixed.
