### ISSUE TITLE
List of all language ids

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-docs#572]
We need a table of all language ids as a reference to extension writers. That table will include all the language ids from the language extensions we maintain, but also for languages from external extensions

**Comment by gregvanl** [comment]
@aeschli Let me know if you'd like other language identifiers added. I didn't want the table to get too long and included those I thought made sense.  I also created https://github.com/Microsoft/vscode/issues/11984 to show the language id in the Extensions Contributions details.  Once that is fixed, I will update the "Language Id" section to point users there for extension language ids.
