### ISSUE TITLE
JSONC documentation seems incomplete, doesn't mention trailing commas

### ISSUE THREAD

**Issue by ell1e** [microsoft/vscode-docs#5728]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Online Documentation Issue
- OS Version: Linux

Steps to Reproduce:

1. Go here https://code.visualstudio.com/docs/languages/json#_json-with-comments
2. Check for any mention in trailing commas and difference in their treatment. You'll likely find none. (I didn't.)
3. Open a `.json` file in VS Code and a `.jsonc` file in VS Code. In a JSON file, if you insert a trailing comma it will show up as a red error "problem", in the JSONC file as a yellow triangle warning "problem". It therefore seems like trailing commas in JSONC are merely discouraged, not invalid.

I suggest the documentation should therefore be edited/expanded to say that the "JSON with Comments" format also allows trailing commas even though they remain discouraged. (This would be less of an issue if there was a format spec somewhere, but since there doesn't seem to be, it seems more important for that documentation section to be exhaustive.)

**Comment by gregvanl** [comment]
Will be published at the 1.73 release, likely first week of November

**Comment by ell1e** [comment]
For what it's worth, I find the wording "tolerates" slightly ambiguous. I think "allows" or "accepts" would be better with an additional note that they're still not encouraged, if that's important to note.

**Comment by gregvanl** [comment]
https://github.com/microsoft/vscode-docs/commit/23664d3b1171ddc19c040742c21374dd3458de08

**Comment by ell1e** [comment]
Thanks so much, that seems perfect!!
