### ISSUE TITLE
No mention of Attach to Process in debugging doc

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#573]
We should mention attach to process in the debugging docs.

**Comment by gregvanl** [comment]
There is a mention in the initial launch.json configuration and in the Node.js debugging section http://code.visualstudio.com/docs/editor/debugging#_attaching-vs-code-to-nodejs

**Comment by gregvanl** [comment]
Attach to Process configuration is no longer in the simplified launch.json but we should add a section to debugging.md explaining how to create such a configuration and use the command variable ${command.PickProcess}

**Comment by gregvanl** [comment]
Covered during the December doc-a-thon. https://code.visualstudio.com/docs/editor/node-debugging#_command-variable-pickprocess-node now covers command.PickProcess.
