### ISSUE TITLE
Documentation states variable substitution is both supported and not supported in environment definition files

### ISSUE THREAD

**Issue by isaacwaldron** [microsoft/vscode-docs#5738]
Variable substitution including environment variables appears to be documented as supported in [environments.md on line 251](https://github.com/microsoft/vscode-docs/blob/68a719a8c561861006ce8cb8ba064ecd3a7dabef/docs/python/environments.md#L251).  However, there is a note on [line 219](https://github.com/microsoft/vscode-docs/blob/68a719a8c561861006ce8cb8ba064ecd3a7dabef/docs/python/environments.md#L219) that indicates this is not supported.  The actual behavior appears to be that it is not supported.

**Comment by luabud** [comment]
Thanks for bringing this up -- you're correct, we currently do not support it. We need to update the variable substitution section accordingly.
