### ISSUE TITLE
CLI setup switches unclear in Docs

### ISSUE THREAD

**Issue by NewtonChutney** [microsoft/vscode-docs#5744]
The switches are said to be from inno setup.. 

`/components=<comma separated list of components>`
But the component names aren't listed in the docs

https://code.visualstudio.com/docs/setup/windows#_what-commandline-arguments-are-supported-by-the-windows-setup

**Comment by NewtonChutney** [comment]
Ah.. After fiddling a bit.. I could get to store my settings to a file with `/SAVEINF=<filename>`

And realized these aren't components but tasks to he sent..

FYI, for other users,
**The checkboxes**
1. Create a desktop icon
2. Open with code in context menu - for files
3. Open with code in context menu - for folders
4. Register code as editor for supported file types
5. Add to path

**Correspond to tasks:**
1. desktopicon
2. addcontextmenufiles
3. addcontextmenufolders
4. associatewithfiles
5. addtopath

It would be good if these flags are kept in the docs.
Thanks! ✌️

**Comment by gregvanl** [comment]
Closing older issue without upvotes. Doesn't feel like we should document Inno setup switches in the VS Code documentation.
Thanks for providing a short summary for others.

**Comment by NewtonChutney** [comment]
> Closing older issue without upvotes. Doesn't feel like we should document Inno setup switches in the VS Code documentation.
> Thanks for providing a short summary for others.

Well these switches are provided by the inno setup app.. 
- /SAVEINF=<filename>
- /components=

But isn't VSCode responsible for documenting its feature toggles? 
- desktopicon
- addcontextmenufiles
- addcontextmenufolders
- associatewithfiles
- addtopath

This would really help enterprise deployment automation.. 
¯\_(ツ)_/¯
