### ISSUE TITLE
Workspace is disabled and CSS is not output 

### ISSUE THREAD

**Issue by kuro-gallery** [microsoft/vscode-docs#5746]
Good evening　I'm sorry if I put you in the wrong place.
I would like to confirm the initial settings of visual studio code.

PC environment Main character computer MAC BOOK AIR M1 2020 Monterey 12.6 memory 16GB (portable) Home PC Windows 10 Pro 22h2 Self-made PC Computer classroom mac OS Big Sur 11.6 24 2021 m1 iMac memory 16GB Confirmation work is performed between the main computer and the MAC in the computer classroom, and at home, it is confirmed with the MAC and Win.

I'm in trouble because CSS is not output because the Visual Studio Code workspace is disabled.

Download the MAC version of Apple Silicon for Visual Studio Code

Unzip and the file will appear

Go to the application's folder

Japaneseize.

Install plugins. (Designated computer classroom)

Dart JS Sass and Scss Instructor Recommendation 　2. However, Scss in the computer classroom uses Live Sass Compiler 　　, so it is necessary to switch the css folder. 　3. After that, use the Live Server originally. 　　Currently, the following error has occurred, so the use is stopped.

error contents

Live reload enabled. on_content_end.js:54 on_content_end ==>response to loadPagePattern, href=omitted=undefined

It seems to be related to Google. response to loadPagePattern After translating, it looks like this A message appears...

warning m=_b,_tp,_r:494 Using this console can allow your personal information to be stolen by an attacker impersonating you using a technique known as Self-XSS. Do not type or paste any code that you do not understand. on_content_end.js:54 on_content_end ==>response to loadPagePattern, href=omitted=undefined

Web production seems to be complete with these three plugins.

In the computer class, I was only taught how to set up the folders I created in a way that I could trust them, and how to put them in and out. Because of this, various problems occur.

Just by running the diagnostic software by Apple, everything will be in the state of the following URL. Please tell me how to fix it. Thank you.

[Workspace Trust](https://code-visualstudio-com.translate.goog/docs/editor/workspace-trust?_x_tr_sl=auto&_x_tr_tl=ja&_x_tr_hl=ja&_x_tr_pto=wapp)

Windows or Mac it happens on both sides
![IMG-0055](https://user-images.githubusercontent.com/116885141/198666027-62cf676e-e925-4766-963c-bbdc9d0aae56.jpg)
mac/volumes untitled trusted

**Comment by gregvanl** [comment]
Hi @kuro-gallery Looking at your comments, I am not sure what is wrong with your setup. 
You mention that this is for a class, is there a teaching assistant, professor, or classmate that you could ask for assistance, perhaps someone who has been able to successfully setup VS Code with the DartJS Compiler extension?

**Comment by gregvanl** [comment]
Closing as no response from user
