### ISSUE TITLE
Azure Extensions documentation should promote Azure Tools pack

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-docs#5752]
About this page:

https://code.visualstudio.com/docs/azure/extensions

Currently, the Azure Extensions documentation prominently links to the Azure App Service and Azure CLI tool. However, as far as I know, the typical recommended extension in Azure Tools since it bundles all the extensions together. That is what I was trying to find when I searched the web and found that page, but it's not linked from there at all. 

I'd suggest linking to this somewhat prominently:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-node-azure-pack

**Comment by isidorn** [comment]
fyi @gkulin 
@pamelafox we accept PRs :)

**Comment by gkulin** [comment]
thank you @pamelafox for bringing this up and @isidorn for looping me in! :)

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/5754
