### ISSUE TITLE
Point to JavaScript IntelliSense section

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#576]
I observed a user looking for help with IntelliSense on the Node.js walkthrough page. It would have helped him to have a tip at the end of the Hello World section to take him to the JavaScript IntelliSense page. 

https://code.visualstudio.com/docs/runtimes/nodejs#_hello-world

**Comment by gregvanl** [comment]
Rather than add a Tip with might disturb the walkthrough flow, I've gone with a documentation best practice to make the first mention of a feature like IntelliSense or settings be a link to the relevant doc.
