### ISSUE TITLE
How do I add a button to 'accounts/context' through ‘vscode Plugin API’?

### ISSUE THREAD

**Issue by MrZmcH** [microsoft/vscode-docs#5766]
![eyFSx](https://user-images.githubusercontent.com/45864434/200242129-28db43b1-dbfb-4fb1-afae-64512e6b4109.png)
I am going to develop a plugin to add one or more buttons in the above position.
Based on the documentation I found, my 'package.json' looks like this：
![swbDG](https://user-images.githubusercontent.com/45864434/200242181-2559c62b-686f-4436-8e2d-c1660860a008.png)
After running F5, it did not achieve the desired effect. Who has such experience?

**Comment by gregvanl** [comment]
Hi @MrZmcH Unfortunately, the Accounts context menu is not extensible.
You could create a suggestion issue in the VS Code product repository at https://github.com/microsoft/vscode/issues, describing your scenario.

**Comment by MrZmcH** [comment]
How do I customize or register? so the Accounts context menu can expand.

**Comment by MrZmcH** [comment]
> Hi @MrZmcH Unfortunately, the Accounts context menu is not extensible. You could create a suggestion issue in the VS Code product repository at https://github.com/microsoft/vscode/issues, describing your scenario.

How do I customize or register? so the Accounts context menu can expand.

**Comment by gregvanl** [comment]
@MrZmcH Not all parts of the VS Code user interface as extensible and it may be that given the security workflows that use the Accounts context menu, the VS Code engineers do not expect third party extensions to add to the menu.
If you think this is a useful extension capability, you can create a new issue in the product repo, explain why it is important, and provide details about what workflow you are trying to enable.
