### ISSUE TITLE
Incorrect "Request forwarding" conclusion about diagnostics

### ISSUE THREAD

**Issue by GerardSmit** [microsoft/vscode-docs#5778]
In the docs, the following is stated about cons of "Request forwarding" (https://code.visualstudio.com/api/language-extensions/embedded-languages#conclusion):

> - Does not yet work with diagnostics errors, which are pushed from Language server. LSP in 3.17 will provide a diagnostic pull model that will make this possible.
>
> _Source: [api/language-extensions/embedded-languages.md:262](https://github.com/microsoft/vscode-docs/blob/52aea9e69687c76b2fa8991ff0f7e42712e768fe/api/language-extensions/embedded-languages.md?plain=1#L270)_

The line "LSP in 3.17 will provide a diagnostic pull model that will make this possible." has been added because of the following issue: https://github.com/microsoft/vscode-extension-samples/issues/430#issuecomment-879711145 in commit https://github.com/microsoft/vscode-docs/commit/e885ed27121cf16249e4bfa34ce2cc4a9b6a4fd8

However, now that [LSP 3.17 is released](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#version_3_17_0) and is implemented in some language servers (HTML/JSON/CSS) you would think it's possible to use "diagnostic pull model" in vscode, which is not the case. [After a lot of digging](https://github.com/microsoft/vscode-extension-samples/issues/430#issuecomment-1181554011) I've asked in the vscode repository if this could be implemented. The response is that it won't be implemented: https://github.com/microsoft/vscode/issues/159911#issuecomment-1236629954

So yes, in LSP 3.17 it's possible to use the new "diagnostic pull model" but you can't use the API's in vscode to actually forward the requests and make use of this new diagnostics API.

Shouldn't the mention about LSP 3.17 be removed? Since it gives false hope 🥲

**Comment by aeschli** [comment]
I commented on https://github.com/microsoft/vscode/issues/159911

So we are only half way there. LSP now has a protocol for diagnostic pull, but our VS Code API not yet.

I update the docs.

**Comment by gregvanl** [comment]
Closing as fixed in vscode-docs vnext branch. This will be published live when the next release goes out beginning of December.
