### ISSUE TITLE
Node.js walkthrough jsconfig.json

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#578]
I observed a user trying to use the jsconfig.json file from this section. He could not copy it because it is an image. We should change the image to code that developers can copy. 

https://code.visualstudio.com/docs/runtimes/nodejs#_adding-a-jsconfigjson-configuration-file

**Comment by gregvanl** [comment]
Reviewing node.js for https://github.com/Microsoft/vscode-docs/issues/436 so I can update the jsconfig.json image to a code block.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/64f34e893b9e494de3499f978540f17e38e35470
