### ISSUE TITLE
##5746continued Trouble with GUID Partition?

### ISSUE THREAD

**Issue by kuro-gallery** [microsoft/vscode-docs#5781]
I'm sorry, I was busy with various circumstances.
At first, I couldn't save it well, so right after I saw it on Genius
All plug-ins, etc. are disabled due to the relationship with the device diagnostic software
In the middle of the day, I didn't go back. (1st time posted here)
After all, initialization → Genius again, machine initialization and hard disk
After initializing the screen, it develops into "Fundamentally equipment problem?"

This time, I will summarize the contents of the question.

  1.Does MAC M1 and intel products from macOS OS X El Capitan or later are compatible with the OS?
     (including Ventura)
  2.Whether alternating file storage between MAC and Windows will interfere with saving.

Below is the situation description.

As a series of work, the contents of VS CODE are transferred to USB HDD from Windows → MAC
If you move (copy the file) with
Symptom that it seems that it is possible to save, but it seems that it is not possible to save
seems to occur with Format exfat.

"Fundamentally equipment problem?" (↓ is what I wrote in Apple's community)

If it is FAT32 or EXFAT formatted in Windows, when you insert a USB memory etc.
File system repair log is automatically applied.

/dev/rdisk〇(number)s2:/dev/rdisk〇(number)s2:** /dev/rdisk〇(number)s2 (NO WRITE)
is recorded, so it is read as EXFAT on NTFS and made read-only
Or the guid partition table that makes EFI exists in the first sector like Windows
There seems to be a difference in equipment.　

※　The DartJS Compiler extension is only used for pure SCSS=CSS output. Some functions of SCSS of
　　Live Sass Compiler will not be supported in the future, so I changed it with an alternative plugin.

**Comment by gregvanl** [comment]
Hi @kuro-gallery I'm having a hard time understanding your issue and I'm not sure if you are having hardward problems with your Mac or some issue related to VS Code.
VS Code has installations for a variety of platforms and machine architectures, which you can find at https://code.visualstudio.com/Download
For Mac, there is both an Intel chip installation and also Apple silicon. The Universal build includes both.
If you wish to run VS Code off a thumb or removable drive, you can learn more at https://code.visualstudio.com/docs/supporting/faq#_can-i-run-a-portable-version-of-vs-code and https://code.visualstudio.com/docs/editor/portable

**Comment by gregvanl** [comment]
Provided user with some pointers on Mac and portable installation.
