### ISSUE TITLE
Document Git Bash setup and usage

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-docs#5794]
Hot topic in surveys and feedback.

**Comment by gregvanl** [comment]
We see many comments in Terminal Basics around setting up Git Bash

**Comment by gregvanl** [comment]
Addressed withhttps://code.visualstudio.com/docs/sourcecontrol/intro-to-git#_git-bash-on-windows
1.77 will also have better Git Bash executable detection, which should help users setting up Git Bash in the terminal
