### ISSUE TITLE
Python Tutorial Bugs

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode-docs#5795]
We received feedback from a QP study that the documentation and Python tutorials (specifically the [Flask tutorial](https://code.visualstudio.com/docs/python/tutorial-flask) and [Creating Python environments page](https://code.visualstudio.com/docs/python/environments)) did not include all the necessary steps for the user to be successful in completing the task. We also received feedback that the format of these documents was not the easiest to follow. We would like to ensure these pages include all necessary steps for users and are easy to follow.

**Comment by satishg123** [comment]
Hi @luabud please guide me, I would like to contribute.

**Comment by gregvanl** [comment]
Closing as not actionable. Feel free to provide more details or submit PRs for suggested updates.
