### ISSUE TITLE
Document that leaving the `-insider` suffix on `engines.vscode` in `package.json` is safe

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#5801]
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility doesn't mention that if you leave `-insider` on the `engines.vscode` in your `package.json` that it's safe to do so.

**Comment by gregvanl** [comment]
Closing as doesn't seem like a best practice that we would want to encourage.

**Comment by brettcannon** [comment]
If this isn't what we want people to do, then what is the messaging to extensions that do want to test against an insiders build of VS Code? You need to push an update the day we release a new VS Code version just to sync up the engine number? To me, the lack of this information would make me never want to release against an insiders version (which is maybe what we want?).
