### ISSUE TITLE
Show how to find the version of VS Code

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#581]
We need to show in the docs how to find the version of VS Code you are using. A simple FAQ should suffice.

**Comment by waderyan** [comment]
@gregvanl do you have any thoughts on the above? This fell through the cracks on my end and needs to be done ASAP for the MP team.

**Comment by gregvanl** [comment]
I can certainly take the PR to add an entry to the FAQ so they can add a Marketplace link to a doc location.
Don't they need to programmatically know the version, sent up in our MP queries?

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/pull/582

**Comment by gregvanl** [comment]
Note that I modified the h2 heading slightly ("I am on" -> "I am using") so the resulting link is:
```
https://vscode-ppe.azurewebsites.net/Docs/supporting/faq#_how-do-i-find-what-version-of-vs-code-i-am-using
```

**Comment by waderyan** [comment]
No they don't. This helps a different use case then the MP queries.
