### ISSUE TITLE
Document the interface for an extension to be used as a `configurationProvider`

### ISSUE THREAD

**Issue by ShamrockLee** [microsoft/vscode-docs#5816]
The current documentation only state that the `configurationProvider` attribute in `c_cpp_properties.json` to be "The ID of a VS Code extension that can provide IntelliSense configuration information for source files", and there's no way for a user to check if an extension supports that, nor can an extension developer get any information about the interface.

https://github.com/microsoft/vscode-docs/blob/eb97c3dc6fa7e6de8bbec096aaecc75b91e3f6a4/docs/cpp/c-cpp-properties-schema-reference.md?plain=1#L94-L95

Is it implemented through certain "commands" the target extension provides? It would be great to see it document.

**Comment by sean-mcmanus** [comment]
The interface extensions need to implement to be a configuration provider is at https://github.com/microsoft/vscode-cpptools-api . Two such providers are https://github.com/microsoft/vscode-cmake-tools and https://github.com/microsoft/vscode-makefile-tools , but there are others too.

**Comment by gregvanl** [comment]
Closing as answered
