### ISSUE TITLE
Is terminal.integrated.automationProfile deprecated?

### ISSUE THREAD

**Issue by elibroftw** [microsoft/vscode-docs#5829]
Reading the docs, terminal.integrated.automationProfile does not appear to be deprecated. It's usage is promoted as being able to set the shell profile for automation-related terminal usage like tasks and debug. But in practice it does not do that. VSCode settings says it is deprecated so what should I use instead? 

For some reason, VSCode wants to use pwsh instead of my default profile when it comes to tasks but for debugging vscode wants to use the default profile instead and there's no way to change it to use powershell without changing the default shell.

So for tasks, I had to re enter my default terminal profile for the workspace, plus I had to use `-c` , and for the debugger, I had to turn on external console.

I somehow managed to get building and debugging working but the docs are not clear that debugging has nothing to do with building. It took me 30 minutes to figure out that the c++ defaults given by the docs do not include comments on how to build the project first.

**Comment by Tyriar** [comment]
Are you confusing `terminal.integrated.automationProfile` with `terminal.integrated.automationShell`? Only the latter is deprecated

**Comment by elibroftw** [comment]
When I set the automation shell:
![image](https://user-images.githubusercontent.com/21298211/208772739-e01805ba-0696-40eb-b8ab-bb0d493f5997.png)

When I set the shell in tasks to
![image](https://user-images.githubusercontent.com/21298211/208772867-60ca16ba-201f-4993-9c3d-a14b57ba21d7.png)

no errors.

**Comment by Tyriar** [comment]
Don't use automation shell, do you have a problem with automation profile?

**Comment by elibroftw** [comment]
I misspoke, I meant to say, when I set the automationProfile, that's what I get.
```json
"terminal.integrated.automationProfile.windows": {
        "path": "C:\\msys64\\usr\\bin\\bash.exe",
    }
```

**Comment by Tyriar** [comment]
Is the problem that you can't use the l/i/x args in automationProfile then?

**Comment by gregvanl** [comment]
Closing as no reply, please reopen if you still have an issue
