### ISSUE TITLE
Unable to bookmark blogs and updates listing

### ISSUE THREAD

**Issue by markcellus** [microsoft/vscode-docs#5847]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Navigate to blogs listing page (https://code.visualstudio.com/blogs)
2. Bookmark page
3. Verify bookmarked page is not https://code.visualstudio.com/blogs but to the latest article (https://code.visualstudio.com/blogs/2022/12/07/remote-even-better at the time of this writing)

This also happens when navigating to https://code.visualstudio.com/updates.

**Comment by gregvanl** [comment]
Closing as no current plans to update the current blog post and release notes rendering. We'll keep this suggestion in mind during future website updates.

**Comment by markcellus** [comment]
I'll just make this available on my server and perhaps a blog post letting everyone know why bookmarking or sharing a list of the entries (such a basic request) can't be implemented. Thanks for considering.
