### ISSUE TITLE
why there is only open settings(ui) in command?

### ISSUE THREAD

**Issue by smallnine9** [microsoft/vscode-docs#5864]
i can't find open setings(json) in command :(, why this happen?

**Comment by gregvanl** [comment]
Hi @smallnine9 I can see the command in the Command Palette (View > Command Palette or F1) in VS Code version 1.74:

![image](https://user-images.githubusercontent.com/12818376/207386805-975e698b-d1db-4f4f-b65d-a07ae09ee3a8.png)

Does this repro if you restart VS Code without extensions `code --disable-extensions`?

**Comment by rzhao271** [comment]
Hi @smallnine9, "Open Settings (JSON)" has been renamed to "Open User Settings (JSON)" to distinguish it from "Open Workspace Settings (JSON)".

**Comment by smallnine9** [comment]
hi，@rzhao271  got it， thanks！
