### ISSUE TITLE
Add full content in RSS feed

### ISSUE THREAD

**Issue by markcellus** [microsoft/vscode-docs#5867]
Thanks for making https://code.visualstudio.com/feed.xml available, but it doesn't allow viewing the full content of an entry in each feed item. It just offers a "Read the full article" link that takes you to the web page, but I'd like to see all content without having to navigate to the page.

**Comment by gregvanl** [comment]
Closing as not planning to duplicate the blog post content in the RSS feed.

**Comment by markcellus** [comment]
For anyone looking for a full set of content for the feeds, looks like https://openrss.org/code.visualstudio.com is available as an alternative.
