### ISSUE TITLE
VSCode extension cache

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-docs#5874]
Please document the **VSCode** extension **cache** system and update the  [Avoiding VS Code extension reinstalls](https://code.visualstudio.com/docs/remote/troubleshooting#devcontainers-articles).  _Isn't the problematic thing re-download the extension rather than re-install it?_

If I'm not wrong (@chrmarti might confirm this), currently, the process done for installing an extension in **[Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)** is like this:

- Check if the extension is found under **/vscode/vscode-server/extensionsCache**
- If the extension is there, then create a symlink under **~/.vscode-server/extensionsCache** pointing there
- If not, then download the extension to **~/.vscode-server/extensionsCache** and, later, copy it to **/vscode/vscode-server/extensionsCache**
- Install extension from **~/.vscode-server/extensionsCache** to **~/.vscode-server/extensions**

To me, the best way to avoid downloading extensions every time is by using a shared volume among all my **Dev Containers** and mounting it under **/vscode/vscode-server/extensionsCache**.  This way, the extensions are always available for any container and install them locally but not downloading over and over again.

**NOTE**: I used to do this with a shared volume mounted under **~/.vscode-server/extensionsCache** but in recent versions looks like there are links to **/vscode/vscode-server/extensionsCache** and I suppose that the way of downloading new extensions under **~/.vscode-server/extensionsCache** first and then copying to **/vscode/vscode-server/extensionsCache** is to allow the sharing I'm proposing and to avoid "concurrent" modification of new extension downloads (is faster and less collision problematic to copy a fully downloaded file than writing it as it is been downloaded).  Otherwise I suppose that the more logical way of doing it should be to directrly download it to **/vscode/vscode-server/extensionsCache** and then simply link it under **~/.vscode-server/extensionsCache** like is done for previously downloaded extensions.

**Comment by chrmarti** [comment]
The way this currently works is an implementation detail and we might want to change it in the future to improve it. Documenting it would only lead more users to rely on specifics of the current implementation.

**Comment by chrmarti** [comment]
@rubensa `/vscode` is mounted on the `vscode` volume, so `/vscode/vscode-server/extensionsCache` is shared between containers. Could you open an issue at https://github.com/microsoft/vscode-remote-release/issues if that does not work?

**Comment by rubensa** [comment]
Wow!!  Thanks @chrmarti.  I didn't know about `/vscode` volume so my shared volume for the extensions cache is not needed anymore.
