### ISSUE TITLE
How to get automatic code completion to work for custom new programming language?

### ISSUE THREAD

**Issue by lancejpollard** [microsoft/vscode-docs#5876]
I am not able to get code completion to work without pressing `CTRL+SPACE` on the Mac, as described (with helpful screenshots/videos) here:

https://stackoverflow.com/questions/74837030/why-isnt-code-completion-working-for-my-custom-programming-language-in-vscode

Any ideas why it's not working and how to fix it? I would like it to work like the JavaScript/TypeScript example in the linked screenshot, where as you type it gives you a list of code completions.

**Comment by gregvanl** [comment]
Closing old support request issue
