### ISSUE TITLE
Incorrect steps mentioned on VS Code website to deploy Azure App Service

### ISSUE THREAD

**Issue by tarekahf** [microsoft/vscode-docs#5911]
The steps mentioned on this link:

https://code.visualstudio.com/docs/java/java-on-azure

for the following:
<html>
<body>

Tutorial | Description | Related Tools
-- | -- | --
Deploy Java web appsto Azure App Service | Deploy a web app to the cloud | Apache MavenAzure App Service
Deploy Spring Boot appsto Azure Spring Apps | Deploy a Spring Boot applicationto Azure Spring Apps | Apache MavenAzure Spring Apps

</body>
</html>

The above articles provide steps to deploy App Service from VS Code. The steps are wrong and they are not working for:
https://code.visualstudio.com/docs/java/java-webapp
https://code.visualstudio.com/docs/java/java-spring-apps

It should be as follows:

1. Clone the Sample Project
2. Optional: Create the App Service with Linux, Java 17, and Java SE from Azure Portal. Could not create the App Service from VS Code.
3. Follow the steps from here to config the project for Azure deployment:
https://learn.microsoft.com/en-us/azure/app-service/quickstart-java?pivots=platform-linux-development-environment-maven&tabs=tomcat
```
PS> mvn com.microsoft.azure:azure-webapp-maven-plugin:2.5.0:config
PS> mvn package azure-webapp:deploy
```
The above PS commands will also create the App Service and deploy it.

Please fix the relevant web pages.

**Comment by nickzhums** [comment]
@tarekahf thanks for creating this issue. The current web pages are creating App Service and Azure Spring Apps using the VS code extension, could you please clarify what went wrong for you? also @silenceJialuo as fyi

**Comment by tarekahf** [comment]
I was following the steps here:
https://code.visualstudio.com/docs/java/java-webapp#_deploy-web-apps-to-the-cloud

and got this error when browsing the App Service:

```
HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/8.5.78
```

Also, the default packaging of the sample project was JAR and it was not deploying JAR and was requesting WAR. I changed the packaging to WAR and deployed successfully but I got the above response error in the browser when navigating to the App Service URL.

What is wrong is the missing steps which I included in the initial post above.

Also, I tried creating App Service from VSCode for Java 17, Java SE, and Linux, but I got an error indicating something wrong with Java 17. However, I was able to create this App Service from the Azure Portal directly. See https://github.com/microsoft/vscode-azureappservice/issues/2348 for details.

See https://stackoverflow.com/q/75010485/4180447 for more details.

Tarek

**Comment by silenceJialuo** [comment]
Also, include @Flanker32 for awareness with the issue.

**Comment by Flanker32** [comment]
@tarekahf Thanks a lot for your report, the issue for Java 17 creation in VSCode has been fixed in PR https://github.com/microsoft/vscode-azureappservice/pull/2350

**Comment by gregvanl** [comment]
Looks like the extension has been released with the necessary fix for Java 17 https://github.com/microsoft/vscode-azureappservice/blob/main/CHANGELOG.md#0246---2023-02-08
Closing the issue
