### ISSUE TITLE
vscode has could not run command line since I updated Win10

### ISSUE THREAD

**Issue by Yu-Che-Gao** [Microsoft/vscode-docs#592]
![default](https://cloud.githubusercontent.com/assets/18100669/18663737/5401cce2-7f52-11e6-9c2f-cbb03a1fd8dc.png)

My version of Windows10 is 10.0.14393

**Comment by gregvanl** [comment]
Hello, this looks like an issue with the preLaunchTask you are trying to run.  Are you trying to run a Java tool and that tool needs to be reinstalled after your Windows 10 update?
This is also not a document issue but perhaps a product issue.  Feel free to open an issue in the vscode repository https://github.com/Microsoft/vscode/issues.  If you do open a new issue, including your tasks.json and launch.json may be helpful.
Thanks
