### ISSUE TITLE
To mark deprecated methods `storagePath` and `globalStoragePath` in guide

### ISSUE THREAD

**Issue by reregaga** [microsoft/vscode-docs#5929]
In the article [Common Capabilities > Data Storage](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage) it would be a good idea to note that the methods `storagePath` and `globalStoragePath` are deprecated and write about the new methods `storageUri` and `globalStorageUri` instead.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/5977
