### ISSUE TITLE
Editing Python Code page could do with some re-organizing.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-docs#5952]
Ref: https://github.com/microsoft/vscode-docs/blob/main/docs/python/editing.md

1. It goes into a lot of topics that a person learning python or new to VS Code would not try. For example, Enable auto imports, or Enable additional locations could be moved lower to advanced or settings part of the docs.
2. Run selection or run line should be replaced with Run in terminal button. The intent is to get users to run code. Running by line can setup a new python user to make to make mistakes. We do want people to know about the feature but it should be documented as additional ways of running code.
3. Refactoring should probably move to its own page.
4. Formatting should move to its own page, but this page should talk about the existence of the feature. Trouble shooting should move to the formatting page.
5. Linting should be a subsection here and the main linting content is already in its own page. The subsection for linting in the editing page should introduce linting, but the bulk of the content should be in the lintings own page.

**Comment by gregvanl** [comment]
Closing old issue.
