### ISSUE TITLE
Move all the python commands their shortcuts to a reference page.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-docs#5956]

**Comment by karthiknadig** [comment]
https://code.visualstudio.com/docs/python/testing#_test-commands
https://code.visualstudio.com/docs/python/jupyter-support-py#_additional-commands-and-keyboard-shortcuts

**Comment by Jakkpob** [comment]
(Issue #5956)

**Comment by gregvanl** [comment]
Closing old issue. I think it makes sense to leave the commands in their context (testing, interactive window) rather than splitting out to a new reference topic
