### ISSUE TITLE
Tutorial on working with VS Code (Windows) & Typescript (WSL)

### ISSUE THREAD

**Issue by sunnyrjuneja** [Microsoft/vscode-docs#597]
Hi,

I'm leaving this issue based on this tweet exchange with the windowsdev twitter account: https://twitter.com/sunnyrjuneja/status/777024115848859648

I'm a recent convert from Linux to Windows 10 and WSL (Windows Subsystem for Linux). For the most part, I've been really happy with the experience. I'm very interested editing files in Windows and running tool chains in WSL. 

I've had a challenging time trying to integrate Typescript 2.0 (installed in WSL) with Visual Studio Code (installed in Windows). I was thinking and hoping that it would be great to see a tutorial or documentation addressing this very use case.

**Comment by gskls** [comment]
It's been a huge problem for me . I totally moved pretty much everything in the wsl and now the typescript problem . Is there any solution ? I mean this is the main thing  . WSL is just the terminal of linux . Now if we can't even use that , what is wsl is for? It is totally stupid to bring this feature out of Beta while nothing stills work . We're doing work here not testing your features .  That's your work . I hope you guys gott it .

**Comment by gregvanl** [comment]
I don't think this is currently supported and may require changes from TypeScript. See https://github.com/Microsoft/vscode/issues/20220 which you can upvote.
