### ISSUE TITLE
Document ordering of welcome views

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode-docs#5972]
The internal VSCode API to add widget to a welcome view supports providing a desired `order`:
https://github.com/microsoft/vscode/blob/3db45fbd420ec9860b4a94211e499bb6527c7e52/src/vs/workbench/common/views.ts#L85-L88

This is not exposed for extensions it seems:
https://github.com/microsoft/vscode/blob/b9bb22d1ba99fc29e4a30d95ff5baffa98bd1969/src/vs/workbench/contrib/welcomeViews/common/viewsWelcomeExtensionPoint.ts#L17-L23

At Google, having this would allow us to convert some patches to properly using the extension API. Would you be open to adding that? I would be happy to send a PR if you agree this should be exposed.

**Comment by gregvanl** [comment]
Group sorting is shared across UI elements so mentioned in https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups
