### ISSUE TITLE
Steps in Using Clang in Visual Studio Code don't happen

### ISSUE THREAD

**Issue by lewisl** [microsoft/vscode-docs#5974]
.vscode directory is never created.  Do I have to do this manually?  It appears so, though is not documented. 

tasks.json is not created in the .vscode directory as said directory doesn't exist.

Do you use VS code yourself?  Do you test what you write in the documentation?

Apparently, not.

**Comment by gregvanl** [comment]
Closing old issue. There are not known issues with creating .vscode when a tasks.json file is created.
