### ISSUE TITLE
should say or Code - Insiders

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-docs#5979]
Testing microsoft/vscode#172015

![Screenshot 2023-01-24 at 10 33 24 AM](https://user-images.githubusercontent.com/29464607/214352030-baad70cc-1357-4452-a8ca-a251c1e7a2f9.png)

**Comment by joaomoreno** [comment]
@meganrogge Next time, please feel free to jump in and make changes in the docs directly, for small stuff like this.

**Comment by meganrogge** [comment]
Didn't want to overstep @joaomoreno as sometimes I have reasons for doing things a certain way in documentation 😄

**Comment by joaomoreno** [comment]
No worries!
