### ISSUE TITLE
Jupyter Notebook documentation contains outdated screens and content

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-docs#5997]
**Problems**
* The screens are not the native VS Code Notebook UI (its the old WebView)
* Getting started section (which is at the bottom is incorrect and does not flow with the links added) 
    * Incorrect because we're recommending users to select an interpreter, however this is not necessary for notebooks
* Screenshots and recordings seem to have very small fonts
* PyViz library is mentioned however that does not produce an output in the new Notebook UI

**Comment by minsa110** [comment]
Note, this is in regard to; https://code.visualstudio.com/learn/educators/notebooks
