### ISSUE TITLE
Minimize code

### ISSUE THREAD

**Issue by theWhiteFox** [Microsoft/vscode-docs#6]
This would be a nice feature.

**Comment by gregvanl** [comment]
Hi theWhiteFox,

I think by minimizing code you mean the code folding feature that is on the VS Code backlog.  
You can add your support for the feature by voting on the VS Code User Voice site: http://visualstudio.uservoice.com/forums/293070-visual-studio-code/filters/top
Code folding is ranked #2 so you're not alone.
- Greg

**Comment by theWhiteFox** [comment]
Yep code folding feature is what I want.

Thanks Greg.
Ste
