### ISSUE TITLE
Do not use /etc/apt/trusted.gpg.d/

### ISSUE THREAD

**Issue by znz** [microsoft/vscode-docs#6004]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: before install
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Do following commands in <https://code.visualstudio.com/docs/setup/linux>

```
sudo apt-get install wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
rm -f packages.microsoft.gpg
```

2. Remove `signed-by=` from `/etc/apt/sources.list.d/vscode.list`
3. Run `apt update` and success. But I expected it failed.

In <https://docs.docker.com/engine/install/ubuntu/>, keys are not in `/etc/apt/trusted.gpg.d/` but in `/etc/apt/keyrings`.
So I want to change installing keys into `/etc/apt/keyrings`.

Another related issue, if keys install as `*.asc`, it does not need to install gpg.

Expected install steps:

```
sudo apt-get install wget
sudo mkdir -p /etc/apt/keyrings
sudo wget -q https://packages.microsoft.com/keys/microsoft.asc -O /etc/apt/keyrings/packages.microsoft.asc
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
```

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/3d2d13a34859c95023b1726647a32ecdfdb1f36c
