### ISSUE TITLE
Document Marketplace API

### ISSUE THREAD

**Issue by dragonDScript** [microsoft/vscode-docs#6006]
VSCode is an open source product. It should have available documentation for the Marketplace & a way to run your own, even if you don't allow third parties to browse the Microsoft-owned Marketplace.

**Comment by rzhao271** [comment]
Moved the issue to the docs repo.
Also see https://github.com/microsoft/vsmarketplace/issues/238#issuecomment-1378486673

**Comment by dragonDScript** [comment]
Thanks

**Comment by gregvanl** [comment]
Closing as the Marketplace issue mentioned above indicates that the API is not meant to be public.

**Comment by dragonDScript** [comment]
> Closing as the Marketplace issue mentioned above indicates that the API is not meant to be public.

That's VS Marketplace, not VSCode marketplace. It's very different. Please re-open. If vscode is open source,all of its essential component should be. Either, it can be considered a monopolistical practice

**Comment by aitor-gomila** [comment]
Please reopen @gregvanl, that issue was directed at the VS Marketplace, not VSCode Marketplace.

**Comment by shoter** [comment]
Issues not related to this issue were linked - I think reason for closure of this issue does not apply.
@gregvanl

**Comment by gregvanl** [comment]
Hi @aitor-gomila I'm not sure I understand your distinction between VS Marketplace and VS Code Marketplace. I believe they are the same and the https://github.com/microsoft/vsmarketplace repo supports it. 
Can you provide the URL to the marketplace you are asking about for clarify?

**Comment by aitor-gomila** [comment]
Their description says Visual Studio:
![Screenshot_2023-03-08-08-18-27-280_com android chrome](https://user-images.githubusercontent.com/46191980/223647136-850532a8-bd25-4a71-9bdd-e986c9ae2d05.jpg)

**Comment by gregvanl** [comment]
The Visual Studio Marketplace is shared across the Visual Studio family of products (VS IDE, VS Code, Azure DevOps).
The tabs at the top of the site pivot between them.
For example, https://marketplace.visualstudio.com/vs for VS IDE and https://marketplace.visualstudio.com/vscode for VS Code.

**Comment by aitor-gomila** [comment]
Not going to force or convince you into doing this, but very disappointing reasoning👎

**Comment by aitor-gomila** [comment]
Not what I'm speaking about, one thing is the implementation Microsoft made for their marketplace, the other is to document what VSCode, an open source product, uses. In this case it would be to document each endpoint of the REST API, at the very least.

**Comment by Grim-GH** [comment]
I'd also like to see this Documentation done as we have an enterprise need to verify which extensions are installed on our network as we ran into an issue with CVEs for unapproved extensions.

If anyone knows how to do that via PowerShell I'm trying to fumble my way through it now and it's slow going. 
Any assistance would be appreciated. 

Resources used...
@jossef 's script above as a starting point
https://gist.github.com/scottmwyant/70f5fd296a935a15c8fbb9b9d646e6ca/revisions
https://www.reddit.com/r/vscode/comments/am1k1t/is_there_an_api_for_getting_list_of_all/
...not to mention a couple days of Googling.  X . X
