### ISSUE TITLE
Remove bithound.io from https://code.visualstudio.com/api/references/extension-manifest

### ISSUE THREAD

**Issue by Randomazianduude** [microsoft/vscode-docs#6011]
Following issue #6010 , the domain bithound[.]io is listed as a trusted service on https://code.visualstudio.com/api/references/extension-manifest.

But according to [this](https://mobile.twitter.com/bitHoundio/status/1001947571265458176) tweet, the service was discontinued in May 2018 and it seems the domain was re-registered in 2020-01-15 according to the domain's WHOIS information.

The domain now points to a site endorsing Bitcoin gambling sites.

Maybe someone could remove the domain from the extension manifest page?

Thanks.

**Comment by gregvanl** [comment]
@Randomazianduude Really appreciate you noticing and calling these out! Looks like you might have tested each one :-)
