### ISSUE TITLE
Profiles documentation

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#6020]
Profiles was released to stable in the 1.75 release.
Should either have a new topic (under User Guide) or add a section to the Settings topic explaining Profiles

**Comment by thevedicdev** [comment]
I am not sure if this is the right place to ask, but I would like to contribute by documenting this feature. I am new to open source.

**Comment by gregvanl** [comment]
Hi @thevedicdev Thank you for your interest in the VS Code documentation. We will scaffold out the initial documentation and would welcome your feedback on any upcoming PRs. Once the first version of the topic is live, feel free to submit your own PRs with updates or suggestions.
