### ISSUE TITLE
`enableTurboSourcemaps` option is missing from nodejs debugging docs

### ISSUE THREAD

**Issue by artu-ole** [microsoft/vscode-docs#6027]
New option [enableTurboSourcemaps](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md#enableturbosourcemaps) introduced in 1.75.0 is missing from the list of available options https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes

Even though it is a temporary one it is inconsistent that it would be missing from the docs other than release notes as the deprecation period for the old source maps discovery mechanism is not specified.

**Comment by gregvanl** [comment]
Hi @artu-ole Thanks for pointing this out and creating an issue. 
Closing the issue as we don't usually document short lived backdoor escape or experimental settings.
By default, enableTurboSourceMaps is true so this setting is really just for insurance if the feature is seen to behave poorly and needs to be disabled in a recovery build or by selected users.
