### ISSUE TITLE
Downloads page lists Mac ARM as "silicon"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-docs#6038]
Hello! :)

![image](https://user-images.githubusercontent.com/8586769/217908912-2754534f-b8ce-434d-806d-3f66e640e3b3.png)

GaN isn't that far along yet, "Apple Silicon" maybe better?

**Comment by gregvanl** [comment]
Hi @JacksonKearl! Nice to hear from you!
We went with the Apple preferred casing ("silicon") per https://support.apple.com/en-us/HT211814

**Comment by JacksonKearl** [comment]
Likewise! 

But still, shouldn't it say "Apple silicon"? Just "silicon" seems vague given basically every chip in the world is silicon.

**Comment by gregvanl** [comment]
Space is tight :-)
It is in the Mac section so figured Apple folks would know and hover shows that it is a separate option

**Comment by gregvanl** [comment]
Closing as "silicon" is the Apple branding
