### ISSUE TITLE
docs: missing documentation on `activationEvents`

### ISSUE THREAD

**Issue by vince-fugnitto** [microsoft/vscode-docs#6039]
**Description**

The [activation events](https://code.visualstudio.com/api/references/activation-events) documentation is missing a number of available `activationEvents` which should be listed for clarity as the docs state "Here is a list of all available Activation Events".

A couple of missing events are as follows:
- `onTaskType`
- `onNotebook`
- `onWalkthrough`
- `onOpenExternalUri`
- `onEditSession`
- ...

The information is at least available in the schema.

**Comment by gregvanl** [comment]
Hi @vince-fugnitto Thanks for pointing this out and entering an issue.
Closing this issue as a duplicate of https://github.com/microsoft/vscode-docs/issues/5745, which calls out the same activation events mentioned here.
