### ISSUE TITLE
Compat table for VS Code's node version per VS Code API major version

### ISSUE THREAD

**Issue by M00TSDNS** [microsoft/vscode-docs#6045]
The problem:

- There are some things the VS Code API intentionally does not do
- This requires extension or library author to shell out to Node built-in
- Developer has little if any info about the version of a commonjs external
  (e.g. `"is webcrypto available?"`)

Extension authors would very much benefit from a table of VS Code versions to the node version used in that electron shell

**Comment by gregvanl** [comment]
Hi @M00TSDNS You can check the Node.js version of a VS Code build via the Help > About dialog.

![image](https://user-images.githubusercontent.com/12818376/218647712-c6b6b6b5-e6a3-4f09-a9f1-3b31174d6d7f.png)

**Comment by M00TSDNS** [comment]
Correct. However, I cannot check the Node.js version for the Electron shell without downloading a different copy of VS Code (possibly portable version).

**Comment by M00TSDNS** [comment]
Extension author solution via Slack: https://github.com/ewanharris/vscode-versions
