### ISSUE TITLE
if you are using window

### ISSUE THREAD

**Issue by hrshtmlng** [microsoft/vscode-docs#6048]
Bro but its not working on my desktop

**Comment by gregvanl** [comment]
Hi @hrshtmlng Sorry to hear that you are having problems. Can you provide more details about what is not working in VS Code or not clear in the VS Code documentation?

**Comment by hrshtmlng** [comment]
![Screenshot (165)](https://user-images.githubusercontent.com/101478591/219005718-c79a2228-fd1e-443f-8271-e18056cb36b2.png)
That's the issue

**Comment by gregvanl** [comment]
Hi @hrshtmlng, from reviewing the Flask tutorial at https://code.visualstudio.com/docs/python/tutorial-flask, I wonder if you need to use the command line `python -m flask run` rather than trying to run flask directly on the command line?

**Comment by gregvanl** [comment]
Closing as interpreting the heart to mean that the user is unblocked
