### ISSUE TITLE
Intellisense not found

### ISSUE THREAD

**Issue by firiox** [microsoft/vscode-docs#6053]
When hovering over vector or string intellisense doesn't pop-up also when typing msg. I don't get the intellisense window

**Comment by gregvanl** [comment]
Hi @firiox Sorry to hear that you are having problems. Can you provide more information about the programming language and extension(s) you are using and whether you are having trouble following a specific topic or tutorial?

**Comment by gregvanl** [comment]
Closing as no reply back from user

**Comment by firiox** [comment]
I was following the tutorial about c++ and visual studio code and using the c++ extesion of visual studio code that tell us in the tutorial [https://code.visualstudio.com/docs/cpp/config-mingw](url)
