### ISSUE TITLE
ToDo: Topic on patched bits

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#607]
for https://github.com/Microsoft/vscode/issues/12021

i set up an FWlink here that currently points to https://code.visualstudio.com/docs

http://go.microsoft.com/fwlink/?LinkId=828886

needs to be updated once there is a doc to point to.

**Comment by gregvanl** [comment]
I think the places to call this out are a section in setup/overview (full details) "Corrupt installation warning" and also a note in FAQ linking to setup/overview. The fwlink would go to setup/overview#corrupt-installation-warning.
FAQ something like "Q: Why is VS Code saying my installation is corrupt?"

**Comment by gregvanl** [comment]
FWLink needs to be updated once 1.6 docs published. Pointing FWLink 828886 to FAQ root for new
