### ISSUE TITLE
Docs for enum constants are not displayed at https://code.visualstudio.com/api/references/vscode-api

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-docs#6082]
At https://code.visualstudio.com/api/references/vscode-api, documents for enum constants are not displayed if they are not static.

For example, at [InlineCompletionTriggerKind](https://code.visualstudio.com/api/references/vscode-api#InlineCompletionTriggerKind), we cannot find `Automatic` and `Explicit` on the web. If the constants of enums are static, docs are displayed. For example, see [CodeActionKind](https://code.visualstudio.com/api/references/vscode-api#CodeActionKind).

![enumdoc](https://user-images.githubusercontent.com/10665499/221338540-3d80de73-bf1c-4837-ba43-01b29c288b9d.png)

```typescript
/**
 * How an {@link InlineCompletionsProvider inline completion provider} was triggered.
 */
export enum InlineCompletionTriggerKind {
	/**
	 * Completion was triggered automatically while editing.
	 * It is sufficient to return a single completion item in this case.
	 */
	Automatic = 0,


	/**
	 * Completion was triggered explicitly by a user gesture.
	 * Return multiple completion items to enable cycling through them.
	 */
	Explicit = 1,
}
```
https://github.com/microsoft/vscode/blob/42bfe4f68df63042e45454c0655212e547b9be40/src/vs/editor/common/languages.ts#L598-L613

**Comment by gregvanl** [comment]
Hi @tamuratak Thank you for taking the time to submit an issue and your interest in the VS Code API documentation.
This is a known issue with our API generation and is already being tracked in our private website infrastructure repo. 
I'm closing this issue as a duplicate and added a link in the other issue so that we can leave a comment when it is fixed.

**Comment by gregvanl** [comment]
This has been fixed and will be published shortly.

![image](https://github.com/microsoft/vscode-docs/assets/12818376/20241e63-5ba4-42a9-8083-1905761184e8)
