### ISSUE TITLE
Add documentation around storage options (API)

### ISSUE THREAD

**Issue by charisk** [microsoft/vscode-docs#6085]
As far as I understand there are a few different storage mechanisms that one can use when developing a VS Code extension. E.g.
- Global storage
- Global state
- Workspace storage
- Workspace state

There isn't, currently, a single place that discuss these options, their differences, and how they should be used.

**Comment by gregvanl** [comment]
Covered in https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage
