### ISSUE TITLE
Uses for profiles: reporting an issue?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-docs#6089]
I found using an empty profile to verify that an issue can be reproduced in the VS Code default setup, that is, without extensions and setting changes, is a useful scenario for profiles. It might make sense to mention 'Reporting VS Code Issues' in the [uses of profiles section](https://github.com/microsoft/vscode-docs/blob/profilesTopic/docs/editor/profiles.md#uses-for-profiles
). 

// CC @isidorn

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/commit/d52aab3481a573b523e744b565845fe92f5ffe83
