### ISSUE TITLE
Installing extensions

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-docs#611]
The doc at https://code.visualstudio.com/docs/extensions/install-extension is saying:

>You can also install a .vsix by opening the file from within VS Code. Run File > Open File... or > unassigned and select the extension .vsix.

This is no longer possible. You need to use the command line or use:

![vsix installation](https://cloud.githubusercontent.com/assets/4674940/18927674/b8efb0c2-8571-11e6-9ac9-5b3a02b989aa.png)

**Comment by gregvanl** [comment]
docs/editor/extension-gallery.md also needs to be updated.
