### ISSUE TITLE
Feedback for Editing Typescript page

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#613]
Moved from https://github.com/Microsoft/vscode-website/issues/503

https://code.visualstudio.com/docs/languages/typescript
- intelliSense for launch/tasks.json is not main selling point. intelliSense for TypeScript is. Not even a single picture shows this feature.
- No instruction on getting typings. For either TS1 or TS2.
- Need its own debugging section. People don't want to go to yet another page and start over a new project to learn debugging:
  ![image](https://cloud.githubusercontent.com/assets/4033249/18936679/2972a378-859e-11e6-8bf3-cd35f9148eb8.png)
- No completed repository on GitHub. People wouldn't know how to get it right if they did something wrong. Also this means people can't copy-paste from an official working project.
- Finally, this is not designed as a flow/tutorial/walk-through. It just touches various points. Would be much better if if starts from an empty repo, and guide the user through step by step while introducing features, and finally have a GitHub repo where each commit corresponds to a single step.
- Should include some info for structuring the project.
- Finally, too long. Better split content into sequential sections and include a table of content at top/sidebar.

Here is a good example: http://electron.atom.io/docs/tutorial/quick-start/
I've tried my friends before and most of them can get it to work under 3 min.

@waderyan

**Comment by gregvanl** [comment]
We've refactored the TypeScript topic into:
languages/typescript - value proposition overview for using TypeScript in VS Code (Matt has some TODO left)

typescript/typescript-tutorial - hello world example
typescript/typescript-compiling - shows tasks and compiler information
typescript/typescript-debugging - shows Node.js and client-side debugging
