### ISSUE TITLE
Documentation for extensions.json format missing

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-docs#614]
Run the command `Extensions: Configure Workspace Recommended Extensions`
It opens a file with below content
```
{
	// See http://go.microsoft.com/fwlink/?LinkId=827846
	// for the documentation about the extensions.json format
	"recommendations": [
		// Extension identifier format: ${publisher}.${name}. Example: vscode.csharp
		
	]
}
```

http://go.microsoft.com/fwlink/?LinkId=827846 takes you to the extensions page that doesnt have any docs for the extensions.json format

**Comment by gregvanl** [comment]
Need to update fwlink 827846 once the 1.6 release is published.
