### ISSUE TITLE
Windows 10: document how to solve issue with VSCode not getting to the foreground

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#616]
We have a famous issue (https://github.com/Microsoft/vscode/issues/929) caused by Electron where opening VS Code does not bring it to the foreground but rather stays in the background with the taskbar blinking.

Now I heard of a workaround that fixes this issue provided the user has access to the windows registry:

* regedit.exe
* find `ForegroundLockTimeout`
* change its value to a low millisecond value (e.g. `10` (decimal))
* restart windows

The related documentation: https://technet.microsoft.com/en-us/library/cc957208.aspx

It is ugly but a viable option for those that really want this.

**Comment by gregvanl** [comment]
Closing as I think this was fixed with a product PR (see https://github.com/Microsoft/vscode/issues/929) and this FAQ is no longer needed.
