### ISSUE TITLE
Migration guide for upgrading an extension for TS 2.0

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#617]
Extension can now leverage TS 2.0 and the new way to acquire typeings. We should help users to migrate the 1.8 extension to 2.0.

We should have this for the September update.

// @dbaeumer

**Comment by gregvanl** [comment]
This was added to the 1.6 release notes.
Still need to update main docs.

**Comment by gregvanl** [comment]
With ATA, this is still in flux. Moving to November

**Comment by gregvanl** [comment]
I'm not sure if there is anything else to do here. TypeScript 2.0 has been out for some time.
