### ISSUE TITLE
Code Snippet throws error after use "yo code"

### ISSUE THREAD

**Issue by DracotMolver** [Microsoft/vscode-docs#62]
I was trying to work with Snippet but I've got this message
![error](https://cloud.githubusercontent.com/assets/13334764/11489482/4dc8f2c4-97ae-11e5-9e42-f9a1942fdf2f.jpeg)

**Comment by scottaddie** [comment]
Out of curiosity, do all checks pass when you run `yo doctor` in your command shell?

**Comment by DracotMolver** [comment]
oooh How could I forget that!!. thanks man.
