### ISSUE TITLE
kbstyle() vs <kbd></kbd>

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-docs#620]
I wonder why you are using a `kbstyle` "macro" when there is the HTML `<kbd>` element that is the semantic fit for keyboard keys, supported by markdown and actually rendered very nice on GitHub:

<kbd>Ctrl</kbd>+<kbd>C</kbd>

**Comment by gregvanl** [comment]
We use kbstyles so that we get the same styling whether the keybindings are coming from a command id mapping or straight keyboard combination.
For example:
```
* `kbstyle(Ctrl+Shift+P)`
* <kb>Ctrl+Shift+C</kb>
* <kb>Ctrl</kb>+<kb>Shift</kb>+<kb>C</kb>
* `kb(workbench.action.showCommands)`
```

![image](https://cloud.githubusercontent.com/assets/12818376/22808467/e6c7c9d4-eee0-11e6-88ab-ae00232abf24.png)

**Comment by gregvanl** [comment]
We want the keyboard shortcuts to look the same (first and fourth).
