### ISSUE TITLE
Emmet configuration wrong indentation for emmet.preferences

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#6234]
On the page

https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration

part of the text for `emmet.preferences` is wrong indented.

The text from: **The format for the filter.commentAfter preference is different and simpler in Emmet 2.0.**

To: **If you want support for any of the other preferences as documented in [Emmet Preferences](https://docs.emmet.io/customization/preferences/), please log a [feature request](https://github.com/microsoft/vscode/issues/new).**

should be indented 1 stop to the left, It is part of the `emmet.preferences` item not extra text for `css.fuzzySearchMinScore` item

**Comment by gregvanl** [comment]
Hi @rioj7 Thanks for pointing this out. The space indentation (4 spaces) is correct in the Markdown file https://github.com/microsoft/vscode-docs/blob/main/docs/editor/emmet.md but not when rendered on either the VS Code Markdown preview, on code.visualstudio.com, or github.com preview. 
I'll see if there is a workaround to get the renderers to do the right thing but it might be Markdown quirk

**Comment by rioj7** [comment]
@gregvanl

The indentation is not consistent.

If I indent the sub list with `css.propertyEnd` 2 spaces I get the correct rendering in VSC preview

You have to indent all 2 or 4 spaces. The sub list needs to align with the text of a list item.
