### ISSUE TITLE
VSCode API: QuickPickItem has links to QuickPickItemKind id's that do not exist

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#6237]
The API section [QuickPickItem](https://code.visualstudio.com/api/references/vscode-api#QuickPickItem) has a number of links to 

----

this property is ignored when [kind](https://code.visualstudio.com/api/references/vscode-api#QuickPickItem.kind) is set to [Separator](https://code.visualstudio.com/api/references/vscode-api#QuickPickItemKind.Separator)

When not specified, the default is [Default](https://code.visualstudio.com/api/references/vscode-api#QuickPickItemKind.Default).

----

`#QuickPickItemKind.Separator` and `#QuickPickItemKind.Default` do not exist

[QuickPickItemKind](https://code.visualstudio.com/api/references/vscode-api#QuickPickItemKind) does not explain a lot.

Also missing is how a separator is rendered.
Reading the QuickPickItem properties the `label` property is not ignored for Separators.
Trying it out in VSC 1.75:
A separator is a solid thin line. With the label text at the right below the solid line.

**Comment by gregvanl** [comment]
This is a known issue with our API generation not rendering enumerations and is already being tracked in our private website infrastructure repo.
I'm closing this issue as a duplicate and added a link in the other issue so that we can leave a comment when it is fixed.

**Comment by gregvanl** [comment]
This has been fixed and will be published shortly

![image](https://github.com/microsoft/vscode-docs/assets/12818376/8a75883f-ecaa-4a9a-8c6e-01fa3361cec3)
