### ISSUE TITLE
User Snippet Documentation Wrong (Mac OS) 

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode-docs#6238]
Does this issue occur when all extensions are disabled?: Yes/No
Yes
This is an issue with your user documentation: 
 [Create Your Own Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#:~:text=To%20create%20or%20edit%20your,should%20appear%20for%20all%20languages.)

This path File > Preferences (Code > Preferences on macOS), is incorrect.
![image](https://user-images.githubusercontent.com/20051/233138999-6675856f-3807-4ab9-b1f8-0211ee9ee536.png)

User Snippets are found here:
![image](https://user-images.githubusercontent.com/20051/233139356-c139a315-3be4-4f94-acf8-1a6a89c92126.png)

- VS Code Version: 
- Version: 1.77.1 (Universal)
- OS Version: 
- 13.2.1 (22D68)

**Comment by gregvanl** [comment]
Thanks for submitting an issue.
This is due to the Ventura update and is being tracked in https://github.com/microsoft/vscode-docs/pull/5937
Once the Ventura install base increases, we'll update the docs.
