### ISSUE TITLE
Add handling of the Terminal / Output pane under User Interface

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode-docs#6239]
In the [user interface section](https://code.visualstudio.com/docs/getstarted/userinterface) there is no mention of the handling of the terminal/output pane as described [here](https://code.visualstudio.com/updates/v1_64#_panel-alignment).

It would be helpful to include the update text in the core documentation under User Interface

**Comment by gregvanl** [comment]
Consider adding to a new "Advanced Editing" topic https://github.com/microsoft/vscode-docs/issues/6393
