### ISSUE TITLE
Update list of platforms to include web

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-docs#6243]
When reading the following https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions

```
The currently available platforms are: win32-x64, win32-ia32, win32-arm64, linux-x64, linux-arm64, linux-armhf, alpine-x64, alpine-arm64, darwin-x64 and darwin-arm64.

If you want a platform-specific extension to also support running in the browser as a [web extension](https://code.visualstudio.com/api/extension-guides/web-extensions), it must target the web platform when publishing. The web platform will respect the browser entry point in the package.json.
```

It wasn't evident that `web` was supported as a platform, as the first line states the list of valid values, and `web` isn't in that list.

**Comment by isidorn** [comment]
Tackled via https://github.com/microsoft/vscode-docs/commit/ef5b84ab72f3ec60658a0b87b2d0d09bdefc7367
