### ISSUE TITLE
Outdated explainer video on Live Share page

### ISSUE THREAD

**Issue by Frazer** [microsoft/vscode-docs#6255]
https://github.com/microsoft/vscode-docs/blob/main/learn/collaboration/live-share.md

includes [this explainer video](https://youtube.com/embed/A2ceblXTBBc?rel=0&disablekb=0&modestbranding=1&showinfo=0) which shows the Live share setup and how to use it.

In the setup step it shows the live share pack, which I don't think exists any more, and discusses Live share audio, which is now deprecated.

This is easy to ignore if someone already knows, but could be disorientating to people getting started, or not familiar with the github marketplace.

**Comment by Frazer** [comment]
Perhaps above the video could be a a disclaimer saying something like:

Note: this video shows installing the Live Share Pack, which is outdated. To achieve what you see in this video, use the Live Share extension.

**Comment by gregvanl** [comment]
@Frazer Thanks for pointing this out!
