### ISSUE TITLE
vscode.executeFoldingRangeProvider is not documented

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-docs#6258]
This command was added in February
https://github.com/microsoft/vscode/issues/36638
https://github.com/microsoft/vscode/issues/173445

It is not reflected in the documentation for built-in commands
https://code.visualstudio.com/api/references/commands

**Comment by aeschli** [comment]
I believe this is generated from the descriptions in the code @gregvanl

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/6256
