### ISSUE TITLE
Add missing colors

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-docs#6269]
Following colours are newly added, please add them to 

https://insiders.vscode.dev/github/microsoft/vscode-docs/blob/vnext/api/references/theme-color.md

- [ ] `interactive.requestBackground`: The background color of an interactive request. @lramos15 @roblourens 
- [ ] `interactive.requestBorder`: The border color of an interactive request. @lramos15 @roblourens  
- [ ] `interactiveEditor.border`: Border color of the interactive editor widget @jrieken 
- [ ] `interactiveEditor.shadow`: Shadow color of the interactive editor widget @jrieken 
- [ ] `interactiveEditor.regionHighlight`: Background highlighting of the current interactive region. Must be transparent. @jrieken 
- [ ] `interactiveEditorInput.border`: Border color of the interactive editor input @jrieken 
- [ ] `interactiveEditorInput.focusBorder`: Border color of the interactive editor input when focused @jrieken 
- [ ] `interactiveEditorInput.placeholderForeground`: Foreground color of the interactive editor input placeholder @jrieken 
- [ ] `interactiveEditorInput.background`: Background color of the interactive editor input @jrieken 
- [ ] `interactiveEditorDiff.inserted`: Background color of inserted text in the interactive editor input @jrieken 
- [ ] `interactiveEditorDiff.removed`: Background color of removed text in the interactive editor input @jrieken 
- [x] `peekViewEditorStickyScroll.background`: Background color of sticky scroll in the peek view editor @jrieken

**Comment by jrieken** [comment]
I believe we don't yet document these new colors because its preview and in-flux features

**Comment by sandy081** [comment]
@jrieken There is one colour from @aiday-mar ie `peekViewEditorStickyScroll.background` - Since she is on vacation, can you please take care of this?

**Comment by jrieken** [comment]
@sandy081 I actually already added `peekViewEditorStickyScroll.background` 2 months ago via https://github.com/microsoft/vscode-docs/commit/00d6cf3ade0b12f53c8a803ace2150469a30b918. How does this list get generated? Did I miss to update some place?

**Comment by sandy081** [comment]
Run `scripts/test-documentation.sh` on the release branch and I saw errors for above colours not being documented.

**Comment by gregvanl** [comment]
1.78 is out the door and appropriate theme colors were updated.

**Comment by EmrecanKaracayir** [comment]
`interactive.activeCodeBorder` and `interactive.inactiveCodeBorder` colors still not documented in version 1.80
