### ISSUE TITLE
Native modules update

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#627]
Refs: https://code.visualstudio.com/docs/extensions/patterns-and-principles#_common-questions

I see we actually encourage people to use native modules. This is dangerous because every time we update Electron these native modules will not work anymore. 

We should strongly advise AGAINST using native modules in extensions after all. And if nothing helps, tell people that each time we release a new version of VS Code they will have to recompile the prebundled native modules against the same node.js version that VS Code ships with.

/cc @egamma

**Comment by egamma** [comment]
Suggest to add a warning as @bpasero suggested to the question. We should keep the question.

>Notice: native modules bundled with an extension must be recompiled with every new version of VS Code against the same node.js version that VS Code ships with. 

We should keep the Common Questin

**Comment by bpasero** [comment]
Maybe add that finding out the node.js version and modules version can be done by running `process.versions` from the developer tools.

**Comment by egamma** [comment]
This is the background issue https://github.com/Microsoft/vscode/issues/13143
