### ISSUE TITLE
Unity support fully deprecated

### ISSUE THREAD

**Issue by sttz** [microsoft/vscode-docs#6273]
Unity has fully deprecated its support for VSCode. The debugger extension has been marked deprecated a while back (#5360) but the 2023.1 beta release of Unity has now deprecated and hidden the VSCode editor package, without which VSCode can only be used as a simple text editor with Unity.

There has been some effort by the community to update the package (most notably by Chizaruu [here](https://github.com/Chizaruu/com.tsk.ide.vscode)) but it's still early days and hard to tell how community support will pan out.

VSCode's Unity documentation should be updated: https://code.visualstudio.com/docs/other/unity

At the very least, there should be a prominent banner that explains that VSCode support in Unity is already limited for all Unity versions (no reliable debugging support) and will become fully unsupported in 2023.1. Maybe it would be better to mark the whole page as deprecated and only applying to old Unity versions – at least until the future of VSCode and Unity has become more clear.

Note that the official Unity documentation has not yet been updated (after many reminders by the community):
https://docs.unity3d.com/2023.1/Documentation/Manual/ScriptingToolsIDEs.html

The deprecation has only been announced in the Unity forums:
https://forum.unity.com/threads/update-on-the-visual-studio-code-package.1302621/

**Comment by gregvanl** [comment]
Closing as Microsoft just released the Unity for Visual Studio Code extension
See https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/ for the announcement.
People can leave feedback on the new extension and Unity in VS Code experience at https://github.com/microsoft/vscode-dotnettools/issues
