### ISSUE TITLE
"Microsoft Cloud for Sovereignty" link 404s in 1.78 release notes

### ISSUE THREAD

**Issue by JohnVeness** [microsoft/vscode-docs#6293]
The link to [Microsoft Cloud for Sovereignty](https://www.microsoft.com/industry/sovereignty/cloud) in https://github.com/microsoft/vscode-docs/blob/f1f8bc68f8b7f06f5d1e0f69c6d16927fcdeb7c1/release-notes/v1_78.md?plain=1#L491 leads to a "We are sorry, the page you requested cannot be found".

https://www.microsoft.com/en-us/industry/sovereignty/cloud seems to work, but I don't know if there's a better or language-neutral URL to use.

**Comment by gregvanl** [comment]
Hmm, that is odd that the site doesn't handle localized content except for en-us.
Thanks for pointing this out. I tested over a VPN and see the same issue.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/6319
