### ISSUE TITLE
Update shell integration sequence 633 E to include the new optional nonce

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#6299]
Documenting this change https://github.com/microsoft/vscode/pull/181523

https://code.visualstudio.com/docs/terminal/shell-integration#_vs-code-custom-sequences-osc-633-st

**Comment by Lokeshc123** [comment]
is this issue still open?

**Comment by Tyriar** [comment]
Yes, the docs haven't been updated yet
