### ISSUE TITLE
Invalid sentence in ASP.NET 5 Runtime docs

### ISSUE THREAD

**Issue by scottaddie** [Microsoft/vscode-docs#63]
In the "Projects and Project Selection" section of Runtimes --> ASP.NET 5, the following sentence needs to be rewritten:

"If you have multiple project.json files you can pick which one you want to use, looks down in the status bar."

What was it intended to say? In its current state, it makes no sense.

**Comment by egamma** [comment]
The sentence refers to the C# status indicator in the bottom left of the status bar.

**Comment by scottaddie** [comment]
@egamma That's the other part that I question. Doesn't the OmniSharp status indicator appear in the bottom right of the status bar? I wonder if that screenshot is from an older version of VS Code.

**Comment by egamma** [comment]
Sorry, the bottom right of the status bar it is... (I'm left handed and still confuse left and right :smile: )

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/pull/66.
Thanks Scott!
