### ISSUE TITLE
Cannot remove extension from profile via `Profiles: Show Contents` view

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode-docs#6302]
The [docs](https://code.visualstudio.com/docs/editor/profiles#_profile-contents) state:

> The Profiles: Show Contents command (available in the Command Palette or Profiles menus) brings up the Profiles view, where you can review the customizations for the profile.

> Extensions - You can remove extensions from the profile by unchecking their entry in the Profiles view.

Implying that unchecking extensions in the `Profiles: Show Contents` view will remove them.

However, unchecking only prevents them from being exported into a file / gist.

VS Code version: Code 1.78.0 (Universal) (https://github.com/microsoft/vscode/commit/252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

**Comment by sandy081** [comment]
@gregvanl Can you please clarify in the profiles wiki that unselecting will not include the extension in the profile to export?
