### ISSUE TITLE
Secondary Side Bar deserves better documentation

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#6326]
Its existence is mentioned only briefly at https://code.visualstudio.com/docs/getstarted/userinterface#_basic-layout

![image](https://github.com/microsoft/vscode-docs/assets/6726799/c916536c-64d2-4a17-b108-ac4363f9dfb6)

but I didn't find information about how to move views there. Perhaps improve https://code.visualstudio.com/docs/getstarted/userinterface#_views to cover that.

**Comment by gjsjohnmurray** [comment]
Evidence at https://github.com/microsoft/vscode/issues/182836#issuecomment-1554046268

**Comment by cadamini** [comment]
Unfortunately, there is no preview because I am working on VS Code Web. I hope my content/image looks good and you like my changes @gjsjohnmurray

**Comment by gregvanl** [comment]
Not sure we need to add more documentation here. Might wait to see if there are upvotes.

For how to populate the Secondary Side Bar, there is a prompt in the UX.

![image](https://github.com/microsoft/vscode-docs/assets/12818376/0feba6a0-0ff8-4a9a-b8a3-c844e15918b2)

**Comment by gjsjohnmurray** [comment]
@sbatten I think you did a lot of the work to create the Secondary Side Bar. Do you think it is under-documented in places where new users might be reading?
