### ISSUE TITLE
Update tasks doc to remove Jake

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#636]
Per this issue - https://github.com/Microsoft/vscode/issues/13322#issuecomment-252598550

We do not support Jake through auto discovery anymore. We should update the doc.

**Comment by gregvanl** [comment]
I think we do. In https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts, I still see tryDetectJake called.

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode/issues/13322#issuecomment-252598550 is about the Configure Task Runner dropdown (which doesn't have a Jake option) not autodetection.
