### ISSUE TITLE
Old image and meta-data is shown on Twitter for release notes URL

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-docs#637]
Link: https://code.visualstudio.com/updates#_experimental-node-debugger  to the 1.6 release notes

Preview on twitter:
![monosnap 2016-10-10 16-58-02](https://cloud.githubusercontent.com/assets/173559/19252490/b9331072-8f0a-11e6-943a-eaf272537a86.png)

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/376e13111b9bbd6e8bdc7b87c3c1aa3f67e8c5f4#diff-4e86ebf9c53698bb20c2858bcbe79267
Thanks for catching this quickly.

**Comment by auchenberg** [comment]
Yay 🔥
