### ISSUE TITLE
Jump to logical EOL as well as physical EOL

### ISSUE THREAD

**Issue by Iwan-Zotow** [Microsoft/vscode-docs#638]
When line-wrap is enables, logical EOL != physical EOL. With [End] key could only jump to logical EOL

Would greatly help with editing LONG lines in the files

**Comment by gregvanl** [comment]
Hi @Iwan-Zotow,
This repo is for vscode documentation content and issues. This sounds like a product suggestion so please enter a new issue in the product repo https://github.com/Microsoft/vscode/issues.
Thanks
