### ISSUE TITLE
Documentation for the keybinding when condition

### ISSUE THREAD

**Issue by krokofant** [Microsoft/vscode-docs#641]
Is there some complete list of what conditions are available for the *when* option in regards to keybindings?

There is the default keybindings.json file but it doesn't explain much.

**Comment by gregvanl** [comment]
There is documentation at http://code.visualstudio.com/docs/customization/keybindings#_when-clause-contexts.
There is also an open issue to add when clause IntelliSense (suggestions). Feel free to vote up that issue (thumbs up) if you think that would be useful.

**Comment by krokofant** [comment]
@gregvanl Thank you. I missed that but the list doesn't seem exhaustive. There are multiple *config.x* that's not listed and for example the *editorHasCompletionItemProvider*.

**Comment by gregvanl** [comment]
@krokofant Yes, I opted not to be exhaustive and left out those _when_ clause items that are specific to VS Code UI shortcuts. I didn't think users would want to override those key bindings and it would have made the list too long.

**Comment by gregvanl** [comment]
Oops I forgot to link to the vscode product issue to offer _when_ clause IntelliSense https://github.com/Microsoft/vscode/issues/9303

**Comment by krokofant** [comment]
@gregvanl I see. Personally it left me thinking what else interesting options where excluded as I first viewed the default keybindings.json as a reference.

**Comment by bohenderson** [comment]
If I wanted to see the exhaustive list of when-contexts for keybindings where would I look?
Is there a command analogous to `vscode.commands.getCommands()` that I could use to get all valid context properties?
Thanks!

**Comment by Prodigy97** [comment]
> Is there some complete list of what conditions are available for the _when_ option in regards to keybindings?
> 
> There is the default keybindings.json file but it doesn't explain much.

yeah, I've been keen on knowing the options for the "when condition" as well

**Comment by soletan** [comment]
Since I came here looking for available values to use in the when clause and missing the link on the page that has been linked above already, I'd like to add here that link to a list of potential values to test for directly so maybe others don't miss that like I did.

https://code.visualstudio.com/api/references/when-clause-contexts#available-context-keys
