### ISSUE TITLE
Notebook extension guide is outdated?

### ISSUE THREAD

**Issue by PatrickMassot** [microsoft/vscode-docs#6420]
Thank you very much for your hard work on documenting VSCode.

It  seems to me the [notebook extension guide](https://code.visualstudio.com/api/extension-guides/notebook) is no  longer accurate. The first section, titled Serializer, is meant to build "a simplified notebook provider extension for viewing files in the [Jupyter Notebook format](https://nbformat.readthedocs.io/en/latest/format_description.html)" but typing the code from the included snippets does not seem to work at all. Maybe this is relying on an old version of the jupyter format because the code does not seem likely to parse anything that looks like the file file structure described in jupyter's documentation you link to. For instance your code seems to assume that top level structure of the file is a list of cells.

I managed to create a custom notebook format that can be read by your code, but then the markdown cells are not rendered at all, one simply sees the markdown source code. Is this meant to be handled by a Controller? From your documentation is sounds like controllers are in charge of executing code cells, not markdown ones.

Note I tried all this on VSCode 1.79.2 on Linux.

**Comment by gregvanl** [comment]
Hi @PatrickMassot I think you meant to link to the Notebook extension guide at https://code.visualstudio.com/api/extension-guides/notebook.
I'll ask a VS Code engineer to have a look at your comments and the current state of the guide. Thanks!

**Comment by PatrickMassot** [comment]
Oops, sorry about the wrong link. I fixed it thanks!

**Comment by rebornix** [comment]
We have pushed updates for serializer doc in vnext, it will be available soon.

**Comment by PatrickMassot** [comment]
Thanks! The next step to make this documentation really useful would be to have more complete examples, including one managing a document behind the scene instead of having purely stateless examples and ` /* Do some execution here; not implemented */` comments.
