### ISSUE TITLE
Create "Glob Patterns Reference" topic

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#6421]
Currently we link to either:
https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options
https://en.wikipedia.org/wiki/Glob_(programming)
when we want to detail glob patterns.
One option would be to create a separate "Glob Patterns Reference" topic under /docs/editor but not visible in the TOC (similar to the "Variables Reference" topic and put existing content there along with general glob pattern usage and explanation.

**Comment by bpasero** [comment]
@gregvanl yes I like that, if you can prepare that site I can fill in the description. 

Our glob implementation is not a standard and misses some behaviour from the standard so I think we cannot link to a wikipedia page.

**Comment by bpasero** [comment]
New topic: `glob-patterns.md`

**Comment by gregvanl** [comment]
This will go out in the 1.80 release
