### ISSUE TITLE
`vscode.workspace.findFiles` example formatting problem

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#6436]
The example of [`vscode.workspace.findFiles`](https://code.visualstudio.com/api/references/vscode-api#workspace.findFiles) is ill formatted

It should look like

```ts
findFiles('*/.js', '/node_modules/', 10)
```

**Comment by gregvanl** [comment]
Looks like a general problem for any `@example` rendered from vscode.d.ts.

		/**
		 * Find files across all {@link workspace.workspaceFolders workspace folders} in the workspace.
		 *
		 * @example
		 * findFiles('**​/*.js', '**​/node_modules/**', 10)
		 *

**Comment by rioj7** [comment]
@gregvanl I looked in the doc repo for the API Markdown file and it looks like it is generated by a tool, 99% is hard coded HTML

**Comment by gregvanl** [comment]
Yep, the version at /api/reference/vscode-api.md is just a build artifact reflecting changes in the /api/references/vscode-api.template and not actually used.
The website build in the vscode-website (private repo) takes the release version of vscode.d.ts (based on the VSCodeCommitHash in the template, and along with the template text sections, generates the HTML page for the website .
To fix this issue, a VS Code engineer would need to make a fix to the API generation in the vscode-website repo.
Once we're done chatting, I'll move this issue over to that repo.

**Comment by gregvanl** [comment]
This is fixed in the API generation and will be published shortly

![image](https://github.com/microsoft/vscode-docs/assets/12818376/673ae5ec-bfd1-4dd8-9bd0-924712c12cfa)
