### ISSUE TITLE
Screen capturing tool for Release Notes

### ISSUE THREAD

**Issue by BukeMan** [microsoft/vscode-docs#6471]
Not really an issue, just a question. 

I'm impressed with the quality and relatively small size of the GIFs and screen recordings included in the release notes.
Could someone shed light on what tool(s) are used to get such results?

**Comment by gregvanl** [comment]
Hi @BukeMan The VS Code team uses a variety of screen recording tools. One free option is from Open Broadcaster Software at https://obsproject.com/.

We had been primarily using GIFs, as they were easy to record and embed with Markdown image tags, but have switched to using MP4 in video elements to improve rendering performance and allow users more control when viewing videos.

**Comment by BukeMan** [comment]
Hi @gregvanl, thanks for replying 🙂 
Would you mind sharing the tool for making GIFs? All I've tried produce either low quality or very big file size 😕

**Comment by gregvanl** [comment]
A VS Code engineer built https://gifcap.dev/ It does compression automatically for you. We also use https://ezgif.com/optimize for shrinking GIFs before we publish to the site

**Comment by BukeMan** [comment]
Wow 🤩 Thanks a lot!
