### ISSUE TITLE
STOP CLOSING THREADS DOWNLOAD WONT WORK

### ISSUE THREAD

**Issue by megatronskneecap** [microsoft/vscode-docs#6503]

**Comment by gregvanl** [comment]
There is already a vscode-docs issue tracking the download issue and it is being worked on by VS Code engineering.

Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Comment by megatronskneecap** [comment]
> There is already a vscode-docs issue tracking the download issue and it is being worked on by VS Code engineering.
> 
> Duplicate of #6496

Yeah but bro it won't work I'm not sure why you're marking them as duplicates and fixed
