### ISSUE TITLE
Vs Code install

### ISSUE THREAD

**Issue by Phantomthesigma** [microsoft/vscode-docs#6505]
https://az764295.vo.msecnd.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/VSCodeUserSetup-x64-1.80.1.exe

**Comment by naathael** [comment]
Thks

**Comment by Sh4krasq** [comment]
tysm bro

**Comment by gregvanl** [comment]
As a workaround, you can create the download URL by following the platform-specific URL patterns documented in https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

For example: https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode-docs/issues/6496
