### ISSUE TITLE
 404 error

### ISSUE THREAD

**Issue by Amin-Keshavarz** [microsoft/vscode-docs#6508]
When trying to download VS Code, we encounter a 404 error. What is the solution?

**Comment by muhohokenya** [comment]
Same issue

**Comment by TomQuixote** [comment]
Same here

**Comment by rajanazirul** [comment]
same here

**Comment by gregvanl** [comment]
As a workaround, you can create the download URL by following the platform-specific URL patterns documented in https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

For example: https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496
