### ISSUE TITLE
Application popup: Visual Studio Just-In-Time Debugger caused crash

### ISSUE THREAD

**Issue by kian25** [microsoft/vscode-docs#6519]
Application popup: Visual Studio Just-In-Time Debugger : An unhandled win32 exception occurred in [5108] soffice.bin. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.

Check the documentation index for 'Just-in-time debugging, errors' for more information.

just caused my LibreOffice application to crash and I lost all my information wasting a whole day, no idea why these two applications should even be interacting with each other

Any help would be appreciated

**Comment by gregvanl** [comment]
Hi @kian25 Sorry that you're having trouble and may have lost some work.
This repository is for VS Code documentation. It appears from the description above that you are using Visual Studio (IDE) and not VS Code.

**Comment by gregvanl** [comment]
Closing as no response from user and appears to be a question about VS IDE not VS Code
