### ISSUE TITLE
CURRENT_TIMEZONE_OFFSET is missing colon in docs

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-docs#6530]
https://code.visualstudio.com/docs/editor/userdefinedsnippets#:~:text=CURRENT_TIMEZONE_OFFSET

`CURRENT_TIMEZONE_OFFSET` 

is documented as: `+HHMM` or `-HHMM` (example `-0700`)

It should be: `+HH:MM` or `-HH:MM` (example `-07:00`)

**Comment by gregvanl** [comment]
Thanks for pointing this out!
