### ISSUE TITLE
Add docs on locked editor groups

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#6568]
I get issues and there's nowhere to point users other than at old release notes

**Comment by gregvanl** [comment]
Duplicate of https://github.com/microsoft/vscode-docs/issues/6312
Propose adding an "Advanced Editing" topic (under User Guide) where we could put more advanced features currently only covered in release notes see https://github.com/microsoft/vscode-docs/issues/6393. This new topic isn't currently planned for April but could be pulled in.

**Comment by Tyriar** [comment]
@gregvanl there was also https://code.visualstudio.com/docs/editor/command-line#_how-do-i-detect-when-a-shell-was-launched-by-vs-code which I just added that doesn't really fit in there. It's more of a advanced customization topic though.

**Comment by Tyriar** [comment]
Added basic docs to https://github.com/microsoft/vscode-docs/commit/3d9ea261ea815e0568c6f2b365a9416e8ce30deb, closing.
