### ISSUE TITLE
vscode API generation not working after recent vscode.d.ts change

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#657]
It looks like commit https://github.com/Microsoft/vscode/commit/dc7402b978ba64b8951bb38a9a9ec5f37de6f205 broke the vscode API generation. I'm guessing the change from "namespace vscode" to "module 'vscode'" is messing up the scripts in vscode-docs api-doc.

**Comment by jrieken** [comment]
fixed on vnext-branch
