### ISSUE TITLE
Document how to hide actions from tool bars

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#6584]
Currently it's only documented in the release notes https://code.visualstudio.com/updates/v1_72#_hide-actions-from-tool-bars

**Comment by gregvanl** [comment]
I worry about putting this tip in introductory content as new users might shoot themselves in the foot if they accidentally hide items.
I'm thinking that "Advanced Features" would be broken up into sections such as "Workbench", "Editor", etc.

**Comment by Tyriar** [comment]
Should we differentiate UI customization from more functional features? Similar to the Terminal > Appearance page?

**Comment by Tyriar** [comment]
Already tackled for the most part in the advancedFeatures branch
