### ISSUE TITLE
"Close All Editors" button gets minimized in dropdown

### ISSUE THREAD

**Issue by mayankrastogi02** [microsoft/vscode-docs#6608]
**Issue:** 
The "Close All Editors" button in the "Open Editors" section of the Explorer pane gets minimized into the dropdown menu (...) "More Actions..."?

**Background Information:**

- Screen is pretty big and the pane is also extended to easily manage the button.
- The same button is visible on the Open Projects (Folder) Tree

**Resources:**
![image](https://github.com/microsoft/vscode-docs/assets/62538173/a9908a81-c7ed-42a1-8531-6077f6d5f57f)
Close All Editors getting merged into "More Actions"

![image](https://github.com/microsoft/vscode-docs/assets/62538173/522729a4-650c-4b9f-a1b5-3408e039c6ea)
"Close All Editors" button appearing on the open folders tree.

**Comment by gregvanl** [comment]
Hi @mayankrastogi02 I think you may have previously or accidentally hidden the "Close All Editors" button.

It is a general feature that if you right-click on any title bar you can hide title bar items.

![image](https://github.com/microsoft/vscode-docs/assets/12818376/18076a24-5d85-4e7a-bdf3-6501d1b5b8ac)

You can unhide items by right-clicking again on the title bar item region and check the hidden item or use the general "Reset Menu" option.

![image](https://github.com/microsoft/vscode-docs/assets/12818376/51530fda-bfb6-4176-9bd9-b527b3346b24)

**Comment by gregvanl** [comment]
And here is a little more explanation of the feature in the 1.72 release notes https://code.visualstudio.com/updates/v1_72#_hide-actions-from-tool-bars

We're currently working on a "Custom Layout" article in the VS Code main docs, which include a section on hiding tool bar items.

**Comment by mayankrastogi02** [comment]
Thanks @gregvanl that did the trick!!
Wasn't able to find that option earlier - had to click on one of the existing buttons on the toolbar and not the toolbar itself.
