### ISSUE TITLE
Link in 1.82 release notes is to an unrelated issue 

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#6635]
https://github.com/microsoft/vscode-docs/blob/2e059de85f0d53bf3fa46220a333eb9d32d0776f/release-notes/v1_82.md?plain=1#L282

This seems to be linking to the wrong issue/PR.

**Comment by gjsjohnmurray** [comment]
Pinging @connor4312

**Comment by gregvanl** [comment]
Fixed during recent edit pass https://github.com/microsoft/vscode-docs/commit/249520962457c04d3a16ef602d2f578c8a5819bc

**Comment by connor4312** [comment]
Thanks Greg!
