### ISSUE TITLE
Some Function in vector library are not working and some are absolutely fine. How to resolve this issue? The tutorial(https://code.visualstudio.com/docs/cpp/config-clang-mac) is not working.

### ISSUE THREAD

**Issue by JagtapDinesh1107** [microsoft/vscode-docs#6643]
<img width="1440" alt="Screenshot 2023-09-06 at 12 47 38 PM" src="https://github.com/microsoft/vscode-docs/assets/127584831/42e42887-95d3-42e3-83d9-ba13a18b1a9a">

**Comment by AlexandraKemperMS** [comment]
Hi @JagtapDinesh1107, which version of the C/C++ Extension are you using? We recently fixed this issue in the newest stable version (1.17.2) of the C/C++ Extension.  You can check your version of the Extension by navigating to the Extensions view on the left, then finding the C/C++ Extension. The version number is at the top of the page, next to the title and starts with a v. If you have a version before 1.17, please update by clicking the "sync" button to the right of the "disable" and "uninstall" buttons.

**Comment by JagtapDinesh1107** [comment]
the version I am using is v1.17.5

**Comment by AlexandraKemperMS** [comment]
Hm, that is unusual - did you just upgrade or were you on 1.17.5 previously? could you restart VS Code and see if that fixes it?

**Comment by JagtapDinesh1107** [comment]
I was previously on v1.17.5. I switched g++ to clang++. But still I am facing the same issue.

**Comment by AlexandraKemperMS** [comment]
Could you send me a screenshot of the terminal that includes the command you are running as well as the error? Also have you tried copying the command that cause the error and manually running it again with `-std=c++14` appended to it.

**Comment by JagtapDinesh1107** [comment]
The problem was solved by adding the -std=c++14 flag.
Thank you @AlexandraKemperMS for helping.
