### ISSUE TITLE
Use table instead of collapsed items while documenting enumerated values

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-docs#665]
https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_a-namecompletionitemkindaspan-classcodeitem-id690completionitemkindspan talks about the different Completion Item Kinds.

When you expand any of the below, all you see is the number associated with the enumeration.
If its just the number we want to document, then we should use a table. Why all the clicks just to see a number?

![image](https://cloud.githubusercontent.com/assets/16890566/19979343/57f90784-a1b7-11e6-97d3-b1a16b1bda1d.png)

**Comment by oriash93** [comment]
might be related to #1151

**Comment by gregvanl** [comment]
@oriash93 Thanks for calling this out. Closed #1151.

**Comment by gregvanl** [comment]
No current plans to update the VS Code API generation. Closing old issue
