### ISSUE TITLE
Move existing refs of deprecated vscode-dev-containers repo to the new devcontainer one

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-docs#6671]
While looking for documentation about devcontainers I stumbled into some pages on the VS Code docs website that still refer to the deprecated repo https://github.com/microsoft/vscode-dev-containers. We should consider updating those pages to refer to the newer https://github.com/microsoft/devcontainers equivalent pages.

CC @bamurtaugh

**Comment by bamurtaugh** [comment]
Hi @iemejia, thanks for opening this! Yes, we'd definitely want to remove references to vscode-dev-containers. We continue trying to find and remove any, so if you've found anymore, it'd be great if you could share them here and/or open a PR to update them.

**Comment by gregvanl** [comment]
Closing as I believe all the references to vscode-dev-containers have been removed from the main vscode-docs topics.
There are still a few mentions in an early blog post and release notes but we don't typically update point-in-time content.
There are also mentions of vscode-dev-containers describing its deprecation and new devcontainers location (for example in the Dev Containers Features blog post https://code.visualstudio.com/blogs/2022/09/15/dev-container-features#_what-else-is-new)
