### ISSUE TITLE
Keyboard shortcuts title

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#668]
Small thing - this is what we see on the keyboard shortcuts for a title. 

![image](https://cloud.githubusercontent.com/assets/2449568/20013429/53daa78e-a270-11e6-9c80-017891afd20a.png)

**Comment by gregvanl** [comment]
Huh, where? I don't see this when I look at the PDFs on either Windows or OS X.

**Comment by waderyan** [comment]
I click on the link on the keybindings doc. I'm using Chrome.

**Comment by waderyan** [comment]
Shows for all three keyboard shortcut cheat sheets for me

**Comment by gregvanl** [comment]
Got it. Doesn't show for Edge. Assigning to @bgashler1 as I just mess up the PDFs when I touch them. Might just be able to clean up the name during the export to PDF.

**Comment by bgashler1** [comment]
This Chrome trying to be helpful.  I think it's referencing metadata within the PDF.  We could manually change this metadata using Adobe Acrobat (but we would need to do it each time we change the cheat sheets).  The alternative is to embed the PDF in an HTML page that we insert a `<title>` tag in.
What do you guys feel more comfortable with?

**Comment by gregvanl** [comment]
Haven't heard this mentioned by any customers. Closing.
