### ISSUE TITLE
Introduce emoji reactions next to sections in release notes

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-docs#6680]
https://code.visualstudio.com/updates/v1_82

Not sure if we would want to do this but this might help with engagement. Users may be more likely to provide feedback or express their feelings about a particular update.

**Comment by gregvanl** [comment]
Not sure how we would do this for both in-product and website release notes or where the feedback would go. 
So far no community upvotes.
Closing now as we already have GitHub issues, Twitter (X) comments, and release notes doc feedback
