### ISSUE TITLE
debugServer no longer supported topLevel in launch.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#674]
We need to update the docs and mention that the `debugServer` attribute is no longer supported top level, but now it needs to be inside the configurations. One reference where I found this is 
https://code.visualstudio.com/docs/extensions/example-debuggers
For that specific case we need to change the json to the following:
{
    "version": "0.2.0",

    "configurations": [{
        "name": "mock test",
        "request": "launch",
        "debugServer": 4711,
        "type": "mock",
        "program": "${workspaceRoot}/readme.md",
        "stopOnEntry": true
    }]
}

We should do a full text search for all mentions of 'debugServer' and update the docs

**Comment by gregvanl** [comment]
Change made in vnext branch and autoclose only works on master.
