### ISSUE TITLE
Add warning that `window.activeBorder` does not work on Windows

### ISSUE THREAD

**Issue by inigohidalgo** [microsoft/vscode-docs#6765]
Window border color customization in Windows was removed from VSCode in v1.71 as per this comment https://github.com/microsoft/vscode/issues/160159#issuecomment-1238190871

The documentation for color customizations does not mention this https://code.visualstudio.com/api/references/theme-color#window-border

**Comment by joey2031** [comment]
Hey I don't mind working on this issue, should we just add a bullet point under "Window Border" that says "The feature was removed VSCode in v1.71" or just get rid of this whole section in the image?

<img width="457" alt="image" src="https://github.com/microsoft/vscode-docs/assets/36198917/9dfb8210-4b8f-43aa-a054-4e33b2f4712c">

**Comment by inigohidalgo** [comment]
As far as I can tell from the issue, it only doesn't work in windows, but I have no way of checking atm.
