### ISSUE TITLE
Update the common questions for JavaScript for 1.7

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#677]
https://code.visualstudio.com/docs/languages/javascript#_common-questions

This is no longer needed:

![image](https://cloud.githubusercontent.com/assets/172399/20248271/9f11c21a-a9e0-11e6-8200-4503a09ccfd2.png)

CC @waderyan

**Comment by waderyan** [comment]
done with this PR - https://github.com/Microsoft/vscode-docs/pull/679
