### ISSUE TITLE
Remove mention of Mesa for Chromium bug

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-docs#6776]
> Can whoever is in charge of the release notes delete the mention that this issue has anything to do with Mesa? It has nothing to do with this issue, this is 100% a pure upstream Chromium issue bug. Mesa makes no guarantees that compiled shader objects should be compatible across updates to mesalib, libdrm, xorg libraries, llvm etc. There's nothing wrong with keeping a cache of those things, but the correct behavior is to discard it upon obvious errors and compile new objects to replace them.
> 
> 
> 
> Source, I help maintain a popular Linux distro and have seen this issue dozens of times across multiple Chromium applications. The following commands are our recommended first troubleshooting step whenever a user complains about rendering issues with Chrome(ium) or an Electron app:
> 
> ```
> 
> find ~/.config -name GPUCache -exec rm -rv {} +
> 
> find ~/.cache -name GPUCache -exec rm -rv {} +
> 
> ``` 

 _Originally posted by @ReillyBrogan in [#193096](https://github.com/microsoft/vscode/issues/193096#issuecomment-1778240213)_

**Comment by gregvanl** [comment]
This issue should be fixed with the next VS Code release 1.85 as https://github.com/microsoft/vscode/issues/190437 is fixed.
While the issue may not be due to an issue with Mesa, it does manifest itself after a Mesa update and is what user will probably search for.
We can look into updating the wording

**Comment by gregvanl** [comment]
Updated release notes wording with https://github.com/microsoft/vscode-docs/commit/13789f1aca504f98824ccc6a108014e5470d44ad
