### ISSUE TITLE
Vue: use create-vue instead of Vue CLI

### ISSUE THREAD

**Issue by sapphi-red** [microsoft/vscode-docs#6788]
The [Vue tutorial](https://github.com/microsoft/vscode-docs/blob/main/docs/nodejs/vuejs-tutorial.md) uses [Vue CLI which is in maintenance mode](https://cli.vuejs.org/#getting-started:~:text=Vue%20CLI%20is,the%20latest%20recommendations.). Vue CLI now recommends [create-vue](https://github.com/vuejs/create-vue) instead.

refs #5189

Disclaimer: I'm a core team member of Vite that is used in create-vue under the hood.

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/pull/6925
