### ISSUE TITLE
Animated GIF in 1.84.0 release notes looks ugly and hard to read (aliasing)

### ISSUE THREAD

**Issue by JohnVeness** [microsoft/vscode-docs#6790]
In the latest release notes (https://code.visualstudio.com/updates/v1_84) the topmost animated gif is showing horrible aliasing, depending on what size it is viewed at. See this static screenshot:

![image](https://github.com/microsoft/vscode-docs/assets/2512915/ff3b35af-7247-4398-ac2b-dab31fc85e5c)

**Comment by gregvanl** [comment]
Hi @JohnVeness Do the other .gifs on the 1.84 release notes also render poorly? For example, there are .gifs for the "Hide Editor Tabs" and "Maximize Editor Groups" sections.
In general, we are moving toward using .mp4 for release notes short videos and so we're curious if you and others are seeing a general problem with .gif rendering on code.visualstudio.com.
Also how does the .gif look in-product, if you view the release notes with Help > Show Release Notes in VS Code?

**Comment by JohnVeness** [comment]
Thanks for the reply. It's just the gif at https://code.visualstudio.com/updates/v1_84#_customize-activity-bar-position that seems to be affected on that page.

Looking at it closely, the background colours are dithered, causing the visual artefacts which show up at different zoom levels. The other gifs seem to be using flat colours. I know gifs are limited to 256 colours so I guess something was different about the theme used, or the gif encoding process, for the troublesome gif.

This does show up in the release notes in the app too, depending on the zoom level (Ctrl+Minus and Ctrl+Plus).

Yes, I noticed the most of the videos were .mp4, which seemed fine, so those are probably better to use that GIFs (or maybe animated PNGs).

**Comment by gregvanl** [comment]
Closing as it's been over a week since the 1.84 release and haven't heard of other users seeing this rendering issue.
Going forward, we'll push for using .mp4 instead of .gifs.
Thanks for calling attention to this issue with .gifs
