### ISSUE TITLE
Dead link to docs/extensionAPI/vscode-api.md

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode-docs#68]
This file https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/overview.md
links to this: https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/vscode-api.md

So there is no API documentation currently available.

**Comment by gregvanl** [comment]
Thanks for noticing so quickly.  We're doing some work on our doc tooling and our generated API docs.   While this is under development, you may see GitHub wonkiness.  I'll leave this issue open so we'll make sure GitHub navigation continues to work well.

**Comment by gregvanl** [comment]
We've rethought this and now that vscode-api.md is autogenerated, we don't want folks to think they can make manual changes to the markdown and we'll only include the template file in GitHub.  The link will be broken for GitHub navigation but it will work on code.visualstudio.com.
Again thanks for your support.
