### ISSUE TITLE
VSCode Python Terminal EROR

### ISSUE THREAD

**Issue by OnDrax-GT** [microsoft/vscode-docs#6814]
PS C:\Users\OnDrax\Projects\Learn> python3 hello.py
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was   
included, verify that the path is correct and try again.
At line:1 char:1
+ python3 hello.py
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundE  
   xception
    + FullyQualifiedErrorId : CommandNotFoundException

I want to run my file but when i input python3 hello.py it shown EROR mesage like this
Pls help me Fix it

**Comment by luabud** [comment]
Hi @OnDrax-GT! Can you please file an issue providing your environment information in the vscode-python repo? The easiest way to do that is by opening VS Code, making sure you have the [Python extension ](https://marketplace.visualstudio.com/items?itemName=ms-python.python) installed, opening the command palette (View > Command Palette...) and typing "Python: Report Issue". It will open up a window with some information that we automatically collect from your settings. Then you can click on the "Create issue" button and it will direct you to the right repo. 

In the mean time, looking at your error, it seems you're trying to run `python3` in PowerShell. Give `py` a try instead, or just `python`, and that may work if you have Python installed! If you don't, make sure to install it here: https://www.python.org/
