### ISSUE TITLE
New Marketplace links

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#684]
The Marketplace has added new links and badges to the Marketplace. We should document how to take advantage of this. 

![image](https://cloud.githubusercontent.com/assets/2449568/20415109/1b05227e-aceb-11e6-93e8-0993da3a41b2.png)

**Comment by gregvanl** [comment]
Closing old issue. Extenders learn from existing open source extension READMEs. It would be hard to keep up with new links and badges.
