### ISSUE TITLE
Extension Packs

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#685]
We should add some docs on best practices for extension packs. I get a handful of questions about them and I'm not sure how they work :)

**Comment by gregvanl** [comment]
Added a section to extension-manifest.md for now for extension authors. Once more Extension Packs are available, we should add a section to the general user extension-gallery.md topic.
https://github.com/Microsoft/vscode-docs/commit/5a2b622c0d2822439eb1bd131f2f64ed1ec57843
