### ISSUE TITLE
Typos in api/ux-guidelines/sidebars

### ISSUE THREAD

**Issue by fyasla** [microsoft/vscode-docs#6857]
In the [UX guidelines for sidebars doc](https://code.visualstudio.com/api/ux-guidelines/sidebars) there are two minor typos:

1. 

> # Sidebars
> 
> The Primary and Secondary Sidebars one of more [Views](/api/ux-guidelines/views) contributed by a [View Container](/api/ux-guidelines/views#view-containers). 
> 
Should be 
> # Sidebars
> 
> The Primary and Secondary Sidebars consists of one or more [Views](/api/ux-guidelines/views) contributed by a [View Container](/api/ux-guidelines/views#view-containers). 
> 

2.

>**❌ Don't**
> 
> - Use an excessive number of View Containers. A single View Container (such as a Sidebar with Views unique that extension) is generally enough for most extensions.
>
should be
> **❌ Don't**
> 
> - Use an excessive number of View Containers. A single View Container (such as a Sidebar with Views unique to that extension) is generally enough for most extensions.
>

**Comment by gregvanl** [comment]
Fixed with #6858
