### ISSUE TITLE
Broken Documentation for Document Selector

### ISSUE THREAD

**Issue by caleb-at-pieces** [microsoft/vscode-docs#6869]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: n/a
- OS Version: n/a

Steps to Reproduce:

1. Go to https://code.visualstudio.com/api/references/vscode-api#DocumentSelector
2. Click on the expand box for the Document Selector
3. nothing happens

Expected behavior is for the box to expand to show more details about the class, much like the rest of the entries on the page.

**Comment by gregvanl** [comment]
Hi @caleb-at-pieces Thank you for calling this out. 
This is a duplicate issue already being tracked in the vscode-website infrastructure repo. Unfortunately the vscode-website repo is private so not great for tracking this issue

**Comment by gregvanl** [comment]
duplicate of https://github.com/microsoft/vscode-website/issues/541
