### ISSUE TITLE
What happened to the vscode-website repo?

### ISSUE THREAD

**Issue by ovasquez** [Microsoft/vscode-docs#687]
I know this might not be the best place to ask, but I haven't found a better place yet.
After trying to build the vscode-docs I noticed the vscode-website repo was probably made private. Is there any chance for this to be made public again to build the website locally?

I reviewed the vscode-docs some time ago and the website source was available, so I don't know why this changed :(

**Comment by gregvanl** [comment]
Hi @ovasquez,
As far as I know, the vscode-website has never been public. It just has the source code for our code.visualstudio.com website which we haven't expected users to need access to.
For viewing vscode-docs Markdown updates, most contributors have found the VS Code Markdown preview sufficient. Is there some documentation change you want to make that needs the full website page rendering?

**Comment by ovasquez** [comment]
Hi @gregvanl , I recall the vscode-website being public at some point (there are issues indexed in Google search). There wasn't anything specific that needed a change in the website, but I noticed the build process (which I know is not required for updating the Markdowns) required access to it and was just wondering what happened to it.
