### ISSUE TITLE
Markdown to HTML conversion issue on the docs/tools/vscecli.md page of the official website

### ISSUE THREAD

**Issue by bbenoist** [Microsoft/vscode-docs#69]
Hi,

The [`docs/tools/vscecli.md`](https://github.com/Microsoft/vscode-docs/blob/master/docs/tools/vscecli.md) file does not seems to be rendered correctly on the official website: https://code.visualstudio.com/docs/tools/vscecli

The `<publisher>` parts of the `vsce create-publisher <publisher>` and `vsce login <publisher>` commands are missing.

From what I've understood, `<publisher>` seems to be interpreted as an HTML tag during the conversion from Markdown.

Here is the HTML output I have with Chrome:
```
<code>vsce create-publisher <publisher>
</publisher></code>
```

**Comment by gregvanl** [comment]
Thanks for spotting the issue.  I've changed it from <publisher> to (publisher name).  I think people will get the idea. 
vsce create-publisher (publisher name)
We're in the process of updating our code.visualstudio.com portal tooling so you won't see this on the live site for a couple of days.
