### ISSUE TITLE
Copilot top level section in docs

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#6916]
* Overview (talk about what it is about, how can people use it, drive them to acquisition)
* Best Practices (when to use regular Copilot, some minor customizations, how to use side bar, when to use inline, generate commit message, generate PR titles, )
* Advanced (/docs, /fix, references, etc)
* Extensibility docs ( @isidorn can drive this)

![image](https://github.com/microsoft/vscode-docs/assets/1926584/7eedd3f7-9a80-4bac-b624-31f47114033d)

**Comment by starball5** [comment]
Is https://code.visualstudio.com/docs/editor/github-copilot#_generate-git-commit-messages up to date? It's still showing the sparkle button, but I don't see the latest GitHub Copilot extension using the `scm/inputbox` menu contribution point anymore...

**Comment by isidorn** [comment]
@starball5 yes, I believe the docs are still up to the date. Though I do not think it is a menu anymore, it is propose API now. So the implementation changed, but the looks (reflected in the docs) are the same.
