### ISSUE TITLE
Copilot extensibility docs

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#6917]
We need good docs to point extension authors for Copilot extensibility.

@egamma had feedback that he was missing  documentation/samples on the different progress kinds (content, task, tree), which is a key part of the UI.
Also we should document some recommendation on creating good prompts.

@jrieken @roblourens  let me know if you think it is too early to start on the docs in January.

**Comment by roblourens** [comment]
I can try to have all the kinds represented in the chat agent sample at least. I suppose we will need an "Extension Guide" at some point

**Comment by isidorn** [comment]
Tackled via https://github.com/microsoft/vscode-docs/pull/7041
