### ISSUE TITLE
Update the "Debugger for Chrome" screenshot in "Developing in WSL"

### ISSUE THREAD

**Issue by captainbrosset** [microsoft/vscode-docs#6972]
On the **Developing in WSL** doc, there's a section about managing extensions: https://code.visualstudio.com/docs/remote/wsl#_managing-extensions

In this section, there's a screenshot to show how local and wsl extensions look in the Extensions view.

Unfortunately, the local extension screenshot is this one:

![image](https://github.com/microsoft/vscode-docs/assets/1152698/617f5f83-0827-4dbe-b871-8bff739462d5)

url: https://code.visualstudio.com/assets/docs/remote/wsl/wsl-local-installed-extensions.png

The problem with this is that the **Debugger for Chrome** extension is now deprecated.

Can you please update the screenshot to show something else.

**Comment by ntrogh** [comment]
Thanks! @captainbrosset

**Comment by captainbrosset** [comment]
I opened PR #6992 to renew the screenshot.
