### ISSUE TITLE
Visual Studio Code problem

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-docs#6978]
HI! I have problems with processing the VS Code. I have problems specifically in the MinGW-w64 part. I hope you could help me. Thank You!

![420051102_907788140819960_1599514097316574096_n](https://github.com/microsoft/vscode-docs/assets/157575071/89f401b9-81da-475c-b09b-2af8b2f9b23d)

**Comment by ntrogh** [comment]
@rnjl Thanks for reaching out. From your screenshot it seems that you're entering a non-numerical input value.

**Comment by AlexandraKemperMS** [comment]
Hi @rnjl it is asking you to select what parts of the toolchain you want to install. Often, the default that installs all of them is the right one, where you can just press enter. If you want a specific one, just write that number.

**Comment by dragon7307** [comment]
Could you state what you are actually trying to achieve?

**Comment by Colengms** [comment]
@AlexandraKemperMS I think the user is pointing out something potentially confusing about [these docs](https://code.visualstudio.com/docs/languages/cpp#_set-up-your-c-environment).  The instruction to "press Enter" is mentioned before the list of options are displayed.  Immediately after that image is the instruction to "Enter Y when prompted whether to proceed with the installation.".  It might be clearer to adopt the approach of always showing an image immediately before the instructions for what to do in that context.

So, maybe change step # 5 to something like:

```
A list of available packages will be displayed:
<image>
Accept the default packages in the toolchain group by pressing Enter.
```
