### ISSUE TITLE
accessiblity tab trapping keyboard shortcut

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docs#699]
https://code.visualstudio.com/Docs/editor/accessibility#_tab-trapping

The docs say Ctrl+M to toggle tab trapping, but the shortcut is Ctrl+Shift+M (on Mac at least).

**Comment by chrisdias** [comment]
also, the screen capture at https://code.visualstudio.com/Docs/editor/accessibility#_accessibility-help shows Control+M, but in the current builds it shows Ctrl+Shift+M.

![image](https://cloud.githubusercontent.com/assets/1487073/20921313/c605950c-bba3-11e6-8d0d-6b4289cde86e.png)

**Comment by gregvanl** [comment]
Ctrl+M is for Windows and Linux, Ctrl+Shift+M for macOS.
Updated the topic text to use platform specific keyboard mapping.
Leaving the screen shot as accurate for Windows and Linux.
