### ISSUE TITLE
Long string in table cell is truncated on doc website

### ISSUE THREAD

**Issue by MinliangLin** [microsoft/vscode-docs#7009]
Hello,

The `Notes` cell of https://github.com/microsoft/vscode-docs/blob/026a711ae7591018a1d94fff7fde0fbfd4197793/docs/remote/linux.md?plain=1#L48 is truncated when it is rendered on the [document webiste](https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites) 

As highlighted in in the below figure:

<img width="1251" alt="image" src="https://github.com/microsoft/vscode-docs/assets/62332477/36d29d47-11af-45a4-a746-b56ecc1fcea0">

```[tasklist]
### Tasks
```

**Comment by muzimuzhi** [comment]
Should have been resolved by #7007.

The webpage screenshot corresponds to the version of `vscode-docs/docs/remote/linux.md` prior to the fix, and the code snippet corresponds to the version with the fix. I think we just need to wait for the next deployment of this repo.

**Comment by ntrogh** [comment]
@MinliangLin Thanks for raising this. As correctly pointed out by @muzimuzhi. this should be fixed. We should be publishing the updates later today. Keep your feedback coming!
