### ISSUE TITLE
Remote Extension drops supports for RHEL7

### ISSUE THREAD

**Issue by shivampotdar** [microsoft/vscode-docs#7011]
Hi 

The latest VSCode update v1.86 (Jan 2024) seems to have dropped support for older Linux distributions like RHEL7. 
It is although concerning that this warning is not mentioned in the VSCode or remote extension release logs (https://code.visualstudio.com/updates/v1_86, remote-release-notes/v1_86.md)
I see this issue has been mentioned here - https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions but no one would reach here unless they actually update VSCode and then realise that support is dropped. 

I use VSCode remote in a corporate environment where I cannot control the remote host OS version. Warning users about such a major change is important!

**Comment by ntrogh** [comment]
@shivampotdar Appreciate you reaching out. 
Our team has a conversation going on in the VS Code repo (https://github.com/microsoft/vscode/issues/203375). We will provide updates there in the next couple of days and will also be documenting this on our website.

**Comment by ntrogh** [comment]
Closing this issue as the recovery release that allows connections to an OS that is not supported by VS Code was released on Thursday (8 Feb).
