### ISSUE TITLE
Update Markdown Documentation

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-docs#7015]
Hi,

can you please add a section mentioning that VS Code renders math expressions using KaTeX.

https://github.com/microsoft/vscode/tree/main/extensions/markdown-math

The extension is bundled with VS Code, but there is no way to know it until you write some math symbol and see that is is displayed in the Preview.

Also, there is a new feature in the latest release, can you please include info about it as well?

https://code.visualstudio.com/updates/v1_86#_paste-a-url-to-automatically-create-a-markdown-link

Thanks!

**Comment by ntrogh** [comment]
@aedwnr Thanks for bringing this up. We'll include this in the docs.

**Comment by ntrogh** [comment]
@iainelder Yes! It's indeed a great feature for technical writing. I'll update the core docs accordingly in the April sprint, so it shows up there.

**Comment by iainelder** [comment]
@ntrogh thanks for the docs refresh.

When does the change go live?

**Comment by ntrogh** [comment]
@iainelder will trigger a deploy later today. Thanks for your interest.

**Comment by iainelder** [comment]
I see it now. Thanks!
