### ISSUE TITLE
1.86 release notes scm.inputMaxLineCount

### ISSUE THREAD

**Issue by starball5** [microsoft/vscode-docs#7018]
> The setting that controls the maximum size of the commit input field has been renamed from scm.inputMaxLines to scm.inputMinLineCount so that it matches the naming convention of similar settings.

Pretty sure `scm.inputMinLineCount` should say `scm.inputMaxLineCount` there :P

**Comment by ntrogh** [comment]
@starball5 thanks for raising this and it should indeed say `scm.inputMaxLineCount`! The release have been updated in the meantime.
