### ISSUE TITLE
Files not downloading

### ISSUE THREAD

**Issue by CG8050** [microsoft/vscode-docs#7021]
After doing everything mentioned, Nothing happend all the 3 version gcc, g++, and gdb were not installed(maybe).
whenever in cmd or powershell, After Installing, I type gcc --version or g++ --version or gdb -- version it shows:
 The term 'g++' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again. (this in powersehell)

**Comment by ntrogh** [comment]
@CG8050 checking in whether this issue is still relevant?
