### ISSUE TITLE
scrapy issues

### ISSUE THREAD

**Issue by Shawag3k** [microsoft/vscode-docs#7025]
how can i did inputs in scrapys - python?? (i don't know how to dowload the archives too)
i'm new in scraping haha, and I watch some videos about it to learn.
in my project i have to input some informations and dowload the form to my computer.
but no one teatch me how can i input informations to fill the form.
(sorry for the bad english)

**Comment by kenshanta** [comment]
Seems like your issue is related to Scrapy/Python rather than vscode-docs itself.
I suggest you close the issue

**Comment by ntrogh** [comment]
Closing this issue as it's not related to VS Code docs.
