### ISSUE TITLE
Intro video not playing for "Code Editing" tutorial

### ISSUE THREAD

**Issue by jamespostsil** [microsoft/vscode-docs#7026]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Go to https://code.visualstudio.com/docs/introvideos/codeediting
2. The embedded video gives an error and won't play:

![Snag_17cf544](https://github.com/microsoft/vscode/assets/106943065/4087ef83-7529-4be6-abde-f16be4cb70fa)

**Comment by ntrogh** [comment]
@jamespostsil Are you still getting the problem of the video not playing?

**Comment by jamespostsil** [comment]
They are available now. Thank you for checking!

--

*James Post*



*Language Technology Consultant*

SIL International <http://www.sil.org/>
