### ISSUE TITLE
What exactly does that mean? "Loading 100 small files is much slower than loading one large file" 

### ISSUE THREAD

**Issue by zalenskiSofteq** [microsoft/vscode-docs#7035]
When I built my vsc extension, I got a message.

> "This extension consists of N files, of which M are JavaScript files. For performance reasons, you should bind your extension, you should bundle your extension: https://aka.ms/vscode-bundle-extension"

In this documentation, I read a line:

> Loading 100 small files is much slower than loading one large file.

But what exactly does that mean? Memory loading, or loading for cold run, or what?

**Comment by ntrogh** [comment]
@zalenskiSofteq The extension host needs to load the extension into memory when it's activated. There's an overhead involved with opening a file, irrespective of the size of the file. So if you have one large file, you have this overhead only once, whereas with a 100 files (for example), you'd multiply this overhead, adding to the time to load your extension into memory.

**Comment by zalenskiSofteq** [comment]
@ntrogh  Thank you for your reply!
We are running front end and back end in our plugin. Backend is an express server  with a bunch of dependencies (including ones with binary files)
1. Does the plugin load all (front and back) files into memory?
2. Is there a way to ignore loading some subfolder where back end is located?

**Comment by ntrogh** [comment]
@zalenskiSofteq To clarify, your project contains both frontend and backend code but the extension only uses the frontend part. The backend part is deployed separately on some backend server?

You can exclude files from being included in the extension by using a `.vscodeignore` file. Details [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#using-.vscodeignore).

**Comment by ntrogh** [comment]
@zalenskiSofteq Apologies for the delay. When done correctly, the server part is only started with a delay (when a webview is opened, and not eagerly or during startup). In that case, loading the files doesn't slow down the extension startup.
It's best to bundle all parts (server and client), but skipping the server component would be less problematic because of the abovementioned.
I added an issue #7124 to add documentation that describes the extension architecture.

**Comment by ntrogh** [comment]
Closing this issue. Feel free to reopen if you have any follow-up questions.

**Comment by Abn7out** [comment]
{
  "scripts": {
    "vscode:prepublish": "npm run esbuild-base -- --minify",
    "esbuild-base": "esbuild ./src/extension.ts --bundle --outfile=dist/extension.js --external:vscode --format=cjs --platform=node",
    "esbuild": "npm run esbuild-base -- --sourcemap",
    "esbuild-watch": "npm run esbuild-base -- --sourcemap --watch",
    "test-compile": "tsc -p ./"
  }
}
