### ISSUE TITLE
Data Wrangler Doc Placeholder

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-docs#7047]
Using this issue to add screenshots for the upcoming Data Wrangler extension documentation. This is not a real issue.

**Comment by jmew** [comment]
<img width="1132" alt="Screenshot 2024-02-22 at 11 22 55 AM" src="https://github.com/microsoft/vscode-docs/assets/15910920/a9041346-5af7-4ec1-b7c5-b643caaad801">

**Comment by jmew** [comment]
![Screenshot 2024-02-22 at 2 35 38 PM](https://github.com/microsoft/vscode-docs/assets/15910920/b36fa8ca-01d7-4335-921f-89ba39884576)

**Comment by jmew** [comment]
![Screenshot 2024-02-22 at 2 46 56 PM](https://github.com/microsoft/vscode-docs/assets/15910920/450de035-aeb6-4e05-87cc-60ea6ac3a586)

**Comment by jmew** [comment]
![Screenshot 2024-02-23 at 9 40 09 AM](https://github.com/microsoft/vscode-docs/assets/15910920/2d37b807-8e55-4233-aa47-1706af223950)

**Comment by jmew** [comment]
<img width="380" alt="Picture1" src="https://github.com/microsoft/vscode-docs/assets/15910920/92bffc97-da96-4ed1-aac1-97e852dd52f2">

**Comment by jmew** [comment]
![Feb-23-2024 10-02-24](https://github.com/microsoft/vscode-docs/assets/15910920/074cbe94-dcbe-48ac-8c21-5e8ec1337503)

**Comment by jmew** [comment]
![Screenshot 2024-02-23 at 11 09 27 AM](https://github.com/microsoft/vscode-docs/assets/15910920/53273480-8544-408a-be96-638ca073b6cd)

**Comment by jmew** [comment]
![Screenshot 2024-02-23 at 11 53 41 AM](https://github.com/microsoft/vscode-docs/assets/15910920/09ceca10-e4c4-48e3-823f-ff03754a5d6f)

**Comment by jmew** [comment]
![Screenshot 2024-02-23 at 12 46 02 PM](https://github.com/microsoft/vscode-docs/assets/15910920/5762375c-d072-4352-9c48-e834a3562880)

**Comment by jmew** [comment]
<img width="1132" alt="Screenshot 2024-02-22 at 11 22 55 AM" src="https://github.com/microsoft/vscode-docs/assets/15910920/722e227e-776c-4e75-ae2c-089fc3871459">

**Comment by jmew** [comment]
![Screenshot 2024-02-23 at 12 54 10 PM](https://github.com/microsoft/vscode-docs/assets/15910920/52106028-bedc-4bfe-93fe-de889f94277d)

**Comment by jmew** [comment]
![Feb-23-2024 13-02-45](https://github.com/microsoft/vscode-docs/assets/15910920/468b82fe-bf78-40a8-ab60-860b2ad4ce53)

**Comment by jmew** [comment]
![update previous step](https://github.com/microsoft/vscode-docs/assets/15910920/e87a13bc-f9dc-4653-867e-8036f9e6cd1f)

**Comment by jmew** [comment]
![go to column](https://github.com/microsoft/vscode-docs/assets/15910920/3835c239-ddc9-496b-876c-c8615476d7db)

**Comment by jmew** [comment]
![Screenshot 2024-02-23 at 1 11 36 PM](https://github.com/microsoft/vscode-docs/assets/15910920/7e39febb-d9d8-46b2-a95f-329145a199a1)

**Comment by jmew** [comment]
![Full DW loop](https://github.com/microsoft/vscode-docs/assets/15910920/1a6d8fd1-6454-4289-b8c4-fe84050ae981)

**Comment by jmew** [comment]
![Screenshot 2024-02-28 at 5 18 42 PM](https://github.com/microsoft/vscode-docs/assets/15910920/3d971723-d57a-4dd6-8bb9-6200777b3573)
![Screenshot 2024-02-28 at 5 18 37 PM](https://github.com/microsoft/vscode-docs/assets/15910920/dd7b4263-492b-4823-9ec9-0381c3b9a4bf)

**Comment by ntrogh** [comment]
@jmew I think we can close this issue as the docs are published?
