### ISSUE TITLE
Incorrect link in IntelliSense Features

### ISSUE THREAD

**Issue by pierredewilde** [Microsoft/vscode-docs#705]
In `IntelliSense Features` page, See `Customize IntelliSense below` is incorrect:

[https://code.visualstudio.com/docs/editor/intellisense#_customize-intellisense](https://code.visualstudio.com/docs/editor/intellisense#_customize-intellisense)

The correct URL is:

[https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense)

Moreover, `Customize IntelliSense below` should be renamed to `Customizing IntelliSense` below.

**Comment by gregvanl** [comment]
Thanks!
