### ISSUE TITLE
The esbuild script doesn't match the package.json and other docs

### ISSUE THREAD

**Issue by yanxiaodi** [microsoft/vscode-docs#7052]
This doc [Bundling Extensions](https://code.visualstudio.com/api/working-with-extensions/bundling-extension#run-esbuild) shows an example of esbuild configuration. However, it uses `out/main.js` for the `--outfile` parameter. This may cause confusion because the other docs mainly uses `dist/extension.js`.

I also tried to create a new project using the latest generator. It seems that the package.json uses "main": "./out/extension.js", by default, instead of dist/extension.js. This may cause more issues due to discrepancies.

It would be great to use an unified bundle path in all docs. I created a PR here: #7051 . Thanks.

**Comment by ntrogh** [comment]
Thanks for raising and fixing this, @yanxiaodi.
Fixed with #7051
