### ISSUE TITLE
Debugging docs use the term 'solidus' for slash

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-docs#707]
https://github.com/Microsoft/vscode-docs/blame/master/docs/editor/debugging.md#L116

I've never heard this before and had to look it up. I think it would be more clear to say something like "without a trailing slash".

**Comment by gregvanl** [comment]
I was confused by "solidus" as well. This is fixed in the vnext branch with commit https://github.com/Microsoft/vscode-docs/commit/3e868d1dc3bca3ef55c22e18beb2124474f35f2d and will be merged and published this week.
