### ISSUE TITLE
Documentation for terminal context menu item group names not available

### ISSUE THREAD

**Issue by Pranith12250** [microsoft/vscode-docs#7088]
I was recently trying to develop an extension that shows a context menu item in the terminal. So, for this, I added the following in the package.json file as per [API docs here](https://code.visualstudio.com/api/references/contribution-points#contributes.menus):
```
"menus": 
    {
      "terminal/context":
      [
        {
          "command": "myextension.solveError",
          "group":"somegroup"
        }
      ]
    }
```

with the command being:
```
"commands": 
[
      {
        "command": "myextension.solveError",
        "category": "MyExtension",
        "title": "Resolve error"
      }
]
```

However, this puts the item in a seperate group like below:
<img width="306" alt="Screenshot 2024-03-05 at 2 05 38 AM" src="https://github.com/microsoft/vscode-docs/assets/127399614/d7f3a87b-e8ef-4c07-a0a8-1234e9719c66">

To put the context menu within existing groups such as the group containing "New Terminal" and "Split Terminal", I would have to set the "group" attribute to the name of the existing groups instead of "somegroup".

I searched the docs for the names of these existing groups but could not find these names for terminal context. Editor context have these names provided in the docs at [Sorting of groups](https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups) with group names mentioned like "navigation", "1_modification" and so on but none for terminal context.

I asked about this in the [vscode-discussions repository](https://github.com/microsoft/vscode-discussions) and got the required answer from alefragnani [here](https://github.com/microsoft/vscode-discussions/discussions/1082#discussioncomment-8674446) with the names being:

```
const enum ContextMenuGroup {
	Create = '1_create',
	Edit = '2_edit',
	Clear = '3_clear',
	Kill = '4_kill',
	Config = '5_config'
}
```

So, it would be nice if these names were included in the API docs as well so that other extension authors can find the information easily.

**Comment by Tyriar** [comment]
Thanks for the issue, I didn't know these were documented. I've made an issue I'll do this month to polish the names before making them public. So hold off on the final names until v1.88 drops

**Comment by Tyriar** [comment]
I just merged in the docs so you can see the final groups in https://github.com/microsoft/vscode-docs/pull/7154, these were changed a little so you'll need to wait until v1.88 releases to use them.
