### ISSUE TITLE
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <title>Barbearia Alura</title>
        <link rel="stylesheet" href="style.css">
    </head>

### ISSUE THREAD

**Issue by musilva10** [microsoft/vscode-docs#7089]
<body>
        <h1 style="text-align: center">Sobre a Barbearia Alura</h1>

        <p>Localizada no coração da cidade a <strong>Barbearia Alura</strong> traz para o mercado o que há de melhor para o seu cabelo e barba.
        Fundada em 2019, a Barbearia Alura já é destaque na cidade e conquista novos clientes a cada dia.</p>

        <p style="font-size: 20px"><em>Nossa missão é: <strong>"Proporcionar auto-estima e qualidade de vida aos clientes"</strong>.</em></p>

        <p>Oferecemos profissionais experientes e antenados às mudanças no mundo da moda.
        O atendimento possui padrão de excelência e agilidade, garantindo qualidade e satisfação dos nossos clientes.</p>
    </body>
</html>

**Comment by wenpez-Motdaw-buvcu0** [comment]
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Plataforma de Roleta</title>
  <style>
    body { font-family: Arial, sans-serif; margin:0; padding:20px; }
    .hidden { display: none; }
    #loginForm, #roletaPage { max-width: 320px; margin: auto; }
    input, button { width: 100%; padding: 10px; margin: 6px 0; font-size: 16px; }
    button { cursor: pointer; background: #4CAF50; color: #fff; border: none; border-radius:4px; }
    canvas { display: block; margin: auto; border:4px solid #444; border-radius:50%; }
    #seta { text-align: center; font-size: 40px; margin-top: -10px; }
    #resultado, #saldo { text-align: center; margin-top: 12px; font-weight: bold;}
  </style>
</head>
<body>

<div id="loginForm">
  <h2>Login / Cadastro</h2>
  <input type="email" id="email" placeholder="Seu e‑mail" required>
  <input type="password" id="senha" placeholder="Sua senha" required>
  <button id="btnLogin">Entrar ou Cadastrar</button>
  <p id="msgLogin" style="color:red;"></p>
</div>

<div id="roletaPage" class="hidden">
  <h2>Bem-vindo, <span id="userEmail"></span></h2>
  <p id="saldo">Você tem <span id="giros">3</span> giros.</p>
  <div id="seta">🔻</div>
  <canvas id="roleta" width="300" height="300"></canvas>
  <button id="btnGirar">Girar Roleta 🎯</button>
  <div id="resultado"></div>
  <button id="btnLogout" style="background:#e74c3c;">Sair</button>
</div>

<script>
  const premios = ['R$100', 'Tente de novo', 'R$50', 'Cupom', 'R$10', 'Nada'];
  const cores = ['#FF5733','#33C1FF','#75FF33','#FFD433','#B833FF','#FF33A6'];
  const canvas = document.getElementById('roleta'), ctx = canvas.getContext('2d');
  const tamanho = 360/premios.length;
  let anguloAtual = 0, girando = false;

  function desenhar() {
    premios.forEach((p, i) => {
      const start = (i*tamanho)*Math.PI/180, end = ((i+1)*tamanho)*Math.PI/180;
      ctx.beginPath();
      ctx.moveTo(150,150);
      ctx.arc(150,150,150,start,end);
      ctx.fillStyle = cores[i];
      ctx.fill(); ctx.stroke();
      ctx.save();
      ctx.translate(150,150);
      ctx.rotate((start+end)/2);
      ctx.textAlign = 'right'; ctx.fillStyle='#000';
      ctx.font='bold 14px Arial'; ctx.fillText(p,140,10);
      ctx.restore();
    });
  }
  desenhar();

  // Login/logout
  const loginForm = document.getElementById('loginForm'), roletaPage = document.getElementById('roletaPage');
  const btnLogin = document.getElementById('btnLogin'), msgLogin = document.getElementById('msgLogin');
  const emailIn = document.getElementById('email'), senhaIn = document.getElementById('senha');
  const userEmail = document.getElementById('userEmail'), girosEl = document.getElementById('giros');
  const saldoGiros = 3;

  btnLogin.onclick = () => {
    const email = emailIn.value.trim(), senha = senhaIn.value;
    if(!email || !senha) { msgLogin.textContent = 'Preencha e‑mail e senha.'; return; }
    let user = JSON.parse(localStorage.getItem(email));
    if(user) {
      if(user.senha !== senha) { msgLogin.textContent = 'Senha incorreta.'; return;}
    } else {
      user = { senha, giros: saldoGiros, historico: [] };
      localStorage.setItem(email, JSON.stringify(user));
    }
    localStorage.setItem('logado', email);
    showRoleta(email);
  };

  // Logout
  document.getElementById('btnLogout').onclick = () => {
    localStorage.removeItem('logado');
    roletaPage.classList.add('hidden');
    loginForm.classList.remove('hidden');
    emailIn.value=''; senhaIn.value='';
  };

  // Mostrar roleta
  function showRoleta(email) {
    loginForm.classList.add('hidden');
    roletaPage.classList.remove('hidden');
    userEmail.textContent = email;
    const user = JSON.parse(localStorage.getItem(email));
    girosEl.textContent = user.giros;
    document.getElementById('resultado').textContent = '';
  }

  // Se já estiver logado
  window.onload = () => {
    const log = localStorage.getItem('logado');
    if(log) showRoleta(log);
  };

  // Girar roleta
  document.getElementById('btnGirar').onclick = () => {
    const email = localStorage.getItem('logado');
    let user = JSON.parse(localStorage.getItem(email));
    if(user.giros < 1) { alert('Sem giros!'); return; }
    if(girando) return;
    girando = true;
    const idx = Math.floor(Math.random()*premios.length);
    const extra = 360*5 + (360 - idx*tamanho - tamanho/2);
    anguloAtual += extra;
    canvas.style.transition = 'transform 4s ease-out';
    canvas.style.transform = `rotate(${anguloAtual}deg)`;
    setTimeout(() => {
      const premio = premios[idx];
      document.getElementById('resultado').textContent = `🎉 Você ganhou: ${premio}`;
      user.giros--;
      user.historico.push({ data: new Date(), premio });
      localStorage.setItem(email, JSON.stringify(user));
      girosEl.textContent = user.giros;
      girando = false;
      canvas.style.transition = ''; // reset
    }, 4000);
  };
</script>

</body>
</html>

**Comment by Gabriel0728** [comment]
<!DOCTYPE html><html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <title>Bot de Treino - Bacará</title>
  <style>
    body { font-family: Arial, sans-serif; background: #f0f0f0; padding: 20px; }
    .container { max-width: 500px; margin: auto; background: white; padding: 20px; border-radius: 10px; }
    h1 { text-align: center; }
    button { margin: 5px; padding: 10px 20px; font-size: 16px; }
    #log { margin-top: 20px; height: 200px; overflow-y: scroll; background: #f9f9f9; padding: 10px; border: 1px solid #ccc; }
    .result { font-weight: bold; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Treino de Bacará</h1>
    <p>Banca: R$ <span id="bank">30.00</span></p>
    <input type="number" id="bet" placeholder="Valor da aposta" value="2" min="1" />
    <div>
      <button onclick="play('Player')">Player</button>
      <button onclick="play('Banker')">Banker</button>
      <button onclick="play('Tie')">Tie</button>
    </div>
    <div id="log"></div>
  </div>  <script>
    let bank = 30.00;

    function play(choice) {
      const bet = parseFloat(document.getElementById('bet').value);
      if (bet > bank || bet <= 0) {
        alert('Aposta inválida.');
        return;
      }

      const options = ['Player', 'Banker', 'Tie'];
      const result = options[Math.floor(Math.random() * 3)];
      let gain = 0;

      if (choice === result) {
        gain = result === 'Tie' ? bet * 8 : bet;
      } else {
        gain = -bet;
      }

      bank += gain;
      document.getElementById('bank').innerText = bank.toFixed(2);

      const log = document.getElementById('log');
      const entry = document.createElement('div');
      entry.innerHTML = `Apostou em <b>${choice}</b>. Resultado: <span class="result">${result}</span>. ${gain >= 0 ? 'Ganhou' : 'Perdeu'} R$ ${Math.abs(gain).toFixed(2)}`;
      log.prepend(entry);
    }
  </script></body>
</html>
