### ISSUE TITLE
Download page should say we support MacOS >= 10.9

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#711]
Relevant discussion https://github.com/Microsoft/vscode/issues/17044

From @joaomoreno 

> We should update the download page to say >=10.9, not 10.X.

**Comment by gregvanl** [comment]
@waderyan This text is hard-coded in vscode-website on DownloadBtn.js and alt-downloads.handlebars. Do you want to take this issue?

**Comment by waderyan** [comment]
Yes I can pick it up

**Comment by gregvanl** [comment]
Updated in vscode-website https://github.com/Microsoft/vscode-website/commit/abcaf96d4ea86704290c6ea00493c250d2be8d19
