### ISSUE TITLE
Missing video file    404

### ISSUE THREAD

**Issue by missile-xuan** [microsoft/vscode-docs#7128]
https://code.visualstudio.com/api/get-started/your-first-extension

https://code.visualstudio.com/api/get-started/your-first-extension/launch.mp4
https://code.visualstudio.com/api/get-started/your-first-extension/reload.mp4
https://code.visualstudio.com/api/get-started/your-first-extension/debug.mp4
![image](https://github.com/microsoft/vscode-docs/assets/38873815/c90ee4ba-c843-4cd5-86e0-953464aaa8be)
![image](https://github.com/microsoft/vscode-docs/assets/38873815/76b84f24-1928-43c2-a145-2f74640a8e7e)

**Comment by ntrogh** [comment]
Thanks for reporting this @missile-xuan - a fix is underway 🔨
