### ISSUE TITLE
why gdb --version look like this?

### ISSUE THREAD

**Issue by congcuon2k5** [microsoft/vscode-docs#7149]
C:\Users\PC>gdb --version
GNU gdb (GDB) 14.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by ntrogh** [comment]
This is the standard version information for GDB. You might check the [GDB project](https://sourceware.org/gdb/) for more information about this or to report issues.
