### ISSUE TITLE
Add docs for terminal chat

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#7159]
https://code.visualstudio.com/docs/copilot/copilot-chat

**Comment by ntrogh** [comment]
Copilot docs updated in https://github.com/microsoft/vscode-docs/pull/7258
Still needs cross-referencing from the terminal docs.

**Comment by Tyriar** [comment]
@ntrogh where were you thinking of doing cross referencing? I'm fine with just having it described in copilot docs.

**Comment by ntrogh** [comment]
@Tyriar I suggest to add a paragraph in the [Terminal Basics](https://code.visualstudio.com/docs/terminal/basics) article to inform people that there is such a thing as terminal inline chat. For more details about Copilot, we can point them to the Copilot Chat docs: https://code.visualstudio.com/docs/copilot/copilot-chat#_terminal-inline-chat
