### ISSUE TITLE
Unclear usage of "CtrlCmd" in 1.88 release notes

### ISSUE THREAD

**Issue by JohnVeness** [microsoft/vscode-docs#7185]
In https://code.visualstudio.com/updates/v1_88#_refactor-preview-keybindings the following text just casually appears "You can now preview edits by using CtrlCmd + Enter (previously Shift + Enter)."

This is the first time I've ever heard of "CtrlCmd"! I'm assuming it means Ctrl on Windows/Linux, Cmd on macOS, but still, it's jarring to have a new piece of jargon suddenly appear without previously being defined.

"Ctrl/Cmd" might be slightly better, but I think you should stick with the long-winded "On Windows & Linux, you can use Ctrl + Enter, and on macOS it is Cmd + Enter" style.

**Comment by ntrogh** [comment]
Thanks for raising this @JohnVeness . A fix is underway!
