### ISSUE TITLE
Commands can be a new category/section for extension authoring overview

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-docs#720]
In [extension authoring overview](https://code.visualstudio.com/docs/extensions/overview#_extensions), we firstly mentioned that we can create extensions to customize VS Code without even writing code, including themes, snippets, etc. This is the easiest way to build up an extension or customization.

Then we introduced two sample extensions to users, hello world and word count, which are about creating, registering and executing a command. This is the second easiest way to customize.

While implementing https://github.com/Microsoft/vscode/issues/3776, I found that from the perspective of extension, I found that most of the commands can be implemented by leveraging existing commands in our `keybindings.json`, with some glue of `editor` and `selection`.

IMHO, we may want to add some topics about how to leverage commands, combine them and contribute to Code. Right now we have a reference page for commands https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands but most new beginners don't notice them when/before they start to write an extension. What we can add are some conceptual docs for commands.

The catch here is whether we want to encourage extension authors to do so. My suspicion is yes as that's what we did for Vim enhancement: add new commands and Vim exts leverage them. @jrieken  @alexandrudima  thoughts?

**Comment by gregvanl** [comment]
There is now a dedicated Extension Guide for Commands https://code.visualstudio.com/api/extension-guides/command.
