### ISSUE TITLE
/docs/supporting/troubleshoot-terminal-launch.md has outdated screenshot.

### ISSUE THREAD

**Issue by hidingmyname** [microsoft/vscode-docs#7204]
The screenshot in “Troubleshooting steps” section is outdated and does not reflect the current interface. The outdated screenshot is as below.
![image](https://github.com/microsoft/vscode-docs/assets/140602238/596b8247-c43a-484a-a89f-1323bd8de2ed)
This screenshot has some errors.
1. The setting ID in the image does not exist any more. In fact, if users want to change the path of the shell that the terminal uses on different platforms, they may use `terminal.integrated.profiles.{platform}` which is mentioned above this image.
2. The `Turn on Settings Sync` button may be replaced by `Backup and Sync Settings`. (The same case )

An updated screenshot should be as below.
 
![image](https://github.com/microsoft/vscode-docs/assets/140602238/dba4f530-7597-40fc-9422-c0e94737abf5)

Meanwhile, the `Turn on Settings Sync` button may be outdated in `search-for-modified-settings.png`
![image](https://github.com/microsoft/vscode-docs/assets/140602238/b1666d03-d533-44a2-b8f6-998c1947159b)

**Comment by ntrogh** [comment]
Thanks for raising this, @hidingmyname
