### ISSUE TITLE
Document that Settings Sync do not sync remote extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-docs#7221]
Document that Settings Sync do not sync remote extensions

**Comment by thernstig** [comment]
Add a note also to https://code.visualstudio.com/docs/editor/profiles about this, as well as https://code.visualstudio.com/docs/editor/extension-marketplace.

Adding it to the Profiles page is important since it goes at lengths describing how good Profiles is for extensions.

**Comment by sandy081** [comment]
Adding to Profiles page makes sense but not in marketplace page.
