### ISSUE TITLE
Main link for Jupyter Notebooks in VSCode is broken

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/vscode-docs#7230]
Following link is broken:
[Jupyter Notebooks in Visual Studio Code](https://code.visualstudio.com/learn/educators/notebooks)

**Comment by ntrogh** [comment]
@saf-itpro Thanks for reaching out. Can you provide more details about this issue, for example repro steps?

**Comment by ntrogh** [comment]
@saf-itpro Feel free to reopen this issue if you need further support.
