### ISSUE TITLE
Broken Links in Latest Release Notes

### ISSUE THREAD

**Issue by andylizf** [microsoft/vscode-docs#7246]
Hello, I've noticed that the latest release notes for Visual Studio Code (https://code.visualstudio.com/updates/v1_89) contain broken links to code.visualstudio.com, leading to 404 errors. 

For example, the link to https://code.visualstudio.com/docs/languages/markdown.md#rename-headers-and-links is incorrect. It appears the ".md" extension should be removed from the URLs.

There are several such broken links in the document, and they need to be corrected.

**Comment by ntrogh** [comment]
@andylizf thanks for raising this. On it!
