### ISSUE TITLE
Discuss AI models behind GitHub Copilot?

### ISSUE THREAD

**Issue by johnd99** [microsoft/vscode-docs#7253]
The AI models behind GitHub Copilot aren't explicitly mentioned in the Copilot section (as far as I could see).  Is this intentional?  Seems like something that would be good to discuss so the user has a better idea of what Copilot could offer.

My current understanding is that the chat feature is powered by GPT-4 and the code completions by a variant of GPT-3, but let me know if that isn't correct.

**Comment by ntrogh** [comment]
@johnd99 This one totally slipped through my triaging -  apologies for the delay.

To provide chat answers or to implement AI-powered features (e.g. commit messages or rename), there are many factors that can play a role. Amongst others, this includes the language model but also the local indexing, input from the LSP, etc. And for some functionality we might apply a compound AI approach, where we use a multi-step approach that leverages multiple language-model roundtrips, potentially using different language model versions for each step. 

All this to say that there's more that goes into getting a chat response, refactoring, or commit message generation than a request to the Copilot language model. We constantly evaluate and evolve our use of language models for each of the use cases.

**Comment by johnd99** [comment]
@ntrogh Ah so it's more nuanced than I was initially thinking. Thanks for clarifying!

**Comment by ntrogh** [comment]
Closing this issue - feel free to reopen if you have any additional questions.
