### ISSUE TITLE
Non-working (HEVC) video in 1.89 release notes

### ISSUE THREAD

**Issue by JohnVeness** [microsoft/vscode-docs#7254]
Similar to #7083, the release notes for 1.89 at https://code.visualstudio.com/updates/v1_89#_implement-all-inherited-abstract-classes-code-action contain an embedded video (https://code.visualstudio.com/assets/updates/1_89/pylance-implement-abstract-classes.mp4) encoded with HEVC which doesn't work in Firefox for example. https://caniuse.com/hevc

**Comment by ntrogh** [comment]
@JohnVeness Thanks for raising this (again). Updated our release checklist to validate this scenario.
