### ISSUE TITLE
contributes.menus doesn't mention all menu ids

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-docs#726]
from #702

we have added new menus, `editor/title/context` and something for debug of which I am unsure if @weinand has already added

**Comment by jrieken** [comment]
Actually in [`vnext`](https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/extension-points.md#contributesmenus) there is an error that `editor/title` is repeated

**Comment by weinand** [comment]
Debug has nothing official added. This is planned for the future.
