### ISSUE TITLE
contributes.snippets is a little thin

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-docs#727]
re #702 

There is little context here: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/extension-points.md#contributessnippets. Maybe we can enrich it a little with the thing we already mentioned in the dedicated snippets doc

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/614e3cdcd1138eb29b3ffd252a490b2ffd286d3e added attribute description and link to VS Code snippet syntax
