### ISSUE TITLE
Editing and Navigating C++ Code: Duplicate information  

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-docs#7279]
https://github.com/microsoft/vscode-docs/blob/a9c9c282a44f2197b35d983ecb8d2d6f438de69c/docs/cpp/cpp-ide.md?plain=1#L22-L28

As can be seen the text is repeated twice. Both in the bullet list and in the section below.

**Comment by ntrogh** [comment]
Thanks for raising this, @thernstig.
