### ISSUE TITLE
Zen mode

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#728]
Zen mode needs to be documented. Not sure under what exact section
@bpasero

**Comment by bpasero** [comment]
Be creative :)

**Comment by isidorn** [comment]
Maybe under Customisation \ Themes we could add a section zen mode.
I'll let @gregvanl decide where to put this and then I can add the content

**Comment by isidorn** [comment]
Ok I have added it under Customisation \ Themes, since all other page felt alien and I do not think zen mode deserves a brand new page.
@gregvanl feel free to move it

**Comment by jamesqo** [comment]
Can the keybindings for Zen Mode also be documented in docs/customization/keybindings.md?

**Comment by isidorn** [comment]
@jamesqo yes! Ping @gregg-miskelly @waderyan

**Comment by gregvanl** [comment]
Wrong Greg. I'll update keybindings.md.

**Comment by isidorn** [comment]
@gregvanl thanks!

**Comment by gregvanl** [comment]
Added to keybindings.md with https://github.com/Microsoft/vscode-docs/commit/5789c5a38bb68e7f8863ba61ac2511151db61fa5.
We should also update the shortcut PDFs once Brad is back from vacation.
