### ISSUE TITLE
/docs/azure/mongodb.md has outdated screenshot

### ISSUE THREAD

**Issue by hidingmyname** [microsoft/vscode-docs#7285]
The screenshot `/docs/azure/images/mongodb/attach-database-account.png` in “Connect to MongoDB” section is outdated and does not reflect the current interface. The outdated screenshot is as below.
![attach-database-account_0](https://github.com/microsoft/vscode-docs/assets/140602238/7761c62a-873d-4d43-b793-51e9755f32c8)
This page does not exist in the latest version.
The latest view after select **Add Connection** is as below.
![attach-database-account_1](https://github.com/microsoft/vscode-docs/assets/140602238/a783ac9f-4899-481b-83fd-5c59de2a75a3)
The corresponding document is outdated too and should also be updated in some aspects:
1. The connection details for the database is as below. Users should then select **Save & Connect** instead of **Connect**.
![image](https://github.com/microsoft/vscode-docs/assets/140602238/9a9c274a-5a9b-455f-8fd4-501b78b8bb37)
2. Users now can also enter a connection string, click the "connect" button as below
![image](https://github.com/microsoft/vscode-docs/assets/140602238/278f2d18-fc8e-49a6-abd5-2e38d3de3581) 
and paste the connection string as below
![image](https://github.com/microsoft/vscode-docs/assets/140602238/c3c1c989-4792-44f3-81ce-4fdc3b94ebf1)

**Comment by ntrogh** [comment]
@hidingmyname thanks for raising this. An update is incoming!
