### ISSUE TITLE
Debug docathon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#729]
This items covers what is missing in our debug docs and is covered in our release notes since June. I did not put features which are self-explanatory and do not require docs (e.g. variable paging). 

General:
- [x] Adding new launch configurations
- [x] Multi target debugging 
- [x] Suggestions in debug console input (multi line console input)
- [x] ~~[Debug settings in settings.json](http://code.visualstudio.com/updates/v1_7#_debug-settings)~~ I think this should not be mentioned as we should keep the debugger document concise, most of settings are not documented and the settings which we have are not that important to be in the spotlight
- [ ] Variable substitution should be moved one level up (duplicated in tasks and debugging) - please advise where to move this section such that no duplication occurs @gregvanl 
- [x] ${fileBasenameNoExt} is not documented

Javascript Debugging:

- [x] Introduction node/node2

Node:
- [x] [Configurable External Terminal](http://code.visualstudio.com/updates/v1_6#_configurable-external-terminal)
- [x] [Launch config supports npm](http://code.visualstudio.com/updates/v1_6#_launch-configuration-supports-npm-and-other-tools)
- [x] Just my code
- [x] Load environment variables from external file 
- [x] Restart frame
- [x] Trace options
- [x] smartStep

Node2:
- [x] Basic info

Debug Extension Authoring:
- [x] Introduction/Architecture
- [x] simplify development setup by using multi session debugging
- [x] contribution points

**Comment by roblourens** [comment]
I have PRs for skipFiles, smartStep, and node2 that I'll merge into this branch

**Comment by roblourens** [comment]
I think the docathon branch should be based off vnext instead of master, since there are some debug-related changes already in vnext. I can merge it if you agree.

**Comment by weinand** [comment]
@roblourens I just did what Greg asked us to do in the Doc-a-thon issue: "Create or update content and submit a PR against vscode-docs **master**." But please go ahead and merge.

**Comment by roblourens** [comment]
Oh, I didn't notice. I see docathon changes going into both branches though...

**Comment by roblourens** [comment]
I've included a basic section on node2 via #708, but I'm hesitant to include node2-specific features. Maybe the centralized doc should focus on info on the default node debug experience. There's a lot of stuff in the node2 readme that could go here but it might be confusing to have all node-debug and node-debug2 stuff on the same page.

**Comment by roblourens** [comment]
Greg said that vnext will be merged into master tomorrow, so my PRs that already went in there can be merged into our branch.

**Comment by isidorn** [comment]
I agree that having one giant document with everything can be too much for new users. We should try to keep the main document concise and have subsections.

**Comment by weinand** [comment]
@roblourens @isidorn in July I've created these restructuring suggestions:
- https://github.com/Microsoft/vscode-docs/issues/448
- https://github.com/Microsoft/vscode-docs/issues/450

**Comment by roblourens** [comment]
I definitely agree with breaking out the "Node debugging" section, and I created a dupe issue yesterday. It seems like we're stretching the 'editor' section though, so I don't know where it should go.

**Comment by weinand** [comment]
@roblourens pls see https://github.com/Microsoft/vscode-docs/issues/447

**Comment by isidorn** [comment]
And https://github.com/Microsoft/vscode-docs/issues/406

**Comment by roblourens** [comment]
Is anyone working on restructuring it? Not sure what the conclusion from those issues is.

**Comment by gregvanl** [comment]
I can work on separating and moving the documents. We could create a new Debugging node in the TOC (between Editor and Customization?) and split debugging.dm into 2-3 topics (Debugging in VS Code, Node.js Debugging, Debug Extensions??). I can take care of creating the pages, stitching into the TOC, adding redirects, etc). For the doc-a-thon, let's just get the content into the appropriate sections in the existing debugging.md.

**Comment by weinand** [comment]
I'm working on this. My Goal is to check off all checkboxes from above and close this issue this week.
(Today I could only spend 2 hours on this because I some personal appointments and we had the team event in the afternoon).

**Comment by weinand** [comment]
@gregvanl I'm done with all planned edits. The final and up-to-date version of the debugging doc lives in the `dec-docathon-debug` branch (for which I will create a PR). 
I've noticed that you already merged some other PRs into master of `debugging.md` which where missing in dec-docathon-debug.
But I've verified that the contents of those PRs is now in the `dec-docathon-debug` branch too. So you do not have to merge `debugging.md` with master but you can just replace the existing.

**Comment by gregvanl** [comment]
Merged the dec-docathon-debug PR and split Node.js Debugging into it's own topic.
Next week I'll talk to Wade and Sean about creating a new Debugging node and moving those topics there.

**Comment by gregvanl** [comment]
@weinand @isidorn Holding on moving the debugging topics to a new DEBUGGING node. Wade and Sean feel strongly on reviewing the entire TOC before we make any incremental changes.

**Comment by gregvanl** [comment]
Any TOC changes are being deferred until February per Wade's website planning [roadmap](https://microsoft.sharepoint.com/teams/DD_OTP/_layouts/OneNote.aspx?id=%2fteams%2fDD_OTP%2fDocuments%2fTicino%2fNotebooks%2fVSCode&wd=target%28Website.one%7c9B03629A-77AD-4EC7-AEC4-12B581EE2864%2fQ1-Q2%20Roadmap%7cA8D71DB5-8A6E-6B48-A78C-71FC02AEAC6C%2f%29
onenote:https://microsoft.sharepoint.com/teams/DD_OTP/Documents/Ticino/Notebooks/VSCode/Website.one#Q1-Q2%20Roadmap&section-id={9B03629A-77AD-4EC7-AEC4-12B581EE2864}&page-id={A8D71DB5-8A6E-6B48-A78C-71FC02AEAC6C}&end)
Sean has also started a TOC principles [page](https://microsoft.sharepoint.com/teams/DD_OTP/_layouts/OneNote.aspx?id=%2fteams%2fDD_OTP%2fDocuments%2fTicino%2fNotebooks%2fVSCode&wd=target%28Docs.one%7cD73DDD10-4D72-43B8-84F7-273807364F90%2fTOC%20Questions%20%26%20Principles%7c47E0E0A0-1352-1047-A715-E28BE5C834C9%2f%29
onenote:https://microsoft.sharepoint.com/teams/DD_OTP/Documents/Ticino/Notebooks/VSCode/Docs.one#TOC%20Questions%20%20Principles&section-id={D73DDD10-4D72-43B8-84F7-273807364F90}&page-id={47E0E0A0-1352-1047-A715-E28BE5C834C9}&end)
