### ISSUE TITLE
TypeScript Extensions section in typescript.md unclear

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-docs#730]
This section reads strange to me. Is there a screen shot missing. Shouldn't we at least list the extension that are helpful for TypeScript. Can't be so many :-).

**Comment by gregvanl** [comment]
I see the confusion. If you do Markdown preview on the topic, you won't see the Marketplace query results displayed. We show a dynamic query of the top 4 TypeScript extensions (currently TSLint, Angular 2 TypeScript snippets, Code Runner, and Angular 1 JavaScript and TypeScript snippets).
