### ISSUE TITLE
Workbench customisation: viewlets can be reordered and hidden

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#732]
We should probably mention https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_8.md#configurable-activity-bar somewhere here: https://code.visualstudio.com/docs/customization/overview

**Comment by gregvanl** [comment]
Added to new docs/getstarted/userinterface.md topic with https://github.com/Microsoft/vscode-docs/commit/21a914e7337dfa8bd5ddd425ba97692404951fa4
