### ISSUE TITLE
Typos in questions 3 and 4 in Source Control FAQ

### ISSUE THREAD

**Issue by edelare** [microsoft/vscode-docs#7324]
Impacted file: docs/sourcecontrol/faq.md
Should read "How do I", not "How to I".

**Comment by angad-singhh** [comment]
Hey @ntrogh , If this issue to contribute, I would like to take this. We only need to remove `letter: I`, then both sentence will make sense.

**Comment by ntrogh** [comment]
Hey @angad-singh feel free to create a PR to fix this. Appreciate your support!
