### ISSUE TITLE
outdated link to TypeSearch

### ISSUE THREAD

**Issue by yg-i** [microsoft/vscode-docs#7336]
at the bottom of this page (https://code.visualstudio.com/docs/editor/intellisense) 

> You can check if a type declaration file package is available for a specific library by using the TypeSearch site

Clicking on the TypeSearch link leads one to this page (https://www.typescriptlang.org/dt/search/) where it's said that:

> This page is no longer necessary.
> The npm and Yarn package registries now include type information for packages.
You can read more on: npm displays packages with bundled TypeScript declarations.

Perhaps it's time to change/remove the link?

**Comment by ntrogh** [comment]
Thanks @yg-i
