### ISSUE TITLE
Changing path variables clarity

### ISSUE THREAD

**Issue by bozofoz** [microsoft/vscode-docs#7344]
In the part about changing the path variable, there is a bit of unclarity in the text, although the video gets it right. You need to OK both the "Edit environment variable" window AND the "Environment Variables" window. It doesn't take effect until the second window is OKed.

I'm guessing this part of Windows is from the Windows 95 era.

**Comment by ntrogh** [comment]
@bozofoz can you clarify in where in the docs you 're referring to?

**Comment by angad-singhh** [comment]
Hey @ntrogh , 
I think @bozofoz is referring to the [this](https://code.visualstudio.com/docs/cpp/config-mingw#:~:text=Select%20OK%20to%20save%20the%20updated%20PATH.%20You%20will%20need%20to%20reopen%20any%20console%20windows%20for%20the%20new%20PATH%20location%20to%20be%20available) part in the docs, same can be found [here](https://code.visualstudio.com/docs/languages/cpp?source=post_page---------------------------#:~:text=Select%20OK%20to%20save%20the%20updated%20PATH.%20For%20the%20new%20PATH%20to%20be%20available%2C%20reopen%20your%20console%20windows.). 

If any change is needed, I will be happy to contribute.

**Comment by bozofoz** [comment]
You got it.
