### ISSUE TITLE
List Go with other languages in Getting Started

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-docs#737]
Doc-athon #702

List Go with the other languages in the first paragraph of the Getting Started page since that is an area where we have put work in recently. (Can't find the Overview page in the repository to submit a PR.)

**Comment by gregvanl** [comment]
This test is in the vscode-website repo. Fixed with https://github.com/Microsoft/vscode-website/commit/c96c675a8e1631c0037800ef815d183adaa463f1
