### ISSUE TITLE
g++ not reccognized

### ISSUE THREAD

**Issue by Suryadeep190** [microsoft/vscode-docs#7391]
while running a c++ code in vsc ,it shows error that the g++ is not recognized ,please check the path

**Comment by ntrogh** [comment]
@Suryadeep190 Have you checked that g++ is installed on your machine?
- Linux: https://code.visualstudio.com/docs/cpp/config-linux#_ensure-gcc-is-installed
- Windows: https://code.visualstudio.com/docs/cpp/config-mingw#_check-your-mingw-installation
- Windows + WSL: https://code.visualstudio.com/docs/cpp/config-wsl#_set-up-your-linux-environment

If you have it installed, you can also configure the path to the compiler with the **C/C++: Edit configurations (UI)** command in the Command Palette. Learn more about [C++ configurations](https://code.visualstudio.com/docs/cpp/config-linux#_cc-configurations) in our docs.

**Comment by ntrogh** [comment]
@Suryadeep190 Closing this issue. Feel free to reopen when you have follow-on questions.
