### ISSUE TITLE
docker-compose doc references non-existent file

### ISSUE THREAD

**Issue by jason-matthew** [microsoft/vscode-docs#7398]
Doc consumers are confused by a unique file reference.

Current doc ( [9c405b7350a5adbcb2d633d09b79fcadb0ee8650/docs/devcontainers/create-dev-container.md#L415](https://github.com/microsoft/vscode-docs/blame/9c405b7350a5adbcb2d633d09b79fcadb0ee8650/docs/devcontainers/create-dev-container.md#L415) ) contains a single reference to `devcontainer.extend.yml`.  Similarly named `docker-compose.extend.yml` is referenced 4x in preceding lines.

**Comment by ntrogh** [comment]
@jason-matthew Thanks for raising this.

**Comment by ntrogh** [comment]
@bamurtaugh It looks like `devcontainer.extend.yml` should actually be `.devcontainer/docker-compose.extend.yml` instead. That way, the development settings override the defaults from the `docker-compose.yml` file. Can you confirm?

**Comment by jason-matthew** [comment]
My attempts to stage a doc update has produced https://github.com/microsoft/vscode-docs/pull/7399.  

Apologies for the noise.

**Comment by ntrogh** [comment]
Thanks for creating a PR. Looks good to me, but need @bamurtaugh to review and confirm.
