### ISSUE TITLE
JavaScript Doc updates needed

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#740]
ping @egamma @mjbvz 

Some things that need updating:
- [x] `jsconfig.json` is not required anymore. We need to figure out the messaging for how to say it isn't required but still recommended. *must document when it is required*
- [x] We can take out the section about [installing typings](https://code.visualstudio.com/docs/languages/javascript#_typescript-definition-files-typings) now that we have ATA. 
- [x] We should have a section on ATA that explains reasons why intellisense may not work (for example, one user wanted IntelliSense but they hadn't created a package.json yet).
- [x] Troubleshooting IntelliSense is out of date with ATA.
- [x] Remove references to typings in Q&A. 

Some other thoughts. 
- [x] Is "Next Generation JavaScript" the right way to describe ES6, ES7, etc.? I haven't seen that vernacular in other places. 
- [x] Revisit running babel - I haven't tried this in a while... 
- [x] Formatting could use an animation. 
- [x] I should look at the common issues list (OneNote table) and add some more Q&A off of what people are running into. Its been a while since I have done that.

**Comment by egamma** [comment]
@waderyan I've updated the node.js documentation accordingly in this PR https://github.com/Microsoft/vscode-docs/pull/762
