### ISSUE TITLE
After applying Reflow "Visual studio code" page is getting 2 Scroll bars: A11y_VisualStudioCodeServices_Gettingstarted_Reflow

### ISSUE THREAD

**Issue by PrasannaPolisetty123** [microsoft/vscode-docs#7409]
## GitHub Tags:
#A11yTCS; #A11ySev3; #A11yMAS; #DesktopWeb; #ChromiumEdge; #WCAG1.4.10;#Reflow;#A11yWCAG2.1#BM_VisualStudioCodeServices_Web_July2024; #Visual Studio Code Services; #Benchmark; #Win11; #FTP; #Desktopweb.

## Environment Details: 
Application Name:  Visual Studio Code Services
URL: https://code.visualstudio.com/docs/?dv=win64user&dark-plus-v2
Microsoft Edge version 126.0.2592.68 (Official build) (64-bit)
## Pre-requisites:(Reflow)

1. Open the web page / screen of the web application that is to be tested
2. Open Chrome/Edge dev Inspect tools. Keyboard shortcut "Ctrl+Shift+I" 
3.  Ensure devtools are customized to Dock location: "undock into separate window". Minimize devtools so they are not obscuring the page.
4. Zoom the browser window of the page to be tested to 200%.
5. Adjust the browser window's height and width to the required viewport of 320px*256px. As long as devTools remain open while resizing the viewport size will be displayed in the upper right corner of the browser so the size can be verified.
### Alternatively:
1. Change the OS display settings to a resolution of 1280x1024 at 100% dpi scaling.
2. Open the web page/ screen of the web application that is to be tested.
3.  Zoom browser 400%. 
4.  Set the browser to **full screen**. Keyboard shortcut "F11" key.
5. If any browser sidebars are still visible (e.g. the Edge discover sidebar), these _must_ be closed.

## Repro steps:

1. Launch the application URL https://code.visualstudio.com/download?dark-plus-v2 and press ENTER.
2. Now Apply the Reflow configuration and observe that "visual studio code" page is getting 2 scroll bars.

**Note: Issue is repro with below URLS as well**

1. https://code.visualstudio.com/docs/python/editing?dark-plus-v2
2. https://code.visualstudio.com/docs/python/linting?dark-plus-v2
4. https://code.visualstudio.com/docs/remote/troubleshooting?dark-plus-v2
5. https://code.visualstudio.com/docs/python/debugging?dark-plus-v2
## Actual :
After applying reflow "visual studio code" page is getting 2 scroll bars.
## Expected
After applying Reflow "visual studio code" page should not get 2 scroll bars.

## User Impact
Low vision users will get impacted if the "visual studio code" page is getting 2 scroll bars.
## Attachment
![reflow](https://github.com/microsoft/vscode-docs/assets/151031203/b69d79b3-9132-4615-8f42-85c997045c2c)

![reflow 3](https://github.com/microsoft/vscode-docs/assets/151031203/3d88e317-a4a4-452c-9afd-3291f2ef0b5f)

![reflow 1](https://github.com/microsoft/vscode-docs/assets/151031203/97fb5597-59b1-4568-90f0-aa5fd7d06419)

![reflow 2](https://github.com/microsoft/vscode-docs/assets/151031203/d5b0e8b4-f0db-43c8-b536-b5b22cb20b2a)

**Comment by 12-shweta** [comment]
#Rev:shwarh;

**Comment by PrasannaPolisetty123** [comment]
@daviddossett could you please provide the environment where the issue is fixed , we will verify the bug 
As per updated Resolved Bug Process (sharepoint.com), if input is not provided by <Current Date + 5 days (f**or e.g. 3rd July 2024**)> then we'll be reactivating the bug.

**Comment by 12-shweta** [comment]
#A11yPreview;
