### ISSUE TITLE
IntelliSense needs doc feedback rollup / SEO review

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#742]
The IntelliSense page is similar to the Python doc. Its high level and meant to be a landing page to bring people in. The best route for finding what changes to make here is to look at doc feedback / GA / and do an SEO review. 

https://code.visualstudio.com/docs/editor/intellisense

**Comment by gregvanl** [comment]
PJ and Wade are doing a BrightEdge SEO investigation.
