### ISSUE TITLE
Unclear sentence in 1.91 release notes 

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#7427]
https://github.com/microsoft/vscode-docs/blob/589abb576983c920932c0926e27358b135959641/release-notes/v1_91.md?plain=1#L79

I find this confusing.

**Comment by ntrogh** [comment]
Added more details to clarify in https://github.com/microsoft/vscode-docs/commit/90992d7f45ccd6d8da0670def3037d9fb5adb33c
