### ISSUE TITLE
Links to archived repo https://aka.ms/vscode-remote/samples

### ISSUE THREAD

**Issue by joebowbeer** [microsoft/vscode-docs#7449]
vscode-docs contains several links to an [archived repo](https://github.com/microsoft/vscode-dev-containers)

Mostly in this file:

https://github.com/microsoft/vscode-docs/blob/main/remote/advancedcontainers/use-docker-kubernetes.md

All instances:

https://github.com/search?q=repo%3Amicrosoft%2Fvscode-docs+vscode-remote%2Fsamples&type=code

Can these be changed to point to https://github.com/devcontainers/features ?

Also, this link in [use-docker-kubernetes.md](https://github.com/microsoft/vscode-docs/blob/main/remote/advancedcontainers/use-docker-kubernetes.md) is broken:

https://github.com/devcontainers/features/tree/main/src/docker-from-docker

Corrected:

https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker

**Comment by ntrogh** [comment]
@bamurtaugh Can you take this up? This might involve some docs updates beyond just updating the links.

**Comment by bamurtaugh** [comment]
Thanks for looping me in! Opened https://github.com/microsoft/vscode-docs/pull/7496 to address this.
