### ISSUE TITLE
Update Profiles docs to reflect the new profiles editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#7452]
https://code.visualstudio.com/docs/editor/profiles

We now have the profiles editor which should be documented in the Profiles docs.

**Comment by sandy081** [comment]
This is still not the default in Stable and I will do it in next milestone.

**Comment by sandy081** [comment]
@ntrogh @isidorn 

I have updated the profiles doc with new profiles editor changes. Please take a look and provide feedback.

https://github.com/microsoft/vscode-docs/blob/0719a1faad1c74a12c769465531c4091722b1852/docs/editor/profiles.md

Thanks

**Comment by isidorn** [comment]
Thanks Sandeep. Nick and me will review this week.

**Comment by ntrogh** [comment]
@sandy081 Thanks for updating the documentation! I've done a review and made some, mostly minor, edits.
