### ISSUE TITLE
Dev Container Docs improvements

### ISSUE THREAD

**Issue by yaoleo34** [microsoft/vscode-docs#7458]
This feedback from a customer at EuroPython 2024, they were having trouble getting the correct information about DevContainers on the Docs page. Here is feedback received:

- What containerization "backends" are supported (Docker, Podman, nerdctl, …)
- What IDEs are supported?
- Can I use devcontainers in a regular terminal outside VSCode?
- Can developers still use their own (their host machine's) Bash/zsh/fish config inside the container? What about CLI tools they have installed on the host machine? Will VSCode use the git binary from inside the container for git operations? Etc.”

**Comment by bamurtaugh** [comment]
Hey @yaoleo34, thanks again for opening this issue!

> having trouble getting the correct information about DevContainers on the Docs page

Do you know which docs page they looked at? As I review this feedback further, we've already tried to address each of these points on our overview doc https://code.visualstudio.com/docs/devcontainers/containers (and most of it is within the first couple paragraphs).

Or if you have a moment to check out https://code.visualstudio.com/docs/devcontainers/containers yourself and let us know if any of the above customer feedback isn't actually apparent / present to you (it's always incredibly helpful to get a fresh set of eyes on these docs), that'd be an incredible help too!

**Comment by bamurtaugh** [comment]
I'm going to close out this issue for now, but @yaoleo34 or others, please do let us know if you have any other details, and we'd love to iterate together!
