### ISSUE TITLE
Home page download buttons incorrect placement on mobile

### ISSUE THREAD

**Issue by yusuf-saydullayev** [microsoft/vscode-docs#7476]
![Screenshot_2024-08-01-23-51-03-113_org mozilla firefox](https://github.com/user-attachments/assets/24d1d6d2-dd0e-46f0-b3a1-4e3170ee90b5)

**Comment by ntrogh** [comment]
@yusuf-saydullayev thanks for bringing this up. Can you provide details about the specific mobile device, OS, and browser you're experiencing this on?

**Comment by yusuf-saydullayev** [comment]
OS: Android 14
Browser: Firefox 128.0.3.
In Chrome (v127) same too.

**Comment by ntrogh** [comment]
@daviddossett seems to be a case where OS detection flags as neither Windows, Linux, or macOS and decides to show all three.

**Comment by daviddossett** [comment]
Can't seem to repro this but I did try to clean up the logic a little bit in https://github.com/microsoft/vscode-website/pull/1872

Since the default is to `display: none` and to only render buttons when they match a certain `data-os` attribute, it seems like the CSS isn't getting applied somehow.

**Comment by ntrogh** [comment]
You can repro by setting the user agent to some random text.

**Comment by daviddossett** [comment]
Thanks, that worked. I see `home win linux osx` applied as classes on `body` now. Not sure why that would be happening though. cc @rzhao271 for any other ideas
