### ISSUE TITLE
Node.js IntelliSense and Typings should use npm install @types instead of typings

### ISSUE THREAD

**Issue by memotive** [Microsoft/vscode-docs#750]
In [Node.js Applications with VS Code - IntelliSense and Typings](https://code.visualstudio.com/Docs/runtimes/nodejs#_intellisense-and-typings), the documentation still refers to 
```
typings
```
instead of recommended 
```
npm install @types/<package>
```

**Comment by gregvanl** [comment]
Node.js walkthrough was updated and shows using the Automatic Type Acquisition feature to get type declaration files.
