### ISSUE TITLE
C++ VSC installation problems "create the hello Word app" MacOS

### ISSUE THREAD

**Issue by lollo137** [microsoft/vscode-docs#7510]
when I go to enter in the terminal 
mkdir projects
cd projects
mkdir helloworld
cd helloworld
code 
it gives me an error saying "zsh: command not found: code"

**Comment by ntrogh** [comment]
@lollo137 Have you installed VS Code and made sure that the `code` executable is added to the `$PATH` environment variable? Follow the instructions here: https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

**Comment by lollo137** [comment]
> @lollo137Hai installato VS Code e verificato che l' `code`eseguibile sia stato aggiunto alla `$PATH`variabile di ambiente? Segui le istruzioni qui: https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

thanks so much I solved it

**Comment by ntrogh** [comment]
Enjoy your VS Code experience!
