### ISSUE TITLE
Vue: Guidance for recommended extensions differs from vuejs.org website

### ISSUE THREAD

**Issue by pedroresende** [microsoft/vscode-docs#7519]
I noticed that the [Vue tutorial](https://github.com/microsoft/vscode-docs/blob/main/docs/nodejs/vuejs-tutorial.md) (docs/nodejs/vuejs-tutorial.md) recommends the Volar extension whereas the [Vue website TypeScript guide](https://vuejs.org/guide/typescript/overview.html#ide-support) now recommends the Vue Official extension. It looks like the advice on the VS Code website might be outdated.

**Comment by pedroresende** [comment]
I've opened a PR to fix the mistake https://github.com/microsoft/vscode-docs/pull/7518

**Comment by pedroresende** [comment]
@gregvanl

**Comment by ntrogh** [comment]
@pedroresende Thanks for reporting this and filing a PR.
