### ISSUE TITLE
Failed page loading

### ISSUE THREAD

**Issue by chibugo95** [microsoft/vscode-docs#7533]
am trying to download C++ MSYS2 of visual code but the installer page doesn't open after i click the installing link. how do i fix this?

**Comment by ntrogh** [comment]
@chibugo95 You are able to download the installer, right? When you run the installer, can you verify that your computer meets the following requirements from [MSYS](https://www.msys2.org/):

> Installing MSYS2 requires 64 bit Windows 10 or newer.

**Comment by chibugo95** [comment]
Yes my  system is windows 10 64bits

**Comment by ntrogh** [comment]
@chibugo95 Can you try grabbing the installer directly from the MSYS website and check their [installer page](https://www.msys2.org/docs/installer/)?
