### ISSUE TITLE
Update "Embedded Programming Languages" to reflect that pull diagnostics are not planned

### ISSUE THREAD

**Issue by zachallaun** [microsoft/vscode-docs#7536]
Context: https://github.com/microsoft/vscode/issues/159911#issuecomment-2321297275

From the [Embedded Programming Languages](https://code.visualstudio.com/api/language-extensions/embedded-languages#conclusion) guide:

> Request forwarding:
> ...
> * <span>-</span> Does not yet work with diagnostics errors. The VS Code API currently does not support diagnostic providers that can 'pull' (request) diagnostics. ([Issue](https://github.com/microsoft/vscode/issues/159911)).

The phrases "Does not yet work with..." and "currently does not support" suggest that VS Code will *eventually* support diagnostic pulling, but the linked issue suggests otherwise. Docs should be updated to reflect that.

**Comment by listsarah** [comment]
See Pull Request: #7539

**Comment by ntrogh** [comment]
@zachallaun Thanks for bringing this up. 
@listsarah Appreciate you contributing the docs update!
