### ISSUE TITLE
`kb(...)` elements remain unsubstituted on API doc pages

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#7563]
https://github.com/microsoft/vscode-docs/blob/f0398fae110c473eb85a72e1d7cbb3cd46b5eec2/api/references/commands.md#L530

displays `kb(workbench.action.showCommands)` at https://code.visualstudio.com/api/references/commands#simple-commands

By comparison:

https://github.com/microsoft/vscode-docs/blob/f0398fae110c473eb85a72e1d7cbb3cd46b5eec2/docs/editor/codebasics.md#L25-L26

results in keybindings displaying at https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

**Comment by ntrogh** [comment]
@rzhao271 Can you help with this one?

**Comment by ntrogh** [comment]
@gjsjohnmurray thanks for flagging this. Problem should be fixed with the next website deployment (Monday).

Issue fixed in website code (keybinding post-processing was overwritten by settings post-processing).
