### ISSUE TITLE
C++ code runner not working

### ISSUE THREAD

**Issue by DanielRein-1** [microsoft/vscode-docs#7574]
My c++ config is "cpp": "cd $dir && g++ -std=c++17 -g-Wall -lm -o $fileNameWithoutExt && $dir$fileNameWithoutExt" when i try to run using the keyboard shortcut/ run code my terminal says unrecognized debug output level '-Wall' mean when i run c++

**Comment by ntrogh** [comment]
@DanielRein-1 It looks like there is a ` ` (whitespace) missing between `-g` and `-Wall`. Without it, the compiler treats `-Wall` as the debug output level and not as a separate command line parameter.

**Comment by ntrogh** [comment]
@DanielRein-1 Closing thiş issue as resolved, feel free to reopen if you encounter any further problems.
