### ISSUE TITLE
a spurious space in "Keyboard shortcuts for Linux" cheat sheet

### ISSUE THREAD

**Issue by partev** [microsoft/vscode-docs#7576]
there is a spurious space in front of "Ctrl+`" in the "Integrated terminal" section of Linux keyboard shortcuts here:

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf

the extra space is highlighted in the screenshot below:
![Screenshot 2024-09-11 08 59 21](https://github.com/user-attachments/assets/565ccca7-3f7e-48ed-aef8-4e7ea123f6c2)

this extra space seems to be present in [keyboard-shortcuts-linux.docx](https://github.com/microsoft/vscode-docs/blob/main/docs/customization/keyboard-shortcuts-linux.docx) and [keyboard-shortcuts-linux-vscode-dev.docx](https://github.com/microsoft/vscode-docs/blob/main/docs/customization/keyboard-shortcuts-linux-vscode-dev.docx)

if those files are used to generate the PDF file then ".docx" files need to be fixed.

**Comment by ntrogh** [comment]
@partev Well spotted! Thanks for reporting - a fix is underway.
