### ISSUE TITLE
Two keyboard shortcuts `kb(<command ID>)` in when-clause-contexts.md are not rendered

### ISSUE THREAD

**Issue by muzimuzhi** [microsoft/vscode-docs#7592]
https://code.visualstudio.com/api/references/when-clause-contexts

- https://github.com/microsoft/vscode-docs/blob/d239f68f168aad63d57202702898d623999d6649/api/references/when-clause-contexts.md?plain=1#L19
  ![image](https://github.com/user-attachments/assets/c4d1386a-4aee-4d4c-8fa2-1e509cc17aff)
- https://github.com/microsoft/vscode-docs/blob/d239f68f168aad63d57202702898d623999d6649/api/references/when-clause-contexts.md?plain=1#L336
  ![image](https://github.com/user-attachments/assets/3c5d8896-1f3a-4009-9f7e-0b7e2944e3e1)
  
Also in the second case, the command ID seems wrong. Should be `kb(workbench.action.inspectContextKeys)`.

**Comment by muzimuzhi** [comment]
Duplicate of #7563?

> Problem should be fixed with the next website deployment (Monday).
> <sub>_https://github.com/microsoft/vscode-docs/issues/7563#issuecomment-2348472281_</sub>

Will find out by Monday.

**Comment by muzimuzhi** [comment]
```md
..., you can use the **Developer: Inspect Context Keys** command from the
Command Palette (`kb(workbench.action.showCommands)`).
```

> Also in the second case, the command ID seems wrong. Should be `kb(workbench.action.inspectContextKeys)`.

Oh, the current command ID is right. It's for openning the Command Palette, not executing the "Developer: Inspect Context Keys" command.

**Comment by ntrogh** [comment]
@muzimuzhi The keybinding substitutions will be fixed later today, when we publish the website. Thanks for raising this though.

**Comment by muzimuzhi** [comment]
Confirmed it's fixed. Thanks!
