### ISSUE TITLE
Font size for tips and contents should be same

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#761]
Pls see the screenshot below, the font size for the tips contents is bigger than for the other content. Given the that tips are already emphasized by the sidebar, bold label, they do not need additional emphasis using the font size.

![image](https://cloud.githubusercontent.com/assets/172399/21222956/f27fce4a-c2c4-11e6-9891-aab1485d7557.png)

**Comment by gregvanl** [comment]
I agree that we don't need to increase the font size of Notes and Tips.
I think we're picking up the increased font-size from the default bootstrap styles for blockquotes. 
Assigning to @bgashler1 @waderyan to prioritize.

**Comment by gregvanl** [comment]
Move to vscode-website repo.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-website#591
