### ISSUE TITLE
unassigned keyboard shortcut in C# documentation

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-docs#7634]
A user reported that when they went to https://code.visualstudio.com/docs/csharp/get-started#_create-a-hello-world-app it now says or use the unassigned keyboard shortcut instead of providing the ctrl+F5 for running without debugging.

![Image](https://github.com/user-attachments/assets/1cc2ecb3-24a4-46c8-af8a-5e09e73cbec4)

**Comment by ntrogh** [comment]
It looks like the command ID for **Run without Debugging** has changed from `workbench.action.run.start` to `workbench.action.debug.run`.
