### ISSUE TITLE
`cmd` + `enter` to open files in a new editor group

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-docs#764]
Review https://github.com/Microsoft/vscode-docs/issues/702.
We mentioned that users can open files in a new editor group in five ways : https://code.visualstudio.com/docs/editor/codebasics#_side-by-side-editing and the first one is

> Ctrl (Mac: 'Cmd') click on a file in the Explorer.

My favorite way is running `cmd+enter` while navigating files through command palette, which is somewhat similar to the first one. Maybe we can enrich this one.

**Comment by gregvanl** [comment]
I put Cmd+Enter in Quick Open at the bottom of the list since Quick Open hasn't been discussed yet in the doc and the other 4 gestures are more straightforward.
