### ISSUE TITLE
Display keybindings on different platform

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-docs#765]
Review #702 

In https://code.visualstudio.com/docs/editor/codebasics sometimes we are showing keybindings for different platforms

> you can switch between them quickly by holding the Ctrl (Mac: 'Cmd') key 

but sometimes we are smart enough to know that users are using Mac and we just show keys specific for Mac.

It's not a big deal but maybe we want to align them. Making it smart always.

**Comment by gregvanl** [comment]
We can use the platform specific key binding look up (command id -> keyboard shortcut) when the text is talking about a command which has a command id. When the text is mentioning a single key like `cmd`, we have to include both the Windows/Linux and Mac key since there is no command id to lookup.
