### ISSUE TITLE
Add documentation for `Do not Disturb` mode

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-docs#7653]
There does not seem to be any documentation regarding the do not disturb mode. The only thing I m able to find is the release notes. Might be worth adding to our docs?

**Comment by bpasero** [comment]
@ntrogh do you have an existing page in mind where this could be added?

**Comment by ntrogh** [comment]
@bpasero might be good to add it in the "Configure the editor" section, just after "zen mode" in the user interface doc. 
https://code.visualstudio.com/docs/getstarted/userinterface#_zen-mode
