### ISSUE TITLE
Pin a file in Open Editors Viewlet

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-docs#766]
Review #702 

In https://code.visualstudio.com/docs/editor/codebasics#_open-editors, we mentioned a file would be listed in Open Editors view if 

> Make a change to a file.
> Double-click a file in the Explorer.
> Open a file that is not part of the current folder.

If you double click on the tab bar of a file, it will be listed in the Open Editors view as well. I learnt this from .NET Native team's manager who uses Code to review .NET code every day.

**Comment by gregvanl** [comment]
Works for both tabbed and non-tabbed headers so calling out the "file's header".
