### ISSUE TITLE
Hyperlink in README.md line 85 404s; Section purpose unclear

### ISSUE THREAD

**Issue by timothywarner** [microsoft/vscode-docs#7660]
Hi team,

I noticed that the link on line 85 of the `README.md` file in the main branch leads to a 404 error.

Additionally, I have a broader question: _What is the purpose of this link and the corresponding section of the document_? Specifically, is there any detailed explanation on how content is promoted from internal to public repository replicas?

Thanks for your help!

**Comment by ntrogh** [comment]
@timothywarner Thanks for raising this and asking. I'll remove the link, as it points to the website deployment instructions, which are in a private repo.

On the broader topic, all VS Code docs are hosted in the public vscode-docs repository, so there's no promotion between the private and public repo. The private repository only contains the website infrastructure code.
