### ISSUE TITLE
Broken git-scm link on Source Control/Overview page titled "Using Git source control in VS Code"

### ISSUE THREAD

**Issue by terrifricker** [microsoft/vscode-docs#7697]
Page with broken link: https://code.visualstudio.com/docs/sourcecontrol/overview
Current link is https://git-scm.com/documentation which results in a 404 error.
The correct link to the documentation page is https://git-scm.com/doc

Screenshot of page

![Image](https://github.com/user-attachments/assets/b6fdc9b6-b14c-4ea8-80eb-056c2ab6a363)

Screenshot of current link https://git-scm.com/documentation

![Image](https://github.com/user-attachments/assets/731178ed-1590-4c78-8d96-cf65feaa0e74)

Screenshot of correct link https://git-scm.com/doc

![Image](https://github.com/user-attachments/assets/c7633efe-8190-4630-9fd5-8b12eb6e825e)

**Comment by ntrogh** [comment]
@terrifricker thanks for reporting this. Fixed and should be live with the next publish of the docs.

**Comment by terrifricker** [comment]
Awesome!
