### ISSUE TITLE
https://code.visualstudio.com/updates/v1_75#_ignore-a-setting-to-sync

### ISSUE THREAD

**Issue by rbrukh** [microsoft/vscode-docs#7714]
![Image](https://github.com/user-attachments/assets/e3e2e084-893a-4b69-b0b4-1e7f36a1595c)

**Comment by ntrogh** [comment]
@rbrukh can you provide more details about this issue?

**Comment by ntrogh** [comment]
Feel free to reopen and provide more information about this issue.
