### ISSUE TITLE
Quick Pick UX guidelines contradict themselves

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-docs#7822]
@timheuer cunningly noticed that we are violating our own guidelines in UX guidelines 
https://code.visualstudio.com/api/ux-guidelines/quick-picks

No strong opinions from me here. Should we update image? Remove guideline?

![Image](https://github.com/user-attachments/assets/2fd2c66a-b1c2-432b-b7ac-f8fae8d628ef)

fyi @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
But they're not the same icon? One has the ✅  and the rest do not. I'm guessing it's referring to the one you're currently connected to?

**Comment by isidorn** [comment]
I guess Tim's point is that items 2 and 3 use the same icon.

I think that might be fine, since they are the same "Item Type".

So maybe the guidelines should be "Use the same icon for multiple item types"

**Comment by TylerLeonhardt** [comment]
![Image](https://github.com/user-attachments/assets/984390eb-dded-402d-b8cb-764cb93eba39)

then we're also breaking our own guideline here as well... to me this should really be "don't use the same icon for all items"

**Comment by timheuer** [comment]
In the world of "do/don't" I am not sure you can come up with a 'don't' that gets all the scenarios.  Even 'don't use the same icon for all items' would break the file list example (think a list of a folder named JPEGs) :-).  I'm not sure the guideline as a 'don't' makes sense.  

There is some guideline here of using thoughtful icons, etc. (maybe put that in the 'do' note and just remove the don't).  

This was definitely a nit from me, but in the world of binary lists, I noticed a violation ;-)
