### ISSUE TITLE
Recommend JSON TextMate extension in the Syntax Highlight Guide

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode-docs#7844]
[developing-a-new-grammar-extension](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#developing-a-new-grammar-extension) recommends using YAML for writing the grammar in. (Using YAML to write a grammar)

however the [JSON TextMate extension](https://marketplace.visualstudio.com/items?itemName=RedCMD.tmlanguage-syntax-highlighter) provides a superior experience:
* Accurate Syntax Highlighting
* Intellisense
* Diagnostics error reporting
* Ctrl+click Definitions
* Breadcrumbs/Outline
* Formatting
* Schema support
* [F2] Rename
* CallStack Viewer
* Deadcode dimming

and doesn't require converting the file on every change

notice how the syntax highlighting in the regex is broken
![YAML](https://code.visualstudio.com/assets/api/language-extensions/syntax-highlighting/yaml-grammar.png)
![JSON TextMate](https://github.com/user-attachments/assets/e1cc0118-f8a7-44c2-9e9c-a78118247a04)

**Comment by alexr00** [comment]
The syntax highlighting is actually ok, that's just an old image (which we should probably update)

![Image](https://github.com/user-attachments/assets/2d776696-5bfb-4795-a379-0279eec9960d)

**Comment by ntrogh** [comment]
Updated the article to refresh the screenshot.

**Comment by alexr00** [comment]
@RedCMD this is a cool extension, but we usually prefer to link to 3rd party extensions to illustrate an example of a common extension category. Your extension is a very specific tool for extension authors. I can see the appeal, but we're not going to add the link at this time!
