### ISSUE TITLE
Document URL handling

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-docs#791]

**Comment by joaomoreno** [comment]
Fixed by 6a136c2bdd671938482e767cbd47d393a0da5957

**Comment by RoadToDream** [comment]
It doesn't seem like it works =-=

**Comment by RoadToDream** [comment]
Neither in VSCode nor VSCode Insider

**Comment by lyrixx** [comment]
it does not work for me either

**Comment by westurner** [comment]
- #3004 
> * https://code.visualstudio.com/updates/v1_23#_git-clone-improvements :
>       > `vscode://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode-vsce.git`
> 
>     * [Support opening files through URL handling vscode#4883 (comment)](https://github.com/microsoft/vscode/issues/4883#issuecomment-270141535) :
>       > Open a file to a specific line and column number:
>       > `vscode://file/path/to/file/file.ext:L:C`
>       > Example: Open `file.ext` to line `55` and column `20`:
>       > `vscode://file/path/to/file/file.ext:55:20`
>       > Open a project, workspace, or folder with directory contents:
>       > `vscode://file/path/to/project/`
