### ISSUE TITLE
Mac keyboard shortcut reference issues

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-docs#794]
See the annotated version of the cheatsheet.
- The red items should be converted to use the official key symbols.
- The orange items use <kbd>Home</kbd>, <kbd>End</kbd>,<kbd>PgUp</kbd>, and <kbd>PgDown</kbd>. On most Mac keyboards there are no such keys. The mapping is as follows:
   - <kbd>Home</kbd> => <kbd>Fn</kbd> + <kbd>Left</kbd>
   - <kbd>End</kbd> => <kbd>Fn</kbd> + <kbd>Right</kbd>
   - <kbd>PgUp</kbd> => <kbd>Fn</kbd> + <kbd>Up</kbd>
   - <kbd>PgDown</kbd> => <kbd>Fn</kbd> + <kbd>Down</kbd>
I propose we add a section to the cheatsheet that explains this mapping.

[keyboard-shortcuts-macos-2.pdf](https://github.com/Microsoft/vscode-docs/files/682930/keyboard-shortcuts-macos-2.pdf)

**Comment by gregvanl** [comment]
Fixed the red items.
I don't think we want to include hardware mappings for Home, End, PgUp, and PgDn. Users should be able to consult their hardware vendors documentation. Special mappings for laptop and other minimal keyboard devices isn't limited to Mac, for example Asus ZenBooks also don't have dedicated Home, End, PgUp and PgDn.

**Comment by kieferrm** [comment]
@gregvanl the argument about 'hardware mappings' doesn't hold for macOS. There is only one hardware provider. There are no such buttons.

**Comment by mozebdi** [comment]
I can improve this part of the documentation if anyone would like to assign it to me.

**Comment by gregvanl** [comment]
Closing older issue as no user upvotes.
