### ISSUE TITLE
Localized Release Note in Japanese

### ISSUE THREAD

**Issue by ayatokura** [Microsoft/vscode-docs#798]
How should it be done when I want to contribute about localization of release note?

As you can see under my repository, I've translated previous release notes from English to Japanese.
https://github.com/ayatokura/JP-VSCode-Docs/tree/master/release-notes

More localized release notes and additional information about VSCode in Japanese are available at https://blogs.msdn.microsoft.com/ayatokura/

**Comment by gregvanl** [comment]
Hi @ayatokura, Thank you for reaching out with your offer to help localize our docs. At this point, we don't plan to translate our official website but if that plan changes, we'll certainly be looking for community help. Thanks!
