### ISSUE TITLE
[question] syntax  for string  embed evaluate code

### ISSUE THREAD

**Issue by foxundermoon** [Microsoft/vscode-docs#799]
**i am use photoshop draw the sample syntax for the custom language.**

![syntax-wxml](https://cloud.githubusercontent.com/assets/2764106/21882562/fc8629fc-d8e5-11e6-8c75-c747a18a79c6.png)

how  to write the syntax of tmLanguage ?

##  evalute code rule
```json
{
      "begin": "\\{\\{",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.brace.curly.start"
        }
      },
      "end": "\\}\\}",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.brace.curly.end"
        }
      },
      "patterns": [
        {
          "include": "source.js#expression"
        }
      ]
    }
```
  use it for child string entity pattern but surround string can not match

## double quoted content rule for attribute of tag
```json

 "string-quoted-double": {
      "begin": "\"",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.wxml"
        }
      },
      "end": "\"",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.wxml"
        }
      },
      "name": "string.quoted.double",     <------------=====
      "patterns":[
            {
                    "include":" the up pattern  ↑"
           }
       ]
    }

```  

if the  name is present，all double quoted content is string‘s color，
else the surround string is plain text color.

**Comment by aeschli** [comment]
I suggest you ask this in a forum related to text mate. We are not really TextMate experts as all the text mate grammars we use in VSCode are maintained by the community.
By asking in a forum you are more likely to get a good response and have other profit from the answers as well.
