### ISSUE TITLE
pylint show again and again  after installed

### ISSUE THREAD

**Issue by qianthinkover** [Microsoft/vscode-docs#805]
![vscode](https://cloud.githubusercontent.com/assets/3151832/22182929/6864fdca-e0ec-11e6-99af-762bf2cd2f24.png)

I install it once ,when I change my code , this plugin still give me a tip to need to install it even I close it, is that bug of IDE or plugin bug? how to solve it?

**Comment by gregvanl** [comment]
This would be an issue with the extension. VS Code doesn't have any direct knowledge of pylint. You should be able to enter an issue in the extension repository.
