### ISSUE TITLE
"code" function for OSX Yosemite fails with syntax errors, max number of files for opening

### ISSUE THREAD

**Issue by yangmillstheory** [Microsoft/vscode-docs#81]
On Yosemite 10.10.5, I followed instructions for setting up `code` in the Mac OS shell [here](https://code.visualstudio.com/docs/editor/setup), but get syntax errors.

	ts (master?!) $ more ~/.bash_profile
	if [ -f ~/.bashrc ]; then
	   source ~/.bashrc
	fi

	# Setting PATH for Python 3.5
	# The orginal version is saved in .bash_profile.pysave
	PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
	export PATH

	code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
	ts (master?!) $ source ~/.bash_profile
	-bash: /Users/valvarez/.bash_profile: line 10: syntax error near unexpected token `('
	-bash: /Users/valvarez/.bash_profile: line 10: `code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}'

Prefixing the definition with `function` makes it work:

	~ $ more ~/.bash_profile
	if [ -f ~/.bashrc ]; then
	   source ~/.bashrc
	fi

	# Setting PATH for Python 3.5
	# The orginal version is saved in .bash_profile.pysave
	PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
	export PATH

	function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*
	 ;}
	~ $ source ~/.bash_profile
	~ $

`code` now opens new files as well as creates new ones if they don't exist, however, it only opens up a maximum of three files plus an optional directory.

	ts (master?!) $ ls -l
	total 40
	-rw-r--r--  1 valvarez  TSI\Domain Users   91 Dec 14 22:03 app.js
	-rw-r--r--  1 valvarez  TSI\Domain Users   92 Dec 14 19:50 app.ts
	-rw-r--r--  1 valvarez  TSI\Domain Users    0 Dec 15 09:41 bar
	-rw-r--r--  1 valvarez  TSI\Domain Users    0 Dec 15 09:41 baz
	-rw-r--r--  1 valvarez  TSI\Domain Users   64 Dec 14 22:03 foo.js
	-rw-r--r--  1 valvarez  TSI\Domain Users   54 Dec 14 19:42 foo.ts
	-rw-r--r--  1 valvarez  TSI\Domain Users  104 Dec 14 22:03 jsconfig.json
	ts (master?!) $ code bar baz app.ts
	ts (master?!) $
    ts (master?!) $ code ../vs-code foo bar ../vs-code/LICENSE.md

You'll have to trust me that these last step opens up a new editor with with the right files :).

That maximum limit is not in accordance with this [documentation](https://code.visualstudio.com/docs/editor/codebasics):

>Sometimes you will want to open or create a file. If a file does not exist, we will create it for you:

> code index.html style.css readme.md
>Tip: You can have as many file names as you want separated by spaces.

I can submit a pull request with [the fixed function definition](https://github.com/yangmillstheory/vscode-docs/commit/a299af80ea91bd9edf37f46ad95309f5fb49161f), but should we denote the limit for the number of files `code` can open at once [here](https://code.visualstudio.com/docs/editor/codebasics)?

**Comment by gregvanl** [comment]
Thank you for the bash fix.  I'll update the website shortly.
I think the second issue is by design.  You can specify as many filenames as you want when you launch VS Code.  The limitation is that you can only have three open editors.  All the files specified on the command line will be available in the WORKING FILES list.  The three editors limit is covered earlier in the Basic Layout section.
