### ISSUE TITLE
Panel screenshots need to be updated

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#820]
Not very high prio, but we updated the panels for the 1.9 release to show the list of available panels to the top and we also changed the icon for hiding the panel:

![image](https://cloud.githubusercontent.com/assets/900690/22519784/00456c52-e8b2-11e6-9afc-5eeccb04aeaf.png)

**Comment by ndrafahl** [comment]
hey @bpasero - is this still an issue?  Was looking for something simple to help fix - was digging through the image files but couldn't locate where it was at.

**Comment by gregvanl** [comment]
I think most of the screen shots have been updated. Reopen if there's something we've missed
