### ISSUE TITLE
Bug in extensions documentation

### ISSUE THREAD

**Issue by wadeanderson7** [Microsoft/vscode-docs#83]
There is a bug when viewing extensions api documentation. See [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_extensions).

I tried to make a change in the code, but I can't figure out where the API content gets loaded (I am looking in vscode-api.template). An explanation of how that works would be great. 

I am on a Macbook running Chrome 47.0.2526.106 (64-bit). 

![image](https://cloud.githubusercontent.com/assets/2449568/11860898/fe2a4a8c-a42e-11e5-8f00-e75bf615c970.png)

**Comment by gregvanl** [comment]
Workaround is to manually modify the generated vscode-api.cshtml page.  Subsequence vscode-docs commits will regenerate this page with the issue.

**Comment by SofianHn** [comment]
This issue is related to https://github.com/markdown-it/markdown-it/issues/187

The spec was confusing on what should define a start/end of an html block within a markdown file. To prevent misbehavior I am adding a whiteline before every pre tag to prevent markdown-it from escaping the html content. This should not have an effect on the final cshtml files.

**Comment by puzrin** [comment]
@SofianHn sorry for stupid question, but what reasons are to use html for code blocks instead of native markdown "fenced blocks"?

**Comment by SofianHn** [comment]
Not stupid at all. We just happened to compile markdown at two stages due to our doc generation structure. Which means at some point we have to deal with HTML content inside markdown. While not idea we think it should not cause any issues.

**Comment by puzrin** [comment]
I mean, you could generate fenced blocks on the first phase and add highlighter via markdown options.

**Comment by SofianHn** [comment]
You are right, we already start with fenced blocks, we should just not compile md at the first stage all together. We are aware of this and want optimize it at some point.

This is a new pipeline that we build out of existing blocks. First stage was to get all pieces working. There is plenty of optimizations that are needed next.
