### ISSUE TITLE
Add PRs for the release notes  (tracking item)

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#832]
Contribute PRs for the contents in the release notes of the January update

- [x] @weinand 
- [x] @dbaeumer 
- [x] @egamma
- [x] @isidorn 
- [x] @bpasero 
- [x] @joaomoreno 
- [x] @aeschli 
- [ ] @alexandrudima 
- [x] @jrieken 
- [x] @sandy081

**Comment by aeschli** [comment]
I delivered a927f2f87e525fbdbb541d34caf521b399f24b3d and f15f36082a5d2efaa442514a0743b985f97b9f07 to vnext.

**Comment by sandy081** [comment]
Created a [PR](https://github.com/Microsoft/vscode-docs/pull/834) for settings features

**Comment by gregvanl** [comment]
I've chatted with Alex and I've taken care of his 1.9 content (Inspect TM Scopes widget and linkForeground) with https://github.com/Microsoft/vscode-docs/commit/d58872ed70ba02c13f5adf47d7751b45e88f7baa
