### ISSUE TITLE
Release notes/documentation issue

### ISSUE THREAD

**Issue by jreljac** [Microsoft/vscode-docs#843]
The release notes for version 1.9 seem to have an error which causes the example to not work properly.

The following is on: https://code.visualstudio.com/updates/v1_9#_insert-snippets

**Insert snippets**
You can now bind your favorite snippets to key bindings. A sample that encloses a selection with single quotes looks like this:

```
{
	"key": "cmd+k '",
	"command": "editor.action.insertSnippet",
	"args": { "snippet": "'$TM_SELECTED_TEXT'" }
}
```

Seems to me that it should be `"key": "cmd+k",` NOT `"key": "cmd+k '",`

Using the current example didn't work but eliminating the extra space and single quote worked.

**Comment by gregvanl** [comment]
Hi @jreljac, 

The keybinding examples works for me on Windows (using "ctrl+k '" - with single quote). What platform are you on? 
Binding directly to "cmd+k" will disable all the keybinding chords such as "cmd+k cmd+c" (addCommentLine).

**Comment by gregvanl** [comment]
A colleague just tried the example on a Mac and it worked. The example is a keyboard chord meaning you do one gesture (cmd+k) followed by another gesture (' single space). 
This section in our documentation explains chords http://code.visualstudio.com/docs/customization/keybindings#_keyboard-rules
