### ISSUE TITLE
Error in the SASS/LESS -> CSS guide

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-docs#85]
_From @malisbad on December 17, 2015 4:53_

There is an error in your SCSS/LESS - > CSS guide. The task shouldn't have the ">" in the task runner (anymore?). If you follow the guide, it writes the compiled .css to the ">". If you remove it, it writes to "styles.css" correctly.

_Copied from original issue: Microsoft/vscode#1401_

**Comment by aeschli** [comment]
_From @dbaeumer on December 17, 2015 8:49_

@aeschli not sure if this is you

**Comment by aeschli** [comment]
This is about the 'Transpiling Sass and Less into CSS' section in https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/css.md
Not sure who authored that, @gregvanl ?

**Comment by gregvanl** [comment]
Will be fixed in the December release documentation.
