### ISSUE TITLE
debug: explain how to redirect input/output from/to the debug target

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-docs#856]
From https://github.com/Microsoft/vscode/issues/20890

**Comment by mike-prokaziuk** [comment]
Hello! 
How can I redirect this output data (while debugging) to my extension?

**Comment by weinand** [comment]
@mike-prokaziuk I don't understand what you mean.

**Comment by mike-prokaziuk** [comment]
At this moment, I launch  child process by using 'spawn' command and attach to him. In this case I can subscribe to 'cp' events and receive data.
But, I wanted to try launch this process using VS Code capabilities and 'launch.json' file. 
The process has started and the VS Code has attached to them, but now I don't understand how to receive the data from them :) . 
The 'process' is simple console app.

**Comment by OmegaDoom** [comment]
```
{
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": [
                "<",
                "in.txt"
              ]
        }
```
No effect. File is not redirecting.

**Comment by OmegaDoom** [comment]
I updated python to 3.7.2 and it started working!

**Comment by guyarad** [comment]
This simple "docs addition" is open for 2 years... 
And currently I'm unable to make this work.
This is my launch configuration:

        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/myapp.dll",
            "args": ["<", "/Users/guyarad/src/input.txt"],
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "stopAtEntry": false
        }

Any ideas?

**Comment by MarcusCemes** [comment]
## Example use case

[The Pino logger](https://github.com/pinojs/pino#development-formatting) recommends piping the output to a "prettifier" when developing, it avoids the use of including dev libraries in code.

**Comment by weinand** [comment]
@gregvanl here is what we could say:

"Redirect input/output from/to the debug target"

Redirecting input/output is debugger/runtime specific, so VS Code does not have a built-in solution that works for all debuggers.

Here are two approaches you might want to consider:
1. launch the program to debug (aka debug target) manually in a terminal shell and redirect input/output as needed. Pass command line options to the debug target to enable that a debugger can attach to it. Create and run an "attach" debug configuration that attaches to the debug target.
2. if the debugger extension you are using allows to run the debug target in VS Code's integrated terminal (or an external terminal), you can try to pass the shell redirect syntax as arguments. E.g.:
   ```
   {
            "name": "launch program that reads a file from stdin",
            "type": "node",
            "request": "launch",
            "program": "program.js",
            "console": "integratedTerminal",
            "args": [
                "<",
                "in.txt"
             ]
    } 
   ```
   This approach requires that the "<" syntax survives the debugger extension and ends up unmodified in the integrated terminal.

**Comment by DollarAkshay** [comment]
Any clue on how to do the same thing in powershell ? I need to add `Get-Content <file> | ..` before my command
