### ISSUE TITLE
Disable CSS Linting

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-docs#86]
_From @cfjedimaster on December 16, 2015 19:59_

I'm working on an extension that supports CSSLint. While you can disable VSC's linting of JS files (https://code.visualstudio.com/docs/languages/javascript#_javascript-linters-eslint-jshint), you can't disable VSC's CSS linting.

_Copied from original issue: Microsoft/vscode#1392_

**Comment by aeschli** [comment]
_From @cfjedimaster on December 16, 2015 20:36_

Ok, it *is* supported, just not documented. :)

**Comment by aeschli** [comment]
_From @egamma on December 16, 2015 20:45_

@cfjedimaster This is what I thought :smile: 

@aeschli can you look into updates in the doc.

**Comment by OutsourcedGuru** [comment]
For what it's worth in Microsoft Visual Studio Community 2017:
  Tools -> Options... -> Text Editor -> CSS -> CssLint -> Enable CSS Lint = False

**Comment by cfjedimaster** [comment]
@OutsourcedGuru totally different product :)

**Comment by OutsourcedGuru** [comment]
@cfjedimaster And yet, wouldn't it be cool to find the feature using the same menu navigation.  ha

**Comment by cfjedimaster** [comment]
Shrug - maybe. I don't ever use Visual Studio so I wouldn't have that muscle memory. ;)

**Comment by DavidTheProgrammer** [comment]
Uhm How do we do this in vscode? SCSS Linting is messed up and I'd like to disable it

**Comment by carlosbvz** [comment]
Thanks @DavidTheProgrammer .

Has anyone know how to disable a specific rule?
I am working with CSS Grids an adding some prefixes for IE11, but got an annoying 'problem': https://cloudup.com/cBSDTRwWdRa

**Comment by Phrogz** [comment]
> Open User Preferences `ctrl + ,` and type "disable" You'll see a host of options to turn off language validations, click the one you'd like to disable and set it to false

Specifically, if you search for "css validate" you will find an option named "CSS: Validate" whose description is "Enables or disables all validations."

![screenshot of the CSS:Validate option](https://user-images.githubusercontent.com/14778/84184767-2ea42580-aa4b-11ea-85e1-f112840da754.png)
