### ISSUE TITLE
Readme should have info on building / viewing (serving) the documentation

### ISSUE THREAD

**Issue by NiloCK** [Microsoft/vscode-docs#861]
I use this repo for offline access to the vscode docs. I'd like to be able to build a local copy of the website rather than view them inside of vscode (for clickable links, etc).

Running the build task creates the following,

```
-out
 -vscode-website
  -src
   -dist/images
   -public
   -views/ ... (various)
```

where the views subdirectories are filled with template and data files (.handlebars), but without any readme or other instruction on how to view or serve the site. I assume this is done with a Jekyll type tool, but I can't see any config files to indicate.

I suggest that the top level Readme for these docs should includ the required information for:

 - serving the built page, and/or
 - building an actual directory of directly viewable .html files

**Comment by gregvanl** [comment]
Here is the incantation:

```
gulp build-website
cd out/vscode-website
npm run dev
npm start
```
Then launch a browser and go to localhost:3000.

I'll update the vscode-docs README with these instructions.

**Comment by gregvanl** [comment]
Update README with https://github.com/Microsoft/vscode-docs/commit/87005557a69f8615db5438b0b9804a198b054354

**Comment by EbXpJ6bp** [comment]
I cant access https://github.com/microsoft/vscode-website.  (private?)
`gulp build-website` will fail.

**Comment by gregvanl** [comment]
Oops, you're right, this won't work since our website repo is private.

**Comment by gregvanl** [comment]
Sorry @NiloCK. Our website repo isn't currently public so you won't be able to pull down the necessary infrastructure locally.
@waderyan

**Comment by gregvanl** [comment]
Hmm, @NiloCK how were you able to successfully run the build-website task to generation out\vscode-website?

**Comment by NiloCK** [comment]
I'm building from inside vs-code with the following tasks.json file:

``` json
    {
      // See https://go.microsoft.com/fwlink/?LinkId=733558
      // for the documentation about the tasks.json format
      "version": "0.1.0",
      "command": "gulp",
      "isShellCommand": true,
      "args": [
        "--no-color"
      ],
      "tasks": [
        {
          "taskName": "compile-all",
          "args": [],
          "isBuildCommand": true
        }
      ]
    }
```

Worth noting that my working directory here is out of date and not a repository.

`gulp -v` on my system returns `[22:47:14] CLI version 1.2.2`
