### ISSUE TITLE
How to add Open with VS Code context menu in Nautilus

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-docs#873]
Might be worth adding a section to setup/linux

Context: https://github.com/Microsoft/vscode/issues/22036

**Comment by LogX7** [comment]
this would be great

**Comment by ajomadlabs** [comment]
Can I take up this issue

**Comment by Tyriar** [comment]
@ajomadlabs please 😃 a section in the FAQ here would be great https://github.com/Microsoft/vscode-docs/blob/master/docs/setup/linux.md#common-questions

**Comment by gregvanl** [comment]
Hi @ajomadlabs Have a look at this repo's README and CONTRIBUTING pages. Feel free to reach out to me if you have questions about providing content.

**Comment by cra0zy** [comment]
On a related note, I tried @RicardoEPRodrigues extension, and turns out, its buggy and its missing stuff:
- Its connecting code process with nautilus process
- Its not providing opening code with multiple files
- Its not allowing to open vs code from the current folder

And so, I have decided to write one from scratch, enjoy: https://gist.github.com/cra0zy/f8ec780e16201f81ccd5234856546414

PS. I tried to do a cross between Tilix extension for Nautilus and Windows VS Code integration naming schemes

**Comment by cra0zy** [comment]
> Not allowing to open vs code from the current folder is a problem with using Nautilus Python extensions (or maybe my lack of experience), since I wasn't able to show the options in the current folder.

No, its a separate method, my extension already fixed it all:
![vscodeext](https://user-images.githubusercontent.com/6773302/38950667-83d555b0-4346-11e8-91b2-d18b16edacce.png)

**Comment by RicardoEPRodrigues** [comment]
Tested your extension. Yup, its very good! :smile:

Thank you!

Maybe one feature I would like is, when only one file is selected, open it without `--new-window`, but I it's more consistent this way.

**Comment by cra0zy** [comment]
> Maybe one feature I would like is, when only one file is selected, open it without --new-window, but I it's more consistent this way.

Hmmm, yea, makes sense, I've modified the script, by default `--new-window` is not set only if you are trying to open at least 1 folder.

**Comment by damogallagher** [comment]
I just tried this on Ubuntu Artful but it doesnt work
Does anyone have any suggestions on how I could get @cra0zy's script to work on Artful?

**Comment by cra0zy** [comment]
You need `python-nautilus` package installed.

**Comment by marc2377** [comment]
For those using Nemo (the file browser for the linux mint's Cinnamon environment) I'm providing a solution here: https://gitlab.com/snippets/1712370

**Comment by MrChriZ** [comment]
I'd like to see a solution for Dolphin

**Comment by lexxyungcarter** [comment]
Got mine working by installing *python-nautilus* package, then creating a new entry:
```bash
sudo ln -s /usr/bin/code /usr/local/bin/code
# With this action I can also open vscode via the terminal by typing 
# code . 
```
Followed by entering the following options in the *command* section:
**Parameters:**
```bash
. --working-directory=%d/%b
# Mind the dot at the start
```
![image](https://user-images.githubusercontent.com/19994360/40885601-24dc006c-6732-11e8-816d-13587ff8f677.png)


Ubuntu 18.04 LTS

**Comment by cra0zy** [comment]
Still better to use my extension, since your way does not seem to take into account a lot of stuff like folder opening, new window creation etc.

Also your `PATH` env variable seems messed up if you needed to create that symlink.

https://gist.github.com/cra0zy/f8ec780e16201f81ccd5234856546414

**Comment by MEXdave1997** [comment]
@ajomadlabs do you have any progress made on this? 😃

**Comment by sdabhi23** [comment]
Any updates on the extensions?

Will each distro require a separate extension? (I guess yes, coz many of them use different file managers)

Also I would like to take this up

**Comment by cra0zy** [comment]
Each file manager would require its own extension, the extension I wrote above is Nautilus only.

**Comment by githubsaturn** [comment]
@cra0zy you may want to update your script. I believe the command `code` is now changed to `vscode`

**Comment by cra0zy** [comment]
Have the newest visual studio code, and `code` is still the valid command for it. Where did you install it from? I could add a list of fallback commands in case it from one of the official sources.

**Comment by githubsaturn** [comment]
That's bizarre... I am running version 1.32.3 on Ubuntu 18 installed from snap.

**Comment by cra0zy** [comment]
Hmm, wrong package installed maybe?

Official package link:
https://snapcraft.io/code

Snapcrafters packages link:
https://snapcraft.io/vscode

**Comment by githubsaturn** [comment]
Oh! Had no idea there are 2 packages!

I'm gonna uninstall my vscode and install code as it seems to be the official one. But if it's possible, i think it's not a bad idea to add vscode as a fallback to your snippet.

**Comment by gregvanl** [comment]
Closing old issue. Looks like people have various solutions and no one has responded to the `help wanted` label.

**Comment by Coderx7** [comment]
@harry-cpp 's solution worked well for me(ubuntu18.04). Thank you very much really appreciate it. 
The previous links are dead here, since he changed his username. 
This is the new link : https://github.com/harry-cpp/code-nautilus 
And this one liner adds code to the right click menu:
```
wget -qO- https://raw.githubusercontent.com/cra0zy/code-nautilus/master/install.sh | bash
```

**Comment by mwpowellhtx** [comment]
I am trying to find the `nautilus-actions` or `filemanager-actions` as some blogs indicated, but cannot seem to find them. Have the repository(ies) vanished? Thank you.

**Comment by kowalski7cc** [comment]
I think VSCode on Linux should have something like @harry-cpp plugin out of the box. Working really well on Fedora 32.
