### ISSUE TITLE
Support to hide .js files from generated .ts and .tsx file

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#875]
Please add this trick from this thread to the FAQ 

```
"**/*.js": { "when": "$(basename).ts" },
"**/**.js": { "when": "$(basename).tsx" }
```

// FYI @waderyan

**Comment by waderyan** [comment]
Looks like we have it in the TypeScript doc. https://code.visualstudio.com/docs/languages/typescript#_hiding-derived-javascript-files

**Comment by egamma** [comment]
@waderyan this is an additional trick :smile:.

You want to hide both .js files generated from .ts files and .tsx files. The challenge is that the glob pattern is also used as the key. Therefore there can only be a single one. The trick is to define a glob pattern that matches the same files but it is different so that it has a separate key  e.g. `**/**.js` vs `**/*.s`

**Comment by waderyan** [comment]
Ah I see. Very subtle :)

**Comment by waderyan** [comment]
@egamma does putting it this [section](https://code.visualstudio.com/docs/languages/typescript#_hiding-derived-javascript-files)  work for you? 

You mention putting it in the FAQ, but I think it makes more sense on the TS page.

**Comment by AaronHarris** [comment]
It looks like this has been removed in more recent versions of VS Code that don't have the JSON settings editor. What's the way to go about this now?

**Comment by gregvanl** [comment]
Hi @AaronHarris Thanks for calling this out. The new Settings editor UI doesn't nicely support adding when clauses so updated the TypeScript Compiling topic to mention the workspace settings.json command with https://github.com/microsoft/vscode-docs/commit/9446fbbe56c7109195e1abc5af1712da27c97ee7
