### ISSUE TITLE
Update release notes to not mention dirty file debugging

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#876]
Due to some late minute bugfixies we had to remove a feature from the newest version of vscode.

Due to that we should fully remove the section unsaved file debugging from our release notes.
I am assigning to you @gregg-miskelly since I am not sure what is our process of editing release notes which are live on the site.
http://code.visualstudio.com/updates/v1_10#_unsaved-file-debugging

**Comment by gregvanl** [comment]
@isidorn Got it. I'll update the 1.10 release notes for the 1.10.2 release.
@gregg-miskelly A case of mistaken identity.

**Comment by isidorn** [comment]
@gregvanl thanks! Had the wrong Greg oups...
