### ISSUE TITLE
small-nav-dropdown not sync

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode-docs#878]
https://github.com/Microsoft/vscode-docs/blob/master/scripts/templates/releasenotes-nav-template.html#L13 blog, portaldocs

I think that should change `"selected"` to `selected=""` or `selected`

**Comment by waderyan** [comment]
@EbXpJ6bp Thank you for opening this issue. 

Can you help me understand what it is you are seeing? Can you explain "not sync"?

**Comment by EbXpJ6bp** [comment]
![3770082f9c454c1e57d87e5bd8e1afb9](https://cloud.githubusercontent.com/assets/8474118/23818227/9fb02136-063c-11e7-8b22-dc294cec3236.png)
This is it.  It also was found in Chrome and firefox.

**Comment by waderyan** [comment]
@EbXpJ6bp I'm still not understanding. What is the problem?

**Comment by waderyan** [comment]
Ah nevermind I see it.. Thank you for reporting. We will take a look.

**Comment by gregvanl** [comment]
Thanks! Your suggestion fixed the issue.
