### ISSUE TITLE
docs/extensionAPI/vscode-api#_extensions has a misformed code block

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode-docs#88]
The underlying markdown HTML is visible rather than the intended code-block output as shown below.

![image](https://cloud.githubusercontent.com/assets/2957173/11917835/1349379e-a721-11e5-8e0a-c395ea79abd1.png)

**Comment by jrieken** [comment]
That is in the tooling which makes razor. the generated markdown is still proper

**Comment by gregvanl** [comment]
Duplicate of #83
