### ISSUE TITLE
Need better documentation with example for SignatureHelpProvider

### ISSUE THREAD

**Issue by indiejames** [microsoft/vscode-docs#881]
It is not obvious at all from what little documentation there is how `SignatureHelpProvider` and `provideSignatureHelp` work. There needs to be a clear example of how the `label` for a `SignatureInformation` object acts as a parameterized template for what is displayed in the popup, and that it *must* contain the values of the `label`s in the associated `ParameterInformation` objects.

**Comment by kjeremy** [comment]
I'm really glad that I just found this comment.

**Comment by jrieken** [comment]
Note that we did improve the documentation and how the feature works. Is there something still missing? 

https://github.com/microsoft/vscode/blob/a0a74450041af7a28afa092a75d65a01692be653/src/vs/vscode.d.ts#L3106-L3114

**Comment by kylmp** [comment]
Wow I'm glad I found this comment. And no, 5 years later the documentation is not obvious about that!

An example for future readers which produces something like this

<img width="287" alt="Image" src="https://github.com/user-attachments/assets/5d4c7732-2477-4de7-853e-f4798d4b67f0" />

```
const provider = {
	provideSignatureHelp(document, position) {
    //const { word, match } = matchWordFromDocument(document, position);
    const signatureInfo = new vscode.SignatureInformation('label (param1, param2, param3)');
    signatureInfo.parameters.push(new vscode.ParameterInformation('param1'));
    signatureInfo.parameters.push(new vscode.ParameterInformation('param2'));
    signatureInfo.parameters.push(new vscode.ParameterInformation('param3'));
    signatureInfo.activeParameter = 1;

    const signatureHelp = new vscode.SignatureHelp();
    signatureHelp.signatures.push(signatureInfo);
    signatureHelp.activeSignature = 0;
    signatureHelp.activeParameter = 1;
    return signatureHelp;
	}
}
```
