### ISSUE TITLE
The customized "path" cannot be used by debugger

### ISSUE THREAD

**Issue by dead-lee** [Microsoft/vscode-docs#886]
I don't have admin right to my working desktop. So I am using below bat to start code:
Set PATH=%PATH%;"P:\IMWB\OCE_JXL\branches\Bluemix_POC\tools\node-v6.9.5-win-x64"
P:\Documents\VSCode-win32-1.10.2\code "P:\IMWB\OCE_JXL\branches\Bluemix_POC\src\api_connect"

I can get node working in "Integrated Terminal".  But not working in debug mode: "Cannot find runtime 'node' on PATH."

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode#22693

**Comment by gregvanl** [comment]
@dead-lee Max, this repo is for VS Code documentation issues. If you think the issue is a product bug or feature request you can open it in the VS Code product repository https://github.com/Microsoft/vscode/issues
