### ISSUE TITLE
`editor.fontFamily` in settings should suggest list of available monospace fonts

### ISSUE THREAD

**Issue by letientai299** [Microsoft/vscode-docs#889]

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode#22917

**Comment by gregvanl** [comment]
I believe this is a suggestion for the in-product settings IntelliSense suggestion so moved to vscode product repository.

**Comment by letientai299** [comment]
Thanks. Don't know why I posted here instead of vscode repo.
