### ISSUE TITLE
Edit button available for page with dynamic content

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode-docs#89]
[docs/extensionAPI/vscode-api](https://code.visualstudio.com/docs/extensionAPI/vscode-api) has an edit button, but it seems that the page is actually defined in this [template](https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/vscode-api.template) which is just a dynamically populated `{{ Content }}` block meaning it is not editable.

This also means that when contributors find bugs such as #88 they cannot contribute fixes.

**Comment by egamma** [comment]
The API documentation is generated from the source in https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts. Please make pull requests against this file.

**Comment by egamma** [comment]
Actually issue #88 is a problem with our tool.

**Comment by hoovercj** [comment]
I should have been more precise with my description:

The bug I'm reporting is that the edit button should be removed from the page in question because it goes to a 404 and the content is dynamically generated anyway and shouldn't be edited by contributors.

Right now it points to, https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/vscode-api.md which does not exist because as you said, https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/vscode-api.template just pulls in content from the typescript definition file.

**Comment by egamma** [comment]
@hoovercj got it and makes sense. The edit button should handle generated documentation, either by being disabled or by linking to the correct source page, that is, the vscode.d.ts.

**Comment by gregvanl** [comment]
Workaround is to manually modify the generated vscode-api.cshtml page and remove the Edit button. Subsequence vscode-docs commits will regenerate this page with the issue.
