### ISSUE TITLE
Remove this page

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-docs#893]
With the identifiers in the UI I think we should remove this page:
https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/identifiers.md

![image](https://cloud.githubusercontent.com/assets/1051190/24119956/2d1e01c0-0d70-11e7-8d49-63acd59fb621.png)

**Comment by gregvanl** [comment]
Removed with https://github.com/Microsoft/vscode-docs/commit/801342cddd4d648e9309ae4d8ac9c6ed2b334842
