### ISSUE TITLE
Languages Overview page

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-docs#894]
The list of extensions and the first search screenshot are a little confusing:
http://code.visualstudio.com/docs/languages/overview

The list of extensions all have there own pages.

The search shows a confusing number of Python extensions.

**Comment by gregvanl** [comment]
Removed the old Python search image.
Nothing to be done with the first list of extensions until we can do a curated list of extensions. Currently the query is category:languages @sort:installs.
