### ISSUE TITLE
how to compile this doc to website

### ISSUE THREAD

**Issue by greatbody** [Microsoft/vscode-docs#907]
I've cloned this rep and i don't know how to build htmls of this doc locally.

thanks

**Comment by gregvanl** [comment]
Hi @greatbody,

The vscode-docs repository just has the VS Code Markdown content. Our website source code is in a private repository and we don't expect our users to build our website.

**Comment by greatbody** [comment]
thanks @gregvanl , I know that now.
Great Job on making vscode the greatest Code Editor Ever Existed.
Thanks!
