### ISSUE TITLE
Add Latex and BibTex to language identifiers

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-docs#909]
_From @pmateusz on March 28, 2017 11:30_

Contribute to the doc by adding language identifiers for Latex and BibTex: https://code.visualstudio.com/docs/languages/identifiers

_Copied from original issue: Microsoft/vscode#23399_

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/312a4348a3e20012754aac6fa48bfa82d8892de5
