### ISSUE TITLE
Page not found after clicking the Edit button for doc

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-docs#910]
_From @pmateusz on March 28, 2017 11:28_

- Browser: Chrome

Steps to Reproduce:
1. Login to GitHub using account not associated with Microsoft/vscode
2. Go to https://code.visualstudio.com/docs/languages/identifiers
3. Click the `Edit` button

Failure:
Got 404 for the page: https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/identifiers.md

_Copied from original issue: Microsoft/vscode#23398_

**Comment by aeschli** [comment]
@gregvanl I look like the list of language identifiers got removed. It served as a reference not just for users but especially for extension authors. I hope you can bring it back.

**Comment by gregvanl** [comment]
@aeschli This page was removed to fix https://github.com/Microsoft/vscode-docs/issues/893. Sean thought that the in-product list was enough and would not need to be maintained.
Do you think we need a page on the website? It would help with search and also list identifiers that the user doesn't currently have installed.

**Comment by aeschli** [comment]
It's also for the many languages that we don't support out of the box. IMO we need a place where actual language ids are coordinated as to prevent multiple ids for the same language.
I know that ideally this would not be in the user doc (although also users at some point need to know about language ids), but in a API reference section.
It would also be great if we had a search function into the marketplace
