### ISSUE TITLE
Document the different options for integrating languages

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#92]
In the documentation we currently only describe the language service server using a common language protocol integration approach. We should describe the different options and their tradeoffs:
- stateful language service server common protocol, examples: PowerShell, eslint, jshint, tsliint
- stateful language service server custom protocol with a client adapter, examples: TypeScript, OmniSharp
- stateless language service, spawn a CLI language tool per request, exampes: PHP, Go_, flow_

Behind the CLI interface Go and Flow use stateful 'demon' process.

**Comment by borgdylan** [comment]
:+1:

**Comment by gregvanl** [comment]
Closing old issue. Extension ecosystem is healthy.
