### ISSUE TITLE
The updates page should also provide access to previous releases

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#93]
CC @joaomoreno @chrisdias 
External users currently have no other means to get a previous version than to build it themeselves. 

We should make previous versions available with the updates https://code.visualstudio.com/Updates.

Currently we have an informal [wiki page](https://github.com/Microsoft/vscode/wiki/Previous-Releases), but it needs to be manually updated and it is already out of date

**Comment by chrisdias** [comment]
@egamma @joaomoreno i suggest we upload binaries to https://github.com/Microsoft/vscode/releases

**Comment by joaomoreno** [comment]
Let's do it, but don't upload the binaries. Just create the releases and link to our CDN downloads in the Markdown description.

**Comment by gregvanl** [comment]
I was going to add a table at the top of each release-note topic with had the links for the different platforms. 
Would you rather we just have one releases topic with all the versions and platforms like the wiki page?

**Comment by joaomoreno** [comment]
Oh, my bad. I somehow assumed this issue was for updating https://github.com/Microsoft/vscode/releases
