### ISSUE TITLE
Mention in 1.11 release notes how to switch to the old Git SCM support

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#931]
pls see https://github.com/Microsoft/vscode/issues/24141#issuecomment-292319773

Suggest to tweak/update what we had mentioned in 1.10 https://code.visualstudio.com/updates/v1_10#_contributable-scm-providers

Suggest, that once this is done we tweet about it and point to this section.

**Comment by gregvanl** [comment]
Agreed, I thought the new SCM provider model was only enabled by default on Insiders. I'll get something in the 1.11 release notes and version control page explaining the change and how to go back.

**Comment by egamma** [comment]
Thanks! Referred to it from tweets.
