### ISSUE TITLE
Suggestion: improve the presentation of the API documentation

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#939]
_From @axefrog on October 13, 2016 2:19_

I have a hunch you guys already know this is important, but I can't see any other issues to this effect.

Is it just me, or is the [API documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api) user experience pretty awful right now? I posted this issue just now in response to trying to find out what the API has to offer with respect to some ideas I have. Key questions in mind are "is it directly capable of X" and "can I get a sense of how much additional work would be required to extend certain base features to support my ideas?"

Problems:
- It's a giant scrolling page; clumping everything together makes it hard to differentiate between different sections and judge how they relate to each other.
- There is nowhere to get a quick overview of everything the API has to offer.
- There is no obvious table of contents that I can use to quickly jump to the section I need.
- There is no clear document hierarchy.
- I can't quickly search for symbols and drill down to find what I need (other than via CTRL+F)
- It's not very readable. The typography makes everything look kind of "same-ish", so it's hard to scroll through and scan for what I need. The font sizes don't make a lot of sense with respect to representing importance of items and their relationship to the document hierarchy.
- Weird line spacing- way more space between property list items than headings and so forth. Again, scannability is an issue.

Would love to see this presented in a way that encourages better absorption and exploration of what the API has to offer, and I'm sure doing so would promote a faster-growing extension ecosystem.

![image](https://cloud.githubusercontent.com/assets/298883/19334565/13ad6778-9140-11e6-8c84-58009ad59729.png)

As an aside; "Complex Commands API" - The intro text is completely unhelpful: _"They are called complex commands because they require parameters and often return a value"_ - this is a description of almost every function in existence.

_Copied from original issue: Microsoft/vscode#13637_

**Comment by gregvanl** [comment]
_From @octref on October 13, 2016 6:53_

Thanks for the thoughtful feedback. The API doc is currently generated from https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts, and it could get some more polish to improve developer experience.

But I guess this should be moved to vscode-docs @waderyan .

**Comment by LWChris** [comment]
Without actually changing the page itself, we can get a much clearer structure with some tiny modifications to the HTML and CSS:

- Change "Variables", "Events" and "Functions" headings from `<h4>` to `<h3>`
- Introduce `.docs .body h3 { margin-top: 30px }` (copied from `.docs .body h4`)
- Change  `.docs p span.ts` from `padding: 15px` to `padding: 4px 8px`
- Change `.docs p span.ts::before` from `top: 25px` to `top: 14px`
- Change `.docs h2` from `margin-top: 30px` to `margin-top: 10px; padding-top: 20px; border-top: 1px solid silver`

Left view: current layout; right view: modified layout

![layout](https://user-images.githubusercontent.com/845152/31031162-3795f6c8-a558-11e7-8508-40b97180c572.png)

**Comment by octref** [comment]
Hi I'm working on the VSCode website now. Thanks for your feedback.

The API doc does need some more work. We have an internal repo for the website and we'll track it in there, together with a few other issues on the API page.

You should see some improvements on this page over the next month.

**Comment by axefrog** [comment]
Awesome. Looking forward to having a proper API area. The current single-page thing feels like trying to read documentation from an extremely-long printout. Are you planning on better cross-referencing and searching capabilities and dividing the API up into separate pages?

**Comment by octref** [comment]
> better cross-referencing and searching capabilities

Yes.

> dividing the API up into separate pages

Not necessarily. 

> ditch the expand/collapse thing

Will think about it.

**Comment by axefrog** [comment]
> Not necessarily.

For what it's worth, the downside of doing it all on one page is that, while you can open different hash URLs of the same page in different tabs, the back button in browsers is a bit wonky when it comes to jumping back to previous locations. As soon as you scroll away from the hash location, you can't use the back button to go back to where you were, because the anchor hash is already in the address bar. Generating separate pages makes this a lot simpler to solve. Just a thought.

**Comment by axefrog** [comment]
> Will think about it.

If you keep the expand/collapse widgets, it'd be nice to at least have a global toggle to expand/collapse everything, which would solve the problem without removing that style of presentation.
