### ISSUE TITLE
Version Control Page

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-docs#959]
We should show the other extensions i.e. Perforce, TFVC, Hg - done

And discuss in more general terms, explain how to switch providers, update the screenshots.

But we should be clear the default is Git... - done

https://code.visualstudio.com/docs/editor/versioncontrol

cc @joaomoreno

**Comment by gregvanl** [comment]
Also need to:
Remove Ctrl+P for git checkout and branch
Add pointer to introductory Git content (for example Chacon book) - this came up during doc feedback verbatim review.

**Comment by gregvanl** [comment]
Also need to update /docs landing page, see https://github.com/Microsoft/vscode-website/issues/630
