### ISSUE TITLE
Docs site is using development version of react - writes error to dev console

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-docs#960]
I don't know if this is known/expected or an oversight, but React is writing an error to the console on the docs site because it's a dev version:

![React dev](https://cloud.githubusercontent.com/assets/1078012/25447900/c83aa8b0-2aae-11e7-93b2-3fe624444d63.png)

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-website#627
