### ISSUE TITLE
The docs-nav overflow

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode-docs#963]
display height: 1080px(taskbar on)

![inked6253337d66563dba710d9eafd947c1fc_li](https://cloud.githubusercontent.com/assets/8474118/25562843/27519a6a-2dcb-11e7-8973-8e9b6e0f8dac.jpg)

one of these days
![inked923be4fc2976982e43b66bc6b1a00969_li](https://cloud.githubusercontent.com/assets/8474118/25562931/881545a8-2dcc-11e7-8e5a-de4b981be299.jpg)

**Comment by gregvanl** [comment]
I may not understand the issue. Is this https://github.com/Microsoft/vscode-website/issues/629?

**Comment by EbXpJ6bp** [comment]
Hmm I don't have a permission to access to the vscode-website. I can't refer to your issue link.

The first image shows that the user can't click hidden links without scrolling to bottom.
The second image shows items will overflow (about 4 months later).
The display height of 1080px is commonly used.

**Comment by gregvanl** [comment]
Hi @EbXpJ6bp, it is the same issue. vscode-website is our private repo for code.visualstudio.com website and is where the rendering logic lives. Closing this issue as a duplicate but we still really appreciate you taking the time to enter the issue.
